### ISSUE TITLE
Horovod 0.16.0 not building with Ubuntu 16.04

### ISSUE THREAD

**Issue by kalyc** [horovod/horovod#1001]
**Environment:**
1. Framework: (TensorFlow 0.13.1)
2. Framework version: 1.13.1
3. Horovod version: 0.16.1 / latest
4. MPI version: Tried with 3.0.2, 3.0.3, 4.0.0
5. CUDA version: 10
6. NCCL version: 2.2.13
7. Python version: 27
8. OS and version: Ubuntu 16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before? https://github.com/horovod/horovod/issues/791

2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Bug report:**
```
pip install --no-cache-dir horovod==0.16.1
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting horovod==0.16.1
  Downloading https://files.pythonhosted.org/packages/89/70/327e1ce9bee0fb8a879b98f8265fb7a41ae6d04a3ee019b2bafba8b66333/horovod-0.16.1.tar.gz (2.6MB)
    100% |████████████████████████████████| 2.6MB 74.2MB/s 
Requirement already satisfied: cffi>=1.4.0 in ./anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages (from horovod==0.16.1) (1.11.5)
Requirement already satisfied: cloudpickle in ./anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages (from horovod==0.16.1) (0.5.3)
Requirement already satisfied: psutil in ./anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages (from horovod==0.16.1) (5.4.5)
Requirement already satisfied: six in ./anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages (from horovod==0.16.1) (1.11.0)
Requirement already satisfied: pycparser in ./anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages (from cffi>=1.4.0->horovod==0.16.1) (2.18)
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /home/ubuntu/anaconda3/envs/tensorflow_p27/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-KfV1hO/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xjvitU/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/compression.py -> build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch
    creating build/lib.linux-x86_64-2.7/horovod/_keras
    copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/_keras
    copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/_keras
    creating build/lib.linux-x86_64-2.7/horovod/mxnet
    copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/mxnet
    copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-2.7/horovod/mxnet
    creating build/lib.linux-x86_64-2.7/horovod/spark
    copying horovod/spark/__init__.py -> build/lib.linux-x86_64-2.7/horovod/spark
    creating build/lib.linux-x86_64-2.7/horovod/run
    copying horovod/run/__init__.py -> build/lib.linux-x86_64-2.7/horovod/run
    copying horovod/run/run.py -> build/lib.linux-x86_64-2.7/horovod/run
    copying horovod/run/task_fn.py -> build/lib.linux-x86_64-2.7/horovod/run
    creating build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    creating build/lib.linux-x86_64-2.7/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-2.7/horovod/common
    creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-2.7/horovod/spark/driver
    copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-2.7/horovod/spark/driver
    copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-2.7/horovod/spark/driver
    copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-2.7/horovod/spark/driver
    copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-2.7/horovod/spark/driver
    creating build/lib.linux-x86_64-2.7/horovod/spark/task
    copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-2.7/horovod/spark/task
    copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-2.7/horovod/spark/task
    copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-2.7/horovod/spark/task
    creating build/lib.linux-x86_64-2.7/horovod/run/driver
    copying horovod/run/driver/driver_service.py -> build/lib.linux-x86_64-2.7/horovod/run/driver
    copying horovod/run/driver/__init__.py -> build/lib.linux-x86_64-2.7/horovod/run/driver
    creating build/lib.linux-x86_64-2.7/horovod/run/task
    copying horovod/run/task/__init__.py -> build/lib.linux-x86_64-2.7/horovod/run/task
    copying horovod/run/task/task_service.py -> build/lib.linux-x86_64-2.7/horovod/run/task
    creating build/lib.linux-x86_64-2.7/horovod/run/common
    copying horovod/run/common/__init__.py -> build/lib.linux-x86_64-2.7/horovod/run/common
    creating build/lib.linux-x86_64-2.7/horovod/run/util
    copying horovod/run/util/cache.py -> build/lib.linux-x86_64-2.7/horovod/run/util
    copying horovod/run/util/threads.py -> build/lib.linux-x86_64-2.7/horovod/run/util
    copying horovod/run/util/__init__.py -> build/lib.linux-x86_64-2.7/horovod/run/util
    copying horovod/run/util/network.py -> build/lib.linux-x86_64-2.7/horovod/run/util
    creating build/lib.linux-x86_64-2.7/horovod/run/common/service
    copying horovod/run/common/service/driver_service.py -> build/lib.linux-x86_64-2.7/horovod/run/common/service
    copying horovod/run/common/service/__init__.py -> build/lib.linux-x86_64-2.7/horovod/run/common/service
    copying horovod/run/common/service/task_service.py -> build/lib.linux-x86_64-2.7/horovod/run/common/service
    creating build/lib.linux-x86_64-2.7/horovod/run/common/util
    copying horovod/run/common/util/codec.py -> build/lib.linux-x86_64-2.7/horovod/run/common/util
    copying horovod/run/common/util/__init__.py -> build/lib.linux-x86_64-2.7/horovod/run/common/util
    copying horovod/run/common/util/secret.py -> build/lib.linux-x86_64-2.7/horovod/run/common/util
    copying horovod/run/common/util/timeout.py -> build/lib.linux-x86_64-2.7/horovod/run/common/util
    copying horovod/run/common/util/host_hash.py -> build/lib.linux-x86_64-2.7/horovod/run/common/util
    copying horovod/run/common/util/network.py -> build/lib.linux-x86_64-2.7/horovod/run/common/util
    copying horovod/run/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-2.7/horovod/run/common/util
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow/keras
    running build_ext
    gcc -pthread -B /home/ubuntu/anaconda3/envs/tensorflow_p27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/home/ubuntu/anaconda3/envs/tensorflow_p27/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/ubuntu/anaconda3/envs/tensorflow_p27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -stdlib=libc++ -mf16c -mavx -I/home/ubuntu/anaconda3/envs/tensorflow_p27/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/ubuntu/anaconda3/envs/tensorflow_p27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -I/home/ubuntu/anaconda3/envs/tensorflow_p27/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    unable to execute 'gcc': No such file or directory
    gcc -pthread -B /home/ubuntu/anaconda3/envs/tensorflow_p27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -stdlib=libc++ -I/home/ubuntu/anaconda3/envs/tensorflow_p27/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    unable to execute 'gcc': No such file or directory
    error: Unable to determine C++ compilation flags (see error above).
    
    ----------------------------------------
Command "/home/ubuntu/anaconda3/envs/tensorflow_p27/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-KfV1hO/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xjvitU/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-KfV1hO/horovod/
```

**Comment by alsrgv** [comment]
@kalyc, can you `apt install build-essential`?

**Comment by YangSN0719** [comment]
(glow) [410@mu01 openmpi-4.0.1]$ pip install horovod==0.13.8
Collecting horovod==0.13.8
  Using cached https://files.pythonhosted.org/packages/43/48/6bf4a5f04caf75da04c5d5e99a14677c40eae4e8b0608e5906c4f4049229/horovod-0.13.8.tar.gz
Requirement already satisfied: cffi>=1.4.0 in /home/410/anaconda3/lib/python3.6/site-packages (from horovod==0.13.8) (1.11.5)
Requirement already satisfied: pycparser in /home/410/anaconda3/lib/python3.6/site-packages (from cffi>=1.4.0->horovod==0.13.8) (2.18)
Building wheels for collected packages: horovod
  Running setup.py bdist_wheel for horovod ... error
  Complete output from command /home/410/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3sjwyld1/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-21u6byo2 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/horovod
  copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
  creating build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
  copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
  creating build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
  creating build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
  creating build/lib.linux-x86_64-3.6/horovod/common
  copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
  creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
  copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
  creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
  copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
  running build_ext
  gcc -pthread -B /home/410/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/410/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  gcc -pthread -shared -B /home/410/anaconda3/compiler_compat -L/home/410/anaconda3/lib -Wl,-rpath=/home/410/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
  INFO: Unable to build TensorFlow plugin, will skip it.
  
  Traceback (most recent call last):
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 53, in check_tf_version
      if tf.__version__ < '1.1.0':
  AttributeError: module 'tensorflow' has no attribute '__version__'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 561, in build_extensions
      abi_compile_flags = build_tf_extension(self, options)
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 414, in build_tf_extension
      check_tf_version()
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 63, in check_tf_version
      'Your TensorFlow version is outdated.  Horovod requires tensorflow>=1.1.0')
  distutils.errors.DistutilsPlatformError: Your TensorFlow version is outdated.  Horovod requires tensorflow>=1.1.0
  
  INFO: Unable to build PyTorch plugin, will skip it.
  
  Traceback (most recent call last):
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 444, in check_torch_import
      import torch
  ModuleNotFoundError: No module named 'torch'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 572, in build_extensions
      build_torch_extension(self, options, abi_compile_flags)
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 492, in build_torch_extension
      check_torch_import()
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 447, in check_torch_import
      'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
  distutils.errors.DistutilsPlatformError: import torch failed, is it installed?
  
  Traceback (most recent call last):
    File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 444, in check_torch_import
      import torch
  ModuleNotFoundError: No module named 'torch'
  
  
  error: Neither TensorFlow nor PyTorch plugins were built. See errors above.
  
  ----------------------------------------
  Failed building wheel for horovod
  Running setup.py clean for horovod
Failed to build horovod
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /home/410/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3sjwyld1/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-272dkuuk/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    running build_ext
    gcc -pthread -B /home/410/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/410/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /home/410/anaconda3/compiler_compat -L/home/410/anaconda3/lib -Wl,-rpath=/home/410/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    INFO: Unable to build TensorFlow plugin, will skip it.
    
    Traceback (most recent call last):
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 53, in check_tf_version
        if tf.__version__ < '1.1.0':
    AttributeError: module 'tensorflow' has no attribute '__version__'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 561, in build_extensions
        abi_compile_flags = build_tf_extension(self, options)
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 414, in build_tf_extension
        check_tf_version()
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 63, in check_tf_version
        'Your TensorFlow version is outdated.  Horovod requires tensorflow>=1.1.0')
    distutils.errors.DistutilsPlatformError: Your TensorFlow version is outdated.  Horovod requires tensorflow>=1.1.0
    
    INFO: Unable to build PyTorch plugin, will skip it.
    
    Traceback (most recent call last):
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 444, in check_torch_import
        import torch
    ModuleNotFoundError: No module named 'torch'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 572, in build_extensions
        build_torch_extension(self, options, abi_compile_flags)
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 492, in build_torch_extension
        check_torch_import()
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 447, in check_torch_import
        'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
    distutils.errors.DistutilsPlatformError: import torch failed, is it installed?
    
    Traceback (most recent call last):
      File "/tmp/pip-install-3sjwyld1/horovod/setup.py", line 444, in check_torch_import
        import torch
    ModuleNotFoundError: No module named 'torch'
    
    
    error: Neither TensorFlow nor PyTorch plugins were built. See errors above.
    
    ----------------------------------------
Command "/home/410/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3sjwyld1/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-272dkuuk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-3sjwyld1/horovod/

**Comment by abditag2** [comment]
@YangSN0719 you would need to install tensorflow or pytorch in order to use horovod.
