### ISSUE TITLE
Static website for documentation

### ISSUE THREAD

**Issue by IgorWilbert** [horovod/horovod#1007]
**Is your feature request related to a problem? Please describe.**
Currently, the documentation seems to be present only in `.md` files. A more user friendly way to present it probably would attract more contributors, and in some situations it is easier to search it as a static website. 

**Describe the solution you'd like**
I would like to have a place to show the documentation organized in a logical and straightforward way, with a pleasant user interface. It would be awesome to show the examples as code snippets as well. Uber Open source has a great number of examples of this, such as [Baseui](https://baseweb.design/) and [Petastorm](https://petastorm.readthedocs.io/en/latest/). Right now the focus would be documentation, but we could also add a showcase section incorporating the content from [here](https://eng.uber.com/horovod/) and [here](https://www.slideshare.net/AlexanderSergeev4/horovod-distributed-tensorflow-made-easy)

**Describe alternatives you've considered**
Since this a project in python, I guess the way to go is transfer the docs content from `.md` file into `.rst` files, just like in Petastorm. But if we decide to make it more visually appealing, like [deck.gl](https://deck.gl/#/), it would be possible to make a static website with react, for example.

**Additional context**
I would like to work on this issue if it happens to be relevant. I guess it would be possible to make at least a basic version of it in a few weeks.

**Comment by alsrgv** [comment]
@IgorWilbert, it's a great suggestion, and something we wanted to do for a while now.  Thanks for volunteering to improve the docs!

After a quick survey, I found Sphinx + ReadTheDocs to be a combination that can be kick-started pretty quickly, similar to what the [Petastorm](https://petastorm.readthedocs.io/en/latest/) project did. I've started kicking tires here - https://horovod.readthedocs.io/en/latest/index.html (branch https://github.com/horovod/horovod/tree/readthedocs).

So far the largest annoyance seems to be the fact that Sphinx autodoc requires ability to import modules, and modules cannot be imported unless Horovod is properly installed.  ReadTheDocs runs in a bare-bone container that we can't install Horovod in, and so we need to set up quick a bit of [mockery](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules).

Do you have any better suggestions?  Otherwise, my plan is to get a starter set up going, and open the doors to pull requests :-)

**Comment by IgorWilbert** [comment]
After a quick search, I believe Sphinx is probably the best option. [Pycco](https://pycco-docs.github.io/pycco/) looks too basic and [Doxygen](www.doxygen.nl) is not as much specialized. I'll think about what can be done with the mockery. Let me know your thoughts about where in the docs should we begin. Thanks!

**Comment by alsrgv** [comment]
PR #1010. Submitted a couple of enhancements to Sphinx as well: https://github.com/sphinx-doc/sphinx/pull/6288, https://github.com/sphinx-doc/sphinx/pull/6289. Hope they get accepted. 🤞

**Comment by alsrgv** [comment]
@IgorWilbert, feel free to start sending PRs.  We could start by fixing API docs, currently they have certain members that should not be public and docstrings are misparsed in certain cases.

Building the docs locally is super easy:
```
$ cd docs
$ pip install -r requirements.txt
$ make clean && make html
$ open _build/html/index.html
```

**Comment by IgorWilbert** [comment]
Thanks @alsrgv ! However, I have an issue. At the moment I am forced to use Windows OS, which does not come with the 'make' or 'open' commands. I have looked for [some ways](https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows/54086635) to overcome it, but if you could provide me a Windows equivalent for starting the documentation without installing anything else I would be very glad!

**Comment by alsrgv** [comment]
@IgorWilbert, can you try going [this route](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?

**Comment by IgorWilbert** [comment]
@alsrgv thanks, but like I said, I'd rather not to because I would have to install Linux OS on top of Windows OS. I had similar issues with baseui documetation and [a few changes](https://github.com/uber-web/baseui/pull/1134/files) in config files was enough to fix [it](https://github.com/uber-web/baseui/issues/1111). Isn't it the same case here? If not, I'll do what you suggested, thanks!

**Comment by alsrgv** [comment]
@IgorWilbert, assuming you have Python 3.x & Pip installed, you may be able to do:
```
$ cd docs
$ pip install -r requirements.txt
$ make.bat
[open _build/html/index.html]
```

**Comment by IgorWilbert** [comment]
Thanks! In fact, the following worked:
`$ cd docs
$ pip install -r requirements.txt
$ make clean && make html
$ start _build/html/index.html`

**Comment by alsrgv** [comment]
@IgorWilbert, great!  Yes, I believe that you have to rerun make to have Sphinx rebuild html pages.  Looking forward to PRs from you.
