### ISSUE TITLE
AttributeError: module 'horovod.mxnet' has no attribute 'DistributedTrainer'(mxnet_mnist.py)

### ISSUE THREAD

**Issue by lakshmiumenon** [horovod/horovod#1016]
**Environment:**
1. Framework: (MXNet)
2. Framework version:1.5.0
3. Horovod version:0.16.1
4. MPI version:OpenMPI 3.1.3
5. CUDA version:
6. NCCL version:
7. Python version:3.7.3
8. OS and version:Ubuntu 18.04

Hi,
  When I tried to run the mxnet_mnist.py I am getting the following error:
AttributeError: module 'horovod.mxnet' has no attribute 'DistributedTrainer'
PMIX ERROR: NO-PERMISSIONS in file gds_dstore.c at line 702

Thanks,
Lakshmi.

**Comment by abditag2** [comment]
what flags did you use for installing mxnet? 
You will need these flags
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_MXNET=1 pip install horovod

If you are using GPU, make sure to follow this doc: https://github.com/horovod/horovod/blob/master/docs/gpus.md

**Comment by lakshmiumenon** [comment]
> what flags did you use for installing mxnet?
> You will need these flags
> HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_MXNET=1 pip install horovod
> 
> If you are using GPU, make sure to follow this doc: https://github.com/horovod/horovod/blob/master/docs/gpus.md

I am not using GPU.

I have used the following command to install horovod:
HOROVOD_WITH_MXNET=1 pip install -v --no-cache-dir horovod

**Comment by WarBean** [comment]
@lakshmiumenon After checking the source code, I found the latest release version (0.16.1) doesn't contain `horovod.mxnet.DistributedTrainer` at all. Looks like the example code is only compatible with the master branch. Installing horovod from the latest source code rather than pip may fix the issue.

**Comment by lakshmiumenon** [comment]
> @lakshmiumenon After checking the source code, I found the latest release version (0.16.1) doesn't contain `horovod.mxnet.DistributedTrainer` at all. Looks like the example code is only compatible with the master branch. Installing horovod from the latest source code rather than pip may fix the issue.

Could you please provide any reference for building horovod from source for mxnet?

**Comment by alsrgv** [comment]
@lakshmiumenon, in your normal steps just replace `[flags] pip install --no-cache-dir horovod` with `[flags] pip install --no-cache-dir git+https://github.com/horovod/horovod`

**Comment by lakshmiumenon** [comment]
> @lakshmiumenon, in your normal steps just replace `[flags] pip install --no-cache-dir horovod` with `[flags] pip install --no-cache-dir git+https://github.com/horovod/horovod`

@alsrgv  Thank you..Will tryout to build horovod from source.

**Comment by lakshmiumenon** [comment]
> > @lakshmiumenon, in your normal steps just replace `[flags] pip install --no-cache-dir horovod` with `[flags] pip install --no-cache-dir git+https://github.com/horovod/horovod`
> 
> @alsrgv Thank you..Will try to build horovod from source.

@alsrgv  Thank you so much...source build of horovod worked and the issue got resolved.
