### ISSUE TITLE
horovodrun throws error

### ISSUE THREAD

**Issue by sudhagar2k5** [horovod/horovod#1021]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): tensorflow 
2. Framework version:1.13.1
3. Horovod version:--
4. MPI version: ---  openmpi-4.0.1
5. CUDA version: CUDA 9.0
6. NCCL version: nccl-repo-ubuntu1604-2.4.2-ga-cuda9.0_1-1_amd64
7. Python version: 3.5.2
8. OS and version: ubuntu 16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

when i run bellow command iam getting error.

(env) sh-4.3# horovodrun -np 3 -H hostname:3 python keras_mnist.py

[ozd2484u:04289] Warning: could not find environment variable "PS1"
[ozd2484u:04289] Warning: could not find environment variable "OLDPWD"
bash: orted: command not found
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).

how to fix this?

**Comment by alsrgv** [comment]
@sudhagar2k5, do you have Open MPI 4.0.0+ installed on `hostname`?
