### ISSUE TITLE
Timeline.json is too large to be loaded in Chrome

### ISSUE THREAD

**Issue by deargqy** [horovod/horovod#1022]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 1.13.1
3. Horovod version:0.16.1
4. MPI version:4.0.0
5. CUDA version:9.0
6. NCCL version:2.3.7-1
7. Python version:3.6.7
8. OS and version:16.04

**Your question:**
I used Tensorflow + Horovod to train the imagenet with 4 GPU and I found the timeline I saved for 1 epoch is too large to be loaded in Chrome. To be more specific, the timeline.json file is about 400M for one epoch, and the Chrome will crash if I load the file.

Thanks very much.

**Comment by alsrgv** [comment]
@deargqy, can you terminate your training after a few dozens of iterations?  You can also edit timeline and truncate it at 1% or 10% depending on the total size.

**Comment by deargqy** [comment]
Thanks for your reply.

May I ask how can I truncate the timeline file? Do I need to truncate the file by certain rules or just do it according to the size?

**Comment by alsrgv** [comment]
@deargqy, you can truncate on a line break after a certain size.
