### ISSUE TITLE
how to monitor the job execution? 

### ISSUE THREAD

**Issue by sudhagar2k5** [horovod/horovod#1023]
how to monitor the job progress in each node after submitting the job?
Hrorovod required Slurm?

**Comment by alsrgv** [comment]
@sudhagar2k5, you can just write job progress on stdout, and mpirun will collect the output of all nodes to the node running mpirun.

**Comment by sudhagar2k5** [comment]
We run multiple jobs from different users. So we may need to monitor the
progress. Can we use any resource alocator for this purpose?

**Comment by alsrgv** [comment]
@sudhagar2k5, sure - you can use Slurm, Kubernetes, or Spark clusters to run Horovod jobs.

**Comment by sudhagar2k5** [comment]
We are plan to use slurm. But  I need distribute a single job on multi node
how can I do this?

**Comment by alsrgv** [comment]
@sudhagar2k5, Slurm is able to allocate resources from multiple nodes for a single job.

**Comment by sudhagar2k5** [comment]
do you have any simple example? for this setup.

**Comment by alsrgv** [comment]
@sudhagar2k5, no - we don't have Slurm set up, but I assume any Slurm reference guide should work.
