### ISSUE TITLE
Storing the final model

### ISSUE THREAD

**Issue by sudhagar2k5** [horovod/horovod#1025]
iam using keras_mnist_advanced.py example. Executing it in two nodes, so i have number of checkpoint files in both workers. Now i want to export a single model file? how can i do this in keras? any sample code ?

**Comment by abditag2** [comment]
Exporting the model is the same way with or without Horovod. Search on Google for how to export a model using Keras and add that to your code. Both nodes will save their copy of model into their machines and those copies will be exactly identical. You can get the model from any of them.
