### ISSUE TITLE
Install Horovod with pytorch 1.0.1 failed

### ISSUE THREAD

**Issue by mathppp** [horovod/horovod#1026]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.0.1.post2
3. Horovod version: 0.16.1
4. MPI version: 3.1.4rc1
5. CUDA version: 10.0
6. NCCL version: 2.3.7
7. Python version: 3.5.2
8. OS and version: ubuntu 16.04.5 LST

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
I have installed the horovod and pytorch by the following process:

# upgrade pip
$ curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

# Install torch
$ pip install torch torchvision

# update Horovod ( without HOROVOD_WITH_MXNET=1 )
$ ldconfig /usr/local/cuda-10.0/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir --upgrade --force-reinstall  horovod && \
    ldconfig

# print the pyTorch version
$ python -c "import torch; print(torch.__version__)"

# print the version of TensorFlow
$ python -c 'import tensorflow as tf; print(tf.__version__)'

the above processes are success to install and testing.

But I try to run the horovod example "pytorch_synthetic_benchmark.py".
command: mpirun -np 2 python pytorch_synthetic_benchmark.py
The error message show the below: 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/horovod/torch/__init__.py", line 24, in <module>
    __file__, 'mpi_lib_v2')
  File "/usr/local/lib/python3.5/dist-packages/horovod/common/__init__.py", line 48, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pytorch_synthetic_benchmark.py", line 9, in <module>
    import horovod.torch as hvd
  File "/usr/local/lib/python3.5/dist-packages/horovod/torch/__init__.py", line 27, in <module>
    __file__, 'mpi_lib', '_mpi_lib')
  File "/usr/local/lib/python3.5/dist-packages/horovod/common/__init__.py", line 48, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by alsrgv** [comment]
@mathppp, can you add `HOROVOD_WITH_PYTORCH=1` to your installation flags, reinstall & share the full installation log?

**Comment by johndpope** [comment]
fixed things for me - thanks

```
 -  HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir --upgrade --force-reinstall horovod &&
ldconfig
```
