### ISSUE TITLE
which communications library select （Openmpi or nccl2） when run horovod ？

### ISSUE THREAD

**Issue by mdztravelling** [horovod/horovod#1027]
**Environment:**
1. Framework:  PyTorch
2. Framework version: 0.4.1
3. Horovod version: 0.16.0
4. MPI version:  3.1.1
5. CUDA version: 8.0
6. NCCL version: 2.2.12
7. Python version: 2.7.14
8. OS and version: CentOS release 6.3  
GPU:  P40

Horovod is great work! 
My question is which communications library（Openmpi or nccl2） select  when run horovod ？which one performing is better or more efficient? 
what is the principle of choice in different network environments (TCP or IB)? And what is principle of choice on multi-node gpu or single-node gpu ?

**Comment by abditag2** [comment]
If you are using GPUs, NCCL is usually going to get you a better performance. Multiple GPUs on the single node will perform faster than multiple GPUs across the network. However, if you need more GPUs than what is available on one machine, you will need to use multiple GPUs over the network. 

@alsrgv can talk about TCP vs IB.

**Comment by mdztravelling** [comment]
appreciate the help in answering the question. @abditag2
