### ISSUE TITLE
How to suppress Read -1 stderr error when using horovodrun 

### ISSUE THREAD

**Issue by vbvg2008** [horovod/horovod#1029]
Whenever I am using horovodrun on multi-gpu system, I get lots of stderr message like:
`
[1,0]<stderr>:[939debe34dff:00468] Read -1, expected 6441, errno = 1
`
1. what is the root cause of this message? does it from MPI or Horovod? 

2. Is there a way to disable these messages when calling horovodrun?  I know #503 offers a workaround, but I am just wondering if it can be done on the horovod API itself.

**Comment by alsrgv** [comment]
@vbvg2008, are you running in Docker containers by any chance?  If so, our [Docker docs](https://github.com/horovod/horovod/blob/master/docs/docker.md#running-on-a-single-machine) suggest running in the privileged mode.

**Comment by vbvg2008** [comment]
@alsrgv Thanks for the reply, by any chance you know the cause of that error message?

**Comment by alsrgv** [comment]
@vbvg2008, we didn't dig it up too much.  I'm suspecting it's caused by some operation inside NCCL or MPI.

**Comment by vbvg2008** [comment]
@alsrgv Thanks for your reply!

**Comment by ChaiBapchya** [comment]
Can we open this issue? Since we don't know how it can be suppressed yet?
At times, we don't have the ability to set `privileged` flag due to security reasons.

**Comment by vbvg2008** [comment]
re-opening this issue to avoid duplicating issues.     I think this issue is worth looking into for docker users.

**Comment by ChaiBapchya** [comment]
duplicate of https://github.com/horovod/horovod/issues/653

**Comment by vycezhong** [comment]
add ` 2> /dev/null` to the end of your command. it will disable all stderr messages.
