### ISSUE TITLE
error:  pip install --no-cache-dir horovod

### ISSUE THREAD

**Issue by haif-liu** [horovod/horovod#1033]
ERROR: Complete output from command /root/anaconda3/envs/....../bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-oupijrb7/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hak6d9us --python-tag cp36:
ERROR: running bdist_wheel
ERROR: Command "/root/anaconda3/envs/....../bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-96xswj95/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-32i5_eh8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-96xswj95/horovod/

**Environment:**
1. Framework: (TensorFlow)
2. Framework version: gpu-1.13
3. Horovod version:
4. MPI version: 4.0.0
5. CUDA version: 10.0
6. NCCL version: 
7. Python version: 3.6
8. OS and version: ubuntu 18

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

**Comment by alsrgv** [comment]
@haif-liu, can you share full installation log?
