### ISSUE TITLE
error:  import horovod.tensorflow

### ISSUE THREAD

**Issue by haif-liu** [horovod/horovod#1034]
import horovod.tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 35, in <module>
    check_extension('horovod.tensorflow', 'HOROVOD_WITH_TENSORFLOW', __file__, 'mpi_lib')
  File "/root/anaconda3/lib/python3.6/site-packages/horovod/common/__init__.py", line 48, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.

**Environment:**
1. Framework: (TensorFlowt)
2. Framework version: gpu-1.13
3. Horovod version: 0.16
4. MPI version: 
5. CUDA version: 10.0
6. NCCL version:
7. Python version: 3.6
8. OS and version: ubuntu 18 

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

**Comment by alsrgv** [comment]
@haif-liu, can you install Horovod with `HOROVOD_WITH_TENSORFLOW=1` and share the full installation log, as the error message requests?

**Comment by cklsoft** [comment]
root@test:/root/horovod# HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/usr/local/cuda-10.1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 python setup.py install
running install
running bdist_egg
running egg_info
writing horovod.egg-info/PKG-INFO
writing dependency_links to horovod.egg-info/dependency_links.txt
writing requirements to horovod.egg-info/requires.txt
writing top-level names to horovod.egg-info/top_level.txt
reading manifest file 'horovod.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '.eggs'
warning: no previously-included files found matching 'third_party/eigen/Eigen/src/IterativeSolvers/*'
writing manifest file 'horovod.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.so
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_link_flags.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.5/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_link_flags.so
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/local/cuda-10.1/include -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cuda.o -L/usr/local/cuda-10.1/lib -L/usr/local/cuda-10.1/lib64 -lcudart -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.so
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/include -I/usr/local/cuda-10.1/include -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_nccl.cc -o build/temp.linux-x86_64-3.5/test_compile/test_nccl.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_nccl.o -L/usr/local/cuda-10.1/lib -L/usr/local/cuda-10.1/lib64 -lnccl -o build/temp.linux-x86_64-3.5/test_compile/test_nccl.so
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/horovod
creating build/bdist.linux-x86_64/egg/horovod/common
copying build/lib.linux-x86_64-3.5/horovod/common/__init__.py -> build/bdist.linux-x86_64/egg/horovod/common
copying build/lib.linux-x86_64-3.5/horovod/common/util.py -> build/bdist.linux-x86_64/egg/horovod/common
copying build/lib.linux-x86_64-3.5/horovod/common/basics.py -> build/bdist.linux-x86_64/egg/horovod/common
creating build/bdist.linux-x86_64/egg/horovod/tensorflow
copying build/lib.linux-x86_64-3.5/horovod/tensorflow/mpi_ops.py -> build/bdist.linux-x86_64/egg/horovod/tensorflow
copying build/lib.linux-x86_64-3.5/horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/horovod/tensorflow
creating build/bdist.linux-x86_64/egg/horovod/tensorflow/keras
copying build/lib.linux-x86_64-3.5/horovod/tensorflow/keras/__init__.py -> build/bdist.linux-x86_64/egg/horovod/tensorflow/keras
copying build/lib.linux-x86_64-3.5/horovod/tensorflow/keras/callbacks.py -> build/bdist.linux-x86_64/egg/horovod/tensorflow/keras
copying build/lib.linux-x86_64-3.5/horovod/tensorflow/__init__.py -> build/bdist.linux-x86_64/egg/horovod/tensorflow
copying build/lib.linux-x86_64-3.5/horovod/tensorflow/compression.py -> build/bdist.linux-x86_64/egg/horovod/tensorflow
copying build/lib.linux-x86_64-3.5/horovod/tensorflow/util.py -> build/bdist.linux-x86_64/egg/horovod/tensorflow
creating build/bdist.linux-x86_64/egg/horovod/keras
copying build/lib.linux-x86_64-3.5/horovod/keras/__init__.py -> build/bdist.linux-x86_64/egg/horovod/keras
copying build/lib.linux-x86_64-3.5/horovod/keras/callbacks.py -> build/bdist.linux-x86_64/egg/horovod/keras
creating build/bdist.linux-x86_64/egg/horovod/torch
copying build/lib.linux-x86_64-3.5/horovod/torch/mpi_ops.py -> build/bdist.linux-x86_64/egg/horovod/torch
creating build/bdist.linux-x86_64/egg/horovod/torch/mpi_lib_impl
copying build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl/__init__.py -> build/bdist.linux-x86_64/egg/horovod/torch/mpi_lib_impl
creating build/bdist.linux-x86_64/egg/horovod/torch/mpi_lib
copying build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib/__init__.py -> build/bdist.linux-x86_64/egg/horovod/torch/mpi_lib
copying build/lib.linux-x86_64-3.5/horovod/torch/__init__.py -> build/bdist.linux-x86_64/egg/horovod/torch
copying build/lib.linux-x86_64-3.5/horovod/torch/compression.py -> build/bdist.linux-x86_64/egg/horovod/torch
copying build/lib.linux-x86_64-3.5/horovod/__init__.py -> build/bdist.linux-x86_64/egg/horovod
creating build/bdist.linux-x86_64/egg/horovod/spark
creating build/bdist.linux-x86_64/egg/horovod/spark/driver
copying build/lib.linux-x86_64-3.5/horovod/spark/driver/__init__.py -> build/bdist.linux-x86_64/egg/horovod/spark/driver
copying build/lib.linux-x86_64-3.5/horovod/spark/driver/job_id.py -> build/bdist.linux-x86_64/egg/horovod/spark/driver
copying build/lib.linux-x86_64-3.5/horovod/spark/driver/driver_service.py -> build/bdist.linux-x86_64/egg/horovod/spark/driver
copying build/lib.linux-x86_64-3.5/horovod/spark/driver/mpirun_rsh.py -> build/bdist.linux-x86_64/egg/horovod/spark/driver
copying build/lib.linux-x86_64-3.5/horovod/spark/__init__.py -> build/bdist.linux-x86_64/egg/horovod/spark
creating build/bdist.linux-x86_64/egg/horovod/spark/task
copying build/lib.linux-x86_64-3.5/horovod/spark/task/task_service.py -> build/bdist.linux-x86_64/egg/horovod/spark/task
copying build/lib.linux-x86_64-3.5/horovod/spark/task/mpirun_exec_fn.py -> build/bdist.linux-x86_64/egg/horovod/spark/task
copying build/lib.linux-x86_64-3.5/horovod/spark/task/__init__.py -> build/bdist.linux-x86_64/egg/horovod/spark/task
creating build/bdist.linux-x86_64/egg/horovod/run
creating build/bdist.linux-x86_64/egg/horovod/run/common
creating build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/settings.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/codec.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/env.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/__init__.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/host_hash.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/network.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/timeout.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/secret.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/util/safe_shell_exec.py -> build/bdist.linux-x86_64/egg/horovod/run/common/util
copying build/lib.linux-x86_64-3.5/horovod/run/common/__init__.py -> build/bdist.linux-x86_64/egg/horovod/run/common
creating build/bdist.linux-x86_64/egg/horovod/run/common/service
copying build/lib.linux-x86_64-3.5/horovod/run/common/service/task_service.py -> build/bdist.linux-x86_64/egg/horovod/run/common/service
copying build/lib.linux-x86_64-3.5/horovod/run/common/service/__init__.py -> build/bdist.linux-x86_64/egg/horovod/run/common/service
copying build/lib.linux-x86_64-3.5/horovod/run/common/service/driver_service.py -> build/bdist.linux-x86_64/egg/horovod/run/common/service
creating build/bdist.linux-x86_64/egg/horovod/run/util
copying build/lib.linux-x86_64-3.5/horovod/run/util/cache.py -> build/bdist.linux-x86_64/egg/horovod/run/util
copying build/lib.linux-x86_64-3.5/horovod/run/util/__init__.py -> build/bdist.linux-x86_64/egg/horovod/run/util
copying build/lib.linux-x86_64-3.5/horovod/run/util/network.py -> build/bdist.linux-x86_64/egg/horovod/run/util
copying build/lib.linux-x86_64-3.5/horovod/run/util/threads.py -> build/bdist.linux-x86_64/egg/horovod/run/util
copying build/lib.linux-x86_64-3.5/horovod/run/task_fn.py -> build/bdist.linux-x86_64/egg/horovod/run
creating build/bdist.linux-x86_64/egg/horovod/run/driver
copying build/lib.linux-x86_64-3.5/horovod/run/driver/__init__.py -> build/bdist.linux-x86_64/egg/horovod/run/driver
copying build/lib.linux-x86_64-3.5/horovod/run/driver/driver_service.py -> build/bdist.linux-x86_64/egg/horovod/run/driver
copying build/lib.linux-x86_64-3.5/horovod/run/__init__.py -> build/bdist.linux-x86_64/egg/horovod/run
creating build/bdist.linux-x86_64/egg/horovod/run/task
copying build/lib.linux-x86_64-3.5/horovod/run/task/task_service.py -> build/bdist.linux-x86_64/egg/horovod/run/task
copying build/lib.linux-x86_64-3.5/horovod/run/task/__init__.py -> build/bdist.linux-x86_64/egg/horovod/run/task
copying build/lib.linux-x86_64-3.5/horovod/run/run.py -> build/bdist.linux-x86_64/egg/horovod/run
creating build/bdist.linux-x86_64/egg/horovod/_keras
copying build/lib.linux-x86_64-3.5/horovod/_keras/__init__.py -> build/bdist.linux-x86_64/egg/horovod/_keras
copying build/lib.linux-x86_64-3.5/horovod/_keras/callbacks.py -> build/bdist.linux-x86_64/egg/horovod/_keras
creating build/bdist.linux-x86_64/egg/horovod/mxnet
copying build/lib.linux-x86_64-3.5/horovod/mxnet/mpi_ops.py -> build/bdist.linux-x86_64/egg/horovod/mxnet
copying build/lib.linux-x86_64-3.5/horovod/mxnet/__init__.py -> build/bdist.linux-x86_64/egg/horovod/mxnet
byte-compiling build/bdist.linux-x86_64/egg/horovod/common/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/common/util.py to util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/common/basics.py to basics.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/tensorflow/mpi_ops.py to mpi_ops.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/tensorflow/keras/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/tensorflow/keras/callbacks.py to callbacks.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/tensorflow/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/tensorflow/compression.py to compression.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/tensorflow/util.py to util.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/keras/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/keras/callbacks.py to callbacks.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/torch/mpi_ops.py to mpi_ops.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/torch/mpi_lib_impl/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/torch/mpi_lib/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/torch/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/torch/compression.py to compression.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/spark/driver/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/spark/driver/job_id.py to job_id.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/spark/driver/driver_service.py to driver_service.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/spark/driver/mpirun_rsh.py to mpirun_rsh.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/spark/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/spark/task/task_service.py to task_service.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/spark/task/mpirun_exec_fn.py to mpirun_exec_fn.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/spark/task/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/settings.py to settings.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/codec.py to codec.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/env.py to env.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/host_hash.py to host_hash.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/network.py to network.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/timeout.py to timeout.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/secret.py to secret.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/util/safe_shell_exec.py to safe_shell_exec.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/service/task_service.py to task_service.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/service/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/common/service/driver_service.py to driver_service.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/util/cache.py to cache.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/util/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/util/network.py to network.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/util/threads.py to threads.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/task_fn.py to task_fn.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/driver/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/driver/driver_service.py to driver_service.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/task/task_service.py to task_service.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/task/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/run/run.py to run.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/_keras/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/_keras/callbacks.py to callbacks.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/mxnet/mpi_ops.py to mpi_ops.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/horovod/mxnet/__init__.py to __init__.cpython-35.pyc
creating stub loader for horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/horovod/tensorflow/mpi_lib.py to mpi_lib.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.5/horovodrun -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/horovodrun to 755
copying horovod.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying horovod.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying horovod.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying horovod.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying horovod.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying horovod.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/horovod-0.16.1-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing horovod-0.16.1-py3.5-linux-x86_64.egg
creating /usr/local/lib/python3.5/dist-packages/horovod-0.16.1-py3.5-linux-x86_64.egg
Extracting horovod-0.16.1-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/dist-packages
Adding horovod 0.16.1 to easy-install.pth file
Installing horovodrun script to /usr/local/bin

Installed /usr/local/lib/python3.5/dist-packages/horovod-0.16.1-py3.5-linux-x86_64.egg
Processing dependencies for horovod==0.16.1
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for psutil==5.6.0
Best match: psutil 5.6.0
Adding psutil 5.6.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for cloudpickle==0.8.0
Best match: cloudpickle 0.8.0
Processing cloudpickle-0.8.0-py3.5.egg
cloudpickle 0.8.0 is already the active version in easy-install.pth

Using /opt/tensorflow/third_party/horovod/.eggs/cloudpickle-0.8.0-py3.5.egg
Finished processing dependencies for horovod==0.16.1
root@test:/root/horovod# python
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod.tensorflow as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kunlong.ckl/horovod/horovod/tensorflow/__init__.py", line 25, in <module>
    check_extension('horovod.tensorflow', 'HOROVOD_WITH_TENSORFLOW', __file__, 'mpi_lib')
  File "/home/kunlong.ckl/horovod/horovod/common/util.py", line 46, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.

@alsrgv

**Comment by alsrgv** [comment]
@cklsoft, can you try using Horovod outside the source code directory?  In your error, it was using Horovod from the source code directory which does not have built binaries - they're installed in the system location.

**Comment by ThrowMeForALoop** [comment]
I have had same problem.
