### ISSUE TITLE
Horovod on multi-GPUs of single machine is slow  than single GPU

### ISSUE THREAD

**Issue by zhanglistar** [horovod/horovod#1036]
**Environment:**
1. Framework: TensorFlow
2. Framework version:  1.13.1
3. Horovod version:  0.16.1 
4. MPI version: (Open MPI) 4.0.0
5. CUDA version: 10.0.130
6. NCCL version:2.3.7
7. Python version: 3.6.7 
8. OS and version:18.04.2

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
no, not hang
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?
yes

**Bug report:**
I am running deepfm using horovod. But it's thoughput is about 1/2 of single GPU when I use 2 GPUs. On single GPU card, about 5second/200batch, while on 2 GPU cards, about 20second/200batch. And I checked timeline, found that mpi_allgather is too slow on indexedslices, Here is the timeline file.

[2.txt](https://github.com/horovod/horovod/files/3130869/2.txt)

**Comment by zhanglistar** [comment]
Here is time on single gpu:
[1,0]<stderr>:2019-04-30 11:13:56,221 - train - INFO - Updates: 200, Loss: 0.5591733747720719, Duration: 5.415455  
Here is time on 2 gpu of same machine:
[1,0]<stderr>:2019-04-30 11:13:11,772 - train - INFO - Updates: 1600, Loss: nan, Duration: 18.929318

**Comment by abditag2** [comment]
Have you installed NCCL? If so, make sure you have enabled peer 2 peer and shared memory flags.

**Comment by zhanglistar** [comment]
There maybe exists some error that I have to double check.

**Comment by zhanglistar** [comment]
> Have you installed NCCL? If so, make sure you have enabled peer 2 peer and shared memory flags.

The same as issue 330

**Comment by alsrgv** [comment]
@zhanglistar, is it feasible to make batches bigger locally?  40 batches per second requires low latency networking, like RoCE or InfiniBand.  Even then, it may not be enough.
