### ISSUE TITLE
what is the order of processes used in hvd.allgather()? 

### ISSUE THREAD

**Issue by XuesongYang** [horovod/horovod#1037]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.12
3. Horovod version: 0.16.1
4. MPI version: 3.1.0
5. CUDA version: 9.0
6. NCCL version: 2.2.13
7. Python version: 3.6.6
8. OS and version: rhel fedora 2018.03

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/running.md)? No
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)? No

**Your question:**
Is the order of allgathered values from multiple GPUs random, or deterministic? If random, how to get a list of GPU IDs in order? If deterministic, I woud assume the list of GPU IDs in order should be `[0, 1, 2, 3, ...]`. For example, let's say:
```
for (x, y) in dataset:
    x_gather = hvd.allgather(x)
    y_gather = hvd.allgather(y)

for (xx, yy) in zip(x_gather.numpy(), y_gather.numpy()):
    print(xx)
    print(yy)
```
Do the element `xx` in `x_gather.numpy()` and  `yy` in `y_gather.numpy()` come from the same GPU id? My use case needs to gather two different evaluation metrics, such as predicted class IDs and truth class IDs. It needs to make sure that the predicted ID and truth ID are from the same example. Thanks.

**Comment by alsrgv** [comment]
@XuesongYang, they should be ordered by ranks.  Please let us know if you find that it's not the case.

**Comment by XuesongYang** [comment]
Thanks. My tests showed that it is ordered by ranks, but just confirmed.
