### ISSUE TITLE
Errors when building in development mode

### ISSUE THREAD

**Issue by kit1980** [horovod/horovod#1039]
When I try to build horovod in development mode (using `python setup.py develop` or `pip install -e`) with `HOROVOD_WITHOUT_TENSORFLOW=1`, I get this error:

`error: can't copy 'build/lib.linux-x86_64-3.6/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so': doesn't exist or not a regular file`

It looks like `python setup.py develop` tries to install everything from the `ext_modules` (and it contains `tensorflow_mpi_lib`, even if the environment variable says not to build it), while `python setup.py install` just installs what's in the build directory.

Do you think installing in the development mode worth fixing?
Maybe this should be documented at least...

**Comment by alsrgv** [comment]
@kit1980, sorry for the delayed response.  I think the development mode could be interesting if it could work in conjunction with `python setup.py build` anytime we need to update the C++ code, which would hopefully do it incrementally.

**Comment by alsrgv** [comment]
@tgaddair, could you incorporate instructions for local development and advise not to use development mode for now in the developer's guide you're writing?

**Comment by tgaddair** [comment]
Absolutely!

**Comment by Ricahrd-Li** [comment]
I also meet this kind of problem but for me is pytorch. 
` error: can't copy 'build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib.cpython-36m-x86_64-linux-gnu.so': doesn't exist or not a regular file
`

**Comment by richardliaw** [comment]
Ran into this issue too -- guess `python setup.py install` is the way to go

**Comment by maxhgerlach** [comment]
Closing this issue as `pip install -e` works fine now and is documented, too.
