### ISSUE TITLE
FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c

### ISSUE THREAD

**Issue by ddkang** [horovod/horovod#1040]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.0.1.post2
3. Horovod version: 0.16.1
4. MPI version: 4.0.0
5. CUDA version: Cuda compilation tools, release 9.0, V9.0.176
6. NCCL version: N/A
7. Python version: 3.5.2
8. OS and version: Ubuntu 16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before?

Yes, but there was no resolution: https://github.com/horovod/horovod/issues/368

**Bug report:**

I tried running the `pytorch_imagenet_resnet50.py` script and got the following error:

```(fd) ddkang@future4:/lfs/1/ddkang/yeet/hvd-test$ time horovodrun -np 8 -H localhost:4,future5:4 python pytorch_imagenet_resnet50.py                                          
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[25215,0],1] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
[future5.stanford.edu:12508] [[25215,0],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
```

I made sure to configure and install OpenMPI as in the dockerfile.

**Comment by abditag2** [comment]
It does seem that your MPI configuration has some issue. Take a look at this and let me know if it provides any help: https://github.com/open-mpi/ompi/issues/4437

**Comment by ddkang** [comment]
I am not using `hwloc`, I didn't see other solutions?

**Comment by alsrgv** [comment]
@ddkang, can you share output of `dpkg -l | grep hwloc`?

**Comment by ddkang** [comment]
@alsrgv 

future4:
```ddkang@future4:~$ dpkg -l | grep hwloc
ii  hwloc-nox                              1.11.2-3                                   amd64        Hierarchical view of the machine - non-X version of utilities
ii  libhwloc-dev:amd64                     1.11.2-3                                   amd64        Hierarchical view of the machine - static libs and headers
ii  libhwloc-plugins                       1.11.2-3                                   amd64        Hierarchical view of the machine - plugins
ii  libhwloc5:amd64                        1.11.2-3                                   amd64        Hierarchical view of the machine - shared libs
```

future5:
```ddkang@future5:~$ dpkg -l | grep hwloc
ii  hwloc-nox                             1.11.2-3                                   amd64        Hierarchical view of the machine - non-X version of utilities
ii  libhwloc-dev:amd64                    1.11.2-3                                   amd64        Hierarchical view of the machine - static libs and headers
ii  libhwloc-plugins                      1.11.2-3                                   amd64        Hierarchical view of the machine - plugins
ii  libhwloc5:amd64                       1.11.2-3                                   amd64        Hierarchical view of the machine - shared libs
```

Please let me know if you need anything else!

**Comment by alsrgv** [comment]
@ddkang, sorry for the delayed response.  Looks like this is the same version as the one flagged in https://github.com/open-mpi/ompi/issues/4437.  Could you try uninstalling hwloc (`apt purge hwloc-nox libhwloc-dev libhwloc-plugins libhwloc5`) and reinstalling Open MPI?

**Comment by ddkang** [comment]
That worked, thank you! It would be nice to have this in the documentation.

**Comment by alsrgv** [comment]
Good idea, added to #1084.
