### ISSUE TITLE
how to allgather tf.string tensors

### ISSUE THREAD

**Issue by XuesongYang** [horovod/horovod#1041]
**Environment:**
1. Framework: Tensorflow
2. Framework version: 1.12
3. Horovod version: 0.16.1
4. MPI version: 3.1.0
5. CUDA version: 9.0
6. NCCL version: 2.2.13
7. Python version: 3.6.6
8. OS and version: rhel fedora 2018.03

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)? No
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)? No

**Your question:**
I am trying to gather tf.string tensors across all GPUs. But it seems that `hvd.allgather()` function does not support this data type. I can definitely work around with looking up in a dict {utterid: index}, but I just need to double check if I am wrong. Any other efficient workarounds? My code is in the following:
``` Python
 83 # Horovod: gather metrics from synchronized allreduce training
 84 class Gather(object):
 85     def __init__(self, name):
 86         self.name = name
 87         self.items = list()
 88
 89     def update(self, val):
 90         self.items.extend(hvd.allgather(val))
 91 
 92 utter_ids = Gather('Utter IDs')
```
``` Python
    212             truth_ids.update(truth)
--> 213             utter_ids.update(uttid)
    214 

ipdb> uttid
<tf.Tensor: id=193500, shape=(4,), dtype=string, numpy=
array([b'00ccc0a2-dfcb-4af5-9887-dff09d336acd_2876.170_2879.025',
       b'011a52d1-a35a-427a-9638-9023b9e3bdd2_745.060_746.475',
       b'0010f9e9-aaa8-4d19-9c60-f312773471cb_264.280_265.165',
       b'00e52fb8-4038-416a-a122-06ad116606c5_317.500_321.355'],
      dtype=object)>
ipdb> utter_ids.update(uttid)
*** tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of string is not in the list of allowed values: uint8, int8, uint16, int16, int32, int64, half, float, double, bool
        ; NodeDef: {{node HorovodAllgather}} = HorovodAllgather[T=DT_STRING](dummy_input); Op<name=HorovodAllgather; signature=tensor:T -> output:T; attr=T:type,allowed=[DT_UINT8, DT_INT8, DT_UINT16, DT_INT16, DT_INT32, DT_INT64, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_BOOL]> [Op:HorovodAllgather]

```

**Comment by abditag2** [comment]
Maybe you could try to convert your tensors from string to bytes and then vice versa after allgather?
https://www.tensorflow.org/api_docs/python/tf/compat/as_bytes

**Comment by XuesongYang** [comment]
Is bytes allowed? from my log, it shows that

 allowed=[DT_UINT8, DT_INT8, DT_UINT16, DT_INT16, DT_INT32, DT_INT64, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_BOOL]

**Comment by alsrgv** [comment]
@XuesongYang, this is probably more supported way - https://www.tensorflow.org/api_docs/python/tf/strings/unicode_decode - it converts strings to int32.  However, we haven't tested it.  Do you plan to allgather a single string from each worker, or a batch of strings from each worker?
