### ISSUE TITLE
Big tiff datasets

### ISSUE THREAD

**Issue by ThrowMeForALoop** [horovod/horovod#1049]
Hi team,

I distributed a large dataset including multiple geo tiff files on hdfs (in particular gray scale image with shape (1, 5000, 5000)). I plan to transform those files into intermediate distributed files but I don't know **which sort of distributed files that horovod can support for distributed training**?

I found a Horovod example that use parquet file which can roughly represent two-dimension dataset so it can not fulfil my requirement for three-dimension data as above.

Thanks and regards,

[vienna10.tif.zip](https://github.com/horovod/horovod/files/3142346/vienna10.tif.zip)

**Comment by alsrgv** [comment]
@ThrowMeForALoop, [Petastorm](https://github.com/uber/petastorm) has codecs that allow it to support multi-dimensional images.  I'd recommend trying it out, and if anything doesn't work raising an issue there.
