### ISSUE TITLE
Preprocess the data once before feeding into Tensorflow pipeline with shard.

### ISSUE THREAD

**Issue by XuesongYang** [horovod/horovod#1050]
My use case is that the data should be preprocessed before feeding into Tensorflow dataset pipeline with shard. I have two instances, each with 8 GPUs, but I only need to preprocess data using a single instance where ranks [0-7] locate (saying `instance_1`). How to let other ranks get access to the data that is in the memory of `instance_1`? The snipet of code:
``` Python
tf.enable_eager_execution()
feat_list, truth_list= prepare_data(some_input_file)
reduced_feat_list, reduced_truth_list = filter_out(feat_list, truth_list)
dataset = tf.data.Dataset.from_tensor_slices((reduced_feat_list, reduced_truth_list))
dataset = dataset.shard(hvd.size(), hvd.rank())
dataset = dataset.apply(tf.data.experimental.parallel_interleave())
dataset = dataset.padded_batch()

num_batches_per_shard = len(reduced_feat_list) // (hvd.size() * batch_size)
for batch, (feat, truth) in dataset.take(num_batches_per_shard):
    pass
```

The above code will make `prepare_data()` and `filter_out()` executed `hvd.size()` times simualtaneously. This is not expected. I just need to execute these two functions once. So the modification is shown below:
``` Python
tf.enable_eager_execution()
if hvd.rank() == 0:
    feat_list, truth_list= prepare_data(some_input_file)
    reduced_feat_list, reduced_truth_list = filter_out(feat_list, truth_list)

dataset = tf.data.Dataset.from_tensor_slices((reduced_feat_list, reduced_truth_list))
dataset = dataset.shard(hvd.size(), hvd.rank())
dataset = dataset.apply(tf.data.experimental.parallel_interleave())
dataset = dataset.padded_batch()

num_batches_per_shard = len(reduced_feat_list) // (hvd.size() * batch_size)
for batch, (feat, truth) in dataset.take(num_batches_per_shard):
    pass
```
Do you think this change is feasible? Thanks

**Comment by alsrgv** [comment]
@XuesongYang, out of my curiosity - what's the reason that you cannot preprocess data on both instances?  Are both servers participating in the single deep learning training, or they're training two different models?
