### ISSUE TITLE
in HOROVOD_HIERARCHICAL_ALLREDUCE=1 mode , Can i still use RDMA on nccl2 between nodes?

### ISSUE THREAD

**Issue by raoxing** [horovod/horovod#1054]
in HOROVOD_HIERARCHICAL_ALLREDUCE=1 mode , Can i still use RDMA on nccl2 between nodes ?

**Comment by alsrgv** [comment]
@raoxing, in case of HOROVOD_HIERARCHICAL_ALLREDUCE=1, MPI is used between nodes.  NCCL natively supports hierarchical allreduce since 2.4.x.  You can try disabling HOROVOD_HIERARCHICAL_ALLREDUCE and upgrading to NCCL 2.4.x to see if it improves the performance of your model.

**Comment by raoxing** [comment]
> @raoxing, in case of HOROVOD_HIERARCHICAL_ALLREDUCE=1, MPI is used between nodes. NCCL natively supports hierarchical allreduce since 2.4.x. You can try disabling HOROVOD_HIERARCHICAL_ALLREDUCE and upgrading to NCCL 2.4.x to see if it improves the performance of your model.
hi, alsrgv ,Thank you for your reply。
I find NCCL 2.4.x does not support  hierarchical allreduce (https://devblogs.nvidia.com/massively-scale-deep-learning-training-nccl-2-4/)， and i Implement a hierarchical allreduce(refer to https://arxiv.org/abs/1807.11205)  base on horovod and nccl2.4, on tf benchmark test(vgg16 model, batch_size=128, two 8-card V100 machines, intra ring over nvlink, inter ring over gpu direct rdma) ,the acceleration ratio increased from 13.3x(base on ring all-reduce) to 14.4x。

**Comment by alsrgv** [comment]
@raoxing, great - did you use `HOROVOD_HIERARCHICAL_ALLREDUCE=1` or did you customize Horovod?
