### ISSUE TITLE
std::bad_alloc when use AUTOTUNE

### ISSUE THREAD

**Issue by cklsoft** [horovod/horovod#1057]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): TensorFlow
2. Framework version: tf_nightly_gpu
3. Horovod version: 0.16.1
4. MPI version: 4.0.0
5. CUDA version: 10
6. NCCL version: 2.4
7. Python version: 3.5
8. OS and version: centos 

![image](https://user-images.githubusercontent.com/3956357/57312461-31ce3300-7120-11e9-80cb-a76d394f9836.png)

I use `-x HOROVOD_AUTOTUNE=1` in mpiexec, then the error occur. @alsrgv  How to solve the error?

**Comment by tgaddair** [comment]
Hey @cklsoft, thanks for raising this issue. This bug was fixed by #995, but hasn't yet been released. If you'd like, you can try building from master as a workaround for now.

**Comment by cklsoft** [comment]
> Hey @cklsoft, thanks for raising this issue. This bug was fixed by #995, but hasn't yet been released. If you'd like, you can try building from master as a workaround for now.

Thanks for your reply, I will try the commit.
