### ISSUE TITLE
GPU memory consumption is different (by a large margin) for different workers(ranks).

### ISSUE THREAD

**Issue by scotthuang1989** [horovod/horovod#1061]
**Environment:**
1. Framework: TensorFlow, Keras
2. Framework version:
3. Horovod version:0.15.2
4. MPI version:3.0
5. CUDA version:9
6. NCCL version:2.2
7. Python version:3.6
8. OS and version:ubuntu 17.04

**Checklist:**

**Bug report:**

I run my training on 4 GPU. but GPU 0 take almost double GPU memory:

![image](https://user-images.githubusercontent.com/5325686/57432947-bed0d380-7269-11e9-9fb8-3b364e64538f.png)

I run this without horovod, GPU memory consumption is ~8000M. so, it looks like the other 3 worker use less GPU memory with run with horovod.

**Comment by alsrgv** [comment]
@scotthuang1989, which version of TensorFlow are you using?  If single-GPU training is taking up 8GB, this does not look like a bug to me.

**Comment by scotthuang1989** [comment]
@alsrgv tensorflow version is 1.9.0.  I didn't stop training since I file this this bug.  everything works ok, the loss, accuracy is in normal range. so what confuse me is  how can other 3 GPUs train the model "correctly" with half GPU amount of memory?

**Comment by alsrgv** [comment]
@scotthuang1989, TensorFlow allocated memory in rather large chunks.  It's possible that even minor additional memory used for any purpose will trigger doubling the amount of memory allocated to TensorFlow.  I wouldn't worry too much about it if your training is progressing normally.

**Comment by scotthuang1989** [comment]
@alsrgv , I think you are right. I try different batch size, the GPU memory assumption is almost the same. thanks.

**Comment by majmin7** [comment]
This problem still exists. I'm running a V100 with 16G of GPU ram, and an additional 8G is being used on the root GPU. I was able to eliminate that overhead by swapping the order of `model.cuda()` and `hvd.broadcast_parameters()`. If `model.cuda()` comes first, then horovod seems to be creating 8G of additional stuff on the master GPU. That's half of the available 16G, so this is not trivial.

If I put `model.cuda()` after `hvd.broadcast_parameters()`, then the memory usage on all GPUs is the same. Unfortunately then I get an error 
```
[1,0]<stderr>:    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
[1,0]<stderr>:RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

What is the correct ordering of `model.cuda()` and parameter broadcast?
