### ISSUE TITLE
Horovod with Unified Memory 

### ISSUE THREAD

**Issue by lee9011** [horovod/horovod#1062]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version: 1.8.0
3. Horovod version: 0.16.1
4. MPI version: OpenMPI 3.1.2
5. CUDA version: 9.0
6. NCCL version: 2.4.2
7. Python version: 3.5
8. OS and version: ubuntu 16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**

I have a single workstation with 2 RTX GPUs which are connected via NVLink.
When I perform deep learning with large size data, sometimes OOM is appeared.
So, I want to use Unified Memory with NVLink and two RTX GPUs.

In addition, there is a options to activate unified memory in TensorFlow (config.gpu_options.per_process_gpu_memory_fraction). 
But, I think it is not working well with horovod because of mpirun (2 graphs are created separately on the 2 GPUs).

In this situation, is it possible to use unified memory with horovod (OpenMPI-mpirun)?

If it is possible, I want to know how to activate/use unified memory with mpirun command.

**Comment by alsrgv** [comment]
@lee9011, can you explain more what you're trying to achieve - do you want to run a single process that would use the memory of both GPUs?  Are you using `config.gpu_options.per_process_gpu_memory_fraction` > 1?  AFAIK, that would just spill over to CPU rather than adjacent GPUs.

**Comment by JF-D** [comment]
@alsrgv Do you know how to run a single process that would use the memory of both GPUs? Besides, do horovod support unified memory training when using tensorflow (I mean using cpu memory)? I can run single card training. But for multi-cards, I encountered illegal memory access in horovod allreduce.
