### ISSUE TITLE
"import horovod.tensorflow" crash on latest version

### ISSUE THREAD

**Issue by ThrowMeForALoop** [horovod/horovod#1071]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version: tensorflow-gpu(1.12)
3. Horovod version: 0.16.1
4. MPI version: 4.0.0
5. CUDA version: 9.0
6. NCCL version: 2.1.2
7. Python version: 3.6.8
8. OS and version: CENTOS 7

I just try to test version 0.16.1 and 0.16.0 with tensorflow-gpu by using "python -c ''import horovod.tensorflow' but it crashes intermediately: "Illegal instruction". I reverted to horovod 0.14.1 and it works fine. However I need "horovod.spark" which has not existed in lower version than 0.16.0.

Can anyone help me, please? Thank you so much

**Comment by tgaddair** [comment]
Hey @ThrowMeForALoop, can you give us some more info about the crash?  Do you have a complete stack trace?

When installing Horovod, did everything seem to work correctly?  What command did you run to install Horovod?  Did you include `--no-cache-dir`?

**Comment by ThrowMeForALoop** [comment]
Hey @tgaddair,
I test just write simple test.py `import horovod.tensorflow` and run `python test.py`
I guess the problem is that **parameter_manager.cc** is missing in horovod common folder.

I tried:
```
pip uninstall -y horovod
HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod
```
However, nothing changed.

![Screen Shot 2019-05-14 at 7 15 36 AM](https://user-images.githubusercontent.com/23578972/57672455-7d00ae00-7618-11e9-98d6-b45b57cb04b1.png)

**Comment by siyux** [comment]
I met the same trouble!

**Comment by tgaddair** [comment]
Can you try installing in a new virtual environment?  I'm wondering if somehow some parts of version 0.14.1 (which did not have `parameter_manager.cc` are still around and conflicting with the new code.

**Comment by ThrowMeForALoop** [comment]
> Can you try installing in a new virtual environment? I'm wondering if somehow some parts of version 0.14.1 (which did not have `parameter_manager.cc` are still around and conflicting with the new code.

I created a new virtual environment but still in same trouble.

**Comment by tgaddair** [comment]
Do you happen to know if the file it's looking for exists in your installation (`horovod/common/parameter_manager.cc`)?

**Comment by ThrowMeForALoop** [comment]
It's indeed not there. I tried to build tensorflow from orginal source code as well but same problem

<img width="865" alt="Screen Shot 2019-05-14 at 9 45 34 PM" src="https://user-images.githubusercontent.com/23578972/57727407-b9bcbb80-7691-11e9-92bc-9739a5ad3a0b.png">

**Comment by tgaddair** [comment]
Do you have a file called `horovod/tensorflow/mpi_lib.so`?  That should be where the `parameter_manager` symbols live.  If so, can you try running `nm -g` on it and providing a gist of the output?

Also, could you provide a full gist of the output when installing from pip?  Thanks, and apologies for all the back and forth.

**Comment by ThrowMeForALoop** [comment]
@tgaddair 
No problem. I changed to hovorovod + tensorflow 1.13.1 without GPU  in this try.
Please refer to attached file for `nm -g` result.

[nm -g .pdf](https://github.com/horovod/horovod/files/3181173/nm.-g.pdf)

**Comment by tgaddair** [comment]
Thanks, the symbols look correct.  Can I also take a look at the output from installing Horovod?

Also, when you import Horovod, be careful that you're not in the Horovod root directory, as that can cause weird issues.

**Comment by ThrowMeForALoop** [comment]
<img width="1283" alt="Screen Shot 2019-05-15 at 11 08 41 PM" src="https://user-images.githubusercontent.com/23578972/57809781-8a2bb300-7766-11e9-9dfe-97366dd0bf14.png">
Installation looks normal. However I realized that the same version works fine in my macbook (using clang) but only have trouble with cluster deployment (gcc 5.4.0) as seen from the picture.

I got stuck now as I tried any possible methods. If you have any ideas, please let me know

**Comment by tgaddair** [comment]
Similar to #761, can you try installing a different gcc in a new conda environment (e.g, `conda install gcc_linux-64 gxx_linux-64`) and installing Horovod again?

**Comment by ThrowMeForALoop** [comment]
nothing changed even with new installed gcc. Still the same problem with missing horovod/common/parameter_manager.cc. Maybe CENTOS 7.0 is the root cause ??

**Comment by ThrowMeForALoop** [comment]
Another thing worth mentioning is that horovod 0.14 works fine with the same setup (gcc, os ...). However I need to use horovod.spark which only exists on 0.16.0 and 0.16.1 version

**Comment by alsrgv** [comment]
@ThrowMeForALoop, what kind of CPU do you have on this server?  Do you build Horovod and run it on the same server?  SIGILL means that an instruction used was not supported by CPU architecture.

**Comment by ThrowMeForALoop** [comment]
<img width="1438" alt="Screen Shot 2019-05-17 at 12 16 15 AM" src="https://user-images.githubusercontent.com/23578972/57890740-0f7f9800-7839-11e9-9fc2-a7bc5bd3acfc.png">
@alsrgv : My CPU is quite old-fashioned. Can you confirm about Horovod support with this sort of CPU.
Thanks

**Comment by alsrgv** [comment]
@ThrowMeForALoop, looks like it's [2011 model](https://ark.intel.com/content/www/us/en/ark/products/52581/intel-xeon-processor-e5649-12m-cache-2-53-ghz-5-86-gt-s-intel-qpi.html).

I've pushed a tentative fix for you.  Can you try installing Horovod via `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir git+https://github.com/horovod/horovod@fix_avx`?

**Comment by ThrowMeForALoop** [comment]
@alsrgv : your build works well. 
Still I get trouble in running 'keras_spark_rossmann' example. I guess the problem is that mpirun command can not run as root as I am a normal user.

Would you mind checking it, please? Thanks
<img width="1084" alt="Screen Shot 2019-05-17 at 4 49 17 PM" src="https://user-images.githubusercontent.com/23578972/57936986-55823d80-78c5-11e9-8fe8-a95c18eb2d9d.png">
<img width="814" alt="Screen Shot 2019-05-17 at 4 51 29 PM" src="https://user-images.githubusercontent.com/23578972/57936987-55823d80-78c5-11e9-8795-b2de00c2fef2.png">

**Comment by alsrgv** [comment]
Great! Can you paste the full output? `mpirun` error should be above these messages.

**Comment by ThrowMeForALoop** [comment]
@alsrgv : Can you check whether your commit is in the latest build of horovod.
You deleted the  horovod@fix_avx branch and I meet the same problem as install horovod from:
`HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod `

**Comment by alsrgv** [comment]
@ThrowMeForALoop, can you install via `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir git+https://github.com/horovod/horovod`?
