### ISSUE TITLE
Segmentation fault when trying to train with tensorflow, then torch 

### ISSUE THREAD

**Issue by divyakul1** [horovod/horovod#1074]
**Environment:**
1. Framework: Tensorflow and Pytorch
2. Horovod version: 0.16.1
3. CUDA version: 10.0
4. Python version:3.6.1

**Bug report:**
I am trying to run a workflow that first trains on tensorflow and then pytorch, but I'm seeing that there is no way to import both horovod.tensorflow and horovod.torch. If this happens hvd.init() returns in a segmenation fault.
Signal: Segmentation fault (11)
Signal Code: (128) 
Failing at address (nil)

Is there anyway to get around this?

All of these combinations result in a seg fault:

import horovod.torch as hvd_torch
import horovod.tensorflow as hvd
hvd_torch.init()

import horovod.tensorflow as hvd
import horovod.torch as hvd_torch
hvd_torch.init()

import horovod.tensorflow as hvd
import horovod.torch as hvd_torch
hvd.init()

import horovod.torch as hvd_torch
import horovod.tensorflow as hvd
hvd.init()

import horovod.torch as hvd_torch
hvd_torch.init()
import horovod.tensorflow as hvd
hvd.init()

**Comment by ThrowMeForALoop** [comment]
Hope that the team can fix it soon. I have the same issue

**Comment by alsrgv** [comment]
@divyakul1, @ThrowMeForALoop, can you give it a shot using Dockers images that we provide, e.g. `horovod/horovod:0.16.1-tf1.12.0-torch1.0.0-mxnet1.4.0-py2.7`?

I was able to get it to work:
```
/examples# python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod.tensorflow as h1
>>> import horovod.torch as h2
>>> h1.init()
0
>>> h2.init()
0
```

**Comment by divyakul1** [comment]
Yes, it does work on the docker image, 
I was using a virtual environment with tensorflow 1.12.0, but just switched to one with **tensorflow 1.13.1** and the same version for all other packages, and I am getting the same results as you. Thank you!
