### ISSUE TITLE
How to specify the device GPU?

### ISSUE THREAD

**Issue by chengjianhong** [horovod/horovod#1091]
Hi, I have 1 machine with 4 gpu. If I only use the 2 gpu of them, how to specify and  run?

**Comment by rakshithvasudev** [comment]
can you try horovodrun -np 2 python yourpyfile.py and check nvidia-smi for gpu utilization?

**Comment by chengjianhong** [comment]
@rakshithvasudev Thanks, I have fixed it. But I have another question whether  there can configure the specified data set on different work sites?

**Comment by alsrgv** [comment]
@chengjianhong, if you're using TensorFlow, you can use tf.data API and [.shard()](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shard) functionality.

**Comment by chengjianhong** [comment]
@alsrgv Yes, I use tensorflow, Can you be more specific?

**Comment by alsrgv** [comment]
@chengjianhong, if you load your data using TensorFlow's Dataset API, you can use `dataset = dataset.shard(hvd.size(), hvd.rank())` to restrict the reader to only look at a portion of data.

**Comment by zdgithub** [comment]
How do you specify the GPU ids? For example , I just want to use `1,2,3` gpus and not to use the `0` gpu

**Comment by tgaddair** [comment]
Hey @zdgithub, you can either do this outside of Horovod by setting `CUDA_VISIBLE_DEVICES="1,2,3"`, or within Horovod by running with `horovodrun -np 3` then pinning to specific GPUs: `config.gpu_options.visible_device_list = str(hvd.local_rank() + 1)`.

**Comment by zdgithub** [comment]
> Hey @zdgithub, you can either do this outside of Horovod by setting `CUDA_VISIBLE_DEVICES="1,2,3"`, or within Horovod by running with `horovodrun -np 3` then pinning to specific GPUs: `config.gpu_options.visible_device_list = str(hvd.local_rank() + 1)`.

Oh, thank you very much!

**Comment by Tangolin** [comment]
I think it is important to note that it is `CUDA_VISIBLE_DEVICES=1,2,3`, it should be used without the quotation marks, confused me for quite a bit there.

**Comment by gg22mm** [comment]
> config.gpu_options.visible_device_list = str(hvd.local_rank() + 1)

pytoch What to do ？
