### ISSUE TITLE
Performance issues on CPU.

### ISSUE THREAD

**Issue by tdww** [horovod/horovod#1094]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 1.13.1
3. Horovod version: 0.16.2
4. MPI version: 2.1.1
5. CUDA version: - 
6. NCCL version: - 
7. Python version: 3.6.7
8. OS and version: Ubuntu 18.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)? -
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)? -

**Your question:**
I have an issue on running horovod on multiple CPUs.
I am using one of the example models **/examples/keras_mnist_advanced.py** and when I'm running training on CPUs there is weird performance issues. I have disabled gpu_options for CPU run.
What I have noticed: 
1. When I'm running the example using 1 machine on 1 CPU core, the training speed is exactly the same like when I'm using 4 cores. 
2. When I'm running using multiple machines (using 4 cores on each) - Using 2 machines (8 cores) and 4 machines (16 cores) gives the exact same results. While 3 machines (12 cores) gives lower performance than with 3 machines. 
Setup for all machines are exactly the same (created on Google Compute Engine).

**Comment by alsrgv** [comment]
@tdww, MNIST example is not meant for performance evaluations, but rather meant to see Horovod integration points.  Can you try running a bigger model?

**Comment by tdww** [comment]
Thanks, gonna try it out.
