### ISSUE TITLE
when horovodrun on 2 servers 4 gpu, there is nothing output but stop.

### ISSUE THREAD

**Issue by liuyongheng123** [horovod/horovod#1105]
**Environment:**
1. Framework:PyTorch
2. Framework version:1.0.0
3. Horovod version: pull horovod docker ,have no idea 
4. MPI version:4.0.0
5. CUDA version:9.0
6. NCCL version:2.3.7
7. Python version:3.6.7 (update ,not use docker's python)
8. OS and version:ubuntu16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/running.md)?  yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?  yes

**Your question:**
when i use horovodrun ,  comand  is below:

horovodrun -np 2 -H 192.168.116.9:1,192.168.116.14:2 -p 10088  --verbose   \
  python train_new.py \
  --epochs "${NUMEPOCHS}" \
  --warmup-factor 0 \
  --lr "${LR}" \
  --no-save \
  --threshold=0.23 \
  --horovod 1  \
  --data ${DATASET_DIR} \
  ${EXTRA_PARAMS[@]} |& grep -v " Read -1"

there is nothing output.  when i just use single server , the program is run well , training outputs well too. 
Then i change mpirun for horovodrun , and set "--mca btl_base_verbose 20 --mca oob_base_verbose 10". the program also stop as before ,but outputs some info as below:

------------------------------------------------------------
A process or daemon was unable to complete a TCP connection
to another process:
  Local host:    6ec142731008
  Remote host:   c35efd36f095
This is usually caused by a firewall on the remote host. Please
check that any firewall (e.g., iptables) has been disabled and
try again.
------------------------------------------------------------
[6ec142731008:00162] [[34855,0],2] tcp:send_handler called to send to peer [[34855,0],0]
[6ec142731008:00162] [[34855,0],2] tcp:send_handler CONNECTING
[6ec142731008:00162] [[34855,0],2]:tcp:complete_connect called for peer [[34855,0],0] on socket 20
[6ec142731008:00162] [[34855,0],2]-[[34855,0],0] tcp_peer_complete_connect: connection failed with error 113
[6ec142731008:00162] [[34855,0],2] tcp_peer_close for [[34855,0],0] sd 20 state CONNECTING
[6ec142731008:00162] [[34855,0],2]:[oob_tcp_connection.c:1008] connect to [[34855,0],0]
[6ec142731008:00162] [[34855,0],2] orte_tcp_peer_try_connect: attempting to connect to proc [[34855,0],0]
[6ec142731008:00162] [[34855,0],2] orte_tcp_peer_try_connect: attempting to connect to proc [[34855,0],0] on socket -1
[6ec142731008:00162] [[34855,0],2] orte_tcp_peer_try_connect: attempting to connect to proc [[34855,0],0] on 172.17.0.2:35477 - 1 retrie
s
[6ec142731008:00162] [[34855,0],2] orte_tcp_peer_try_connect: 172.17.0.2:35477 is down
[6ec142731008:00162] [[34855,0],2] tcp:failed_to_connect called for peer [[34855,0],0]
[6ec142731008:00162] [[34855,0],2] tcp:failed_to_connect unable to reach peer [[34855,0],0]
[6ec142731008:00162] [[34855,0],2] TCP SHUTDOWN
[6ec142731008:00162] no hnp or not active
[6ec142731008:00162] [[34855,0],2] TCP SHUTDOWN done
[6ec142731008:00162] mca: base: close: component tcp closed
[6ec142731008:00162] mca: base: close: unloading component tcp
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------

then i check the firewall , i found there is no ufw installed. So i have no idea to solve this problem.
Please help me

**Comment by alsrgv** [comment]
@liuyongheng123, can you share the output of `ifconfig -a` on both servers?

**Comment by liuyongheng123** [comment]
This is 192.168.116.14's ifcong info:
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.2  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:02  txqueuelen 0  (Ethernet)
        RX packets 14916  bytes 13370908 (13.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9406  bytes 1832640 (1.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 408197  bytes 54543966 (54.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 408197  bytes 54543966 (54.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
this is 192.168.116.9's ifconfig info:
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:01  txqueuelen 0  (Ethernet)
        RX packets 1672  bytes 377609 (377.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1270  bytes 176636 (176.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 28  bytes 2008 (2.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 28  bytes 2008 (2.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
anther situation needed to know is, i use ssd training program in dockers, these dockers is set --port 10088:22 ,use the host's ip .

**Comment by alsrgv** [comment]
@liuyongheng123, looks like the issue is that you're running docker without `--network=host`. Can you run it with `--network=host`?

**Comment by liuyongheng123** [comment]
Yes, it is the right solution. mpirun will set some random port for tcp connecting. First there is no free port because i forgot to set, the connect across servers is not succeed. 
Thank you again!
may i ask another following problem.  when i run horovod again ,it shows,
Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Notified all the hosts that the registration is complete.
Waiting for hosts to perform host-to-host interface checking.
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/run.py", line 425, in run
    settings, fn_cache=fn_cache)
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/util/cache.py", line 103, in wrap_f
    results = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/run.py", line 240, in _driver_fn
    driver.wait_for_task_to_task_address_updates(settings.timeout)
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/common/service/driver_service.py", line 127, in wait_for_task_to_task_address
_updates
    'tasks to update task-to-task addresses')
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/common/util/timeout.py", line 32, in check_time_out_for
    raise Exception(self._message.format(activity=activity))
Exception: Timed out waiting for tasks to update task-to-task addresses. Please check connectivity between servers. You may need to incr
ease the --start-timeout parameter if you have too many servers.


when use mpirun, it shows ,
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       lyh-ThinkStation-P520
Executable:  #horovodrun
--------------------------------------------------------------------------
3 total processes failed to start
[lyh-ThinkStation-P520:00279] [[27268,0],0] TCP SHUTDOWN
[lyh-ThinkStation-P520:00279] [[27268,0],0] TCP SHUTDOWN done
[lyh-ThinkStation-P520:00279] mca: base: close: component tcp closed
[lyh-ThinkStation-P520:00279] mca: base: close: unloading component tcp

**Comment by liuyongheng123** [comment]
This is the newest mpirun info. please ignore above mpirun info.

WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

  Local host: zlf-ThinkStation-P520
  PID:        222
  Message:    connect() to 172.17.0.1:1025 failed
  Error:      Operation now in progress (115)

Since i run docker with --network=host, the script run and stop , printing the info above.  it seems tcp does not work well?

**Comment by liuyongheng123** [comment]
Then i still go back to use horovodrun command . For settling down the connecting timeout, i set  --start-timeout 300  to try. luckily, the script runs well ,  and  the training program works now . 
Thanks again!
