### ISSUE TITLE
Can we run two independent pieces of code (let's say A & B) and then merge them, and execute it over and over again, and at the same time using the basic concept of horovod workload partitioning?

### ISSUE THREAD

**Issue by rvallari1** [horovod/horovod#1107]
I am trying to perform model parallelism, on a U-Net.. and Using Horovod for multi-node purpose. But is it possible to run two pieces of code in parallel on a single piece of dataset but computing different hyper-parameters?

**Comment by alsrgv** [comment]
@rvallari1, not sure I fully understand the question.  How is it different from running two different jobs?

**Comment by rvallari1** [comment]
@alsrgv , as far as my understanding goes, horovod performs workload partitioning. I am trying to do..
Within the (subset of dataset) partitioning, if I can run two computations (totally independent ) and these computations are similar to neural network training procedure. 
So what can I do?
1. if I have -n cores i my system,
 perform n//2 partitions of dataset & allot 2 cores to each subset of training data?

**Comment by alsrgv** [comment]
@rvallari1, you generally don't need Horovod if you're not doing distributed training.  There are other frameworks for workload partitioning, e.g. Apache Spark.
