### ISSUE TITLE
Show horovod container install verbs library when using rdma ?

### ISSUE THREAD

**Issue by xiaozhouX** [horovod/horovod#1117]
**Environment:**
Framework: TensorFlow
Framework version: 1.12.0
Horovod version: 0.15.2 ( Image uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py3.5 )
MPI version: 
CUDA version: 
NCCL version: 
Python version: 3.5
OS and version: CentOS 7.4

I'm using horovod in RDMA on kubernetes. In NCCL logs, it shows up using tcp rather then RDMA, which is 
```
Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
```

After I fellow the docs (https://community.mellanox.com/s/article/how-to-deploy-and-run-a-horovod-framework-with-mellanox-network),  install `libibverbs` and `libmlx5` in image:
```
apt install libibverbs-dev
apt install libmlx5-dev
```
It seems to use RDMA. 
Should we install `libibverbs` and `libmlx5` in horovod image by default ?

**Comment by alsrgv** [comment]
@xiaozhouX, AFAIK version of Mellanox OFED installed in the container is tightly coupled with the version of the Mellanox driver installed on the host.  Because of that, we cannot publish a standard RDMA-enabled image - this is something customer need to do based on their environment.

**Comment by byronyi** [comment]
> @xiaozhouX, AFAIK version of Mellanox OFED installed in the container is tightly coupled with the version of the Mellanox driver installed on the host. Because of that, we cannot publish a standard RDMA-enabled image - this is something customer need to do based on their environment.

We thought that too, until recently we found out only installing the following packages in recent Deb-based distro suffices:

* librdmacm1
* libibverbs1
* ibverbs-providers

We run this configuration without installing OFED in the container.

**Comment by alsrgv** [comment]
@byronyi, the latest info I got from Mellanox is that MOFED 4.4 in the container will work with MOFED 4.4+ on the host.  But OFED in the container and MOFED on the host are not compatible (my earlier experiments to make them work together failed, too).  So, the current plan is to add these instructions (#1150).

Did you manage to make OFED in the container work with MOFED on the host, or are you using some other combination?

**Comment by byronyi** [comment]
> Did you manage to make OFED in the container work with MOFED on the host, or are you using some other combination?

Sorry, when I talked about OFED it always means MOEFD...but we did manage to make it work without MOFED in the container. With inbox packages mentioned above, we could run either ibverbs, rdmacm, or RDMA enabled NCCL, all without a hassle. 

It used to fail with old-style libibverbs1 and librdmacm1 though. With the new ibverbs-providers (accessible via deb backport or Ubuntu 18.04) package, it seems we could use the upstream userspace libraries directly with https://github.com/linux-rdma/rdma-core.

**Comment by alsrgv** [comment]
@byronyi, this sounds great!  What's the exact list of packages that you installed in the container to make it work?  Also, did you have to use any special settings on the host during MOFED installation, e.g. `--upstream-libs`?

**Comment by byronyi** [comment]
I don’t think so, it’s just plain MOFED on host. I will double-check soon. 

Btw, we are evaluating using upstream drivers directly, which makes our kernel team happy than ever. Up till now I find no problems except for manually modprobe several kernel drivers and relaxing page locked memory size limit.

**Comment by alsrgv** [comment]
@byronyi, you're right - I was able to upgrade Horovod Dockerfile to Ubuntu 18.04, add RDMA libraries you mention, and NCCL/IB worked just fine (https://github.com/horovod/horovod/pull/1159). Thanks for the suggestion!

**Comment by byronyi** [comment]
@xiaozhouX do you have any other issues with our solution? If so, feel free to leave your comments or suggestions :)

**Comment by vilmara** [comment]
> @byronyi, you're right - I was able to upgrade Horovod Dockerfile to Ubuntu 18.04, add RDMA libraries you mention, and NCCL/IB worked just fine (#1159). Thanks for the suggestion!

hi @alsrgv , I ran it Ubuntu 16.04 and got this error:  `E: Unable to locate package ibverbs-providers``

**Comment by byronyi** [comment]
@vilmara you need at least Ubuntu 18.04, or Debian 9.0 with backport. 

For Ubuntu 16.04, please use OFED instead.

**Comment by vilmara** [comment]
hi @byronyi, I used OFED, now I am getting other errors, could you please take a look at #1261?

**Comment by xiaozhouX** [comment]
> @xiaozhouX do you have any other issues with our solution? If so, feel free to leave your comments or suggestions :)
There is another wa using rdma in horovod. 
I modify the device plugin to mount the `libibverbs.so`, `librdmacm.so`, `libmlx5.so`  and some other `.so` files in pod. 
In this way, we don't need to install any library in docker image.

**Comment by vilmara** [comment]
Hi @xiaozhouX , thanks for your comment. May I know what kind of modifications you did to make it work with the mounted libraries, does it work for Ubuntu 16.04?

**Comment by xiaozhouX** [comment]
> work

In my case, it worked in Host CentOS 7.4 and the image system is Ubuntu16.04. 
I thought it should work in Ubuntu Host too.

**Comment by xiaozhouX** [comment]
> Hi @xiaozhouX , thanks for your comment. May I know what kind of modifications you did to make it work with the mounted libraries, does it work for Ubuntu 16.04?

In my case, it worked in Host CentOS 7.4 and the image system is Ubuntu16.04.
I thought it should work in Ubuntu Host too.
