### ISSUE TITLE
 HOROVOD_TIMELINE: command not found

### ISSUE THREAD

**Issue by liuyongheng123** [horovod/horovod#1134]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.1.0
3. Horovod version:  (pull the horovod docker -python2.7 version,have no idea of the Horovod version)
4. MPI version: 4.0.0
5. CUDA version: 9.0
6. NCCL version: 2.3.7-1+cuda9.0 (not use in the case)
7. Python version: 3.6.7
8. OS and version: ubuntu 16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? yes

**Your question:**
Please ask your question here.
As i follow the guide of horovod HOROVOD_TIMELINE, set the command as "HOROVOD_TIMELINE = /tmp/timeline.json HOROVOD_TIMELINE_MARK_CYCLES = 1 \
horovodrun -np 2 -H 192.168.116.9:2 -p 10088 ..........."
The system says that, ./run_and_time_horovod.hi: line 100: HOROVOD_TIMELINE: command not found .

Then i tried to use mpirun. set the command as "mpirun -np 2 -H 192.168.116.9:2 ....  -x HOROVOD_TIMELINE = /tmp/timeline.json" 
The system says that, " Warning: could not find environment variable "HOROVOD_TIMELINE"" and  "mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well."

how do i do for using HOROVOD_TIMELINE?
Thanks a lot!

**Comment by alsrgv** [comment]
@liuyongheng123, can you try removing spaces between `VARIABLE=value`?

**Comment by liuyongheng123** [comment]
yes , that is it . thank you

**Comment by 652994331** [comment]
@alsrgv  Hi, could you please help me solve this, when i used command
 HOROVOD_TIMELINE=/path/to/timeline.json mpirun -np  8 -H 10.252.192.90:4,10.252.192.89:4 -bind-to none  -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python3 run_pretraining.py   --input_file=./tf_examples.tfrecord*          --output_dir=./pretrain_jd/pretraining_output_jd \    --do_train=True      --do_eval=True     --bert_config_file=./bert_config.json    --init_checkpoint=./model_new.ckpt          --train_batch_size=64        --max_seq_length=128    --max_predictions_per_seq=20          --num_train_steps=1000000          --num_warmup_steps=10000          --learning_rate=1e-5    --use_fp16   --horovod 

i cant generate timeline, the errors are:

![image](https://user-images.githubusercontent.com/51428350/65080182-92367200-d955-11e9-9a35-6eb80cb1ba4d.png)
