### ISSUE TITLE
Understand the process behind training.

### ISSUE THREAD

**Issue by rvallari1** [horovod/horovod#1142]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): Keras
2. Framework version: 2.2.4
3. Horovod version:0.16.3
4. MPI version: 4.0.0
9. GCC version:7.0.0

**Your question:**
I am running mnist.py using keras, using the command 
horovodrun -np 2 -H localhost:2 python train.py
<img width="582" alt="Capture1" src="https://user-images.githubusercontent.com/32358727/59324065-f1536d80-8cfa-11e9-826f-0612d6abccdc.PNG">
Another, using horovodrun -np 4 -H localhost:4 python train.py
<img width="582" alt="Capture2" src="https://user-images.githubusercontent.com/32358727/59324093-0cbe7880-8cfb-11e9-9571-b59638f81788.PNG">

The training ends like this, which is hard to understand.. I want to see the full log of the process..

**Comment by tgaddair** [comment]
Hey @rvallari1, if your goal is to clean up the log output, one common technique is to only print metrics and other info on the first rank.  For example, by setting `verbose = 1 if hvd.rank() == 0 else 0` as in the [keras_imagenet_resnet50](https://github.com/horovod/horovod/blob/master/examples/keras_imagenet_resnet50.py#L75) example.  Is that what you had in mind?

**Comment by rvallari1** [comment]
@tgaddair Thanks! Apology for being late. It is printing training processes for 12 epochs but runs 12/n epochs with n as number of workers. Gotcha.
