### ISSUE TITLE
Benchmark scaling efficiency 

### ISSUE THREAD

**Issue by SoulGuedria** [horovod/horovod#1144]
Environment:

Framework: TensorFlow, Keras
Horovod version: 0.15.2
MPI version:(OpenRTE) 3.0.0
CUDA version: release 9.0, V9.0.176
Python version: python3
OS and version: debian 9
My question:

Hello,
I'm doing a benchmark for horovod for two CNN architecures. The first one is a Tensorflow based CNN which i scaled up using the horovod tensorflow version and it achieves a 57% of scaling efficiency (120 epochs, batchsize 12 and lr =1e-05 ). The second one is keras-based horovod parallelized CNN and it achieves 105% of scaling efficiency (100 epochs, batchsize 7 and lr =1e-05). 
Does  anyone have explanations for these bench results?

Thanks a lot :)

**Comment by tgaddair** [comment]
Hey @SoulGuedria, it's tough to say without knowing the specifics of the models, data, and your environment (network, number of workers, number of GPUs per worker, etc.).  

Have you tried running the [tensorflow_synthetic_benchmark](https://github.com/horovod/horovod/blob/master/examples/tensorflow_synthetic_benchmark.py)?  That should give you a good baseline of performance to compare against.
