### ISSUE TITLE
Mixing vanilla keras with tensorflow

### ISSUE THREAD

**Issue by lminer** [horovod/horovod#1151]
I'm trying to run a keras model with a tensorflow backend. Unfortunately, one of my layers is a custom layer that relies on `tf.depth_to_space`. So when I try to train the model using horovod, I get a CuDNN error "failed to alloc 1073741824 bytes on host". It does work when I use, `tf.keras` instead but the performance is a lot worse for some reason.

Is there some way to get vanilla keras to work with tensorflow code or is it impossible?

```
[1,0]<stderr>:2019-06-17 04:56:13.963510: E tensorflow
/stream_executor/cuda/cuda_driver.cc:868] failed to alloc 536870912 bytes on host: CUDA_ERROR_OPERATING
_SYSTEM: OS call failed or operation not supported on this OS
[1,0]<stderr>:2019-06-17 04:56:14.128134: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed
to alloc 483183872 bytes on host: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supporte
d on this OS
[1,0]<stderr>:2019-06-17 04:56:14.262813: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed
to alloc 434865664 bytes on host: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supporte
d on this OS
[1,0]<stderr>:2019-06-17 04:56:14.385534: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed
to alloc 391379200 bytes on host: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supporte
d on this OS
[1,0]<stderr>:2019-06-17 04:56:14.513476: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed
to alloc 352241408 bytes on host: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supporte
d on this OS
[1,0]<stderr>:2019-06-17 04:56:14.617280: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed
to alloc 317017344 bytes on host: CUDA_ERROR_INVALID_VALUE: invalid argument
```

**Comment by tgaddair** [comment]
Hey @lminer, most of our Keras [examples](https://github.com/horovod/horovod/blob/master/examples/keras_imagenet_resnet50.py) are using vanilla Keras mixed with TensorFlow, so Horovod should work fine with that combination.

I'm not familiar with the specifics of `tf.depth_to_space` enough to know how it might be causing this error.  Do you have a minimal reproducible example?

**Comment by lminer** [comment]
Seems like it's a problem with my CUDA/CUDNN/NCCL installation as it works fine on a different machine.
