### ISSUE TITLE
How to make workers run sequentially (instead of simultaneously) 

### ISSUE THREAD

**Issue by ImranRolo** [horovod/horovod#1166]
**Environment:**
1. Framework: Tensorflow
2. Framework version: 1.12
3. Horovod version: 0.16.4
4. MPI version: 4.0.1
5. CUDA version: V9.0.176
6. NCCL version:
7. Python version: 3.6
8. OS and version: Ubuntu 16
9. GCC version:

**Your question:**
I'm using horovod to train a programme on a local machine with 2 GPUs. Before the training happens, I have to load a large dataset which takes a lot of CPU usage and memory. However because the workers are loading the dataset simultaneously, the process gets killed as it can't handle training them both. Is there a way for this operation that the workers can run the operations one after the other instead of simultaneously?

-------------------------05148 [15:18<2:12:45, 70.22it/s]   ,0]<stderr>:
mpirun noticed that process rank 1 with PID 0 on node deeplearner exited on signal 9 (Killed).
--------------------------------------------------------------------------

**Comment by alsrgv** [comment]
@ImranRolo, is it an option to have each worker load half of the dataset?

**Comment by ImranRolo** [comment]
Hi @alsrgv. How do I make each worker work on a different dataset?

**Comment by alsrgv** [comment]
@ImranRolo, you can use `hvd.rank()` to detect [process rank](https://github.com/horovod/horovod/blob/master/docs/concepts.rst) and then write code to load the part of dataset that corresponds to that rank.
