### ISSUE TITLE
speed is slow when run mxnet with horovod

### ISSUE THREAD

**Issue by cham-3** [horovod/horovod#1168]
**Environment:**
1. Framework: mxnet
2. Framework version: 1.4.1
3. Horovod version: 0.16.4
4. MPI version: 4.0.0
5. CUDA version: 90
6. NCCL version:
7. Python version: python 2.7.12
8. OS and version: ubuntu 16.04
9. GCC version: 5.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?

**Your question:**
1. Yes, but I have not found the solution.
2. Yes.
3. Yes.

**Comment by cham-3** [comment]
Everything goes well when I run the script on a single node with 4 gpus. 
CPU utilization became very low when I run the script on two or more nodes.

**Comment by alsrgv** [comment]
@cham-3, what's the speed of your network interfaces?

**Comment by cham-3** [comment]
@alsrgv Thanks for your replying. The speed of my network interfaces is 10000Mb/s and  20000Mb/s, respectively.

**Comment by alsrgv** [comment]
@cham-3, can you try adding NCCL to your setup and checking if this improves performance?
