### ISSUE TITLE
The tensorflow program hang on a few hours when use multi gpu node to run 

### ISSUE THREAD

**Issue by sinllychen** [horovod/horovod#1173]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.12.0
3. Horovod version: 0.16.4
4. MPI version: 4.0.0
5. CUDA version: 9.0
6. NCCL version: 2.4.7
7. Python version: 3.6.5
8. OS and version: centos 7.4
9. GCC version: 4.8.5

**Your question:**
When I use the below command to install horovod, I can run the tensorflow_mnist example in one node with multi GPU successfully.
```HOROVOD_CUDA_HOME=/usr/local/cuda-9.0/  HOROVOD_CUDA_INCLUDE=/usr/local/cuda-9.0/include  HOROVOD_CUDA_LIB=/usr/local/cuda-9.0/lib64  HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/data/users/chenxinjie/install_libs/nccl pip install --no-cache-dir horovod```

 But when I use the command
```horovodrun -np 4 -H localhost:2,10.60.1.124:2 --start-timeout 300 --verbose python tensorflow_mnist.py``` 
 to run the tensorflow_mnist example with two server node and four GPUs. From the beginning the program can run well but it then hang on when it use ```W tensorflow/core/common_runtime/bfc_allocator.cc:271``` to all reduce data.  The running logs as following:
<img width="1280" alt="WX20190627-180145@2x" src="https://user-images.githubusercontent.com/7518364/60258191-3a184280-9907-11e9-95af-a45318b18334.png">
<img width="1276" alt="WX20190627-181906@2x" src="https://user-images.githubusercontent.com/7518364/60258611-13a6d700-9908-11e9-812d-277a5d6af497.png">

As the log picuture above , the program hang on the all reduce iteration and when I use ```nvidia-smi``` to watch the GPU process , I can find two GPU process also running, it means that the program is running but it have been hang on. From the log I can't find any useful information to help me to get the program. 
<img width="579" alt="WX20190627-181851@2x" src="https://user-images.githubusercontent.com/7518364/60258712-4355df00-9908-11e9-8a23-f20160a21136.png">

And also I use mpirun to run the tensorflow program and get the same result.
```mpirun --allow-run-as-root --tag-output -np 4 -H localhost:2,10.62.2.124:2 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python tensorflow_mnist.py```

**Comment by alsrgv** [comment]
@sinllychen, you have some existing python3 script that used up all the available GPU memory. You need to kill that script first.  Make sure you have zero GPU memory usage before the test.

**Comment by sinllychen** [comment]
@alsrgv If the horovod program need zero GPU memory to test? But when I run the test script, the two iteration of the chunks is ok and never prompt out of memory.

**Comment by sinllychen** [comment]
@alsrgv Hi, I empty a free GPU card from the two nodes and run the scrip again, it works.  Thank you very much. It may be caused by GPU memory, I have a question that can horovod identify idle GPU card  automatically? From my test, I only can use the command  ```CUDA_VISIBLE_DEVICES=0,1``` to set the free GPU card.

**Comment by alsrgv** [comment]
@sinllychen, unfortunately, you have to specify it manually.

**Comment by sinllychen** [comment]
@alsrgv Thanks very much!

**Comment by sinllychen** [comment]
@alsrgv I have a question that if the program run out of memory, why it not exit and print the OOM log, but hang on for waiting?

**Comment by alsrgv** [comment]
@sinllychen, it's actually supposed to exit, but I'm guessing TensorFlow gets stuck in this particular case.

**Comment by sinllychen** [comment]
@alsrgv I have a question about that when I use horovod to run script on two distributed GPU nodes, I need to copy script and its train dataset to two nodes  with the same directory, or it will prompt me the script and input dataset not found when I run the script in one node.  If I should segment the train dataset to two parts and distributed them to the GPU nodes before I run the distributed horovod script?

**Comment by alsrgv** [comment]
@sinllychen, all nodes should have the training code in the same directory.  Duplicating dataset vs partitioning it across workers is up to you, either way should work fine, as long as workers read data randomly.

**Comment by sinllychen** [comment]
@alsrgv Thank you for your detail answer. As you say, we use horovod distribute mode to run the script , we need to duplicate the dataset or partition it to all workers at first. If the dataset is very large such 100g, we will waste a lot of time to duplicate or partition the data ,  in this way, wheather we run the script by one node  be faster than two nodes or more or not use horovod framework? The more the node numbers are, the  higher the data transmition will cost.

**Comment by alsrgv** [comment]
@sinllychen, you just need to find a way for workers to read the portion of the data, either random portion or an assigned partition.  If workers cannot read data, you cannot do distributed training.
