### ISSUE TITLE
Horovod support for Pytorch

### ISSUE THREAD

**Issue by abidmalikwaterloo** [horovod/horovod#1175]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
Pytorch
2. Framework version:
1
3. Horovod version:
0.16.4
4. MPI version:
spectrum-mpi/10.3.0.0-20190419
5. CUDA version:
cuda/9.2.148
6. NCCL version:
2.3.7
7. Python version:
3.6.5
8. OS and version:
9. GCC version:
7.20

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?

**Your question:**
Please ask your question here.
During interactive mood in Python

```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:38:54) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import horovod.torch as hvd
>>> hvd.init()
--------------------------------------------------------------------------
By default, for Open MPI 4.0 and later, infiniband ports on a device
are not used by default.  The intent is to use UCX for these devices.
You can override this policy by setting the btl_openib_allow_ib MCA parameter
to true.

  Local host:              login2
  Local adapter:           mlx5_1
  Local port:              1

--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   login2
  Local device: mlx5_1
--------------------------------------------------------------------------
[login2:111076] mca_base_component_repository_open: unable to open mca_pml_pami: libpami.so.3: cannot open shared object file: No such file or directory (ignored)
[login2:111076] mca_base_component_repository_open: unable to open mca_coll_ibm: libcollectives.so.3: cannot open shared object file: No such file or directory (ignored)
[login2:111076] mca_base_component_repository_open: unable to open mca_osc_pami: libpami.so.3: cannot open shared object file: No such file or directory (ignored)
2054834736
```

Is this normal behavior when you initialize horovod? I am trying to run it on Summit.

**Comment by alsrgv** [comment]
@abidmalikwaterloo, Horovod supports PyTorch. You need to submit the job to the cluster instead of running the code on the login node.
