### ISSUE TITLE
Failed to build on Mac OS 10.14.5 "library not found for -lstdc++"

### ISSUE THREAD

**Issue by Lyken17** [horovod/horovod#1183]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): PyTorch
2. Framework version: 1.10
3. Horovod version: 0.16.4
4. MPI version: 4.0.0
5. CUDA version: None
6. NCCL version: None
7. Python version: 3.6 
8. OS and version: Mac OS 10.14.5
9. GCC version: Apple LLVM version 10.0.1 (clang-1001.0.46.4)

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

When I was trying to run, 
```
HOROVOD_WITH_PYTORCH=1 python setup.py install
```

it raises the error 

```
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1
```

I realize it is error caused by deprecation of libstdc++ on mac platform. So I add 

```
CXXFLAGS+="-std=libc++" HOROVOD_WITH_PYTORCH=1 python setup.py install
```

But the it is still the same error. The strange part it, I didn't see any snippet that involves `libstdc++` after checking the `setup.py`.  How can I fix the build issue?

**Comment by alsrgv** [comment]
@Lyken17, can you see if [this comment](https://github.com/horovod/horovod/issues/154#issuecomment-360679399) help you?  Please adjust Mac OS version to 10.14 in the environment variable.

**Comment by Lyken17** [comment]
Thanks. It works for me!
