### ISSUE TITLE
How can i check mpi already use ib rdma?

### ISSUE THREAD

**Issue by xieydd** [horovod/horovod#1184]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
All
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
How can i check mpi already use ib rdma? Can i get some useful message? @alsrgv

**Comment by alsrgv** [comment]
@xieydd, you can check [Mellanox user guides](https://community.mellanox.com/s/article/understanding-mlx5-linux-counters-and-status-parameters#jive_content_id_HW_Counters_RDMA_diagnostics) for querying IB performance counters.  That is the ultimate source of truth.

**Comment by xieydd** [comment]
@alsrgv tks.
