### ISSUE TITLE
Data distribution with MPI

### ISSUE THREAD

**Issue by chandana1332** [horovod/horovod#1187]
Environment:

Framework: MXNET
Framework version: 1.4.1
Horovod version:
MPI version: 3.1.0
CUDA version: 10.0
NCCL version:
Python version: 3.6
OS and version: "Amazon Linux AMI" "2018.03"
GCC version: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
What is the best way to distribute data across machines for training in the absence of NFS?

**Comment by alsrgv** [comment]
@chandana1332, you can use HDFS, S3 or other file storage solutions.

**Comment by chandana1332** [comment]
@alsrgv Okay, are logs also accumulated in a similar way?

**Comment by alsrgv** [comment]
@chandana1332, training results are equivalent on all workers, and so can be saved from the first worker to your storage system of choice.
