### ISSUE TITLE
What role does the cache perform?

### ISSUE THREAD

**Issue by Lyken17** [horovod/horovod#1189]
During my training, the following messages displayed on the console
```bash
[1,1]<stderr>:[2019-07-02 18:17:43.902321: W horovod/common/response_cache.cc:113] 
A response has been evicted from cache which may indicate reduced performance. 
Better performance may be obtained by disabling caching (HOROVOD_CACHE_CAPACITY=0) 
or increasing the cache capacity (HOROVOD_CACHE_CAPACITY>8192).
```

I am curious about the usage of the cache. In my understanding, the gradients are sent during each backward. Why is the usage of cache here?

**Comment by alsrgv** [comment]
It's used to improve coordination performance. Please see #902.

**Comment by Lyken17** [comment]
wo, such a quick rely. Thank you!
