### ISSUE TITLE
FP16 is not working in Horovod benchmark but works in TensorFlow benchmark

### ISSUE THREAD

**Issue by renganxu** [horovod/horovod#119]
Recently I tested FP16 in TensorFlow benchmark https://github.com/tensorflow/benchmarks.git. It works and FP16 is ~50% faster than FP32. I added the flags "--use_fp16=True --use_tf_layers=False" when using FP16.  Then I tested FP16 in Horovod_v2 branch of Horovod benchmark repo https://github.com/alsrgv/benchmarks.git, but it has the following error:

Traceback (most recent call last):
  File "tf_cnn_benchmarks.py", line 46, in <module>
    tf.app.run()
  File "/usr/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 129, in run
    _sys.exit(main(argv))
  File "tf_cnn_benchmarks.py", line 36, in main
    bench = benchmark_cnn.BenchmarkCNN(params)
  File "/cm/shared/scratch/centos/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 707, in __init__
    self.model.get_fp16_loss_scale())
AttributeError: 'ResnetModel' object has no attribute 'get_fp16_loss_scale'

Hi @alsrgv , do you know why this error happened and how to solve it?

Regards,
Rengan

**Comment by joeyearsley** [comment]
The `Horovod_V2` branch needs updating, the `TF` one has been updated a month ago compared to 2 months for Horovod.

**Comment by alsrgv** [comment]
@hfutxrg, @joeyearsley, I just published `horovod_v3` branch which contains recent changes.  Unfortunately, these recent changes require one to use nightly TF GPU build, so I don't want to force it on everyone by updating `horovod_v2`. Horovod benchmarks are in the processes of getting [upstreamed](https://github.com/tensorflow/benchmarks/pull/73) into the official TF benchmarks, so hopefully, this juju won't be required soon.

I was able to run FP16 training: `mpirun <args> python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --use_fp16=True --use_tf_layers=False --variable_update=horovod`

Can you share the performance you get on your setup?
