### ISSUE TITLE
Why is the Faster-RCNN model scaling efficiency so low?

### ISSUE THREAD

**Issue by jiangzihanict** [horovod/horovod#1194]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.12
3. Horovod version: 0.15.2
4. MPI version: 3.1.2
5. CUDA version: 9.0
6. NCCL version: 2.3.5
7. Python version: 3.5
8. OS and version: linux ubuntu 16.04
9. GCC version: 5.4

**Your question:**
We are scaling a FasterRCNN from 1 GPU to 32GPUs (4nodes, 8 GPUs per node). The performance numbers are as following:

1GPU: 5 images/s
8GPUs: 25 images/s
16GPUs(2 nodes): 41 images/s
32GPUs(4nodes): 80 images/s

So the scaling efficiency is only 50%?  Even in the same node, the efficiency is only 60%. I read the performance data in Horovod's paper (the attached picture). Is this efficiency related to the model? In addition, our experiments are performed in docker, will this have any bad impact?
  
![Screen Shot 2019-07-04 at 4 38 32 PM](https://user-images.githubusercontent.com/22028950/60653286-545c9e00-9e7c-11e9-8c83-3c8bb0f80fd6.png)

**Comment by alsrgv** [comment]
@jiangzihanict, can you share the command you're running to start the training, as well as NCCL output (with `-x NCCL_DEBUG=INFO`)?

**Comment by jiangzihanict** [comment]
@alsrgv Thanks for your reply. This question has been solved. Because in RCNN, each image has a different number and size of objects, which leads to heterogeneous workloads. So, Its poor scalability is caused by the model. I'll close this issue.
