### ISSUE TITLE
tensorflow_mnist_estimator run false : ncclCommInitRank failed: ncclCommInitRank failed: unhandled system error

### ISSUE THREAD

**Issue by ivankxt** [horovod/horovod#1195]
We want to run the tensorflow_mnist_estimator.py  example in two machine, but we got error as:  

UnknownError (see above for traceback): ncclCommInitRank failed: unhandled system error
        [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dep
endency_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:G
PU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]

Tensorflow 1.12 NCCL version 2.3.5+cuda9.0

mpirun -x LD_LIBRARY_PATH -x NCCL_IB_GID_INDEX=5  -np 2 -H 1.0.135.222:1,1.0.202.241:1 python tensorflow_mnist_estimator.py

The error detail:
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_session_config': gpu_options {
  allow_growth: true
  visible_device_list: "0"
}
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <te
nsorflow.python.training.server_lib.ClusterSpec object at 0x7fd337ef4590>, '_model_dir': './mnist_convnet_model', '_pro
tocol': None, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_repl
icas': 0, '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_experimental_distribute': None, '_
num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_evaluation_master': '', '_eval_distribute': Non
e, '_global_id_in_cluster': 0, '_master': ''}
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpmQyHc8
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_session_config': gpu_options {
  allow_growth: true
  visible_device_list: "0"
}
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <te
nsorflow.python.training.server_lib.ClusterSpec object at 0x7efb8c3dbbd0>, '_model_dir': '/tmp/tmpmQyHc8', '_protocol':
 None, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas':
0, '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_experimental_distribute': None, '_num_wor
ker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_evaluation_master': '', '_eval_distribute': None, '_gl
obal_id_in_cluster': 0, '_master': ''}
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/inputs/queues/feeding_queue_
runner.py:62: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a futur
e version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/inputs/queues/feeding_functi
ons.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a
 future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/inputs/queues/feeding_queue_
runner.py:62: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a futur
e version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/inputs/queues/feeding_functi
ons.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a
 future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-07-04 21:03:17.264617: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that th
is TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Graph was finalized.
2019-07-04 21:03:17.318315: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that th
is TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-04 21:03:17.633696: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:85:00.0
totalMemory: 23.90GiB freeMemory: 23.65GiB
2019-07-04 21:03:17.633875: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-07-04 21:03:18.179095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor
with strength 1 edge matrix:
2019-07-04 21:03:18.179304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-07-04 21:03:18.179368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-07-04 21:03:18.180158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:lo
calhost/replica:0/task:0/device:GPU:0 with 23072 MB memory) -> physical GPU (device: 0, name: Tesla M40 24GB, pci bus i
d: 0000:85:00.0, compute capability: 5.2)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py:804: sta
rt_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future vers
ion.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-07-04 21:03:18.695028: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Tesla M40 24GB major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:84:00.0
totalMemory: 23.90GiB freeMemory: 23.79GiB
2019-07-04 21:03:18.695155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpmQyHc8/model.ckpt.
2019-07-04 21:03:19.491182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor
with strength 1 edge matrix:
2019-07-04 21:03:19.491292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-07-04 21:03:19.492946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:lo
calhost/replica:0/task:0/device:GPU:0 with 23072 MB memory) -> physical GPU (device: 0, name: Tesla M40 24GB, pci bus i
d: 0000:84:00.0, compute capability: 5.2)
INFO:tensorflow:Restoring parameters from ./mnist_convnet_model/model.ckpt-1178
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py:804: sta
rt_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future vers
ion.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 1178 into ./mnist_convnet_model/model.ckpt.
tf1-12-m40-0:858:917 [0] NCCL INFO NET : Using interface eth0:1.0.135.222<0>
tf1-12-m40-0:858:917 [0] NCCL INFO NET/IB : Using interface eth0 for sideband communication
tf1-12-m40-0:858:917 [0] NCCL INFO NET/IB: [0] mlx4_0:2/RoCE
tf1-12-m40-0:858:917 [0] NCCL INFO Using internal Network IB
tf1-12-m40-0:858:917 [0] NCCL INFO NET : Using interface eth0:1.0.135.222<0>
tf1-12-m40-0:858:917 [0] NCCL INFO NET/Socket : 1 interfaces found
NCCL version 2.3.5+cuda9.0
tf1-12-m40-0:858:917 [0] NCCL INFO rank 0 nranks 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET : Using interface eth0:1.0.202.241<0>
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET/IB : Using interface eth0 for sideband communication
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET/IB: [0] mlx4_0:2/RoCE
tf1-12-m40-1:1840:1899 [0] NCCL INFO Using internal Network IB
tf1-12-m40-1:1840:1899 [0] NCCL INFO rank 1 nranks 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO comm 0x7efb2c3b2dc0 rank 1 nranks 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET : Using interface eth0:1.0.202.241<0>
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET/Socket : 1 interfaces found
tf1-12-m40-1:1840:1899 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(SOC)
tf1-12-m40-0:858:917 [0] NCCL INFO comm 0x7fd26838f230 rank 0 nranks 2
tf1-12-m40-0:858:917 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(SOC)
tf1-12-m40-0:858:917 [0] NCCL INFO Using 256 threads
tf1-12-m40-0:858:917 [0] NCCL INFO Min Comp Cap 5
tf1-12-m40-0:858:917 [0] NCCL INFO Ring 00 :    0   1
tf1-12-m40-0:858:917 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported by GPU)
tf1-12-m40-0:858:917 [0] NCCL INFO Ring 00 : 1 -> 0 via NET/IB/0
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported by GPU)
tf1-12-m40-1:1840:1899 [0] NCCL INFO Ring 00 : 0 -> 1 via NET/IB/0
tf1-12-m40-0:858:917 [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 5.
tf1-12-m40-0:858:917 [0] NCCL INFO NET/IB: Dev 0 Port 2 qpn 588 mtu 3 GID 5 (0/E9445864FFFF0000)
tf1-12-m40-1:1840:1899 [0] NCCL INFO NCCL_IB_GID_INDEX set by environment to 5.
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET/IB: Dev 0 Port 2 qpn 792 mtu 3 GID 5 (0/0)
                                                                                                                       
tf1-12-m40-0:858:917 [0] misc/ibvwrap.cu:284 NCCL WARN Call to ibv_modify_qp failed with error Invalid argument
tf1-12-m40-0:858:917 [0] NCCL INFO transport/net_ib.cu:406 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO transport/net_ib.cu:510 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO include/net.h:26 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO transport/net.cu:313 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO init.cu:491 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO init.cu:557 -> 2
                                                                                                                       
tf1-12-m40-1:1840:1899 [0] misc/ibvwrap.cu:284 NCCL WARN Call to ibv_modify_qp failed with error No such device or addr
ess
tf1-12-m40-1:1840:1899 [0] NCCL INFO transport/net_ib.cu:406 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO transport/net_ib.cu:510 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO include/net.h:26 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO transport/net.cu:313 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO init.cu:491 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO init.cu:557 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO rank 0 nranks 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO rank 1 nranks 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO comm 0x7efb2c3b4ec0 rank 1 nranks 2
tf1-12-m40-0:858:917 [0] NCCL INFO comm 0x7fd268391330 rank 0 nranks 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(SOC)
tf1-12-m40-0:858:917 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx4_0/2(SOC)
tf1-12-m40-0:858:917 [0] NCCL INFO Using 256 threads
tf1-12-m40-0:858:917 [0] NCCL INFO Min Comp Cap 5
tf1-12-m40-0:858:917 [0] NCCL INFO Ring 00 :    0   1
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported by GPU)
tf1-12-m40-1:1840:1899 [0] NCCL INFO Ring 00 : 0 -> 1 via NET/IB/0
tf1-12-m40-0:858:917 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx4_0 (not supported by GPU)
tf1-12-m40-0:858:917 [0] NCCL INFO Ring 00 : 1 -> 0 via NET/IB/0
tf1-12-m40-0:858:917 [0] NCCL INFO NET/IB: Dev 0 Port 2 qpn 590 mtu 3 GID 5 (0/E9445864FFFF0000)
tf1-12-m40-1:1840:1899 [0] NCCL INFO NET/IB: Dev 0 Port 2 qpn 794 mtu 3 GID 5 (0/0)
                                                                                                                       
tf1-12-m40-0:858:917 [0] misc/ibvwrap.cu:284 NCCL WARN Call to ibv_modify_qp failed with error Invalid argument
tf1-12-m40-0:858:917 [0] NCCL INFO transport/net_ib.cu:406 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO transport/net_ib.cu:510 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO include/net.h:26 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO transport/net.cu:313 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO init.cu:491 -> 2
tf1-12-m40-0:858:917 [0] NCCL INFO init.cu:557 -> 2
                                                                                                                       
tf1-12-m40-1:1840:1899 [0] misc/ibvwrap.cu:284 NCCL WARN Call to ibv_modify_qp failed with error No such device or addr
ess
tf1-12-m40-1:1840:1899 [0] NCCL INFO transport/net_ib.cu:406 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO transport/net_ib.cu:510 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO include/net.h:26 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO transport/net.cu:313 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO init.cu:491 -> 2
tf1-12-m40-1:1840:1899 [0] NCCL INFO init.cu:557 -> 2
Traceback (most recent call last):
  File "tensorflow_mnist_estimator.py", line 218, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist_estimator.py", line 205, in main
    hooks=[bcast_hook])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_de
fault
    saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_est
imator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled system error
        [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dep
endency_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:G
PU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]
                                                                                                                       
Caused by op u'DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dep
endency_1_0', defined at:
  File "tensorflow_mnist_estimator.py", line 218, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tensorflow_mnist_estimator.py", line 205, in main
    hooks=[bcast_hook])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_de
fault
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "tensorflow_mnist_estimator.py", line 122, in cnn_model_fn
    global_step=tf.train.get_global_step())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 400, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python2.7/dist-packages/horovod/tensorflow/__init__.py", line 203, in compute_gradients
    compression=self._compression)
  File "/usr/local/lib/python2.7/dist-packages/horovod/tensorflow/__init__.py", line 83, in allreduce
    summed_tensor_compressed = _allreduce(tensor_compressed)
  File "/usr/local/lib/python2.7/dist-packages/horovod/tensorflow/mpi_ops.py", line 90, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 51, in horovod_allreduce
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_h
elper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()
                                                                                                                       
UnknownError (see above for traceback): ncclCommInitRank failed: unhandled system error
        [[node DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_dense_1_BiasAdd_grad_tuple_control_dep
endency_1_0 (defined at <string>:51)  = HorovodAllreduce[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:G
PU:0"](gradients/dense_1/BiasAdd_grad/BiasAddGrad)]]
                                                                                                                       
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
                                                                                                                       
  Process name: [[44755,1],1]
  Exit code:    1

We have check the machine hostname are tf1-12-m40-0 and tf1-12-m40-1.
Can you give us some advise? Thanks.

**Comment by tgaddair** [comment]
Hey @ivankxt, can you try running with `-x NCCL_DEBUG=INFO` so we can see more details of the error?  Thanks.

**Comment by ivankxt** [comment]
> NCCL_DEBUG=INFO

Hello, I add -x NCCL_DEBUG=INFO to the script and run:

mpirun -x LD_LIBRARY_PATH -x NCCL_IB_GID_INDEX=5 -x NCCL_DEBUG=INFO -np 2 -H 1.0.135.222:1,1.0.202.241:1 python tensorflow_mnist_estimator.py

But, the error output is the same as above.

**Comment by alsrgv** [comment]
@ivankxt, could you try the same with our latest docker image (`horovod/horovod:0.16.4-tf1.14.0-torch1.1.0-mxnet1.4.1-py3.6 `) and following [these instructions](https://github.com/horovod/horovod/blob/master/docs/docker.rst#adding-mellanox-rdma-support)?  What's your OFED/MOFED version on the host?

**Comment by rajatchopra** [comment]
@ivankxt Did you get around and resolve that error?
