### ISSUE TITLE
How to differentiate NCCL-based communication with MPI-based communication

### ISSUE THREAD

**Issue by wangshuaizs** [horovod/horovod#1196]
Hi，

I installed horovod with Open MPI v4.0.0 and NCCL v2.4.7. I found that if installing horovod with `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`, then horovod is based on NCCL to communication, and if installing horovod with `HOROVOD_GPU_ALLREDUCE=MPI pip install --no-cache-dir horovod`, then horovod is based on MPI communication. 
But when running horovod based on NCCL(that is, I installed horovod with cmd `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`), if I didn't set the parameters for MPI (e.g., `UCX_NET_DEVICES`), the nodes cannot communicate with each other. But if I didn't set the parameters for NCCL (e.g., `NCCL_IB_HCA`), the nodes can still communicate normally. So I think horovod didn't use NCCL in my experiment. Is there any way to differentiate NCCL-based communication with MPI-based communication?

**Comment by tgaddair** [comment]
Hey @wangshuaizs, yes, if you take a look at the Horovod [timeline](https://github.com/horovod/horovod/blob/master/docs/timeline.rst) you should see where Horovod is using `NCCL_ALLREDUCE` vs `MPI_ALLREDUCE`, which will tell you which one is being used.

**Comment by wangshuaizs** [comment]
@tgaddair , sorry to bother, but I ran into some problems.
Without timeline, when I ran cmd `mpirun -np 2 -H 12.12.10.14:1,12.12.10.16:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x HOROVOD_MPI_THREADS_DISABLE=1 -x NCCL_SOCKET_IFNAME=eth2 -x NCCL_IB_DISABLE=1 -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_include eth2 python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --local_parameter_device=gpu --num_gpus=1 --num_batches=100 --num_warmup_batches=10 --variable_update=horovod --optimizer=sgd --batch_size=32 --model=vgg19 --horovod_device=cpu`, it  can run normally. But if I add timeline, that is, I use cmd `HOROVOD_TIMELINE=NCCL.json mpirun -np 2 -H 12.12.10.14:1,12.12.10.16:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x HOROVOD_MPI_THREADS_DISABLE=1 -x NCCL_SOCKET_IFNAME=eth2 -x NCCL_IB_DISABLE=1 -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_include eth2 python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --local_parameter_device=gpu --num_gpus=1 --num_batches=100 --num_warmup_batches=10 --variable_update=horovod --optimizer=sgd --batch_size=32 --model=vgg19 --horovod_device=cpu`, the error happend. The log is as follows:
```
$ HOROVOD_TIMELINE=NCCL.json mpirun -np 2 -H 12.12.10.14:1,12.12.10.16:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x HOROVOD_MPI_THREADS_DISABLE=1 -x NCCL_SOCKET_IFNAME=eth2 -x NCCL_IB_DISABLE=1 -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_include eth2 python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --local_parameter_device=gpu --num_gpus=1 --num_batches=100 --num_warmup_batches=10 --variable_update=horovod --optimizer=sgd --batch_size=32 --model=vgg19 --horovod_device=cpu
TensorFlow:  1.10
Model:       vgg19
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  64 global
             32 per device
Num batches: 100
Num epochs:  0.00
Devices:     ['horovod/gpu:0', 'horovod/gpu:1']
Data format: NCHW
Optimizer:   sgd
Variables:   horovod
Horovod on:  cpu
[g6-nasp:19175] *** An error occurred in MPI_Allreduce
[g6-nasp:19175] *** reported by process [4179820545,1]
[g6-nasp:19175] *** on communicator MPI COMMUNICATOR 3 DUP FROM 0
[g6-nasp:19175] *** MPI_ERR_TRUNCATE: message truncated
[g6-nasp:19175] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[g6-nasp:19175] ***    and potentially your MPI job)
TensorFlow:  1.10
Model:       vgg19
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  64 global
             32 per device
Num batches: 100
Num epochs:  0.00
Devices:     ['horovod/gpu:0', 'horovod/gpu:1']
Data format: NCHW
Optimizer:   sgd
Variables:   horovod
Horovod on:  cpu
Generating model
An MPI communication peer process has unexpectedly disconnected.  This
usually indicates a failure in the peer process (e.g., a crash or
otherwise exiting without calling MPI_FINALIZE first).

Although this local MPI process will likely now behave unpredictably
(it may even hang or crash), the root cause of this problem is the
failure of the peer -- that is what you need to investigate.  For
example, there may be a core file that you can examine.  More
generally: such peer hangups are frequently caused by application bugs
or other external events.

  Local host: g4-nasp
  Local PID:  20849
  Peer host:  12.12.10.16
```

**Comment by alsrgv** [comment]
@wangshuaizs, can you try using `-x HOROVOD_TIMELINE=NCCL.json`?  If only one rank knows about the timeline, there could be misalignment.
