### ISSUE TITLE
Does horovod support cuda8.0? If support, could you provide a docker image with cuda8.0?

### ISSUE THREAD

**Issue by yangwenhuan** [horovod/horovod#1220]

**Comment by tgaddair** [comment]
Hey @yangwenhuan, yes, Horovod should still support CUDA 8.0.  If you look back at older versions of our example Dockerfile, you'll find a version that was built with CUDA 8.0 [here](https://github.com/horovod/horovod/commit/60d778249f13c39a021e5893b00c59aa99be032c#diff-3254677a7917c6c01f55212f86c57fbf).  I would suggest modifying that with some more recent packages and see if that works.

**Comment by yangwenhuan** [comment]
@tgaddair , I have built image with cuda8.0 and openmpi3.0.0, but openmpi 3.0.0 didn't work with multi  
 machines in my cluster.

**Comment by abditag2** [comment]
@yangwenhuan what is the error message? Did you use the exact docker file?
Also, make sure to check out the same version of Horovod code from the repository.

**Comment by yangwenhuan** [comment]
@abditag2 , where is the exact docker file for cuda8.0? docker file above provided by @tgaddair is incomplete. I have tried many ways. is there something wrong with openmpi 3.0.0?

1. docker image: denisovlev/horovod:latest.       didn't work.

2. check openmpi 3.0.0 alone in my cluster.      didn't work.

3. check openmpi 4.0.0 alone in my cluster.      work.

error message is as follow:

ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).

**Comment by alsrgv** [comment]
@yangwenhuan, if openmpi-4.0.0 works for you, can you just keep using that?
