### ISSUE TITLE
Is there any peer to peer communication API?

### ISSUE THREAD

**Issue by Lyken17** [horovod/horovod#1224]
Most currently communication APIs are global operations, like allreduce / allgather. I wonder is there any peer to peer APIs, for example

```
hvd.send(tensor, dst=1, name="test") # send tensor to worker 1
tensor = hvd.recv(src=0, name="test") # recv tensor from worker 1
```

**Comment by abditag2** [comment]
Horovod currently does not have any API for peer to peer communication.

**Comment by Lyken17** [comment]
Is there any plan to add it? Since it is necessary to implement some algorithms, e.g, parameter-server.

**Comment by tgaddair** [comment]
Hey @Lyken17, do you have a use case in mind for this?  If we were to add a parameter server implementation of Horovod as an alternative to collective communication, it would be better to do that in the C++ layer rather than leave it to users to implement in the Python API.

**Comment by Lyken17** [comment]
@tgaddair Yes, I do have such user cases during the research. I agree that C++ layer implementation leads to better efficiency but Python API layer is easier to operate and access. From a researcher respective, this is important especially when you want to quickly prototype and verify an idea.

For example, pytorch shows [how to implement your own ring-allreduce](https://pytorch.org/tutorials/intermediate/dist_tuto.html#our-own-ring-allreduce) with simple python layer API (Send/Recv) without the need to involve the low-level C++ codes. With such support, I can easily hack all-reduce to implement [Deep Gradient Compression](https://arxiv.org/pdf/1712.01887.pdf) that compresses gradients by 600x without loss on accuracy. But for horovod, the only method I can access in Python API is all-gather, which consumes much more bandwidth.

**Comment by Lyken17** [comment]
I wonder the difficulty of adding the support of Recv/Send. In my understanding, these are quite common APIs in various distributed frameworks and should not affect other functions.

**Comment by tgaddair** [comment]
For the kind of experimentation you're suggesting, I would recommend using [mpi4py](https://mpi4py.readthedocs.io/en/stable/tutorial.html) (assuming you have multi-threaded MPI available to you).

The problem with doing this within Horovod is that not all frameworks support Recv/Send.  MPI does, but we are in the process of removing MPI as a strict requirement for Horovod.  Gloo, the other framework we're adding as an MPI alternative, does not support Recv/Send, nor does NCCL.

Do you think mpi4py would work for your use case?

**Comment by Lyken17** [comment]
I see. Thanks for your advice and I will have a look!
