### ISSUE TITLE
Add support for PyTorch sparse tensors

### ISSUE THREAD

**Issue by qchenclaire** [horovod/horovod#1230]
There is no device_sparse option in hvd.DistributedOptimizer. Is there any other way to force it?

**Comment by Lyken17** [comment]
Do you mean to allgather sparse tensors?

**Comment by alsrgv** [comment]
@qchenclaire, we don't currently support sparse tensors in PyTorch. We'd love to!  Do you have example use case (script) where they're useful?

**Comment by Lyken17** [comment]
@alsrgv One of my use case is to communicate with sparse gradients to reduce the bandwidth requirement, for example [Deep Gradient Compression](https://arxiv.org/abs/1712.01887).

**Comment by alsrgv** [comment]
@Lyken17, got it. We do need to add support for sparse tensors as a precondition for all that. Contributions are very welcome!

**Comment by Lyken17** [comment]
Is there any progress?

**Comment by maxhgerlach** [comment]
This has been implemented a while ago in #2580.

**Comment by Lyken17** [comment]
Great! Thanks for the pointer.
