### ISSUE TITLE
train 2 models simultaneously and separately with independent inputs

### ISSUE THREAD

**Issue by souxun2015** [horovod/horovod#1235]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.1.0
3. Horovod version: 0.16.4
4. MPI version: 2.1.1
5. CUDA version: 9.0
6. NCCL version: 2.4.2
7. Python version: 3.7.3
8. OS and version: Ubuntu 18.04.2
9. GCC version: gxx_linux-64

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
Yes, I found the similar [one](https://github.com/horovod/horovod/issues/921)

**Your question:**
I want to train 2 models separately and simultaneously, and each model will be tested after one epoch. Each model is trained by independent input and assigned in different GPUs. 

I am confusing about how to initialize the hvd and train them simultaneously.
The following code is to declare 2 models and their responding data inputs. During the training , each model will be tested by the testloader after each epoch.
```
net_cluster = {}
for i in range(2):
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=args.batch_size)
    test_loader = torch.utils.data.DataLoader(
        test_dataset, batch_size=args.test_batch_size)
    model = Net()
    optimizer = optim.SGD(model.parameters(), lr=args.lr, weight_decay=2e-4)
    model.to(torch.device('cuda', i))
    net_cluster['model{}'.format(i)] = {'model': model,
                                        'optimizer': optimizer,
                                        'device': torch.device('cuda', i),
                                        'trainloader': train_loader,
                                        'testloader': test_loader}
```
I don't know how to initialize the hvd, and train them separately and simultaneously. I can't find a example about this.

**Comment by alsrgv** [comment]
@souxun2015, this should still work fine, but you need some adjustments to your strategy:
1. Run with 2 GPUs per process, i.e. on a server with 4 GPUs, run 2 processes.
2. Assign devices based on `hvd.local_rank() * 2 + i`. This will assign GPUs 0 and 1 to process 0, and GPUs 2 and 3 to process 1.
3. Use a standard `hvd.DistributedOptimizer()`. It should work fine, e.g. see this [test case](https://github.com/horovod/horovod/blob/master/test/test_torch.py#L1148).
