### ISSUE TITLE
Distributed tensorflow benchmark

### ISSUE THREAD

**Issue by Young768** [horovod/horovod#1239]
Hi , i was testing tensorflow benchmark. I can run benchmark on single machine:

$python tf_cnn_benchmarks.py --device=CPU --batch_size=64 --model=resnet50 --variable_update=horovod --data_format=NHWC

But when I want to distribute the benchmark on two machines:
$horovodrun --start-timeout 300 --verbose -np 2 -H localhost:1,slave0:1 python tf_cnn_benchmarks.py --device=CPU --batch_size=64 --model=resnet50 --variable_update=horovod --data_format=NHWC

Do you know how to fix it?

Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Interfaces on all the hosts were successfully checked.
mpirun --allow-run-as-root --tag-output -np 2 -H localhost:1,slave0:1 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_include eth0 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 -x SPARK_HOME -x SHELL -x TERM -x HADOOP_HOME -x CONDA_SHLVL -x CONDA_PROMPT_MODIFIER -x USER -x LS_COLORS -x SUDO_USER -x CONDA_EXE -x SUDO_UID -x USERNAME -x MAVEN_OPTS -x _CE_CONDA -x MAIL -x PATH -x QT_QPA_PLATFORMTHEME -x CONDA_PREFIX -x PWD -x JAVA_HOME -x HADOOP_CLASSPATH -x LANG -x _CE_M -x SHLVL -x SUDO_COMMAND -x HOME -x LANGUAGE -x CONDA_PYTHON_EXE -x LOGNAME -x XDG_DATA_DIRS -x CONDA_DEFAULT_ENV -x LESSOPEN -x SCALA_HOME -x SUDO_GID -x DISPLAY -x LESSCLOSE -x COLORTERM -x XAUTHORITY -x _ -x OLDPWD -x _HOROVOD_SECRET_KEY python tf_cnn_benchmarks.py --device=CPU --batch_size=64 --model=resnet50 --variable_update=horovod --data_format=NHWC
[slave0:02994] [[26610,0],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[26610,0],1] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)

This is something that should be reported to the developers.
--------------------------------------------------------------------------

**Comment by abditag2** [comment]
Can you add more details about your environment? What version of Horovod, MPI, TF, CUDA?

**Comment by Young768** [comment]
Hi @abditag2  I dont know how to check my horovod version. But im usring MPI 4.0.1 and MKL TF 1.13.01

Now I can run the example you provide on both single machine or multiple machines. But I want to run the tensorflow [benchmark](https://github.com/tensorflow/benchmarks). 

I can also run their models on a single machine. But they did not provide tutorials on how to run it on multiple machines.

**Comment by Young768** [comment]
Hi @abditag2 Any luck to have your help?

**Comment by alsrgv** [comment]
@Young768, does [this section](https://github.com/horovod/horovod/blob/89121661a2eaa36e4fab8566bd4f84e2361f3469/docs/troubleshooting.rst#force-terminate-at-data-unpack-would-read-past-end-of-buffer) of our troubleshooting guide help?

**Comment by Young768** [comment]
Hi @alsrgv I think my case does not have the required installation problems. Because I can run the provided examples on both single machine or multiple machines.

I found that now tensorflow benchmarks support Horovod but there is no related tutorial.
https://github.com/tensorflow/benchmarks

Is this the correct cmd to run tensorflow benchmark on two nodes?

$horovodrun --start-timeout 300 --verbose -np 2 -H localhost:1,slave0:1 python tf_cnn_benchmarks.py --device=CPU --batch_size=64 --model=resnet50 --variable_update=horovod --data_format=NHWC

**Comment by alsrgv** [comment]
@Young768, you can find the docs here - https://horovod.readthedocs.io/en/latest/benchmarks_include.html. Your usage looks reasonable.

**Comment by Young768** [comment]
@alsrgv Oh, I found that this is the FORCE-TERMINATE AT Data unpack would read past end of buffer.

Do I need to uninstall OpenMPI and purge hwloc?

**Comment by Young768** [comment]
@alsrgv Hi, I have a quick question. If i run Horovod on multiple nodes with real dataset, e.g. CIFAR-10, do i need to replicate the dataset on every node?

**Comment by abditag2** [comment]
Yes. Horovod does not distribute the data.
You can use a shared datastore like NFS and put the data there and have all the nodes to read from there.

**Comment by Young768** [comment]
Hi @alsrgv Alex, Now I can run horovod on each node. But when I distribute the benchmark on three nodes. The error occurs. I did follow the troubleshooting section to purge hwloc and re-install openmpi. The error still exists. Do you have any ideas?


[slave0:28661] [[12426,0],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
[slave1:27619] [[12426,0],2] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[12426,0],1] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
[master:27173] 1 more process has sent help message help-errmgr-base.txt / simple-message
[master:27173] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by Young768** [comment]
@alsrgv Hi, alex. Could you please have a look at this problem? It seems one of the algorithm on MPI, recursive doubling, would require the number of nodes to be even. I am not sure if this problem is caused by that.
