### ISSUE TITLE
Should I set different seeds for different GPUs?

### ISSUE THREAD

**Issue by Oktai15** [horovod/horovod#1252]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.0
3. Horovod version: latest

I have custom loop training mode (like [that](https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist_eager.py)) and read data from tf.Dataset that I shuffled and repeated.

Should I set different seeds for different GPU's if I want to get mini-batches in random order on every gpu OR it can be without setting different seed (I mean `tf.random.set_seed(hvd.rank()`)?

**Comment by tgaddair** [comment]
Hey @Oktai15, typically we do not set the random seed when running Horovod.  By default, TensorFlow will use a random seed if you don't specify one explicitly, which should ensure that every worker gets a random batch.
