### ISSUE TITLE
Do I need to re build horovod docker to add MLNX_OFED support?

### ISSUE THREAD

**Issue by vilmara** [horovod/horovod#1255]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version: TensorFlow. Version incluided in Horovod Dockerfile
3. Horovod version: Version incluided in Horovod Dockerfile
4. MPI version: Version incluided in Horovod Dockerfile
5. CUDA version: Version incluided in Horovod Dockerfile
6. NCCL version:  Version incluided in Horovod Dockerfile
7. Python version: Version incluided in Horovod Dockerfile
8. OS and version: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-143-generic x86_64)
9. GCC version: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

**Your question:**
Hi all, I saw the new feature "Adding Mellanox RDMA support" running Horovod in Docker. So,  do I still need to build horovod to add MLNX_OFED support?, or is it enough just adding the flag `--device=/dev/infiniband `

Any way, I modified the Dockerfile to add Mellanox support as shown below, but I got some errors:

Addtion to the Dockerfile:
```
RUN wget http://www.mellanox.com/downloads/ofed/MLNX_OFED-4.6-1.0.1.1/MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.tgz && \
    tar -xzvf MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.tgz && \
    MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64/mlnxofedinstall --user-space-only --without-fw-update --all -q && \
    cd .. && \
    rm -rf MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64 && \
    rm -rf *.tgz  
```  
    
Error building the image:
```
./MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64/docs/dhcp/sles11.3/README
./MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64/docs/dhcp/sles11.3/dhcp.spec.diff
./MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64/docs/release_notes/
./MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64/docs/release_notes/ibdump_release_notes_v3.0.0.txt
./MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64/RPM-GPG-KEY-Mellanox
lsb_release is required to continue
Current operation system in not supported!
The command '/bin/bash -cu wget http://www.mellanox.com/downloads/ofed/MLNX_OFED-4.6-1.0.1.1/MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.tgz &&     tar -xzvf MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64.tgz &&     MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64/mlnxofedinstall --user-space-only --without-fw-update --all -q &&     cd .. &&     rm -rf MLNX_OFED_LINUX-4.6-1.0.1.1-ubuntu16.04-x86_64 &&     rm -rf *.tgz' returned a non-zero code: 1

```

**Comment by byronyi** [comment]
> lsb_release is required to continue
< Current operation system in not supported!

You should consult your RDMA vendor, e.g. Mellanox, on this subject matter.

Take an example here: https://github.com/Mellanox/mofed_dockerfiles/blob/master/Dockerfile.ubuntu16.4.mofed-4.4

**Comment by vilmara** [comment]
hi @byronyi , thanks for your reply. I solved it by adding the instruction `RUN apt-get update && apt-get install -y lsb-core`.

About my first question.  I saw the new feature "Adding Mellanox RDMA support" running Horovod in Docker. So, do I still need to build horovod to add MLNX_OFED support?, or is it enough just adding the flag --device=/dev/infiniband?

**Comment by byronyi** [comment]
No, RDMA support doesn’t need re-build; NCCL dynamically loads the library of it finds one.

Passing the dev node shall suffice.

**Comment by vilmara** [comment]
@byronyi , is this a new feature?, in the past I rebuilt the dockerfile to add MLNX_OFED support as explained here **Add RDMA instructions to Dockerfile** #1150

**Comment by byronyi** [comment]
> @byronyi , is this a new feature?, in the past I rebuilt the dockerfile to add MLNX_OFED support as explained here **Add RDMA instructions to Dockerfile** #1150

No, this is not new; if you look into NCCL source code you will find the dynamic loading code: https://github.com/NVIDIA/nccl/blob/master/src/misc/ibvwrap.cc#L59-L66
