### ISSUE TITLE
Warning Message for OpenMPI

### ISSUE THREAD

**Issue by abidmalikwaterloo** [horovod/horovod#1260]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
Pytorch
2. Framework version:
1
3. Horovod version:
1.14
4. MPI version:
IBM OpenMPI
5. CUDA version:
9
6. NCCL version:
2
7. Python version:
3.6
8. OS and version:
Linux
9. GCC version:
7
**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

I am getting the following message:

[2019-07-29 12:27:01.682718: W horovod/common/operations.cc:897] MPI has already been initialized without multi-threading support (MPI_THREAD_MULTIPLE). This will likely cause a segmentation fault.

Is it safe?

**Comment by Himscipy** [comment]
Any answers to the question facing similar issues.

**Comment by tgaddair** [comment]
Hey @abidmalikwaterloo @Himscipy how are you initializing MPI?  Does your installation support multi-threading, and if so, can you initialize with `MPI_THREAD_MULTIPLE`?  Horovod runs a separate background thread for MPI ops and if your MPI does not support multi-threading it could segfault.

**Comment by Himscipy** [comment]
Hey @tgaddair , I use `hvd.init()` only once in my code and I see this warning getting printed.
I also saw this when, I had `hvd.init()` and `mpi4py` both in my code, even after shutting off my `mpi4py 
 comm` I see this message.

**Comment by tgaddair** [comment]
Hey @Himscipy have you tried running `hvd.init(comm)` with your existing communicator?

**Comment by denfromufa** [comment]
I see the same warning with pytorch at least.

**Comment by denfromufa** [comment]
Does HOROVOD_MPI_THREADS_DISABLE=1 solve this?
