### ISSUE TITLE
When Horovod is installed using HOROVOD_GPU_ALLREDUCE=NCCL what is used for cross machines communication?

### ISSUE THREAD

**Issue by aaron276h** [horovod/horovod#1262]
When we install Horovod using `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`, what is used for cross machine commutation NCCL or MPI?

**Comment by tgaddair** [comment]
Hey @aaron276h, NCCL is used for inter-node (cross machine) allreduce as well as intra-node allreduce.

**Comment by aaron276h** [comment]
@tgaddair Thanks!
