### ISSUE TITLE
Does docker support only cpu run?

### ISSUE THREAD

**Issue by jimmy-walker** [horovod/horovod#1277]
**Environment:**
1. Docker with the project provided

**Your question:**
I have used docker the project provided. Cause I have no GPU, I wanna use the CPU instead.
But it always show the error:"Attempting to fetch value instead of handling error Internal: no CUDA devices found".
So I wanna ask a question, does the docker support only cpu run?

**Comment by wlzzZ** [comment]
the file Docker.test.cpu would help you

**Comment by wlzzZ** [comment]
The Dockfile.test.cpu would help you~

**Comment by zhonghual1206** [comment]
but use  Dockfile.test.cpu i always build failed 
tensorflow 1.14.1
python 3.6

Error ：
/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:191: UserWarning:
!! WARNING !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (/usr/bin/g++-4.8 4.8) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.
See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! WARNING !!
warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
INFO: Compiler /usr/bin/g++-4.8 (version 4.8.5) is not usable for this PyTorch installation, see the warning above.
INFO: Compilers /usr/bin/gcc and /usr/bin/g++ (version 7.4.0) selected for PyTorch plugin build.
CMake Error: The source directory "/tmp/pip-req-build-7s3qro0i/third_party/gloo" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
INFO: Unable to build PyTorch plugin, will skip it.
Traceback (most recent call last):
File "/tmp/pip-req-build-7s3qro0i/setup.py", line 1389, in build_extensions
build_torch_extension_v2(self, options, torch_version)
File "/tmp/pip-req-build-7s3qro0i/setup.py", line 1299, in build_torch_extension_v2
build_cmake(build_ext, gloo_lib, 'torchv2', gloo_abi_flag, options, torch_mpi_lib_v2)
File "/tmp/pip-req-build-7s3qro0i/setup.py", line 1351, in build_cmake
cwd=build_temp)
File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-7s3qro0i/third_party/gloo', '-DUSE_MPI=ON', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CXX_FLAGS_RELEASE:STRING=-D_GLIBCXX_USE_CXX11_ABI=0', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-7s3qro0i/build/lib.linux-x86_64-3.6', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-7s3qro0i/build/temp.linux-x86_64-3.6/lib/torchv2']' returned non-zero exit status 1.
CMake Error: The source directory "/tmp/pip-req-build-7s3qro0i/third_party/gloo" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
INFO: Unable to build MXNet plugin, will skip it.
Traceback (most recent call last):
File "/tmp/pip-req-build-7s3qro0i/setup.py", line 1403, in build_extensions
build_mx_extension(self, options)
File "/tmp/pip-req-build-7s3qro0i/setup.py", line 998, in build_mx_extension
build_cmake(build_ext, gloo_lib, 'mxnet', [], options=options)
File "/tmp/pip-req-build-7s3qro0i/setup.py", line 1351, in build_cmake
cwd=build_temp)
File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-7s3qro0i/third_party/gloo', '-DUSE_MPI=ON', '-DCMAKE_BUILD_TYPE=Release', "-DCMAKE_CXX_FLAGS_RELEASE:STRING=''", '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-7s3qro0i/build/lib.linux-x86_64-3.6', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-7s3qro0i/build/temp.linux-x86_64-3.6/lib/mxnet']' returned non-zero exit status 1.
error: None of TensorFlow, PyTorch, or MXNet plugins were built. See errors above.
Running setup.py install for horovod: finished with status 'error'
Cleaning up...
Removing source in /tmp/pip-req-build-7s3qro0i
Removed build tracker '/tmp/pip-req-tracker-ajwmqxou'
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7s3qro0i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7s3qro0i/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uyersz6_/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
Exception information:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 188, in main
status = self.run(options, args)
File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 407, in run
use_user_site=options.use_user_site,
File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
**kwargs
File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 959, in install
spinner=spinner,
File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 931, in call_subprocess
raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7s3qro0i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7s3qro0i/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uyersz6_/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
Removing intermediate container 0ff8fb0e3aed
The command '/bin/bash -cu if [[ ${MPI_KIND} == "MLSL" ]]; then if [ -z "${LD_LIBRARY_PATH:-}" ]; then export LD_LIBRARY_PATH=""; fi; if [ -z "${PYTHONPATH:-}" ]; then export PYTHONPATH=""; fi; source /usr/local/mlsl/intel64/bin/mlslvars.sh "thread"; echo "pip install horovod, mpicxx is $(which mpicxx)"; pip install -v /horovod/dist/horovod-*.tar.gz; else pip install -v /horovod/dist/horovod-*.tar.gz; fi' returned a non-zero code: 1


thank you for your help！

**Comment by wlzzZ** [comment]
The g++ version seems not to be compatible.

**Comment by alsrgv** [comment]
@jimmy-walker, @zhonghual1206, it seems like you don't have Git submodules cloned.  Can you re-clone with `--recursive`?

**Comment by zhonghual1206** [comment]
> @jimmy-walker, @zhonghual1206, it seems like you don't have Git submodules cloned. Can you re-clone with `--recursive`?

ok, i will try  thank you very much !

**Comment by zhonghual1206** [comment]
> The g++ version seems not to be compatible.

i had try anthoner g++ vesion but also not work. thanks for your review

**Comment by plenari** [comment]
Thanks

**Comment by plenari** [comment]
How to start horovodrun when only cpus?

**Comment by apdullahyayik** [comment]
I have just cloned using `$ git clone --recursive https://github.com/horovod/horovod.git` like @alsrgv said and it worked! Thank you @alsrgv

**Comment by apdullahyayik** [comment]
@plenari clone repo like above, then run `docker build -f .\docker\horovod-cpu\Dockerfile .`, that is all. This issue can be closed now.
