### ISSUE TITLE
Attribute error with horovod_broadcast

### ISSUE THREAD

**Issue by Griffbo99** [horovod/horovod#1280]
Hey, 

When trying to run a program i run into this issue:

File "/lib/python3.7/site-packages/horovod/tensorflow/mpi_ops.py", line 155, in broadcast
    return MPI_LIB.horovod_broadcast(tensor, name=name, root_rank=root_rank)
AttributeError: module '670cc8cfec5b6d3b8635f39bd583d769' has no attribute 'horovod_broadcast'

I have no clue what this is referring to and any sort of help would be greatly appreciated.

Thanks!

**Comment by llango** [comment]
I have the same problem. Who has a solution
