### ISSUE TITLE
Why Horovod doesn't have compute and communication overlap when XLA is used?

### ISSUE THREAD

**Issue by LiweiPeng** [horovod/horovod#1283]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 1.14
3. Horovod version: 0.16.4
4. MPI version: 3.1.1
5. CUDA version: 10.0
6. NCCL version: 2.4.7
7. Python version: 2.7.5
8. OS and version: CentOS 7.4
9. GCC version: 4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I used horovod to train distributed BERT model using nvidia's src code at https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/LanguageModeling/BERT.  I found when XLA is not used, horovod+bert has very good scalability (~1.92x from 1 to 16 GPUs). nvprof shows that there is good compute and communication (shown as 'mem' in the screenshot below) overlap, as expected.

NOTE: the screenshots below are nvprof results for a whole step.

![bert-no-xla](https://user-images.githubusercontent.com/8562078/62654697-366bd880-b915-11e9-8577-d81c2f884cc9.png)

However, when XLA is used, horovod+bert has much worse scalability (~1.8x from 1 to 16 GPUs). nvprof shows that there is little compute and communication overlap. 

![bert-xla](https://user-images.githubusercontent.com/8562078/62654709-3bc92300-b915-11e9-9c7b-7ecee429f372.png)

My question is: What caused this no compute and communication overlap when XLA is used?

**Comment by luomai** [comment]
@LiweiPeng Hi Liwei, did you resolve this issue?
