### ISSUE TITLE
No module named horovod.run  when running on nvidia-docker

### ISSUE THREAD

**Issue by tohmas19** [horovod/horovod#1287]
**Environment:**
1. Framework: Keras
2. Framework version: 2.2.4
3. Horovod version: 0.16.4
4. MPI version:
5. CUDA version: 10.1
6. NCCL version: 
7. Python version: 2.7
8. OS and version: Ubuntu 16.04
9. GCC version:

**Checklist:**
1. Did you sear ch issues to find if somebody asked this question before?
   yes.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
  yes.
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
  I followed the explanation. But I couldn't run on multiple  machines.
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?
   yes.

**Your question:**
I installed horovod using docker. It can run on localhost. However, it can't run on multiple machines on my local network.

On the Primary worker,
`$ sudo nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest`
`# horovodrun -np 1 -H host1:1 -p 45405 python keras_mnist.py`

On the Secondary worker,
`sudo nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest \
    bash -c "/usr/sbin/sshd -p 45405; sleep infinity"`

and I got
`$ Launching horovodrun task function was not successful:
/usr/bin/python: No module named horovod.run`

I think that SSH is because the docker containers are not connected.
But I can't solve it myself.  Please help me.

**Comment by aonrdbit** [comment]
I encountered the same problem, did you solve it?

**Comment by tohmas19** [comment]
I solved it by setting passwordless SSH between PCs in the Root user.
