### ISSUE TITLE
Horovod single server multi gpu pytorch using same gpu

### ISSUE THREAD

**Issue by garyshincc** [horovod/horovod#1293]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.1.0
3. Horovod version: 0.16.4
4. MPI version: 2.1.1
5. CUDA version: 10.1
6. NCCL version: N/A
7. Python version: 3.6.8
8. OS and version: Ubuntu 18.04
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

I'm trying to run horovod pytorch on a single server, with 2 gpus.
I set up a test to make sure its using 2 gpu's, not one as follows:
`
import torch
import horovod.torch as hvd
hvd.init()

print(f"Num devices: {torch.cuda.device_count()}")
print("rank:", hvd.rank())
torch.cuda.set_device(hvd.local_rank())
print(torch.cuda.current_device())
`
run with:
$ horovodrun -np 2 -H localhost:2 python3 test.py

outputs:
[1,0]<stdout>:Num devices: 2
[1,0]<stdout>:rank: 0
[1,0]<stdout>:0
[1,1]<stdout>:Num devices: 2
[1,1]<stdout>:rank: 0
[1,1]<stdout>:0

meaning that both processes are using the same GPU.
I also ran the command
$ CUDA_VISIBLE_DEVICES=1,2

Could you please help on this issue?

**Comment by tgaddair** [comment]
Hey @garyshincc, looks like MPI is launching completely separate processes, as each process has rank 0.  This can happen if you somehow have multiple versions of MPI installed on your system (see [this](https://stackoverflow.com/questions/4039608/why-do-all-my-open-mpi-processes-have-rank-0) SO answer for suggestions on how to debug).

I would also suggest upgrading to OpenMPI v3 or v4, and unsetting `CUDA_VISIBLE_DEVICES`.
