### ISSUE TITLE
Horovod without MPI (using only Gloo)

### ISSUE THREAD

**Issue by 5hubh4m** [horovod/horovod#1296]
I'm in an environment without MPI so I'm trying to build Horovod with Gloo support without using MPI. I'm building with `HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_MPI=1 python setup.py bdist_wheel && HOROVOD_WITH_TORCH=1 pip install dist/horovod-0.16.4-cp36-cp36m-linux_x86_64.whl -U` but when I try to test it, it throws the following error:

```
$ python -c 'import horovod.torch'
Traceback (most recent call last):
  File "/home/gandiva/horovod/horovod/torch/__init__.py", line 27, in <module>
    __file__, 'mpi_lib_v2')
  File "/home/gandiva/horovod/horovod/common/util.py", line 47, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gandiva/horovod/horovod/torch/__init__.py", line 30, in <module>
    __file__, 'mpi_lib', '_mpi_lib')
  File "/home/gandiva/horovod/horovod/common/util.py", line 47, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.
```

Can anyone help me out?

**Environment:**
1. Framework: PyTorch
2. Framework version: 1.1.0
3. Horovod version: master/HEAD
4. MPI version: N/A
5. CUDA version: 10.0
6. NCCL version: 2.6.2
7. Python version: 3.6.8
8. OS and version: Ubuntu 16.04
9. GCC version: 5.4.0

**Comment by alsrgv** [comment]
@5hubh4m, can you try installing with `HOROVOD_WITH_PYTORCH=1`? It should catch the error and help debug.

cc @tgaddair @zsh-thu

**Comment by 5hubh4m** [comment]
> @5hubh4m, can you try installing with `HOROVOD_WITH_PYTORCH=1`? It should catch the error and help debug.
> 
> cc @tgaddair @zsh-thu

I've done this already, as I mentioned in the original post. But for clarity, here's the output from `pip install`. 

```
$ HOROVOD_WITH_TORCH=1 pip install dist/horovod-0.16.4-cp36-cp36m-linux_x86_64.whl  -U
Processing ./dist/horovod-0.16.4-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied, skipping upgrade: cffi>=1.4.0 in /opt/conda/lib/python3.6/site-packages (from horovod==0.16.4) (1.12.3)
Requirement already satisfied, skipping upgrade: cloudpickle in /opt/conda/lib/python3.6/site-packages (from horovod==0.16.4) (1.2.1)
Requirement already satisfied, skipping upgrade: six in /opt/conda/lib/python3.6/site-packages (from horovod==0.16.4) (1.12.0)
Requirement already satisfied, skipping upgrade: psutil in /opt/conda/lib/python3.6/site-packages (from horovod==0.16.4) (5.6.2)
Requirement already satisfied, skipping upgrade: pycparser in /opt/conda/lib/python3.6/site-packages (from cffi>=1.4.0->horovod==0.16.4) (2.19)
Installing collected packages: horovod
  Found existing installation: horovod 0.16.4
    Uninstalling horovod-0.16.4:
      Successfully uninstalled horovod-0.16.4
Successfully installed horovod-0.16.4
```

**Comment by 5hubh4m** [comment]
Figured it out. I was executing `python` from within `/horovod` which with preventing it from picking the module from the `PYTHONPATH`.

**Comment by tgaddair** [comment]
@5hubh4m, what Alex is saying is that you should try setting `HOROVOD_WITH_PYTORCH=1`, you're setting `HOROVOD_WITH_TORCH=1`, which is not the same thing.

**Comment by tgaddair** [comment]
Hey @5hubh4m, is this issue resolved?  I see you had a comment here previously:

> Figured it out. I was executing python from within /horovod which with preventing it from picking the module from the PYTHONPATH.

But that comment has since been deleted somehow.
