### ISSUE TITLE
DUPLICATE_NAME_ERROR when broadcast variables

### ISSUE THREAD

**Issue by passerbyd** [horovod/horovod#1306]
**Environment:**
1. Framework: TensorFlow 
2. Framework version: 1.13
3. Horovod version: 0.16.1
4. MPI version: 4.0.0
5. CUDA version: 9
6. NCCL version: 2.1.15
7. Python version: 3.6
8. OS and version: centOS 7
9. GCC version: 4.9

**Bug report:**
When running broadcast op, "DUPLICATE_NAME_ERROR" is returned in TensorQueue::AddToTensorQueue function. There is no problem in calling allreduce op. The codes are running well before.

**Comment by alsrgv** [comment]
@passerbyd, could you try it again with the latest Horovod version?  Also, which broadcast ops are you using, are you using BroadcastGlobalVariablesHook() or something else?

**Comment by passerbyd** [comment]
@alsrgv 
Days spent on this problem, tried different horovod and tensorflow versions to find which modification cause it.
BroadcastGlobalVariablesHook in the demo use an empty device for the broadcast op, which works well in local_server mode. But if in distributed TF mode(ps-workers), the empty device will place all the ops on worker:0, which causes DUPLICATE_NAME_ERROR.
And as the processes run independent, in some cases, an empty broadcast op triggered first. Then there is no error but variables are inconsistent. which makes the problem more weired. 
If there is an outer device chooser, which selects a local device for the broadcast op, the problem will be avoid.
There could be a specified device in the demo maybe, to clear that the ops are placed appropriately.

**Comment by alsrgv** [comment]
What was the use case that required parameter server usage with Horovod? Normally, you don't need them.

________________________________

**Comment by passerbyd** [comment]
normally yes, so there is little information about this problem.
In my case, I need a shared_name queue as a message queue among the session. I do not use PS for sync variables.

**Comment by alsrgv** [comment]
I see, I wonder if you could accomplish similar results with [mpi4py](https://mpi4py.readthedocs.io/en/stable/index.html) instead of parameter servers.
