### ISSUE TITLE
Can no longer use IP for remote hostnames

### ISSUE THREAD

**Issue by kangp3** [horovod/horovod#1325]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
TensorFlow

2. Framework version:
`1.14.0`

3. Horovod version:
`0.17.0.post1`

4. MPI version:
`4.0.0`

5. CUDA version:
`10.0`

6. NCCL version:
`2.4.2-1+cuda10.0`

7. Python version:
`3.6.8`

8. OS and version:
`Ubuntu 18.04.1 LTS`

9. GCC version:
`g++-4.8 4.8.5-4ubuntu8`

**Bug report:**
Previously, we were able to use IPs to specify remote hosts, but since `0.17.0` (specifically [#1181](https://github.com/horovod/horovod/pull/1181/files#diff-202497121925143c32fd281b782c3d52R347-R363)) it seems that this functionality was removed. It's more convenient for us to continue to use raw IPs, so would it be possible to bring that functionality back?

```
# horovodrun --verbose -np 1 -H 10.0.0.3:1 -p 12345 python /horovod/examples/keras_mnist.py
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/run.py", line 396, in run
    raise ValueError('Invalid host input, please make sure it has '
ValueError: Invalid host input, please make sure it has format as : worker-0:2,worker-1:2.
```

**Comment by alsrgv** [comment]
Fixed by #1327
