### ISSUE TITLE
Neither MPI nor Gloo support has been built

### ISSUE THREAD

**Issue by oskotsky** [horovod/horovod#1329]
I am trying to install horovod on aws ami ec2 instance.
I have open mpi installed and added to the path:
[ec2-user@ip-10-0-9-178 ~]$ mpicxx --show
g++ -I/opt/ompi/include -pthread -Wl,-rpath -Wl,/opt/ompi/lib -Wl,--enable-new-dtags -L/opt/ompi/lib -lmpi
[ec2-user@ip-10-0-9-178 ~]$ sudo mpicxx --show
g++ -I/opt/ompi/include -pthread -Wl,-rpath -Wl,/opt/ompi/lib -Wl,--enable-new-dtags -L/opt/ompi/lib -lmpi

and I don't get any errors during horovod installation (pip) however when I run test:

[ec2-user@ip-10-0-9-178 ~]$ horovodrun -np 1 python36 train.py  --verbose
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/run.py", line 503, in run
    raise ValueError('Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that '
ValueError: Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that either MPI is installed (MPI) or CMake is installed (Gloo).

tried installation different ways  

sudo HOROVOD_WITH_MPI=1 pip-3.6 install horovod --no-cache-dir 
or
sudo pip-3.6 install horovod --no-cache-dir   
no luck. 

please help

Thank you

**Comment by oskotsky** [comment]
looks like default version horovod-0.17.0.post1 is the problem
it looks better with older 0.16.4

**Comment by oskotsky** [comment]
horovod==0.17.0 works as well but his different problem 
ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.

even if horovod was installed with tensorflow

**Comment by tgaddair** [comment]
Hey @oskotsky, can you clarify something: were you able to get this working with v0.17.0.post1, or did you need to roll back?  If it's not working with the latest release, we should keep this issue open and find a solution for you.

**Comment by oskotsky** [comment]
correct - v0.17.0.post1 totally failed for me. I installed with horovod==0.17.0 and things look better. I am running test on the single host so far and planning to try on the cluster. What is the difference between v0.17.0.post1 and v.0.17.0?

**Comment by tgaddair** [comment]
The main difference is https://github.com/horovod/horovod/commit/bab1f83a769d5cdd5ae22141559dab4a3fe3c460, which adds subprocess isolation to check which frameworks are installed.  It looks like somehow the subprocesses are failing to return the correct values to you.

Using `0.17.0.post1`, what happens if you run `mpirun -np 1 python36 train.py --verbose` instead of `horovodrun`?

**Comment by alsrgv** [comment]
@oskotsky, I've started https://github.com/horovod/horovod/pull/1332 to help debug this further.  Could you re-install Horovod via `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir git+https://github.com/horovod/horovod@verbose_check_build`, run `horovodrun --check-build --verbose`, and share the full output?

**Comment by oskotsky** [comment]
I think I found the reason for the failure. Please correct me if I am wrong.
I am installing horovod on aws ec2 p2 type (gpu). The instance has gpu but doesn't have nvidia drivers for it (I wrongly assumed that since it 2 type the instance has everything installed). However, installation tensroflow and horovod works even without cuda(?). When I manually installed drivers for gpu   v0.17.0.post1 seems to be working fine. What I saw before working with v.0.17.0 was training code running on cpu not gpu. Sorry for bothering you as it seems like my mistake.

**Comment by alsrgv** [comment]
@oskotsky, gotcha! No problem, glad it's working now.

**Comment by oskotsky** [comment]
Thank you! Will see what problems I will have when I move to cluster from single instance. ;)

**Comment by Oktai15** [comment]
This problem can be caused by install pytorch while horovod was already installed for tensorflow (or vice versa). It can be fixed not only uninstall pytorch (tensorflow), but also downgrade other dependencies (if you use `conda`, see `conda list --revisions`).
