### ISSUE TITLE
Call HorovodAllreduce independently without training

### ISSUE THREAD

**Issue by HongmingHUANG** [horovod/horovod#1330]
Hello
I want to do some performance analyzing experiment that just call HorovodAllreduce() like a communication library without training a model. Is there any documents or guidance about howto achieve that? There seems to be so many environment variables to set.
E.g. I will just define a tensor on 2 GPU and call HorovodAllreduce() to aggregate them.

**Comment by tgaddair** [comment]
Hey @HongmingHUANG, you can take a look at our [unit tests](https://github.com/horovod/horovod/blob/master/test/test_tensorflow.py#L184) for examples of how to call `hvd.allreduce` to aggregate tensors without training a model.

**Comment by HongmingHUANG** [comment]
Thanks a lot, I can run it now~
