### ISSUE TITLE
horovodrun times out but mpirun works

### ISSUE THREAD

**Issue by oskotsky** [horovod/horovod#1338]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version: 1.14
3. Horovod version: 0.17.1
4. MPI version: Open MPI: 4.0.1
5. CUDA version: 396.26
6. NCCL version: 2.2.13
7. Python version: 3.6
8. OS and version: Amazon Linux
9. GCC version: 4.8.5

mpirun -np 2 -H localhost:1,10.0.7.54:1 python3 train.py runs fine

the same command through horovod:
horovodrun -np 2 -H localhost:1,10.0.7.54:1 python3 train.py fails (timeout):
Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers.

the single version:
horovodrun -np 1 -H localhost:1 python3 train.py
runs on both instances

Please help.

**Comment by alsrgv** [comment]
Can you add --verbose flag and possibly --start-timeout 60?

________________________________

**Comment by oskotsky** [comment]
doesn't help :(

[hadoop@ip-10-0-13-220 tmp]$ horovodrun -np 2 -H localhost:1,10.0.7.54:1 python3 train.py --start-timeout 60 --verbose
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/run.py", line 471, in run
    settings, fn_cache=fn_cache)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/util/cache.py", line 103, in wrap_f
    results = func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/run.py", line 223, in _driver_fn
    driver.wait_for_initial_registration(settings.timeout)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/common/service/driver_service.py", line 117, in wait_for_initial_registration
    timeout.check_time_out_for('tasks to start')
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/common/util/timeout.py", line 32, in check_time_out_for
    raise Exception(self._message.format(activity=activity))
Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers.
[hadoop@ip-10-0-13-220 tmp]$

**Comment by alsrgv** [comment]
Can you add those before word "python"? Otherwise, they're passed as arguments to your training script instead of Horovodrun

________________________________

**Comment by oskotsky** [comment]
oops.. this looks better
[hadoop@ip-10-0-13-220 tmp]$ horovodrun -np 2 -H localhost:1,10.0.7.54:1 --start-timeout 60 --verbose python3 train.py
Filtering local host names.
Remote host found: 10.0.7.54
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Launching horovodrun task function was not successful:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/task_fn.py", line 67, in <module>
    _task_fn(index, driver_addresses, settings)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/task_fn.py", line 31, in _task_fn
    task.wait_for_initial_registration(settings.timeout)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/common/service/task_service.py", line 110, in wait_for_initial_registration
    timeout.check_time_out_for('tasks to start')
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/common/util/timeout.py", line 32, in check_time_out_for
    raise Exception(self._message.format(activity=activity))
Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers.

[hadoop@ip-10-0-13-220 tmp]$

**Comment by oskotsky** [comment]
could it be NCCL related?

**Comment by oskotsky** [comment]
oh well, doesn't look like it is about NCCL but I had to try it - reinstalled horovod with 
sudo HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/usr/local/nccl HOROVOD_WITH_TENSORFLOW=1 pip-3.6 --no-cache-dir install horovod

not luck and I am stuck - mpirun works but horovod doesn't

**Comment by oskotsky** [comment]
while horovodrun trying to start a job on remote server:

horovodrun -np 1 -H 10.0.8.81:1 --verbose 4 python3 train.py --mpi

that server 10.0.8.81 sees request:

[hadoop@ip-10-0-8-81 ~]$ ps aux | grep horovod*
hadoop    3143  2.0  0.0 582180 17144 ?        Ssl  07:02   0:00 /usr/bin/python3.6 -m horovod.run.task_fn gASVAwAAAAAAAABLAC4= gASVfwAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTR6qhpRhjARldGgwlF2UjAkxMC4wLjYuODSUTR6qhpRhjAdkb2NrZXIwlF2UjAoxNzIuMTcuMC4xlE0eqoaUYYwPYnItZjIxZGY3ZThhNzEzlF2UjAoxNzIuMTguMC4xlE0eqoaUYXUu gASV4AEAAAAAAACMIGhvcm92b2QucnVuLmNvbW1vbi51dGlsLnNldHRpbmdzlIwIU2V0dGluZ3OUk5QpgZR9lCiMB3ZlcmJvc2WUSwKMCHNzaF9wb3J0lE6MA2tleZRDIKIIjty0vjfO10B5MFn9rBcDroBx4Ip0GzKFOYlJdGuZlIwHdGltZW91dJSMH2hvcm92b2QucnVuLmNvbW1vbi51dGlsLnRpbWVvdXSUjAdUaW1lb3V0lJOUKYGUfZQojAtfdGltZW91dF9hdJRHQddYOEJKf+WMCF9tZXNzYWdllIyhVGltZWQgb3V0IHdhaXRpbmcgZm9yIHthY3Rpdml0eX0uIFBsZWFzZSBjaGVjayBjb25uZWN0aXZpdHkgYmV0d2VlbiBzZXJ2ZXJzLiBZb3UgbWF5IG5lZWQgdG8gaW5jcmVhc2UgdGhlIC0tc3RhcnQtdGltZW91dCBwYXJhbWV0ZXIgaWYgeW91IGhhdmUgdG9vIG1hbnkgc2VydmVycy6UdWKMCW51bV9ob3N0c5RLAYwIbnVtX3Byb2OUSwGMBWhvc3RzlIwLMTAuMC44LjgxOjGUjAdjb21tYW5klF2UKIwBNJSMB3B5dGhvbjOUjAh0cmFpbi5weZSMBS0tbXBplGV1Yi4=
hadoop    3165  0.0  0.0 110516  2172 pts/0    S+   07:02   0:00 grep --color=auto horovod*
[hadoop@ip-10-0-8-81 ~]$

but some how the next step doesn't happen.

**Comment by oskotsky** [comment]
i uninstalled 0.17.1 and installed 0.17.0 
now mpirun -np 3 -H localhost:1,10.0.12.32:1,10.0.7.77:1 python3 train.py  works 

but horovodrun does different thing:
[hadoop@ip-10-0-7-187 ~]$ horovodrun -np 3 -H localhost:1,10.0.12.32:1,10.0.7.77:1 python3 train.py
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/run.py", line 396, in run
    raise ValueError('Invalid host input, please make sure it has '
ValueError: Invalid host input, please make sure it has format as : worker-0:2,worker-1:2.
[hadoop@ip-10-0-7-187 ~]$

**Comment by alsrgv** [comment]
@oskotsky, were you able to resolve your issue?

**Comment by Ricahrd-Li** [comment]
I meet the same problem but I'm NOT using container.

Framework: mxnet-cu101
Horovod version: 0.19.0
MPI version: Open MPI: 3.1.2
CUDA version: 10.1
NCCL version: 2.4.2
Python version: 3.6.8
OS and version: linux 3.10.0-957.21.2.el7.x86_64
GCC version: 5.4.0
After execuate:
`NCCL_SOCKET_IFNAME=xxxxxx horovodrun -np 2 -H gpu15:1,gpu16:1  --start-timeout 60 --verbose python3 xxx`
I get 
`Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers.`

but mpirun works.

**Comment by Ricahrd-Li** [comment]
I just found that if I set --start-timeout be 300, then it works. Sorry for bothering you.

**Comment by loveunk** [comment]
> I just found that if I set --start-timeout be 300, then it works. Sorry for bothering you.

 Same issue here, I am trying to set the timeout as 300.

**Comment by maqy1995** [comment]
I met the same issue and my environment is standalone. In my environment, the reason for 'timed out' is that the time between the servers is not synchronized. After using the `date` command to synchronize the time, the problem was solved
