### ISSUE TITLE
Launching horovodrun task function was not successful

### ISSUE THREAD

**Issue by beizhengren** [horovod/horovod#1340]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)PyTorch
2. Framework version:1.2.0
3. Horovod version:latest
4. MPI version:
5. CUDA version:10.0
6. NCCL version:2.4.8
7. Python version:3.7.2
8. OS and version:ubuntu18.04
9. GCC version:7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?yes

**Your question:**
Please ask your question here.
- 1.what should I do?
When I can run only process in my own machine
```
$horovodrun -np 1 -H localhost:1 python train.py 
``` 
But when run 2 process in two machine, an error existed
```
$ horovodrun -np 2 -H 192.168.10.51:1,192.168.10.105:1 python train.py  

Launching horovodrun task function was not successful:
bash: /home/wyz/.pyenv/versions/3.7.2/envs/env-3.7.2/bin/python3.7: No such file or directory
```
- 2.Should I install the environment (for instance, horovod, framework, ... ) in all the machine?
or I only install the environment in my own machine.  

Thank you so much!

**Comment by chldmstj** [comment]
I have same problem.
how did you fix it?

**Comment by 972461099** [comment]
hello,can you tell me how did you fix it?

**Comment by Ricahrd-Li** [comment]
I also want to ask for a solution, thx!

**Comment by Ricahrd-Li** [comment]
I find a solution. Just have all the paths of python3 on your servers be the same. For example, I use 2 servers gpu1 and gpu2, then I have the same python3 path that `horovod_venv/bin/python3"`.

**Comment by chaochaoSZ** [comment]
Have you already soloved the problem? I also meet the same problem when I want to run on two different servers.

**Comment by beizhengren** [comment]
@chaochaoSZ @972461099 @chldmstj 
Sorry for the late reply.Make sure that two servers have the same environment will help.
