### ISSUE TITLE
terminate called after throwing an instance of 'gloo::EnforceNotMet'   ifa != nullptr. Unable to find address for: eth0

### ISSUE THREAD

**Issue by khayamgondal** [horovod/horovod#1341]
hvd.init() throws following error
```
>>> hvd.init()
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /tmp/pip-install-3dvzdqhs/horovod/third_party/gloo/gloo/transport/tcp/device.cc:88] ifa != nullptr. Unable to find address for: eth0
Aborted
```
What I understand is that gloo is hardcoded to check for eth0 and in my case (Centos 7.6) I have em1 and em2. I came acrros solution to export the below env variables but i am still seeing the issue
```
export GLOO_SOCKET_IFNAME=em2
export NCCL_SOCKET_IFNAME=em2
```
How can I get pass this?

**Environment:**
Framework:  Keras
Tensorflow Version 1.13.1
Keras Version 2.2.4-tf
Horovod version: horovod==0.17.0.post1
Python version: 3.6

**Comment by tgaddair** [comment]
Hey @khayamgondal, can you try setting `HOROVOD_GLOO_IFACE=em2` instead?  Apologies that this is not better documented, I'll add some docs to explain this (and perhaps we can even auto-detect this similar to how we do it for MPI).

**Comment by khayamgondal** [comment]
Thanks @tgaddair, If its a minor issue in the code, I can try to fix it.

**Comment by tgaddair** [comment]
Like I said, it's just another environment variable you need to set:

```
export HOROVOD_GLOO_IFACE=em2
```

Let me know if that works.

**Comment by khayamgondal** [comment]
@tgaddair Yes, I got it the first time. What I was saying that I can try to fix it like you said "auto-detect this similar to how we do it for MPI". But looks like you already have a PR opened.

**Comment by tgaddair** [comment]
Ah, sorry I misunderstood.  Hopefully the fix should prevent you from needing to set anything manually, feel free to try it out and let us know how it goes.

**Comment by shamanez** [comment]
@khayamgondal 

Have you tried executing [finetune.sh](https://github.com/amogkam/transformers/blob/rag-ray/examples/rag/finetune.sh)?
