### ISSUE TITLE
Running Horovod on Jetson Series

### ISSUE THREAD

**Issue by marcfielding1** [horovod/horovod#1348]
Heya,

So we'd like to see if we can run Horovod on Jetson TX2 I tried building the docker image and got...

```
 ---> Running in 2053ce8a11c5
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/bash -cu apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends         build-essential         cmake         g++-4.8         git         curl         vim         wget         ca-certificates         libcudnn7=${CUDNN_VERSION}         libnccl2=${NCCL_VERSION}         libnccl-dev=${NCCL_VERSION}         libjpeg-dev         libpng-dev         python${PYTHON_VERSION}         python${PYTHON_VERSION}-dev         librdmacm1         libibverbs1         ibverbs-providers' returned a non-zero code: 1
```

Now this makes sense because some of the libs are x86_x64 whereas Jetson is ARM, has anyone managed to achieve this? If not no worries we can try and figure it out - obviously didn't want to reinvent the wheel if anyone else has already done the work.

Cheers

Marc

**Comment by yichungchen84** [comment]
I did it on Jetson nano with NV Jetpack image and tensorflow 1.3.1. No need of NCCL (since you dont have NV driver) but you may want to install horovod by pip from github master.

**Comment by marcfielding1** [comment]
@yichungchen84 thanks for your response so you just literally installed via pip and it worked?

**Comment by yichungchen84** [comment]
Yes, now you can only use tensorflow and horovod.
follow this for tensorflow and then hovorod
[nvidia_jetson_tensorflow](https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html)

**Comment by marcfielding1** [comment]
Awesome that works, thanks!
