### ISSUE TITLE
How to call "horovodrun -np 4 -H localhost:4 python mnist.py" for distributed training in Pycharm?

### ISSUE THREAD

**Issue by ipScore** [horovod/horovod#1360]
**Environment:**
1. Framework: (PyTorch)
2. Framework version: 1.2
3. Horovod version: 0.18
4. MPI version: 4.0.0
5. CUDA version: 10.1
6. NCCL version: 2.1.4
7. Python version: 2.6.8
8. OS and version: Ubuntu 16.04
9. GCC version: 7.4.0

**Your question:**
Hello, I'd like to call **"horovodrun -np 4 -H localhost:4 python mnist.py"** for distributed training in **Pycharm**?  I wonder konw if I can set in Pycharm as the following :
![image](https://user-images.githubusercontent.com/30183023/63824565-34cc8800-c98a-11e9-96b6-ad915f8d37ef.png)

**Comment by ipScore** [comment]
@alsrgv Thank you for reply. Actually, directly running command **horovodrun -np 4 -H localhost:4 python mnist.py** in **terminal** to start training is OK, but it doesn't work in **Pycharm** . Thus,  I wonder if there is a module like **torch.distributed.launch** in horovod to lauch the distributed training in **Pycharm**.

**Comment by ipScore** [comment]
Hey @tgaddair., thank you for your advice. But it seems something wrong with my environment. Since I've installed OpenMPI 4.0.0 and re-installed horovord with pip, it still doesn't work.
![image](https://user-images.githubusercontent.com/30183023/63902577-cac0eb00-ca3c-11e9-9c53-647615322909.png)

![image](https://user-images.githubusercontent.com/30183023/63902475-63a33680-ca3c-11e9-837f-6c0717f84f5f.png)

```
/opt/conda/bin/python3 -u -m horovod.run.run -np 4 -H localhost:4 python mnist.py --allow-run-as-root
Was not able to run mpirun --version:
/bin/bash: mpirun: command not found

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/horovod/run/run.py", line 675, in <module>
    run()
  File "/opt/conda/lib/python3.6/site-packages/horovod/run/run.py", line 666, in run
    mpi_run(settings, common_intfs, env)
  File "/opt/conda/lib/python3.6/site-packages/horovod/run/mpi_run.py", line 58, in mpi_run
    'horovodrun convenience script does not find an installed OpenMPI.\n\n'
Exception: horovodrun convenience script does not find an installed OpenMPI.

Choose one of:
1. Install Open MPI 4.0.0+ and re-install Horovod (use --no-cache-dir pip option).
2. Run distributed training script using the standard way provided by your MPI distribution (usually mpirun, srun, or jsrun).
3. Use built-in gloo option (horovodrun --gloo ...).

Process finished with exit code 1 
```

**Comment by abditag2** [comment]
This error is most likely due to pycharm path. In the meanwhile, have you considered using python debugger instead of pycharm for debugging? Simply do 'pip install ipdp' and then in your code 'import ipdb;ipdb.set_trace()' where you want to set a breakpoint.

**Comment by jsrimr** [comment]
> Hey @ipScore, the module for `horovodrun` is `horovod.run.run`. So to run it in PyCharm you should be able to set **Module name** to `horovod.run.run` and **Parameters** to `-np 4 -H localhost:4 python mnist.py`.
> 
> This is equivalent to running `python -m horovod.run.run -np 4 - H localhost:4 python mnist.py` on the command line.
```
Error while finding module specification for 'horovod.run.run' (ModuleNotFoundError: No module named 'horovod.run')
```
I got this error when trying to use horovod.run.run module. Is this name still valid?

**Comment by tgaddair** [comment]
Hey @jsrimr, in the most recent versions of Horovod, you should be able to call `horovod.run` directly as a function.

**Comment by jsrimr** [comment]
> Hey @jsrimr, in the most recent versions of Horovod, you should be able to call `horovod.run` directly as a function.

![image](https://user-images.githubusercontent.com/16870927/107723355-42afcd80-6d24-11eb-81c3-b8652160cd2d.png)
when I run with the above setting, I get this error. :(

```
/opt/conda/envs/gpu/bin/python: No module named horovod.run
```

my horovod version is ```horovod==0.21.2``` and running in command line with ```horovodrun -np 4 python train_ofa_net.py``` works fine.

Do I have to call ```horovod.run``` somehow differntly? thx!

**Comment by tgaddair** [comment]
Hey @jsrimr, sorry didn't see that you were looking for the entrypoint for `horovodrun`.  This can be found [here](https://github.com/horovod/horovod/blob/master/setup.py#L188) in the setup.py file.  It's now `horovod.runner.launch`.
