### ISSUE TITLE
still mpicxx --show fails

### ISSUE THREAD

**Issue by thalassa3** [horovod/horovod#137]
Hi!  Thank you so much for open-sourcing this.

Question:  I have 

- openmpi installed in /home/username/openmpi
- added this to my path and 
- can successfully mpicxx --show and mpirun --version  

When I tried pip install --no-cache-dir horovod, I still get 'mpicxx -show failed (see error below), is MPI in $PATH?'

....
running build_ext
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -L/usr/lib64 -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o -L/usr/local/lib/python2.7/site-packages/tensorflow/core -L/usr/lib64 -ltensorflow_framework -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.so
    /usr/bin/ld: cannot find -ltensorflow_framework
    collect2: error: ld returned 1 exit status
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o -L/usr/local/lib/python2.7/site-packages/tensorflow/core -L/usr/lib64 -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.so
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -std=c++11 -fPIC -O2 -D_GLIBCXX_USE_CXX11_ABI=0 -I/usr/local/lib/python2.7/site-packages/tensorflow/include -I/usr/local/lib/python2.7/site-packages/tensorflow/include/external/nsync/public -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.o -L/usr/local/lib/python2.7/site-packages/tensorflow/core -L/usr/lib64 -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.so
    error: mpicxx -show failed (see error below), is MPI in $PATH?
    Note: If your version of MPI has a custom command to show compilation flags, please specify it with the HOROVOD_MPICXX_SHOW environment variable.
 
    Traceback (most recent call last):
      File "/tmp/pip-build-UkFuoh/horovod/setup.py", line 173, in get_mpi_flags
        shlex.split(show_command), universal_newlines=True).strip()
      File "/usr/lib64/python2.7/subprocess.py", line 567, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
 
 
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-UkFuoh/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-VCYuEx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-UkFuoh/horovod/

------------------------------------------------------------------
For the h*ll of it, I also tried

- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/username/openmpi/lib and
- echo /home/username/openmpi/lib |sudo tee -a/etc/ld.so.conf

Any other suggestions? 

Thank you!

**Comment by alsrgv** [comment]
@thalassa3, do you do `pip install` or `sudo pip install`?  The latter will override PATH.  Also, activating `virtualenv` overrides PATH.

**Comment by thalassa3** [comment]
@alsrgv thank you so much, yes I sudo.

**Comment by thalassa3** [comment]
@alsrgv I can figure it out from here, thanks!!

**Comment by mohammedayub44** [comment]
@alsrgv  Hey I have the same setup as yours and I'm getting the same error. Did you happen to resolve this ? 

@thalassa3  - how can I specify pip to use my current installation of OpenMPI which resides in "/home/myuser/.openmpi"

Any help appreciated. 

Thanks !
Mohammed Ayub

**Comment by alsrgv** [comment]
@mohammedayub44, you can add your MPI installation to PATH before running `pip install horovod`, like this:

```
$ export PATH=$PATH:/home/myuser/.openmpi/bin
$ [flags] pip install --no-cache-dir horovod
```

**Comment by mohammedayub44** [comment]
For now, I followed this blog post : 
`https://superuser.com/questions/927512/how-to-set-path-for-sudo-commands`
to edit the sudoers $PATH because pip overrides user's $PATH variable.
and then ran 
 `sudo pip install --verbose --no-cache-dir horovod`

and it worked fine. 
I'm not sure this is the most secure way to do it, as not everyone will have access to edit the sudoers $PATH file.

**Comment by alsrgv** [comment]
You can also do: `sudo PATH=$PATH pip install --verbose --no-cache-dir horovod`

**Comment by mohammedayub44** [comment]
Great. That works ! Thanks @alsrgv
