### ISSUE TITLE
a quick question about running the horovod

### ISSUE THREAD

**Issue by 652994331** [horovod/horovod#1371]
**Environment:**
1. Framework: (TensorFlow,)
2. Framework version: tensorflow-gpu==1.12.0
3. Horovod version: 0.18.0
4. MPI version: 4.0.0
5. CUDA version: 9.0
6. NCCL version: 2.4.8
7. Python version: 3.6.5
8. OS and version: centos 7
9. GCC version: >4.8.5

**Your question:**
Please ask your question here. Hi, can i ask a quick question? I was using horovod multi-gpu in my server, it ok. Recently i moved to a new server and already got every thing for the environment, but when i used same command as my old server, it said:
![image](https://user-images.githubusercontent.com/51428350/64043248-bb16d480-cb18-11e9-995a-527312a08929.png)

i guess ther's something wrong with "localhost". could you please help me out, thanks!

**Comment by khayamgondal** [comment]
Try chaning your hostname i.e. remove underscores.

**Comment by 652994331** [comment]
@khayamgondal thanks so much man, it works.

**Comment by khayamgondal** [comment]
Glad it helped. @tgaddair can you close this one?

**Comment by SimZhou** [comment]
Adding param `--mca orte_keep_fqdn_hostnames 1` while running mpirun may also help, check: https://github.com/open-mpi/ompi/issues/12089
