### ISSUE TITLE
Configure gloo timeout

### ISSUE THREAD

**Issue by ppwwyyxx** [horovod/horovod#1374]
**Is your feature request related to a problem? Please describe.**
I'm seeing this in a run with gloo:
```
third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:72] Timed out waiting 30000ms for recv operation to complete
```
at the first iteration.

**Describe the solution you'd like**
In tensorflow, the first iteration often involves heavy tasks such as jit-compile some cuda kernels and XLA-compile the graph. It is quite common that my model takes >5 minutes in the first iteration. I would like to be able to disable the timeout.

The timeout in gloo's context can be configured, and hopefully with the existing `--stall-check-shutdown-time-seconds` that's available in horovod.

**Comment by tgaddair** [comment]
Good suggestion!  Should be a simple change. Though I think it would make more sense to users to have a new flag for this, like `--gloo-timeout-ms`. Does that work for you?

**Comment by alsrgv** [comment]
Could probably be just `--gloo-timeout-seconds` since high resolution is unlikely necessary?

________________________________
