### ISSUE TITLE
RuntimeError: storage has wrong size

### ISSUE THREAD

**Issue by xuwwwux** [horovod/horovod#1382]
**Environment:**
1. Framework: PyTorch
2. Framework version:1.0
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Your question:**
Hi. I use the docker image (0.16.1-tf1.12.0-torch1.0.0-mxnet1.4.0-py2.7) from dockerhub (https://hub.docker.com/r/horovod/horovod/tags), and I successfully trained the model with several GPUs in multi machaines. But when I test the model, sometimes the models work well, sometimes it can't work and I meet the following error:
1. I trained the model with 4 GPUs in 4 machines (one GPUs each machine), successfully finished the training process, when testing, the error is:
/pytorch-classification-cl-v1.4/explore/ours/MODELS/model_resnet_ours.py:140: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.fc.weight)
/pytorch-classification-cl-v1.4/explore/ours/MODELS/model_resnet_ours.py:144: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.state_dict()[key], mode='fan_out')
=> creating model compact resnet18 
    Total params: 3.09M
==> Resuming from checkpoint..
Traceback (most recent call last):
  File "explore_dist.py", line 591, in <module>
    main()
  File "explore_dist.py", line 213, in main
    checkpoint = torch.load(args.resume)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 545, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected -5669828023084467774 got 256

2. I trained the model with 4 GPUs in 2 machines (2 GPUs each machine), successfully finished the training process, when testing, the error is:
/pytorch-classification-cl-v1.4/explore/ours/MODELS/model_resnet_ours.py:140: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.fc.weight)
/pytorch-classification-cl-v1.4/explore/ours/MODELS/model_resnet_ours.py:144: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.state_dict()[key], mode='fan_out')
=> creating model compact resnet18 
    Total params: 3.09M
==> Resuming from checkpoint..
Traceback (most recent call last):
  File "explore_dist.py", line 591, in <module>
    main()
  File "explore_dist.py", line 213, in main
    checkpoint = torch.load(args.resume)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 540, in _load
    deserialized_storage_keys = pickle_module.load(f)
EOFError

It seems that there is nothing in the mode file, but I check it for several times, the model is no empty.

The above are the 2 errors that I met. When I trained the model with 4 GPUs in 3 machines or with 2 GPUs in 2 machines, I successfully finished the training and testing process. The training and testing code are the same.

Could you please take a look at these two problems?

**Comment by wshj2020** [comment]
have you solved this problem,could you tell me how to do it
