### ISSUE TITLE
Daily build failed.

### ISSUE THREAD

**Issue by WeichenXu123** [horovod/horovod#1385]
See https://buildkite.com/horovod/horovod/builds/1135
Test on Tensorflow 2.0 were failed.

**Comment by alsrgv** [comment]
Logs suggest that the issue was with 20190905 nightly build, but it seems that they pulled it since now the latest is 20190903. I reran the test and it worked.

**Comment by alsrgv** [comment]
Looks like 20190906 also has an issue though, this time another set of objects is missing.  I've raised https://github.com/tensorflow/tensorflow/issues/32293
