### ISSUE TITLE
Only 2X speedup using 4GPUs on the same machine

### ISSUE THREAD

**Issue by wsstriving** [horovod/horovod#1386]
**Environment:**
1. Framework: Pytorch
2. Framework version: 1.2.0
3. Horovod version: 0.18
4. MPI version: openmpi 4.0.0
5. CUDA version: 10.0
6. NCCL version:  2.4.8
7. Python version: 3.6
8. OS and version: 
9. GCC version: 5.4.0

**Your question:**
I just installed Horovod and tried the benchmark:
https://github.com/horovod/horovod/blob/master/examples/pytorch_synthetic_benchmark.py

command is

horovodrun -np ngpu -H localhost:ngpu python pytorch_synthetic_benchmark.py --batch-size 64 --model resnet101
However, I can not get reasonable speedup, gpus are on the same node. the following are the results:

[1,0]<stdout>:Total img/sec on 1 GPU(s): 172.4 +-2.1

[1,0]<stdout>:Total img/sec on 2 GPU(s): 277.3 +-6.3

[1,0]<stdout>:Total img/sec on 3 GPU(s): 337.3 +-6.9

[1,0]<stdout>:Total img/sec on 4 GPU(s): 332.5 +-8.4

I can only achieve X2 speedup using 4 gpus, has anyone met the same problem before?

**Comment by CXMANDTXW** [comment]
> @CXMANDTXW can you try running `horovodrun --check-build` and print the results. Also, please let us know what versions of PyTorch / TensorFlow, MPI, NCCL you're using.
> 
> Next step would be to generate a [timeline](https://horovod.readthedocs.io/en/latest/timeline.html), which can give us a lot more insight into where the bottlenecks are.

horovodrun --check-build
Horovod v0.18.1:

Available Frameworks:
    [ ] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [ ] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] MLSL
    [X] MPI
    [ ] Gloo    

pytorch: 1.2.0 ,MPI: 4.0.1
no NCCL

**Comment by CXMANDTXW** [comment]
I have generated a timeline, I only see two situations：
![image](https://user-images.githubusercontent.com/22285070/64955383-aed19c00-d8ba-11e9-9317-00263fd96eca.png)
![image](https://user-images.githubusercontent.com/22285070/64955408-bee97b80-d8ba-11e9-8bc0-a4685b05f770.png)
Is there any bottlenecks exits?

**Comment by tgaddair** [comment]
Hey @CXMANDTXW, thanks for the info.  Could you upload the full JSON file?  It's hard to see what's going on at the granularity shown in the screenshot.

One possible culprit, as discussed in #1070, is CPU over-utilization, since you're using MPI on a single host.  Can you share how many CPU cores your machine has, and check its utilization in `top` when the benchmark is running?

**Comment by CXMANDTXW** [comment]
Sorry, it’s been a long time to return to you. My machine has 32 CPU cores as we can see in the screenshot.
this is a 'htop' screenshot 
![image](https://user-images.githubusercontent.com/22285070/65150626-1886ad00-da57-11e9-9945-561183ef784d.png)
this is a 'top' screenshot
![image](https://user-images.githubusercontent.com/22285070/65150800-6bf8fb00-da57-11e9-904e-d0984e5cd8d5.png)
this is my full JSON file.(I can't upload it directly)
[timeline.zip](https://github.com/horovod/horovod/files/3626536/timeline.zip)
