### ISSUE TITLE
Installing Horovod on Summit with Pytorch

### ISSUE THREAD

**Issue by abidmalikwaterloo** [horovod/horovod#1404]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
Pytorch
2. Framework version:
1.01
3. Horovod version:
the latest
4. MPI version:
IBM version on the summit machine
5. CUDA version:
9.2
6. NCCL version:
2.3
7. Python version:
3.6.6
8. OS and version:
Linux
9. GCC version:
7.4
**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

using
```
pip3 install --no-cache-dir git+https://github.com/horovod/horovod.git
```
but getting the following

```
Traceback (most recent call last):
      File "/tmp/pip-req-build-jt18is3w/setup.py", line 72, in check_tf_version
        import tensorflow as tf
    ModuleNotFoundError: No module named 'tensorflow'
    
    
    INFO: Unable to build PyTorch plugin, will skip it.
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-jt18is3w/setup.py", line 1060, in check_torch_version
        import torch
    ModuleNotFoundError: No module named 'torch'
```
However

```
import torch
import mpi4py

```
work

**Comment by abidmalikwaterloo** [comment]
I created and new environment using conda with python 3.6.6 and building Horovod in the new environment. Just in case the information helps

**Comment by nvcastet** [comment]
@bethune-bryant
