### ISSUE TITLE
Horovod + MPICH on custom ports - NCCL INFO Call to connect returned Connection refused, retrying

### ISSUE THREAD

**Issue by abhi8830** [horovod/horovod#1408]
Hi,
Our node setup blocks communication except on open ports. 
I am using MPICH as the MPI lib and a simple MPI communication example works fine between the nodes. I set the open port range in the MPICH_PORT_RANGE env variable.

However, when I run my tensorflow program with NCCL and Horovod it stalls after a bunch of errors from NCCL complaining about Connection refused.
**hostname:26407:26474 NCCL INFO Call to connect returned Connection refused, retrying...**

I am trying to understand if I can force NCCL to communicate over the open ports and any other debugging strategies...

This is how I start my program.
```/usr/lib64/mpich-3.2/bin/mpirun -n 2 -ppn 1 -hosts mr3-509-0708-15-srv:1,mr3-509-0506-03-srv:1 -genvnone -env NCCL_DEBUG INFO -envlist PYTHONPATH,MPICH_PORT_RANGE,NCCL_SOCKET_IFNAME,MPIEXEC_PORT_RANGE,I_MPI_PORT_RANGE python3.6 /root/mnist.py```

here's the output of my ifconfig
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 175.18.0.2  netmask 255.255.0.0  broadcast xxx.xx.xxx.xxx
        ether --:--:--:--:--:--  txqueuelen 0  (Ethernet)
        RX packets 1936547  bytes 3331649153 (3.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1833665  bytes 269902475 (257.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 993050  bytes 49667223 (47.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 993050  bytes 49667223 (47.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by rahmatkhah** [comment]
I am also running into a similar issue. However, I'm setting different parameters to limit the ports:
`mpiexec --allow-run-as-root \
        -hostfile "$hostfile" \
        -bind-to none \
        -map-by slot \
        --mca pml ob1 \
        --mca plm_rsh_args "-p $ssh_port" \
        --mca orte_base_help_aggregate 0 \
        --mca btl ^openib \
        --mca btl_tcp_if_exclude docker0,lo \
        --mca btl_tcp_port_min_v4 "$btl_tcp_port_min_v4" \
        --mca btl_tcp_port_range_v4 "$btl_tcp_port_range_v4" \
        --mca oob_tcp_dynamic_ipv4_ports "$oob_tcp_dynamic_ipv4_ports" \
        --mca oob_tcp_if_exclude docker0,lo \
        -x NCCL_SOCKET_IFNAME=^docker0,lo \
        -x NCCL_IB_DISABLE=1 \
        -x NCCL_DEBUG=TRACE \
        -x NCCL_DEBUG_SUBSYS=ALL \
        -x LD_LIBRARY_PATH \
`
And, here is where my program stalls:
`include/socket.h:369 NCCL WARN Call to connect failed : Connection timed out
NCCL INFO transport/net_socket.cu:138 -> 2
NCCL INFO bootstrap.cu:19 -> 2
NCCL INFO bootstrap.cu:205 -> 2
NCCL INFO init.cu:446 -> 2
NCCL INFO init.cu:593 -> 2`
