### ISSUE TITLE
Dynamic / fluctuating number of hosts during training?

### ISSUE THREAD

**Issue by marcfielding1** [horovod/horovod#1413]
I hope you mind me dodging the to question template as it doesn't really apply it's more of a general question. FYI I'm on the latest tensorflow and keras with MPI and Horovod at their default versions from pip.

I'm launching our training on a pre configured image containing horovod/mpi on AWS spot instances with worker 0 being an on demand instance so it can't get terminated.

Let's say I have a fleet of 5 other workers which are spot instances and 2 get terminated because the spot price went up - then when the spot price drops two new nodes come back up.

Is there a way to discover new worker nodes? I suppose this could apply if you wanted to add extra resource to a training job whilst it was ongoing.

**Comment by karakusc** [comment]
@marcfielding1 Although MPI provides some functionality to include new hosts mid-way, this is a bit complicated and it is not a feature currently built into Horovod. If you are training with spot instances on AWS, you might want to check out [Spot training on SageMaker](https://www.linkedin.com/in/marc-fielding-a8bb3293/).

**Comment by karakusc** [comment]
@marcfielding1 Although MPI provides some functionality to include new hosts mid-way, this is a bit complicated and it is not a feature currently built into Horovod. If you are using spot instances for training in AWS, you might want to checkout [Spot training on SageMaker](https://docs.aws.amazon.com/sagemaker/latest/dg/model-managed-spot-training.html).

**Comment by marcfielding1** [comment]
@karakusc Thanks a lot, I was just wondering tis all, I can imagine it's very complicated!

**Comment by hollowgalaxy** [comment]
@karakusc what happens to horovod's optimizer if an instance goes down in a multi-node setup?

**Comment by karakusc** [comment]
@hollowgalaxy If you are using Horovod with MPI, then MPI will detect that some of the processes died and the program will crash. Not sure how Gloo handles such scenarios.

**Comment by tgaddair** [comment]
Hey @marcfielding1, this is something we're working on right now with Gloo.  Should have something for you early 2020.

**Comment by vdabravolski** [comment]
@tgaddair curious, if there are any updates on support of fluctuating number of nodes in MPI ring. A specific use case in mind - using spot cloud instances (which can be dynamically taken away).

**Comment by tgaddair** [comment]
Hey @vdabravolski, @hollowgalaxy, @marcfielding1,

We have an experimental elastic mode that has been landed to master, and will be released in v0.20.0.  You can read up on how to make use of this feature [here](https://github.com/horovod/horovod/blob/master/docs/elastic.rst).

We're still working on evaluating and improving the performance, and adding support for various data loaders (as well as cloud providers), but you can get started with it now if you'd like, and let us know if you run into any issues!

**Comment by EnricoMi** [comment]
And to emphasis this again: the elastic mode is only available with Gloo, not MPI.

**Comment by marcfielding1** [comment]
> Hey @vdabravolski, @hollowgalaxy, @marcfielding1,
> 
> We have an experimental elastic mode that has been landed to master, and will be released in v0.20.0. You can read up on how to make use of this feature [here](https://github.com/horovod/horovod/blob/master/docs/elastic.rst).
> 
> We're still working on evaluating and improving the performance, and adding support for various data loaders (as well as cloud providers), but you can get started with it now if you'd like, and let us know if you run into any issues!

Heya, really sorry for the slow reply @tgaddair not that I'm asking for any special treatment but I'm taking a startup through funding(Having already pulled in funding from some household names) training one of the largest CV models on the planet by class (time of writing we're gathering data for 250,000 objects in a retail setting) - currently we're investing in our own Nvidia GPU's and some AWS infrastructure - would it be possible (paid or otherwise) to grab an hour of your time to figure out how and IF given our current capabilities we could leverage Horovod?

We have tiered model structure which can and will receive perhaps thousands of micro-updates a day hence my original interest in horovod.

Please see my LinkedIn here: https://www.linkedin.com/in/marc-fielding-a8bb3293/

**Comment by tgaddair** [comment]
Hey @marcfielding1, happy to chat about this.  Let's set something up.
