### ISSUE TITLE
horovod can't run in two servers

### ISSUE THREAD

**Issue by linjiaqin** [horovod/horovod#1414]
**Environment:**
1. Framework: (Keras)
2. Framework version:
3. Horovod version: 0.18
4. MPI version: 4.0.0
5. CUDA version:
6. NCCL version:
7. Python version: 3.6
8. OS and version: ubuntu14.04
9. GCC version: 4.9

**Bug report:**

(horovod) hadoop3@cu11:~$ horovodrun -np 16 -H cu11:8,cu08:8 python keras_mnist.py
Traceback (most recent call last):
  File "/software/hadoop3/anaconda3/envs/horovod/bin/horovodrun", line 21, in <module>
    run.run()
  File "/software/hadoop3/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/run/run.py", line 677, in run
    settings, fn_cache=fn_cache)
  File "/software/hadoop3/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/run/util/cache.py", line 103, in wrap_f
    results = func(*args, **kwargs)
  File "/software/hadoop3/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/run/run.py", line 229, in _driver_fn
    driver.wait_for_initial_registration(settings.timeout)
  File "/software/hadoop3/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/run/common/service/driver_service.py", line 117, in wait_for_initial_registration
    timeout.check_time_out_for('tasks to start')
  File "/software/hadoop3/anaconda3/envs/horovod/lib/python3.6/site-packages/horovod/run/common/util/timeout.py", line 32, in check_time_out_for
    raise Exception(self._message.format(activity=activity))
Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers.

**Comment by marcfielding1** [comment]
Hey, i'm not part of the Horovod team but have just been through debugging this, First thing to check is that you can SSH manually to cu08?

```
ssh cu08
```

**Comment by tgaddair** [comment]
Yes, as @marcfielding1 suggested, it looks like ssh connectivity or interface compatibility might be the issue here.  Please try what he suggested.

**Comment by linjiaqin** [comment]
@marcfielding1 @tgaddair 
I have followed what you suggest and the debug result are in the below. It seems the ssh is fine.

hadoop3@cu11:~$ horovodrun --verbose -np 16 -H cu11:8,cu08:8 python keras_mnist.py
Filtering local host names.
Remote host found: cu08
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Traceback (most recent call last):
  File "/software/hadoop3/anaconda3/envs/zoo/bin/horovodrun", line 21, in <module>
    run.run()
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/horovod/run/run.py", line 677, in run
    settings, fn_cache=fn_cache)
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/horovod/run/util/cache.py", line 103, in wrap_f
    results = func(*args, **kwargs)
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/horovod/run/run.py", line 229, in _driver_fn
    driver.wait_for_initial_registration(settings.timeout)
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/horovod/run/common/service/driver_service.py", line 117, in wait_for_initial_registration
    timeout.check_time_out_for('tasks to start')
  File "/software/hadoop3/anaconda3/envs/zoo/lib/python3.6/site-packages/horovod/run/common/util/timeout.py", line 32, in check_time_out_for
    raise Exception(self._message.format(activity=activity))
Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers.

hadoop3@cu11:~$ ifconfig -a
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2597636 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2597636 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:592102472 (592.1 MB)  TX bytes:592102472 (592.1 MB)

p2p1      Link encap:Ethernet  HWaddr 00:25:90:6b:95:48  
          inet addr:192.168.0.11  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::225:90ff:fe6b:9548/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4185438397 errors:0 dropped:0 overruns:3757 frame:0
          TX packets:6620259159 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5504867255398 (5.5 TB)  TX bytes:6808735045161 (6.8 TB)
          Memory:dfb20000-dfb3ffff 

p2p2      Link encap:Ethernet  HWaddr 00:25:90:6b:95:49  
          inet6 addr: fe80::225:90ff:fe6b:9549/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11887551 errors:0 dropped:149 overruns:0 frame:0
          TX packets:492378 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2348213335 (2.3 GB)  TX bytes:95188626 (95.1 MB)
          Memory:dfb00000-dfb1ffff 

virbr0    Link encap:Ethernet  HWaddr d2:19:da:b6:28:af  
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

hadoop3@cu11:~$ ssh cu08
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-157-generic x86_64)
  System information as of Wed Sep 25 10:22:45 CST 2019

  System load:  1.46                Processes:              410
  Usage of /:   91.7% of 211.44GB   Users logged in:        3
  Memory usage: 13%                 IP address for p2p1:    192.168.0.8
  Swap usage:   9%                  IP address for docker0: 172.17.0.1

  => / is using 91.7% of 211.44GB

    
Last login: Wed Sep 25 10:21:53 2019 from cu08
hadoop3@cu08:~$ ifconfig -a
docker0   Link encap:Ethernet  HWaddr 02:42:60:f0:6f:4f  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:957243 errors:0 dropped:0 overruns:0 frame:0
          TX packets:957243 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:20964659668 (20.9 GB)  TX bytes:20964659668 (20.9 GB)

p2p1      Link encap:Ethernet  HWaddr 00:25:90:6b:93:38  
          inet addr:192.168.0.8  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::225:90ff:fe6b:9338/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4440500725 errors:0 dropped:0 overruns:719 frame:0
          TX packets:6925162418 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5943731147858 (5.9 TB)  TX bytes:7116009064957 (7.1 TB)
          Memory:dfb20000-dfb3ffff 

p2p2      Link encap:Ethernet  HWaddr 00:25:90:6b:93:39  
          inet6 addr: fe80::225:90ff:fe6b:9339/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11970199 errors:0 dropped:138 overruns:0 frame:0
          TX packets:449131 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2375167297 (2.3 GB)  TX bytes:77876352 (77.8 MB)
          Memory:dfb00000-dfb1ffff

**Comment by marcfielding1** [comment]
So could you make sure ALL tcp traffic is permitted between those two servers temporarily rather than just 22 for ssh? mpirun uses a few ports(I don't know what they are at this stage).

If that is the case already could you try using ```--start-timeout 600```
