### ISSUE TITLE
horovod on aws emr with auto-scaling 

### ISSUE THREAD

**Issue by oskotsky** [horovod/horovod#1423]
We are testing Horovod on aws emr cluster. So far so good. However we use auto scaling on our cluster (auto scaling adds and deletes workers when needed to avoid under/over provisioning). Will this a problem for Horovod? Will spark-horovod handle this dynamic correctly?

Thank you

**Comment by marcfielding1** [comment]
So I asked a similar question here if it helps: #1413

**Comment by oskotsky** [comment]
Thank you! Looks like auto-scaling is not on the menu at least for now.

**Comment by tgaddair** [comment]
Hey @oskotsky, just FYI, we're actively working on auto-scaling support and should have something ready early 2020.

**Comment by umialpha** [comment]
@tgaddair  thx for your information! Our cluster needs this feature sooo much! I can't wait.

**Comment by oskotsky** [comment]
This is great! Thank you!

Boris
