### ISSUE TITLE
AllReduceMin/Max needed

### ISSUE THREAD

**Issue by passerbyd** [horovod/horovod#1425]
**Is your feature request related to a problem? Please describe.**
The min/max values in a tensor will be used from time to time.

**Describe the solution you'd like**
Get the min/max value via ringallreduce. nccl on gpus.

**Describe alternatives you've considered**
For now, the procedure will be reducing locally, allgather, then reduce again.
directly allreduce will consume much less memory and run faster.

**Comment by tgaddair** [comment]
Hey @passerbyd, thanks for the suggestion, and apologies for the late response.  This is a good suggestion.  Would you be interested in contributing this yourself?  If not, no worries, we can add it to the backlog.

**Comment by wangxianliang** [comment]
We also need **allreduce argmin/argmax** operation.

**Comment by densechen** [comment]
The allrecude operation in PyTorch-version is the naive one, which will directly gather tensor from each other node, or the RingAllReduce one?

In the official PyTorch training policy, it is the RingAllReduce implemented. How it does in horovod?

**Comment by tgaddair** [comment]
@densechen, Horovod uses NCCL to compute the allreduce on GPU and one of MPI/Gloo/oneCCL for CPU allreduce. Under the hood, these frameworks will choose to use ring, tree, or some other form of allreduce. We also support a different kind of allreduce entirely called Adasum that is intended to help with model training convergence.

**Comment by maxhgerlach** [comment]
implemented via #3660
