### ISSUE TITLE
python3: can't open file 'mnist.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by GoWeiXH** [horovod/horovod#1434]
**Environment:**
1. Framework: Keras
2. Framework version: 2.2.4
3. Horovod version: 0.18.1
4. MPI version: (Open MPI) 4.0.0
5. CUDA version: 9.0
6. NCCL version: 2.0
7. Python version: 3.6.2
8. OS and version: CentOS Linux release 7.3.1611 (Core) 
9. GCC version: 4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before? ——yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?——no about hang
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?—— no about docker
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?——yes

**Your question:**
Environment installation completed, run——————↓↓↓

'''horovodrun --verbose -np 2 -H 192.168.8.42:1,192.168.8.41:1 -p 10000 --start-timeout 600 python3 mnist.py'''

Results are as follows——————↓↓↓

‘’‘Filtering local host names.
Remote host found: 192.168.8.42
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Notified all the hosts that the registration is complete.
Waiting for hosts to perform host-to-host interface checking.
Host-to-host interface checking successful.
Interfaces on all the hosts were successfully checked.
Common interface found: eno1
Checking whether extension tensorflow was built with MPI.
/home/dev/yiwendao/env/Python-3.6.2/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Extension tensorflow was built with MPI.
mpirun --allow-run-as-root --tag-output -np 2 -H 192.168.8.42:1,192.168.8.41:1 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib -mca plm_rsh_args "-p 10000" -mca btl_tcp_if_include eno1 -x NCCL_SOCKET_IFNAME=eno1 -x XDG_SESSION_ID -x HOSTNAME -x TERM -x SHELL -x HISTSIZE -x SSH_CLIENT -x MONGODB_HOME -x QTDIR -x QTINC -x MED_KN -x SSH_TTY -x QT_GRAPHICSSYSTEM_CHECKED -x CUDA_HOME -x USER -x LD_LIBRARY_PATH -x LS_COLORS -x MAVEN_HOME -x MAIL -x PATH -x PWD -x JAVA_HOME -x LANG -x HISTCONTROL -x SHLVL -x HOME -x LOGNAME -x PYTHON3PATH -x QTLIB -x CLASSPATH -x SSH_CONNECTION -x LESSOPEN -x XDG_RUNTIME_DIR -x _ -x HOROVOD_STALL_CHECK_TIME_SECONDS -x HOROVOD_STALL_SHUTDOWN_TIME_SECONDS -x HOROVOD_NUM_NCCL_STREAMS -x HOROVOD_MLSL_BGT_AFFINITY python3 mnist.py
[1,1]<stderr>:python3: can't open file 'mnist.py': [Errno 2] No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58250,1],1]
  Exit code:    2
--------------------------------------------------------------------------
’‘’

But command ‘’‘horovodrun -np 2 -H 192.168.8.42:1 -p 10000 python3 mnist.py’‘’ can be executed normally.（192.168.8.42 is local server）

（This file '''mnist.py''' is available on both servers and has the same storage path.）

I need help !!!
Thanks very much !!!

**Comment by tgaddair** [comment]
Hey @GoWeiXH, can you try specifying the path to `mnist.py` as an absolute path and double check that it is the same path with the same permissions on both machines?  MPI may be having trouble changing directories into that path on the other host.

**Comment by GoWeiXH** [comment]
Thanks for your attention! @tgaddair 

I‘m tried to use absolute path: '''horovodrun --verbose -np 2 -H 192.168.8.42:1,192.168.8.41:1 -p 10000 --start-timeout 600 python3  /home/jq/Distributed_learning/mnist.py''', but not work.

1. The path of 'mnist.py' is same: '/home/jq/Distributed_learning/mnist.py';
2. The Python env path is same;
3. The openMPI path is same: '/usr/local/openmpi'
4. The permissions was same, and now I chmod 777 on both machines;

Not ... work ... T_T

**Comment by GoWeiXH** [comment]
This problem has been solved.
1. I unified the users and paths of the python environment of the two servers.
2. I created a new folder on both servers and moved the script into it.

Close！
