### ISSUE TITLE
Horovod not support tensorflow_gpu==1.15.0-rc3 ? 

### ISSUE THREAD

**Issue by cklsoft** [horovod/horovod#1435]
**Environment:**
3. Horovod version: 0.18.1
4. MPI version: 4.0.0
5. CUDA version: 10.0
6. NCCL version: 2.4.7
7. Python version: 2.7
8. OS and version: ubuntu
9. GCC version: 4.9.3

**Your question:**
 Traceback (most recent call last):
    File "/tmp/pip-install-EQHt8d/horovod/setup.py", line 1375, in build_extensions
      build_tf_extension(self, options)
    File "/tmp/pip-install-EQHt8d/horovod/setup.py", line 907, in build_tf_extension
      'Could not find compiler compatible with this TensorFlow installation.\n'
  DistutilsPlatformError: Could not find compiler compatible with this TensorFlow installation.
  Please check the Horovod website for recommended compiler versions.
  To force a specific compiler version, set CC and CXX environment variables.

But run `python -c 'import tensorflow as tf;print(tf.__version__)'`: 
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
1.15.0-rc3

Which latest tf version horovod support?

**Comment by tgaddair** [comment]
Hey @cklsoft, what version of gcc are you using?  Can you share that along with the string returned from `tf.version.COMPILER_VERSION`?  There are some ABI incompatibilities between certain versions of GCC (namely 4.X to 5.X) that can cause this issue (see: https://github.com/tensorflow/tensorflow/issues/27067).

**Comment by jyhengcoder** [comment]
I meet the same problem in tensorflow1.15.0. I got error when installing horovod by`pip install horovod`. @tgaddair
