### ISSUE TITLE
What is the "ideal" in benchmark figure?

### ISSUE THREAD

**Issue by zarzen** [horovod/horovod#1436]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Hi,
I am curious about the definition of "ideal" used in the benchmark graph.
![benchmark](https://user-images.githubusercontent.com/16640218/38965607-bf5c46ca-4332-11e8-895a-b9c137e86013.png)
Could someone explain how to compute the "ideal" here? Does it mean "single-performance * num-nodes"?

**Comment by tgaddair** [comment]
Hey @zarzen, "ideal" here is 1:1 (100%) scaling efficiency, meaning exactly what you suggested: the comparison of the performance with N GPUs as compared to 1 GPU.  You can calculate the scaling efficiency at N GPUs as `scaling_efficiency(N) = (inputs_per_s(N) / N) / inputs_per_s(1)`.
