### ISSUE TITLE
Support of non-mpi communications

### ISSUE THREAD

**Issue by nateagr** [horovod/horovod#1440]
Hello there,

I'm currently working on a tensorflow distribution strategy similar to Horovod (based on allreduce/allgather ops for gradient aggregations). But contrary to Horovod, I don't rely on MPI. Instead, I'm using dmlc/rabit (https://github.com/dmlc/rabit) for non-mpi communications between nodes. I wonder if I could introduce dmlc/rabit in Horovod as an alternative to mpi. How do you guys feel about that ?

**Comment by tgaddair** [comment]
Hey @nateagr, that sounds great!  To clarify, Horovod no longer relies on MPI, we also support [Gloo](https://github.com/facebookincubator/gloo/tree/master/gloo) as an alternative to MPI for our control plane.  You can take a look at #1181 to get an idea for how to do this for dmlc/rabit.  The one thing I'm unsure of with rabit is how to handle Allgather, which is used for dealing with sparse tensors in Horovod.  Do you know if rabit supports or plans to support allgather?

**Comment by nateagr** [comment]
Thanks for you quick answer @tgaddair 
Allgather op is almost part of dmlc/rabit. It will be after this last pr https://github.com/dmlc/rabit/pull/113. I'll have a look to your pointers.

**Comment by tgaddair** [comment]
Excellent, then once that's landed it should work fine.  Feel free to reach out if you have any questions.

**Comment by liyi193328** [comment]
Great ideas. @nateagr That distribution strategy will be public?
