### ISSUE TITLE
Time consuming for distributed training is confusing

### ISSUE THREAD

**Issue by df19900725** [horovod/horovod#1446]
My model is seq2seq written by TensorFlow 1.13.
I use two machines which each one of them have 8 vCPUs.
I use tqdm to record time consuming for training. I have 40110 training samples in total and batch size is 256. Max epoch is set to be 100.
When I use only one machine with python command, it shows time consuming as follows:

`94/157 [00:07<00:05, 11.83it/s]`

it seems that the program processed 11.83 iterations per second.

However, when I use horovod to execute the program, it will consume more time than use python command. My horovod command is:

`horovodrun -np 16 -H  100.106.79.229:8,100.106.78.45:8 --start-timeout 480 python xx.py`

time consuming is:

`3/157 [00:01<01:02,  2.45it/s]`

It means if I use two machines with 16 vCPUs, it will slow down the training. When I decrease the number vCPUs, the process time will decrease too. The list below shows the relationships between vCPUs and training time:

8 vCPUs in total, 4 for each machine:
`110/157 [00:19<00:08,  5.69it/s]`

4 vCPUs in total, 2 for each machine:
`56/157 [00:07<00:12,  7.85it/s]`

2 vCPUs in total, 1 for each machine:
`95/157 [00:26<00:06,  8.89it/s]`

It was so strange! Can anyone could explain this for me? Thanks

**Comment by tgaddair** [comment]
Hey @df19900725, can you try running one of our synthetic benchmark scripts in the [examples](https://github.com/horovod/horovod/tree/master/examples) directory and see if you get the same results.  If so, we can try creating a [timeline](https://github.com/horovod/horovod/blob/master/docs/timeline.rst) to dig into where things are slowing down.
