### ISSUE TITLE
Does horovod make program read all dataset for each rank?

### ISSUE THREAD

**Issue by df19900725** [horovod/horovod#1448]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.13
3. Horovod version: 0.18
4. MPI version: 4.0.1
5. CUDA version:
6. NCCL version:
7. Python version: 3.6
8. OS and version: SUSE 12
9. GCC version: 4.9.3

**Your question:**

I use tf.data.dataset api to load data from local file system

`raw_data = np.loadtxt(file)`
`tf.data.Dataset.from_tensor_slices(raw_data).shard(num_shards, index).batch(batch_size).repeat(n_epoch)`

since raw data is very large, if I run the program on 8 vCPUs, it seems that the program will execute  `raw_data = np.loadtxt(file)` for 8 times. If one machine has 64 GB, load dataset for one time will consume 40GB, it will throw exception if I run the program on 8 vCPUs.

How could I solve this problem?

**Comment by tgaddair** [comment]
Hey @df19900725, my suggestion would be to stream the data as opposed to reading it all into memory at once.  For example, you could try using [tf.data.TextLineDataset](https://www.tensorflow.org/api_docs/python/tf/data/TextLineDataset) or you could preprocess your data into a [tf.data.TFRecordDataset](https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset).
