### ISSUE TITLE
Does horovod support stable tensorflow2.0 now?

### ISSUE THREAD

**Issue by venuswu** [horovod/horovod#1449]
Which version of horovod support stable tensorflow2.0?

@alsrgv

**Comment by tgaddair** [comment]
Hey @venuswu, stable TensorFlow 2.0 support is available in the latest version of Horovod: `0.18.1`.  Feel free to reach out if you have any issues!

**Comment by zh794390558** [comment]
follow this.

**Comment by zh794390558** [comment]
@tgaddair where can i find the performance comparison with tensorflow?

**Comment by tgaddair** [comment]
Hey @zh794390558, what kind of performance comparison are you looking for?  We had a comparison of Horovod with Distributed TensorFlow (parameter servers) in the original [Horovod blog post](https://eng.uber.com/horovod/) from 2017.  For more up to date numbers, I'd suggest following our [benchmarks](https://github.com/horovod/horovod/blob/master/docs/benchmarks.rst) guide and comparing different setups in your environment.

**Comment by kingwales1** [comment]
Hi, @tgaddair I want to do the performance comparison with [tensorflow 2](https://github.com/tensorflow/models/tree/master/official) official models. But the provided guideline is evaluated with tensorflow 1. Do the tensorflow 2 official models support Horovod now?  Could you please show me a simple command example to run the [BERT ](https://github.com/tensorflow/models/tree/master/official/nlp/bert)training with Horovod? Many thanks!
