### ISSUE TITLE
horovodrun  

### ISSUE THREAD

**Issue by lijain** [horovod/horovod#1452]
The security free communication between servers has been OK. It is OK to run horovodrun - NP 1 - H 192.168.48.145:1 Python xx.py on a separate server of 192.168.48.145. But on 192.168.48.145, the program horovodrun - NP 1 - H 192.168.31.147:1 Python XX. Py does not respond???

**Comment by tgaddair** [comment]
Hey @lijain, can you try running with `horovodrun --verbose` and provide the printed output here?  Thanks.

**Comment by lijain** [comment]
出现这个，麻烦你帮忙看下



------------------ 原始邮件 ------------------
发件人: "Travis Addair"<notifications@github.com>;
发送时间: 2019年10月18日(星期五) 上午6:56
收件人: "horovod/horovod"<horovod@noreply.github.com>;
抄送: "利剑"<1632401541@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [horovod/horovod] horovodrun   (#1452)




Hey @lijain, can you try running with horovodrun --verbose and provide the printed output here?  Thanks.
