### ISSUE TITLE
Question on PyTorch 1.3.0 compatibility

### ISSUE THREAD

**Issue by hanyucui** [horovod/horovod#1457]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.3.0
3. Horovod version: 0.18.1
4. MPI version: 3.0.0 (OpenMPI)
5. CUDA version: 10.0
6. NCCL version: 2.4.7
7. Python version: 3.7
8. OS and version: Ubuntu 16.04 LTS

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

We want to upgrade to the latest PyTorch (1.3.0) but are not sure if the latest Horovod release (0.18.1) supports it. Have you tested this combination?

**Comment by tgaddair** [comment]
Hey @hanyucui, there shouldn't be any issues running Horovod with PyTorch 1.3.0.  Our integration tests run against both a stable PyTorch version (currently 1.1.0) and nightly (currently 1.4.0.dev20191022), and we haven't seen any breaking changes from PyTorch in some time.  But of course, please let us know if something comes up!

**Comment by hanyucui** [comment]
Great. Thanks a lot, @tgaddair .
