### ISSUE TITLE
How to run Horovod + Keras on CUDA9?

### ISSUE THREAD

**Issue by y-vectorfield** [horovod/horovod#1471]
Our team's GPU server is installed on CUDA9. However, the latest versions of Horovod on Docker needs CUDA10. We would like to know how to run Horovod Docker latest + Keras on CUDA9. Our team should install CUDA latest version 10 ??

**Comment by tgaddair** [comment]
Hey @y-vectorfield, one option is to upgrade to CUDA 10, as you said (that would be my recommendation).  

If that's not an option for you, you can also build your own Docker image using our provided [Dockerfile](https://github.com/horovod/horovod/blob/master/Dockerfile.gpu) using CUDA 9, or use one of our older images with older versions of Horovod.  Images on DockerHub built with Horovod v0.16.4 (a stable release) use CUDA 9.

In the future, we can make a point of tagging CUDA versions for the Docker images to avoid confusion.

**Comment by y-vectorfield** [comment]
Hello, @tgaddair 
Thank you very much for your comments.
We tried to use Horovod V0.16.4, we found that this version of Dockerfile need to add Keras version ENV. If we build this Dockerfile without changes, we can not run Horovod on Docker.(import keras is terminated with import Error) Therefore, We would like to add ENV KERAS_VERSION=2.2.4 to this and submit a pull request.

**Comment by tgaddair** [comment]
Hey @y-vectorfield, are you able to build the Docker image with your modifications?  The Dockerfiles provided are just intended to be used as an example, so shouldn't be any need to pin to a specific Keras version on master.

**Comment by y-vectorfield** [comment]
Hello, @tgaddair,
Thank you very much for your message. I understand what you said. The Dockerfile on master should not pin to a Keras version.
