### ISSUE TITLE
How to convert "ts" field in timeline trace file to standard datetime?

### ISSUE THREAD

**Issue by zarzen** [horovod/horovod#1472]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.14
3. Horovod version: 0.18.2
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Your question:**
Hi there,
I am checking the timeline-file, following is part of the log
```
{"ph": "B", "name": "NEGOTIATE_ALLREDUCE", "ts": 354516603107, "pid": 5},
{"ph": "X", "name": "0", "ts": 354516603109, "pid": 5, "dur": 0},
{"name": "process_name", "ph": "M", "pid": 6, "args": {"name": "training/Adadelta_Allreduce/HorovodAllreduce_Adadelta_1_gradients_conv2d_BiasAdd_grad_BiasAddGrad_0"}},
{"name": "process_sort_index", "ph": "M", "pid": 6, "args": {"sort_index": 6}},
{"ph": "B", "name": "NEGOTIATE_ALLREDUCE", "ts": 354516608183, "pid": 6},
```
I am confused about the "ts" field, I think this is the "time-started", but how to interpret the number?
How to convert it to regular datetime? 
I checked the [timeline.cc](https://github.com/horovod/horovod/blob/master/horovod/common/timeline.cc) file, which shows the "ts" get a microsecond number. But divide `354516608183` by `1000` and then convert it to datetime, seems strange. Here is the output
```
from datetime import datetime
    ...: timestamp = 354663785644/1000.0
    ...: dt_object = datetime.fromtimestamp(timestamp)
    ...: print("dt_object =", dt_object)
    ...: print("type(dt_object) =", type(dt_object))
    ...:
    ...:
dt_object = 1981-03-28 16:43:05.644000
type(dt_object) = <class 'datetime.datetime'>
```
I think it is due to the fact that logging time always minused with `start_time`, so is there easy way to get the start time? ([timeline-L169](https://github.com/horovod/horovod/blob/master/horovod/common/timeline.cc#L169))

The reason I want to get the absolute time is to fuse multiple timeline traces.

**Comment by tgaddair** [comment]
Hey @zarzen, the time being printed being off is due to a bug with the initialization of the start time.  What it is intended to show you is the timestamp of the event since the timeline was initialized (roughly, the start of the program).  I can put together a quick fix for that so the timestamps make more sense.

It sounds like what you're interested in, however, is the system clock timestamp of the event.  Can you explain more about where these multiple timelines you want to fuse are coming from?  Are you running multiple jobs at once on the same machine?

**Comment by zarzen** [comment]
Hi @tgaddair , thanks for the quick response.
I am trying to fuse both timelines from horovod and tensorflow/pytorch, first. So we can get ideas of event relationship between the distributed operator, HOROVOD_ALLREDUCE and normal forward/backward operations. 
multiple timelines are also possible coming from multiple machines, so we can have a general view of what's happening between servers.

**Comment by tgaddair** [comment]
Thanks for clarifying @zarzen.  Given your use case, it sounds like having the timestamp be relative to the application start time would be the most useful solution.  I put together #1476 to address the issue of the timestamp not making sense, please take a look and let me know what you think.

**Comment by zarzen** [comment]
@tgaddair Thanks for the suggested fix. While the relative to the application start might not align well for fusing from multiple timelines in my opinion. e.g. TensorFlow profiler started at `T1`, horovod-profiler start from `T2`, if we use the relative time to plot them on the same timeline, we might inaccurate relative time between horovod-profiler and tensorflow-profiler, if `deltaT = abs(T1-T2)` is large.

**Comment by tgaddair** [comment]
@zarzen, if we provided an option to use absolute system clock time instead of relative steady clock time, would that work for you?

**Comment by zarzen** [comment]
@tgaddair that would be great. Thanks!
