### ISSUE TITLE
RuntimeError: cuda runtime error

### ISSUE THREAD

**Issue by Maxpa1n** [horovod/horovod#1475]
**Environment:**
1. Framework: PyTorch
2. Framework version:1.1.0
3. Horovod version:0.18.2
4. MPI version:4.0.0
5. CUDA version:9.0.176
6. NCCL version:2.4.8-1
7. Python version:3.7.0
8. OS and version:ubuntu 16.04
9. GCC version:5.4.0

Please ask your question here.

`[1,0]<stderr>:THCudaCheck FAIL file=horovod/torch/cuda_util.cc line=32 error=35 : CUDA driver version is insufficient for CUDA runtime version`
`[1,0]<stderr>:Traceback (most recent call last):`
`[1,0]<stderr>:  File "test.py", line 104, in <module>`
`[1,0]<stderr>:    hvd.broadcast_parameters(model.state_dict(), root_rank=0)`
`[1,0]<stderr>:  File "/home/songran/anaconda3/envs/py_pytorch_gpu/lib/python3.7/site-packages/horovod/torch/__init__.py", line 279, in broadcast_parameters`
`[1,0]<stderr>:    handle = broadcast_async_(p, root_rank, name)`
`[1,0]<stderr>:  File "/home/songran/anaconda3/envs/py_pytorch_gpu/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 387, in broadcast_async_`
`[1,0]<stderr>:    return _broadcast_async(tensor, tensor, root_rank, name)`
`[1,0]<stderr>:  File "/home/songran/anaconda3/envs/py_pytorch_gpu/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 297, in _broadcast_async`
`[1,0]<stderr>:    tensor, output, root_rank, name.encode() if name is not None else _NULL)`
`[1,0]<stderr>:RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at horovod/torch/cuda_util.cc:32
`
I get  this Error  when I run `horovodrun -np 1 -H localhost:1 python test.py`.
I can use GPU without horovod.The model can load in GPU,and then get this error
Horovod can run without cuda.

**Comment by tgaddair** [comment]
Hey @Maxpa1n, is it possible you have more than one version of CUDA on your system?  Could you try re-installing with the following flags as in #591:

```
HOROVOD_CUDA_HOME=/path/to/cuda9.0 ... pip install -v --no-cache-dir horovod
```

**Comment by Maxpa1n** [comment]
Thank you,it is work!
