### ISSUE TITLE
Why is bitvecotr a long long type

### ISSUE THREAD

**Issue by Tron-x** [horovod/horovod#1487]
![image](https://user-images.githubusercontent.com/7659413/67916348-5fc49980-fbd0-11e9-888e-89d662c8df58.png)
When I analyze the source code and read some articles, I understand that 0 or 1 should be stored in the bitvector, but why is the long long type here? I'm confused

**Comment by Tron-x** [comment]
Each long long in bitvector_ represents a maximum of 64 sensors. What about two long long elements in bitvector_? So what does the whole bitvector_ stand for?

**Comment by VincentJing** [comment]
@Tron-x as you say, each long long in bitvector_ represents a maximum of 64 sensors. in the bitvector, there are m long long elements, as a result, it can represent m * 64 tensors,  but the first element has NUM_STATUS_BITS to represent the status, and if the timeline enabled, there are some bits to represent, The  `long long` type can make it more efficient.
