### ISSUE TITLE
Interaction with probabilistic frameworks (pyro, tensorflow probability)?

### ISSUE THREAD

**Issue by SaremS** [horovod/horovod#1495]
Hi,

does Horovod as of now interoperate with the above mentioned probabilistic frameworks for PyTorch and/or Tensorflow? Google and the Issue archive didn't really provide a clear answer I'm afraid.

Thanks for any help,
Sarem

**Comment by tgaddair** [comment]
Hey @SaremS, I'm not aware of anyone having used Horovod with Pyro or TensorFlow Probability in the past.  Is this something you're looking into?  Would be happy to help out with any issues that come up.

**Comment by SaremS** [comment]
@tgaddair Thanks for the offer and your answer. So far, this is only an idea that I have for a problem I want to solve. Once plans become more concrete, Ill definitely come back to you.
