### ISSUE TITLE
Memory usage issue when using Horovod with spark-submit and YARN

### ISSUE THREAD

**Issue by alasdairm-gr** [horovod/horovod#1497]
**Environment:**
1. Framework: Keras (but it doesn't matter)
2. Framework version:
3. Horovod version: 0.18.2
4. MPI version: 4
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.6
8. OS and version: N/A
9. GCC version: N/A

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?  N/A
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**
We have found an issue when using Horovod with YARN.  We are happy to fix this ourselves.  We would like some guidance from the Horovod community on what would be the best approach.

Scenario:
- You have a YARN cluster of 4 nodes
- You run horovod via spark-submit with 5 executors, 32GB per executor and 8 cores per executor

Result:
- 5 executors (YARN containers) are created
- One node gets 2 executors (YARN containers)
- That node gets 16 cores allocated
- 16 keras processes are started on that node through openmpi
- The 16 keras processes all share 32GB memory because they are all started inside the same YARN container
- Your process runs out of memory and crashes because you do not expect to have 16 keras processes sharing 32GB data; you expect them to be split into 2 separate containers with 8 processes sharing 32GB data

I think i found the code that causes this to happen:
https://github.com/horovod/horovod/blob/6cc9ca78515efaf3b1e553ed66f5410c86393ed8/horovod/spark/driver/mpirun_rsh.py#L32 Horovod makes the assumption that all processes on the same host have shared memory. This is not a correct assumption when you are using YARN.

Possible solutions:
Below are the solutions I can think of.  I would appreciate some advice on other approaches.

- Change the way we calculate host hashes, use one host hash per YARN container
- When starting the MPI processes, somehow work out how many containers we have on each node and then start the process on the right container (not sure how this would work)

**Comment by tgaddair** [comment]
Hey @alasdairm-gr, apologies for the late response.  Sounds like we need to modify the host_hash calculation in [host_hash.py](https://github.com/horovod/horovod/blob/master/horovod/run/common/util/host_hash.py) for YARN.  If we add information about the YARN container ID ([example](https://stackoverflow.com/questions/41724300/how-do-i-get-the-yarn-containerid-from-inside-the-container)), it should make the individual containers uniquely identifiable.

**Comment by EnricoMi** [comment]
Hi @tgaddair, adding CONTAINER_ID environment variable to the host hash fixed this problem: #1525.

It took quite some effort to understand how Horovod uses MPI to launch the Python method inside the Spark executors. I have added a description of that process to the contributors.rst file in docs, together with some more comments in the code, that would have helped me understanding the mechanics faster.

Please have a look at the PR and let me know what you think.

**Comment by tgaddair** [comment]
Thanks for the PR!  We'll go ahead and close the issue sicne #1525 has landed.
