### ISSUE TITLE
How to step through C++ part of the horovod?

### ISSUE THREAD

**Issue by zarzen** [horovod/horovod#1498]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.3.0
3. Horovod version: 0.18.2
4. MPI version: 4.0.2
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version: ubuntu 16.04
9. GCC version: 5.4.0

**Your question:**
I am trying to step through `horovod` implementations, specifically the `DoAllreduce` at `horovod/torch/mpi_ops_v2.cc` file. Because I want to know the runtime context of the function and to know when will this function be invoked by PyTorch hooks. 

I built the horovod with debug flag from source code. `CFLAGS='-Wall -O0 -g' python setup.py build`,
I didn't install the horovod, instead
I change the directory to `~/horovod/build/lib.linux-x86_64-3.7`, and setting the `PYTHONPATH` to be this folder. `export PYTHONPATH=~/horovod/build/lib.linux-x86_64-3.7:$PYTHONPATH`. 

Then launch python through `gdb`, and running the script. I have inserted the breakpoint at  the script file `pytorch_resnet50_cifar10.py`. 
```
gdb ~/.pyenv/versions/3.7.5/bin/python
<...logs>
(gdb) run -m horovod.run.run -np 2 -H localhost:2 ~/.pyenv/versions/3.7.5/bin/python ~/distributed-training/test_scripts/pytorch_resnet50_cifar10.py
```

Running with previous command results two issues:
1) there is a warning at very beginning of the execution
```
Starting program: /home/zhen/.pyenv/versions/3.7.5/bin/python -m horovod.run.run -np 2 -H localhost:2 ~/.pyenv/versions/3.7.5/bin/python ~/distributed-training/test_scripts/pytorch_resnet50_cifar10.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/home/zhen/.pyenv/versions/3.7.5/lib/python3.7/runpy.py:125: RuntimeWarning: 'horovod.run.run' found in sys.modules after import of package 'horovod.run', but prior to execution of 'horovod.run.run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```
Could you kindly explain how to resolve this runtime warning?

2) the program terminated immediately. If I remove the `import pdb; pdb.set_trace()`, the program can run. But in this case, I don't know how to intercept the training.

Any suggestions for debugging?

**Comment by tgaddair** [comment]
Hey @zarzen, I would take a look at [this](https://gist.github.com/Mistobaan/738e76c3a5bb1f9bcc52e2809a23a7a1) gist.  It documents how to attach a debugger to a running process running C++ code but launched by Python.
