### ISSUE TITLE
Memory Leak Of tensorflow_mnist_eager.py

### ISSUE THREAD

**Issue by josephren** [horovod/horovod#1501]
**Environment:**
1. Framework:Tensorflow
2. Framework version:1.12.0
3. Horovod version:0.16.2
4. MPI version:4.0.1rc3
5. CUDA version:9.0
6. NCCL version:
7. Python version:3.5
8. OS and version:
9. GCC version:5.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

When I run the demo on two cards, [tensorflow_mnist_eager.py ](https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist_eager.py
)
horovodrun -np 2 -H localhost:2 python3 tensorflow_mnist_eager.py 
the memory usage keeping going up from 0.5% to 5.9%, after 1500 steps, and it keeps going up.

When I run the demo on one card, the memory usage is 0.4%, and it does not go up.

**Comment by NigulasiChen** [comment]
The same problem with Horovod version： 0.18.1  ！！

**Comment by NigulasiChen** [comment]
this code cause the Memory Leak :
tape = hvd.DistributedGradientTape(tape)

**Comment by tgaddair** [comment]
Thanks for pointing this out, @josephren.  I'll take a look at this and see if I can repro.
