### ISSUE TITLE
Is Tensor Fusion enabled by default when I use mpirun?

### ISSUE THREAD

**Issue by zarzen** [horovod/horovod#1502]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version: 0.18.2
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Your question:**
If running distributed training with `mpirun` command, will `horovod` enable tensor fusion by default?

**Comment by tgaddair** [comment]
Hey @zarzen, yes tensor fusion is enabled by default with a 64MB buffer.  This can be configured with `horovodrun --fusion-threshold-mb` or the `HOROVOD_FUSION_THRESHOLD` environment variable.

**Comment by austinmw** [comment]
Is `HOROVOD_FUSION_THRESHOLD` also in MB?

**Comment by tgaddair** [comment]
Good question, @austinmw.  The environment variable `HOROVOD_FUSION_THRESHOLD` is actually in bytes.  When using `horovodrun`, however, there is a parameter `--fusion-threshold-mb` that is in MB.  Sorry for the confusion!
