### ISSUE TITLE
RHEL 8 support

### ISSUE THREAD

**Issue by rchinna** [horovod/horovod#1503]
Hi,

Looks like RHEL 8 comes with GCC 8 by default and that makes it hard to have G++4 libraries in the system. 

Are there any instructions to install horovod on RHEL8 without G++4.8/4.9 installation?

Thanks,
Raj

**Comment by tgaddair** [comment]
Hey @rchinna, what version of TensorFlow / PyTorch / MXNet are you using?  If you're using TensorFlow, I would suggest upgrading to TensorFlow 1.15, which can be built with newer versions of GCC.

**Comment by rchinna** [comment]
> Hey @rchinna, what version of TensorFlow / PyTorch / MXNet are you using? If you're using TensorFlow, I would suggest upgrading to TensorFlow 1.15, which can be built with newer versions of GCC.


I am using TensorFlow version 2.0. I will try building with GCC8 and see if it helps.

**Comment by tgaddair** [comment]
Hey @rchinna, any luck with 2.0?  As I mentioned in #1506, you may also want to see if there's a GCC 4.8 package available in your RHEL distribution.
