### ISSUE TITLE
An Error which is that I can't install with HOROVOD_WITH_TENSORFLOW=1

### ISSUE THREAD

**Issue by vichubtor** [horovod/horovod#1507]
**can anyone help me please?...
when I import horovod.tensorflow, there was an importError. so I reinstall it. then I got this below.** 

$ sudo HOROVOD_NCCL_HOME=/usr/local/nccl_2.4.8-1+cuda10.1_x86_64 HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_ALLREDUCE=MPI HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI HOROVOD_WITH_TENSORFLOW=1 pip3 install --no-cache-dir horovod
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple
Collecting horovod
  Downloading https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/2b/ae/c86526c637e427c4bac1b6eff890ae39493ddde7ff48b7bb497d0ceaef1b/horovod-0.18.2.tar.gz (2.9MB)
     |################################| 2.9MB 185kB/s
Requirement already satisfied: cffi>=1.4.0 in ./lib/python3.5/dist-packages (from horovod) (1.13.2)
Requirement already satisfied: cloudpickle in ./lib/python3.5/dist-packages (from horovod) (1.2.2)
Requirement already satisfied: psutil in ./lib/python3.5/dist-packages (from horovod) (5.6.5)
Requirement already satisfied: pyyaml in ./lib/python3.5/dist-packages (from horovod) (5.1)
Requirement already satisfied: six in ./lib/python3.5/dist-packages (from horovod) (1.11.0)
Requirement already satisfied: pycparser in ./lib/python3.5/dist-packages (from cffi>=1.4.0->horovod) (2.19)
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-q7z07etr/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_e6m6u8h --python-tag cp35:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/horovod
  copying horovod/__init__.py -> build/lib.linux-x86_64-3.5/horovod
  creating build/lib.linux-x86_64-3.5/horovod/common
  copying horovod/common/util.py -> build/lib.linux-x86_64-3.5/horovod/common
  copying horovod/common/basics.py -> build/lib.linux-x86_64-3.5/horovod/common
  copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/common
  creating build/lib.linux-x86_64-3.5/horovod/spark
  copying horovod/spark/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark
  creating build/lib.linux-x86_64-3.5/horovod/_keras
  copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/_keras
  copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/_keras
  creating build/lib.linux-x86_64-3.5/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/keras
  creating build/lib.linux-x86_64-3.5/horovod/mxnet
  copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/mxnet
  copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-3.5/horovod/mxnet
  creating build/lib.linux-x86_64-3.5/horovod/run
  copying horovod/run/mpi_run.py -> build/lib.linux-x86_64-3.5/horovod/run
  copying horovod/run/run.py -> build/lib.linux-x86_64-3.5/horovod/run
  copying horovod/run/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run
  copying horovod/run/gloo_run.py -> build/lib.linux-x86_64-3.5/horovod/run
  copying horovod/run/task_fn.py -> build/lib.linux-x86_64-3.5/horovod/run
  creating build/lib.linux-x86_64-3.5/horovod/torch
  copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/torch
  copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch
  copying horovod/torch/compression.py -> build/lib.linux-x86_64-3.5/horovod/torch
  creating build/lib.linux-x86_64-3.5/horovod/tensorflow
  copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
  copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
  creating build/lib.linux-x86_64-3.5/horovod/spark/driver
  copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
  copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
  copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
  copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
  creating build/lib.linux-x86_64-3.5/horovod/spark/task
  copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
  copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
  copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
  creating build/lib.linux-x86_64-3.5/horovod/run/common
  copying horovod/run/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common
  creating build/lib.linux-x86_64-3.5/horovod/run/util
  copying horovod/run/util/network.py -> build/lib.linux-x86_64-3.5/horovod/run/util
  copying horovod/run/util/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/util
  copying horovod/run/util/threads.py -> build/lib.linux-x86_64-3.5/horovod/run/util
  copying horovod/run/util/cache.py -> build/lib.linux-x86_64-3.5/horovod/run/util
  creating build/lib.linux-x86_64-3.5/horovod/run/rendezvous
  copying horovod/run/rendezvous/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/rendezvous
  copying horovod/run/rendezvous/http_server.py -> build/lib.linux-x86_64-3.5/horovod/run/rendezvous
  creating build/lib.linux-x86_64-3.5/horovod/run/driver
  copying horovod/run/driver/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/run/driver
  copying horovod/run/driver/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/driver
  creating build/lib.linux-x86_64-3.5/horovod/run/task
  copying horovod/run/task/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/task
  copying horovod/run/task/task_service.py -> build/lib.linux-x86_64-3.5/horovod/run/task
  creating build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/network.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/config_parser.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/env.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/codec.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/timeout.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/secret.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/host_hash.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  copying horovod/run/common/util/settings.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
  creating build/lib.linux-x86_64-3.5/horovod/run/common/service
  copying horovod/run/common/service/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
  copying horovod/run/common/service/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
  copying horovod/run/common/service/task_service.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
  creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
  copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
  creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
  copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
  creating build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
  copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
  copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
  running build_ext
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.so
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_link_flags.o
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.5/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_link_flags.so
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -I/usr/local/cuda/include -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.o
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lcudart -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.so
  error: import tensorflow failed, is it installed?

  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/usr/lib/python3.5/imp.py", line 242, in load_module
      return load_dynamic(name, filename, file)
    File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-q7z07etr/horovod/setup.py", line 72, in check_tf_version
      import tensorflow as tf
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
      from tensorflow.python import *
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
      from tensorflow.python import pywrap_tensorflow
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
      raise ImportError(msg)
  ImportError: Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
      from tensorflow.python.pywrap_tensorflow_internal import *
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
      _pywrap_tensorflow_internal = swig_import_helper()
    File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
      _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
    File "/usr/lib/python3.5/imp.py", line 242, in load_module
      return load_dynamic(name, filename, file)
    File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
      return _load(spec)
  ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

  Failed to load the native TensorFlow runtime.

  See https://www.tensorflow.org/install/install_sources#common_installation_problems

  for some common reasons and solutions.  Include the entire stack trace
  above this error message when asking for help.

  ----------------------------------------
  ERROR: Failed building wheel for horovod
  Running setup.py clean for horovod
Failed to build horovod
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-q7z07etr/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0un5s1f8/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.5/horovod
    creating build/lib.linux-x86_64-3.5/horovod/common
    copying horovod/common/util.py -> build/lib.linux-x86_64-3.5/horovod/common
    copying horovod/common/basics.py -> build/lib.linux-x86_64-3.5/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/common
    creating build/lib.linux-x86_64-3.5/horovod/spark
    copying horovod/spark/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark
    creating build/lib.linux-x86_64-3.5/horovod/_keras
    copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/_keras
    copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/_keras
    creating build/lib.linux-x86_64-3.5/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/keras
    creating build/lib.linux-x86_64-3.5/horovod/mxnet
    copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/mxnet
    copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-3.5/horovod/mxnet
    creating build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/mpi_run.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/run.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/gloo_run.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/task_fn.py -> build/lib.linux-x86_64-3.5/horovod/run
    creating build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/compression.py -> build/lib.linux-x86_64-3.5/horovod/torch
    creating build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    creating build/lib.linux-x86_64-3.5/horovod/spark/driver
    copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
    copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
    copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
    copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
    creating build/lib.linux-x86_64-3.5/horovod/spark/task
    copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
    copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
    copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
    creating build/lib.linux-x86_64-3.5/horovod/run/common
    copying horovod/run/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common
    creating build/lib.linux-x86_64-3.5/horovod/run/util
    copying horovod/run/util/network.py -> build/lib.linux-x86_64-3.5/horovod/run/util
    copying horovod/run/util/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/util
    copying horovod/run/util/threads.py -> build/lib.linux-x86_64-3.5/horovod/run/util
    copying horovod/run/util/cache.py -> build/lib.linux-x86_64-3.5/horovod/run/util
    creating build/lib.linux-x86_64-3.5/horovod/run/rendezvous
    copying horovod/run/rendezvous/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/rendezvous
    copying horovod/run/rendezvous/http_server.py -> build/lib.linux-x86_64-3.5/horovod/run/rendezvous
    creating build/lib.linux-x86_64-3.5/horovod/run/driver
    copying horovod/run/driver/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/run/driver
    copying horovod/run/driver/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/driver
    creating build/lib.linux-x86_64-3.5/horovod/run/task
    copying horovod/run/task/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/task
    copying horovod/run/task/task_service.py -> build/lib.linux-x86_64-3.5/horovod/run/task
    creating build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/network.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/config_parser.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/env.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/codec.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/timeout.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/secret.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/host_hash.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/settings.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    creating build/lib.linux-x86_64-3.5/horovod/run/common/service
    copying horovod/run/common/service/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
    copying horovod/run/common/service/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
    copying horovod/run/common/service/task_service.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
    creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.so
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_link_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.5/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_link_flags.so
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -I/usr/local/cuda/include -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lcudart -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.so
    error: import tensorflow failed, is it installed?

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/usr/lib/python3.5/imp.py", line 242, in load_module
        return load_dynamic(name, filename, file)
      File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-q7z07etr/horovod/setup.py", line 72, in check_tf_version
        import tensorflow as tf
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
        from tensorflow.python import *
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
        from tensorflow.python import pywrap_tensorflow
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
        raise ImportError(msg)
    ImportError: Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
        from tensorflow.python.pywrap_tensorflow_internal import *
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
        _pywrap_tensorflow_internal = swig_import_helper()
      File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
        _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
      File "/usr/lib/python3.5/imp.py", line 242, in load_module
        return load_dynamic(name, filename, file)
      File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
        return _load(spec)
    ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

    Failed to load the native TensorFlow runtime.

    See https://www.tensorflow.org/install/install_sources#common_installation_problems

    for some common reasons and solutions.  Include the entire stack trace
    above this error message when asking for help.

    ----------------------------------------
ERROR: Command "/usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-q7z07etr/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0un5s1f8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-q7z07etr/horovod/

**Comment by tgaddair** [comment]
Hey @vichubtor, what versions of TensorFlow and CUDA are you using?  Can you try running `ldconfig -v` and print the result?
