### ISSUE TITLE
Improve documentation on Horovod installation

### ISSUE THREAD

**Issue by Flamefire** [horovod/horovod#1508]
Judging by the logic in https://github.com/horovod/horovod/blob/38e91bee84efbb5b563a4928027a75dc3974633b/setup.py#L1369 it is clear, that before installing Horovod one needs to install the underlying framework(s) (TensorFlow, PyTorch, ...).

This is not mentioned in the installation instructions which made me think, I can install Horovod and then any framework I like (or switch between them) and it will work, but (I guess) it won't.

- Can you clarify the dependencies on the framework(s)?
- Do you need to have all frameworks installed when installing Horovod?
- Can you upgrade a framework after installing Horovod? Or do you need to reinstall Horovod?
- Can you uninstall a framework after installing Horovod? E.g. Have TF+PyTorch installed, install Horovod, uninstall PyTorch, use Horovod+TF

**Comment by tgaddair** [comment]
Hey @Flamefire, thanks for bringing this up.  We can definitely add this to the docs.

To answer your questions here:

- Most of Horovod's dependencies are included in the requirements, except for specific training frameworks (TensorFlow, Keras, PyTorch, MXNet).
- For any framework you want to use with Horovod, it should be installed at the time you install Horovod.
- To be safe, we recommend reinstalling Horovod whenever you upgrade a framework.  In some cases it may still work (if APIs haven't changed between versions), but often times it will not.
- You can safely uninstall a framework and still use Horovod with a different framework, yes.

**Comment by alokprasad** [comment]
@tgaddair i feel documentation need information.specially simplest multihost setup.
1. Example for 2 Machine with single GPU each 
2 .prerequisite like same interface name in all host etc.
3.Recommended for system , like higher bw networking backbone as most of the general user might be using 1G interface which might not give them required speed boost in training as they would have expected.
4.Diagram of simple host setup 
5. How dataset needs to accessed , copy on each host or shared network storage.
