### ISSUE TITLE
Where is the partitioning of the gradients done for Ring AllReduce?

### ISSUE THREAD

**Issue by hpc-unex** [horovod/horovod#1510]
Hello, im trying to undestard the communication code, and as I see in the original paper, the gradients are divided in hvd.size() partitions and then the allreduce is done in 2*(N-1) steps, but I cannot find that code in the framework. Im working under Torch.

**Comment by tgaddair** [comment]
Hey @hpc-unex, this is handled by the underlying implementation of `Allreduce` in MPI, NCCL, Gloo, etc.  You can see an example implementation for Gloo [here](https://github.com/facebookincubator/gloo/blob/master/gloo/allreduce_ring.h).
