### ISSUE TITLE
old GCC compiler on Dockerfile.gpu 

### ISSUE THREAD

**Issue by vilmara** [horovod/horovod#1511]
I see the Dockerfile.gpu still refers gcc 4.8 version even though it builds from ubuntu18.04 with TENSORFLOW_VERSION=2.0.0, should the Dockerfile be updated to use a newer version of gcc compiler?, if so what is the recommended version?

**Comment by tgaddair** [comment]
Hey @vilmara, I believe we can safely remove that going forward, thanks for pointing that out.  The version of GCC that comes with ubuntu18.04 should be ABI compatible with the latest TensorFlow, as should any version >= GCC 5.  You can check which version of GCC was used to compile TensorFlow with `tf.version.COMPILER_VERSION` to be safe.

**Comment by vilmara** [comment]
@tgaddair, I got it. Thanks!
