### ISSUE TITLE
for help: training seized up when synchronize 

### ISSUE THREAD

**Issue by zjusgy** [horovod/horovod#1517]
**Environment:**
1. Framework: PyTorch
2. Framework version:
3. Horovod version:0.18.2
4. MPI version:4.0.2
5. CUDA version:9.0
6. NCCL version:2.2.13
7. Python version:3.5
8. OS and version:Ubuntu 16.04
9. GCC version:5.4.0

Hello:
I've run codes for distributed pretraining bert with pytorch. 
However, it seized up at optimizer.step(). I found it can be traced back to 
`output = synchronize(handle)` and exactly 
`mpi_lib.horovod_torch_wait_and_clear(handle)`.
It happens when allreduce_async_ input tensor.
I want to know what happens when `mpi_lib.horovod_torch_wait_and_clear(handle)`

**Comment by tgaddair** [comment]
Hey @zjusgy, what version of PyTorch are you using?  `wait_and_clear(handle)` is like a "join" operation following a "fork" (in multithreading terms).  You can see the implementation for PyTorch >=1.0 [here](https://github.com/horovod/horovod/blob/master/horovod/torch/mpi_ops_v2.cc#L228).

Does training also hang if you run one of our examples scripts like [pytorch_mnist.py](https://github.com/horovod/horovod/blob/master/examples/pytorch_mnist.py)?

**Comment by zjusgy** [comment]
Thx, @tgaddair , My version of Pytorch is 1.0.0.
yep, it also hangs when I try to run pytorch_mnist.py at same line.
I try to `synchronize(handle)` in `_allreduce_async` and I got this error:
`ncclGetUniqueId failed: unhandled system error`
with `NCCL_DEBUG=WARN` I got warning like this:
` transport/net_ib.cu:103 WARN NET/IB : No IP interface found.`
`include/socket.h:311 WARN Socket creation failed : Address family not supported by protocol`
