### ISSUE TITLE
For the large Full Connect layer 

### ISSUE THREAD

**Issue by Sampson1107** [horovod/horovod#152]
@alsrgv 
If  one full connect layer have the 90 percent  weight parameters in a 100 layers network, is there any method to split the gradients and  allreduce them?

**Comment by alsrgv** [comment]
@Sampson1107, you could try to define two (or more) separate dense layers that would be placed on different GPUs using `with tf.device('/gpu:X)`, and then concatenate them.  You can then use Horovod across workers.

E.g.:

```python
x = Dense(1000)(x)
```

Will become:
```python
with tf.device('/gpu:0'):
  x1 = Dense(250)(x)
with tf.device('/gpu:1'):
  x2 = Dense(250)(x)
with tf.device('/gpu:2'):
  x3 = Dense(250)(x)
with tf.device('/gpu:3'):
  x4 = Dense(250)(x)
x = Concatenate()([x1, x2, x3, x4])
```
