### ISSUE TITLE
Incremental build support

### ISSUE THREAD

**Issue by rb-determined-ai** [horovod/horovod#1520]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow
2. Framework version: TF 1.14.0
3. Horovod version: tip of master
4. MPI version:
5. CUDA version: 10.0
6. NCCL version: tip of master
7. Python version: 3.6.8
8. OS and version: Ubuntu 18.04
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes.

**Your question:**

Is there any way to do an incremental build of horovod?  I can't figure out a way to build horovod from a local copy of the source code, except through `pip install .`, but that seems to build from scratch every time, regardless of changes to the source code.

**Comment by tgaddair** [comment]
Hey @rb-determined-ai, are you modifying C++ or Python files?  For C++, I'm not aware of any way to speed things up currently other than to exclude frameworks you're not using (e.g., `HOROVOD_WITHOUT_TENSORFLOW=1`.  That said, we have plans to migrate our build process to CMake sometime next year, which should enable incremental build support (though we haven't yet tested that).

For Python, things are a bit easier, you can just rsync or cp the files into the install path and things should work fine.

**Comment by rb-determined-ai** [comment]
Yeah, I'm referring to the C++ code.  I'll look forward to the CMake build system.
