### ISSUE TITLE
GPU utilization when running using MPI commands on 2 computers

### ISSUE THREAD

**Issue by HassamSheikh** [horovod/horovod#1522]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TF
2. Framework version: 1.13.1
3. Horovod version: 0.18.2
4. MPI version: 4. 0. 0
5. CUDA version: 10.1
6. NCCL version:2.4.8
7. Python version:3.6.8
8. OS and version: Ubuntu 18.04
9. GCC version: 4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/running.rst)? yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? No
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

Server1: 1 GPU (1070)
Server2: 2 GPU (1080Ti)

**Your question:**
I have been trying to run the benchmark examples using 
```
mpirun -np 3 -H server1:1,server2:2\
   -bind-to none -map-by slot \
   -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
   -x NCCL_SOCKET_IFNAME=^virbr0 \
   -mca btl_tcp_if_exclude virbr0 \
   -mca pml ob1 -mca btl ^openib \
   python3.6 tensorflow_word2vec.py

```
The problem I have been facing is very low gpu to 0 gpu utilization of the gpus, especially on the server2. I tried running  

```
mpirun -np 2 -H server2:2\
   -bind-to none -map-by slot \
   -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
   -x NCCL_SOCKET_IFNAME=^virbr0 \
   -mca btl_tcp_if_exclude virbr0 \
   -mca pml ob1 -mca btl ^openib \
   python3.6 tensorflow_word2vec.py

```
from server1, and it was running perfectly fine. i.e high gpu utilization on server2. so I am assuming that the mpi command is running only on 1 machine? Can someone help?

**Comment by tgaddair** [comment]
Hey @HassamSheikh, could you try creating a [timeline](https://github.com/horovod/horovod/blob/master/docs/timeline.rst) for the 3 GPU / 2 server case?  My guess is that server2 is spending a lot of time waiting for server1 to catch up, which is leading to low utilization.
