### ISSUE TITLE
OS Issue

### ISSUE THREAD

**Issue by ujjawalcse** [horovod/horovod#1524]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
Is there any documentation to set up it on a windows machine?
I'm getting stuck at installing Open MPI on my windows machine.

**Comment by tgaddair** [comment]
Hey @ujjawalcse, I would suggest taking a look at #758.  My understanding is that some people have successfully installed Horovod on Windows, but I have not tried it myself.

**Comment by ujjawalcse** [comment]
Thanks for your response.
