### ISSUE TITLE
Horovod doesn't work when I use 2 machines, each machine has 8 GPUs.

### ISSUE THREAD

**Issue by VincentJing** [horovod/horovod#1526]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version: Tensorflow
3. Horovod version: 0.18.2
4. MPI version: 4.0.2
5. CUDA version: 10.0
6. NCCL version: 2.4.8
7. Python version: 3.5.2
8. OS and version: ubuntu 16.04
9. GCC version: 4.9

**Checklist:**
1. Did you search issues to find if somebody asked this question before? 
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
when I compile the source code by myself.  
`python setup.py sdist`
`sudo HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1  HOROVOD_CUDA_HOME=/data/cuda/cuda-10.0/cuda pip3 install --no-cache-dir dist/horovod-0.18.2.tar.gz `
it could install horovod successfully. and it can work by the instruction:
`horovodrun -np 8 -H localhost:8 --timeline-filename timeline.txt --timeline-mark-cycles  python nvcnn_hvd.py --model resnet50 --num_batches 200 --b 16 --data_dir=/data/imagenet
`
but when i use 2 machines:
`horovodrun -np 16 -H host1:8,host2:8  python nvcnn_hvd.py --model resnet50 --num_batches 200 --b 32 --data_dir=/data/imagenet`
it seems that horovod lanched normally, but it can't work well. the result is as follows:
![image](https://user-images.githubusercontent.com/20381269/69243932-fcca8f00-0bde-11ea-83cf-d188e8c25610.png)
it will stay the situation all the time.
I don't know why?  Could someone help me?

**Comment by tgaddair** [comment]
Hey @VincentJing, to clarify, does Horovod get stuck there and is unable to continue?  Have you tried running the [tensorflow_synthetic_benchmark.py](https://github.com/horovod/horovod/blob/master/examples/tensorflow_synthetic_benchmark.py) example, and does it have the same issues?

**Comment by VincentJing** [comment]
I have solved the problem by reinstalling the openMPI
