### ISSUE TITLE
Where is Horovod shared library normally installed on Ubuntu?

### ISSUE THREAD

**Issue by meshaun9** [horovod/horovod#1528]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:latest
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:Ubuntu 18.04
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?yes

**Your question:**
Where is Horovod shared library(.so) normally installed on Ubuntu?

**Comment by tgaddair** [comment]
Hey @meshaun9, if you're running outside a virtual environment, it will typically be something like `/usr/lib/python3.6/site-packages`.  You can check the install path in Python like so:

```
import horovod
print(horovod.__path__)
```

We build a separate `.so` for each framework you install, so you may have multiple libraries like:

```
/usr/lib/python3.6/site-packages/horovod-0.18.2-py3.6-linux-x86_64.egg/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so
/usr/lib/python3.6/site-packages/horovod-0.18.2-py3.6-linux-x86_64.egg/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so
```

**Comment by meshaun9** [comment]
Hi @tgaddair  I saw the mpi*.so  but is their one specific for Tensorflow?

**Comment by tgaddair** [comment]
Hey @meshaun9, yes, the `mpi_lib.*.so` under `horovod/tensorflow` is specific to TensorFlow.  That contains the compiled custom op used to connect TensorFlow to Horovod.
