### ISSUE TITLE
horovod with tensorflow--More GPU, More RAM?

### ISSUE THREAD

**Issue by ahzz1207** [horovod/horovod#1534]
**Environment:**
1. Framework: tf
2. Framework version:1.14
3. Horovod version:0.18
4. MPI version:4.0.2
5. CUDA version:10.0
6. NCCL version:2.0
7. Python version:3.6
8. OS and version:linux & k8s 
9. GCC version:4.9

**Your question:**
I found that when I use more GPUs to run script I will meet bug that  process get killed(exited signal 9), when I increase RAM to run the same cmd, this bug is gone.
So I wunder if every process  will copy one inputfile to RAM,  it means that I will use (number of GPUs * inputfiles_size) amount RAM in my machine ?
Thanks!

**Comment by tgaddair** [comment]
Hey @ahzz1207, yes, if you run (for example): `horovodrun -np 4 ...` then there will be 4 copies of the same process running on the same machine (but using different GPUs).  That means that any input files that get read in by that process will be read in multiple times.

**Comment by ahzz1207** [comment]
> Hey @ahzz1207, yes, if you run (for example): `horovodrun -np 4 ...` then there will be 4 copies of the same process running on the same machine (but using different GPUs). That means that any input files that get read in by that process will be read in multiple times.

Thank u for replay. So if I want to avoid the OOM Killer of Linux in Docker way on k8s, I must set bigger RAM to run the horovod on more GPUs. 
That would be great if u can imporve it, let every process read inputs from RAM for only one copy.
