### ISSUE TITLE
how to define Noam optimizer in horovod.torch?

### ISSUE THREAD

**Issue by kaituoxu** [horovod/horovod#1541]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

I define norm optimizer (Transformer's optimizer) like below:
```
class NoamOpt(object):
    def __init__(self, model_size, factor, warmup, optimizer):
        pass
...
```
But below code can not run correctly:
```
optimizer = torch.optim.Adam(model.parameters(), lr=0, betas=(0.9, 0.98), eps=1e-9)
optimizer = NormOpt(model_size, factor, warmup, optimizer)
optimizer = hvd.DistributedOptimizer(optimizer,
                                             named_parameters=model.named_parameters(),
                                             backward_passes_per_step=args.accum_grad)
```
because in https://github.com/horovod/horovod/blob/master/horovod/torch/__init__.py#L57 will get error
```
TypeError: __init__() missing 3 required positional arguments: 'factor', 'warmup', and 'optimizer'
```
So, how to define Noam optimizer in horovod.torch? Thx.

**Comment by roclark** [comment]
Hey @kaituoxu! Did you ever find a solution to this? I'm running into a similar issue when I use a custom optimizer with additional parameters and am trying to figure out how to get it working.

Thanks for any help!

**Comment by yuekaizhang** [comment]
Hey,@tgaddair, I was wondering whether you have some time to answer it? I encountered the same issue. I believe support for noam would be a very helpful feature.

**Comment by tgaddair** [comment]
Hey @yuekaizhang, do you have a complete example of the optimizer implementation?  If it extends from `torch.optim.Optimizer`, it should work.
