### ISSUE TITLE
Mixed precision support for MXNet 

### ISSUE THREAD

**Issue by haven-jeon** [horovod/horovod#1553]
**Environment:**
1. Framework: MXNet
2. Framework version: 1.5.1
3. Horovod version: 0.18.2
4. MPI version: 4.0
5. CUDA version: 10.0
6. NCCL version: 2.4.7-1+cuda10.0
7. Python version: 3.6
8. OS and version: ubuntu18.04
9. GCC version: 4.8

Does horovod support mixed precision triaining(amp) for MXNet？

**Comment by tgaddair** [comment]
Hey @apeforest and @yuxihu, can you comment on the status of AMP + Horovod with MXNet?

**Comment by apeforest** [comment]
@haven-jeon Yes, AMP + Horovod works with MXNet. Please refer to https://mxnet.apache.org/api/python/docs/tutorials/performance/backend/amp.html

**Comment by haven-jeon** [comment]
As I see #1089 case of pytorch.

> Important things:
> 
>     Do amp.initialize() after optimizer is wrapped into DistributedOptimizer.
>     Do optimizer.synchronize() within scale_loss block (code).

Do I need to add `optimizer.synchronize()` like codes on MXNet scripts?

**Comment by karan6181** [comment]
@haven-jeon No. You don't need to add `optimizer.synchronize()` separately. Distributed Trainer Handles this for you. Here is another example of `amp` with MXNet/Gluon.

https://github.com/dmlc/gluon-cv/blob/master/scripts/instance/mask_rcnn/train_mask_rcnn.py

You will find more examples in `gluon-cv`.

**Comment by haven-jeon** [comment]
Thanks @karan6181 !
