### ISSUE TITLE
 module 'horovod.tensorflow' has no attribute 'Average'

### ISSUE THREAD

**Issue by rahul003** [horovod/horovod#1569]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TF
2. Framework version: 1.15
3. Horovod version: 0.18.2
4. MPI version: 4.0.1
5. CUDA version: 10.0
6. NCCL version:
7. Python version: 3.6
8. OS and version: Ubuntu 16.04
9. GCC version: 

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Not hang
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Not docker
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?  Not there

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

```bash
mpirun -np 4     -bind-to none -map-by slot     -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH     -mca pml ob1 -mca btl ^openib -x PYTHONPATH=~/sagemaker-debugger/ -x SMDEBUG_CONFIG_FILE_PATH=config.json python examples/tensorflow/sagemaker_official_container/tensorflow_mnist.py
```
When I run the tensorflow_mnist.py example, it crashes on this line https://github.com/horovod/horovod/blob/c8fef498d35b5087fba754b8c92ace6a2b75e3ec/examples/tensorflow_mnist.py#L130

I have verified that the horovod version is 0.18.2 from the training process logs

```
Traceback (most recent call last):
  File "examples/tensorflow/sagemaker_official_container/tensorflow_mnist.py", line 175, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "examples/tensorflow/sagemaker_official_container/tensorflow_mnist.py", line 133, in main
    opt = hvd.DistributedOptimizer(opt, op=hvd.Adasum if args.use_adasum else hvd.Average)
AttributeError: module 'horovod.tensorflow' has no attribute 'Average'
```

**Comment by tgaddair** [comment]
Hey @rahul003, the examples on GitHub have changes from the upcoming `0.19.0` release, which is not out yet.  Could you try pulling the examples from tag `v0.18.2`?

**Comment by surak** [comment]
Worked for me on every test which failed before. You can close this

**Comment by jarednielsen** [comment]
Getting a similar issue with `horovod.tensorflow.size()` on horovod 0.18.2. I believe it's related, let's re-open and resolve the issue.

**Comment by tgaddair** [comment]
Hey Jared, can you create a new issue for your problem?  I suspect there may be something else going on in your case.
