### ISSUE TITLE
Error using horovod to run tensorflow benchmark

### ISSUE THREAD

**Issue by Agoniii** [horovod/horovod#157]
tensorflow version: 0.15.0rc
horovod version: 0.11.2
NCCL version 2.1.2+cuda9.0

I used horovod to run tensorflow benchmark on one machines with 8 gpus . My command is as follows(using the HOROVOD_FUSION_THRESHOLD):
```
/usr/local/openmpi-3.0.0/bin/mpirun --allow-run-as-root  -np 8  -bind-to none -map-by slot  -x LD_LIBRARY_PATH -x NCCL_DEBUG=INFO python tf_cnn_benchmarks.py --num_batches 100 --display_every 1 --num_gpus 1 --model resnet50 --batch_size 128 --data_name imagenet --data_dir /data0/imagenet_data --variable_update horovod --horovod_device gpu --batch_group_size=4 --num_inter_threads 0 --optimizer momentum
```
But it got the error :

```
total images/sec: 1476.57
----------------------------------------------------------------
--------------------------------------------------------------------------
The call to cuIpcCloseMemHandle failed. This is a warning and the program
will continue to run.
  cuIpcCloseMemHandle return value:   4
  address: 0x7f48ac600000
Check the cuda.h file for what the return value means. Perhaps a reboot
of the node will clear the problem.
--------------------------------------------------------------------------
[node00:11635] Sleep on 11635
[node00:11627] Sleep on 11627
[node00:11629] Sleep on 11629
[node00:11618] 2 more processes have sent help message help-mpi-common-cuda.txt / cuIpcCloseMemHandle failed
[node00:11618] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[node00:11618] 1 more process has sent help message help-mpi-common-cuda.txt / cuIpcCloseMemHandle failed
[node00:11629] Sleep on 11629
[node00:11635] Sleep on 11635
[node00:11627] Sleep on 11627
[node00:11618] 2 more processes have sent help message help-mpi-common-cuda.txt / cuIpcCloseMemHandle failed
```

**Comment by alsrgv** [comment]
@Agoniii, you can ignore that error - it happens with CUDA-aware Open MPI upon TensorFlow termination and is not harmful.

**Comment by Agoniii** [comment]
@alsrgv Thanks for your quick answer. I have another question to ask you please.

When I run on  two machines with 8 gpus per machine. My command is as follows(using the HOROVOD_FUSION_THRESHOLD):
```
/usr/local/openmpi-3.0.0/bin/mpirun --allow-run-as-root  -np 2  -H node00:1,node01:1 -bind-to none -map-by slot -x LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x HOROVOD_FUSION_THRESHOLD=4194304 -x NCCL_SOCKET_IFNAME=eth0 python tf_cnn_benchmarks.py --num_batches 100 --display_every 1 --num_gpus 1 --model resnet50 --batch_size 128 --data_name imagenet --data_dir /data0/imagenet_data --variable_update horovod --horovod_device gpu --batch_group_size=4 --num_inter_threads 0 --optimizer momentum
```
My results are vary greatly within 5 tests. 

| Test1 | Test2 | Test3 | Test4 | Test5 |
| :------- : | :------- : | :------- : | :------- : | :------- : |
| 2082.97 | 1217.45 | 1149.17 | 2310.15 | 1311.98 |

**Comment by alsrgv** [comment]
@Agoniii, few questions:

1. What kind of network do you have between machines?
2. How much does performance fluctuate during each run, as it prints out images/sec?
3. Can you try specifying large `--num_batches` value, say 1000, and report if you see any difference in the behavior?

**Comment by Agoniii** [comment]
@alsrgv 
1. Network between machines is 10 GbE. 
2. The performance fluctuate:
   for test4: 100 images/sec: 144.6 +/- 3.2 (jitter = 45.5) 
   for test5: 100 images/sec: 82.0 +/- 2.6 (jitter = 27.1) 
3. I found that I did not set  `HOROVOD_GPU_ALLREDUCE=NCCL` When I installed horovod.
After reinstalled with NCCL, the results are relatively stable:
| Test1 | Test2 | Test3 | Test4 | Test5 |
|:-------:|:-------:|:-------:|:-------:|:-------:|
|2832.89 | 2801.24 | 2772.92 | 2608.41 | 2759.93 |

**Comment by alsrgv** [comment]
@Agoniii, that's a little better.  What performance do you get on a single GPU?  10 GbE is on a lower side, we typically recommend 25-50 GbE for Pascal and 50-100 GbE for Volta.
