### ISSUE TITLE
how to run horovod with multi-machine on conda env

### ISSUE THREAD

**Issue by misslibra** [horovod/horovod#1572]
**Environment:**
1. Framework: PyTorch
2. Framework version:
3. Horovod version:0.18.2
4. MPI version:4.0.2
5. CUDA version:10.1
6. NCCL version:2
7. Python version:3.7
8. OS and version:ubutnu 16.04
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I have 3 machines, each with 1 GPU 2080ti,and their  env is the same  in conda.
but these 3 are not connected in a cluster, only connection in local network.
can I use horovod for distribute training ?
how to set IP to run horovod ?

**Comment by tgaddair** [comment]
Hey @misslibra, as long as you can ssh between the machines, then you should be able to run distributed training.  Then you can just specify `horovodrun -np 3 -H server_ip1:1,server_ip2:1,server_ip3:1 ...`.

**Comment by misslibra** [comment]
thanks for your support! 
I run: horovodrun -np 2 -H ip1:2 ip2:2 ~/anaconda3/envs/py37/bin/python  path_to_my_script/train.py
but I got error:
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       l4-Precision-7820-Tower
Executable: 10.202.91.232:2
--------------------------------------------------------------------------
2 total processes failed to start

**Comment by misslibra** [comment]
problem fix,by install openmpi and horovod 
troubleshooting docs can be helpfull:
https://horovod.readthedocs.io/en/latest/troubleshooting_include.html

**Comment by always-H** [comment]
It seems that it should be "ip1:1,ip2:1" instead of "ip1:1 ip2:1". I guess it's not a correct format ues " " between ip. It works fine for me.
