### ISSUE TITLE
No module named horovod

### ISSUE THREAD

**Issue by Vidyaranya** [horovod/horovod#1574]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 1.11.0
3. Horovod version: NA
4. MPI version: 3.1.2
5. CUDA version: 9.0
6. NCCL version: 2.3.5-2+cuda9.0
7. Python version: 2.7
8. OS and version: ubuntu16.04
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I am new to Singularity and Horovod. So, this might be a very basic question! I was trying to run horovod by using the singularity as explained here: https://github.com/sylabs/examples/tree/master/machinelearning/horovod To briefly put what I have done, I have copied the [horovod.def](https://raw.githubusercontent.com/sylabs/examples/master/machinelearning/horovod/horovod.def) file and run the command 

`sudo singularity build horovod.sif horovod.def`
 I was able to successfully build the image. However, when I try to import horovod, I get No module named horovod found error

```
$ singularity shell horovod.sif 
Singularity: Invoking an interactive shell within container...

Singularity horovod.sif:~> python
Python 2.7.12 (default, Oct  8 2019, 14:14:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named horovod
```
I believe that this error should not pop up as the singularity image already has horovod installed. Any help is greatly appreciated. Thanks!

**Comment by s-0** [comment]
Hi @Vidyaranya, 

You probably have various versions of Python installed. 

Try the following command to ensure you are installing it to your current environment:

`python -m pip install horovod `
