### ISSUE TITLE
how to control data transfer frequency between nodes ?

### ISSUE THREAD

**Issue by misslibra** [horovod/horovod#1589]
**Environment:**
1. Framework: PyTorch
2. Framework version:
3. Horovod version:0.18.2
4. MPI version:4.0
5. CUDA version:10.1
6. NCCL version:2.5.6
7. Python version:3.7
8. OS and version:linux16.04
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?--yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?--No,i use conda env
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?--yes

**Your question:**
Please ask your question here.
1. my two machine are connected to a Gigabit Switch, ssh to each other without password.
I use iftop to see the traffic,transfer and receive traffic is up to 600Mb
And I try to connected two machines directionly, no improvement. So I think this may not caused by network traffic.
2. command:
horovodrun -np 2 -H 10.202.91.230:1,10.202.91.232:1 ~/anaconda3/envs/py37/bin/python ~/Documents/training/train.py
run success,and training log is normal
BUT : train process is even slower than one machine with one gpu
one machine training without horovod ,500 epoch, costs about 20h,  GPU-Util is 80%-98%
but two machine training with horovod,50h only train 300 epoch , GPU-Util is only 1% - 20%
CPU usage is normal for these two situations
Please help me ,my code is like this:

**Comment by misslibra** [comment]
`if __name__ == "__main__":
    '''DDP SETTING '''
    torch.manual_seed(317)
    torch.cuda.manual_seed(317)
    if 'WORLD_SIZE' in os.environ:
        args.distributed = int(os.environ['WORLD_SIZE']) > 1
    if args.distributed and not FLAGS_horovod:
        torch.cuda.set_device(args_plus.local_rank)
        torch.distributed.init_process_group(backend='nccl', init_method='env://')
        args.world_size = torch.distributed.get_world_size()
    elif args.distributed and  FLAGS_horovod:
        hvd.init()
        torch.cuda.set_device(hvd.local_rank())
    assert torch.backends.cudnn.enabled, "Amp requires cudnn backend to be enabled."
    ''' Get dataloader'''
    dataset = ListDataset(train_path, class_names, augment=False, multiscale=args.multiscale_training)
    train_sampler = None
    if args.distributed and not FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
    elif args.distributed and FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset,
                                                                        num_replicas=hvd.size(), rank=hvd.rank())
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=(train_sampler is None),
        num_workers=args.n_cpu,
        pin_memory=True,
        sampler=train_sampler,
        collate_fn=dataset.collate_fn)
    ''' init  model'''
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = Darknet(args.model_def).to(device)
    if args.sync_bn and FLAGS_amp and args.distributed:
        print("using apex synced BN")
        model = apex.parallel.convert_syncbn_model(model)
    model = model.cuda()
    model.apply(weights_init_normal)
    if args.pretrian:
        if args.restore_path.endswith(".pth"):
            model.load_state_dict(torch.load(args.restore_path))
        else:
            model.load_darknet_weights(args.restore_path)
    optimizer = config_optimizer(model.parameters(), args.optimizer_name, args.learning_rate_init, args.momentum)
    if args.distributed and FLAGS_horovod:
        optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=model.named_parameters())
        hvd.broadcast_parameters(model.state_dict(), root_rank=0)
        hvd.broadcast_optimizer_state(optimizer,root_rank=0)

    if FLAGS_amp:
        amp.register_float_function(torch, 'sigmoid')
        model, optimizer = amp.initialize(model, optimizer,
                                        opt_level=args.opt_level,
                                        keep_batchnorm_fp32=args.keep_batchnorm_fp32,
                                        loss_scale=args.loss_scale
                                        )
    for epoch in range(args.total_epoches):
        if args.distributed:
            train_sampler.set_epoch(epoch)
        model.train()
        prefetcher = data_prefetcher(dataloader)
        path, imgs, targets = prefetcher.next()
        iteration = 0
        while imgs is not None:
            start_time_i = time.time()
            global_batch = len(dataloader) * epoch + batch_i
            imgs = Variable(imgs.to(device))
            targets = Variable(targets.to(device), requires_grad=False)
            if FLAGS_amp:
                with amp.scale_loss(loss, optimizer) as scaled_loss:
                    scaled_loss.backward()
                    if FLAGS_horovod:
                        optimizer.synchronize()
                if FLAGS_horovod:
                    with optimizer.skip_synchronize():
                        optimizer.step()
            else:
                loss.backward()
                optimizer.step()
            optimizer.zero_grad()`

**Comment by misslibra** [comment]
`if __name__ == "__main__":
    '''DDP SETTING '''
    torch.manual_seed(317)
    torch.cuda.manual_seed(317)
    if 'WORLD_SIZE' in os.environ:
        args.distributed = int(os.environ['WORLD_SIZE']) > 1
    if args.distributed and not FLAGS_horovod:
        torch.cuda.set_device(args_plus.local_rank)
        torch.distributed.init_process_group(backend='nccl', init_method='env://')
        args.world_size = torch.distributed.get_world_size()
    elif args.distributed and  FLAGS_horovod:
        hvd.init()
        torch.cuda.set_device(hvd.local_rank())
    assert torch.backends.cudnn.enabled, "Amp requires cudnn backend to be enabled."
    ''' Get dataloader'''
    dataset = ListDataset(train_path, class_names, augment=False, multiscale=args.multiscale_training)
    train_sampler = None
    if args.distributed and not FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
    elif args.distributed and FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset,
                                                                        num_replicas=hvd.size(), rank=hvd.rank())
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=(train_sampler is None),
        num_workers=args.n_cpu,
        pin_memory=True,
        sampler=train_sampler,
        collate_fn=dataset.collate_fn)
    ''' init  model'''
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = Darknet(args.model_def).to(device)
    if args.sync_bn and FLAGS_amp and args.distributed:
        print("using apex synced BN")
        model = apex.parallel.convert_syncbn_model(model)
    model = model.cuda()
    model.apply(weights_init_normal)
    if args.pretrian:
        if args.restore_path.endswith(".pth"):
            model.load_state_dict(torch.load(args.restore_path))
        else:
            model.load_darknet_weights(args.restore_path)
    optimizer = config_optimizer(model.parameters(), args.optimizer_name, args.learning_rate_init, args.momentum)
    if args.distributed and FLAGS_horovod:
        optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=model.named_parameters())
        hvd.broadcast_parameters(model.state_dict(), root_rank=0)
        hvd.broadcast_optimizer_state(optimizer,root_rank=0)

    if FLAGS_amp:
        amp.register_float_function(torch, 'sigmoid')
        model, optimizer = amp.initialize(model, optimizer,
                                        opt_level=args.opt_level,
                                        keep_batchnorm_fp32=args.keep_batchnorm_fp32,
                                        loss_scale=args.loss_scale
                                        )
    for epoch in range(args.total_epoches):
        if args.distributed:
            train_sampler.set_epoch(epoch)
        model.train()
        prefetcher = data_prefetcher(dataloader)
        path, imgs, targets = prefetcher.next()
        iteration = 0
        while imgs is not None:
            start_time_i = time.time()
            global_batch = len(dataloader) * epoch + batch_i
            imgs = Variable(imgs.to(device))
            targets = Variable(targets.to(device), requires_grad=False)
            if FLAGS_amp:
                with amp.scale_loss(loss, optimizer) as scaled_loss:
                    scaled_loss.backward()
                    if FLAGS_horovod:
                        optimizer.synchronize()
                if FLAGS_horovod:
                    with optimizer.skip_synchronize():
                        optimizer.step()
            else:
                loss.backward()
                optimizer.step()
            optimizer.zero_grad()`

**Comment by misslibra** [comment]
`#!usr/bin/python
#-*-coding:utf-8-*-

from __future__ import division

from models import *
from utils.utils import *
from utils.datasets import *

import os
import time
import argparse

import torch
from torch.utils.data import DataLoader
from torch.autograd import Variable
import args
import logging
import torch.backends.cudnn as cudnn
import torch.distributed as dist
import torch.utils.data.distributed
FLAGS_amp = args.FLAGS_amp
FLAGS_apex_DDP = args.FLAGS_apex_DDP
if FLAGS_amp:
    try:
        import apex
        from apex.parallel import DistributedDataParallel as DDP
        from apex.fp16_utils import *
        from apex import amp, optimizers
        from apex.multi_tensor_apply import multi_tensor_applier
    except ImportError:
        raise ImportError("Please install apex from https://www.github.com/nvidia/apex.")

FLAGS_horovod = args.FLAGS_horovod
if FLAGS_horovod:
    try:
        import horovod.torch as hvd
    except ImportError:
        raise ImportError("Please install horovod from https://github.com/horovod/horovod#install.")

os.environ['KMP_WARNINGS'] = 'off'

if args.distributed:
    torch.backends.cudnn.benchmark = True

parser = argparse.ArgumentParser()
parser.add_argument("--local_rank", default=0, type=int)
args_plus = parser.parse_args()

if __name__ == "__main__":
    '''DDP SETTING '''
    torch.manual_seed(317)
    torch.cuda.manual_seed(317)
    if 'WORLD_SIZE' in os.environ:
        args.distributed = int(os.environ['WORLD_SIZE']) > 1
    if args.distributed and not FLAGS_horovod:
        torch.cuda.set_device(args_plus.local_rank)
        torch.distributed.init_process_group(backend='nccl', init_method='env://')
        args.world_size = torch.distributed.get_world_size()
    elif args.distributed and  FLAGS_horovod:
        hvd.init()
        torch.cuda.set_device(hvd.local_rank())
    assert torch.backends.cudnn.enabled, "Amp requires cudnn backend to be enabled."
    ''' Get dataloader'''
    dataset = ListDataset(train_path, class_names, augment=False, multiscale=args.multiscale_training)
    train_sampler = None
    if args.distributed and not FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
    elif args.distributed and FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset,
                                                                        num_replicas=hvd.size(), rank=hvd.rank())
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=(train_sampler is None),
        num_workers=args.n_cpu,
        pin_memory=True,
        sampler=train_sampler,
        collate_fn=dataset.collate_fn)
    ''' init  model'''
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = Darknet(args.model_def).to(device)
    if args.sync_bn and FLAGS_amp and args.distributed:
        print("using apex synced BN")
        model = apex.parallel.convert_syncbn_model(model)
    model = model.cuda()
    model.apply(weights_init_normal)
    if args.pretrian:
        if args.restore_path.endswith(".pth"):
            model.load_state_dict(torch.load(args.restore_path))
        else:
            model.load_darknet_weights(args.restore_path)
    optimizer = config_optimizer(model.parameters(), args.optimizer_name, args.learning_rate_init, args.momentum)
    if args.distributed and FLAGS_horovod:
        optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=model.named_parameters())
        hvd.broadcast_parameters(model.state_dict(), root_rank=0)
        hvd.broadcast_optimizer_state(optimizer,root_rank=0)

    if FLAGS_amp:
        amp.register_float_function(torch, 'sigmoid')
        model, optimizer = amp.initialize(model, optimizer,
                                        opt_level=args.opt_level,
                                        keep_batchnorm_fp32=args.keep_batchnorm_fp32,
                                        loss_scale=args.loss_scale
                                        )
    for epoch in range(args.total_epoches):
        if args.distributed:
            train_sampler.set_epoch(epoch)
        model.train()
        prefetcher = data_prefetcher(dataloader)
        path, imgs, targets = prefetcher.next()
        iteration = 0
        while imgs is not None:
            start_time_i = time.time()
            global_batch = len(dataloader) * epoch + batch_i
            imgs = Variable(imgs.to(device))
            targets = Variable(targets.to(device), requires_grad=False)
            if FLAGS_amp:
                with amp.scale_loss(loss, optimizer) as scaled_loss:
                    scaled_loss.backward()
                    if FLAGS_horovod:
                        optimizer.synchronize()
                if FLAGS_horovod:
                    with optimizer.skip_synchronize():
                        optimizer.step()
            else:
                loss.backward()
                optimizer.step()
            optimizer.zero_grad()
`

**Comment by misslibra** [comment]
`if __name__ == "__main__":
    '''DDP SETTING '''
    torch.manual_seed(317)
    torch.cuda.manual_seed(317)
    if 'WORLD_SIZE' in os.environ:
        args.distributed = int(os.environ['WORLD_SIZE']) > 1
    if args.distributed and not FLAGS_horovod:
        torch.cuda.set_device(args_plus.local_rank)
        torch.distributed.init_process_group(backend='nccl', init_method='env://')
        args.world_size = torch.distributed.get_world_size()
    elif args.distributed and  FLAGS_horovod:
        hvd.init()
        torch.cuda.set_device(hvd.local_rank())
    assert torch.backends.cudnn.enabled, "Amp requires cudnn backend to be enabled."
    ''' Get dataloader'''
    dataset = ListDataset(train_path, class_names, augment=False, multiscale=args.multiscale_training)
    train_sampler = None
    if args.distributed and not FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
    elif args.distributed and FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset,
                                                                        num_replicas=hvd.size(), rank=hvd.rank())
`

**Comment by misslibra** [comment]
`if __name__ == "__main__":
    '''DDP SETTING '''
    torch.manual_seed(317)
    torch.cuda.manual_seed(317)
    if 'WORLD_SIZE' in os.environ:
        args.distributed = int(os.environ['WORLD_SIZE']) > 1
    if args.distributed and not FLAGS_horovod:
        torch.cuda.set_device(args_plus.local_rank)
        torch.distributed.init_process_group(backend='nccl', init_method='env://')
        args.world_size = torch.distributed.get_world_size()
    elif args.distributed and  FLAGS_horovod:
        hvd.init()
        torch.cuda.set_device(hvd.local_rank())
    assert torch.backends.cudnn.enabled, "Amp requires cudnn backend to be enabled."
    ''' Get dataloader'''
    dataset = ListDataset(train_path, class_names, augment=False, multiscale=args.multiscale_training)
    train_sampler = None
    if args.distributed and not FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
    elif args.distributed and FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset,
                                                                        num_replicas=hvd.size(), rank=hvd.rank())`

**Comment by misslibra** [comment]
`    if FLAGS_amp:
        amp.register_float_function(torch, 'sigmoid')
        model, optimizer = amp.initialize(model, optimizer,
                                        opt_level=args.opt_level,
                                        keep_batchnorm_fp32=args.keep_batchnorm_fp32,
                                        loss_scale=args.loss_scale
                                        )
    for epoch in range(args.total_epoches):
        if args.distributed:
            train_sampler.set_epoch(epoch)
        model.train()
        prefetcher = data_prefetcher(dataloader)
        path, imgs, targets = prefetcher.next()
        iteration = 0
        while imgs is not None:
            start_time_i = time.time()
            global_batch = len(dataloader) * epoch + batch_i
            imgs = Variable(imgs.to(device))
            targets = Variable(targets.to(device), requires_grad=False)
            if FLAGS_amp:
                with amp.scale_loss(loss, optimizer) as scaled_loss:
                    scaled_loss.backward()
                    if FLAGS_horovod:
                        optimizer.synchronize()
                if FLAGS_horovod:
                    with optimizer.skip_synchronize():
                        optimizer.step()
            else:
                loss.backward()
                optimizer.step()
            optimizer.zero_grad()`

**Comment by misslibra** [comment]
`#!usr/bin/python
#-*-coding:utf-8-*-

from __future__ import division

from models import *
from utils.utils import *
from utils.datasets import *

import os
import time
import argparse

import torch
from torch.utils.data import DataLoader
from torch.autograd import Variable
import args
import logging
import torch.backends.cudnn as cudnn
import torch.distributed as dist
import torch.utils.data.distributed
FLAGS_amp = args.FLAGS_amp
FLAGS_apex_DDP = args.FLAGS_apex_DDP
if FLAGS_amp:
    try:
        import apex
        from apex.parallel import DistributedDataParallel as DDP
        from apex.fp16_utils import *
        from apex import amp, optimizers
        from apex.multi_tensor_apply import multi_tensor_applier
    except ImportError:
        raise ImportError("Please install apex from https://www.github.com/nvidia/apex.")

FLAGS_horovod = args.FLAGS_horovod
if FLAGS_horovod:
    try:
        import horovod.torch as hvd
    except ImportError:
        raise ImportError("Please install horovod from https://github.com/horovod/horovod#install.")

os.environ['KMP_WARNINGS'] = 'off'

if args.distributed:
    torch.backends.cudnn.benchmark = True

parser = argparse.ArgumentParser()
parser.add_argument("--local_rank", default=0, type=int)
args_plus = parser.parse_args()

if __name__ == "__main__":
    '''DDP SETTING '''
    torch.manual_seed(317)
    torch.cuda.manual_seed(317)
    if 'WORLD_SIZE' in os.environ:
        args.distributed = int(os.environ['WORLD_SIZE']) > 1
    if args.distributed and not FLAGS_horovod:
        torch.cuda.set_device(args_plus.local_rank)
        torch.distributed.init_process_group(backend='nccl', init_method='env://')
        args.world_size = torch.distributed.get_world_size()
    elif args.distributed and  FLAGS_horovod:
        hvd.init()
        torch.cuda.set_device(hvd.local_rank())
    assert torch.backends.cudnn.enabled, "Amp requires cudnn backend to be enabled."
    ''' Get dataloader'''
    dataset = ListDataset(train_path, class_names, augment=False, multiscale=args.multiscale_training)
    train_sampler = None
    if args.distributed and not FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset)
    elif args.distributed and FLAGS_horovod:
        train_sampler = torch.utils.data.distributed.DistributedSampler(dataset,
                                                                        num_replicas=hvd.size(), rank=hvd.rank())
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=(train_sampler is None),
        num_workers=args.n_cpu,
        pin_memory=True,
        sampler=train_sampler,
        collate_fn=dataset.collate_fn)
    ''' init  model'''
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = Darknet(args.model_def).to(device)
    if args.sync_bn and FLAGS_amp and args.distributed:
        print("using apex synced BN")
        model = apex.parallel.convert_syncbn_model(model)
    model = model.cuda()
    model.apply(weights_init_normal)
    if args.pretrian:
        if args.restore_path.endswith(".pth"):
            model.load_state_dict(torch.load(args.restore_path))
        else:
            model.load_darknet_weights(args.restore_path)
    optimizer = config_optimizer(model.parameters(), args.optimizer_name, args.learning_rate_init, args.momentum)
    if args.distributed and FLAGS_horovod:
        optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=model.named_parameters())
        hvd.broadcast_parameters(model.state_dict(), root_rank=0)
        hvd.broadcast_optimizer_state(optimizer,root_rank=0)
    if FLAGS_amp:
        amp.register_float_function(torch, 'sigmoid')
        model, optimizer = amp.initialize(model, optimizer,
                                        opt_level=args.opt_level,
                                        keep_batchnorm_fp32=args.keep_batchnorm_fp32,
                                        loss_scale=args.loss_scale
                                        )
    for epoch in range(args.total_epoches):
        if args.distributed:
            train_sampler.set_epoch(epoch)
        model.train()
        prefetcher = data_prefetcher(dataloader)
        path, imgs, targets = prefetcher.next()
        iteration = 0
        while imgs is not None:
            start_time_i = time.time()
            global_batch = len(dataloader) * epoch + batch_i
            imgs = Variable(imgs.to(device))
            targets = Variable(targets.to(device), requires_grad=False)
            if FLAGS_amp:
                with amp.scale_loss(loss, optimizer) as scaled_loss:
                    scaled_loss.backward()
                    if FLAGS_horovod:
                        optimizer.synchronize()
                if FLAGS_horovod:
                    with optimizer.skip_synchronize():
                        optimizer.step()
            else:
                loss.backward()
                optimizer.step()
            optimizer.zero_grad()
`

**Comment by misslibra** [comment]
>            optimizer.synchronize() ## this takes a lot of time
>            with optimizer.skip_synchronize():
>                optimizer.step()

**Comment by misslibra** [comment]
`
optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=model.named_parameters(),
                                                        compression=compression,
                                                         backward_passes_per_step=50
                                                              )
`
I set backward_passes_per_step=50, Does it mean very 50 batches, do once all_reduce and data transfer between multi nodes ?
but why each batch( batch size is 24 ) still take 4 seconds?

**Comment by misslibra** [comment]
@alsrgv @mcarilli
hi ~~ Could you please help me with the problem that how I can control data transfer frequency between nodes?
I find each batch ,data transfer cost too much time ,so I want to do local training for every 50 batch,and then transfer data to do all reduce once.

**Comment by tgaddair** [comment]
Hey @misslibra, yes, `backward_passes_per_step` is what you'd want to use to reduce communication between workers.  We have an example in [pytorch_imagenet_resnet50.py](https://github.com/horovod/horovod/blob/master/examples/pytorch_imagenet_resnet50.py) that shows how it can be used in practice.  The key to getting better performance is that you only want to call `optimizer.step()` every `backward_passes_per_step` steps, as shown here:

https://github.com/horovod/horovod/blob/master/examples/pytorch_imagenet_resnet50.py#L196

**Comment by misslibra** [comment]
hi @tgaddair  Thanks for your reply!
I followed the example,and change my optimizer.step() from this guide:
[https://github.com/horovod/horovod/blob/master/docs/pytorch.rst](url)
 do  optimizer.step()  for every  batch  to be 'pytorch_imagenet_resnet50.py ' way ,that is every epoch do one step() .In this way ,every batch time is cut down .
But it crash 
`File "/home/l4/anaconda3/envs/py37/lib/python3.7/site-packages/horovod/torch/__init__.py", line 132, in hook
[1,1]<stderr>:    "Gradients were computed more than "
[1,1]<stderr>:AssertionError: Gradients were computed more than backward_passes_per_step times before call to step(). Increase backward_passes_per_step to accumulate gradients locally.`

Go into this source code:
`_register_hooks(self):` has for loop ,so that in `_make_hook(self, p) `  do  `self._allreduce_delay[p] -= 1` every time,
and  it will always hit the error 
`    if self._allreduce_delay[p] <= 0:
                    raise AssertionError("Gradients were computed more than "
                        "backward_passes_per_step times before call "
                        "to step(). Increase backward_passes_per_step to "
                        "accumulate gradients locally.")`

and if do  ` optimizer.step()` every batch,no the error .
