### ISSUE TITLE
OpenMPI "slot" not available using horovodrun

### ISSUE THREAD

**Issue by jinamshah** [horovod/horovod#1591]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.4.0a0+bb0e46b
3. Horovod version: 0.18.2
4. MPI version: 4.0.2
5. CUDA version: 10.1
6. NCCL version: 2.4.8
7. Python version: 3.6
8. OS and version: Ubuntu 18.04
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I tried to run the pytorch_synthetic_benchmark and got the error shown in the picture.
Note:

- The architecture had 2 machines with 1 GPU each.
- Both the servers had the same openmpi version
- users on both the servers can ssh into each other without password
- command executed: `horovodrun -np 2 -H localhost:1 server2-ip:1 python pytorch_synthetic_benchmark.py`

@tgaddair for your reference!
![Screenshot from 2019-12-16 18-19-07](https://user-images.githubusercontent.com/40169508/70971548-410a5b80-20c7-11ea-9c02-051d6ed9e3cd.png)

**Comment by tgaddair** [comment]
Hey @jinamshah, looks like you put a space between the hosts in your `horovodrun` command.  This is likely what's causing the parsing error.  Can you try replacing the space with a command and running again, like so:

```
horovodrun -np 2 -H localhost:1,server2-ip:1 python pytorch_synthetic_benchmark.py
```

**Comment by jinamshah** [comment]
Thanks for this @tgaddair 
I cannot believe I made this mistake :man_facepalming: 
Anyway, after solving the above error, I got this error:

> orted: error while loading shared libraries: libopen-rte.so.40: cannot open shared object file: No such file or directory
ORTE was unable to reliably start one or more daemons.
This usually is caused by:
> * not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default
> * lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.
> * the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.
> *  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.
> * an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).


I have already added /usr/local/lib (the prefix for openmpi installation) to LD_LIBRARY_PATH and PATH variables in bash.bashrc

**Comment by tgaddair** [comment]
Hey @jinamshah, could you try some of the suggestions in #400.  Sounds like there may be some config differences between the two machines.

**Comment by jinamshah** [comment]
Hey @tgaddair I have tried the suggestions in #400 and they didn't seem to make any difference

**Comment by tgaddair** [comment]
Hey @jinamshah, sorry for the late response.  Have you tried looking for that file on each machine? Also, have you run `ldconfig` on each machine?

I would take a look at [this](https://askubuntu.com/questions/997681/mpirun-error-while-loading-shared-libraries-libopen-rte-so-12/997684) answer and try looking for installation differences between the hosts and reinstalling the missing package as necessary:

```
find /usr/lib -name *libopen-rte*
dpkg -S /usr/lib/libopen-rte.so.40
```

**Comment by jinamshah** [comment]
Hey, @tgaddair sorry for the late response.
I tried the above commands, and the packages were the same on both the machines.
