### ISSUE TITLE
pytorch1.0.0 + horovod 0.15.2  !=  pytorch1.1.0 + horovod 0.18.2

### ISSUE THREAD

**Issue by Fangyh09** [horovod/horovod#1593]
Hello,
these two different configurations gave different results. What are the possible reasons?
I used these two configurations to train a CNN.
configuration1:  pytorch1.0.0 + horovod 0.15.2, train the CNN successfully
configuration2:  pytorch1.1.0 + horovod 0.18.2, output NaN

---
**Environment:**
1. Framework: PyTorch
2. Framework version: 
3. Horovod version:
4. MPI version:
5. CUDA version: 9.0
6. NCCL version:
7. Python version: 
8. OS and version: ubuntu
9. GCC version:

**Comment by tgaddair** [comment]
Hey @Fangyh09, do you have a minimal reproducible example?  I am not aware of any changes in 0.18.2 that would causes NaNs like this.  Does the same issue occur with PyTorch 1.0.0 + Horovod 0.18.2?

**Comment by Fangyh09** [comment]
I am sorry that I  forgot to update it.
I tried PyTorch 1.2.0 + Horovod 0.18.2, and it is okay. So currently I think NaN is related to the version of PyTorch.
