### ISSUE TITLE
Module 'horovod' has no attribute 'keras', and can I use tf.keras for keras code?

### ISSUE THREAD

**Issue by hoangcuong2011** [horovod/horovod#1601]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): TensorFlow + Keras
2. Framework version: 1.15.0
3. Horovod version:0.18.2
4. MPI version: openmpi-4.0.2
5. CUDA version: 10.0
6. NCCL version: 2.5.6
7. Python version: 3.6
8. OS and version: Ubuntu
9. GCC version: 5.4.0 

Hello - I have two questions.

First, I install horovod succesfully. I can use horovod.tensorflow, but I cannot use horovod.keras. Why is it the case and how to fix it?

Second, by keras, can I implement with tf.keras as well? Or it is keras only? If I have tf.keras code, should I use horovod.tensorflow or horovod.keras?

I installed horovod by trying these commands (all of them are successful, I just tried all of them to see whether  it fixes the issue, but it does not):
```
HOROVOD_GPU_ALLREDUCE=NCCL  HOROVOD_NCCL_HOME=my_path pip install --no-cache-dir horovod
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1  HOROVOD_NCCL_HOME=my_path pip install --no-cache-dir horovod))
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_KERAS=1  HOROVOD_NCCL_HOME=my_path pip install --no-cache-dir horovod))
```

Thank you!

**Comment by tgaddair** [comment]
Hey @hoangcuong2011, how are you importing Horovod?  Have you tried running the example scripts first, and do they produce the same error?

We have examples for both [keras](https://github.com/horovod/horovod/blob/master/examples/keras_mnist.py) and [tf.keras](https://github.com/horovod/horovod/blob/master/examples/tensorflow_keras_mnist.py) you can try running.

Also, can you try running `horovodun --check-build` and share the results?  It will tell you if TensorFlow support has been successfully installed.  You do not need to compile Horovod specifically for Keras.

**Comment by hoangcuong2011** [comment]
@tgaddair: Sorry for late response as it takes sometimes to figure out. I confirmed it works now, and the tf.keras example is extremely useful for me.
I want to thanks for your help, and I will close the ticket.
