### ISSUE TITLE
Spack Installation of Horovod

### ISSUE THREAD

**Issue by coreyjadams** [horovod/horovod#1602]
Is there any plan to implement a spack (https://github.com/spack/spack) installation of horovod?  We over here at Argonne's leadership computing facility have been exploring spack as a way to manage our compiler/python/mpi/DL-framework dependency matrix, and horovod is an obvious missing piece.

We're still exploring the installation of the base DL frameworks for pytorch and TF, though working with the spack developers and making progress.  I know we'd be happy to collaborate on this and submit a pull request if you're willing to help us support spack for horovod.

Thoughts?

**Comment by tgaddair** [comment]
Hey @coreyjadams, thanks for proposing this.  There aren't any immediate plans on our end, but I'd be happy to meet to discuss this and figure out what it would take make it happen.  Let me know if that's something you all would be interested in.

**Comment by henrique** [comment]
you can probably close this issue
please see: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-horovod/package.py
