### ISSUE TITLE
Multi-node training seems to only happen on 2 of my 4 nodes

### ISSUE THREAD

**Issue by LaVieEstDure** [horovod/horovod#1610]
**Environment:**
1. Framework: pytorch
2. Framework version: 1.2.0
3. Horovod version: 0.18.2
4. MPI version: 4.0.1
5. CUDA version: 10.1
6. NCCL version: 2.2.13
7. Python version: 3.5.6
8. OS and version: Ubuntu 16.04
9. GCC version: 5.4

**Checklist:**
1. Did you search issues to find if somebody asked this question before? ✓
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? ✓
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? ✓
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? ✓

**Bug report:**
I am launching horovod with 4 nodes with
`horovodrun -np 4 -H localhost:1,host2:1,host3:1,host4:1 python model.py`. I see batches training but only my last 2 nodes are printing the training prints. With print statements, I've narrowed down that hvd.init() never finishes on my first 2 nodes but does on the last 2 (all nodes print things that happen before hvd.init()).

**Comment by tgaddair** [comment]
Hey @LaVieEstDure, does this also happen when you run our example scripts?  Can you try running with [pytorch_synthetic_benchmark.py](https://github.com/horovod/horovod/blob/master/examples/pytorch_synthetic_benchmark.py) and share the results?

**Comment by LaVieEstDure** [comment]
Error was somewhere in inconsistent MPI setup between nodes. Reinstalled MPI and horovod on all nodes with a script which fixed it.
