### ISSUE TITLE
Remove hvd.allreduce and val_sampler in pytorch_imagenet_resnet50.py, will it be equivalent to original setting?

### ISSUE THREAD

**Issue by Fangyh09** [horovod/horovod#1615]
Hello,
I am use horovod v0.15.2.
For codes in 
`https://github.com/horovod/horovod/blob/v0.15.2/examples/pytorch_imagenet_resnet50.py`,
I removed hvd.allreduce and val_sampler, will it be equivalent to original code? Thanks !

**Comment by tgaddair** [comment]
Hey @Fangyh09, yes, results should be nearly the same.  The major difference, of course, is that you will be computing the validation metrics on the entire dataset on every worker, instead of dividing that work between the different workers.

**Comment by Fangyh09** [comment]
Yes, I need to compute the validation metrics on the entire dataset on every worker.
Because I have many metrics, it will be a bit simpler to use the above trick instead of adding hvd.allreduce for each metrics.

**Comment by Fangyh09** [comment]
By the way, has version v0.18.2 improved accuracy comparing to v0.15.2?
Thanks !
