### ISSUE TITLE
Horovodrun stops unexpectedly without any notifications

### ISSUE THREAD

**Issue by hoangcuong2011** [horovod/horovod#1616]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow Keras
2. Framework version:  1.15.0
3. Horovod version: 0.18.2
4. MPI version: openmpi-4.0.2
5. CUDA version: 10.0
6. NCCL version: 2.5.6
7. Python version: 3.6
8. OS and version: Ubuntu
9. GCC version: 5.4.0

I run my abc python file as:
`horovodrun -np 4 -H localhost:4 python abc.py`

Just in case: my model is a seq2seq model. It has a large amount of parameters (80Million). The batch size for training the model is 50.

I runs successfully, but then exists for no reason sometimes later (iterations 240 of 2667 from the third epoch) (see picture - the program just exists)

![image](https://user-images.githubusercontent.com/8759715/71476995-46c81580-281a-11ea-9ddd-14c535fe2d20.png)

I would also highlight that there is no warning, error. It just stops without any thing. 
Also I run the code another time and got similar result. The only difference is that it stops somewhere in epoch 2, not epoch 3 as the above.

So I wonder whether it is a bug? Did you ever observe this before?

**Comment by tgaddair** [comment]
Hey @hoangcuong2011, I've not seen this behavior before.  Does this also happen if you run without `horovodrun`, or run with fewer processes?

The lack of any error message whatsoever implies that some other process is hard killing `horovodrun`.  If the worker processes were killed somehow, there would be an error message from MPI.

**Comment by hoangcuong2011** [comment]
@tgaddair: Thx for your reply. I think one of the possible reasons is that I set the steps_per_epoch wrongly. This is because If I do that properly (by dividing to hvd.size() as well) then I don't observe it happens. Modifying steps_per_epoch was the only thing I did if I recall correctly.

I will close this but when I know in details with more examples why it happens and how to fix that, I will reopen and let you know.
Thx.

**Comment by hoangcuong2011** [comment]
@tgaddair: Actually, I wanted to confirm that it happens again.
I have the same code, and I run it multiple times.
For the first time it runs OK. For the seconds it was killed around epoch 7. Because of this I reopen the issue, even though I don't know how to do next because the error seems mysterious.
So I will try runing without horovodrun, or run with fewer processes and let you know.

**Comment by hoangcuong2011** [comment]
@tgaddair: I have a Mac laptop, and I loggin GCP machines with the laptop. I run python with nohup command.
I noticed if I kept my mac access to the same session on GCP I run python all the time, I didn't have any of this problem. However, if I happened to exist the session for sometime the problem would happen at some points - horovod suddently stops unexpectedly.

Specially, It happened when turn off my laptop, or when I got some issues with the internet for a moment.
I don't think this is a bug with horovod, but rather a problem with the linux or MPI? I don't know. Any comments on this are more than appreciated. Meanwhile I will try to keep connecting to GCP machine all the time! :))

**Comment by hoangcuong2011** [comment]
I think I found a way to overcome this issue - instead of running with nohup, I can run horovod with & command. For instance:

horovodrun -np 8 -H localhost:8 python -u mycode.py > ./mylog_file 2>&1 &

With this I did not find the issue.
