### ISSUE TITLE
the communication method between GPUs in a node

### ISSUE THREAD

**Issue by VincentJing** [horovod/horovod#1623]
I want to know the communication method between GPUs in a node, p2p or others?

**Comment by tgaddair** [comment]
Hey @VincentJing, it will depend on your hardware setup and choice of underlying framework (NCCL, MPI, DDL, etc.).

If you're using NCCL, then you can take advantage of NVLinks (P2P) if your nodes are configured with them.  NVIDIA wrote a good [blog post](https://devblogs.nvidia.com/scaling-deep-learning-training-nccl/) about NCCL and NVLink that covers this in more detail.

**Comment by VincentJing** [comment]
hey @tgaddair  If I don't install the NCCL, it will communicate through MPI between the GPUs in a node ?

**Comment by Tron-x** [comment]
@tgaddair  hey, if we chose nccl , intra-node gpu communication, the default is PCI-CPU or PCI- switch?

**Comment by tgaddair** [comment]
Hey @VincentJing, yes MPI is the default if you do not have NCCL installed.

Hey @Tron-x, PCI-CPU vs PCI-switch will depend on how your nodes are configured.  I would talk with your hardware folks about that.
