### ISSUE TITLE
Horovodrun give me Permission denied (publickey,password) when using cpu dockerfile

### ISSUE THREAD

**Issue by mariamrahmaani** [horovod/horovod#1627]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) pytorch
2. Framework version:
3. Horovod version: 0.18.2
4. MPI version: 4.0.0
5. CUDA version:-
6. NCCL version:-
7. Python version: 3.6.8
8. OS and version: ubuntu 18.04
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
 I am using 2 cpu-based systems to run using docker and using the instruction provided for CPU docker.

I have set the password-less ssh. so Host1 and Host2 can ssh to each other without needing any password.

However when I run "ssh root@Host2" inside docker in Host1 it asks for password. so my question is do I need to set password-less ssh inside docker in Host1 and docker in Host2 as well? and if yes, how can I set that inside docker?

Right now when inside docker I run  "horovodrun -np 4 -H Host1:2,Host2:2 ..." then I get permission denied.
 Here is the log:

ssh not successful for host Host2:
Permission denied, please try again.
Permission denied, please try again.
root@Host2: Permission denied (publickey,password).

Thanks for any help you can provide.
-Mariam

**Comment by mariamrahmaani** [comment]
Any clue?

**Comment by tgaddair** [comment]
Hey @mariamrahmaani, the process you used for enabling passwordless-ssh from node1 to 2 can be replicated for ssh from node 2 to 1.

For a more general solution, we recommend taking a look at our docs for running [Horovod in Docker](https://horovod.readthedocs.io/en/latest/docker_include.html), which covers using a shared filesystem for common SSH keys.

**Comment by mariamrahmaani** [comment]
Thanks Travis for your reply. I enabled the passwordless-ssh from node 2 to 1 as well but still I see the same issue.
I think I don't completely understand your documents for running Horovod in multi machine Dockers.

This is what the document says:

host1$ nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest
root@c278c88dd552:/examples# horovodrun -np 16 -H host1:4,host2:4,host3:4,host4:4 -p 12345 python keras_mnist_advanced.py

I guess --network=host is added because you want to use the same networking config between host and container. when I run this command line I get something like this:

mariam@lin-haswell-01:~$ docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest
root@lin-haswell-01:~/examples#

this doesn't have container ID: (e.g. c278c88dd552) as it shows in your example. If I run this command without --network=host then I get:

mariam@lin-haswell-01:~$ docker run -it  -v /mnt/share/ssh:/root/.ssh horovod:latest
root@37e16c364896:~/examples#

 if the containerID is there in the prompt, then shouldn't the shared public key also contain that containerID in authorized_keys? Before running a container we don't know that containerID so it cannot be shared.

So I am a bit confused with the section that you provided for "Running on multiple machines".
Thanks for any explanation you can provide.
-Mariam

**Comment by mariamrahmaani** [comment]
PS. sorry I don't know how my command lines have crossed lines. I couldn't fix it.

**Comment by tgaddair** [comment]
Hey @mariamrahmaani, the container ID is not important for SSH.  When you run sshd within one of the containers, that service will be running on some port (in the examples, we use port `12345`).  So you're still just sshing into `lin-haswell-01`, `lin-haswell-02`, etc., but because you're using port `12345` instead of `22`, you'll ssh into the correct container.

Just make sure that the other workers are running the sshd service a shown in the example.

**Comment by alokprasad** [comment]
@tgaddair my remote machine dont have root user but another user "xyz" with same privilega but horovod run only tries to connect remove user with root@host instead of xyz@host.?
Is there setting in docker before running horovodrun where user can be specified.

**Comment by alokprasad** [comment]
it turned out , You need Docker pub key in the host it is running and all remote machine.Setting up docker environment was not clear.

**Comment by zhenhuahu** [comment]
> it turned out , You need Docker pub key in the host it is running and all remote machine.Setting up docker environment was not clear.

Hi, I ran into the same problem, too. The host and nodes no longer need a password to communicate. But we still got the "permission denied" problem. May I ask what you did to set the Docker pub key? Thanks.
