### ISSUE TITLE
Does horovod  support multiple sessions running in parallel?

### ISSUE THREAD

**Issue by NanYan1119** [horovod/horovod#1633]
I notice that when pushing the tensor into the tensor_queue, horovod uses node name to identify different allreduce op. But node name can be the same in different graphs or sessions in tensorflow. If so, does horovod support multiple graphs or sessions running in parallel? If supported, how to identify these nodes with the same name?

**Comment by tgaddair** [comment]
Hey @NanYan1119, yes you can run multiple sessions in parallel, but you need to ensure that tensor names do not conflict between the sessions.  One way to achieve that would be to use a name scope for each session.
