### ISSUE TITLE
Usage of MPI within Horovod

### ISSUE THREAD

**Issue by chandana1332** [horovod/horovod#1635]
Hello,

I'm trying to understand what is the need for MPI in Horovod. 

From reading through, I see that 
1. MPI is used for all collective communication operations in the absence of NCCL
2. MPI is used to reduce gradients across nodes

What are the other usages?
Is it used to negotiate all reduce, etc?

**Comment by tgaddair** [comment]
Hey @chandana1332, MPI is used to reduce gradients across nodes with hierarchical allreduce, but if you're not using that feature than NCCL will be used across nodes.

The primary purpose of MPI when using NCCL is to manage the control plane to determine which tensors need to be reduced at each step (negotiation).  Alternatively, you can also use Gloo for this.

**Comment by apeforest** [comment]
Thanks @tgaddair for answering. @chandana1332 Please let me know if this answers your question and feel free to reopen if more clarification is needed.
