### ISSUE TITLE
Installation issue - No such file or directory <bits/stdlib-bsearch.h>

### ISSUE THREAD

**Issue by amity137** [horovod/horovod#1640]
Hi, I am installing hvd for and for PyTorch I get this error. The final message is "Above error indicates that this PyTorch installation does not support CUDA." but from the compilation error it seems the problem is something else.

_cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    In file included from /home/adsbybing/anaconda3/lib/python3.7/site-packages/torch/lib/include/TH/THGeneral.h:9:0,
                     from /home/adsbybing/anaconda3/lib/python3.7/site-packages/torch/lib/include/THC/THCGeneral.h:4,
                     from /home/adsbybing/anaconda3/lib/python3.7/site-packages/torch/lib/include/THC/THC.h:4,
                     from build/temp.linux-x86_64-3.7/test_compile/test_torch_cuda.cc:1:
    /usr/include/stdlib.h:759:11: fatal error: bits/stdlib-bsearch.h: No such file or directory
     **# include <bits/stdlib-bsearch.h>**_

PATH, LD_LIBRARY_PATH and soft links are already there as per https://github.com/horovod/horovod/issues/383. What could be the issue? Thanks in advance.

**Comment by tgaddair** [comment]
Hey @amity137, can you verify that `bits/stdlib-bsearch.h` exists on your system?
