### ISSUE TITLE
DockerFile build NCCL is invalid

### ISSUE THREAD

**Issue by fengchaohao** [horovod/horovod#1647]
**Hello when I try to build the latest  Dockerfile(with Add NCCL Broadcast operation)  ,I meet the err**

  error: HOROVOD_GPU_BROADCAST=NCCL is invalid, supported values are "", "MPI".
  ----------------------------------------
  ERROR: Failed building wheel for horovod

I think the git was updated  but  PyPI was not updated, Please check the Dockerfile.gpu:

RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 \
         **pip install --no-cache-dir horovod** && \

**The PyPI version is 0.18.2 , it does not support NCCL. so i want to comfirm with you,if there is  a bug in you Dockerfile? Could you help me to solve the problem？I'm looking forward to your early reply. Thank you.**

**Comment by tgaddair** [comment]
Hey @fengchaohao, please take a look at Dockerfile.gpu for [v0.18.2](https://github.com/horovod/horovod/blob/v0.18.2/Dockerfile.gpu).  The master branch has changes for v0.19.0, which has not yet been released.
