### ISSUE TITLE
Run pytorch_mnist.py, got ValueError('Neither MPI nor Gloo support has been built. )

### ISSUE THREAD

**Issue by XueCangQiuYe** [horovod/horovod#1655]
**Environment:**
1. Framework: (TensorFlow,  PyTorch)
2. Framework version:1.14,1.12
3. Horovod version:0.18
4. MPI version:4.0.2
5. CUDA version:10.0
6. NCCL version:
7. Python version:3.6
8. OS and version:centos7
9. GCC version:4.9.4

 when i run pytorch_mnist.py (official example)
`[root@vm-gpu-2 horovod_pytorch]# horovodrun -np 2 -H ip1:1,ip2:1 python pytorch_mnist.py
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/run.py", line 736, in run
    raise ValueError('Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that '
ValueError: Neither MPI nor Gloo support has been built. Try reinstalling Horovod ensuring that either MPI is installed (MPI) or CMake is installed (Gloo).
`

I am sure I have installed openmpi 4.0.2
and also run this command:

`[root@vm-gpu-2 horovod_pytorch]# HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1  pip install --no-cache-dir horovod
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Requirement already satisfied: horovod in /usr/local/lib64/python3.6/site-packages
Requirement already satisfied: cffi>=1.4.0 in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from horovod)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.6/site-packages (from horovod)
Requirement already satisfied: psutil in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: pyyaml in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.4.0->horovod)
`

**Comment by lento234** [comment]
What's your output to:

`horovodrun --check-build`

**Comment by XueCangQiuYe** [comment]
@lento234 
thank you for your reply, I will try later and let you know the result

**Comment by brandon-biggs** [comment]
Did you do a `module load mpi` when you tried to install horovod? I ran into this issue because I forgot to load mpi when I started a new environment to install horovod.

**Comment by XueCangQiuYe** [comment]
> What's your output to:
> 
> `horovodrun --check-build`
i got this output 
`Horovod v0.18.2:

Available Frameworks:
    [ ] TensorFlow
    [ ] PyTorch
    [ ] MXNet

Available Controllers:
    [ ] MPI
    [ ] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] MLSL
    [ ] MPI
    [ ] Gloo `

What it means?

**Comment by XueCangQiuYe** [comment]
Hi, @brandon-biggs ,
You mean to do `model load mpi` after install openmpi?
How can I do `model load mpi`, or how to solve this problem? Uninstalled horovod ,then `model load mpi`, then install horovod?

**Comment by lento234** [comment]
> > What's your output to:
> > `horovodrun --check-build`
> > i got this output
> > `Horovod v0.18.2:
> 
> Available Frameworks:
> [ ] TensorFlow
> [ ] PyTorch
> [ ] MXNet
> 
> Available Controllers:
> [ ] MPI
> [ ] Gloo
> 
> Available Tensor Operations:
> [ ] NCCL
> [ ] DDL
> [ ] MLSL
> [ ] MPI
> [ ] Gloo `
> 
> What it means?

It means that the horovod installation wasn't properly linked with the MPI, GLOO, NCCL nor the python library for some reason. 

You can make sure the horovod sees links the library during the installation using the following flags:
```
HOROVOD_CUDA_HOME=</path/to/your/cuda> \
HOROVOD_CUDA_INCLUDE=</path/to/your/cuda/include> \
HOROVOD_CUDA_LIB=</path/to/your/cuda/include/lib> \ 
HOROVOD_NCCL_HOME=</path/to/your/NCCL> \ 
HOROVOD_NCCL_LIB=</path/to/your/NCCL/lib> \
HOROVOD_NCCL_INCLUDE=</path/to/your/NCCL/include> \
HOROVOD_GPU_ALLREDUCE=NCCL \
HOROVOD_WITH_PYTORCH=1 \
HOROVOD_WITH_TENSORFLOW=1 \
HOROVOD_WITH_MPI=1 \
HOROVOD_MPICXX_SHOW=$(mpicxx -show) \
pip install --no-cache-dir horovod
```

Try with the above command (you can skip NCCL if you don't want it) and check the horovod build again. If that doesn't work, perhaps you can try to install horovod+pytorch+tensorflow in a conda environment.

**Comment by XueCangQiuYe** [comment]
@lento234 thank you a lot, i give up installing horovod locally, i'm not good at linux, maybe docker pull the image is a good optation.....

**Comment by lento234** [comment]
@XueCangQiuYe You should omit the braces (< >). Also, perhaps install it to your user dir. Perhaps, you don't have the necessary privileges for install to system directory. Install to your user dir with the following flag `--user`.

```
HOROVOD_CUDA_HOME=/usr/local/cuda-10.0 \
HOROVOD_CUDA_INCLUDE=/usr/local/cuda-10.0/include \
HOROVOD_CUDA_LIB=/usr/local/cuda-10.0/lib64 \
HOROVOD_WITH_TENSORFLOW=1 \
HOROVOD_WITH_PYTORCH=1 \
HOROVOD_WITH_MPI=1 \
HOROVOD_MPICXX_SHOW=$(mpicxx -show) \
pip install --user --no-cache-dir horovod
```

**Comment by XueCangQiuYe** [comment]
@lento234 thanks, i will try it tomorrow.

today, i try run horovod docker in one machine with 1 gpu，and up 2 container，call a and b.
`docker run -it --name a --runtime=nvidia horovod
docker run -it --name b --runtime=nvidia horovod`
and got ipa, ipb
in container a, i run this command
`root@a:/examples# horovodrun -np 2-H ipa1:1,ipb:1 -p 12345 python keras_mnist_advanced.py`
but it not working properly.
so `docker rm -f a b`
and run the command below
`docker run -it --name a --runtime=nvidia --network=host -v /mnt/share/ssh:/root/.ssh horovod
docker run -it  --name b --runtime=nvidia --network=host -v /mnt/share/ssh:/root/.ssh horovod bash -c "/usr/sbin/sshd -p 12345; sleep infinity"`
in container a, i run this command
`root@a:/examples# horovodrun -np 2 -H ipa1:1,ipb:1 -p 12345 python keras_mnist_advanced.py`
but it also not working properly. it seem like, the container a and b can not ssh each other....
Frustrated day.

**Comment by lento234** [comment]
I would first try a simple setup and progressively increase the complexity:

- [ ] Inside docker or native without distributed computing (i.e. just `python pytorch_mnist.py`).
- [ ] Then with a distributed setup using MPI.
- [ ] Then multi-docker setup in a single machine.
- [ ] Multi-docker in multi-machine setup.

Good luck.

**Comment by XueCangQiuYe** [comment]
@lento234 , hi, i ran the command thart you provided.
the ouput is 
`
[root@vm-gpu-2 horovod_pytorch]# HOROVOD_CUDA_HOME=/usr/local/cuda-10.0 \
> HOROVOD_CUDA_INCLUDE=/usr/local/cuda-10.0/include \
> HOROVOD_CUDA_LIB=/usr/local/cuda-10.0/lib64 \
> HOROVOD_WITH_TENSORFLOW=1 \
> HOROVOD_WITH_PYTORCH=1 \
> HOROVOD_WITH_MPI=1 \
> HOROVOD_MPICXX_SHOW=$(mpicxx -show) \
> pip install --user --no-cache-dir horovod
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Requirement already satisfied: horovod in /usr/local/lib64/python3.6/site-packages
Requirement already satisfied: cffi>=1.4.0 in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: psutil in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: pyyaml in /usr/local/lib64/python3.6/site-packages (from horovod)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from horovod)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.6/site-packages (from horovod)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi>=1.4.0->horovod)
`
then, i ran the command in ip1 machine:
 `horovodrun -np 2 -H ip1:1,ip2:1 python pytorch_mnist.py`
but i got anohter error:
`[root@vm-gpu-1 horovod_pytorch]# horovodrun -np 2 -H 192.168.0.52:1,192.168.0.193:1 python pytorch_mnist.py
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/run.py", line 692, in run
    settings, fn_cache=fn_cache)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/util/cache.py", line 103, in wrap_f
    results = func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/run.py", line 229, in _driver_fn
    driver.wait_for_initial_registration(settings.timeout)
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/common/service/driver_service.py", line 117, in wait_for_initial_registration
    timeout.check_time_out_for('tasks to start')
  File "/usr/local/lib64/python3.6/site-packages/horovod/run/common/util/timeout.py", line 32, in check_time_out_for
    raise Exception(self._message.format(activity=activity))
Exception: Timed out waiting for tasks to start. Please check connectivity between servers. You may need to increase the --start-timeout parameter if you have too many servers.
`
the two machine can ssh each other without password,
why?

**Comment by lento234** [comment]
Can you try on a single node, single-core first? Maybe, it wasn't properly installed.
