### ISSUE TITLE
horovod multiple NCCL streams did not bring performance improvements

### ISSUE THREAD

**Issue by Richie-yan** [horovod/horovod#1658]
When I was profiling horovod, a long QUEUE time was displayed on the timeline. My understanding of QUEUE is: the time to wait for the nccl stream to end.
So I used HOROVOD_NUM_NCCL_STREAMS = 4 and found that the final training speed is almost the same as when HOROVOD_NUM_NCCL_STREAMS = 1, but there is almost no QUEUE on the timeline, so I am confused about this phenomenon.
I compared timeline information using one NCCL stream and multiple NCCL streams:
Although multiple NCCL streams are opened, there is almost no QUEUE time on the timeline, but the NCCL_ALLREDUCE time has increased relatively, which is almost equal to the QUEUE time + NCCL_ALLREDUCE time for opening one NCCL stream.
When there are many QUEUE times, adding NCCL streams and improving the overlap of computing and communication has not improved the performance?

**Comment by tgaddair** [comment]
Hey @Richie-yan, did @romerojosh's response in #1128 answer your question?

**Comment by Richie-yan** [comment]
Hey @tgaddair  Yes he answered my doubts and i will close the question
