### ISSUE TITLE
Models available for tensorflow2_synthetic_benchmark.py

### ISSUE THREAD

**Issue by ticlazau** [horovod/horovod#1659]
Hello,

for the https://github.com/horovod/horovod/blob/master/examples/tensorflow2_synthetic_benchmark.py

- it seems that using model ResNet152, VGG16, Alexnet etc is not working
- same for --fp16-allreduce option, has no effect on performance.

I am getting with TF 2.0. on single V100 GPU 342.4 img/sec for default values, has anyone used this synthetic benchmark?

Rgds,
Florin

**Comment by nvcastet** [comment]
Hi Florin,

What are the errors you are getting for those models? Could you paste the full console output?
For `--fp16-allreduce`, it is casting the gradients to 16bits to reduce the amount of communicated data (still using float32 computation), so you will see performance benefits only when the network is the bottleneck (unlikely on single box with NVLINK GPUs).

Regards,

Nicolas

**Comment by ticlazau** [comment]
Hi @nvcastet ,

I am running fine with default values, however if I want to change the model from ResNet50 to something else I am getting this error:
**RUN:**
horovodrun -np 1 -H localhost:1 python tensorflow2_synthetic_benchmark.py --model Alexnet
**Error:**
Process 0 exit with status code 1.
Traceback (most recent call last):
  File "/nobackup/users/florin/anaconda3/envs/wmlce-ea/bin/horovodrun", line 21, in <module>
    run.run()
  File "/nobackup/users/florin/anaconda3/envs/wmlce-ea/lib/python3.6/site-packages/horovod/run/run.py", line 734, in run
    gloo_run(settings, remote_host_names, common_intfs, env)
  File "/nobackup/users/florin/anaconda3/envs/wmlce-ea/lib/python3.6/site-packages/horovod/run/gloo_run.py", line 299, in gloo_run
    _launch_jobs(settings, env, host_alloc_plan, remote_host_names, run_command)
  File "/nobackup/users/florin/anaconda3/envs/wmlce-ea/lib/python3.6/site-packages/horovod/run/gloo_run.py", line 262, in _launch_jobs
    .format(name=name, code=exit_code))
RuntimeError: Gloo job detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 1

**Comment by ticlazau** [comment]
+3 more questions:
- what are the supported models?
- is mix precision used in TF?
- what is the used resolution?

**Comment by nvcastet** [comment]
So it is for 224x224 images. So you need to make sure the model takes the same input shape. I don't know what have been tested with this script? @tgaddair Do you know?
This script does not seem to use mix precision but TF supports it.
Is there other info before the gloo termination error you are getting?

**Comment by tgaddair** [comment]
Hey @ticlazau, to answer your questions:

- These are the available models: https://www.tensorflow.org/api_docs/python/tf/keras/applications#functions
- In our script, we only test fp16 compression during allreduce.  We do not benchmark using fp16 during the forward/backward passes.
- As @nvcastet said, the images are 224x224 with 3 channels.
