### ISSUE TITLE
fail to install horovod

### ISSUE THREAD

**Issue by rudvlf0413** [horovod/horovod#1662]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.3
3. Horovod version: 18.2
4. MPI version: 4.0.2
5. CUDA version: 10.0
6. NCCL version: 2.4.8
7. Python version: python 3.7
8. OS and version: ubuntu 18.04
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? yes

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

When I tried to install horovod using following commands,
export LD_LIBRARY_PATH="/home/rudvlf0413/nccl_2.4.8/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="/home/rudvlf0413/openmpi/lib:$LD_LIBRARY_PATH"
export PATH="/home/rudvl0413/openmpi/bin:$PATH"

HOROVOD_NCCL_HOME=/home/rudvlf0413/nccl-2.4.8 HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL pip install --no-cache-dir horovod

and I got errors like below:

Running setup.py clean for horovod
Failed to build horovod
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    ERROR: Command errored out with exit status 1:
     command: /home/rudvlf0413/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5xfw07v5/horovod/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5xfw07v5/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xr6p0xle/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-5xfw07v5/horovod/
    Complete output (86 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.7/horovod
    creating build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/basics.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/util.py -> build/lib.linux-x86_64-3.7/horovod/common
    creating build/lib.linux-x86_64-3.7/horovod/spark
    copying horovod/spark/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark
    creating build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/compression.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/torch
    creating build/lib.linux-x86_64-3.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/keras
    creating build/lib.linux-x86_64-3.7/horovod/mxnet
    copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-3.7/horovod/mxnet
    copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/mxnet
    creating build/lib.linux-x86_64-3.7/horovod/_keras
    copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/_keras
    copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/_keras
    creating build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    creating build/lib.linux-x86_64-3.7/horovod/run
    copying horovod/run/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run
    copying horovod/run/run.py -> build/lib.linux-x86_64-3.7/horovod/run
    copying horovod/run/task_fn.py -> build/lib.linux-x86_64-3.7/horovod/run
    creating build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    creating build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    creating build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    creating build/lib.linux-x86_64-3.7/horovod/run/common
    copying horovod/run/common/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/common
    creating build/lib.linux-x86_64-3.7/horovod/run/util
    copying horovod/run/util/cache.py -> build/lib.linux-x86_64-3.7/horovod/run/util
    copying horovod/run/util/threads.py -> build/lib.linux-x86_64-3.7/horovod/run/util
    copying horovod/run/util/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/util
    copying horovod/run/util/network.py -> build/lib.linux-x86_64-3.7/horovod/run/util
    creating build/lib.linux-x86_64-3.7/horovod/run/driver
    copying horovod/run/driver/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/run/driver
    copying horovod/run/driver/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/driver
    creating build/lib.linux-x86_64-3.7/horovod/run/task
    copying horovod/run/task/task_service.py -> build/lib.linux-x86_64-3.7/horovod/run/task
    copying horovod/run/task/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/task
    creating build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/host_hash.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/timeout.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/secret.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/settings.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/env.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/codec.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/network.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    creating build/lib.linux-x86_64-3.7/horovod/run/common/service
    copying horovod/run/common/service/task_service.py -> build/lib.linux-x86_64-3.7/horovod/run/common/service
    copying horovod/run/common/service/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/run/common/service
    copying horovod/run/common/service/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/common/service
    running build_ext
    /home/rudvlf0413/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/rudvlf0413/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/rudvlf0413/anaconda3/include -fPIC -std=c++11 -fPIC -O2 -Wall -I/home/rudvlf0413/anaconda3/include/python3.7m -c build/temp.linux-x86_64-3.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.7/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-conda_cos6-linux-gnu-gcc -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/rudvlf0413/anaconda3/lib -L/home/rudvlf0413/anaconda3/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/rudvlf0413/anaconda3/lib -L/home/rudvlf0413/anaconda3/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/rudvlf0413/anaconda3/lib -Wl,-rpath-link,/home/rudvlf0413/anaconda3/lib -L/home/rudvlf0413/anaconda3/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/rudvlf0413/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/rudvlf0413/anaconda3/include build/temp.linux-x86_64-3.7/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.7/test_compile/test_cpp_flags.so
    /home/rudvlf0413/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/rudvlf0413/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/rudvlf0413/anaconda3/include -fPIC -I/home/rudvlf0413/anaconda3/include/python3.7m -c build/temp.linux-x86_64-3.7/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.7/test_compile/test_link_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-conda_cos6-linux-gnu-gcc -pthread -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/rudvlf0413/anaconda3/lib -L/home/rudvlf0413/anaconda3/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/rudvlf0413/anaconda3/lib -L/home/rudvlf0413/anaconda3/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/rudvlf0413/anaconda3/lib -Wl,-rpath-link,/home/rudvlf0413/anaconda3/lib -L/home/rudvlf0413/anaconda3/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/rudvlf0413/anaconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/rudvlf0413/anaconda3/include -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.7/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.7/test_compile/test_link_flags.so
    error: HOROVOD_GPU_BROADCAST=NCCL is invalid, supported values are "", "MPI".
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/rudvlf0413/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5xfw07v5/horovod/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5xfw07v5/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xr6p0xle/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

I think horovod couldn't detect nccl or openmpi.
Do you know how to solve this problem?

Thank you.

**Comment by kit1980** [comment]
Support for `HOROVOD_GPU_BROADCAST=NCCL` added just a few days ago, you need to build from master to use it. Are you sure you really need this parameter?

**Comment by tgaddair** [comment]
Hey @rudvlf0413, as @kit1980 said this feature was just added.  Horovod v0.19.0 was released yesterday, so if you try again it should work.

**Comment by rudvlf0413** [comment]
@kit1980 @tgaddair Thank you for answering my question.

After reinstalling Horovod and trying to load the library, I got an error as

import horovod.torch as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/horovod/torch/__init__.py", line 39, in <module>
    from horovod.torch.mpi_ops import allreduce, allreduce_async, allreduce_, allreduce_async_
  File "/home/rudvlf0413/anaconda3/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 31, in <module>
    from horovod.torch import mpi_lib_v2 as mpi_lib
ImportError: /home/rudvlf0413/anaconda3/lib/python3.7/site-packages/horovod/torch/mpi_lib_v2.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

**Comment by rudvlf0413** [comment]
I reinstall the openmpi, and I fix the bug I got the error.

Thank you.
