### ISSUE TITLE
Migrating from (non-distributed)TensorFlow to Horovod

### ISSUE THREAD

**Issue by saurabh-jogalekar** [horovod/horovod#1664]
I am new to the distributed ML paradigm and I have a few TF scripts written for, let's say, a "non-distributed" mode. Now, I need to migrate these scripts to a Horovod environment. Is there any way I can automate this migration? Surely, I shall try and understand the MPI concepts and run through examples but was curious to know if there was a package/library that did this?

**Comment by tgaddair** [comment]
Hey @saurabh-jogalekar, we do not have an automated script.  We've toyed with the idea before, but for any but the most simple cases it could potentially break something.  That said, the modifications are usually pretty minimal, and we have a tutorial [here](https://github.com/horovod/tutorials/tree/master/fashion_mnist) that walks you through everything you need to change in your script (about 5 lines of code).

**Comment by saurabh-jogalekar** [comment]
@tgaddair Thanks a lot!
