### ISSUE TITLE
Training speed is more and more slow on 8 Tesla V100 GPUs !

### ISSUE THREAD

**Issue by yguo33** [horovod/horovod#1672]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.14
3. Horovod version: 0.18.1
4. MPI version: 4.00
5. CUDA version: 10.1
6. NCCL version: 2.3.4
7. Python version: 3.6
8. OS and version: centos7
9. GCC version: 4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I trained bert model on multi gpu three times, the training speed is more and more slow. Training processes are as forllows:

![截屏2020-01-15下午7 41 12](https://user-images.githubusercontent.com/11401434/72431774-90c86980-37d0-11ea-8e91-20b675592aba.png)
![截屏2020-01-15下午7 37 53](https://user-images.githubusercontent.com/11401434/72431786-958d1d80-37d0-11ea-9e05-5d0d819f6f2f.png)
![截屏2020-01-15下午7 36 44](https://user-images.githubusercontent.com/11401434/72431790-9a51d180-37d0-11ea-844f-0631d497ebd8.png)
<img width="1661" alt="截屏2020-01-15下午7 42 42" src="https://user-images.githubusercontent.com/11401434/72431814-a89fed80-37d0-11ea-9fa9-591c75f16d43.png">

**The timeline image is the last training, the training speed is only 1/10 of first time, I don't know why.** 

**Training Script:**
horovodrun -np 8 -H localhost:8 python run_classifier.py ...

**Comment by tgaddair** [comment]
Hey @yguo33, can you run `horovodrun --check-build` verify that everything is properly installed?  Also, can you clarify your training setup.  Was there an existing script for Horovod on BERT you used, or did you make modifications to a script yourself?

**Comment by yguo33** [comment]
> Hey @yguo33, can you run `horovodrun --check-build` verify that everything is properly installed? Also, can you clarify your training setup. Was there an existing script for Horovod on BERT you used, or did you make modifications to a script yourself?



Thank you for your response. I did modifications to bert script and and the training is successful, you can check the first image, and the training speed is very quick. But when I retrain the model, it became more and more slow, I don't know why. 'nvidia-smi' shows normally, 8 Gpus are using, 'Volatile GPU-Util' almost 100%.

Here is the `horovodrun --check-build` shows:
`Available Frameworks:
    [X] TensorFlow
    [X] PyTorch
    [X] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] MLSL
    [X] MPI
    [X] Gloo`
