### ISSUE TITLE
ModuleNotFoundError: No module named 'horovod.torch'; 'horovod' is not a package

### ISSUE THREAD

**Issue by vainaijr** [horovod/horovod#1674]
horovod installed but when I
```
import horovod.torch as hvd
```
then it throws error

**Comment by tgaddair** [comment]
Hey @vainaijr, can you share the error?

Likely Horovod installed correctly for one of the frameworks (e.g., TensorFlow), but failed to install with PyTorch.  To force Horovod to fail if it can't install with PyTorch, run with `... HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir horovod`.
