### ISSUE TITLE
Horovodrun can't run when translating to mpirun because of '-H'

### ISSUE THREAD

**Issue by brandon-biggs** [horovod/horovod#1677]
**Environment:**
1. Framework: (**TensorFlow**)
2. Framework version: 2.0 GPU
3. Horovod version: 0.19.0
4. MPI version: 1.10.7
5. CUDA version: 10.2
6. NCCL version: 2.5.6
7. Python version: 3.7
8. OS and version: Centos 7.7
9. GCC version: 4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before? I looked for it, couldn't find it.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Not about hang
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Not about docker
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Not in the guide

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

When running `horovodrun` from the terminal, you can pass a hostfile with, `-hostfile/--hostfile`. If you use `--verbose`, you can see the equivalent Open MPI command. I noticed that horovodrun converts the `--hostfile` to -H for hosts. This isn't an exact conversion from `horovodrun` to `mpirun`, and for some reason is causing issues in my environment.

I installed openmpi with yum. There's some kind of weird bug that I haven't fully figured out yet where specifying just the host with -H causes the `ORTE was unable to reliably start one or more daemons.` error, but `--hostfile` does not cause this issue. However, because `horovodrun` translates both `--hostfiles` and `-H` to `mpirun -H, horovodrun` will not work. Because I installed openmpi from yum and didn't make any changes, I thought this may be an important bug to note for others who may also run into this issue. 

Example from the [documentation](https://horovod.readthedocs.io/en/latest/mpirun.html): 
`horovodrun -np 16 -H server1:4,server2:4,server3:4,server4:4 python train.py`
Equivalent:
```
mpirun -np 16 \
    -H server1:4,server2:4,server3:4,server4:4 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python train.py
```
However,
`horovodrun -np 16 --hostfile hostfile python train.py`
is not equivalent to:
```
mpirun -np 16 \
    --hostfile hostfile \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python train.py
```
but is equivalent to the original, which in my case, causes problems, not sure why. 
```
mpirun -np 16 \
    -H server1:4,server2:4,server3:4,server4:4 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python train.py
```

I'm recompiling mpi. Hopefully that will resolve my issues, but I wanted to bring this to everyone's attention. Let me know if there are any questions about this report. This may definitely be by design, or maybe there's an easy workaround that I'm just not aware of.

**Comment by tgaddair** [comment]
Hey @brandon-biggs, were you able to resolve the issue by recompiling MPI?  I agree that the behavior is not identical to running `mpirun --hostfile, but I'm hesitant to add more complexity to the code by changing the behavior without understanding where the difference in behavior is coming from.  @nvcastet or @romerojosh, are you familiar enough with the underlying workings of MPI to know if there's a behavior difference between `-H` and `--hostfile`?

**Comment by nvcastet** [comment]
@tgaddair @brandon-biggs In the past, I have seen different behavior between `-H` and `--rankfile` and saw that Open MPI had a separate logic for both code paths. I would not be surprise if for legacy reason, there is also a different behavior with `--hostfile` in same cases.
@brandon-biggs We could probably call `--hostfile` with horovodrun but it would be nice if you could share with us a specific behavior issue you had by having the translation from `--hostfile` to `-H`?
On the other hand, it is nice to have a consistent behavior between `--hostfile` and `-H` because it is what the user intuitively expects if it does not know the details of MPI.

**Comment by brandon-biggs** [comment]
@tgaddair No, recompiling MPI didn't seem to resolve my issue. I understand the complexity issue. I wasn't really looking for you to solve my issue here, I just wanted to make everyone aware of this issue that I was running into. Maybe someone will stumble upon this in the future.

@nvcastet `-H` doesn't work. I'm not sure why. Something to do with this version of openmpi, or a mix with Centos7 + openmpi, I really don't know. So I have to use `--hostfile` which means I can't use horovodrun as intended.

**Comment by nvcastet** [comment]
@brandon-biggs I tried to google "behavior differences between --hostfile and -H MPI" but did not get anything. If you are interested in pursuing this mystery, it would be nice to get more info from the MPI guys by opening an issue at: https://github.com/open-mpi/ompi/issues (assuming you are using OpenMPI).

**Comment by brandon-biggs** [comment]
@nvcastet It really was a weird issue. Doesn't really matter to me. I installed a different version from source and it's fine now, assuming I use horovodrun with that new openmpi loaded of course :)

Really just wanted to make a note of it in case someone else ran into this issue as this stumped me for quite some time while I was trying to get horovodrun to work in my environment, especially since it happened with the default `yum install openmpi-devel` package.

**Comment by nvcastet** [comment]
@brandon-biggs Just for reference, which version of OpenMPI pulled by `yum install openmpi-devel` did not work and which one did work (built from source)?

**Comment by brandon-biggs** [comment]
`yum install openmpi-devel` installed - 
```
$ mpiCC --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
```

From source, looks like the same version, but with different configure flags. 
```
$ mpiCC --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
```
The config flags - `./configure --prefix=./openmpi/openmpi-4.0.2/ --with-tm=/opt/pbs/ --enable-mpirun-prefix-by-default`

**Comment by nvcastet** [comment]
@brandon-biggs That is the GCC version. To get the MPI version, run `mpirun --version`.

**Comment by brandon-biggs** [comment]
That's embarrassing. Both are 4.0.2

**Comment by nvcastet** [comment]
@brandon-biggs No problem. Just curious, can you try the default MPI with `horovodrun -np 16 --hostfile hostfile --mpi-args="--prefix <full_path>" python train.py` with `full_path` being the absolute path of your MPI folder e.g. `/opt/openmpi/openmpi-4.0.2/`?

**Comment by brandon-biggs** [comment]
@nvcastet 
```
ssh: Could not resolve hostname localhost:4: Name or service not known
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
```

**Comment by nvcastet** [comment]
@brandon-biggs Ok i found the issue: https://www.mail-archive.com/devel@lists.open-mpi.org/msg18505.html
In version `1.10`, specifying the number of slots on the command line with `-H` is not supported, so it considers the `:4` as part of the hostname.

**Comment by tgaddair** [comment]
Nice find @nvcastet!  I think a sufficient solution to this issue is to note in our docs that `horovodrun` with Open MPI requires version > 2.  What do you think?

**Comment by nvcastet** [comment]
@brandon-biggs  For RHEL/CentOS 7, the version 3 of MPI should be present in their repo:
`sudo yum install openmpi3-devel` (notice the number `3` in the package name). But to get the latest version, you will need to compile.

**Comment by nvcastet** [comment]
@nvcastet Yes that should be fine.
