### ISSUE TITLE
tcp_peer_send_blocking broken pipe

### ISSUE THREAD

**Issue by sto-chastic** [horovod/horovod#1684]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.4
3. Horovod version: 0.19
4. MPI version: 1.10.2
5. CUDA version: 10.0
6. NCCL version:  2.4.2
7. Python version: 3.5
8. OS and version: Ubuntu 16.04
9. GCC version: 7.4.0

I have the same docker environment running on two different machines in my network. I can successfully ssh between the two docker containers (from one to the other and vice-versa) without being prompted for password or anything. However, when I try to run 
`mpirun -report-uri - --hostfile hostfile --mca plm_rsh_args "-p 8022" -np 1 /tmp/sample.py`

I get:
`2844262400.0;tcp://172.17.0.2:56711
[1d26d805fd33:10032] [[43400,0],2] tcp_peer_send_blocking: send() to socket 9 failed: Broken pipe (32)
ORTE was unable to reliably start one or more daemons.`
where "1d26d805fd33" is indeed the correct name of my other container, however "172.17.0.2" is the ip address of my docker0 interface.

I tried running:
`mpirun -report-uri - --hostfile hostfile -bind-to none --mca btl_tcp_if_exclude docker0,eth1 --mca btl ^docker0,eth1 --mca btl_tcp_if_include 192.168.21.11/24 --mca plm_rsh_args "-p 8022" -np 1 /tmp/sample.py`

with no change at all in the output. Same "...;tcp://172.17.0.2:56711"

Running with the "-vvv" flag shows:

`
2964848640.0;tcp://172.17.0.2:53315
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "192.168.21.11" port 8022
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.21.11 [192.168.21.11] port 8022.
debug1: Connection established.
debug1: identity file /home/n/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "192.168.21.93" port 8022
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.21.93 [192.168.21.93] port 8022.
debug1: Connection established.
debug1: identity file /home/n/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/n/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.8 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.21.11:8022 as 'n'
debug3: put_host_port: [192.168.21.11]:8022
debug3: hostkeys_foreach: reading file "/home/n/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/n/.ssh/known_hosts:9
debug3: load_hostkeys: loaded 1 keys from [192.168.21.11]:8022
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:KOKzldAbixZWlLykWKjR1IVWMhyhSIJhYcIXO4FTNAc
debug3: put_host_port: [192.168.21.11]:8022
debug3: put_host_port: [192.168.21.11]:8022
debug3: hostkeys_foreach: reading file "/home/n/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/n/.ssh/known_hosts:9
debug3: load_hostkeys: loaded 1 keys from [192.168.21.11]:8022
debug3: hostkeys_foreach: reading file "/home/n/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/n/.ssh/known_hosts:9
debug3: load_hostkeys: loaded 1 keys from [192.168.21.11]:8022
debug1: Host '[192.168.21.11]:8022' is known and matches the ECDSA host key.
debug1: Found key in /home/n/.ssh/known_hosts:9
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: /home/n/.ssh/id_rsa (0x55bd6afb3350)
debug2: key: /home/n/.ssh/id_dsa ((nil))
debug2: key: /home/n/.ssh/id_ecdsa ((nil))
debug2: key: /home/n/.ssh/id_ed25519 ((nil))
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.8
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.8 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.21.93:8022 as 'n'
debug3: put_host_port: [192.168.21.93]:8022
debug3: hostkeys_foreach: reading file "/home/n/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/n/.ssh/known_hosts:10
debug3: load_hostkeys: loaded 1 keys from [192.168.21.93]:8022
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:CDzELfO8hvkzWzhwcdIBkUtoIRckqWdYVXArbB+kzno
debug3: put_host_port: [192.168.21.93]:8022
debug3: put_host_port: [192.168.21.93]:8022
debug3: hostkeys_foreach: reading file "/home/n/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/n/.ssh/known_hosts:10
debug3: load_hostkeys: loaded 1 keys from [192.168.21.93]:8022
debug3: hostkeys_foreach: reading file "/home/n/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /home/n/.ssh/known_hosts:10
debug3: load_hostkeys: loaded 1 keys from [192.168.21.93]:8022
debug1: Host '[192.168.21.93]:8022' is known and matches the ECDSA host key.
debug1: Found key in /home/n/.ssh/known_hosts:10
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: /home/n/.ssh/id_rsa (0x564c635a3350)
debug2: key: /home/n/.ssh/id_dsa ((nil))
debug2: key: /home/n/.ssh/id_ecdsa ((nil))
debug2: key: /home/n/.ssh/id_ed25519 ((nil))
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/n/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug2: input_userauth_pk_ok: fp SHA256:Ud1qqnqacz8SBrmts5V2MzX7pySecB2aKccmL1kHF9M
debug3: sign_and_send_pubkey: RSA SHA256:Ud1qqnqacz8SBrmts5V2MzX7pySecB2aKccmL1kHF9M
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.21.11 ([192.168.21.11]:8022).
debug2: fd 4 setting O_NONBLOCK
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/n/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug2: input_userauth_pk_ok: fp SHA256:Ud1qqnqacz8SBrmts5V2MzX7pySecB2aKccmL1kHF9M
debug3: sign_and_send_pubkey: RSA SHA256:Ud1qqnqacz8SBrmts5V2MzX7pySecB2aKccmL1kHF9M
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.21.93 ([192.168.21.93]:8022).
debug2: fd 4 setting O_NONBLOCK
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 91
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x08
debug2: client_session2_setup: id 0
debug1: Sending environment.
debug3: Ignored env CUDNN_VERSION
debug3: Ignored env TERM_PROGRAM
debug3: Ignored env HOSTNAME
debug3: Ignored env REDIS_MODE
debug3: Ignored env NVIDIA_REQUIRE_CUDA
debug3: Ignored env TERM
debug3: Ignored env SHELL
debug3: Ignored env AMD_ENTRYPOINT
debug3: Ignored env LIBRARY_PATH
debug3: Ignored env TERM_PROGRAM_VERSION
debug3: Ignored env LS_COLORS
debug3: Ignored env NVIDIA_VISIBLE_DEVICES
debug3: Ignored env LD_LIBRARY_PATH
debug3: Ignored env NVIDIA_DRIVER_CAPABILITIES
debug3: Ignored env REDIS_HOST
debug3: Ignored env PATH
debug3: Ignored env PWD
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env CUDA_PKG_VERSION
debug3: Ignored env CUDA_VERSION
debug3: Ignored env REDIS_PORT
debug3: Ignored env SHLVL
debug3: Ignored env HOME
debug3: Ignored env PIPE_LOGGING
debug3: Ignored env LANGUAGE
debug3: Ignored env NCCL_VERSION
debug3: Ignored env VSCODE_IPC_HOOK_CLI
debug3: Ignored env LESSOPEN
debug3: Ignored env DISPLAY
debug3: Ignored env VERBOSE_LOGGING
debug3: Ignored env LESSCLOSE
debug3: Ignored env COLORTERM
debug3: Ignored env _
debug3: Ignored env OMPI_MCA_plm_rsh_args
debug3: Ignored env OMPI_COMMAND
debug1: Sending command:  orted --hnp-topo-sig 0N:1S:1L3:6L2:6L1:6C:12H:x86_64 -mca ess "env" -mca orte_ess_jobid "2964848640" -mca orte_ess_vpid 1 -mca orte_ess_num_procs "3" -mca orte_hnp_uri "2964848640.0;tcp://172.17.0.2:53315" --tree-spawn -mca plm "rsh" -mca plm_rsh_args "-p 8022 -vvv" --tree-spawn
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: read<=0 rfd 4 len 0
debug2: channel 0: read failed
debug2: channel 0: close_read
debug2: channel 0: input open -> drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug3: send packet: type 96
debug2: channel 0: input drain -> closed
debug2: channel 0: rcvd ext data 1100
debug2: channel 0: rcvd ext data 550
debug2: channel 0: written 1650 to efd 6
debug3: receive packet: type 91
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x08
debug2: client_session2_setup: id 0
debug1: Sending environment.
debug3: Ignored env CUDNN_VERSION
debug3: Ignored env TERM_PROGRAM
debug3: Ignored env HOSTNAME
debug3: Ignored env REDIS_MODE
debug3: Ignored env NVIDIA_REQUIRE_CUDA
debug3: Ignored env TERM
debug3: Ignored env SHELL
debug3: Ignored env AMD_ENTRYPOINT
debug3: Ignored env LIBRARY_PATH
debug3: Ignored env TERM_PROGRAM_VERSION
debug3: Ignored env LS_COLORS
debug3: Ignored env NVIDIA_VISIBLE_DEVICES
debug3: Ignored env LD_LIBRARY_PATH
debug3: Ignored env NVIDIA_DRIVER_CAPABILITIES
debug3: Ignored env REDIS_HOST
debug3: Ignored env PATH
debug3: Ignored env PWD
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env CUDA_PKG_VERSION
debug3: Ignored env CUDA_VERSION
debug3: Ignored env REDIS_PORT
debug3: Ignored env SHLVL
debug3: Ignored env HOME
debug3: Ignored env PIPE_LOGGING
debug3: Ignored env LANGUAGE
debug3: Ignored env NCCL_VERSION
debug3: Ignored env VSCODE_IPC_HOOK_CLI
debug3: Ignored env LESSOPEN
debug3: Ignored env DISPLAY
debug3: Ignored env VERBOSE_LOGGING
debug3: Ignored env LESSCLOSE
debug3: Ignored env COLORTERM
debug3: Ignored env _
debug3: Ignored env OMPI_MCA_plm_rsh_args
debug3: Ignored env OMPI_COMMAND
debug1: Sending command:  orted --hnp-topo-sig 0N:1S:1L3:6L2:6L1:6C:12H:x86_64 -mca ess "env" -mca orte_ess_jobid "2964848640" -mca orte_ess_vpid 2 -mca orte_ess_num_procs "3" -mca orte_hnp_uri "2964848640.0;tcp://172.17.0.2:53315" --tree-spawn -mca plm "rsh" -mca plm_rsh_args "-p 8022 -vvv" --tree-spawn
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: read<=0 rfd 4 len 0
debug2: channel 0: read failed
debug2: channel 0: close_read
debug2: channel 0: input open -> drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug3: send packet: type 96
debug2: channel 0: input drain -> closed
debug2: channel 0: rcvd ext data 1650
debug2: channel 0: written 1650 to efd 6
debug2: channel 0: rcvd ext data 103
[1d26d805fd33:11422] [[45240,0],2] tcp_peer_send_blocking: send() to socket 9 failed: Broken pipe (32)
debug2: channel 0: written 103 to efd 6
debug3: receive packet: type 98
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug3: receive packet: type 96
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug2: channel 0: obuf empty
debug2: channel 0: close_write
debug2: channel 0: output drain -> closed
debug3: receive packet: type 97
debug2: channel 0: rcvd close
debug3: channel 0: will not send data after close
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug3: send packet: type 97
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)

debug3: send packet: type 1
debug1: fd 0 clearing O_NONBLOCK
Transferred: sent 2972, received 4592 bytes, in 0.1 seconds
Bytes per second: sent 25208.0, received 38948.6
debug1: Exit status 1
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.`

**Comment by tgaddair** [comment]
Hey @sto-chastic, have you tried running with `horovodrun` instead of `mpirun`?  It simplifies a lot of the process of finding the right arguments to `mpirun`.

Alternatively, can you try running `ifconfig` on each machine and ensuring that network interfaces are the same.  If not, try excluding the ones that do not overlap with `-mca btl_tcp_if_exclude`.

It also seems you're using an old version of MPI, is it possible to upgrade?

If none of those suggestions work, I would also take a look at #400.

**Comment by sto-chastic** [comment]
Hello @tgaddair, I did indeed solved this issue by upgrading MPI, and adding "--network=host" parameter when running the docker container.
However, I know face another issue which is that my hvd.local_rank() is always 0, no matter the slots or the number of processes. Do you have some idea of what I could try?
