### ISSUE TITLE
hvd.local_rank() is always 0

### ISSUE THREAD

**Issue by sto-chastic** [horovod/horovod#1686]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.4
3. Horovod version: 0.19
4. MPI version: 1.10.2 OR 4.0. (tested both) 
5. CUDA version: 10.0
6. NCCL version: 2.4.2
7. Python version: 3.5
8. OS and version: Ubuntu 16.04
9. GCC version: 7.4.0

When I run `mpirun --hostfile hostfile_horovod -mca plm_rsh_args "-p 8022" python3 small_test.py`, which prints `print(hvd.local_rank())`, I always get 0, even when my nodes have 2 slots and 2 GPUs each.

I read that this could be because of different version of openmpi, (which I did have), however since I am using a docker container, I was able to remove one and the other. First I tested uninstalling version 1.10 and working only with version 4, and then I tried only using version 1.10 (never installing version 4), but I get the same result.

More interestingly, I ran the following script 
```
#include <stdio.h>
#include <mpi/mpi.h>

int main (int argc, char **argv) {
   int nProcId, nProcNo;

   int nNameLen;
   char szMachineName[MPI_MAX_PROCESSOR_NAME];

   MPI_Init (&argc, &argv); // Start up MPI

   MPI_Comm_size (MPI_COMM_WORLD,&nProcNo); // Find out number of processes
   MPI_Comm_rank (MPI_COMM_WORLD, &nProcId); // Find out process rank
   MPI_Get_processor_name (szMachineName, &nNameLen); // Get machine name

   printf ("Hello World from process %d on %s\r\n", nProcId, szMachineName);

   if (nProcId == 0)
      printf ("Number of Processes: %d\r\n", nProcNo);

   MPI_Finalize (); // Shut down MPI

   return 0;
}
```
on purely mpi `mpirun --hostfile hostfile -np 8 -mca plm_rsh_args "-p 8022" sample`, and it properly prints:
```
Hello World from process 3 on david-System-Product-Name
Hello World from process 2 on david-System-Product-Name
Hello World from process 5 on david-System-Product-Name
Hello World from process 0 on david-System-Product-Name
Number of Processes: 8
Hello World from process 1 on david-System-Product-Name
Hello World from process 4 on david-System-Product-Name
Hello World from process 6 on n
Hello World from process 7 on n
```
where my two nodes are _david-System-Product-Name_ and _n_.

**Comment by tgaddair** [comment]
Hey @sto-chastic, in the second example, you specify `-np 8` to `mpirun`:

```
mpirun --hostfile hostfile -np 8 -mca plm_rsh_args "-p 8022" sample
```

But in the Horovod example run, you do not:

```
mpirun --hostfile hostfile_horovod -mca plm_rsh_args "-p 8022" python3 small_test.py
```

Please try providing `-np` when using Horovod, and try again.  Also, you may want to consider using `horovodrun` instead of `mpirun`.  Is there a reason you're using `mpirun` directly?

**Comment by sto-chastic** [comment]
Hello, thank you for your help. I tried adding np:
`mpirun --hostfile hostfile_horovod -np 4 -mca plm_rsh_args "-p 8022" python3 small:test.py` with the same result. Also, I do not use `horovodrun` since I use a custom port "-p 8022", and in the documentation I found, the example you provide for custom ports uses `mpirun`. I am not sure how to use custom ports directly with `horovodrun`
