### ISSUE TITLE
Is Keras (with MXNet backend) supported by Horovod?

### ISSUE THREAD

**Issue by awan-10** [horovod/horovod#1712]
**Environment:**
1. Framework: (MXNet)
2. Framework version: 
3. Horovod version: 0.19.0
4. MPI version:
5. CUDA version: 10.1
6. NCCL version: N/A
7. Python version: Python3
8. OS and version: RHEL 7
9. GCC version: gcc 8.3.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I am trying to run the examples/keras_mnist.py using MXNet as a backend for Keras. Is this supported officially?

Also, I changed the following line
import horovod.keras as hvd --> import horovod.mxnet as hvd

When I run the code, I get the following error.

Traceback (most recent call last):
  File "keras_mnist.py", line 75, in <module>
    metrics=['accuracy'])
  File "/home/awan/mconda3-mv2gdr/lib/python3.7/site-packages/keras/backend/mxnet_backend.py", line 5392, in compile
    sample_weight_mode, **kwargs)
  File "/home/awan/mconda3-mv2gdr/lib/python3.7/site-packages/keras/engine/training.py", line 96, in compile
    self.optimizer = optimizers.get(optimizer)
  File "/home/awan/mconda3-mv2gdr/lib/python3.7/site-packages/keras/optimizers.py", line 805, in get
    str(identifier))
ValueError: Could not interpret optimizer identifier: <horovod.mxnet.DistributedOptimizer object at 0x7fa56989d550>

**Comment by tgaddair** [comment]
Hey @awan-10, at the moment we only support Keras with a TensorFlow backend, but this sounds like it would be worth adding support for.  @apeforest, is this on your roadmap, or do you have an estimate for how difficult it would be to support this?

**Comment by awan-10** [comment]
@tgaddair - Thanks for your quick response! It will be great to have this support as Keras is a good bridge between two major frameworks (TF and MXNet). It will also simply my life as a person developing benchmarks for distributed training using different frameworks.
