### ISSUE TITLE
Problem about the hostname

### ISSUE THREAD

**Issue by 652994331** [horovod/horovod#1713]
I am using a cluster(there are multi gpus here). However, this cluster has an old problem. the node name of each machine(hostname) contain "_". when i tried to use horovod on the machines in this cluster. invalid hostname (because of "_" in the hostname of the machine) cause problem. however, this hostname problem can not be modified because of the rules of the cluster. My question is: Is there any way we can still use horovod if the hostname is invalid(contains "_").Thanks

**Comment by tgaddair** [comment]
Hey @652994331 can you share the full error message you see?  This may be MPI specific.  If so, you could consider using our [Gloo](https://github.com/horovod/horovod#gloo) controller instead.
