### ISSUE TITLE
Can horovod run with OpenMPI's allreduce implement?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [horovod/horovod#1719]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)TensorFlow
2. Framework version:1.13.1
3. Horovod version:0.19.0 
4. MPI version:4.0.2
5. CUDA version:10.0
6. NCCL version:2.4.2
7. Python version:3.6.8
8. OS and version:CentOS 7.6
9. GCC version:4.8.5

I am try to bring `usnic`(a `NIC`  support `DMA`) to allreduce of deep learning framework. Currently, `usnic` can be used  by `OpenMPI`,  and horovod's documents indicated that horovod can use MPI's all reduce implement,  so I decide to compile horovod with `OpenMPI`'s all reduce implement then  `OpenMPI` can use `usnic` to complete bytes transport during all reduce operation.  But it seems that `OpenMPI`'s all reduce implement doesn't supoort handle bytes in GPU memory, so does horovod consider this, and can horovod run with `OpenMPI`'s allreduce implement?

**Comment by tgaddair** [comment]
Hey @Keepmoving-ZXY, Horovod does support OpenMPI for allreduce.  If you want to use MPI for operations on GPU memory, you need to set `HOROVOD_GPU_ALLREDUCE=MPI` at install time (see docs [here](https://github.com/horovod/horovod/blob/master/docs/gpus.rst#advanced-have-a-proprietary-mpi-implementation-with-gpu-support-optimized-for-your-network)).

**Comment by Keepmoving-ZXY** [comment]
ok, thank you, I will try to find another way to achieve this.
