### ISSUE TITLE
AWS DLAMI upgrade to Horovod Spark

### ISSUE THREAD

**Issue by sazzad1012** [horovod/horovod#1723]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
Hello!
I am using Ubuntu 18.04 an AWS DLAMI with preinstalled Horovod. I wanted to upgrade to Horvod[Spark] using the following command:
pip3 install --upgrade --user Horvod[Spark}
But the built process failed. Could you pls point out what I can do to install or upgrade to Horvod[Spark] version. Thanks.

**Comment by tgaddair** [comment]
Hey @sazzad1012, happy to help.  Can you share the error message along with the exact command you used to install Horovod?

**Comment by sazzad1012** [comment]
Hello Travis. Thanks a lot for your prompt response. I have two issues, one
is withe the DLAMI. The other is installing Horovod from scratch on an AWS
EC2 gpu instance. But for this I can't even downgrade to g++-4.9 on
Ubuntu18.04.  I have tried various suggestions offered at Stackoverflow
(see below). Pls let me know what is the best way to proceed to have
Horovod installed on AWS instances. Your help is truly appreciated. Thanks.
Sazzad

For example if run

 sudo apt install gcc-4.9 g++-4.9

Reading package lists... Done

Building dependency tree

Reading state information... Done

Package gcc-4.9 is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or

is only available from another source


Package g++-4.9 is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or

is only available from another source


E: Package 'gcc-4.9' has no installation candidate

E: Package 'g++-4.9' has no installation candidate
