### ISSUE TITLE
Horovod.run.run on multiple hosts kills jupyter notebook session

### ISSUE THREAD

**Issue by brandon-biggs** [horovod/horovod#1724]
**Environment:**
1. Framework: (**TensorFlow**, Keras, PyTorch, MXNet)
2. Framework version: 2.0
3. Horovod version: 0.19.0
4. MPI version: 
```
mpirun --version
mpirun (Open MPI) 4.0.2
```
5. CUDA version: 10.2
6. NCCL version: 2.5.6
7. Python version: 2.7
8. OS and version: Centos 7,7
9. GCC version:
```
$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
```
**Checklist:**
1. Did you search issues to find if somebody asked this question before? No
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Don't think it's about hang
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Not about docker
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Couldn't find it

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

I have horovod.run.run working on 1 server with four GPUs finally after the issues I had in #1691. However, now when I try to run horovod.run.run on multiple servers with multiple GPUs, my Jupyter notebook runs for a few seconds and then crashes. The error message is:
```
The kernel appears to have died. It will restart automatically.
```
Here's my first cell:
```
import horovod
import horovod.run
import tensorflow as tf
import horovod.tensorflow as hvd

def test_main():
    # Horovod: initialize Horovod.
    hvd.init()
    # Horovod: pin GPU to be used to process local rank (one GPU per process)
    gpus = tf.config.experimental.list_physical_devices('GPU')
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)
    if gpus:
        tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
    print(f"Hello world from {hvd.local_rank()}")
```
Then I make my horovod.run.run call in my second cell:
```
horovod.run.run(test_main, np=2, hosts="host1:4, host2:4", verbose=True, disable_cache=True)
```
I do get a little output before it crashes:

> Filtering local host names.
> Remote host found: host1
> Checking ssh on all remote hosts.
> SSH was successful into all the remote hosts.
> Testing interfaces on all the hosts.
> Launched horovodrun server.
> Attempted to launch horovod task servers.
> Waiting for the hosts to acknowledge.
> Notified all the hosts that the registration is complete.
> Waiting for hosts to perform host-to-host interface checking.

After this it immediately crashes. I figured there might be a brief wait, but there is not. Looking at the code, the crash appears to be occurring in [run.py)[https://github.com/horovod/horovod/blob/master/horovod/run/run.py#L252].

I can run this script with just mpi and it works on host1:4 and host2:4 just fine, so I don't think it's that. If y'all have any ideas, let me know. 

I'd like to scale horovod.run.run up to a _few_ more than just these two nodes if possible. :)

**Comment by tgaddair** [comment]
Hey @brandon-biggs, does it also fail if you use `horovodrun` as opposed to `mpirun`?  The code paths should be very similar.

**Comment by brandon-biggs** [comment]
Thanks @tgaddair sorry for all the problems I'm causing. Hopefully these problems are more helpful to y'all than annoying :)
```
$ horovodrun -np 8 -H host1:4,host2:4 python horovod-run-run.py --verbose

Launching horovodrun task function was not successful:

File "../path/python3.7/site-packages/horovod/run/common/util/network.py", line 174, in __init__
    'Linux.'.format(service_name=service_name, addresses=addresses))
horovod.run.common.util.network.NoValidAddressesFound: Horovodrun was unable to connect to horovodrun task service #0 on any of the following addresses: {'lo': [('127.0.0.1', 12913)], '<host 1 network interface1>': [('<host1 ip address here>', 12913)]}.

'Linux.'.format(service_name=service_name, addresses=addresses))
horovod.run.common.util.network.NoValidAddressesFound: Horovodrun was unable to connect to horovodrun task service #1 on any of the following addresses: {'lo': [('127.0.0.1', 19370)], 'host 2 interface1': [('<host2 ip address here', 19370)]}.

One possible cause of this problem is that horovodrun currently requires every host to have at least one routable network interface with the same name across all of the hosts. You can run "ifconfig -a" on every host and check for the common routable interface. To fix the problem, you can rename interfaces on Linux.
```
Hmm.. How interesting. Quite the issue. The interface names definitely aren't the same. It's not on purpose that they're different. When we set this system up, we never really had a purpose to having them be the same or different, it just happened. 

According to the documentation, the equivalent should be the following mpirun command, which does work:
```
mpirun -np 8 -H host1:4,host2:4 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python horovod-run-run.py
```

What's the purpose in requiring the interface names to be the same?

**Comment by tgaddair** [comment]
That's a good question, @brandon-biggs.  cc @abditag2, who did the original implementation of `horovodrun`.  Do you know the reasoning for including interfaces instead of excluding unroutable interfaces?  It may make sense to allow users to circumvent this behavior in some way.

**Comment by abditag2** [comment]
After looking carefully into this, matching interface names is not something that is strictly necessary. If I remember correctly, we chose this because explicitly specifying what NIC to use rather than excluding some NICs, seemed simpler and compatible with most of the common naming scheme on cloud and on-prem machines. 

I don't disagree with switching to excluding the unroutable interfaces. Note that if the naming of interfaces is not consistent across workers, we might still end up in a situation like the following where we will have to exclude both eth0 and eth1 and show different behavior than mpirun. 

Host 1: 
eth0: local virtual machine or container
eth1: physical eth NIC

Host 2:
eth0: physical eth NIC
eth1: local virtual machine or container

**Comment by brandon-biggs** [comment]
Hi @abditag2 Thanks for the feedback. That makes sense as to why it may be an option, but it seems like it's being strictly enforced right now. I could be wrong, I just never saw an option as to where I could specify a way to ignore this.

Is there a way to ignore strict enforcement so that I can submit to multiple nodes or is there something in the code that's going to need to change?

**Comment by abditag2** [comment]
we don't have an option right now. I will submit a fix for this asap. In the meanwhile, can you rename your NICs to get unblocked?

**Comment by alokprasad** [comment]
@abditag2 anyway to bypass same name NIC requirement .

**Comment by tgaddair** [comment]
Hey @alokprasad @brandon-biggs, can you try out #1808 and check that it addresses your issue?

**Comment by brandon-biggs** [comment]
@tgaddair I'd be happy to give it a shot! I'll try it out today and get back to you on it.

**Comment by brandon-biggs** [comment]
@tgaddair I installed it, tested it on my "hello world" code that was in my original post, and it didn't crash! So that's exciting! I'm working on a more advanced test now. I'll keep y'all updated. Here's my horovod.run.run command:

horovod.run.run(train, np=2, hosts="host1:4,host2:4", verbose=True, disable_cache=True, network_interface="enp19s0f1.10,enp19s0f0.10", use_mpi=True, mpi_args="--oversubscribe")​
