### ISSUE TITLE
S3Store on hovorod.spark.common.store

### ISSUE THREAD

**Issue by nanne-aben** [horovod/horovod#1732]
I'm interested in using Hovorod on our Spark cluster, but I'd like to use it with S3 rather than HDFS.

**Comment by tgaddair** [comment]
Hey @nanne-aben, thanks for the feature request.  I think this should be doable given that PyArrow now natively supports S3.  I can try putting together a quick PR for you to try out.

**Comment by nanne-aben** [comment]
Hi @tgaddair, that'd be great! Thanks! Let me know when it's there, would be more than happy to look at the PR.

**Comment by tgaddair** [comment]
Hey @nanne-aben, quick update on this.  We're making some changes to our intermediate data storage API to make it more generic, so it will work with S3 if your Spark application is configured to use S3.  I'll let you know when these features are available, should be soon.  Thanks.

**Comment by nanne-aben** [comment]
Thanks, Travis!
