### ISSUE TITLE
V0.19.0 allreduce not working

### ISSUE THREAD

**Issue by jacob1017** [horovod/horovod#1742]
**Environment:**
1. Framework: pytorch
2. Framework version: 1.3.0
3. Horovod version:0.19.0
4. MPI version:mpich 3.3a2
5. CUDA version:10.1
6. NCCL version:2.4.8
7. Python version:3.7.5
8. OS and version:ubuntu 16.04
9. GCC version:4.9

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.
`
 import horovod.torch as hvd
import torch

hvd.init()
if hvd.rank()==0:
    l = [7371]
else:
    l = [7340]
al = torch.as_tensor(l)
hvd.allreduce(al,average=False)
print("rank {} {}".format(hvd.rank(),al))
if hvd.rank() == 0:
    print("size{}".format(hvd.size()))
    print("rank {}".format(hvd.rank()))
`
Try run `mpirun -np 2 python3 test_hvd.py` I get the result below:
`
rank 1 tensor([7340])
rank 0 tensor([7371])
size2
rank 0
`

**Comment by romerojosh** [comment]
The issue here is that you are using `hvd.allreduce` which is the out of place version of the operation. For an in-place allreduce, use `hvd.allreduce_`.

**Comment by jacob1017** [comment]
@romerojosh thank you for your reply. I found this operation was not in-place。
