### ISSUE TITLE
How to interpret the autotune score?

### ISSUE THREAD

**Issue by LearnedVector** [horovod/horovod#1745]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

How do you interpret the autotune score? Here are examples of the score i got from the `--autotune` flag. is lower or higher better? Thanks.

hierarchical_allreduce | hierarchical_allgather | cache_enabled | cycle_time_ms | tensor_fusion_threshold | score
-- | -- | -- | -- | -- | --
0 | 0 | 0 | 5 | 4 | 345.019
0 | 0 | 0 | 50 | 32 | 277.975
0 | 0 | 0 | 25 | 16 | 304.979
0 | 0 | 0 | 10 | 8 | 333.886
0 | 0 | 0 | 3.67928 | 12.2035 | 343.508
0 | 0 | 0 | 79.3857 | 21.2982 | 243.854
0 | 0 | 0 | 15.8994 | 9.7665 | 321.553

**Comment by tgaddair** [comment]
Hey @LearnedVector, the score is approximately a measure of bytes processed during allreduce / allgather per microsecond, so higher is better.  In this case, it looks like a low cycle time and fusion buffer threshold resulted in the best performance.  Worth noting is that the best param settings will vary with each model, number of workers, cluster config, etc.  Let me know if you have any additional questions!

**Comment by LearnedVector** [comment]
thank you!
