### ISSUE TITLE
Issues with multi machine training

### ISSUE THREAD

**Issue by abdullahfsm** [horovod/horovod#1754]
1. Do I need to have the executing script available on all servers in a multi-machine training setup?
2. It seems like horovodrun is just replicating the training script on specified servers rather than synchronized distributed training between them. I know this because printing hvd.rank() yields the same value (= 0) from each instance. Am I missing something? I have been able to correctly run multi-gpu training on a single machine but in this the gpus are on different machines.
Thanks!

**Comment by tgaddair** [comment]
Hey @abdullahfsm, to answer your questions:

1. Yes, the training script needs to be available on all hosts.  This can be either on a local disk or a shared filesystem like NFS.
2. Seeing `hvd.rank() == 0` across all workers usually means there's an issue with how MPI is configured (see [this](https://stackoverflow.com/questions/4039608/why-do-all-my-open-mpi-processes-have-rank-0) SO issue, for example).  To test this, you could try running with Gloo mode instead (`horovodrun --gloo`).
