### ISSUE TITLE
Why hvd.rank() is always 0 while 4 MPI processes have been launched?

### ISSUE THREAD

**Issue by wuxun-zhang** [horovod/horovod#1756]
**Environment:**
1. Framework: MXNet
2. Framework version:
3. Horovod version: 0.18.2
4. MPI version: Intel MPI
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I used Intel MPI and Horovod to launch multiple processes in one node. Now, I have already launched 4 MPI processes, however `hvd.size()` and `hvd.rank()` are always `1` and `0`.

```
[0] MPI startup(): Rank    Pid      Node name            Pin cpu
[0] MPI startup(): 0       80756    mlp  {96}
[0] MPI startup(): 1       80755    mlp  {120}
[0] MPI startup(): 2       80754    mlp  {144}
[0] MPI startup(): 3       80757    mlp  {168}
```

```
[2020-03-03 03:46:35] num_workers = 1
[2020-03-03 03:46:35] this rank = 0
[2020-03-03 03:46:35] Distributed training is enabled via Horovod.
[2020-03-03 03:46:35] num_workers = 1
[2020-03-03 03:46:35] this rank = 0
[2020-03-03 03:46:35] Distributed training is enabled via Horovod.
[2020-03-03 03:46:35] num_workers = 1
[2020-03-03 03:46:35] this rank = 0
[2020-03-03 03:46:35] Distributed training is enabled via Horovod.
[2020-03-03 03:46:35] num_workers = 1
[2020-03-03 03:46:35] this rank = 0
[2020-03-03 03:46:35] Distributed training is enabled via Horovod.
```

I also encounter an error related to gloo like below. and just set `HOROVOD_GLOO_IFACE=lo` to get rid of this issue. However, I am not sure if these two issue are related.
```
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /tmp/pip-install-e4c1qr23/horovod/third_party/gloo/gloo/transport/tcp/device.cc:88] ifa != nullptr. Unable to find address for: eth0
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /tmp/pip-install-e4c1qr23/horovod/third_party/gloo/gloo/transport/tcp/device.cc:88] ifa != nullptr. Unable to find address for: eth0
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /tmp/pip-install-e4c1qr23/horovod/third_party/gloo/gloo/transport/tcp/device.cc:88] ifa != nullptr. Unable to find address for: eth0
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /tmp/pip-install-e4c1qr23/horovod/third_party/gloo/gloo/transport/tcp/device.cc:88] ifa != nullptr. Unable to find address for: eth0
```

Can anyone help me on this problem. Really appreciate your help. Thanks.

**Comment by tgaddair** [comment]
Hey @wuxun-zhang, how are you launching Horovod?  It looks like Horovod was installed with Gloo support, but you're attempting to launch it with `mpirun`.  If that's true, then you have a couple options:

1. Use `horovodrun` instead of `mpirun` to run with Gloo.
2. Reinstall Horovod setting `HOROVOD_WITH_MPI=1` to run with MPI.

**Comment by wuxun-zhang** [comment]
@tgaddair Thanks. It's my fault. There is something wrong with the MPI library I used and looked it fall back to Gloo implementation. Now everything is Okay after switching to the right one.

**Comment by tgaddair** [comment]
Glad you got it working, @wuxun-zhang.  I'll close the issue for now.
