### ISSUE TITLE
Latency with Horovod

### ISSUE THREAD

**Issue by chandana1332** [horovod/horovod#1759]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): MXNET
2. Framework version: 1.5
3. Horovod version: 0.18.2
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I have been benchmarking various types of models with and without Horovod. 
I see drastically varying improvements with Horovod between model types and sizes. 

Sometimes, I see a 5x improvement in training time but sometimes, it's only 1.2x.
Can someone shed some light on why is there such drastic difference in observed improvements?
What factors affect scaling efficiency?

**Comment by tgaddair** [comment]
Hey @chandana1332, assuming the same number of hosts, GPUs, networking environment, etc., and only the model is changed, then it's usually a matter of the number and size of parameters.  

Some models like VGG16 with 138 million parameters will be more difficult to scale than ResNet50 with 25 million parameters.

But that said your particular GPU and networking setup can also be better suited to some models than others.  In general, we recommend creating a [timeline](https://github.com/horovod/horovod/blob/master/docs/timeline.rst) when you see poor scaling efficiency so we can better understand where the slowdown is happening.

**Comment by chandana1332** [comment]
Some models like VGG16 with 138 million parameters will be more difficult to scale than ResNet50 with 25 million parameters.
>> Is it hard it scale 138M parameters because it is bottlenecked by NVLink bandwidth?

But that said your particular GPU and networking setup can also be better suited to some models than others. In general, we recommend creating a timeline when you see poor scaling efficiency so we can better understand where the slowdown is happening
>> I can create a timeline but when you say some models are better suited for some GPUs are you talking about CUDA and CUDNN's performance for some models are more optimal than others?

Also, what is the expected scaling for very small, medium and very large models? Which of these are expected to scale the best and why?
I presume, medium, large and small in the order of scaling.
