### ISSUE TITLE
DenseVectors metadata missing when Model is fitted on parquete

### ISSUE THREAD

**Issue by m-mallory** [horovod/horovod#1762]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version: 0.19.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
When fitting an estimator using parquete training data ([fit_on_parquet()](https://github.com/horovod/horovod/blob/586dbcdc448739b3ab3108a9549ad478afae9e17/horovod/spark/common/estimator.py#L39)).
In [get_simple_metadata_from_parquet()](https://github.com/horovod/horovod/blob/586dbcdc448739b3ab3108a9549ad478afae9e17/horovod/spark/common/util.py#L387)

the `'shape'` of the metadata field is set null. 

However, when applying the fitted model, in [_transform()](https://github.com/horovod/horovod/blob/586dbcdc448739b3ab3108a9549ad478afae9e17/horovod/spark/torch/estimator.py#L375), 
The shape of dense vectors are used:
```
if col_type == DenseVector:
                        shape = meta['shape']
                        flattened_pred = pred.reshape(shape, )
                        field = DenseVector(flattened_pred)
```

**Comment by abditag2** [comment]
this should fix it: https://github.com/horovod/horovod/pull/1764
