### ISSUE TITLE
How should I use Horovod if I change the model size during training

### ISSUE THREAD

**Issue by yeliang2258** [horovod/horovod#1778]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): pytorch
2. Framework version: 1.4.0
3. Horovod version:0.19.0
4. MPI version:
5. CUDA version:10.1
6. NCCL version:
7. Python version:3.6
8. OS and version:16.06
9. GCC version:5.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
How should I use Horovod if I change the model size during training. 
I will change the size of the model during the training process. In this case, how should I use Horovod？ Thanks

**Comment by tgaddair** [comment]
Hey @yeliang2258, can you give an example of what you're attempting to do?  In principle, it should be possible to change the model and have Horovod work correctly, but I'm not familiar with the approach you're describing to say for sure.

**Comment by yeliang2258** [comment]
> Hey @yeliang2258, can you give an example of what you're attempting to do? In principle, it should be possible to change the model and have Horovod work correctly, but I'm not familiar with the approach you're describing to say for sure.

Thank you for replying. For example, I want to use horovod to help me complete the network compression work. In 10 training epochs, the size of the network will reduce gradually. In general, I want to train on multiple GUPs, but as the training progresses, the network size will change gradually.
