### ISSUE TITLE
Dockerfile needs to be updated

### ISSUE THREAD

**Issue by abcinje** [horovod/horovod#1791]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version: 3.6
8. OS and version: Ubuntu 18.04.4
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

Hello. I've followed the instructions in the [docker guide](https://github.com/horovod/horovod/blob/master/docs/docker.rst).
While building Horovod in docker by running
```
$ docker build -t horovod:latest horovod-docker-gpu
```
I've got the following error
![bug](https://user-images.githubusercontent.com/33629617/76625760-4ae31400-657b-11ea-9e6e-8c28ef3ec12c.PNG)

As a workaround, I added an argument to `get_supported()` function like:
```
w.get_supported('.')
```
And it worked well.

**Comment by tgaddair** [comment]
Thanks for catching this @abcinje.  Looks like there was a breaking change to the `wheel` module at https://github.com/pypa/wheel/commit/b5733b86155c696274564e86c2a5f966f9abbebf.  I'll make a fix.
