### ISSUE TITLE
When build docker container with ubuntu16.04 install horovod failed with error code -4

### ISSUE THREAD

**Issue by JuZhengHub** [horovod/horovod#1798]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow
2. Framework version: tensorflow-gpu==1.14.0
3. Horovod version: latest
4. MPI version: 3.1.5
5. CUDA version: 10.0
6. NCCL version: 2.5.6
7. Python version: 3.5
8. OS and version: ubuntu16.04
9. GCC version: g++ 5.6

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I am trying to build container with "nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04"
chose tensorflow version 1.14.0 
refer to "Dockerfile-gpu" on github
found openmpi-4.0.x cannot compile passed on ubuntu16.04 ,so change to openmpi-3.1.5 and compile passed

but when i try to install horovod by follow command some error happened:

RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
      HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 \
          ¦python3 -m pip install --no-cache-dir horovod && \
      ldconfig
---------------------------------------------------------------------
Error message(failed with error code -4) (but i cannot find any useful error message.....):

Step 9/11 : RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs &&     HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1          python3 -m pip install --no-cache-dir horovod &&     ldconfig
 ---> Running in 569e38897ff5
Collecting horovod
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c0/31/dae1f224a284ccaf0fd700565a53658bfba9c3d5964719305953e72a11e0/horovod-0.19.1.tar.gz (2.9MB)
Collecting cloudpickle (from horovod)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ea/0b/189cd3c19faf362ff2df5f301456c6cf8571ef6684644cfdfdbff293825c/cloudpickle-1.3.0-py2.py3-none-any.whl
Collecting psutil (from horovod)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/c4/b8/3512f0e93e0db23a71d82485ba256071ebef99b227351f0f5540f744af41/psutil-5.7.0.tar.gz (449kB)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python3.5/dist-packages (from horovod)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python3.5/dist-packages (from horovod)
Collecting cffi>=1.4.0 (from horovod)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d6/7f/7acc85c478f5056b98c9961a31697b1e53fbec158ee5f723097e1c355660/cffi-1.14.0-cp35-cp35m-manylinux1_x86_64.whl (399kB)
Collecting pycparser (from cffi>=1.4.0->horovod)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
Installing collected packages: cloudpickle, psutil, pycparser, cffi, horovod
  Running setup.py install for psutil: started
    Running setup.py install for psutil: finished with status 'done'
  Running setup.py install for horovod: started
    Running setup.py install for horovod: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_8yka3m6/horovod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-l0nal9cq-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.5/horovod
    creating build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/mpi_run.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/run.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/gloo_run.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/run_task.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run
    copying horovod/run/task_fn.py -> build/lib.linux-x86_64-3.5/horovod/run
    creating build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow
    creating build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/compression.py -> build/lib.linux-x86_64-3.5/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch
    creating build/lib.linux-x86_64-3.5/horovod/spark
    copying horovod/spark/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark
    creating build/lib.linux-x86_64-3.5/horovod/common
    copying horovod/common/util.py -> build/lib.linux-x86_64-3.5/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/common
    copying horovod/common/basics.py -> build/lib.linux-x86_64-3.5/horovod/common
    creating build/lib.linux-x86_64-3.5/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/keras
    creating build/lib.linux-x86_64-3.5/horovod/_keras
    copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/_keras
    copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/_keras
    creating build/lib.linux-x86_64-3.5/horovod/mxnet
    copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-3.5/horovod/mxnet
    copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-3.5/horovod/mxnet
    creating build/lib.linux-x86_64-3.5/horovod/run/http
    copying horovod/run/http/http_server.py -> build/lib.linux-x86_64-3.5/horovod/run/http
    copying horovod/run/http/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/http
    copying horovod/run/http/http_client.py -> build/lib.linux-x86_64-3.5/horovod/run/http
    creating build/lib.linux-x86_64-3.5/horovod/run/task
    copying horovod/run/task/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/task
    copying horovod/run/task/task_service.py -> build/lib.linux-x86_64-3.5/horovod/run/task
    creating build/lib.linux-x86_64-3.5/horovod/run/common
    copying horovod/run/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common
    creating build/lib.linux-x86_64-3.5/horovod/run/driver
    copying horovod/run/driver/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/run/driver
    copying horovod/run/driver/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/driver
    creating build/lib.linux-x86_64-3.5/horovod/run/util
    copying horovod/run/util/threads.py -> build/lib.linux-x86_64-3.5/horovod/run/util
    copying horovod/run/util/cache.py -> build/lib.linux-x86_64-3.5/horovod/run/util
    copying horovod/run/util/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/util
    copying horovod/run/util/network.py -> build/lib.linux-x86_64-3.5/horovod/run/util
    creating build/lib.linux-x86_64-3.5/horovod/run/common/service
    copying horovod/run/common/service/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
    copying horovod/run/common/service/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
    copying horovod/run/common/service/task_service.py -> build/lib.linux-x86_64-3.5/horovod/run/common/service
    creating build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/config_parser.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/secret.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/env.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/codec.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/__init__.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/settings.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/timeout.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/network.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    copying horovod/run/common/util/host_hash.py -> build/lib.linux-x86_64-3.5/horovod/run/common/util
    creating build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/tensorflow/keras
    creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.5/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.5/horovod/spark/task
    copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
    copying horovod/spark/task/task_info.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
    copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
    copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-3.5/horovod/spark/task
    creating build/lib.linux-x86_64-3.5/horovod/spark/torch
    copying horovod/spark/torch/estimator.py -> build/lib.linux-x86_64-3.5/horovod/spark/torch
    copying horovod/spark/torch/remote.py -> build/lib.linux-x86_64-3.5/horovod/spark/torch
    copying horovod/spark/torch/util.py -> build/lib.linux-x86_64-3.5/horovod/spark/torch
    copying horovod/spark/torch/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/torch
    creating build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/_namedtuple_fix.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/estimator.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/cache.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/params.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/store.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/util.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/backend.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/constants.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    copying horovod/spark/common/serialization.py -> build/lib.linux-x86_64-3.5/horovod/spark/common
    creating build/lib.linux-x86_64-3.5/horovod/spark/keras
    copying horovod/spark/keras/bare.py -> build/lib.linux-x86_64-3.5/horovod/spark/keras
    copying horovod/spark/keras/estimator.py -> build/lib.linux-x86_64-3.5/horovod/spark/keras
    copying horovod/spark/keras/optimizer.py -> build/lib.linux-x86_64-3.5/horovod/spark/keras
    copying horovod/spark/keras/remote.py -> build/lib.linux-x86_64-3.5/horovod/spark/keras
    copying horovod/spark/keras/util.py -> build/lib.linux-x86_64-3.5/horovod/spark/keras
    copying horovod/spark/keras/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/keras
    copying horovod/spark/keras/tensorflow.py -> build/lib.linux-x86_64-3.5/horovod/spark/keras
    creating build/lib.linux-x86_64-3.5/horovod/spark/driver
    copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
    copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
    copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
    copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-3.5/horovod/spark/driver
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -fassociative-math -ffast-math -ftree-vectorize -funsafe-math-optimizations -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_cpp_flags.so
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.5/test_compile/test_link_flags.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.5/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.5/test_compile/test_link_flags.so
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -fassociative-math -ffast-math -ftree-vectorize -funsafe-math-optimizations -I/usr/local/cuda/include -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lcudart -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.so
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -fassociative-math -ffast-math -ftree-vectorize -funsafe-math-optimizations -I/usr/local/cuda/include -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_nccl.cc -o build/temp.linux-x86_64-3.5/test_compile/test_nccl.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_nccl.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lnccl_static -o build/temp.linux-x86_64-3.5/test_compile/test_nccl.so
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++11 -fPIC -O2 -Wall -fassociative-math -ffast-math -ftree-vectorize -funsafe-math-optimizations -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/usr/local/cuda/include -I/usr/include/python3.5m -c build/temp.linux-x86_64-3.5/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lcudart -o build/temp.linux-x86_64-3.5/test_compile/test_cuda.so
    
    ----------------------------------------
[91mCommand "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_8yka3m6/horovod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-l0nal9cq-record/install-record.txt --single-version-externally-managed --compile" **failed with error code -4 i**n /tmp/pip-build-_8yka3m6/horovod/
-------------------------------------------------------------------------------------------------------

within this error message i canno figure out what error happened , could anyone meet this error or can help to fix this ,thank u ~

**Comment by tgaddair** [comment]
Hey @JuZhengHub, this error looks very similar to the one from #577.  Can you check that your CPU supports AVX instructions?

**Comment by JuZhengHub** [comment]
@tgaddair exactly , this eeror cause by this, i changed another server to build this image, it works !
thank u for answer, this is really helpful for me !
