### ISSUE TITLE
How to use Horovod timeline to analyze the communication time?

### ISSUE THREAD

**Issue by jiangzihanict** [horovod/horovod#1800]
I have two questions about the timeline.

First, the following picture is the timeline after running 10 steps of [the Imagenet ResNet-50 code](https://github.com/horovod/horovod/blob/master/examples/keras_imagenet_resnet50.py). I want to get the communication time each step, but the granularity is second and the events are too crowded. Is there a way to make the millisecond-level analysis? 

Second, the communication may overlap the computation, so how can I get the non-overlap part? 

<img width="1677" alt="Screen Shot 2020-03-18 at 10 41 24 PM" src="https://user-images.githubusercontent.com/22028950/76974824-a55de500-696c-11ea-969e-e431f86c4a5b.png">

Thanks!

**Comment by tgaddair** [comment]
Hey @jiangzihanict, in the tracing UI you can use the third button in the selection (upper right of the screenshot) to zoom in for higher granularity.

As for digging into communication-only time, the NCCLAllreduce step int the timeline should represent that the most closely.  @romerojosh, do you have any further suggestions for digging into communication time?

**Comment by jiangzihanict** [comment]
Thanks, @tgaddair. I use this timeline tool to analyze my code and find there is a NEGOTIATED_ALLREDUCE before each ALL_REDUCE operation of each training step. The NEGOTIATED_ALLREDUCE dominated the communication time (The following figure).  It seems very time-consuming. 

My question is what is the purpose of this negotiation? I have read the related docs, but I am confused cause there are too many NEGOTIATED_ALLREDUCE operations, occupying a lot of training time. 

Is NEGOTIATED_ALLREDUCE trying to solve the deadlock problem (From [this paper](https://dl.acm.org/doi/10.5555/3291656.3291724))? 

![7341585229544_ pic_hd](https://user-images.githubusercontent.com/22028950/77658819-31e25600-6fb2-11ea-867c-dd44d34e18d3.jpg)

**Comment by romerojosh** [comment]
The Horovod timeline doesn't show any of the compute operations on GPU, so you cannot get a good understanding of how well communication is overlapping with computation using this alone. I generally use NVIDIA profiling tools (like NVPROF and NVVP for visualization or the newer Nsight system). With these more broad profiles, you can see all the NCCL Allreduce kernels launched by Horovod along side all the other operations launched by the framework on the GPU.

**Comment by jiangzihanict** [comment]
Thanks, @romerojosh. I've already used Nvidia NVPORF to analyze the time breakdown of a FasterRCNN model. I trained this model with an end-to-end manner and deployed it on an 8-V100-GPUs machine. The GPU is connected bt NVLINK. 

In my profiling results, the kernel named `ncclAllReduceRingLLKernel_sum_f32` occupies 35% of total running time. Is it because of the bad overlap between communication and computation? Except for increasing batch_size (this model only support batch_size=1), is there any other way to decrease the time of `ncclAllReduceRingLLKernel_sum_f32`?

**Comment by kingwales1** [comment]
Hi @jiangzihanict Did you figure it out? I also want to profile both and computation and communication time in each step respectively.

**Comment by mrhalyang** [comment]
> Thanks, @romerojosh. I've already used Nvidia NVPORF to analyze the time breakdown of a FasterRCNN model. I trained this model with an end-to-end manner and deployed it on an 8-V100-GPUs machine. The GPU is connected bt NVLINK.
> 
> In my profiling results, the kernel named `ncclAllReduceRingLLKernel_sum_f32` occupies 35% of total running time. Is it because of the bad overlap between communication and computation? Except for increasing batch_size (this model only support batch_size=1), is there any other way to decrease the time of `ncclAllReduceRingLLKernel_sum_f32`?

Have you solved this issue？ @jiangzihanict
