### ISSUE TITLE
Runtime Error: hvd.broadcast_global_variables() does not support eager execution

### ISSUE THREAD

**Issue by yurinishikawa** [horovod/horovod#1802]
**Environment:**
1. Framework: Keras
2. Framework version: 2.3.1 (Backend: TensorFlow 2.0.1)
3. Horovod version: 0.19.1
4. MPI version: OpenMPI 2.1.6
5. CUDA version: 10.0.130.1 
6. NCCL version: 2.5.6-1
7. Python version: 3.6.5
8. OS and version: CentOS 7.5.1804
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?  -- yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? 
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? --yes

**Your question:**

Hi.  I am trying to run [examples/keras_mnist.py](examples/keras_mnist.py) using TF2.0 backend.  
I am having trouble with the following error:

```
RuntimeError: hvd.broadcast_global_variables() does not support eager execution. 
Please use `hvd.broadcast_variables(<model/optimizer variables>)` instead.
```

I looked into [examples/tensorflow2_keras.py](examples/tensorflow2_keras.py) (which works fine), but it imports `tf.keras` and `horovod.tensorflow.keras`.  I am currently trying to apply Horovod to my code written in standalone Keras (which requires TF2.0 backend), so I want to run [examples/keras_mnist.py](examples/keras_mnist.py) without any error.

I also noticed that `experimental_run_tf_function=False` was set in [ examples/tensorflow2_keras.py](examples/tensorflow2_keras.py).  
When I set that option in [examples/keras_mnist.py](examples/keras_mnist.py), it returns:

```
ValueError: Session keyword arguments are not support during eager execution. 
You passed: {'experimental_run_tf_function': False}
```

The training starts when I remove `hvd.callbacks.BroadcastGlobalVariablesCallback(0)` from callback, but I think it is not recommended due to my understanding.  I appreciate your help in advance!

**Comment by tgaddair** [comment]
Hey @yurinishikawa, you should not need `experimental_run_tf_function` for standalone Keras.  Instead of using `BroadcastGlobalVariablesCallback` should still work, if it's not then that may be a bug on our end.  Can you share a gist of the script you're running with all the modifications you've made?

**Comment by yurinishikawa** [comment]
Thanks @tgaddair.  The training started when I omitted both `experimental_run_tf_function` and `BroadcastGlobalVariablesCallback` from my code, but I encountered a NaN loss after around 10 epochs, so I was thinking it was due to removing the function from the callback.   (I get the runtime error when I only remove `experimental_run_tf_function` since the following statement becomes False, probably because `variables` attribute doesn't exist in `self.model` when I build a model with standalone Keras) 
https://github.com/horovod/horovod/blob/8280bc72b45ab3883247df04f147e46d7efb0d98/horovod/_keras/callbacks.py#L33

I have another question -- according to the [document](https://horovod.readthedocs.io/en/latest/keras.html), `BroadcastGlobalVariablesCallback` broadcasts only initial variable states, but the broadcast operation seems to be running at the end of each batch according to [callbacks.py](horovod/horovod/_keras/callbacks.py).  Is there a way (or an example) to broadcast a model state to the other workers periodically without using the callback?

The modifications I made are as follows:
-  lr = original_lr * hvd.size
- steps_per_epoch = original_steps / hvd.size
The rest of the hyperparameters are the same as the original code (such as epochs and batch size)  

Thanks!

**Comment by yurinishikawa** [comment]
Hi @tgaddair, the NaN loss issue has been resolved by scheduling the learning rate using `LearningRateScheduleCallback`.  Thanks for your help.  I am still curious about the behavior of `BroadcastGlobalVariablesCallback` at the end of each batch.  I'd appreciate if you can give me the answers to the question in your free time.

**Comment by tgaddair** [comment]
Hey @yurinishikawa, glad you got the issue resolved.  Feel free to reach out if you have any further questions.

**Comment by arunkumar1605** [comment]
@tgaddair i'm also facing same error.
"RuntimeError: hvd.broadcast_global_variables() does not support eager execution. Please use `hvd.broadcast_variables(<model/optimizer variables>)` instead."

import horovod.tensorflow.keras as hvd

scaled_lr = learning_rate * hvd.size()
optimizer=tf.optimizers.Adam(scaled_lr)
opt = hvd.DistributedOptimizer(optimizer)

callbacks=[hvd.callbacks.BroadcastGlobalVariablesCallback(0)]

**Comment by tgaddair** [comment]
Hey @arunkumar1605, can you share more of your script?  Are you using `import keras` or `tf.keras`?

**Comment by arunkumar1605** [comment]
Hi @tgaddair, i have provided training script and the estimator step details below. Please let me know if any additional details required.

######################## import packages ################################################

import keras
import tensorflow as tf
from keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D,BatchNormalization,Activation,LeakyReLU
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential
from keras.applications.densenet import DenseNet121,DenseNet169
from keras.applications.densenet import preprocess_input
from tensorflow.keras.utils import multi_gpu_model, Sequence
import os
import horovod.tensorflow.keras as hvd
from keras import backend as K
########################Horovod setup########################################################
hvd.init()

gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')

    
verbose=1 if hvd.rank() == 0 else 0
##############################Building Model############################################################
from sklearn.metrics import accuracy_score,roc_auc_score
from keras.optimizers import Adam

print('Building Model...')


model=Sequential()
model.add(DenseNet121(weights='imagenet',include_top=False,input_shape=(224,224,3)))#,dropout_rate=0.5))
model.add(GlobalAveragePooling2D())
model.add(Dropout(0.5))
model.add(Dense(14,activation='sigmoid'))# adds last layer to have 14 neurons [[14 ,kernel_regularizer=regularizers.l2(0.01))]]
model.summary()
parallel_model = model
'''

model=tf.keras.Sequential([
    tf.keras.applications.DenseNet121(weights='imagenet',include_top=False,input_shape=(224,224,3)),
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(14,activation='sigmoid')])
model.summary()

parallel_model = model
'''
def custom_loss(targets, output):
    _epsilon = tf.convert_to_tensor(K.epsilon(),output.dtype.base_dtype)#, output.dtype.base_dtype
    output = tf.clip_by_value(tf.cast(output,tf.float32), _epsilon, 1 - _epsilon)
    output = tf.math.log(output / (1 - output))
    weight=tf.convert_to_tensor(w_minus,dtype='float32')
    return K.mean(weight*tf.nn.weighted_cross_entropy_with_logits(logits=output, labels=targets, pos_weight=np.array(n_by_p), name=None),axis=-1)


auc_roc = tf.keras.metrics.AUC(
    num_thresholds=200, curve='ROC', summation_method='interpolation', name=None,
    dtype=None, thresholds=None)



scaled_lr = learning_rate * hvd.size()
optimizer=Adam(scaled_lr)

opt = hvd.DistributedOptimizer(optimizer)

parallel_model.compile(loss=custom_loss,optimizer=opt,metrics=[auc_roc])

# start an Azure ML run
run = Run.get_context()

############################## Model Building Ends here ##########################################

############################# Model Training & Validation Starts ####################################
from keras.callbacks import ReduceLROnPlateau
            
class Histories(keras.callbacks.Callback):
    def __init__(self,model):
        self.model_for_saving = model
        self.monitor_op = np.less
        self.best = np.Inf
        
    def on_train_begin(self, logs={}):
        self.aucs = []
        self.losses = []
        print("training started")

    def on_train_end(self, logs={}):
        return

    def on_epoch_begin(self, epoch, logs={}):
        return

    def on_epoch_end(self, epoch, logs={}):
        self.losses.append(logs.get('loss'))
        ####run.log('Loss',log['loss'])
        current=logs.get('val_loss')
        ####run.log('val_loss',log['val_loss'])
        if self.monitor_op(current, self.best):
            print('\nEpoch %05d: %s improved from %0.5f to %0.5f,'
                  ' saving model'
                  % (epoch + 1, 'val_loss', self.best,
                     current))
                     
            self.best = current
            self.model_for_saving.save(os.path.join(model_path,'weights.best.dense_generator_callback.hdf5'))
        else:
            print('\nEpoch %05d: %s did not improve from %0.5f' %
                                  (epoch + 1, 'val_loss', self.best))
        
        return

    def on_batch_begin(self, batch, logs={}):
        return

    def on_batch_end(self, batch, logs={}):
        return

auc=Histories(model=model)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                              patience=5, mode='min',min_lr=.00001,cooldown=1)


callbacks=[hvd.callbacks.BroadcastGlobalVariablesCallback(0),auc,reduce_lr]

if hvd.rank() == 0:
    callbacks.append(keras.callbacks.ModelCheckpoint('./checkpoint-{epoch}.h5'))
    
def train():
    import keras.backend as k
    history=parallel_model.fit_generator(training_generator,
                        steps_per_epoch=td_shape // hvd.size(), epochs=epochs,
                       validation_data=validation_generator,
                        validation_steps=vd_shape // hvd.size(),
                         verbose=verbose,
                        workers=4,
                        use_multiprocessing=False,
                        callbacks=callbacks
                       )#
    pd.DataFrame(history.history).to_csv(os.path.join(model_path,'history.csv'),index=False)
    history = pd.read_csv(os.path.join(model_path,'history.csv'))
    
    plt.plot(history['loss'])
    plt.plot(history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epochs')
    plt.legend(['train','valid'], loc='upper left')
    
    run.log_image('Epoch vs Loss',plot=plt)

######################### Estimator step ##########################################
from azureml.core.runconfig import MpiConfiguration
from azureml.train.dnn import TensorFlow

script_params = {
    '--epochs': 2,
    '--batch_size': 32,
    '--learning_rate':0.001
    
}

estimator_step = TensorFlow(source_directory = script_folder,
                script_params = script_params,
                compute_target = gpu_compute_target,
                entry_script = 'hyperdrive_training.py',
                pip_packages=['keras==2.3.1','matplotlib','opencv-python','azure-storage-blob==2.1.0'], 
                conda_packages = ['scikit-learn==0.22.1'] ,
                inputs=[xrayimage_dataset.as_named_input('xrayimage_dataset').as_mount('/temp/xray_images'),
                        traindata_dataset.as_named_input('traindata_dataset'),
                        validdata_dataset.as_named_input('validdata_dataset'),
                        traintarget_dataset.as_named_input('traintarget_dataset'),
                        validtarget_dataset.as_named_input('validtarget_dataset')],
                framework_version = '2.0',
                node_count=3,
                process_count_per_node=1,
                distributed_training=MpiConfiguration(),
                use_gpu=True)

**Comment by ChaiBapchya** [comment]
Did we find a resolution for the issue @arunkumar1605
