### ISSUE TITLE
openmpi - could not resolve hostname

### ISSUE THREAD

**Issue by EchoTheCat** [horovod/horovod#1811]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
--------------------------------------------------------------------------
I'm attempting to follow this tutorial,
https://docs.abinit.org/tutorial/basepar/
I run the command mpirun -np 2 -machinefile cluster ../../src/main/abinit < tbasepar_1.files >& tbasepar_1.log &
I open the output file and see an error message,
ssh: Could not resolve hostname sleepy: nodename nor servname provided, or not known
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
Upon searching I find that most common cause is having an outdated version of open mpi, so I check mpirun --version and the result is:
mpirun (Open MPI) 4.0.3

Any thoughts on what might be causing this issue?

**Comment by tgaddair** [comment]
Hey @EchoTheCat, can you check that you don't have more than one version of OpenMPI installed?  Also, can you try `ssh sleepy` directly and verify that it works without a password prompt?

**Comment by EchoTheCat** [comment]
Hi! I'm not sure to check if I have multiple versions installed, though I have attempted to uninstall openmpi with the command `make uninstall openmpi-4.0.3` and the result is `make: *** No rule to make target `uninstall'.  Stop.` The result of `sudo ssh sleepy` and `ssh sleepy` is `Could not resolve hostname sleepy: nodename nor servname provided, or not known`
