### ISSUE TITLE
Horovod synthetic benchmarks example command exec fail

### ISSUE THREAD

**Issue by cCloudSky** [horovod/horovod#1812]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
0.19.1
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
run example command
https://horovod.readthedocs.io/en/latest/benchmarks.html#horovod-synthetic-benchmarks
>$ horovodrun -np 4 server1:2,server2:2 \
    python --fp16-allreduce tensorflow2_synthetic_benchmark.py

with error occur
>mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.
NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

is lack `-H` flag before hosts?

**Comment by tgaddair** [comment]
Hi @cCloudSky, yes, you need specify the command as:

```
horovodrun -np 4 -H server1:2,server2:2 python --fp16-allreduce tensorflow2_synthetic_benchmark.py
```

We'll update the docs.  Thanks for pointing this out.
