### ISSUE TITLE
Can I specify multiple CPUs and memory?

### ISSUE THREAD

**Issue by pratzz** [horovod/horovod#1816]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

Can I specify number of CPUs and memory to be used? If yes, how? I saw docs stating either number of processes or number of GPUs, can I specify both? Basically I am looking for a multi node multi CPU multi GPU deployment.

**Comment by abditag2** [comment]
You can only specify number of processes. If there are GPUs on the machine, each process will use one GPU. If there are no GPUs on the machine, process can use all the machine cores. How much of the cores they utilize totally depends on your code and your framework (pytorch and TF's underlying multiprocessing and multithreading. 

We do not restrict the use of memory and it is all up to your code. You can use parameters such as batch size to control the memory footprint.
