### ISSUE TITLE
Does Horovod use the optimized NCCL2 hierarchical allreduce?

### ISSUE THREAD

**Issue by chandana1332** [horovod/horovod#1827]
I have the understanding that Horovod uses NCCL to allreduce (with a ring structure) within each machine and use MPI to allreduce (with a tree structure) across machines because NCCL's allreduce across machines wasn't not optimal. 

NCCL2 has since introduced a hierarchical allreduce. Does Horovod use that?

**Comment by romerojosh** [comment]
The hierarchical strategy (NCCL intranode, MPI internode) is an optional path in Horovod (enabled via `HOROVOD_HIERARCHICAL_ALLREDUCE=1`), while the default path is to use NCCL alone for the allreduce across the entire worker set. The underlying NCCL library will use tree-based or ring-based communication algorithms, depending on the topology of the system it detects and message sizes.

**Comment by chandana1332** [comment]
>>The underlying NCCL library will use tree-based or ring-based communication algorithms, depending on the topology of the system it detects and message sizes.

I couldn't find anything on NCCL that explains the above behaviour. Is the logic to pick a particular algorithm in Horovod or NCCL?

Also, if MPI for allreduce is optional behavior, what are the main reasons for using MPI in Horovod? Can I get speedup by using NCCL's ring allreduce without MPI?

**Comment by romerojosh** [comment]
The algorithm selection logic is within NCCL. For more details, you can refer to their docs or ask a question on their Github repository.

Even when using NCCL for allreduce and other collectives, there is still network communication in Horovod for control logic (making sure workers are submitting the same collectives, in the same order, etc.). Horovod can use either MPI or gloo for this control communication layer.
