### ISSUE TITLE
load and pre-process training data when doing the sync of weight

### ISSUE THREAD

**Issue by Leslie-Fang** [horovod/horovod#1840]
Hi All, I am using horovod with TF. Since my dataset is little bit larger. When I am using horovod to do the training among the CPU cluster. After each training step, horovod would sync the data among the system with ring-allreduce. 
My question is that, is it possible for the worker to load and pre-process the training data for next step when sync the weights of current training step among the worker.

**Comment by tgaddair** [comment]
Hey @Leslie-Fang, yes, this is something that TensorFlow natively supports called [prefetching](https://www.tensorflow.org/guide/data_performance#prefetching).  If you're using `tf.data` and you enable it, then you can preprocess batch b+1 while batch b is being allreduced.

**Comment by Leslie-Fang** [comment]
@tgaddair Thanks that's what I am looking for.
