### ISSUE TITLE
Dataset distribution

### ISSUE THREAD

**Issue by anweshpanda** [horovod/horovod#1841]
Hi
I have my own dataset and I am using horovod with pytorch. I want to distribute my dataset among all the processors uniformly so that I can do distributed training. So can anyone please help , how can I do that?

**Comment by SriramAvatar** [comment]
@anweshpanda, these two links could help.
[Issue1210](https://github.com/horovod/horovod/issues/1210)
[Issue1100](https://github.com/horovod/horovod/issues/1100) - Check the last replies.
Thanks.

**Comment by anweshpanda** [comment]
I checked them but I did not get them quite much.... What I want to do is like process 0 reads the data,store in a dataloader and distributes them uniformly among all the processors....How can I do that?Is there any simple way to achieve this?

**Comment by SriramAvatar** [comment]
I am working on a similar sample.Try the distribution using dataframe slicing as below.
`dfSliced = dfFull.iloc[hvd.rank()::hvd.size(), :].copy()`

dfFull - the pandas dataframe that contains the image path as a column
On node 0, hvd.rank() = 0 and for a total of 4 nodes, hvd.size()
So on node 0, take dfFull.iloc[0::4(every 4th record)]. Make sure to copy the dataframe.

**Comment by anweshpanda** [comment]
Thanks....... @SriramAvatar
