### ISSUE TITLE
Horovod with Tensorflow

### ISSUE THREAD

**Issue by Victorsoukhov** [horovod/horovod#1842]
**Environment:**
Documentation information

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
There is no information on the link https://github.com/horovod/horovod/blob/master/docs/tensorflow.rst

Please Provide.

Thank you!

**Comment by tgaddair** [comment]
Hey @Victorsoukhov, thanks for pointing out this issue with the docs.  I'll make a change to fix this.  In the meantime, you can find the information you're looking for [here](https://horovod.readthedocs.io/en/latest/tensorflow.html).

Also, we have a number of [examples](https://github.com/horovod/horovod/tree/master/examples) of both TensorFlow v1 and v2 (with and without Keras) to work off of.

**Comment by oldmonkABA** [comment]
Hi @tgaddair The [link](https://horovod.readthedocs.io/en/latest/tensorflow.html) you have given seems to be for Tensorflow 1.0 and not 2.0. Do you have something for tf 2.0

**Comment by tgaddair** [comment]
Hey @oldmonkABA, yes.  I've updated the docs to include v2 details in #1854.  Please take a look.
