### ISSUE TITLE
Running Horovod on Kubernetes with Istio

### ISSUE THREAD

**Issue by akirillov** [horovod/horovod#1855]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.1.0
3. Horovod version: 0.19.0
4. MPI version: 4.0.0
5. CUDA version: 10.1
6. NCCL version: 2.4.8
7. Python version: 3.7.5
8. OS and version: Ubuntu 18.04 (Docker)
9. GCC version: 7.5.0

**Checklist:**
- [x] 1. Did you search issues to find if somebody asked this question before?
- [x] 2. If your question is about hang, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/running.rst)?
- [x] 3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
- [x] 4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Hi everyone!

I'm running Horovod-on-Spark on Kubernetes with Istio. Istio injects sidecars to all the running containers which modify `iptables` to reroute the application traffic through the proxy running in the sidecars. From the Horovod point of view, every single service (inherited from `BasicService`) runs behind NAT which leads to the expected error in logs:
```
Running 5 processes (inferred from spark.default.parallelism)...
ERROR: Task 2 declared addresses {'lo': [('127.0.0.1', 13739)], 'eth0': [('192.168.141.99', 13739)]}, but has connected from a different address 127.0.0.6. This is not supported. Is the server behind NAT?
ERROR: Task 0 declared addresses {'lo': [('127.0.0.1', 9545)], 'eth0': [('192.168.141.98', 9545)]}, but has connected from a different address 127.0.0.6. This is not supported. Is the server behind NAT?
ERROR: Task 1 declared addresses {'lo': [('127.0.0.1', 28561)], 'eth0': [('192.168.2.168', 28561)]}, but has connected from a different address 127.0.0.6. This is not supported. Is the server behind NAT?
ERROR: Task 4 declared addresses {'lo': [('127.0.0.1', 55957)], 'eth0': [('192.168.143.45', 55957)]}, but has connected from a different address 127.0.0.6. This is not supported. Is the server behind NAT?
ERROR: Task 3 declared addresses {'lo': [('127.0.0.1', 49520)], 'eth0': [('192.168.143.46', 49520)]}, but has connected from a different address 127.0.0.6. This is not supported. Is the server behind NAT?
```

It seems like this is by design but I'd really appreciate any pointers to the documentation or explanation why the inter-service communication designed that way and why NAT is not supported.

Is there any way to change `TaskService` registration mechanism so that all the remote workers register with their local IPs and bypass this check?

If anybody in the community has an idea for a workaround, I'd really appreciate any suggestions.

**Comment by ZHUXUHAN** [comment]
hi, do you solve the problem?

**Comment by akirillov** [comment]
soft ping @EnricoMi. Can you please share any pointers to the documentation or share the idea why the inter-service communication deprecates NAT? Is it possible to make this behavior configurable?

**Comment by silenceli** [comment]
I meet the some question

**Comment by tgaddair** [comment]
Looks like this check was added by @alsrgv in #1076 to address #1032.

It seems like we should be able ignore the `client_address` and go with the IP from the task address when the user explicitly provides a NIC.  @alsrgv, do you have any thoughts on this, or are you aware of additional complications when using NAT?

**Comment by akirillov** [comment]
Thanks for some of the background, @tgaddair. I'm also wondering if this check still valid for Gloo backend?
