### ISSUE TITLE
Data Parallelism: How it works and is Slicing the right way?

### ISSUE THREAD

**Issue by SriramAvatar** [horovod/horovod#1858]
**Data Parallelism:**
 As horovod does a training based on data parallelism, every node trains on the different set of data?How is the data split done with proper sampling? 
Some tensorflow samples use the tensorflow: `tensorflow.dataset.shard()`
Some databricks samples use Slicing : `dfSliced = dfFull.iloc[hvd.rank()::hvd.size(), :].copy()`

1 : What is the correct way?
2 : If slicing is used, is it required that each node should contain data representing all labels, example, there could be a chance that for a multi-class problem a node receives only data representing one class.
Thanks.

**Comment by tgaddair** [comment]
Hey @SriramAvatar, usually we would recommend using `tf.dataset.shard()` if using TFRecord, or [Petastorm](https://github.com/uber/petastorm) if using Parquet.

The example Databricks provides using `iloc` is probably a toy example.  In practice, you wouldn't use Pandas to read the data, as it would require reading the entire dataset into memory on each worker.  One of the motivations for data parallelism is that the dataset is often too large to read into memory.  Using the other libraries I mentioned, they will shard the data without needing to read it first, and will stream in records to avoid out-of-memory errors.
