### ISSUE TITLE
horovod docker run multiple machines without shared filesystem

### ISSUE THREAD

**Issue by xupengcoding** [horovod/horovod#1883]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
I don't understand the horovod docker docs, how can i run on multi machines without shared filesystem.

**Comment by xupengcoding** [comment]
@tgaddair

**Comment by iamyangchen** [comment]
You basically need to be able to ssh to the other machines from your rank 0 docker. With that said, simply copy the public key to the other machines' `/root/.ssh/authorized_keys`.
