### ISSUE TITLE
How does horovod handles fault tolerance

### ISSUE THREAD

**Issue by dkajtoch** [horovod/horovod#1887]
I would like to know if horovod is able to resume training if one of the nodes is down in distributed training? This situation happens frequently on Google Ai platform when training for many hours with lot of virtual machines and resources. I believe it maybe due to maintenance reasons. Or from different angle: is it possible to train models on preemptible virtual machines which can be down pretty often?

**Comment by tgaddair** [comment]
Hey @dkajtoch, this is a timely question.  We have a PR in review now that adds fault tolerance capabilities to Horovod: #1849.

Once that lands, it will be possible to recover from individual worker failure or run on preemptible VMs, with minor code changes (see the linked [RFC](https://docs.google.com/document/d/15ZoHA5AeSI_boeyIBapg9WPXKrYXMRvPytPzQWTCTn4)).

We hope to have that landed soon, hopefully by the end of the month.
