### ISSUE TITLE
horovod running on remote host

### ISSUE THREAD

**Issue by kmtaotao** [horovod/horovod#1892]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
when I run the horovod on remote server with same network interface and SSH connected properly, I receive the error message:
Filtering local host names.
Remote host found: 192.168.1.178
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Launching horovodrun task function was not successful:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tao/.virtualenvs/dl4cv/lib/python3.6/site-packages/horovod/run/task_fn.py", line 67, in <module>
    _task_fn(index, driver_addresses, settings)
  File "/home/tao/.virtualenvs/dl4cv/lib/python3.6/site-packages/horovod/run/task_fn.py", line 24, in _task_fn
    task = task_service.HorovodRunTaskService(index, settings.key, settings.nics)
AttributeError: 'Settings' object has no attribute 'nics'

**Comment by tgaddair** [comment]
Hey @kmtaotao, what version of Horovod are you running?  Looks like the name of this property was recently changed from `nic` to `nics`.

**Comment by kmtaotao** [comment]
Thanks for the reply, it looks the remote server could be the problem, especially when the Hovovod is not installed properly, to make sure the most update version, to install Horovod with: 
HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir git+https://github.com/horovod/horovod

**Comment by kmtaotao** [comment]
@tgaddair  thanks a lot for the support, I tried to reinstall the horovod as well as openmpi, the newer version looks better for me. I believe the source file has to be the github new version.
