### ISSUE TITLE
gluon.Trainer restore parameters

### ISSUE THREAD

**Issue by feevos** [horovod/horovod#1897]
Dear all, 

how can I restore gluon.Trainer parameters from a saved state? I cannot find anything in the documentation. I have seen corresponding functions from pytorch, but I am not sure how to translate it (if possible) to mxnet. When I tried to load states from all nodes, it didn't work. 

Any help most appreciated.

**Comment by tgaddair** [comment]
Hey @apeforest @eric-haibin-lin any thoughts on this?

**Comment by feevos** [comment]
@apeforest  gave me a solution [in mxnet forum](https://discuss.mxnet.io/t/distributed-training-questions/1269/25), thank you. Am closing the issue.
