### ISSUE TITLE
Catch KeyboardInterrupt

### ISSUE THREAD

**Issue by jchwenger** [horovod/horovod#1903]
Hi,
I'm working on distributing openAI's TF 1.14 gpt-2 code on several GPUs, working fine so far, except I can't preserve this handy feature to save the model on keyboard interrupt:
```
try:
    # the training loop
except KeyboardInterrupt:
   if hvd.rank() == 0:
      save()
```
I would do it only on rank 0, but nothing happens, no exception at all (I also tried `except Exception as e:` to see if I could print it). I'm assuming this is because the horovod/mpi wrapper is the one receiving the signal, and then shutting down the python process in some other way . Is there a straightforward way to do this ? 

Horovod version: 0.19.1, 
mpirun (Open MPI): 4.0.3
CUDA Version 10.1.243
nccl: libnccl2=2.4.8-1+cuda10.1 libnccl-dev=2.4.8-1+cuda10.10.1
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

(installed using [the recommended steps](https://github.com/horovod/horovod#install))

Many thanks in advance!

**Comment by tgaddair** [comment]
Hey @jchwenger, when MPI receives an interrupt signal, it sends a SIGTERM signal to all the worker processes, followed shortly by a SIGKILL (see discussion [here](https://users.open-mpi.narkive.com/x4jxxpE4/ompi-users-how-does-mpirun-handle-ctrl-c)).

So my suggestion would be to use a signal handler to do the saving:

```
import signal

def on_exit():
    if hvd.rank() == 0:
        save()

signal.signal(signal.SIGINT, on_exit)
signal.signal(signal.SIGTERM, on_exit)
```

**Comment by jchwenger** [comment]
Hi @tgaddair thanks a lot for this! It really is the exact same situation as in the post you mention. I tried implementing your proposal, but so far no luck, I also have a print message in my function, and nothing happens (the processes are just stopped). I tried `SIGKILL` directly, which cannot be stopped or used in this way, and that unsurprisingly doesn't work.  I'll see if I can find time to get into this a bit deeper, but otherwise I fear this might be too time-consuming, as I also have another issue on the hob (compatibility with sentencepiece, I'll probably post another thing).

**Comment by jchwenger** [comment]
Hi again! 

After a quick investigation, I adapted [this script](https://stackoverflow.com/a/2148925) to loop through all the signals and see which one was printed by my processes. 

It seems it was `18`, or `SIGCONT`. However, even with this one, no luck. If I only ask my gpu processes to print this then they do, but if I ask them to save as well I'm back to silence, I'm assuming that the saving of the model is simply too long, and that the mpi master just sends the inescapable SIGKILL.... 

Thanks a lot for your help, that definitely put me on the right track!

**Comment by jchwenger** [comment]
I thought I'd write a message to the open-mpi users list, as a complement to the answer from 2015 quoted above, and I received this response:

> I have used SIGUSR1 and write a signal handler in the rank 0
> program to do whatever is needed to save data and shutdown cleanly
> (using standard MPI messages on an alternative communication
> channel that is initialized for just this purpose.  Other ranks
> test for messages on this channel at suitable points where they
> can stop gracefully.).
> Then you need to use kill to send the signal instead of CTRL/C.
> But I have a note in my code that I never implemented, that in
> case running on a remote server, some sort of socket protocol is
> needed to initiate the shutdown instead of a signal.
> George Reeke

I'm guessing that in order to do that one would have to bake this parallel messaging functionality into horovod itself (the rank 0 program)?  Clearly beyond what I can do right now, but maybe useful to somebody.
