### ISSUE TITLE
gcc error

### ISSUE THREAD

**Issue by joadiazcr** [horovod/horovod#1905]
While installing horovod with 

HOROVOD_WITH_TENSORFLOW=1 pip install horovod[tensorflow,keras]

I am getting a long error that ends with:

error: command '/usr/bin/gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mhz8vk74/horovod/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mhz8vk74/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-33ieci1w/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/simulations/.local/include/python3.6m/horovod Check the logs for full command output.

I think this is because I am not using the correct gcc version, which should be 4.8.5 (I have this version installed, but when I  do "gcc -v" I get gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
). How can I  solve this?

**Comment by tgaddair** [comment]
Hey @joadiazcr, can you share the full log output?  It looks like there might be another error message hidden in there.

What version of TensorFlow are you using?  That should also help us determine which version of gcc you should be using.  Assuming you have the correct version of gcc somewhere on your system, our install script should be able to find it.

**Comment by joadiazcr** [comment]
[horovod_install.log](https://github.com/horovod/horovod/files/4525976/horovod_install.log)

Thanks for the reply!

Attached is the log file.

The tensorflow version I have is 2.1.0 for python 3

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

When I try to install gcc 4.8 I  get:

$ sudo apt-get install gcc-4.8
[sudo] password for simulations: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc-4.8 is already the newest version (4.8.5-4ubuntu8).
The following packages were automatically installed and are no longer required:
  libvulkan1 python-psutil xbase-clients
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.

**Comment by tgaddair** [comment]
Hmm, looks like this may be related to AVX instructions.  What kind of CPU are you using?

```
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:85:0,
                   from third_party/eigen/Eigen/src/Core/util/ConfigureVectorization.h:307,
                   from third_party/eigen/Eigen/Core:22,
                   from horovod/common/ops/adasum/../../parameter_manager.h:26,
                   from horovod/common/ops/adasum/../../global_state.h:24,
                   from horovod/common/ops/adasum/../../controller.h:23,
                   from horovod/common/ops/adasum/adasum_mpi.h:22,
                   from horovod/common/ops/adasum/adasum_mpi.cc:16:
  /usr/lib/gcc/x86_64-linux-gnu/7/include/fmaintrin.h: In member function ‘void horovod::common::Adasum<Communicator_type>::ComputeDotAndNormSqrdsfp16(const uint16_t*, const uint16_t*, int, double&, double&, double&, int) [with Communicator_type = ompi_communicator_t*]’:
  /usr/lib/gcc/x86_64-linux-gnu/7/include/fmaintrin.h:47:1: error: inlining failed in call to always_inline ‘__m256d _mm256_fmadd_pd(__m256d, __m256d, __m256d)’: target specific option mismatch
   _mm256_fmadd_pd (__m256d __A, __m256d __B, __m256d __C)
   ^~~~~~~~~~~~~~~
```

@nvcastet, any thoughts?

**Comment by joadiazcr** [comment]
![image](https://user-images.githubusercontent.com/12650044/80163875-55d29080-858c-11ea-9090-47d2d19db113.png)
Here the CPU info

**Comment by nvcastet** [comment]
weird, your cpu does not support fma and we use `__FMA__ ` guard when that is the case so it should not compile this code.

**Comment by nvcastet** [comment]
@joadiazcr Can you paste the output of `gcc -dM -E - < /dev/null`?

**Comment by nvcastet** [comment]
Nevermind, my PR https://github.com/horovod/horovod/pull/1835 did not make it to the 0.19.1 release, @joadiazcr before we cut a new release you can build with master branch `pip install git+https://github.com/horovod/horovod.git --no-cache-dir`

**Comment by joadiazcr** [comment]
Thanks! It worked:
Successfully installed horovod-0.19.1

**Comment by tgaddair** [comment]
Glad you got it working!  I'm going to close this issue for now.  Sounds like we should try and get 0.19.2 released soon.
