### ISSUE TITLE
Elastic mode to enable fault tolerance and auto-scaling

### ISSUE THREAD

**Issue by tgaddair** [horovod/horovod#1907]
[RFC](https://docs.google.com/document/d/15ZoHA5AeSI_boeyIBapg9WPXKrYXMRvPytPzQWTCTn4/edit?usp=sharing)

This feature covers the bare-metal implementation of a fault tolerant and auto-scaling capability / API for Horovod built on top of the Gloo controller.

**Comment by gilinachum** [comment]
Does this implementation provides fault tolerance already? Starting of which Horovod/TF/PyTorch version?
Any user guide on how to utilize it? Does it work in AWS/EC2/SageMaker?

**Comment by tgaddair** [comment]
Hey @gilinachum, this was released in v0.20.0, supporting all versions of TF / PyTorch we support (TF >= 1.15, PyTorch >= 1.2).  

We have a guide you can check out [here](https://horovod.readthedocs.io/en/stable/elastic_include.html).  There are also a number of examples [here](https://github.com/horovod/horovod/tree/master/examples/elastic).

You can run this on AWS or any environment, including bare metal.  However, we do not currently provide a launcher to automatically provision the job.  This will change once #2291, which will allow you to use Ray to provision an Elastic Horovod job in any environment where Ray is supported.
