### ISSUE TITLE
Installation issue with MXNet built from source - No such file or dictionary <dmlc/base.h>

### ISSUE THREAD

**Issue by shuo-ouyang** [horovod/horovod#1910]
**Environment:**
1. Framework: MXNet
2. Framework version: 1.4.0
3. Horovod version: 0.19
4. MPI version: openmpi-2.1.6
5. CUDA version: CUDA 8.0
6. NCCL version: None
7. Python version: 2.7.9
8. OS and version: centos 7.6
9. GCC version: 4.8.5

**Your question:**

Hi, I am installing horovod for mxnet, which is built from source, using `pip install horovod-0.19.1.tar.gz` on my private cluster, and I get following error during installation. The issue can be partially sovled by changing relative path `dmlc/base.h` to absolute path `../../3rdparty/dmlc-core/include/dmlc/base.h`, but there are too many headers to change it manually one by one. Are there any approachs to cope with it?

```
In file included from horovod/mxnet/mpi_ops.h:19:0,
                     from horovod/mxnet/mpi_ops.cc:20:
    /PARA/mxnet-1.4.0/python/mxnet/../../include/mxnet/base.h:32:23: fatal error: dmlc/base.h: No such file or directory
     #include "dmlc/base.h"
                           ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/WORK/app/Python/2.7.9-fPIC/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-YJNzVX/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-uKO7cH/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-YJNzVX/
```

**Comment by tgaddair** [comment]
@apeforest @romerojosh is there any guidance on how best to install Horovod + MXNet built from source?

**Comment by shuo-ouyang** [comment]
Solved it by adding all header files into system environment variable `CPLUS_INCLUDE_PATH`.
