### ISSUE TITLE
ValueError: Feature column count 5 must equal model inputs count 1

### ISSUE THREAD

**Issue by csdingbin** [horovod/horovod#1911]
**Environment:**
1. Framework: PyTorch
2. Framework version:1.3.1
3. Horovod version:0.19

I used the horovod on spark to run pytorch model. In my pytorch model forward, there had 5 inputs.
The code like below:

def forward(self,input1,input2,input3,input4,input5):

I set the feature_cols=['input1','input2','input3','input4','input5']

torch_estimator = hvd.TorchEstimator(store=store,
                                     model=model,
                                     optimizer=optimizer,
                                     loss=lambda input, target: loss(input, target.long()),
                                     input_shapes=[[5,1]],
                                     feature_cols=['input1','input2','input3','input4','input5'],
                                     label_cols=['label'],
                                     batch_size=batch_size,
                                     epochs=num_epoch,
                                     verbose=1)
    
torch_model = torch_estimator.fit(train_df).setOutputCols(['label_prob'])

And I run the above code, it appeared the error of "ValueError: Feature column count 5 must equal model inputs count 1"

The data like this
![Capture](https://user-images.githubusercontent.com/52478962/80303787-f91de280-87e4-11ea-9f6a-5b20ff822b93.PNG)

Is there anyone know how to solve this issue?

**Comment by tgaddair** [comment]
Hey @csdingbin, apologies for the unclear error message.  What it's trying to say is that the number of `input_shapes` must equal the number of `feature_cols`.  In your case, it looks like you need to set `input_shapes=[[5,1], [1], [1], [1], [1]]`.

**Comment by csdingbin** [comment]
@tgaddair Thanks for your reply. You are right. But I got another issue

Exception: Timed out waiting for Spark tasks to start. Please check that you have enough resources to run all Horovod processes. Each Horovod process runs in a Spark task. You may need to increase the start_timeout parameter to a larger value if your Spark resources are allocated on-demand.

I used Spark-submit(Spark2.4.4 on Yarn) to submit the python file. Am I right? Or need I use other methods to run the python file? such as python shell, mpirun. Do you have any suggestion and do you know how to solve this issue?
Thank you very much.

**Comment by tgaddair** [comment]
Hey @csdingbin, can you try setting `TorchEstimator(num_proc=...)` epxlicitly?  It might be that the default parallelism is asking for too many resources.
