### ISSUE TITLE
hvd.load_model not properly wrapping optimizer in tf.keras 1.15

### ISSUE THREAD

**Issue by sparticlesteve** [horovod/horovod#1920]
**Environment:**
1. Framework: tf.keras
2. Framework version: TF 1.15.0
3. Horovod version: 0.19.0
4. MPI version: cray-mpich/7.7.10
5. CUDA version: n/a
6. NCCL version: n/a
7. Python version: 3.7.4
8. OS and version: Cray linux based on SLES 15
9. GCC version: 7.3.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Oui
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? n/a
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? n/a
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Oui oui

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I've been noticing bad training results when resuming from checkpoint with `hvd.load_model`. I tracked it down to diverging worker models, and noticed that my model optimizers from `hvd.load_model` were not properly wrapped in the horovod DistributedOptimizer. I believe it's a bug in this logic that determines all optimizer classes to wrap right here:
https://github.com/horovod/horovod/blob/d1b13ec131af22b31d0ba999dae15a29991cfeae/horovod/_keras/__init__.py#L113

This part:

    horovod_objects = {
        subclass.__name__.lower(): wrap_optimizer(subclass)
        for subclass in keras.optimizers.Optimizer.__subclasses__()
        if subclass.__module__ == keras.optimizers.Optimizer.__module__
    }

This check on the subclass module matching Optimizer module doesn't work in TF 1.15. E.g., for the SGD optimizer, the class module (the LHS) is actually

    In [9]: tensorflow.python.keras.optimizer_v2.gradient_descent.SGD.__module__
    Out[9]: 'tensorflow.python.keras.optimizer_v2.gradient_descent'

whereas the RHS is

    In [10]: tf.keras.optimizers.Optimizer.__module__
    Out[10]: 'tensorflow.python.keras.optimizer_v2.optimizer_v2’

I have for now implemented a workaround in my code that just removes the module equality comparison and confirm that my optimizers are correctly being wrapped in DistributedOptimizer.

I don't have a suggestion for how to fix this in Horovod. Presumably the module paths are inconsistent across Keras and TF versions :(

**Comment by tgaddair** [comment]
Thanks for raising this issue, @sparticlesteve.  I'll take a look this.  Presumably, this means our load_model test is not behaving correctly (or at least missing some edge cases).

**Comment by tgaddair** [comment]
Hey @sparticlesteve, I think #1935 should address this issue.  Please give it a shot when you have some time and let us know how it goes.  Thanks.

**Comment by sparticlesteve** [comment]
Awesome, @tgaddair , thanks for the quick turnaround!
I will report back when I can.
