### ISSUE TITLE
 support for xPU 

### ISSUE THREAD

**Issue by wuchangping** [horovod/horovod#1924]
Dear,
Is there any plan for adding the addons or contrib folder  and MACRO XPU to support xPU, for example: Google TPU, or xxxx xPU, or any other deep learning processors?

Jeff Wu

**Comment by tgaddair** [comment]
Hey @wuchangping, there is interest in adding other deep learning accelerators.  Some (like TPU) do not lend themselves to the allreduce model of gradient aggregation across devices.  However, others (like Intel Habana) might be good candidates.

Was there a particular use case you had in mind?

**Comment by wuchangping** [comment]
hi @tgaddair ，Sorry for late reply.

Yes, in addition to GPU / CPU / TPU, there are many start-up AI chip companies, which are also part of  AI ecosystem.
For example, current horvord / tensorflow supports CPU / GPU. When tensorflow needs to be supported, different macros have to be added to isolate the code. For example, TPU.NPU, XXU, etc., This approach destroys the beauty of the code and is difficult to maintain.
Therefore,  hope that there can be a general macro or similar plug-in design ideas, which can be used as a plug-in for other chips.

Otherwise, different chip companies need to maintain their own branches of Horovod, which is a very painful thing, and is not conducive to the establishment of horovod software ecology.

Thank you very much!

Jeff Wu

**Comment by wuchangping** [comment]
Closed
