### ISSUE TITLE
Can't find routable network interface when using Horovod Docker on two machines

### ISSUE THREAD

**Issue by Inception95** [horovod/horovod#1934]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Keras
2. Framework version: 2.3.1 (TensorFlow 1.14.0 backend)
3. Horovod version: 0.18.2
4. MPI version: 1.10.2
5. CUDA version: 10.0
6. NCCL version: 2.4.8
7. Python version: 3.6.8
8. OS and version: Ubuntu 18.04 (Docker), Ubuntu 16.04 (Host)
9. GCC version: 

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
Yes, similar issue: https://github.com/horovod/horovod/issues/1068, tried to add --start-timeout 300 but still didn't work.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
Yes, but my passwordless ssh between the two machines is fine.
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
Yes, I followed this site to run training script.
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?
I checked but no.

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

Hi, thanks for your great contribution!

I used to use Horovod training image classification task on two machines with 16 GPUs (CentOS 7), now I try to do it on Ubuntu but failed. I am using Horovod Docker to run the task, when I run the task on one machine using Docker, it went well, but when running it on two machines (already set the passwordless ssh), it shows:

`horovod.run.common.util.network was unable to connect to horovodrun driver on any of the following address.`

The command I used inside the docker after set the worker "sleep infinitely" and open the 12345 port is: 
`horovodrun --verbose -np 2 -H localhost:1,worker-ip:1 --start-timeout 300 -p 12345 python keras_mnist.py`

it shows:
```
Filtering local host names.
Remote host found: worker-ip
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Lanuched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
```

Now it just hangs here for about 10 mins, but firstly it shows:
horovod.run.common.util.network was unable to connect to horovodrun driver on any of the following address.
one possible caused of this problem is that horovodrun currently requires every host to have at least one routable network interfaces with the same name across all of the hosts. You can run "ifconfig -a" on every host and check for the common routable interface.

I ran the "ifconfig -a" on two machines and their interfaces have the same name (I trained on the aws instances and asked the support center to check the network status, it seems fine). I also try to reproduce this training on CentOS instances but this problem shows again.

Is there any possible reasons to my situation? Thanks in advance!

**Comment by tgaddair** [comment]
Hey @Inception95, can you share your results from running `ifconfig -a` here?  If you know which network interface you need to use, you can provide it manually using `horovodrun --nic`.

**Comment by Inception95** [comment]
Hi @tgaddair, sure. Here is the screenshot of "ifconfig -a" of the two machines I use:
<img width="802" alt="ifconfig_info" src="https://user-images.githubusercontent.com/56369917/81024220-a0bf9400-8e27-11ea-88a2-17de745d8aaa.png">
Please let me know if any else is needed.

**Comment by tgaddair** [comment]
Looks like ens3 should be the right interface.  Can you try using `mpirun` without `horovodrun` following [these](https://github.com/horovod/horovod/blob/master/docs/mpirun.rst) instructions, and let us know if it works.

cc @abditag2

**Comment by Inception95** [comment]
Hi @tgaddair there, here are my trying:

try1(use "Custom SSH ports" section example): mpirun -np 2 --allow-run-as-root -H localhost:1,server1:1 -bind-to none -map-by slot -mca plm_rsh_args "-p 12345" -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python examples/keras_mnist.py

try2(exclude lo and docker0): mpirun -np 2 --allow-run-as-root -H localhost:1,server1:1 -bind-to none -map-by slot -mca plm_rsh_args "-p 12345" -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x NCCL_SOCKET_IFNAME=^lo,docker0 -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude lo,docker0 python examples/keras_mnist.py

try3(exclude lo,docker0 and other 2 interface but ens3): mpirun -np 2 --allow-run-as-root -H localhost:1,server1:1 -bind-to none -map-by slot -mca plm_rsh_args "-p 12345" -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x NCCL_SOCKET_IFNAME=^lo,docker0 -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude lo,docker0 python examples/keras_mnist.py

but all trying shows this at first:
![image-20200505231444053](https://user-images.githubusercontent.com/56369917/81144357-b8cb0c80-8f28-11ea-92ab-067ca007de06.png)

after hangs about 2 mins, it shows:
![image-20200505231634026](https://user-images.githubusercontent.com/56369917/81144382-c7192880-8f28-11ea-9f17-f0e548a33401.png)

any ideas?

Thanks for your time.

**Comment by abditag2** [comment]
It seems that the workers are unable to connect to the Horovodrun server. Do your AWS machine allow incoming traffic over ports in the range of `min_port = 1024,    max_port = 65536`?

**Comment by Inception95** [comment]
Thanks! @abditag2 I thought the port 12345 is the only inbound port I need to open besides ssh 22 (same as the horovod docker example), it works now after I allow all traffic inbound to my server1 node. I think I can close the issue now.

**Comment by huwenyue** [comment]
I also met such problem: I use horovodrun in server1 to control server2, but it doesn't work and shows timeout.
horovodrun -np 4 -H server2:4 --autotune --binding-args="-bind-to numa -map-by numa" --mpi-args="--report-bindings" --start-timeout 600 --verbose python train.py 
But when I use mpirun and when use the server2 to control server1, it works. Why?

**Comment by Snoeprol** [comment]
Is there any updates on this?

I have the following: 
2 docker containers: both can ssh into each other on two different computers on the same local network.

iptables tells me

```
root@68a803e7c073:/horovod/examples# iptables -L
Chain INPUT (policy ACCEPT)
target prot opt source destination
Chain FORWARD (policy ACCEPT)
target prot opt source destination
Chain OUTPUT (policy ACCEPT)
target prot opt source destination
```

On both nodes. 

There is no firewall on the nodes on which the docker runs either.

...
