### ISSUE TITLE
Error while trying to install in virtual environment

### ISSUE THREAD

**Issue by anweshpanda** [horovod/horovod#1937]
Hi,
I am trying to install horovod with tensorflow 1.14 in virtual environment. I am following the instructions from the link below
https://horovod.readthedocs.io/en/latest/contributors_include.html
----------------------------------------------------------------------------------------------------------------
But while executing  the command : HOROVOD_WITH_TENSORFLOW=1 python setup.py install 
I am getting the following error
-------------------------------------------------------------------------------------------------------------------------
ERROR: Command errored out with exit status 1:
   command: /mnt/lustre/cds/cdsanwesk/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-io6xod58/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-io6xod58/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1xwa_d5j
       cwd: /tmp/pip-wheel-io6xod58/psutil/
  Complete output (46 lines):
  No supported cpu target is set, CRAY_CPU_TARGET=x86-64 will be used.
  Load a valid targeting module or set CRAY_CPU_TARGET
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
  creating build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/psutil
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=570 -DPSUTIL_LINUX=1 -I/mnt/lustre/cds/cdsanwesk/env/include -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
  psutil/_psutil_common.c:9:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/lustre/cds/cdsanwesk/env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmps6ts_v7e', '--quiet', 'psutil']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 1633, in <module>
    scripts=['bin/horovodrun'])
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    _install_setup_requires(attrs)
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/setuptools/dist.py", line 698, in fetch_build_eggs
    replace_conflicting=True,
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1078, in obtain
    return installer(requirement)
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/mnt/lustre/cds/cdsanwesk/env/lib64/python3.6/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/mnt/lustre/cds/cdsanwesk/env/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmps6ts_v7e', '--quiet', 'psutil']' returned non-zero exit status 1.
-------------------------------------------------------------------------------------------------------------------------------
I tried but could not find a solution for virtual environmment specifically. 
Can someone please help..??

**Comment by tgaddair** [comment]
Hey @anweshpanda, looks like you may be missing `libpython3.6-dev`.  Could you take a look at https://github.com/pwndbg/pwndbg/issues/356 and try running through the suggestions there?

**Comment by anweshpanda** [comment]
Hi @tgaddair , thanks for the reply. But the solution says to install libpython system wide using sudo. But I am working in a cluster and do not have sudo permission. Is there any way out?

**Comment by anweshpanda** [comment]
I tried to install with conda and it worked....
