### ISSUE TITLE
Horovod issue with MXNet 1.6 and Cuda 10.x

### ISSUE THREAD

**Issue by pmthahir** [horovod/horovod#1938]
After building horovod with MXNet 1.6 and Cuda 10.x, when importing 'horovod.mxnet' I get the following issue
  File "horovod/mxnet/__init__.py", line 25, in <module>
    from horovod.mxnet.mpi_ops import allgather
  File "horovod/mxnet/mpi_ops.py", line 29, in <module>
    _basics = _HorovodBasics(__file__, 'mpi_lib')
  File "horovod/common/basics.py", line 27, in __init__
    self.MPI_LIB_CTYPES = ctypes.CDLL(full_path, mode=ctypes.RTLD_GLOBAL)
  File "python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: horovod/mxnet/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

Here is what I found doing LD_DEBUG
The symbol cudaSetupArgument is referenced in NCCL library and with Cuda9.x, the libcudart.so file is resolved to find this symbol. But in Cuda10.x it is not able to find the symbol

Would appreciate any help with regards to this

Thanks,
Thahir

**Comment by chandana1332** [comment]
@apeforest any suggestions on how to resolve this issue?

**Comment by apeforest** [comment]
@pmthahir Could you provide more information to reproduce?
e.g. did you build mxnet/horovod from pypi or source? Which version etc.

**Comment by rondogency** [comment]
It is solved. The reason is we were using a lemon NCCL binary, which were built against a very old CUDA (version < 7.0). This cudaSetupArgument is an API deprecated in CUDA 7.0, and the binary compatibility is up until 10.0. Since we were running with 10.1, this issue suddenly pops up.
