### ISSUE TITLE
How does broadcast_parameters() work?

### ISSUE THREAD

**Issue by abcinje** [horovod/horovod#1940]
### **Framework: PyTorch**

Hello.

I wonder how `broadcast_parameters()` works when using Horovod with PyTorch.
The function is defined [here](https://github.com/horovod/horovod/blob/master/horovod/torch/__init__.py#L452).

Looking at `pytorch_mnist.py` in `examples` directory, the function is called [here](https://github.com/horovod/horovod/blob/master/examples/pytorch_mnist.py#L173).
And the first argument, `model.state_dict()` has an OrderedDict type.

Is it possible that the others except the root node update their parameters when passing an object with that type? I thought that the first argument should be `model` or something else, and there should be an update process such as `model.load_state_dict()`.

I think I've missed something. When do the other nodes initialize their parameters?

Thanks in advance.

**Comment by tgaddair** [comment]
Hey @abcinje, before we call `broadcast_parameters()`, every node has random weight initialization.  Then, when we call `broadcast_parameters()`, all the weights from the root node (rank 0) are used to set the values of the other nodes.  The `state_dict` contains all the tensors of the model, and when we broadcast them, every other worker node can set its model tensors to the broadcasted values.

**Comment by abcinje** [comment]
@tgaddair Thank you for your reply.
What I was wondering is actually the underlying details about how the function works (how the function does in-place update of `model.state_dict()` for the other nodes), but I resolved the problem with a workaround. I'm going to close the issue.
