### ISSUE TITLE
How to restore a tensorflow checkpoint while using hvd

### ISSUE THREAD

**Issue by czs1886** [horovod/horovod#1942]
When I use the restorer of tensorflow, it gave me 'You must feed a value for placeholder tensor 'keep_prob' with dtype float' error.' 
Is there a special way to restore a checkpoint file when using hvd?

**Comment by tgaddair** [comment]
Hey @czs1886, there shouldn't be any need for special handling.  This issue also came up in #77, and turned out to be unrelated the Horovod directly.  Could you take a look at that thread and see if your problem has a similar cause?
