### ISSUE TITLE
the cluster of horovod is slow 

### ISSUE THREAD

**Issue by Matrixsun** [horovod/horovod#196]
my cluster is 8 server , each server has 4 GPU , when I start the cluster running resnet-50 , after some time, the cluster became slow

**Comment by alsrgv** [comment]
@Matrixsun, how are you measuring slowness?  In terms of images per second?

**Comment by Matrixsun** [comment]
yes.  at first,  10  iterations(about 1000 images) takes less than 3 seconds. 10  iterations(about 1000 images)  would take 7-17s when the cluster is slow.

**Comment by alsrgv** [comment]
@Matrixsun, are you using real data or synthetic data?  Can you confirm whether your data pipeline is always full?

**Comment by alsrgv** [comment]
@Matrixsun, what GPUs are you using and what's your network interface bandwidth?

**Comment by Matrixsun** [comment]
My GPU is P40, network is RoCe 40Gb.

**Comment by alsrgv** [comment]
@Matrixsun, that combination should work pretty well.  Can you try running [benchmarks](https://github.com/uber/horovod/blob/master/docs/benchmarks.md) with synthetic and real data to see if you get better performance?
