### ISSUE TITLE
run yolo3(tf.keras implemented) with cpu, after first epoch, the process will exist.

### ISSUE THREAD

**Issue by 836304831** [horovod/horovod#1961]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)Tensorflow
2. Framework version:1.12.0
3. Horovod version:0.19.0
4. MPI version:4.0.0
5. CUDA version:None
6. NCCL version:None
7. Python version:3.6.9
8. OS and version: ubuntu18.04
9. GCC version: 7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

run examples is ok：
`horovodrun -np 2 -H localhost:2 python tensorflow_keras_mnist.py`

but when run yolo3，after first epoch， the process will exist， error as：
![image](https://user-images.githubusercontent.com/8056281/82209940-be6d1d00-9940-11ea-9b89-72333174148e.png)

**Comment by tgaddair** [comment]
Hey @836304831, can you share the full log in a gist or pastebin?  This error message just says that there was some kind of error, possibly a user error.  The true error message is usually above this.

**Comment by 836304831** [comment]
The problem is out of memory but the print error has no indicte the naturely reason. 
I will close this issue.
