### ISSUE TITLE
Horoved install with NCCL

### ISSUE THREAD

**Issue by lljjgg** [horovod/horovod#1962]
I want to use Horovod on GPU with nccl.But for some special reasons, I can only provide static libraries of nccl. want to know if I can install horovod in this case. if feasible ,What should I do.Looking forward to your reply.Thanks.

**Comment by DEKHTIARJonathan** [comment]
Please check the documentation: https://github.com/horovod/horovod/blob/master/docs/install.rst#environment-variables

**HOROVOD_NCCL_LINK** - {SHARED, STATIC}. Mode to link NCCL library. Defaults to STATIC for CUDA, SHARED for ROCm.

**Comment by lljjgg** [comment]
Thank you for your reply.I add environment variables and compile with setup.py.The compile line is “HOROVOD_NCCL_LINK=STATIC HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/usr/local python ./setup.py install”. But there are still errors that "ImportError: libnccl.so.2: cannot open shared object file: No such file or directory".I think that I only use static libraries,Maybe is a problem with my compile line.Do you know the reason for the error?Looking forward to your reply.Thanks.
