### ISSUE TITLE
ResNet50 training using Pytorch is heavily communication bound on CPUs.

### ISSUE THREAD

**Issue by mshaikh786** [horovod/horovod#1976]
**Environment:**
1. Framework: (Pytorch
2. Framework version: 1.3.1a
3. Horovod version: 0.19.0
4. MPI version: Cray-mpich (GNU programming environment)
5. CUDA version: None
6. NCCL version: None 
7. Python version: Intel Python 3.7.3
8. OS and version: CLE7 UP05 (Based of SLES15)
9. GCC version: GNU 8.3.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?  Yes

**Your question:**
I have built the software stack on CrayXC40 with Cray Aries interconnect. I am trying to scale out the Imagenet training example provided in Horovod examples (pytorch_imagenet_resnet50.py). 
However many nodes I attempt on, the training is heavily communication bound and most of the time is being spent in MPI_Allreduce. I profiled the training and it appears that approximately 10% of the time is spent in computation (most of that is memory access too), the rest in MPI communication. I/O appears to be insignificant too (I experimented on both  Luster and local storage on each node). 
I played a bit with batch size from 32 to 1024 and the profile remains pretty much the same. 
Horovod was not built with OpenMPI so horovodrun is not being used as a launcher. Instead, the job is launched using srun and cpu-bind=cores.

My question is whether this is an expected behaviour? Is there a CPU benchmark  available for training that I can use as reference?

**Comment by tgaddair** [comment]
Hey @mshaikh786, in this case, the limiting factory may be your network bandwidth.  How many nodes are you using, and what is the network bandwidth on your environment?

**Comment by mshaikh786** [comment]
Hi @tgaddair 
The theoretical bandwidth of CrayXC40 interconnect is of the order of 14GB/s. Here is the OSU microbenchmark (bidirectional bandwidth) between two MPI ranks, one on each node:
# OSU MPI Bi-Directional Bandwidth Test v5.6.2
# Size      Bandwidth (MB/s)
1                       1.86
2                       3.69
4                       7.32
8                      15.03
16                     30.84
32                     61.75
64                    118.98
128                   237.28
256                   442.28
512                   892.87
1024                 1325.42
2048                 1659.36
4096                 2039.40
8192                 5337.89
16384                9960.47
32768               11494.40
65536               12944.47
131072              13790.76
262144              14261.50
524288              14331.68
1048576             14367.35
2097152             14027.48
4194304             12734.43
