### ISSUE TITLE
[common_runtime/scoped_allocator_mgr.cc:81] Failed to find instance 32581 in container 6 on /job:localhost/replica:0/task:0/device:CPU:0

### ISSUE THREAD

**Issue by sunnyWangGirl** [horovod/horovod#1978]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
Tensorflow-cpu 1.8.0
2. Framework version:
1.8.0
3. Horovod version:
0.19.2
4. MPI version:
openmpi3.1.2
5. CUDA version:
none
6. NCCL version:
none
7. Python version:
none
8. OS and version:
ubuntu14.04  and ubuntu16.04
9. GCC version:
4.9.4
**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? 
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? yes

**Your question:**
Please ask your question here.

Hello,everyone.I want to run horovod in two servers without gpu(only cpu).I install horovod in physical machine not in Docker.I Just run command as follows.
server1:ubuntu14.04,its name:PowerEdge-R630,tensorflow1.8.0 in anaconda3,horovod0.19.2
server2:ubuntu16.04,its name: PowerEdge-R220,tensorflow1.8.0 in anaconda3,horovod0.19.2

` mpirun -np 2     -H server1:1,server2:1     -bind-to none -map-by slot     -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH     -mca pml ob1 -mca btl ^openib     -mca btl_tcp_if_include 10.108.63.77/22     /home/ipoc345/anaconda3/envs/figtensorflow/bin/python ~/myshare/untitled/horovod_demo.py`

but error occurs.

>  INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2020-05-23 02:45:02.835756: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from ./checkpoints/model.ckpt-1
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Graph was finalized.
2020-05-23 14:44:52.471384: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
2020-05-23 14:44:56.654525: F tensorflow/core/common_runtime/scoped_allocator_mgr.cc:81] Failed to find instance 32581 in container 6 on /job:localhost/replica:0/task:0/device:CPU:0
[ipoc345-PowerEdge-R630:77232] *** Process received signal ***
[ipoc345-PowerEdge-R630:77232] Signal: Aborted (6)
[ipoc345-PowerEdge-R630:77232] Signal code:  (-6)
[ipoc345-PowerEdge-R630:77232] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340)[0x7f456ab3b340]
[ipoc345-PowerEdge-R630:77232] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39)[0x7f4569e86f79]
[ipoc345-PowerEdge-R630:77232] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f4569e8a388]
[ipoc345-PowerEdge-R630:77232] [ 3] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so(+0x3be2954)[0x7f45558ef954]
[ipoc345-PowerEdge-R630:77232] [ 4] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(+0x910018)[0x7f4551940018]
[ipoc345-PowerEdge-R630:77232] [ 5] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow16ThreadPoolDevice18GetScopedAllocatorENS_19AllocatorAttributesEx+0x32)[0x7f45519492f2]
[ipoc345-PowerEdge-R630:77232] [ 6] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow15OpKernelContext13get_allocatorENS_19AllocatorAttributesE+0x37)[0x7f4551459b37]
[ipoc345-PowerEdge-R630:77232] [ 7] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow15OpKernelContext15allocate_tensorENS_8DataTypeERKNS_11TensorShapeEPNS_6TensorENS_19AllocatorAttributesERKNS_20AllocationAttributesE+0x48)[0x7f4551459fd8]
[ipoc345-PowerEdge-R630:77232] [ 8] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so(_ZN10tensorflow15OpKernelContext19allocate_persistentENS_8DataTypeERKNS_11TensorShapeEPNS_16PersistentTensorEPPNS_6TensorENS_19AllocatorAttributesE+0x80)[0x7f455145a630]
[ipoc345-PowerEdge-R630:77232] [ 9] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so(+0x8cf57)[0x7f4549c02f57]
[ipoc345-PowerEdge-R630:77232] [10] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so(_ZN7horovod6common19FusionBufferManager16InitializeBufferEliSt10shared_ptrINS0_9OpContextEEiSt8functionIFvvEES7_+0x10c)[0x7f4549ba958c]
[ipoc345-PowerEdge-R630:77232] [11] /home/ipoc345/anaconda3/envs/figtensorflow/lib/python3.5/site-packages/horovod/tensorflow/mpi_lib.cpython-35m-x86_64-linux-gnu.so(+0x4411c)[0x7f4549bba11c]
[ipoc345-PowerEdge-R630:77232] [12] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9de9e)[0x7f4550d83e9e]
[ipoc345-PowerEdge-R630:77232] [13] /lib/x86_64-linux-gnu/libpthread.so.0(+0x8182)[0x7f456ab33182]
[ipoc345-PowerEdge-R630:77232] [14] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f4569f4b30d]
[ipoc345-PowerEdge-R630:77232] *** End of error message ***
An MPI communication peer process has unexpectedly disconnected.  This
usually indicates a failure in the peer process (e.g., a crash or
otherwise exiting without calling MPI_FINALIZE first).
Although this local MPI process will likely now behave unpredictably
(it may even hang or crash), the root cause of this problem is the
failure of the peer -- that is what you need to investigate.  For
example, there may be a core file that you can examine.  More
generally: such peer hangups are frequently caused by application bugs
or other external events.
      Local host: PowerEdge-R220
      Local PID:  31080
      Peer host:  (null)
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
mpirun noticed that process rank 1 with PID 77232 on node server1 exited on signal 6 (Aborted).

I found this error is 
`2020-05-23 14:44:56.654525: F tensorflow/core/common_runtime/scoped_allocator_mgr.cc:81] Failed to find instance 32581 in container 6 on /job:localhost/replica:0/task:0/device:CPU:0`
I am new for horovod.I have no idea how to solve this problem.I just wanna run horovod in two servers in only-cpu.PPPlease help me.

the code I run is listed below
[https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist.py](url),but remove
`config.gpu_options.allow_growth = True
  config.gpu_options.visible_device_list = str(hvd.local_rank())`

**Comment by sunnyWangGirl** [comment]
@alsrgv Would you mind giving me some ideas?

**Comment by sunnyWangGirl** [comment]
Who can Help me? Best wishes.

**Comment by Young768** [comment]
Maybe you can try upgrading your mpi to 4.0.0.

**Comment by sunnyWangGirl** [comment]
> Maybe you can try upgrading your mpi to 4.0.0.

Hello.I have tried to update mpi version to 4.0.0.the error disappear!!!Thank you very much.
