### ISSUE TITLE
Can't find command horovodrun in docker ?

### ISSUE THREAD

**Issue by Desein-Yang** [horovod/horovod#1986]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TEnsorflow 1.12.0
2. Framework version: 1.12.0 
3. Horovod version: 1.16.0
4. MPI version: 4.8.0
5. CUDA version: 9.0
6. NCCL version: 
7. Python version: 3.5
8. OS and version:
9. GCC version: 5.3.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I have pulled images `horovod/horovod: 0.16.0-tf1.12.0-torch1.0.0-mxnet1.4.0-py3.5 ` from docker hub and run a container of it. 

And horovod with tf in python terminal works but horovodrun command cannot be found.
```bash
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod.tensorflow as hvd

>>> print(hvd.__path__)
['/usr/local/lib/python3.5/dist-packages/horovod/tensorflow']
```

```bash
$ horovodrun -np 4 -H localhost:4 python keras_mnist_advanced.py
bash: horovodrun: command not found
```
When I find horovodrun with `whereis horovodrun` it returns none. And cuda \ nccl paths are all in system path.

How can I solve this problem ? Or the image is broken?

**Comment by tgaddair** [comment]
Hey @Desein-Yang, `horovodrun` was added in v0.18.0 of Horovod.  Are you able to pull a more recent image (for example, v0.19.3)?

**Comment by Desein-Yang** [comment]
> Hey @Desein-Yang, `horovodrun` was added in v0.18.0 of Horovod. Are you able to pull a more recent image (for example, v0.19.3)?

Thank a lot , I use 0.16.0 horovod so I try to use mpirun command with hyperparameters in command to replace horovodrun.
