### ISSUE TITLE
Horovod 19.2 cannot run mpirun --version

### ISSUE THREAD

**Issue by matthewc-gr** [horovod/horovod#2002]
We've just upgraded our horovod version from 0.19.1 to 0.19.2 and we get the below runtime exception while training using Tensorflow 2.2.0. (We also see this in 0.19.4)

We are using spark to schedule horovod jobs using horovod.spark.run and the exception bubbles up from spark. 

Dependencies:
```
horovod==0.19.2
tensorflow==2.2.0 
```

Exception:
```
Was unable to run mpirun --version:
Traceback (most recent call last):
  File "/tmp/spark-b145d01d-da23-4170-89f3-430afe3d3eca/sample_train_tfrecord.py", line 173, in <module>
    trainer.train(train_fn)
  File "/home/matthewc/ml_working_dir/devlibs/mariana/mariana/mariana_trainer.py", line 253, in train
    env=env, )
  File "/home/matthewc/horovod-env/venv/lib/python3.6/site-packages/horovod/spark/runner.py", line 221, in run
    _launch_job(use_mpi, use_gloo, settings, driver, env, stdout, stderr)
  File "/home/matthewc/horovod-env/venv/lib/python3.6/site-packages/horovod/spark/runner.py", line 128, in _launch_job
    settings.verbose)
  File "/home/matthewc/horovod-env/venv/lib/python3.6/site-packages/horovod/run/runner.py", line 692, in run_controller
    mpi_run()
  File "/home/matthewc/horovod-env/venv/lib/python3.6/site-packages/horovod/spark/runner.py", line 126, in <lambda>
    use_mpi, lambda: mpi_run(settings, nics, driver, env, stdout, stderr),
  File "/home/matthewc/horovod-env/venv/lib/python3.6/site-packages/horovod/spark/mpi_run.py", line 53, in mpi_run
    hr_mpi_run(settings, nics, env, command, stdout=stdout, stderr=stderr)
  File "/home/matthewc/horovod-env/venv/lib/python3.6/site-packages/horovod/run/mpi_run.py", line 143, in mpi_run
    raise Exception(_MPI_NOT_FOUND_ERROR_MSG)
Exception: horovod does not find an installed MPI.
Choose one of:
1. Install Open MPI 4.0.0+ or IBM Spectrum MPI or MPICH and re-install Horovod (use --no-cache-dir pip option).
2. Run distributed training script using the standard way provided by your MPI distribution (usually mpirun, srun, or jsrun).
3. Use built-in gloo option (horovodrun --gloo ...).
```

mpirun is on the path and I can call mpirun --version fine on the edge node. 
```
 mpirun --version
mpirun (Open MPI) 4.0.1

Report bugs to http://www.open-mpi.org/community/help/
```

It also looks like the horovod install has mpi as an available controller

```
horovodrun --check-build
Horovod v0.19.4:
Available Frameworks:
    [X] TensorFlow
    [ ] PyTorch
    [ ] MXNet
Available Controllers:
    [X] MPI
    [X] Gloo
Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo
```

Any ideas to what is going on here?

Thanks,

Matt

**Comment by tgaddair** [comment]
Hey @matthewc-gr, I suspect the `PATH` is not getting propagated correctly through the virtual environment, causing the `mpirun` executable not to be found.  

@EnricoMi, do you have any thoughts?

**Comment by EnricoMi** [comment]
@matthewc-gr, can you provide me the exact `horovod.spark.run` call with all arguments from `mariana_trainer.py:253`? Looks like the `PATH` in the `env` argument used to execute `mpirun` on the edge node does not include the location of `mpirun`. Can you please also run `which mpirun` on the edge node?

**Comment by matthewc-gr** [comment]
Sure,

Env: 
```
'PATH': '/home/matthewc/horovod-env/venv/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin',
```
mpirun dir:
```
which mpirun
/usr/bin/mpirun
```
Which looks ok. If I modify the mpi_run.py directly file and add in a call like 
```
print(os.popen(command).read())
```
Then it returns correctly `mpirun (Open MPI) 4.0.1`.

It seems like the call to the tiny_shell_exec is throwing for some reason.

**Comment by EnricoMi** [comment]
@tgaddair can you help me replicate this? I have never seen this and I am only using virtualenv. There are many tests that run `mpirun` through `horovod.spark.run`, all in a virtualenv.

**Comment by EnricoMi** [comment]
@matthewc-gr can you print out the `env` that is used in `horovod.run.mpi_run.py:197`:

            exit_code = safe_shell_exec.execute(mpirun_command, env=env, stdout=stdout, stderr=stderr)

**Comment by EnricoMi** [comment]
Found the problem, `horovod.run.mpi_run._get_mpi_implementation` calls into `tiny_shell_exec.execute` without any env (as you mentioned). I will prepare a fix.

**Comment by EnricoMi** [comment]
Does #2005 fix this issue for you @matthewc-gr, @tgaddair ?

**Comment by matthewc-gr** [comment]
I added the changes locally and still see the error. I can see that the env is properly being propagated down to the safe_shell_exec.py, which still returns an exit code of 1. Have there been any major changes to this file since 19.1?

**Comment by EnricoMi** [comment]
If the problem is really in `safe_shell_exec`, then this would be @tgaddair's call. Can you confirm the `env` passed to `safe_shell_exec` contains a proper `PATH`?

**Comment by matthewc-gr** [comment]
Yep so just before the middleman is created in the execute method of the safe_shell_exec.py I printed out the PATH from the env and it looked like ` {'PATH': '/home/matthewc/horovod-env/venv/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin'...`

**Comment by tgaddair** [comment]
Hey @matthewc-gr, does this error also happen when you run the example spark scripts (like [keras_spark_rossmann_run.py](https://github.com/horovod/horovod/blob/master/examples/keras_spark_rossmann_run.py)?

I noticed in our environment this error was a red herring for a different error that was printed above:

```
File "/usr/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/run/common/util/tiny_shell_exec.py", line 32, in execute
    exit_code = safe_shell_exec.execute(command, env=env, stdout=output, stderr=output)
  File "/usr/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/run/common/util/safe_shell_exec.py", line 181, in execute
    middleman.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

This is caused by not guarding your script with `if __name__ == '__main__':`.  Can you check that the example scripts exhibit the same error?

**Comment by matthewc-gr** [comment]
Hi @tgaddair yes you're right, adding in the if check at the top of my script fixes it. Do we know what change has made this required? Might be worth adding to some docs somewhere (unless it already is!). Thanks so much for looking into it @tgaddair and @EnricoMi

**Comment by tgaddair** [comment]
Hey @matthewc-gr, this was introduced by #1915.  It is a limitation of using Python's multiprocessing "spawn" API, as opposed to fork.  Forking was leading to deadlocks in some situations, which is why the change was made.  We'll update the docs to make this more clear.

Can you clarify if the issue is solved for v0.19.4 with only the added check at the top of your script, or do you also need the fix in #2005 for things to work correctly?

**Comment by EnricoMi** [comment]
@tgaddair can we detect that situation (the missing `if`) and raise a meaningful exception? We should still put #2005 into master.

**Comment by everestas** [comment]
Hey,

I am having the same issue. 

horovod==0.26.1
tensorflow==2.10.0 

In my case, I am running the script in Zeppelin notebook on Spark cluster:
```
def fn(magic_number):
    hvd.init()
    print('Hello, rank = %d, local_rank = %d, size = %d, local_size = %d,magic_number = %d' % (hvd.rank(), hvd.local_rank(), hvd.size(), hvd.local_size(), magic_number))
    return hvd.rank()

import horovod.spark
horovod.spark.run(fn, args=(42,))
```

It will fail with error: 
` Exception: horovod does not find an installed MPI. `

I have tried adding ` if __name__=='__main__' ` statement, but that would be False in notebooks.

**Comment by EnricoMi** [comment]
@everestas did you try `spark.run(fn, args=(42,), use_gloo=True)`?

**Comment by everestas** [comment]
Thanks! use_gloo fixed it for me.

**Comment by EnricoMi** [comment]
Did you mean to use MPI and Horovod just could not find it or is MPI deliberately not installed?

**Comment by everestas** [comment]
I have Zeppelin, Spark master and worker containers. Now, I looked into both Zeppelin and worker containers and I can see that both of them have MPI installed. However, for some reason spark master doesn't have MPI installed and most likely because of that MPI wasn't running. 

By the way, Spark master and worker are using the same images.
