### ISSUE TITLE
Getting different results from using mpirun & horovodrun

### ISSUE THREAD

**Issue by jasonliu747** [horovod/horovod#2006]
**Environment:**
1. Framework: MXNet
2. Framework version: 1.5.0
3. Horovod version: 1.9.4
4. MPI version: 4.0.0
5. CUDA version: 10.0
6. NCCL version: 2.4.7-1+cuda10.0
7. Python version: 3.6
8. OS and version: 18.04.1-Ubuntu
9. GCC version: 7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
When using mpirun, everything is alright. But when I wanna try the --autotune function, I changed my command to horovodrun, it simply didn't work anymore. Here are my commands, please do help me take a look.

`mpirun --allow-run-as-root -np 32 
       -mca pml ob1 
       -mca btl ^openib 
       -bind-to none 
       -map-by slot 
       -x NCCL_IB_DISABLE=1 
       -x NCCL_SOCKET_IFNAME=eth0 
       -x LD_LIBRARY_PATH 
       ./run_dcv_20200603152206.sh`

`horovodrun -np 32
       --mpi-args="--allow-run-as-root -x NCCL_IB_DISABLE=1 -x NCCL_SOCKET_IFNAME=eth0 -x LD_LIBRARY_PATH"
       --binding-args="-bind-to none -map-by slot"
       ./run_dcv_20200603152206.sh`

The only difference I can tell from logs is when using mpirun, it will call `kubectl exec` at the beginning. But when using horovodrun, it would go straight to `make -C dcv clean`.
![image](https://user-images.githubusercontent.com/24452340/83609183-7ab91b00-a5b0-11ea-9dd2-903b6ef6b86c.png)

**Comment by tgaddair** [comment]
Hey @jasonliu747, when using `horovodrun`, can you try removing everything in `--mpi-args`.  All of those should be taken care of by the `horovodrun` script itself.

If you cannot get `horovodrun` to work for whatever reason, you can also enable autotuning using environment variables to `mpirun`: `HOROVOD_AUTOTUNE=1`.

**Comment by jasonliu747** [comment]
Thanks for your reply @tgaddair . I got it working by using environment variables to `mpirun`: `HOROVOD_AUTOTUNE=1`.
FYI, I can't get `horovodrun` working on example script either. Are you able to reproduce it?
![image](https://user-images.githubusercontent.com/24452340/84458218-0f013d00-ac97-11ea-82e1-a33e0b3ebc17.png)

**Comment by tgaddair** [comment]
I have not been able to reproduce it.  One thing you could try is running `horovodrun` with the `--verbose` flag, so we can see the actual `mpirun` command that's being called.  But if using `mpirun` with `HOROVOD_AUTOTUNE=1` is working, then that's okay too.

**Comment by jasonliu747** [comment]
Will stick with mpirun with HOROVOD_AUTOTUNE=1, thanks Travis.

**Comment by RookieoftheYear** [comment]
hi,@tgaddair ，i used `horovodrun `instead of `mpirun`,but now i want to change some options of `mpirun`  command like setting `-mca btl_openib_receive_queues P,128,32:P,2048,32:P,12288,32:P,131072,32`, could please tell me how to do it within `horovodrun `,thx!

**Comment by tgaddair** [comment]
Hey @RookieoftheYear, as mentioned in the other thread, you can set `--mpi-args` to provide additional arguments to `mpirun` through `horovodrun`.
