### ISSUE TITLE
Is there a way to dynamically turn off/on the timeline without killing application ?

### ISSUE THREAD

**Issue by Vikas-kum** [horovod/horovod#2008]
Can we turn off the timeline profiler by setting env config. Currently, if I have to profile, I turn the profiler on it writes huge amount of logs and then I have to kill my application. 
Rather than killing application, I would like to dynamically turn it off, by setting a flag or config in a file. 

**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

**Comment by weberxie** [comment]
good point! we  are also investigating this feature.

**Comment by Vikas-kum** [comment]
Any thoughts on this?

**Comment by tgaddair** [comment]
Hey @Vikas-kum, this is a great idea.  We do not have a way to do this currently, but I can think of a few ways we might accomplish this.  Let me know what makes the most sense to you:

1. Python API

```
hvd.enable_timeline('/path/to/logfile', mark_cycles=True)
...
hvd.disable_timeline()
```

2. Fixed length timeline

```
horovodrun --timeline-duration-seconds 600 ...
```

3. Shutdown signal / file

```
horovodrun --timeline-shutdown-filename /path/shutdown
```

Then in a separate terminal:

```
touch /path/shutdown
```

I tend to like the idea of a Python API, as it gives the most flexibility to the user to set the exact point the timeline should begin or end.  What do you think?

**Comment by Vikas-kum** [comment]
Thanks @tgaddair 
Yes, I agree with you. Python api would be very useful to start with.

**Comment by Vikas-kum** [comment]
@tgaddair 
Hi Travis, 
Is there any plan on this? I think one simple first implementation can be file based where writer timeline thread can keep on looking for a file and its contents to decide where the profiler is turned on or off. 

while(True):
   read_configuration_file_periodically()
  if disabled():
     continue
  ....
  ...

**Comment by tgaddair** [comment]
Hey @Vikas-kum, I can take a stab at implementing the Python API we discussed in probably a week or two from now.  If you have the time and inclination to work on this before then, contributions are certainly welcome.  In general, I would prefer to go the Python API route over having a config file, as I feel it's easier to control from a user perspective, but open to continue discussing the pros/cons if you'd like.

**Comment by Vikas-kum** [comment]
hi @tgaddair , 
Were you able to take a stab at it?
 I am not very familiar with horovod repository. I can quickly try implementing the solution described [here](https://github.com/horovod/horovod/issues/2008#issuecomment-654371781) 

This is cheaper to implement and would serve the purpose but i agree that pythonic API interface would be more cleaner. Please let me know if you are ok with cheaper solution and I cna go ahead implementing it.

**Comment by tgaddair** [comment]
Hey @Vikas-kum, can you take a look at #2129 and let me know if it works for your use case?

**Comment by Vikas-kum** [comment]
Thanks @tgaddair for working on it. I took a brief look and it looks good. I will take a more closer look tomorrow.
