### ISSUE TITLE
Consistent way to check if horovod is shutdown ?

### ISSUE THREAD

**Issue by vfdev-5** [horovod/horovod#2011]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.4
3. Horovod version: '0.19.3'
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

Is there a consistent way to check if horovod is shutdown ?
For example,
```python
import horovod.torch as hvd
# hvd.rank() => raises ValueError: Horovod has not been initialized; use hvd.init().
hvd.init()
hvd.rank()  # for example gives 0
hvd.shutdown()
hvd.rank()  # still gives 0, however horovod is shutdown and I would expect the same behaviour as before init()
```

**Comment by vfdev-5** [comment]
@tgaddair thank for the answer. Yes, method like `is_initialized` would work. 
You marked the issue as "contribution welcome", what would be a pointer to help with this issue ?

**Comment by tgaddair** [comment]
Thanks for looking into this, @vfdev-5.  I would start by looking at similar functions that expose properties from the C++ layer in Python code in [basics.py](https://github.com/horovod/horovod/blob/master/horovod/common/basics.py#L83).  These Python functions call into C++ functions in [operations.cc](https://github.com/horovod/horovod/blob/master/horovod/common/operations.cc#L713).  A similar function can be written that checks and returns the state of the [initialize_flag](https://github.com/horovod/horovod/blob/master/horovod/common/global_state.h#L45).

**Comment by vfdev-5** [comment]
Right, thanks for the detailed explanation, @tgaddair !
I'll try to implement it and send a PR (being aware of your [CONTRIBUTING.md guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)).
