### ISSUE TITLE
How should I use Horovod if I change the compression strategy during training？

### ISSUE THREAD

**Issue by Tonyhukaifan** [horovod/horovod#2013]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.5
3. Horovod version: 0.18.2
4. MPI version:mvapich2/2.3.2
5. CUDA version: 10.0.130
6. NCCL version:2.4.6
7. Python version: 3.6
8. OS and version: Linux 3.10.0
9. GCC version: 4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
How should I use Horovod if I change the compression strategy during training?
I will change the compression during the training process. In this case, how should I use Horovod？ The pseudo-code is shown below：
```
compression = hvd.Compression.fp16

optimizer = hvd.DistributedOptimizer(optimizer,
                                         named_parameters=model.named_parameters(),
                                         compression=compression,
                                         op=hvd.Adasum if args.use_adasum else hvd.Average)

for epoch in range(0,100):
      if epoch > 50:
             compression = hvd.Compression.none
             How to apply that compression above to the DistributedOptimizer?

      train()
      test()

      .....

```

Anyone could help me to solve this problem? Appreciate for your help!!!

**Comment by tgaddair** [comment]
Hey @Tonyhukaifan, there is a way to do this today, but it comes with a caveat.

Basically, you can set a private property of the optimizer directly:

```
optimizer._compression = hvd.Compression.none
```

The caveat is that you need to be sure that there are no pending allreduce calls that need to be completed, otherwise they will not decompress correctly.  So the full solution would be to do this:

```
optimizer.synchronize()
optimizer._compression = hvd.Compression.none
```

We should also provide this as a standard part of the API, so I've tagged this issue to track that enhancement.

**Comment by Tonyhukaifan** [comment]
Okay, thx for your reply. I will have a try on it.
