### ISSUE TITLE
Multiple trainings within same process without deepcopy

### ISSUE THREAD

**Issue by olimastro** [horovod/horovod#2017]
**Environment:**
1. Framework: (PyTorch)
2. Framework version: 1.4
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

** I am using horovod in a docker https://github.com/horovod/horovod/blob/master/docs/docker.rst
and running on multiple machines. The setup is 2 servers with one gpu each. 

So `nvidia-docker run horovod/horovod:0.19.1-tf2.1.0-torch1.4.0-mxnet1.6.0-py3.6-gpu` I think answers all the questions above.

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
It seems to be impossible to do multiple training within the same process. It seems to crash if some model modifications are happening in-place even though I rebroadcast everything again. I wrote a self containing script emulating the crash and a very simple solution which is deepcopyng the model (pass `--copy` to script). It happens even if there are no mutation to the model. 

`deepcopy` can be annoying if done multiple times so I guess it would nice if there was a way to avoid it. Thanks!

```python
import argparse
from copy import deepcopy

import torch
import torch.nn as nn
import horovod.torch as hvd


class FakeData:
    def __getitem__(self, item):
        return torch.rand(1, 10)

    def __len__(self):
        return 10


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--copy", action='store_true')
    args = parser.parse_args()
    hvd.init()
    torch.cuda.set_device(hvd.local_rank())

    model = nn.Sequential(
        nn.Linear(10, 10),
        nn.Linear(10, 1)
    )
    data = FakeData()

    i = 0
    while i < 10:
        print('training %d' % i)
        # this line can be commented out and the bug is the same
        model[0] = nn.Sequential(nn.Linear(10, 10), nn.Linear(10, 10))
        if args.copy:
            print('copying')
            model = deepcopy(model)

        model.cuda()
        model.train()

        sampler = torch.utils.data.distributed.DistributedSampler(data, num_replicas=hvd.size(), rank=hvd.rank())
        dataloader = torch.utils.data.DataLoader(dataset=data, batch_size=2, sampler=sampler)

        optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)
        optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=model.named_parameters())

        hvd.broadcast_parameters(model.state_dict(), root_rank=0)
        hvd.broadcast_optimizer_state(optimizer, root_rank=0)

        for e in range(2):
            sampler.set_epoch(e)
            for x in dataloader:
                x = x.cuda()
                loss = model(x).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
        i += 1
```

**Comment by tgaddair** [comment]
Hey @olimastro, can you explain your scenario a little bit more?  It's not clear to me why you need to deep copy the model.  In Horovod, we do not run multiple training workers in the same process.  How are you launching `horovodrun`?

**Comment by olimastro** [comment]
It is hard to say in a more concrete way than what I am already showing in the example script above. In other words, I am trying different models in the same program and the way it is built is with inplace modifications to the model, pretty much like what is shown above in the outer while loop. Then there is an inner loop for training. 

`deepcopy` helps because it prevents horovod from crashing at 
```
[1,0]<stderr>:    loss.backward()
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 195, in backward
[1,0]<stderr>:    torch.autograd.backward(self, gradient, retain_graph, create_graph)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 99, in backward
[1,0]<stderr>:    allow_unreachable=True)  # allow_unreachable flag
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 160, in hook
[1,0]<stderr>:    handle, ctx = self._allreduce_grad_async(p)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/__init__.py", line 143, in _allreduce_grad_async
[1,0]<stderr>:    handle = allreduce_async_(tensor_compressed, name=name, op=self.op)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 228, in allreduce_async_
[1,0]<stderr>:    return _allreduce_async(tensor, tensor, name, op)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod/torch/mpi_ops.py", line 127, in _allreduce_async
[1,0]<stderr>:    name.encode() if name is not None else _NULL, true_op)
[1,0]<stderr>:ValueError: Requested to allreduce, allgather, or broadcast a tensor with the same name as another tensor that is currently being processed.  If you want to request another tensor, use a different tensor name. 
```
I would actually like to avoid `deepcopy`. 

`horovodrun` is ran only once exactly like was is told on `docker.rst` except with my servers config of course.

**Comment by olimastro** [comment]
So for anybody looking at this issue there is a work around. Simply reassign this function to the method of the optimizer and clear the backward hooks like this:
```python
def _register_hooks(self):
    self.bw_hook_handles = []
    for param_group in self.param_groups:
        for p in param_group['params']:
            if p.requires_grad:
                p.grad = p.data.new(p.size()).zero_()
                self._requires_update.add(p)
                p_tmp = p.expand_as(p)
                grad_acc = p_tmp.grad_fn.next_functions[0][0]
                h = grad_acc.register_hook(self._make_hook(p))
                self.bw_hook_handles.append(h)
                self._grad_accs.append(grad_acc)

hvd._DistributedOptimizer._register_hooks = _register_hooks
# ...
# in outer loop
for h in optimizer.bw_hook_handles:
    h.remove()
```
From what I understand the hooks are never removed and when recreating another optimizer for the same model object `grad_acc` gets more than one hook and it crashes.
