### ISSUE TITLE
ImportError : Undefined Symbol.

### ISSUE THREAD

**Issue by Tonyhukaifan** [horovod/horovod#2021]
**Environment:**
1. Framework: PyTorch
2. Framework version:1.4.0
3. Horovod version:0.18.2
4. MPI version:3.1.4
5. CUDA version:10.0.130
6. NCCL version:2.4.6
7. Python version:3.7
8. OS and version: CentOS
9. GCC version:5.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/running.rst)?Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?Yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?Yes

**Your question:**
When I have installed the Horovod and get started with an example program, then have an error below:
```
Traceback (most recent call last):
  File "trainer.py", line 16, in <module>
    import horovod.torch as hvd
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Horovod/lib/python3.7/site-packages/horovod/torch/__init__.py", line 35, in <module>
    from horovod.torch.mpi_ops import allreduce, allreduce_async, allreduce_, allreduce_async_
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Horovod/lib/python3.7/site-packages/horovod/torch/mpi_ops.py", line 28, in <module>
    from horovod.torch import mpi_lib_v2 as mpi_lib
ImportError: /GPUFS/nudt_chkwu_2/.conda/envs/Horovod/lib/python3.7/site-packages/horovod/torch/mpi_lib_v2.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

```
and the `ldd ...mpi_lib_v2.cpython-37m-x86_64-linux-gnu.so` print that,
```
$ldd /GPUFS/nudt_chkwu_2/.conda/envs/Horovod/lib/python3.7/site-packages/horovod/torch/mpi_lib_v2.cpython-37m-x86_64-linux-gnu.so 
        linux-vdso.so.1 =>  (0x00007ffdb5b91000)
        libcudart.so.10.0 => not found
        libmpi.so.40 => /app/MPI/openmpi/3.1.4-icc-18.0.1/lib/libmpi.so.40 (0x00002b2a9ec9a000)
        libstdc++.so.6 => /GPUFS/app_GPU/application/anaconda3/5.3.1/envs/HOROVOD/lib/libstdc++.so.6 (0x00002b2a94a43000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b2a9efd4000)
        libgcc_s.so.1 => /GPUFS/app_GPU/application/anaconda3/5.3.1/envs/HOROVOD/lib/libgcc_s.so.1 (0x00002b2a94bb8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b2a9f2d6000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b2a9f4f2000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b2a94a09000)
        libopen-rte.so.40 => /app/MPI/openmpi/3.1.4-icc-18.0.1/lib/libopen-rte.so.40 (0x00002b2a9f8bf000)
        libopen-pal.so.40 => /app/MPI/openmpi/3.1.4-icc-18.0.1/lib/libopen-pal.so.40 (0x00002b2a9fb91000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b2a9fee7000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00002b2aa00ef000)
        libz.so.1 => /lib64/libz.so.1 (0x00002b2aa02f2000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b2aa0508000)
```
Any help is appreciated! Thanks.

**Comment by tgaddair** [comment]
Hey @Tonyhukaifan, is it possible that you installed a different version of PyTorch after you installed Horovod, or that there is a different version of PyTorch in your conda environment from the one that was used to install Horovod?
