### ISSUE TITLE
Horovod slow node detection

### ISSUE THREAD

**Issue by Richie-yan** [horovod/horovod#2026]
When using Horovod for multi-gpu training, sometimes when the scalability is not good, can there be a way to get the communication operator of each gpu to consume time, so as to know which gpu is the current slow node?
I understand that Horovod only sees which GPUs are slow to negotiate on the timeline during negotiation. Can I get the time-consuming communication operator? Or in what way can the currently trained slow node be detected?

**Comment by tgaddair** [comment]
Hey @Richie-yan, good question.  Slow node detection is something we've wanted to add for a while now, but haven't had the time.

There are multiple ways to go about it, but one approach might be to have the coordinator track the timestamp that every tensor is observed from each worker.  Then when the final set is computed for allreduce, it can compare the timestamps to see which worker(s) took the longest to become ready.

That of course only tackles the problem from the "overall" slowness side (which can include a lot of things like dataset imbalance, I/O, etc.).  If your goal is to determine which workers are slow from a NCCL allreduce perspective, that would require a different solution.

@romerojosh do you have some thoughts on this (from either way of looking at the problem)?

**Comment by Richie-yan** [comment]
Okay, got it. So, do you have any suggestions for to determine which workers are slow from a NCCL allreduce perspective? My idea may be that some processing needs to be done on the nccl code side @tgaddair
