### ISSUE TITLE
more GPUs are used than specified

### ISSUE THREAD

**Issue by ChenYang-ChenYang** [horovod/horovod#2028]
horovod version: 0.19.4
NCCL：2.7.3
Open MPI: 4.0.3
Tensorflow: 1.13.1

I have a server with 4 Nvidia GPUs. I ran following command to try to use the first 2 GPUs: 
horovodrun -np 2 -H localhost:2 python examples/tensorflow_mnist.py

But all the 4 GPUs are used when I ran nvidia-smi. Each GPU have two lines and the GPU 0, 1 used more memory than others, 643MiB in two lines. I checked "ps -aef |grep python", there are two python tensorflow_mnist.py processes only.
I think the correct result should be only GPU 0 and 1 are used and each has one line in the nvidia-smi. How to resolve it?

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
.......

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     35165      C   python                                       643MiB |
|    0     35166      C   python                                       135MiB |
|    1     35165      C   python                                       135MiB |
|    1     35166      C   python                                       643MiB |
|    2     35165      C   python                                       135MiB |
|    2     35166      C   python                                       135MiB |
|    3     35165      C   python                                       135MiB |
|    3     35166      C   python                                       135MiB |
+-----------------------------------------------------------------------------+

**Comment by tgaddair** [comment]
Hey @ChenYang-ChenYang, can you try upgrading to TensorFlow 1.15 (and reinstalling Horovod)?  This may be an issue with TensorFlow 1.13.1.

**Comment by ChenYang-ChenYang** [comment]
> Hey @ChenYang-ChenYang, can you try upgrading to TensorFlow 1.15 (and reinstalling Horovod)? This may be an issue with TensorFlow 1.13.1.

@tgaddair I tried to install Tensorflow 1.14 and the issue was gone. So it is Tensorflow 1.13.1 issue. Thanks for the quick response!
