### ISSUE TITLE
SGE parallel environment multi-node training

### ISSUE THREAD

**Issue by albertz** [horovod/horovod#2034]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.14
3. Horovod version: 0.19.4
4. MPI version: Open MPI 1.10.2
5. CUDA version: 10.1
6. NCCL version:
7. Python version: 3.7
8. OS and version: Ubuntu 16.04
9. GCC version:

Our framework: [RETURNN](https://github.com/rwth-i6/returnn)

**Your question:**

In our cluster environment, scheduled via SGE, we used the parallel environment (PE). E.g. `qsub -pe mpi 8 -l gpu=1 ...` would schedule a PE job with 8 slots where each slot would get 1 GPU.

Inside the job, I followed the Horovod docs and used:
```
mpirun -np 8 \
        -bind-to none -map-by slot \
        -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x HOROVOD_TIMELINE -x DEBUG \
        -mca pml ob1 -mca btl ^openib \
        python3 my-tf-training-script.py
```
OpenMPI explicitly supports SGE (see [here](https://www.open-mpi.org/faq/?category=sge)).

This works fine if I run it without PE, i.e. use N GPUs on a single node, like `qsub -l gpu=4 ...`.

For the multi-node case, I think the main problem is that the other nodes of the PE slots are possibly shared by other independent jobs. E.g. a PE slot node has maybe 4 GPUs, and my PE slot gets one of these GPUs, and the other GPUs are occupied by sth else. So setting `gpu_opts["visible_device_list"] = str(hvd.local_rank())` as described in the Horovod docs would only work correct if `CUDA_VISIBLE_DEVICES` was set correctly per slot via `mpirun`. But I don't think `mpirun` does that. (I'm not totally sure, though.)

For reference, what I get then is this TF crash:
```
2020-06-18 09:11:27.365463: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 63 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2020-06-18 09:11:27.488767: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
Fatal Python error: Aborted
```
I found [this](https://github.com/tensorflow/tensorflow/issues/34851), [this](https://github.com/tensorflow/tensorflow/issues/25329) and [this](https://github.com/google/jax/issues/39) related report, but I think in my case the reason is not too low compute capability, but that the GPU is already used by another process (also `GPU:0 with 63 MB memory`...).

I don't think that Horovod is really to blame here, or not sure if it is even related (although my goal is of course to use Horovod here). But I thought I post this anyway here in case other people run into this.

TF is maybe to blame for the hard crash, but I think this is just an artifact, and the real reason is wrong `CUDA_VISIBLE_DEVICES` or wrong `visible_device_list`.

This is maybe due to `mpirun` not handling this correctly?
(Maybe [this](https://github.com/choderalab/yank/issues/269) is also related?)

What can I do?

**Comment by tgaddair** [comment]
Hey @albertz, are you setting `visible_device_list` as shown [here](https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist.py#L152)?

If so, this may be a bug on the TensorFlow side.  Can you try upgrading to TensorFlow 1.15?

**Comment by albertz** [comment]
Yes, we do.
We had to make some changes to our SGE environment to make this possible. It basically sets the correct `CUDA_VISIBLE_DEVICES` on every node. All the other stuff was already working just in the same way as for single node training.
@curufinwe did that. I don't really know what exactly he did do related to MPI or SGE. I just know that some custom script is involved at some point which figures out how to set `CUDA_VISIBLE_DEVICES`. Maybe he can give some pointers?
