### ISSUE TITLE
XLA_GPU or GPU?   tf.config.list_physical_devices('GPU') == None

### ISSUE THREAD

**Issue by Jie-Yuan** [horovod/horovod#2045]
https://github.com/horovod/horovod/blob/master/examples/tensorflow2_keras_mnist.py#L23

![image](https://user-images.githubusercontent.com/20265321/85264932-0df4ba80-b4a4-11ea-9a5d-e22d6c25471c.png)

**Comment by tgaddair** [comment]
Hey @Jie-Yuan, can you clarify your question?  In your environment, it looks like you may want to try `tf.config.experimental.list_physical_devices('XLA_GPU')` instead.
