### ISSUE TITLE
Use multi-core for node in CPU

### ISSUE THREAD

**Issue by darkalexpp** [horovod/horovod#2062]
**Environment:**
1. Framework: keras with tensorflow
2. Framework version: keras 2.1.6 and tensorflow 1.5.0
3. Horovod version: 0.19.4
4. MPI version: openmpi 4.0.4
5. CUDA version: null
6. NCCL version: null
7. Python version: 3.6
8. OS and version: manajro 20.0.3 kernel 5.6
9. GCC version: 8.4

how to use multi core in cpu?
 when i run keras with tensorflow, this only uses 1 core for node

**Comment by tgaddair** [comment]
Hey @darkalexpp, can you provide the `horovodrun` / `mpirun` command you're using?  What kind of CPU are you using, and does it have multiple sockets?

**Comment by darkalexpp** [comment]
I use:
horovodrun -np2 -H 192.168.100.3:1,192.168.100.4 python3.6 lstm.py

Use cpu1: intel core i5 6gen
Use cpu2: intel core pentium
Tensorflow without avx, avx2

Openmpi support multi-theared

I try use mpi4py and work multicore but not combine the 2 cpus in the training
