### ISSUE TITLE
Horovod Timeline ( with TF) 

### ISSUE THREAD

**Issue by whatdhack** [horovod/horovod#2068]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): TF
2. Framework version: 2.1
3. Horovod version: 0.19.4
4. MPI version: 
5. CUDA version: X
6. NCCL version: X
7. Python version: 3.6.9
8. OS and version: Centos 7
9. GCC version: 8.3

**Checklist:** yes
1. Did you search issues to find if somebody asked this question before?   yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? no
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?no
4. Did you check if your question is answered in the [troubleshooting guide] yes(https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Collecting horovod  timeline with the following simple piece of code. 

```
import numpy as np
import tensorflow as tf
import horovod.tensorflow as hvd

# Initialize Horovod
hvd.init()
print ( "rank: ", hvd.rank())
hvd_r=int(hvd.rank())
N=3
for i in range  (100):
    shape = [N]*(i+1)
    test_array=np.full(shape, hvd.rank(), dtype=np.float32)
    y=hvd.allreduce(test_array, op=hvd.mpi_ops.Sum)
    #print("rank {} op of the big array is {} {}".format(hvd_r, test_array, y))
```

with the following simple mpirun command

```
HOROVOD_TIMELINE_MARK_CYCLES=1 HOROVOD_TIMELINE=./tf_hvd_hello_tl.json  mpirun -n 4 -ppn 4 -hosts  localhost  python tf_hvd_hello.py 2>&1 | tee tf_hvd_hello.out
```

I see the following following timeline. Wondering why the  duration between ALLREDUCE is increasing  ( proportional to the size of tensor) ? I think, a related question is what duration does the green/purple ALLREDUCE band exactly represent ? 

![image](https://user-images.githubusercontent.com/12969966/86078202-6dbe0900-ba42-11ea-8150-07909d2099c0.png)

**Comment by tgaddair** [comment]
Hey @whatdhack, the size of the bar corresponds to the time from the beginning of the `MPI_Allreduce` call to the end.  As the size of the tensor increases (as it does each iteration of your loop), then time taken for the Allreduce will increase, because more data needs to be transmitted between the worker processes.

**Comment by whatdhack** [comment]
Thanks, that makes sense.  Why is  the gap between MPI_Allreduce is also increasing proportionately ?
