### ISSUE TITLE
Any Examples about Horovod's broadcast functions?

### ISSUE THREAD

**Issue by golden0080** [horovod/horovod#2070]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)  **Tensorflow**
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version: 
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? **Yes**
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

I'm trying to do a custom Keras callbacks, that would like to use broadcast to synchronize between processes.
However I couldn't find any examples that uses broadcast to sync processes or sending primitive data?
If I understand correctly, horovod can be used together with `MPI4Py`, do you suggest to use `MPI4Py` for the simple process syncing use cases?

**Comment by tgaddair** [comment]
Hey @golden0080, if your goal is to broadcast a plain Python object, then using `mpi4py` is a good option.  Alternatively, if you want to use a pure-Horovod approach (which would work for Gloo as well as MPI), you can base your callback on the (unreleased) [broadcast_object](https://github.com/horovod/horovod/blob/master/horovod/tensorflow/functions.py#L59) function.
