### ISSUE TITLE
question on horovod workflow

### ISSUE THREAD

**Issue by mmmeee1111** [horovod/horovod#2071]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

Hi Horovod experts,

I am looking into horovod code. For tensorflow, EnqueueTensorAllReduce is for framework plugins. in the operation.cc file, EnqueueTensorAllReduce  pushes tensor and message into the tensor_table and queue. If my understanding is correct, RunLoopOnce will perform MPI operations and put back the response. Can you please help me understand the logic behind this? My question is how the RunLoopOnce is informed to perform the Allreduce when the tensor is ready.

**Comment by tgaddair** [comment]
Hey @mmmeee1111, when `EnqueueTensorAllReduce` is called, the tensor is added to a table containing all the ready tensors ("ready" here means ready on a particular worker).  During the background loop (`RunLoopOnce`) there is a step called Negotiation where the workers determine which tensors are ready on all workers (set intersection).  Once the final list of ready tensors is determined, the Allreduce happens, and a callback is made to send the final result back to TensorFlow.  You can find the implementation of this logic in the [Controller](https://github.com/horovod/horovod/blob/master/horovod/common/controller.cc) class.

**Comment by mmmeee1111** [comment]
Hi @tgaddair Thanks for the detailed answer. is it "[response](https://github.com/horovod/horovod/blob/master/horovod/common/controller.cc#L610)" the callback returned by Horovod, so as to send the processed results back to TF?

**Comment by tgaddair** [comment]
The `response` is the set of tensors that are ready for allreduce across all workers.  Processed results are sent back by calling the callback [here](https://github.com/horovod/horovod/blob/master/horovod/common/operations.cc#L310).  We don't need to actually return a buffer of data because the tensors are modified in-place.

**Comment by mmmeee1111** [comment]
Thanks, everything is clear now.
