### ISSUE TITLE
Horovod not recognizing multiple GPUs on Databricks

### ISSUE THREAD

**Issue by mbluestone** [horovod/horovod#2072]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.5.0
3. Horovod version: 0.19.1
4. MPI version: mpirun (Open MPI) 3.0.0
5. CUDA version: 10.1 
6. NCCL version: 2.7.3
7. Python version: 3.7.6
8. OS and version: Ubuntu 18.04.4 LTS
9. GCC version: 7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? It seems to be similar to issue #604 which hasn't been resolved.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? NA
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? NA
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**
I am running Horovod on Databricks Runtime 7.0 ML with 3 Standard_NC24 GPU worker instances and it seems like not all GPUs that are available are being utilized. There are 4 GPUs on each worker, so 12 GPUs in total.

I have been running tests using the following code:
```
import horovod.torch as hvd
from sparkdl import HorovodRunner

def test_fn():
    hvd.init()
    print(hvd.local_rank())
        
hr = HorovodRunner(np=8)
hr.run(test_fn)
```

At one point, the output of this code was:

```
[1,3]<stdout>:1
[1,0]<stdout>:0
[1,1]<stdout>:0
[1,5]<stdout>:2
[1,7]<stdout>:3
[1,4]<stdout>:2
[1,2]<stdout>:1
[1,6]<stdout>:3
```

I then restarted the cluster and the output was:
```
[1,6]<stdout>:2
[1,0]<stdout>:0
[1,3]<stdout>:1
[1,7]<stdout>:2
[1,4]<stdout>:1
[1,1]<stdout>:0
[1,2]<stdout>:0
[1,5]<stdout>:1
```

How come Horovod isn't picking up all of the GPUs available and is doubling/tripling up processes on a few GPUs? Am I doing something wrong here? Is this an issue with HorovodRunner from sparkdl?

I've tried manually reinstalling Horovod but that doesn't seem to change anything. Any help is greatly appreciated!

**Comment by mbluestone** [comment]
I now recognize the difference between `hvd.rank()` and `hvd.local_rank()` which explains the output that I'm getting. However, when training a model using this configuration the system metrics show that only 4 GPUs are being utilized. What could explain this?

**Comment by tgaddair** [comment]
Hey @mbluestone, in your example, you're running with `hr = HorovodRunner(np=8)`, so we would expect that you should be using a total of 8 GPUs / processes.  In the first block of output, those 8 processes were split across all 4 GPUs of 2 different hosts.  In the second block of output, you had processes spread across 3 hosts: 3 GPUs on host-0, 3 GPUs on host-1, and 2 GPUs on host-2.

When you say only 4 GPUs are being used, how does that relate to how the processes are being allocated?  In other words, are you seeing 8 processes running on a single (4 GPU) host?  If so, that sounds a like a problem with the cluster configuration (`HorovodRunner` being unable to discover more than one host).

**Comment by mbluestone** [comment]
Hey @tgaddair thanks for getting back to me! Turns out the GPU utilization is occurring exactly as it should, and the issue we were having is with Comet.ml and their system metrics tracking. I'll go ahead and close this issue - thanks!
