### ISSUE TITLE
Horovod Elasticity Architecture and Components

### ISSUE THREAD

**Issue by vibhatha** [horovod/horovod#2076]
I have a question about the host discovery and the blacklist mechanism. 

I want to know whether the host discovery process is a static or dynamic. The way I understood was it is being provided as a static file containing classic MPI-hostfile config. And this is only done once the job is launched. How the new workers are being identified/searched when all workers in the host file are blacklisted (by the blacklist mechanism). If Horovod elastic is hosted in a cloud environment, how this is handled? This is my first question. 

The second question is the blacklist mechanism.  I am not clear about the blacklist mechanism. 
When a worker is blacklisted how does the driver know it is blacklisted. And while the training happens, can the driver dynamically identify the state change of a previously blacklisted worker which has now come out of the blacklist. Is this already implemented? I would like to know some information about this. 

My third question is about the re-initializing the workers. When the driver sees re-initialization, how new workers are being registered (other than the workers in the host discovery config)? 

My fourth question is about the rendezvous. When the notification manager is registered, the notification service and the secret key are saved in a key-value store. Is this key value store an in-memory key-value store in the driver or is it a disk-based key-value store like Redis? 

My fifth question is about the way the distributed data loading is being handled. It is not quite clear how the data loaders are being improved for the elasticity. Does the user has to provide the logic externally or is this being handled by the framework? What I mean is does the user has to write a custom ElasticDistributedDataLoader and handle elasticity. Another question, related to this is by keeping an offset on already trained data per a given epoch, we can avoid re-training. Is this something being done in the current release of Elastic Horovod? 

My sixth question is what is the criterion to decide the restart of the workers in terms of a failure. How this is being managed?
When all workers fail, will the job be restarted? Or marked as a failed one and not try again. If a set of the workers failed, but another set works fine, does the job restart? What is the way of declaring a worker succeeded or failed? 

Thank You, 
Vibhatha.

**Comment by EnricoMi** [comment]
Hi @vibhatha, let me answer a few of your questions.

The discovery is done by a shell script (`--host-discovery-script`) that being **executed** returns the hostnames and slots that are available via STDOUT. Everytime this script is executed, a different list of hosts can be returned. So the output of that script is dynamic in that sense. Horovod Elastic detects changes in that list and reorganizes the Horovod cluster if needed. You can read more about the discovery script in [docs/elastic.rst](https://github.com/horovod/horovod/blob/master/docs/elastic.rst#running-with-horovodrun).

The blacklisting is a term of Horovod Elastic, in the sense that Horovod detects node failures and blacklists them internally. The blacklisted hosts are then not used by Horovod, even though the discovery script still lists them. I think currently, blacklisted hosts are ignored forever, but we will add a timeout soon which will make Horovod periodically retry those blacklisted hosts (if still in the discovery scripts output).

Registration and initialization of new workers is a very Horovod internal topic. Why are you asking?

A worker is marked a success when it exits with exit code zero. A non-zero exit code or a loss of communication to the worker is considered a worker failure. The host is blacklisted and the Horovod cluster is re-initialized to continue the job without the worker. Only when all workers fail the whole Horovod job fails. And only when all workers succeed, the Horovod finishes.

I think @tgaddair will be able to answer your other questions.

Cheers,
Enrico

**Comment by tgaddair** [comment]
Hey @vibhatha, to follow-up on @EnricoMi's answer:

> My third question is about the re-initializing the workers. When the driver sees re-initialization, how new workers are being registered (other than the workers in the host discovery config)?

After the worker calls `state.commit()` or `state.check_host_updates()`, then Horovod will use this opportunity to add new workers to the training process.

> My fourth question is about the rendezvous. When the notification manager is registered, the notification service and the secret key are saved in a key-value store. Is this key value store an in-memory key-value store in the driver or is it a disk-based key-value store like Redis?

The key-value store is currently in-memory, since the Driver is the single source of truth for this information.  In the future, when we add additional layers of fault tolerance to the driver, this may change to something like Redis or etcd.

> My fifth question is about the way the distributed data loading is being handled. It is not quite clear how the data loaders are being improved for the elasticity. Does the user has to provide the logic externally or is this being handled by the framework? What I mean is does the user has to write a custom ElasticDistributedDataLoader and handle elasticity. Another question, related to this is by keeping an offset on already trained data per a given epoch, we can avoid re-training. Is this something being done in the current release of Elastic Horovod?

There are two options for data loading: random sampling or partitioning.  Random sampling doesn't require any special consideration for elastic training.  Each batch, you simply select a random set of data from the training set.  For partitioning, there is some work that still needs to be done to make it work.  In theory, it can be handled entirely on the user side, but we will be adding additional APIs to make it easier to manage prior to the v0.20.0 release.

> My sixth question is what is the criterion to decide the restart of the workers in terms of a failure. How this is being managed?
> When all workers fail, will the job be restarted? Or marked as a failed one and not try again. If a set of the workers failed, but another set works fine, does the job restart? What is the way of declaring a worker succeeded or failed?

When all workers fail, the job will fail.  There needs to be at least one process alive at all times for training to continue.  When any worker succeeds, the whole job shuts down, regardless of the state of the other workers.  Because Horovod workers all do the same things at the same time (just with different data), it should not be the case that one worker succeeds but the others are still working.

**Comment by vibhatha** [comment]
@tgaddair and @EnricoMi Thanks a lot for the responses. 

It is not quite clear to me how the host discovery is dynamic. If the provided discovery config is static (because we provide a file with host info), how can new workers join in?
Will another process be writing to this about the possible new workers. In this case, does HVD expects a resource scheduler to provide the info that there are new workers available, etc.? How does this Elastic okay response comes to the HVD elastic? 

This part is not quite clear from the docs. I also looked into the code, from my current understanding it is being executed in the very beginning. Or is this being called again in terms of the aforementioned elastic response. Please correct me if I am wrong.

**Comment by tgaddair** [comment]
Hey @vibhatha, the host discovery script you provide is an executable script, not a config.  So it's code.  Inside that script, you might, for example, make an API call to your container orchestrator / resource scheduler to get the set of available containers in your job.  We have an example.  In our tests, you can see an example of how the discovery script can be used to read an external data source dynamically at runtime: https://github.com/horovod/horovod/blob/master/test/integration/elastic_common.py#L33.

In the `driver.py` file, you can see where the host discovery takes place.  We execute the host discovery script once every few seconds to get the most updated set of host information: https://github.com/horovod/horovod/blob/master/horovod/run/elastic/driver.py#L178.

**Comment by vibhatha** [comment]
@tgaddair This makes everything clear. Thank you.
