### ISSUE TITLE
I use Horovod+TensorFlow to run 8 GPU traning and find out that each step's time cost is not as expected.

### ISSUE THREAD

**Issue by zpcalan** [horovod/horovod#2077]
1. Framework: TensorFlow
2. Framework version: 1.14
3. Horovod version:0.19
4. MPI version:3.1.5
5. CUDA version:10.0
6. NCCL version:2.4.8
7. Python version:3.7.5
8. OS and version:ubuntu 16.04
9. GCC version:7.3.0

I run the test case [https://github.com/horovod/horovod/blob/master/examples/keras_imagenet_resnet50.py](url) with 8 V100 GPUs:(with fp16 allreduce disabled.)

`horovodrun -np 8 -H localhost:8 python keras_imagenet_resnet50.p`

I write the time callback and print the time cost each step. **But the time cost is almost 300ms each step. But when I run 1 GPU resnet50 example of TensorFlow, the time cost is nearly 100ms.**
Could anybody tell me what's the problem with my test case?

**Comment by tgaddair** [comment]
Hey @zpcalan, how did you install Horovod?  Can you run `horovodrun --check-build` and provide the output here?

**Comment by zpcalan** [comment]
I installed horovod by `HOROVOD_GPU_OPERATIONS=NCCL pip install horovod`. 
And the output is down below:
Horovod v0.19.5:

Available Frameworks:
    [ ] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo

**Comment by zpcalan** [comment]
Is there anything wrong with my environment?
I think NCCL should be enabled but the output turns out to be unselected. And the Available Framework has TensorFlow excluded.
Do you think these two details are the reason that I get the wrong time cost?

Thank you very much!

**Comment by vfdev-5** [comment]
I have the same issue with 0.19.5 version and seems like env var `HOROVOD_GPU_OPERATIONS` is not yet introduced in setup.py: https://github.com/horovod/horovod/blob/b52e4b3e6ce5b1b494b77052878a0aad05c2e3ce/setup.py

To enable NCCL we need to specify :
```
export HOROVOD_GPU_ALLREDUCE=NCCL
export HOROVOD_GPU_BROADCAST=NCCL
```
However, in my case I get stuck with nccl lib recognition via vars:
```
    HOROVOD_NCCL_HOME - path where NCCL include and lib directories can be found
    HOROVOD_NCCL_INCLUDE - path to NCCL include directory
    HOROVOD_NCCL_LIB  - path to NCCL lib directory
```
the error is
```
/opt/conda/lib/libnccl_static.a: error adding symbols: File format not recognized
```
