### ISSUE TITLE
Horovod Controller 

### ISSUE THREAD

**Issue by jackygit-alt** [horovod/horovod#2080]
I have a question about horovod controller logics. 
Supposed we have two ranks, `rank0` and `rank1`, one tensor `tensor0`, in the last cycle, `tensor0` is ready at `rank0`, but unready at `rank1`, in this situation, we should try to process this `tensor0` request message again in next cycle. In the next cycle, if we again push another ready `tensor 0` request message to `tensor_queue_` at `rank0`, and `tensor0` is still unready at `rank1`. According to this controller logic, because we already have two `tensor0` request message at `rank0`, so when we call `IncrementTensorCount(message, state.joined_size);` at `rank0`, it returns `true`, that means `tensor0` is ready at all ranks, but it's incorrect in this special case. 
That makes confused, is it a bug or something else?

**Comment by tgaddair** [comment]
Hey @jackygit-alt, in general it should not be allowed to submit two tensors with the same name before the first operation has completed.  I'd have to look closely at the code to see how we handle this to be sure.  @romerojosh, do you know off the top of your head how we handle this?

**Comment by romerojosh** [comment]
That is correct. We explicitly do not allow there to be two pending tensors with the same name, so this situation cannot occur. See here: https://github.com/horovod/horovod/blob/e740b938e183fe54a2d2882fb606e8787b5de329/horovod/common/tensor_queue.cc#L29-L31

**Comment by jackygit-alt** [comment]
Thank you for your prompt reply, @romerojosh  @tgaddair . The code above doesn't allow two request messages with the same tensor name to exist in one `tensor_queue.message_queue_` and it can avoid the case mentioned above happens, but still assuming that we have two ranks, `rank0` and `rank1`, one tensor `tensor0`, and `rank0` is the `root` process. 
    In the last cycle, `tensor0` is ready at `rank0`, and unready at `rank1`, but in this cycle the `request` message of `tensor0` hit `CacheState::INVALID`. In this case, the `response_cache_` both at `rank0` and `rank1` would remove this invalid tensor entry - `tensor0` and this `request` message of `tensor0` would be put in the `message_table_` at `rank0`. 
    In the next cycle, `tensor0` is ready again at `rank0`, and still unready at `rank1`, because now there is no `request` message of `tensor0` existing in the `tensor_queue.message_queue_` at `rank0`, we can still push this `request` message of `tensor0` into the `tensor_queue.message_queue_` at `rank0`. Furthermore, because there is no `tensor0` entry existing in the `response_cache_` at `rank0`, so in this cycle this `request message` of `tensor0` would hit `CacheState::MISS`, so as the code shows below, we would push this `request` message of `tensor0` into `message_queue_tmp` in this `cycle` at `rank0`:
https://github.com/horovod/horovod/blob/e740b938e183fe54a2d2882fb606e8787b5de329/horovod/common/controller.cc#L142-L159
So in this `cycle`, when we call this function `IncrementTensorCount(message, state.joined_size);` at rank0, it returns `True`, because now there are two `request` messages of `tensor0` in the `message_table` at `rank0`, and it means that `tensor0` is ready at all ranks, but `tensor0` is actually unready at `rank1`. 
https://github.com/horovod/horovod/blob/e740b938e183fe54a2d2882fb606e8787b5de329/horovod/common/controller.cc#L224

**Comment by romerojosh** [comment]
Even in your second example, the `DUPLICATE_NAME_ERROR` will block a second request of `tensor0` from `rank0` as `tensor0` from the initial request will exist in the `tensor_table_`. I think you might be mixing up the `tensor_table_` for the `message_queue_`, as the `DUPLICATE_NAME_ERROR` does not check for duplicate entries in `message_queue_`.  `tensor0` will not be removed from `tensor_table_` until the operation to process the request is executed here (which requires all workers to have submitted a matching request for `tensor0`): https://github.com/horovod/horovod/blob/master/horovod/common/operations.cc#L241

Hope that clears things up a bit.

**Comment by jackygit-alt** [comment]
OK, I get it. Thank you for your answer, I really appreciate it! @romerojosh 
Now i will close this issue.
