### ISSUE TITLE
How do different machines read different data

### ISSUE THREAD

**Issue by Jie-Yuan** [horovod/horovod#2082]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tgaddair** [comment]
Hey @Jie-Yuan, this is handled outside of Horovod.  For example, if your data is in the Parquet format, you can use [Petastorm](https://github.com/uber/petastorm).  For TFRecord, you can use TensorFlow's [tf.data.Dataset.shard](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shard).  For PyTorch, there is the [DistributedSampler](https://pytorch.org/docs/stable/data.html#torch.utils.data.distributed.DistributedSampler).
