### ISSUE TITLE
Different number of steps on different workers

### ISSUE THREAD

**Issue by tvatsal1996** [horovod/horovod#2083]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 2.1.0
3. Horovod version: 0.19.4
4. MPI version: 3.0.0
5. CUDA version: 10.1
6. NCCL version: 2.4.7+
7. Python version: 3.6.6
8. OS and version: Linux 3.10
9. GCC version: 7.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

I am using [shard](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shard) to split my data to 2 workers. This gives first worker one extra batch than the second worker in case of odd number of batches initially. This creates different number of training steps on each worker. As a result, first worker keeps on waiting while the second worker proceeds for evaluation. Basically different number of steps in different worker is creating problem. Is there any workaround for this? Thank you !!

**Comment by tgaddair** [comment]
Hey @tvatsal1996, yes, you can use the newly introduced [hvd.join()](https://github.com/horovod/horovod/blob/master/test/test_tensorflow.py#L1317) function to work around this.  If you call `hvd.join()` at the end of the epoch, then the workers that finish early will wait until the stragglers complete before moving on to the next set of work.

**Comment by tvatsal1996** [comment]
Hi, I installed horovod-0.19.5 from source using ```HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=<cuda_path> HOROVOD_NCCL_HOME=<nccl_path> pip install --no-cache-dir horovod-0.19.5.tar.gz```, but getting ```AttributeError: module 'horovod.tensorflow' has no attribute 'join'```

**Comment by tvatsal1996** [comment]
Hi I am installing it from source. I got the error during installation: ``` CMake Error: The source directory "/tmp/pip-_1021vn3-build/third_party/gloo" does not appear to contain CMakeLists.txt.``` I then searched third_party/gloo dir. It was empty.
