### ISSUE TITLE
Conda environment.yml location

### ISSUE THREAD

**Issue by vfdev-5** [horovod/horovod#2084]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? No
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? No
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**

According to the docs: https://github.com/horovod/horovod/blob/master/docs/conda.rst#dependencies

> Below are the core required dependencies. The complete `environment.yml` file is available on GitHub.

But I can not find this complete `environment.yml`. Could you please indicate its location. Thanks.

**Comment by tgaddair** [comment]
Hey @vfdev-5, the docs are referring to the `environment.yml` from [this](https://github.com/kaust-vislab/horovod-gpu-data-science-project) repo (see #2056).

@davidrpugh, could you update the `conda.rst` file to point to the correct location of the `environment.yml` file in your repo?

**Comment by davidrpugh** [comment]
@tgaddair Yes I will make the update.

**Comment by davidrpugh** [comment]
@tgaddair can this issue can be closed since #2111 was merged?
