### ISSUE TITLE
SSH Issues - Username 

### ISSUE THREAD

**Issue by vinhdiesal** [horovod/horovod#2089]
I want to create a `horovod` job on three machines at `192.168.1.119`, `192.168.1.191` and `192.168.1.119`, however in order for the computer to connect via SSH, you need the username which is `vinhdiesal`. 
However, `horovodrun` doesn't provide the option to specify a username. I tried the following command which errors out:
`horovodrun -np -4 -H localhost vinhdiesal@192.168.1.191 vinhdiesal@192.168.1.119 python tensorflow.py` which provides error because it needs to be in the `worker:2` format. 

Also is there a way to run the tensorflow model using `horovod` inside `jupyter notebook`. I'm trying to experiment `horovod` with packages like `DASK` for distributed machine learning.

**Comment by tgaddair** [comment]
Hey @vinhdiesal, to SSH using a specific username, you should be able to accomplish this by modifying `/etc/ssh/ssh_config` or `~/.ssh/config` like so:

```
Host 192.168.1.191 192.168.1.119
User vinhdiesal
...
```

See [this](https://stackoverflow.com/questions/6518314/configure-mpi-hostsfile-to-use-multiple-user-identities) answer on StackOverflow for more details.

You also need to specify the number of slots in your command, so something like:

```
horovodrun -np -4 -H localhost:2 192.168.1.191:1 192.168.1.119:1 python tensorflow.py
```

Depending on how many GPUs / processes you want to run on each host (in the example above, 2 processes run on localhost, and 1 process runs on each of the remote hosts).

To answer your other question, you can use the [interactive Horovod API](https://horovod.readthedocs.io/en/stable/api.html#module-horovod.run) to run from a jupyter notebook:

```
import horovod.run.run as horovodrun

horovodrun(training_function, np=4, ...)
```

**Comment by vinhdiesal** [comment]
thanks @tgaddair for your quick and thorough response. Much appreciated, I ran a few tensorflow scripts which finished really quick, but I'm not sure where the results are to analyze the error metrics. Usually when you run the .fit in tensorflow you get several lines after each epoch and it's performance metrics. How do I see this data, or where is the data log so I can visualize it with tools like tensorboard?
Thanks
