### ISSUE TITLE
Got error of running an example code on this horovod website on GPU clusters

### ISSUE THREAD

**Issue by umusa** [horovod/horovod#2095]
I am trying to run the example https://github.com/horovod/horovod/blob/master/examples/tensorflow2_keras_mnist.py

on databricks GPU cluster with 1 driver and 2 workers.

The environment

      6.5 ML, scala 2.11,  spark 2.4.5
      python 3.7
      TensorFlow 2.2.0

I got the error:

      NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory

I cannot find a solution after searching online.

Could anybody help me about this ? 

thanks

**Comment by tgaddair** [comment]
Hey @umusa, this means that the version of CUDA that was used to install TensorFlow does not match the version of CUDA in the image.  TensorFlow 2.2 expects CUDA 10.1.  Can you try running `nvcc --version` to check your system CUDA version?
