### ISSUE TITLE
Mpirun doesn't run the script and it gets stucked

### ISSUE THREAD

**Issue by arehmanAzam** [horovod/horovod#2098]
**Environment:**
1. Framework: Keras
2. Framework version: Keras==2.1.6
3. Horovod version: horovod==0.19.5
4. MPI version: 4.0.1
5. CUDA version: 10.0
6. NCCL version: nccl_2.4.8-1
7. Python version: 3.6
8. OS and version: Ubuntu 18.04
9. GCC version: 7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
Yes i did and tried many solutions but none seems to be effective
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
Yes and i have installed OpenMPI 4.0.1. 
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
No
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?
None

**Your question:**
Please ask your question here.
I am trying to run distributed training using 2 machines.
Both machines can ssh eachother without password authentication.
ssh config of machine worker-1 is as follows
![image](https://user-images.githubusercontent.com/29056479/87304554-6f053080-c52e-11ea-8c70-e7c7799e4670.png)
ssh config of machine worker-2 is as follows
![image](https://user-images.githubusercontent.com/29056479/87304691-a2e05600-c52e-11ea-9764-4b7681f664ac.png)

I am running command on both machines as follows . 

`mpirun --prefix /usr/local -np 2     -H worker-1:1,worker-2:1     -bind-to none -map-by slot   -x NCCL_SOCKET_IFNAME=eth0  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH     -mca btl_tcp_if_include eth0,lo python3 -W ignore detector.py train --model=last --dataset=../data --class_map=./taco_config/xavor_map_17.csv --round 0 --lrate 0.01`
There is not a single ouput it shows on both machines. The command shows empty cursor and then exits after some time.
Don't know what am i doing wrong 
@alsrgv any help will be highly appreciated

**Comment by tgaddair** [comment]
Hey @arehmanAzam, can you verify that the problem also occurs without running any Python or Horovod, so:

```
mpirun ... echo "hello world"
```

Next steps would be to try using strace as shown [here](https://github.com/horovod/horovod/issues/110#issuecomment-347737251) to see where the hang is coming from.

**Comment by arehmanAzam** [comment]
@tgaddair i have gotten out of this issue and infact the multiple nodes are working.
The problem was that i needed to have install openmpi at root. .bashrc environment variables were not picked up by the ssh when i tried to run `ssh worker-1 ompi_info | head`. 
Then i made unified user and made same directory structure of project at both nodes as mentioned in this issue
https://github.com/horovod/horovod/issues/1434

Now that i am over it , the training starts but the GPU consumption is like very less on both nodes. [To be very clear, i am just starting the mpi process in worker-1 and it starts processes in both nodes]
Also the worker-1 shows following output:

`Epoch 24/30`
`2020-07-16 19:44:50.190598: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0`
`2020-07-16 19:44:50.716428: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7`
`2020-07-16 19:44:57.956702: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.71GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.`
`2020-07-16 19:44:57.956752: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.71GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-16 19:44:57.962991: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.05GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-16 19:44:57.963018: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.05GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.`
`2020-07-16 19:44:58.015502: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.04GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-16 19:44:58.015543: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.04GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.`
`2020-07-16 19:44:58.034678: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-16 19:44:58.034739: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-16 19:44:58.455914: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.12GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-16 19:44:58.455975: W tensorflow/core/common_runtime/bfc_allocator.cc:239] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.12GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-07-16 19:45:11.463620: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-07-16 19:45:12.865615: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7`

`ai2-pc:15828:15906 [0] bootstrap.cc:37 NCCL WARN Bootstrap : no socket interface found`
`ai2-pc:15828:15906 [0] NCCL INFO init.cc:128 -> 3`
`ai2-pc:15828:15906 [0] NCCL INFO bootstrap.cc:76 -> 3`
`ai2-pc:15828:15906 [0] NCCL INFO bootstrap.cc:245 -> 3`
`ai2-pc:15828:15906 [0] NCCL INFO bootstrap.cc:266 -> 3`
`ai2-pc:15828:15906 [0] NCCL INFO bootstrap.cc:76 -> 3`
`ai2-pc:15828:15906 [0] NCCL INFO bootstrap.cc:245 -> 3`
`ai2-pc:15828:15906 [0] NCCL INFO bootstrap.cc:266 -> 3`

**Comment by arehmanAzam** [comment]
Also my generator code is as 
`self.keras_model.fit_generator(
                train_generator,
                initial_epoch=self.epoch,
                epochs=epochs,
                steps_per_epoch=self.config.STEPS_PER_EPOCH,
                callbacks=callbacks,
                validation_data=val_generator,
                validation_steps=self.config.VALIDATION_STEPS,
                max_queue_size=100,
                workers=workers,
                use_multiprocessing=True,
            )`
Now i want to use multiple workers but the cpu cores consumptions is also very less.
![image](https://user-images.githubusercontent.com/29056479/87689069-35882b80-c7a1-11ea-9704-17ec9b17e8c8.png)

This is the situation at both nodes
The GPU consumption is as 
![image](https://user-images.githubusercontent.com/29056479/87689162-50f33680-c7a1-11ea-8e27-bfb1f12be140.png)

I dont know if my nodes are training. 
Also when i try to run this script in other node making that as chief or master. At both nodes i am running this command
`mpirun  -np 2     -H worker-1:1,worker-2:1     -bind-to none -map-by slot   -x NCCL_SOCKET_IFNAME=eth0  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  python3 -W ignore detector.py train --model=last --dataset=../data --class_map=./taco_config/xavor_map_17.csv --round 0 --lrate 0.01
`
I am facing these two issues. Any idea @tgaddair 
Gist of strace worker-1 https://gist.github.com/arehmanAzam/23755c78abe9fc9e99be62e445455dbe
Gist of strace worker-2 https://gist.github.com/arehmanAzam/4e3e5d13af08831aff251a60b494fcd7

**Comment by tgaddair** [comment]
Hey @arehmanAzam, can you try running the [tensorflow_synthetic_benchmark](https://github.com/horovod/horovod/blob/master/examples/tensorflow_synthetic_benchmark.py) first and verify that it works correctly with good performance in your environment?  If everything goes well there, then we can rule out setup issues and start digging into your model.

**Comment by arehmanAzam** [comment]
Okay. Will let you know when done with this synthetic benchmark.
