### ISSUE TITLE
CIFAR scaling efficiency

### ISSUE THREAD

**Issue by mreso** [horovod/horovod#2103]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.4.0
3. Horovod version: 0.19.1
4. MPI version: 4.0.0
5. CUDA version: 10.1
6. NCCL version: 2.4.8-1
7. Python version: 3.6
8. OS and version: ubuntu18.04
9. GCC version: 4.8

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Hi,

I am trying to figure out why the training with pytorch + horovod is not scaling well in my project.
To debug the issue I broke it down to a basic example with docker and the CIFAR10 dataset.
My environment consist of 3 nodes with 6 K80 gpus each.
Running the synthetic pytorch and tensorflow benchmarks scales with 88% efficiency up to all 18 gpus but running the CIFAR example gives me merely 58%.

I start my master node with:
```docker run -ti --rm --network=host --ipc=host -v "/mnt/nfs/:/app" -v /mnt/nfs/ssh:/root/.ssh horovod/horovod:0.19.1-tf2.1.0-torch1.4.0-mxnet1.6.0-py3.6-gpu horovodrun -np 18 -H 192.168.2.1:6,192.168.2.2:6,192.168.2.3:6 -p 12345 python /app/pytorch_hvd_cifar10.py --batch-size 128```

And my worker nodes with:
```docker run -ti --rm --network=host --ipc=host -v "/mnt/nfs/:/app" -v /mnt/nfs/ssh:/root/.ssh horovod/horovod:0.19.1-tf2.1.0-torch1.4.0-mxnet1.6.0-py3.6-gpu bash -c "/usr/sbin/sshd -p 12345; sleep infinity"```

My training script is the python_mnist.py example with minor modifications to use CIFAR10 and for timing the training which gives me these throughput values:

```
num gpus: images / sec
1:    510.9
6:    410.1
12:   330.2
18:   298.5
```

Any ideas why it is scaling so badly?

pytorch_hvd_cifar10.py:
```
import argparse
import time
import numpy as np
import torch.multiprocessing as mp
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
import torch.utils.data.distributed
import horovod.torch as hvd
from torchvision import models

# Training settings
parser = argparse.ArgumentParser(description='PyTorch CIFAR Example')
parser.add_argument('--batch-size', type=int, default=64, metavar='N',
                    help='input batch size for training (default: 64)')
parser.add_argument('--test-batch-size', type=int, default=1000, metavar='N',
                    help='input batch size for testing (default: 1000)')
parser.add_argument('--epochs', type=int, default=10, metavar='N',
                    help='number of epochs to train (default: 10)')
parser.add_argument('--lr', type=float, default=0.01, metavar='LR',
                    help='learning rate (default: 0.01)')
parser.add_argument('--momentum', type=float, default=0.5, metavar='M',
                    help='SGD momentum (default: 0.5)')
parser.add_argument('--no-cuda', action='store_true', default=False,
                    help='disables CUDA training')
parser.add_argument('--seed', type=int, default=42, metavar='S',
                    help='random seed (default: 42)')
parser.add_argument('--log-interval', type=int, default=10, metavar='N',
                    help='how many batches to wait before logging training status')
parser.add_argument('--fp16-allreduce', action='store_true', default=False,
                    help='use fp16 compression during allreduce')
parser.add_argument('--use-adasum', action='store_true', default=False,
                    help='use adasum algorithm to do reduction')

def train(epoch):
    model.train()
    # Horovod: set epoch to sampler for shuffling.
    train_sampler.set_epoch(epoch)
    for batch_idx, (data, target) in enumerate(train_loader):
        if args.cuda:
            data, target = data.cuda(), target.cuda()
        optimizer.zero_grad()
        output = model(data)
        loss = F.cross_entropy(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % args.log_interval == 0:
            # Horovod: use train_sampler to determine the number of examples in
            # this worker's partition.
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_sampler),
                100. * batch_idx / len(train_loader), loss.item()))


def metric_average(val, name):
    tensor = torch.tensor(val)
    avg_tensor = hvd.allreduce(tensor, name=name)
    return avg_tensor.item()


def test():
    model.eval()
    test_loss = 0.
    test_accuracy = 0.
    for data, target in test_loader:
        if args.cuda:
            data, target = data.cuda(), target.cuda()
        output = model(data)
        # sum up batch loss

        test_loss += F.cross_entropy(output, target, size_average=False).item()
        # get the index of the max log-probability
        pred = output.data.max(1, keepdim=True)[1]
        test_accuracy += pred.eq(target.data.view_as(pred)).cpu().float().sum()

    # Horovod: use test_sampler to determine the number of examples in
    # this worker's partition.
    test_loss /= len(test_sampler)
    test_accuracy /= len(test_sampler)

    # Horovod: average metric values across workers.
    test_loss = metric_average(test_loss, 'avg_loss')
    test_accuracy = metric_average(test_accuracy, 'avg_accuracy')

    # Horovod: print output only on first rank.
    if hvd.rank() == 0:
        print('\nTest set: Average loss: {:.4f}, Accuracy: {:.2f}%\n'.format(
            test_loss, 100. * test_accuracy))


if __name__ == '__main__':
    args = parser.parse_args()
    args.cuda = not args.no_cuda and torch.cuda.is_available()

    # Horovod: initialize library.
    hvd.init()
    torch.manual_seed(args.seed)

    if args.cuda:
        # Horovod: pin GPU to local rank.
        torch.cuda.set_device(hvd.local_rank())
        torch.cuda.manual_seed(args.seed)


    # Horovod: limit # of CPU threads to be used per worker.
    torch.set_num_threads(1)

    kwargs = {'num_workers': 1, 'pin_memory': True} if args.cuda else {}
    # When supported, use 'forkserver' to spawn dataloader workers instead of 'fork' to prevent
    # issues with Infiniband implementations that are not fork-safe
    if (kwargs.get('num_workers', 0) > 0 and hasattr(mp, '_supports_context') and
            mp._supports_context and 'forkserver' in mp.get_all_start_methods()):
        kwargs['multiprocessing_context'] = 'forkserver'

    train_dataset = \
        datasets.CIFAR10('/app/data-%d' % hvd.rank(), train=True, download=True,
                       transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                            std=[0.229, 0.224, 0.225])
                       ]))
    # Horovod: use DistributedSampler to partition the training data.
    train_sampler = torch.utils.data.distributed.DistributedSampler(
        train_dataset, num_replicas=hvd.size(), rank=hvd.rank())
    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=args.batch_size, sampler=train_sampler, **kwargs)

    test_dataset = \
        datasets.CIFAR10('/app/data-%d' % hvd.rank(), train=False, transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
        ]))
    # Horovod: use DistributedSampler to partition the test data.
    test_sampler = torch.utils.data.distributed.DistributedSampler(
        test_dataset, num_replicas=hvd.size(), rank=hvd.rank())
    test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=args.test_batch_size,
                                              sampler=test_sampler, **kwargs)

    model = models.resnet18()

    # By default, Adasum doesn't need scaling up learning rate.
    lr_scaler = hvd.size() if not args.use_adasum else 1

    if args.cuda:
        # Move model to GPU.
        model.cuda()
        # If using GPU Adasum allreduce, scale learning rate by local_size.
        if args.use_adasum and hvd.nccl_built():
            lr_scaler = hvd.local_size()

    # Horovod: scale learning rate by lr_scaler.
    optimizer = optim.SGD(model.parameters(), lr=args.lr * lr_scaler,
                          momentum=args.momentum)

    # Horovod: broadcast parameters & optimizer state.
    hvd.broadcast_parameters(model.state_dict(), root_rank=0)
    hvd.broadcast_optimizer_state(optimizer, root_rank=0)

    # Horovod: (optional) compression algorithm.
    compression = hvd.Compression.fp16 if args.fp16_allreduce else hvd.Compression.none

    # Horovod: wrap optimizer with DistributedOptimizer.
    optimizer = hvd.DistributedOptimizer(optimizer,
                                         named_parameters=model.named_parameters(),
                                         compression=compression,
                                         op=hvd.Adasum if args.use_adasum else hvd.Average)

    img_per_secs = []
    for epoch in range(1, args.epochs + 1):
        start_time = time.time()
        train(epoch)
        epoch_time = time.time() - start_time
        img_per_secs.append(len(train_dataset)/epoch_time)
        if hvd.rank() == 0:
            print('Average samples/sec: {}'.format(img_per_secs[-1]))
        test()
    mean_img_per_secs= np.mean(img_per_secs)
    if hvd.rank() == 0:
        print('Average samples/sec: {}'.format(mean_img_per_secs))
        print('Average samples/sec per gpu: {}'.format(mean_img_per_secs/hvd.size()))
```

**Comment by tgaddair** [comment]
Hey @mreso, is the data being read from NFS?  It might be that I/O is bottlenecking the training process.  One way to dig into this further would be to generate a [timeline](https://github.com/horovod/horovod/blob/master/docs/timeline.rst) file so we can check whether the allreduce calls are the culprit or something else.

**Comment by mreso** [comment]
Hi @tgaddair 
thanks for your reply!
Good point with the data. I cache it on nfs after downloading it to safe some time as I only use temporary docker containers which are removed when I stop them. I tested it with local caching and had the same results though. If I read the code of the CIFAR dataset correctly the data is loaded completely into memory anyway during execution (https://github.com/pytorch/vision/blob/ab73b44887eb9d7566b2a80fd45cb5f68b11d643/torchvision/datasets/cifar.py#L73).
I created a timeline with local caching now [timeline.zip](https://github.com/horovod/horovod/files/4934073/timeline.zip). Would be great if you could take a look at it as I am unsure what exactly to look for.
Thanks again for looking into my problem!

**Comment by tgaddair** [comment]
Hey @mreso, thanks for providing the timeline, I think it reveals a lot about what is probably going on here.

If you take a look at the capture below, you'll see that the majority of the Horovod time is being spent in the QUEUE state:

<img width="1235" alt="Screen Shot 2020-07-16 at 2 29 56 PM" src="https://user-images.githubusercontent.com/1742912/87724772-de6a6280-c770-11ea-82f9-b04e060c3309.png">

This means that the requested NCCL operation can't start yet because the previous NCCL op is still in progress.

What this tells me is that the reason for the poor scaling is most likely because the resnet18 model you're using for CIFAR-10 is too small and your GPU too powerful for your network to keep up.  This is the same thing we observe with the MNIST example, for instance.

When using a bigger model like resnet50, the GPU takes longer to push tensors for allreduce, meaning it's easier to overlap computation with communication, leading to better scaling like you saw with the synthetic benchmark.

So one thing to try would be to use a beefier model, or increase the batch size per worker.

**Comment by mreso** [comment]
Oh, that makes it pretty much clear! I was always worrying about the negotiation times which looked a bit long compared to the allreduce in some instances but I totally overlooked that the gap between allreduce where tiny. With resnet50 and 1024 batch size I get over 80% efficiency which looks much more reasonable. Thank you so much @tgaddair for pointing me to this!
