### ISSUE TITLE
Format Data for Horovod.Spark

### ISSUE THREAD

**Issue by aliatprotopia** [horovod/horovod#2104]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TF/Keras
2. Framework version: 2.2.0
3. Horovod version: 0.19.5
4. MPI version: Gloo
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7
8. OS and version: Amazon Linux 2
9. GCC version: 4.8

**Checklist:**
1. Did you search issues to find if somebody asked this question before? No
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? N/A
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**
I am trying to use `hvd.KerasEstimator().fit(train_dataset)` and I am very confused as of how I should format my `train_dataset`. I have my data stored as standard parquet with two columns `image` and `label`. `Image` is a `list(list(list))` and `label` is a `list` such that if I apply `np.array`, it gives the right dimensions for my network.

The RDD below has the correct `(input, label)-pair` for training, but Horovod does not accept RDD, how should I correctly convert this to Dataframe for training?
`spark.read.parquet('\path').rdd.map(lambda data: (np.array(data['image']), np.array(data['label'])))`

I have tried many code snippets with `petastorm`'s `unischema ` with no success.

**Comment by tgaddair** [comment]
Hey @aliatprotopia, no need to use Unischema.  All you need to do is convert your nested lists into a single-dimensional [ArrayType](https://stackoverflow.com/questions/48394717/creating-a-pyspark-schema-involving-an-arraytype) of floats.  Then to convert the RDD into a DataFrame you can use createDataFrame as shown [here](https://stackoverflow.com/questions/29383578/how-to-convert-rdd-object-to-dataframe-in-spark).

**Comment by aliatprotopia** [comment]
@tgaddair How does Horovod know the right dimensions for my network input to convert the one-dimensional array back to the proper numpy array with correct size and feed it to my network for training?

**Comment by tgaddair** [comment]
@aliatprotopia, for Keras this can be inferred automatically by looking at the model definition.  For PyTorch, you need to pass in the input shape.

**Comment by aliatprotopia** [comment]
@tgaddair I am asking specifically about `hvd.KerasEstimator().fit(train_dataset)`. If I pass `train_dataset` as a Spark dataframe with two columns; one input and one target (both being single-dimensional arrays), would this work? Or do I need to do more?

**Comment by tgaddair** [comment]
If you take a look at the [keras_spark_mnist](https://github.com/horovod/horovod/blob/master/examples/keras_spark_mnist.py#L89) example, you'll see what I'm referring to.  The input to the model is coming in as a column called `features` that is a 1D `DenseVector`.  But the model input shape is `(28, 28, 1)`.  So we take care of the reshaping for you.

On your end, what you need to do is:

1. Make sure the `train_dataset` is a DataFrame with only scalar or 1D Vector/Array types.
2. Pass in the appropriate [args](https://github.com/horovod/horovod/blob/master/examples/keras_spark_mnist.py#L102) for these params.

Hope that makes sense.  Let me know if you have more questions.

**Comment by aliatprotopia** [comment]
@tgaddair Thanks a lot. Let me try this and get back to you. Appreciate your help.

**Comment by aliatprotopia** [comment]
Hi @tgaddair I made all the changes as you said and now am running into this error and I could not find any spark config to resolve this; can you help?

```
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/mnt/yarn/usercache/hadoop/appcache/application_1594902417610_0001/container_1594902417610_0001_01_000002/pyspark.zip/pyspark/worker.py", line 377, in main
    process()
  File "/mnt/yarn/usercache/hadoop/appcache/application_1594902417610_0001/container_1594902417610_0001_01_000002/pyspark.zip/pyspark/worker.py", line 372, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1594902417610_0001/container_1594902417610_0001_01_000002/pyspark.zip/pyspark/serializers.py", line 393, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/dev/shm/python_packages/horovod/spark/runner.py", line 89, in _mapper
    yield _task_fn(index, driver_addresses, key, settings, use_gloo)
  File "/dev/shm/python_packages/horovod/spark/runner.py", line 50, in _task_fn
    task.wait_for_initial_registration(settings.timeout)
  File "/dev/shm/python_packages/horovod/run/common/service/task_service.py", line 190, in wait_for_initial_registration
    timeout.check_time_out_for('tasks to start')
  File "/dev/shm/python_packages/horovod/run/common/util/timeout.py", line 32, in check_time_out_for
    raise Exception(self._message.format(activity=activity))
Exception: Timed out waiting for tasks to start. Please check that you have enough resources to run all Horovod processes. Each Horovod process runs in a Spark task. You may need to increase the start_timeout parameter to a larger value if your Spark resources are allocated on-demand.
```

**Comment by tgaddair** [comment]
@aliatprotopia how many processes are you attempting to run with?  Can you verify that you have enough executor cores to run that many tasks?

I'm not too familiar with running on YARN.  @EnricoMi do you have some additional debugging suggestions?

**Comment by aliatprotopia** [comment]
@tgaddair  It turned out I was both specifying executor memory and executor cores. I removed executor memory config and everything worked. Thanks again. Closing ticket.

**Comment by tgaddair** [comment]
Glad you got it working!
