### ISSUE TITLE
Error while trying to run using a job script

### ISSUE THREAD

**Issue by anweshpanda** [horovod/horovod#2105]
I am using horovod with Pytorch. I installed the package in miniconda using the following as suggested in this forum before.
--------------------------------------------------
conda config --set channel_priority strict
conda create --name fresh_env python=3.7 tensorflow-gpu pytorch horovod conda activate fresh_env
-------------------------------------------------
When I am running from command line using horovodrun , it works fine. But , as I am using CRAY XC40 system , I need to submit a job script to utilise multiple nodes. The script uses aprun command. But I am getting the following error.
-------------------------------------------------
The application appears to have been direct launched using "aprun",
but OMPI was not built with ALPS support. This usually happens
when OMPI was not configured --with-alps and we weren't able
to discover an ALPS installation in the usual places.

Please configure as appropriate and try again.
-------------------------------------------------
Can anyone please help me with this?

**Comment by tgaddair** [comment]
Hey @anweshpanda, for running with `aprun`, can you take a look at #516 and see if the suggestions there work for you?
