### ISSUE TITLE
Cannot run test with Gloo

### ISSUE THREAD

**Issue by shirosankaku** [horovod/horovod#2112]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.6.0a0+b7b99ab
3. Horovod version: master branch commit 7ded1075d21230266d87bfac209281ba59e55de9
4. MPI version: building Horovod without MPI
5. CUDA version: n/a
6. NCCL version: n/a
7. Python version: 3.6.10
8. OS and version: Red Hat Enterprise Linux Server 7.6
9. GCC version: 8.3.0
10. Conda env: 4.8.2

Hello! Could you, please, help me to figure out what the problem is.
I built and installed Horovod with Gloo support. But I cannot run a test because Gloo was not build according to the runner.
building:
`export HOROVOD_CPU_OPERATIONS=CCL`
`export HOROVOD_WITH_GLOO=1`
`export HOROVOD_WITHOUT_MPI=1`
`export HOROVOD_WITHOUT_TENSORFLOW=1`
`export HOROVOD_WITHOUT_MXNET=1`
`export HOROVOD_WITH_PYTORCH=1`
`python setup.py build`
`python setup.py install`

output:
`running build`
`...`
`Scanning dependencies of target gloo`
`[ 12%] Building CXX object gloo/CMakeFiles/gloo.dir/algorithm.cc.o`
`[ 12%] Building CXX object gloo/CMakeFiles/gloo.dir/allgather.cc.o`
`[ 12%] Building CXX object gloo/CMakeFiles/gloo.dir/allreduce.cc.o`
`[ 12%] Building CXX object gloo/CMakeFiles/gloo.dir/allgatherv.cc.o`
`[ 15%] Building CXX object gloo/CMakeFiles/gloo.dir/allreduce_local.cc.o`
`[ 18%] Building CXX object gloo/CMakeFiles/gloo.dir/barrier.cc.o`
`[ 21%] Building CXX object gloo/CMakeFiles/gloo.dir/broadcast.cc.o`
`[ 25%] Building CXX object gloo/CMakeFiles/gloo.dir/context.cc.o`
`[ 28%] Building CXX object gloo/CMakeFiles/gloo.dir/gather.cc.o`
`[ 31%] Building CXX object gloo/CMakeFiles/gloo.dir/reduce.cc.o`
`[ 34%] Building CXX object gloo/CMakeFiles/gloo.dir/scatter.cc.o`
`[ 37%] Building CXX object gloo/CMakeFiles/gloo.dir/types.cc.o`
`[ 40%] Building CXX object gloo/CMakeFiles/gloo.dir/common/logging.cc.o`
`[ 46%] Building CXX object gloo/CMakeFiles/gloo.dir/common/linux.cc.o`
`[ 50%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/context.cc.o`
`[ 50%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/file_store.cc.o`
`[ 53%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/hash_store.cc.o`
`[ 56%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/prefix_store.cc.o`
`[ 62%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/store.cc.o`
`[ 62%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/address.cc.o`
`[ 65%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/buffer.cc.o`
`[ 68%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/context.cc.o`
`[ 71%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/device.cc.o`
`[ 75%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/pair.cc.o`
`[ 78%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/unbound_buffer.cc.o`
`[ 81%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/address.cc.o`
`[ 87%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/buffer.cc.o`
`[ 87%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/context.cc.o`
`[ 90%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o`
`[ 93%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/pair.cc.o`
`[ 96%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/unbound_buffer.cc.o`
`[100%] Linking CXX static library /horovod/build/temp.linux-x86_64-3.6/lib/torchv2/libgloo.a`
`[100%] Built target gloo`
`INFO: HOROVOD_WITHOUT_MPI detected, skip compiling Horovod with MPI.`
`INFO: Set default CPU operation to CCL`
`...`

Running test:
`HOROVOD_CONTROLLER=GLOO horovodrun --disable-cache --gloo -np 2 --verbose python -u ./tests/test_torch.py`
Output:
`Filtering local host names.`
`Remote host found:`
`All hosts are local, finding the interfaces with address 127.0.0.1`
`Local interface found lo`
`Traceback (most recent call last):`
`  File "/anaconda_new/envs/py36_pytorch_ccl_hvd/bin/horovodrun", line 33, in <module>
    sys.exit(load_entry_point('horovod==0.19.2', 'console_scripts', 'horovodrun')())`
`  File "/anaconda_new/envs/py36_pytorch_ccl_hvd/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/runner/launch.py", line 717, in run_commandline
    _run(args)`
`  File "/anaconda_new/envs/py36_pytorch_ccl_hvd/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/runner/launch.py", line 707, in _run
    return _run_static(args)`
`  File "/anaconda_new/envs/py36_pytorch_ccl_hvd/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/runner/launch.py", line 570, in _run_static
    _launch_job(args, settings, nics, command)`
`  File "/anaconda_new/envs/py36_pytorch_ccl_hvd/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/runner/launch.py", line 683, in _launch_job
    args.verbose)`
`  File "/anaconda_new/envs/py36_pytorch_ccl_hvd/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/runner/launch.py", line 632, in run_controller
    if not gloo_built(verbose=verbose):`
`  File "/anaconda_new/envs/py36_pytorch_ccl_hvd/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/common/util.py", line 119, in wrapper
    retval = f(*args, **kwargs)`
`  File "/anaconda_new/envs/py36_pytorch_ccl_hvd/lib/python3.6/site-packages/horovod-0.19.2-py3.6-linux-x86_64.egg/horovod/common/util.py", line 152, in gloo_built
    raise RuntimeError('Failed to determine if Gloo support has been built. '`
`RuntimeError: Failed to determine if Gloo support has been built. Run again with --verbose for more details.`

**Comment by tgaddair** [comment]
Hey @shirosankaku, I'm not sure that we've tested Gloo + CCL before.  Does this error also occur if you don't specify `HOROVOD_CPU_OPERATIONS=CCL`?
