### ISSUE TITLE
Broadcasting to all processes not only tensors

### ISSUE THREAD

**Issue by P-Light** [horovod/horovod#2114]
**Is your feature request related to a problem? Please describe.**
I resume training and start from  epoch = n > 0. On the master process it is possible to set  start epoch = n, while slave process needs to get start epoch value from the master. 

**Describe the solution you'd like**
Implement horovod.broadcast() for objects like int, float, list, etc.

**Describe alternatives you've considered**
Now I'm using this workaround:
`self.start_epoch = hvd.allreduce(
                                    torch.IntTensor(
                                        [self.start_epoch]),
                                    op=hvd.Sum,
                                    ).tolist()[0]`

**Comment by tgaddair** [comment]
Hey @P-Light, we do have a [hvd.broadcast_object](https://horovod.readthedocs.io/en/stable/api.html#horovod.torch.broadcast_object) function for this purpose.  Does this work for your use case?

**Comment by P-Light** [comment]
@tgaddair, I didn't notice this function before. It works, thank you!
