### ISSUE TITLE
If each process has the different train steps, how to synchronize the result after one epoch, Can fast processes wait for slow processes to complete?

### ISSUE THREAD

**Issue by leodemo** [horovod/horovod#2118]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.12
3. Horovod version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
![image](https://user-images.githubusercontent.com/6127696/87848679-0d213e00-c915-11ea-966c-e61b5b90a66b.png)

**Comment by tgaddair** [comment]
Hey @leodemo, you can solve this by calling [hvd.join()](https://github.com/horovod/horovod/blob/master/horovod/tensorflow/mpi_ops.py#L201) at the end of the epoch.  That'll ensure that workers that have already finished will wait for other workers to complete before proceeding to the next step.

**Comment by leodemo** [comment]
@

> Hey @leodemo, you can solve this by calling [hvd.join()](https://github.com/horovod/horovod/blob/master/horovod/tensorflow/mpi_ops.py#L201) at the end of the epoch. That'll ensure that workers that have already finished will wait for other workers to complete before proceeding to the next step.
> 
> Note that this feature is not yet in a released version of Horovod, so you'll need to install from the `master` branch to use it.

@tgaddair Which branch contains the function of join？

**Comment by tgaddair** [comment]
It's in the master branch.

**Comment by leodemo** [comment]
> It's in the master branch.

thx, i will try this.

**Comment by leodemo** [comment]
> Hey @leodemo, you can solve this by calling [hvd.join()](https://github.com/horovod/horovod/blob/master/horovod/tensorflow/mpi_ops.py#L201) at the end of the epoch. That'll ensure that workers that have already finished will wait for other workers to complete before proceeding to the next step.
> 
> Note that this feature is not yet in a released version of Horovod, so you'll need to install from the `master` branch to use it.

BTW, When will this feature be released？

**Comment by tgaddair** [comment]
We plan to have v0.20.0 released some time in August.  Until then, you can always install directly from master:

```
pip install --no-cache-dir git+https://github.com/horovod/horovod.git@master
```
