### ISSUE TITLE
How can I use elastic horovod

### ISSUE THREAD

**Issue by jiaqianjing** [horovod/horovod#2125]
**Your question:**
How can I use [elastic horovod](https://horovod.readthedocs.io/en/latest/elastic_include.html)?
Following this guidance (https://github.com/horovod/horovod/blob/master/docs/docker.rst), I found that the installed version of horovod is 0.19.5.
When I build horovod from source code of master branch, I found that the version of horovod is 0.19.2.

None of these meet the requirements of the  elastic horovod version.
![image](https://user-images.githubusercontent.com/16071449/88129180-0b53c500-cc0a-11ea-98ed-67034c4cf09d.png)

**Comment by jiaqianjing** [comment]
OK, I see. Horovod from source code of master branch has been elastic, but only version is 0.19.2.

**Comment by tgaddair** [comment]
Hey @jiaqianjing, sorry for the confusion.  Yes, we do not typically update the `__version__` until we cut a new release.  0.20.0 should be officially released in August.

**Comment by weberxie** [comment]
Hi @tgaddair , thanks for your great work! I'm very looking forward to the version 0.20.0, when will it be available?

**Comment by tgaddair** [comment]
Hey @weberxie, we're hoping to release later this week.
