### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by collinabidi** [horovod/horovod#2137]
**Environment:**
1. Framework:: Pytorch
2. Framework version: 1.5.1
3. Horovod version: 0.19.2
4. MPI version: OpenMPI 4.0.3
5. CUDA version: NA
6. NCCL version: NA
7. Python version: 3.7.0
8. OS and version: Red Hat Enterprise Linux 7
9. GCC version: 8.2.0 / 4.8.5 (See below)

**Your question:**

Hi there. I'm attempting to install Horovod from source on a Red Hat cluster for distributed CPU learning. I have a couple of questions about installation process. I'm currently attempting to follow the [steps from this issue](https://github.com/horovod/horovod/issues/155) but I don't think my errors are related to this.

Question 1. **How do I tell Horovod to use the correct gcc/g++?**

_Relevant Information_
I use the following commands to install Horovod:
```
HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MPI=1 HOROVOD_WITHOUT_GLOO=1 HOROVOD_BUILD_ARCH_FLAGS=-L  HOROVOD_CPU_OPERATIONS=MPI HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1  python setup.py clean
```
followed by
```
HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MPI=1 HOROVOD_WITHOUT_GLOO=1 HOROVOD_BUILD_ARCH_FLAGS=-L  HOROVOD_CPU_OPERATIONS=MPI HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1  python setup.py install
```
I get the following warnings when compiling:
![warnings](https://user-images.githubusercontent.com/29078081/88320434-95278f00-cceb-11ea-8109-5cd3eb7b3252.PNG)

It seems like the ```gcc``` and ```g++``` versions used by Horovod (4.8.5) do not match the ones that I load in my virtual environment (8.2.0).
```which gcc``` and ```which g++``` both do see the correct versions 8.2.0 for both. It therefore seems that Horovod is using ```\usr\bin\gcc``` and ```\usr\bin\g++``` though (which output version 4.8.5), even though I've explicitly loaded the correct ones using ```module load gcc/8.2.0```.

Question 2. **How do I fix** ```libgcc_s.so.1 must be installed for pthread_cancel to work```?

_Relevant Information_
I've followed the install steps, troubleshooting guide, and looked at several previous issues, but I always end up with the above error when attempting ```horovodrun --check-build```.

This seems like an issue with PATH, so I found where ```libgcc_s.so.1``` resides (/usr/lib/) and put it at the front of my PATH variable. I then appended to my ```LD_LIBRARY_PATH``` just to be sure.

**Comment by tgaddair** [comment]
Hey @collinabidi, when installing Horovod, can you try setting the `CC` and `CXX` environment variables to point to the right versions of `gcc` and `g++` respectively?

**Comment by collinabidi** [comment]
Hey @tgaddair , that seems to have cleared up some of the issues during compilation!

Another set of errors came up though:

1. During compilation, setup.py complains about PyTorch version being built without ROCm.

![no_rocm](https://user-images.githubusercontent.com/29078081/88324274-76c49200-ccf1-11ea-9c5f-d205c5fb62c5.png)

It sounds like I shouldn't just ```pip install torch``` and I should find a way to get ROCm on my system as well. Does this sound correct?

2. When doing ```horovodrun --check-build``` now, there seems to be an issue with loading the ```horovod.run``` module.

![horovod_errors](https://user-images.githubusercontent.com/29078081/88324415-affd0200-ccf1-11ea-9b89-25b61ebd0e7e.png)

**Comment by tgaddair** [comment]
Hey @collinabidi, the ROCm print out is not an issue unless you have AMD GPUs.

Regarding the error message in `horovodrun --check-build` are you installing from source?  It looks like something in your path may be messed up.  I would try running `python -c "import horovod.run"`) and check that that works.  It may be that there are multiple versions of Horovod installed on your system that need to be uninstalled.

**Comment by collinabidi** [comment]
Running ```python -c "import horovod.run"``` results in ```ModuleNotFoundError: No module named 'horovod.run'``` directly after the ```FLAGS python setup.py install``` process. However, ```python -c "import horovod"``` works just fine.

**Comment by tgaddair** [comment]
Try running`python -c "import horovod; print(horovod.__path__)"`, then check the contents of that directory.  Is there a folder called `run`?

**Comment by collinabidi** [comment]
Hey @tgaddair , there is no folder called ```run``` but there is one called ```runner```. Interesting.

**Comment by tgaddair** [comment]
Looks like you installed from master.  We recently renamed `run` to `runner`.

But also looks like your `horovodrun` script is out of date somehow.  Possibly your path is picking up `horovodrun` from an old install of Horovod?

**Comment by collinabidi** [comment]
So I wiped my horovod install and re-installed from ```master``` (if this is correct) using the ```--recursive``` option. I then built and ran the ```horovodrun --check-build``` with nothing being printed in the output file. Running the ```pytorch_mnist.py``` example seemed to work though. Thank you for all the help! I had been pulling my hair out for a couple of weeks trying to figure this out.

The following list is a summary of what helped me get Horovod working, for anyone struggling with this in the future:

1. Creating a new virtual environment with ```mkvirtualenv```
2. Removing horovod completely and cloning from master:
```rm -rf horovod``` and ```git clone --recursive https://github.com/horovod/horovod.git```

3. Ensuring that both ```conda``` and ```pip``` **do not** have horovod installed:
```conda list``` and ```pip list```

4. Setting the ```CC``` and ```CXX``` environment variables to use the correct versions of ```gcc``` and ```g++```:
```export CC=/path/to/gcc``` and ```export CXX=/path/to/g++```

5. Setting the ```LD_LIBRARY_PATH``` to the directory where libgcc_s.so.1 is located:
```export LD_LIBRARY_PATH=/path/to/libgcc_file/```

6. Doing a clean install of horovod **without pip or conda**:
```python setup.py clean``` and ```FLAGS python setup.py install```

7. Running an example with the ```mpirun``` command, as I am using OpenMPI (these --mca flags are specific to my setup):
```
mpirun -n 8 -bind-to none -map-by slot \
        --mca mpi_cuda_support 0 \
        --mca pml ucx --mca osc ucx --mca scoll ucx \
        --mca atomic ucx --mca orte_base_help_aggregate 0 \
        --mca btl ^vader,tcp,openib,uct -x UCX_UNIFIED_MODE=1 \
        -x LD_LIBRARY_PATH python3 examples/pytorch_mnist.py
```
