### ISSUE TITLE
Logging doesn't work correctly

### ISSUE THREAD

**Issue by abcinje** [horovod/horovod#2142]
**Environment:**
1. Framework: Pytorch
2. Framework version: 1.4.0
3. Horovod version: 0.19.2
4. MPI version: 4.0.0
5. CUDA version:
6. NCCL version:
7. Python version: 3.6.9
8. OS and version: 
9. GCC version:

Hello.

I found that logging macro sometimes doesn't work correctly.
Specifically, logged messages are mixed up when running applications using multiple nodes.
When logging, I set the log level as **TRACE**.
The following is an example I have gotten.
```
[1,2]<stdout>:[[1,3]<stdout>:[2020-07-22 14:10:47.953428: T horovod/common/controller.cc:758] Created response of size 2048
```
It has to be two seperated messages starting with [1,2] and [1,3].
But I doubt that using multiple nodes is the cause of the issue as getting the following log
```
[1,1]<stdout>:[[1,1]<stdout>:2020-07-22 14:10:48. 87263: T horovod/common/operations.cc:589] [1]: Performing allreduce.layer4.0.downsample.0.weight
```
In this case, the ranks of two mixed messages are same.

BTW, how can I avoid this problem when logging?
If it is actually a problem, it should be changed into an atomic operation...?

**Comment by tgaddair** [comment]
Hey @abcinje, unfortunately this is mostly unavoidable.  When using MPI, printing messages from different workers is out of our control.  When using Gloo, we could opt to only print out a line containing a new line character, but that breaks other features, like a progress bar the relies on carriage returns to show progress on the same line.

**Comment by abcinje** [comment]
@tgaddair Thanks for your reply!
