### ISSUE TITLE
Hang when using multiple nodes with GPUs

### ISSUE THREAD

**Issue by bilgeacun** [horovod/horovod#215]
I'm seeing the below hang with the ImageNet example code when running on more than 1 node each having 4 GPUs. 

```
mpirun -np 32 - H s1:4,s2:4,...s8:4 -bind-to none -map-by slot -x LD_LIBRARY_PATH python keras_imagenet_resnet50.py
...
Epoch 1/90
228/625 [=========>....................] - ETA: 6:32 - loss: 7.6713 - acc: 0.0073 - top_k_categorical_accuracy: 0.0276---------------------
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. Stalled ops: training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv1_1_BiasAdd_grad_BiasAddGrad_0 [ready ranks: 21, 25, 26, 27, 28, 29, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 1, 3, 0, 15, 17, 18, 20, 22, 23, 24, 31, 8, 19, 2, 30], training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_335_0 [ready ranks: 21, 25, 26, 27, 28, 29, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 1, 3, 0, 15, 17, 18, 20, 22, 23, 24, 31, 8, 19, 2, 30]
```
It keeps printing the warning and training does not progress. It looks like only 1 or only a few ranks do not contribute to allreduce when it hangs - in this case only rank # 16 is missing. Also, the hang does not occur when running only on the CPUs with the same setup.

```
Keras==2.1.2
horovod==0.12.1
Open MPI==2.0.1
```

I have read the troubleshoot page but none of the solutions help. Do you have any other tips?

**Comment by alsrgv** [comment]
@bilgeacun, can you try upgrading to Open MPI 3.0.0 just to rule it out, check whether you have any errors in `dmesg`, especially on the node that is late, and also run [TF benchmark](https://github.com/uber/horovod/blob/master/docs/benchmarks.md) on all nodes, and just on that GPU (using CUDA_VISIBLE_DEVICES)?

**Comment by bilgeacun** [comment]
The hang is not deterministic -- missing ranks are different in consequent runs using the same nodes. No errors in `dmesg` and TF benchmark runs fine on all nodes. I'm having a different problem with OpenMPI 3.0.0 in my system, it seems not related to horovod. 
Setting keras workers in model.fit_generator to 1 does not make the hang disappear but it makes it happen on larger scale. Maybe there's some a race condition?

**Comment by alsrgv** [comment]
@bilgeacun, what if you set workers to 0, does it help?  Also, can you try to upgrade to latest Keras?

**Comment by bilgeacun** [comment]
@alsrgv Same hang occurs with 0 workers, and with keras-2.1.4, also with and without NCCL too.

**Comment by alsrgv** [comment]
@bilgeacun, if TF benchmark is working without hiccups, I suspect the issue is with reading / processing the data.  Something is causing an imbalance in your load pattern.

**Comment by yongwww** [comment]
I saw the same issue using tensorflow 1.10, horovod  0.14.1, cuda 9.0, cudnn  7.2, nccl 2.2 and openmpi 3.1 on AWS P3.16xl instances

**Comment by mrfox321** [comment]
Experiencing the same at the end of an epoch using

tensorflow 1.10, horovod 0.14.1, cuda 9.2, cudnn 7.2, nccl 2.2 and openmpi 2.0.2.

It is always at the end of an epoch.  Usually after the 2nd epoch.  Sometimes it de-syncs early, sometimes later.  Going to disable checkpointing to see if that keeps it going for longer.

It is hanging on a single node with 2x GPUs.

Using Dataset API for feeding.

**Comment by alsrgv** [comment]
@yongwww, @mrfox321, when you see the hang, could you try running `gdb -p <pid> -ex "thread apply all bt"` for each of the processes and share all the logs as a [gist](https://gist.github.com)?  This should help to pinpoint the cause of the hang.

**Comment by mrfox321** [comment]
`mpirun -np 2    
-H localhost:2     -bind-to none -map-by slot     
-x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x HOROVOD_TIMELINE   -mca pml ob1 -mca btl ^openib     python train_gen.py`

will send a stack trace soon.

**Comment by alsrgv** [comment]
@mrfox321, these flags should work on OpenMPI 2.1.1, but I'm not really sure about OpenMPI 2.0.2.

**Comment by mrfox321** [comment]
@alsrgv switched to SSD and the GPUs no longer hang.  Something about the I/O on HDD leads to a race condition (poisson process?).  

FYI, Horovod is ~25% slower with CUDA 10 on RNNs (cudnn).
