### ISSUE TITLE
We cannot run examples using horovod:latest docker image.

### ISSUE THREAD

**Issue by workingloong** [horovod/horovod#2152]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.1.0
3. Horovod version: 0.19.5
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. Spark / PySpark version:
9. OS and version:
10. GCC version:

**Bug report:**
The TensorFlow APIs in examples are deprecated by TensorFlow 2.1.0, such as `tf.train.AdamOptimizer`. However, the [docker file](https://github.com/horovod/horovod/blob/master/Dockerfile.cpu) set the TF-2.1.0. So, we cannot run the examples in the docker container using this image.

**Comment by tgaddair** [comment]
Hey @workingloong, which examples are you referring to?  For TensorFlow 2, you should use the examples that start with `tensorflow2_`.

**Comment by workingloong** [comment]
> Hey @workingloong, which examples are you referring to? For TensorFlow 2, you should use the examples that start with `tensorflow2_`.

Oh, Thanks. I use examples that start with `tensorflow_`. And we can close the issue first.
