### ISSUE TITLE
divide parameters into two optimizations

### ISSUE THREAD

**Issue by zanonShao** [horovod/horovod#2154]
Hey @tgaddair , I divide the parameters in a model into two parts, then use optimization1 and optimization2 to contral the update of them. But when the second execution to` loss.back()` There will be an error:

`:RuntimeError: Gradients were computed more than backward_passes_per_step times before call to step(). Increase backward_passes_per_step to accumulate gradients locally.`

I think that's  caused by another part of parameter's gradients have not been used by `step()` therefore `self._handles` is not None (some overlap).
So how can I use horovod in this situation？

now I code like：
```
    optimizer_1 = hvd.DistributedOptimizer(optimizer_1, named_parameters=model.named_parameters_1)
    optimizer_2 = hvd.DistributedOptimizer(optimizer_2, named_parameters=model.named_parameters_2)
 
    for i in range(...):
        optimizer_1.zero_grad()
        logits = model(input)
        loss = criterion(logits, target)
        loss.backward()    --------------------->second execution to` loss.back()` There will be an error
        optimizer.step()
```

_Originally posted by @zanonShao in https://github.com/horovod/horovod/issues/1549#issuecomment-667704633_

**Comment by tgaddair** [comment]
Hey @zanonShao, can you take a look at this comment -- https://github.com/horovod/horovod/issues/1417#issuecomment-588367250 -- and let me know if it addresses your issue?

**Comment by zanonShao** [comment]
Thank you for your prompt reply. I tried your suggestion, and glad this method works ^_^
After each optimizer.step(), call another optimizer's `synchronize()` to blank run and clear() the` _handles`.Thus solved my problem.

after I code like：
```
    optimizer_1 = hvd.DistributedOptimizer(optimizer_1, named_parameters=model.named_parameters_1)
    optimizer_2 = hvd.DistributedOptimizer(optimizer_2, named_parameters=model.named_parameters_2)
 
    for i in range(...):
        #train the parameters in optimizer_1
        optimizer_1.zero_grad()
        logits = model(input)
        loss = criterion(logits, target)
        loss.backward()    
        optimizer_1.step()
        optimizer_2.synchronize()                          <-------------------------------------

        #train the parameters in optimizer_2
        optimizer_2.zero_grad()
        logits = model(input)
        loss = criterion(logits, target)
        loss.backward()    
        optimizer_2.step()
        optimizer_1.synchronize()                         <-------------------------------------
```

**Finally, will this method slow down the training process?**

**Comment by talkhaldi** [comment]
I think so, because you'll be calling your model's "forward" (model(input)) twice, and the "backward" twice.

I'm also trying to find a way to implement this:

```
no_decay = ["bias", "LayerNorm.weight"]
optimizer_grouped_parameters = [
        {
            "params": [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)],
            "weight_decay": args.weight_decay,
        },
        {"params": [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], "weight_decay": 0.0},
    ]

optimizer = AdamW(optimizer_grouped_parameters, lr=args.learning_rate, eps=args.adam_epsilon)
```

in Horovod, but it seems hvd.DistributedOptimizer doesn't support grouped parameters for the "named_parameters" argument. (Please correct me if I'm wrong!)

**Comment by talkhaldi** [comment]
Okay, I managed to get it working by just passing model.named_parameters() to the DistributedOptimizer, while the grouped_params are only passed to the base optimizer.

**Comment by tgaddair** [comment]
Glad you got it working @talkhaldi.

@zanonShao, this should not noticeably affect performance to add the extra `optimizer.synchronize()`.  There should be no additional allreduce calls that are made as a result of this, it simply blocks on the async handles from the previous allreduce calls and clears them.
