### ISSUE TITLE
run on multiple cpu nodes

### ISSUE THREAD

**Issue by zlwzlwzlw** [horovod/horovod#2159]
**Environment:**
1. Framework: TensorFlow
2. Framework version:1.14
3. Horovod version:0.19.5
4. MPI version:4.0.4
5. CUDA version:
6. NCCL version:
7. Python version:3.6.5
8. OS and version:centos-7.6
9. GCC version:4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before?yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
SSH was successful into all the remote hosts
node204---->ifconfig network name em1
node211---->ifconfig network name eno1
When I run command horovodrun -np 4 -H node204:2,node211:2 --network-interface "em1,eno1" --start-timeout 300 --verbose python tensorflow_mnist.py

ERROR:
WARNING: An invalid value was given for btl_tcp_if_include.  This
value will be ignored.
  Local host: node211
  Value:      em1
  Message:    Unknown interface name

At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[56707,1],2]) is on host: node211
  Process 2 ([[56707,1],0]) is on host: node204
  BTLs attempted: self vader
Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
[1,2]<stderr>:Error in MPI_Isend(139931378106736, 1, 0x7f4456a7cc80, 0, -27, 139931488365712) (-12)
[1,2]<stderr>:Error in NBC_Start_round() (-12)
[1,2]<stderr>:Error in NBC_Start_round() (-1)

**Comment by wanzaiqidao** [comment]
hello, have you fixed the issue? I meet the same issue.
