### ISSUE TITLE
Multiple MPI ranks per GPU process

### ISSUE THREAD

**Issue by mkovalski** [horovod/horovod#216]
Hello,

I wanted to know if there's a way to use multiple processes per GPU rank. For example, say I wanted there to be 4 total processes per GPU, where 3 of those processes simply do data augmentation and the other to get the data from the other 3 processes and feed to the training. I was able to set this up using a single GPU using MPI Groups without horovod, but now I wanted to scale this up. Would something like this be possible?

**Comment by alsrgv** [comment]
@mkovalski, would it work if we had a way to set up a communicator across a specific list of ranks as part of `hvd.init()` - do you know that information up front, or would you need MPI to discover topology?

**Comment by mkovalski** [comment]
@alsrgv Ideally, I'd use MPI first to find topology but I can always grab this from some environment variables I use instead (for my use, grab whatever slurm environment variables I can)

**Comment by alsrgv** [comment]
@mkovalski, that seems like sub-par experience.  I guess we could also add `mpi_init=False` to `hvd.init()` in case you ran `MPI_Init_thread()` before using mpi4py.  Would those two things be ideal?

**Comment by mkovalski** [comment]
@alsrgv Yeah that would work really well then, that in addition to specifying ranks to hvd init would be great!

**Comment by alsrgv** [comment]
OK, excellent.  This should be pretty straightforward.  I will mark this as a "contribution welcome" task in case you want to work on it before we get to it :-)

**Comment by alsrgv** [comment]
@mkovalski, BTW, another way to solve this was mentioned in #105, I wonder if it may be relevant to you, too.  The idea was to be able to specify a subset of ranks per operation.  The benefit is that you can do separately an allreduce within node and an allreduce between nodes.  The downside is that all workers would still participate in global MPI coordination, but those are lightweight messages and it should not really be a problem.
