### ISSUE TITLE
Took a hour before starting the training

### ISSUE THREAD

**Issue by Doffery** [horovod/horovod#2165]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.40
3. Horovod version: 0.19.0
4. MPI version: mpiexec (OpenRTE) 3.0.0
5. CUDA version: 10.0.130
6. NCCL version:  2.7.6
7. Python version: 3.7
8. OS and version: Ubuntu 16.4
9. GCC version: 5.4.0

**Your question:**
Please ask your question here.
I'm running on spark cluster on Azure Databricks, prepared the data outside of the train_hvd function, which is called HorovodRunner to do horvord distrsibuted training. Then wrap it inside of train_hvd. Raw text data is like 1Gb size.
It took hours to get the training start. Quite confused what's happening.

```
def train_hvd(training_generator,
                  bilstm_model,
                  crf_model,
                  lr_decay_trigger,
                  optm,
                  batch_size,
                  epoch_num,
                  word_to_ix,
                  char_to_ix,
                  char_embedding,
                  validation_generator,
                  checkpoint_dir,
                  crf_layer):
    hvd.init()
    if torch.cuda.is_available():
        torch.cuda.set_device(hvd.local_rank())
    parameters = list(bilstm_model.parameters())+list(crf_model.parameters())
    named_parameters = list(bilstm_model.named_parameters())+list(crf_model.named_parameters())
    if char_embedding:
        for idx, conv in enumerate(bilstm_model.conv_layers):
            parameters += list(conv.parameters())
            for pname, pvalue in conv.named_parameters():
                named_parameters.append(("Conv_{}".format(idx)+pname, pvalue))
    if optm == 'adam':
        optimizer = optim.Adam(parameters,
                               lr=init_lr, weight_decay=1e-4)
    else:
        optimizer = optim.SGD(parameters,
                              lr=init_lr, weight_decay=1e-4)
    optimizer = hvd.DistributedOptimizer(optimizer, named_parameters)
    my_lr_scheduler = optim.lr_scheduler.ExponentialLR(optimizer=optimizer,
                                                       gamma=lr_rate_decay)
    if char_embedding:
        for conv in bilstm_model.conv_layers:
            hvd.broadcast_parameters(conv.state_dict(), root_rank=0)
    hvd.broadcast_parameters(bilstm_model.state_dict(), root_rank=0)

    hvd.broadcast_parameters(crf_model.state_dict(), root_rank=0)
  
    train_sampler = torch.utils.data.distributed.DistributedSampler(
                training_generator, num_replicas=hvd.size(), rank=hvd.rank())

    train_loader = torch.utils.data.DataLoader(training_generator, batch_size=None, sampler=train_sampler)
    Training.training(train_loader,
                  bilstm_model,
                  crf_model,
                  optimizer,
                  my_lr_scheduler,
                  lr_decay_trigger,
                  optm,
                  batch_size,
                  epoch_num,
                  word_to_ix,
                  char_to_ix,
                  char_embedding,
                  validation_generator,
                  checkpoint_dir=model_path,
                  crf_layer=crf_layer)
```

Detailed Log:

> /databricks/python/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>   from collections import Mapping, MutableMapping
> Using TensorFlow backend.
> HorovodRunner will stream all training logs to notebook cell output. If there are too many logs, you
> can adjust the log level in your train method. Or you can set driver_log_verbosity to
> 'log_callback_only' and use a HorovodRunner log  callback on the first worker to get concise
> progress updates.
> The global names read or written to by the pickled function are {'enumerate', 'hvd', 'Training', 'lr_rate_decay', 'init_lr', 'list', 'model_path', 'optim', 'torch'}.
> The pickled object size is 1811276997 bytes.
> The pickled object size is greater than 10MB. It might cause training slow to start. You might
> consider:
> * Loading large datasets inside the main function instead of materializing them on the driver.
> * Avoid pulling unnecessary variables from the notebook context.
> 
> ### How to enable Horovod Timeline? ###
> HorovodRunner has the ability to record the timeline of its activity with Horovod  Timeline. To
> record a Horovod Timeline, set the `HOROVOD_TIMELINE` environment variable  to the location of the
> timeline file to be created. You can then open the timeline file  using the chrome://tracing
> facility of the Chrome browser.
> 
> HorovodRunner was called with np=2, which is greater than the maximum processes that can be placed
> on this cluster. This cluster can place at most 1 processes on 1 executors. Training won't start
> until there are enough workers on this cluster. You  can increase the cluster size or cancel the
> current run and retry with a smaller np.
> Start training.
>

**Comment by EnricoMi** [comment]
The log output says:

    The pickled object size is 1811276997 bytes.

Which means your code has some datastructure that is 1.8 GB in size, which is very slow to pickle (serialize) and send over the wire. I think getting this number down has to be targeted first.

**Comment by Doffery** [comment]
> The log output says:
> 
> ```
> The pickled object size is 1811276997 bytes.
> ```
> 
> Which means your code has some datastructure that is 1.8 GB in size, which is very slow to pickle (serialize) and send over the wire. I think getting this number down has to be targeted first.

Thanks for quick reply!

That's should be mostly space took by my training data.
Do you know how can I solve that with reducing training data? I assumed this size of training data should be common.

Thanks.

**Comment by tgaddair** [comment]
Hey @Doffery, my suggestion here would be to pull the model into the training function, instead of passing it as a parameter.  That way, the model does not need to be pickled.

So instead of writing:

```
def train_hvd(training_generator,
                  bilstm_model,
                  crf_model, ...):
```

You could write:

```
def train_hvd(training_generator,
                   ...):
   bilstm_model = create_bilstm_model()
   crf_model = create_crf_model()
```

**Comment by Doffery** [comment]
> Hey @Doffery, my suggestion here would be to pull the model into the training function, instead of passing it as a parameter. That way, the model does not need to be pickled.
> 
> So instead of writing:
> 
> ```
> def train_hvd(training_generator,
>                   bilstm_model,
>                   crf_model, ...):
> ```
> 
> You could write:
> 
> ```
> def train_hvd(training_generator,
>                    ...):
>    bilstm_model = create_bilstm_model()
>    crf_model = create_crf_model()
> ```

Thanks @tgaddair  for your advice. I tried your solution, it's still using a great amount of time to prepare the training. My model size of not big, only few million parameters.

**Comment by Doffery** [comment]
Any new comment on this problem?

**Comment by tgaddair** [comment]
Hey @Doffery, sorry for the late response.  As a next step, I would try reducing your training function to something very minimal, like:

```
def train_hvd():
    import horovod.torch as hvd
    hvd.init()
    return hvd.rank()
```

And then building up more args until you reach the same behavior.  My guess is that something you're passing in is causing this issue, but it's unclear what at this time.
