### ISSUE TITLE
some question about w/o gdr and +gdr.

### ISSUE THREAD

**Issue by DeruiLiu** [horovod/horovod#2168]
i want to test the performance with horovod IB +NCCL w/o GDR and Horovod IB +NCCL +GDR.
but i don't know how to start/off GDR.
my start code as below: does i use GDR? and the performance is about 149.
mpirun --allow-run-as-root -np 2 \
    -H 172.168.30.26:1,172.168.30.25:1 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python2 /root/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py \
        --model vgg16 \
        --batch_size 64 \
        --variable_update horovod \
        --data_dir /root/img \
        --data_name imagenet \
        --num_batches=50

**Comment by DeruiLiu** [comment]
when i run tf_cnn_benchmarks.py, i find i can use grpc+gdr in server_protocol, but when i use this parameter, the performance is worse than grpc+verbs.  so  how can i use gdr correctly to run tf_cnn_benchmarks.py?
my another start code is as below:
python /root/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py \
--server_protocol=grpc+verbs \
--model=vgg16 --variable_update=parameter_server \
--batch_size=64  --num_batches=50 --num_warmup_batches=10 \
--local_parameter_device=gpu --num_gpus=1 \
--job_name=ps  --task_index=0 \
--ps_hosts=172.168.30.25:10011 \
--worker_hosts=172.168.30.26:50012 &

**Comment by tgaddair** [comment]
Hey @DeruiLiu, GDR should work automatically with Horovod, provided it is enabled and [nv_peer_memory](https://github.com/Mellanox/nv_peer_memory) is installed.  Can you check that NCCL support is enabled by running `horovodrun --check-build` and sharing the output?

**Comment by DeruiLiu** [comment]
> Hey @DeruiLiu, GDR should work automatically with Horovod, provided it is enabled and [nv_peer_memory](https://github.com/Mellanox/nv_peer_memory) is installed. Can you check that NCCL support is enabled by running `horovodrun --check-build` and sharing the output?

yeah! nv_peer_memory is loaded. when i run tf_cnn_benchmarks.py， server_protocol use parameter grpc+gdr is worse than grpc + verbs, i don't know why? so i have a question as above. does anyone has same question?

root@s36-2288H-V5:~# /etc/init.d/nv_peer_mem status
nv_peer_mem module is loaded.
root@s36-2288H-V5:~# horovodrun --check-build
Horovod v0.19.5:

Available Frameworks:
    [X] TensorFlow
    [ ] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [ ] Gloo

Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [ ] Gloo
