### ISSUE TITLE
difference between run multiple processes in one node and run multiple processes in multiple nodes

### ISSUE THREAD

**Issue by weberxie** [horovod/horovod#2171]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.2
3. Horovod version: 0.17
4. MPI version: 3.0
5. CUDA version: 9.0
6. NCCL version: 2.4.6
7. Python version: 3.6
8. OS and version: CentOS 7
9. GCC version: Gcc 5

**Your question:**
I'm training MobileNetV2 with 4 V100 cards, then I find that training it with 4 processes in 1 docker with 4 V100 cards is about worse 1% on Top-1 error compare with training it with 4 processes in 4 dockers  on 4 nodes each with 1 V100 card.

So, is there any difference about Horovod on there two training mode?

Thanks!

**Comment by tgaddair** [comment]
Hey @weberxie, as long as the number of processes remains the same, there should not be any differences in terms of convergence between training within a host vs between hosts.  There is, however, non-determinism when training that can vary results from one run to the next.  Are you seeing this convergence degradation consistently across multiples runs?

**Comment by weberxie** [comment]
Yes, this convergence degradation is consistently. Thanks for your reply, I'll dive into it more deeper.
