### ISSUE TITLE
does it work if I runallreduce on tf.indexedslices

### ISSUE THREAD

**Issue by gongjingcs** [horovod/horovod#2173]
**Your question:**
Please ask your question here.

**Comment by gongjingcs** [comment]
hi, I found that it also works if I run horovod allreduce on tf.indexedslices, so if I want to use allreduce on tf.indexedslices, I don't need to convert it to tf.tensor? I will be grateful for your reply

    # if isinstance(tensor, tf.IndexedSlices):
    #     # TODO: Need to fix this to actuall call Adasum
    #     if op == Adasum:
    #         raise NotImplementedError('The Adasum reduction does not currently support sparse tensors. As a '
    #                                   'workaround please pass sparse_as_dense=True to DistributedOptimizer')
    #     with tf.device(device_sparse):
    #         # For IndexedSlices, do two allgathers instead of an allreduce.
    #         horovod_size = tf.cast(size(), tensor.values.dtype)
    #         values = allgather(tensor.values)
    #         indices = allgather(tensor.indices)
    #         # To make this operation into an average, divide allgathered values by
    #         # the Horovod size.
    #         new_values = (values / horovod_size) if op == Average else values
    #     return tf.IndexedSlices(new_values, indices,
    #                             dense_shape=tensor.dense_shape)
    # else:

**Comment by tgaddair** [comment]
Hey @gongjingcs, that's correct, you can use `hvd.allreduce` with `tf.IndexedSlices`.  Under the hood, instead of doing an allreduce, we will instead do an allgather operation.  This works well if your slices are relatively sparse.  If they are more dense, you may be better off using allreduce anyway and running `hvd.allreduce(..., sparse_to_dense=True)`.
