### ISSUE TITLE
how to debug horovod remotely with pycharm

### ISSUE THREAD

**Issue by benjiachong** [horovod/horovod#2174]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) PyTorch
2. Framework version: 1.6.0
3. Horovod version:0.19.5
4. MPI version:4.0.4
5. CUDA version:11.0
6. NCCL version:2.7.8
7. Python version:3.8
8. OS and version:ubuntu18.04
9. GCC version:7.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

Firstly, I can't find "horovod.run.run"(only "horovod/run/runner.py" or "horovod/run/run_task.py") as others said.
Secondly, I try the configuration as follows ( add environment variable and with full path of horovodrun). It can run normally but can't stop, and can't debug.

![1](https://user-images.githubusercontent.com/16750835/89913634-87986180-dc26-11ea-8390-30acf9c7c220.jpg)

What's the matter of my project? or the matter of horovod?

**Comment by tgaddair** [comment]
Hey @benjiachong, which part of the code are you attempting to debug?  

If it's your training script, then I would suggest just running as a single python process (not using `horovodrun`) and debugging normally.

If it's the Horovod launch script, then you can run `python -m horovod.run.runner.run` (this path is thankfully being changed in v0.20).

If you need to debug Horovod itself (the distributed training piece), then I suggest creating a [timeline](https://github.com/horovod/horovod/blob/master/docs/timeline.rst) to see what's happening under the hood.  Most of the logic here is written in C++ and the workers are running in separate processes, so PyCharm will not be able to help with debugging.

**Comment by benjiachong** [comment]
@tgaddair Thanks for your reply. I run my code in linux shell by "horovodrun -np 4 -H localhost:4 python  main.py".  It's OK.  Now I need to debug "main.py", which is my own training script lanched by Horovod. I config pycharm as follows. It still reminds me "No module named horovod.run.runner.run".  Is there something wrong to my environment variable setting, or something else?
![image](https://user-images.githubusercontent.com/16750835/89963293-ca375980-dc79-11ea-819a-91d4b521172b.png)

**Comment by benjiachong** [comment]
Hey @tgaddair. Thanks for your advice. I set the module name as "horovod.run.runner" in pycharm, it seems OK. I find horovodrun also use horovod.run.runner.

There also has 2 problem. 
1. When I train my script by setting module name as "horovod.run.runner", I can't stop the process.
2. Debugging still is not OK.
![image](https://user-images.githubusercontent.com/16750835/89972947-b4359300-dc91-11ea-8cdb-d0616a3daa29.png)
