### ISSUE TITLE
Does horovod support apex's SyncBatchNorm?

### ISSUE THREAD

**Issue by MingYang-buaa** [horovod/horovod#2183]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) 
Pytorch
2. Framework version: 
1.6.0
3. Horovod version:
0.19.5
4. MPI version:
1.0
5. CUDA version:
10.1
6. NCCL version:
2.0
7. Python version:
3.7.7
8. OS and version:
ubuntu 18.04
9. GCC version:
6.5.0
**Checklist:**
1. Did you search issues to find if somebody asked this question before?
yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?
yes

**Your question:**
Please ask your question here.
Q: Does horovod support apex's SyncBatchNorm? I'm trying to train a model with horovod and apex(using mixed precision and sync bn).It will get error message when set opt_level to "O1". Also I try to set opt_level to "O0", it looks like be fine but the sync bn's grad will be always 0(about weights and bias).
main code as follow:

       # Create distributed optimizer
        compression = hvd.Compression.fp16
        optimizer = hvd.DistributedOptimizer(module.optimizer,
            named_parameters=module.named_parameters(), compression=compression)
        scheduler = module.scheduler
        
        #apex
        module.model = convert_syncbn_model(module.model)
        module.model, optimizer = amp.initialize(module.model, optimizer, keep_batchnorm_fp32=None, opt_level="O1")

the error message as follow:

> File "/home/yhzn/yangming/workshop/code/baseline/packnet-sfm/packnet_sfm/trainers/horovod_trainer.py", line 106, in train
[1,1]<stderr>:    optimizer.synchronize()
[1,1]<stderr>:  File "/home/yhzn/anaconda3/envs/monodepth/lib/python3.7/site-packages/horovod/torch/__init__.py", line 175, in synchronize
[1,1]<stderr>:    handle, ctx = self._allreduce_grad_async(p)
[1,1]<stderr>:  File "/home/yhzn/anaconda3/envs/monodepth/lib/python3.7/site-packages/horovod/torch/__init__.py", line 145, in _allreduce_grad_async
[1,1]<stderr>:    tensor_compressed, ctx = self._compression.compress(tensor)
[1,1]<stderr>:  File "/home/yhzn/anaconda3/envs/monodepth/lib/python3.7/site-packages/horovod/torch/compression.py", line 52, in compress
[1,1]<stderr>:    if tensor.dtype.is_floating_point:
[1,1]<stderr>:AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by tgaddair** [comment]
Hey @MingYang-buaa, Horovod does work with Apex / AMP, but for SyncBatchNorm we recommend using our internal implementation [here](https://github.com/horovod/horovod/blob/master/horovod/torch/sync_batch_norm.py#L39).

**Comment by MingYang-buaa** [comment]
Hi  @tgaddair, i had tried to test hvd.SyncBatchNorm in my work, there was no error but the GPU-Util has dropped from 90% to 40%. Is normal?

**Comment by MingYang-buaa** [comment]
Hi  @tgaddair, i had tried to test hvd.SyncBatchNorm in my work, there was no error but the GPU-Util has dropped from 90% to 40%. Is normal?

**Comment by MingYang-buaa** [comment]
Hi  @tgaddair, i had tried to test hvd.SyncBatchNorm in my work, there was no error but the GPU-Util has dropped from 90% to 40%. Is normal?

**Comment by MingYang-buaa** [comment]
Hi  @tgaddair, i had tried to test hvd.SyncBatchNorm in my work, there was no error but the GPU-Util has dropped from 90% to 40%. Is normal?

**Comment by MingYang-buaa** [comment]
Hi  @tgaddair, i had tried to test hvd.SyncBatchNorm in my work, there was no error but the GPU-Util has dropped from 90% to 40%. Is normal?

**Comment by MingYang-buaa** [comment]
Hi  @tgaddair, i had tried to test hvd.SyncBatchNorm in my work, there was no error but the GPU-Util has dropped from 90% to 40%. Is normal?

**Comment by tgaddair** [comment]
Hey @MingYang-buaa, there is some overhead to SyncBatchNorm, but that sounds like a big drop.  @alsrgv @romerojosh can you comment on any expected performance hit with SyncBatchNorm?

**Comment by romerojosh** [comment]
I haven't used Horovod's PyTorch sync BN but I recall Alex mentioning in a prior thread somewhere that it was slow.

To improve performance, have you tried reducing the cycle time (via `HOROVOD_CYCLE_TIME` env var or `--cycle-time-ms` arg to `horovodrun`? The default cycle time of 5 ms is very long, and might be especially bad for Sync BN where Horovod operations are introduced directly in the forward/backward pass.

**Comment by MingYang-buaa** [comment]
Thanks for your suggestion，I will try with it !

**Comment by MingYang-buaa** [comment]
@romerojosh Hey, I tried to set the --cycle-time-ms to 1 when training the model, and GPU-Util had up from 40% to 70%. 

It looks good but there also is a gap between 70% with 90%. Is it the limit? 
All suggestions are welcome.
