### ISSUE TITLE
OSError: /usr/local/mpi/lib/libmpi.so.40: undefined symbol: opal_hwloc201_hwloc_get_type_depth

### ISSUE THREAD

**Issue by ChaiBapchya** [horovod/horovod#2187]
**Environment:**
1. Framework: MXNet
2. Framework version: 1.6.0.post0
3. Horovod version: 0.19.5
4. MPI version: 3.1.0
5. CUDA version: 10.1/10.2/11
6. NCCL version:
7. Python version: 3.7/3.7
8. Spark / PySpark version: NA
9. OS and version:ubuntu 18.04
10. GCC version:7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?NA
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?NA
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Nope

**Bug report:**

Upon installing mxnet & horovod
```
import horovod.mxnet as hvd
```
fails with the error
```
OSError: /usr/local/mpi/lib/libmpi.so.40: undefined symbol: opal_hwloc201_hwloc_get_type_depth
```

**Comment by tgaddair** [comment]
Hey @ChaiBapchya, could you provide more context on this issue?

Have you taken a look at troubleshooting steps related to hwloc: https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst#force-terminate-at-data-unpack-would-read-past-end-of-buffer

**Comment by ChaiBapchya** [comment]
Sure.. i added the command it failed on & the error.. 
By context, is there anything more I can add?

Thanks for looking into this @tgaddair

**Comment by ChaiBapchya** [comment]
the link you pointed is about data unpck reading past end of buffer while the one I'm getting is `opal_hwloc201_hwloc_get_type_depth` are they both related?

Nonetheless I tried the workaround of
1. purge hwloc from system
```
apt purge hwloc-nox libhwloc-dev libhwloc-plugins libhwloc5
```
2. reinstall latest openmpi 4.0.4
[i had to run `make all install` with `sudo`]
It failed to install though.

**Comment by tgaddair** [comment]
@ChaiBapchya, are you able to run any `mpirun` command successfully?  If you do not already use MPI for other purposes, I would suggest using the Gloo controller instead:

```
horovodrun --gloo ...
```

**Comment by mozizhao** [comment]
hi everyone, I met the same problem and I solve it by "ldconfig" command. Hope it works for you guys.

**Comment by ZJLi2013** [comment]
> hi everyone, I met the same problem and I solve it by "ldconfig" command. Hope it works for you guys.

how ? thanks
