### ISSUE TITLE
some question to start tensorflow_synthetic_benchmark.py

### ISSUE THREAD

**Issue by DeruiLiu** [horovod/horovod#2188]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version:1.10
3. Horovod version:0.19.5
4. MPI version:4.0.3rc4
5. CUDA version:9.0
6. NCCL version:2.3
7. Python version:2.7.12
8. OS and version:ubuntu16.04
9. GCC version:4.9.4

**Your question:**
Please ask your question here.
when i use start code to run tensorflow_synthetic_benchmark.py as below, it all report the same error, can anyone help me?
1.horovodrun -np 2 -H 172.168.30.26:1,172.168.30.25:1 python2 /root/ldr/horovod/examples/tensorflow_synthetic_benchmark.py
2.mpirun -np 2 -H 172.168.30.26:1,172.168.30.25:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x NCCL_IB_DISABLE=0 -x NCCL_IB_HCA=mlx5_1:1 -x NCCL_IB_GID_INDEX=3 -x NCCL_IB_CUDA_SUPPORT=1 -x NCCL_IB_TC=106 -mca pml ob1 -mca btl ^openib  python2 /root/ldr/horovod/examples/tensorflow_synthetic_benchmark.py --model VGG16 --num-iters 10 --batch-size 64

the error is:
*****************************************************************************

root@s36-2288H-V5:~/ldr# ./hdrun.sh
  File "/root/ldr/horovod/examples/tensorflow_synthetic_benchmark.py", line 85
    print(s, end='\n' if nl else '')
                ^
SyntaxError: invalid syntax

Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[39179,1],1]
  Exit code:    1

************************************************************************
but i run tensorflow/benchmark，it success。

**Comment by tgaddair** [comment]
Hey @DeruiLiu, are you able to upgrade to Python 3?  Horovod is dropping support for Python 2 in the next release, as it has been deprecated since January.

If you are unable to upgrade at the moment, you can try running the version of this script from the 0.19.5 release, which is still Python 2 compatible: https://github.com/horovod/horovod/blob/v0.19.5/examples/tensorflow_synthetic_benchmark.py

**Comment by DeruiLiu** [comment]
thank you! when i update to python3 , the problem is resolved.
