### ISSUE TITLE
horovod docker build file is broken

### ISSUE THREAD

**Issue by deepbrain** [horovod/horovod#2194]
The docker build fails at multiple points:
1. With the default latest wheel the code python -c "import wheel.pep425tags as w" fails, so I had to roll back to
pip install wheel==0.34.2

2. MXNET pip install fails to find the specified version

3. horovod install inside the docker fails with error:
libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by tgaddair** [comment]
Thanks for reporting this, @deepbrain.  Apologies for the late response.

Let me know if #2223 resolved the issue for you.
