### ISSUE TITLE
horovod+pytorch,  The program cannot be executed at hvd.init()

### ISSUE THREAD

**Issue by liumaoxi** [horovod/horovod#2196]
###
 when i test the horovod+pytorch, the code hvd.init() cannot executed at hvd.init(),i have wait for a few hours。
![image](https://user-images.githubusercontent.com/31879949/90866596-bb158180-e3c6-11ea-956f-3358fca4f041.png)
###
the 
"
[1,0]<stdout>:=========================horovod=========================
[1,0]<stdout>:1
[1,1]<stdout>:=========================horovod=========================
[1,1]<stdout>:1
"
is my debug output

and the code is 
“
           print("1")
            hvd.init()
            print("2")
            local_rank = hvd.local_rank()
            print("3")
            torch.cuda.set_device(local_rank)
            print("4")
”
thanks for your help

**Comment by tgaddair** [comment]
Hey @liumaoxi, could you get the stack trace by attaching to the hanging process via `gdb -p <pid>` and share the output of `thread apply all bt`?
