### ISSUE TITLE
support other shell tools in gloo run

### ISSUE THREAD

**Issue by zw0610** [horovod/horovod#2198]
**Is your feature request related to a problem? Please describe.**
When trying to support `horovodrun` with `--gloo` in `kubeflow/mpi-operator`, it is spotted that, unlike the `gloo_run.py` under `spark`, the `gloo_run.py` under `runner` simply hard-codes `ssh` as the tool to launch process on other worker. This prevents `kubeflow/mpi-operator` from adopting horovod with gloo.

**Describe the solution you'd like**
We would need to de-couple the shell tool from the gloo runner. 

**Describe alternatives you've considered**
This has been part of a plan to feature `kubeflow/mpi-operator` with Horovod-elastic.

**Additional context**
I can take care of this modification.

**Comment by tgaddair** [comment]
This is awesome, thanks for looking into this @zw0610!  I will take a look at the PR and provide some feedback.
