### ISSUE TITLE
coordinator negotiate  and response_cache

### ISSUE THREAD

**Issue by gongjingcs** [horovod/horovod#2202]
hi，I noticed that horovod has two negotiate modes，one can be called request&response，it is a master-slave mode; the other one we called response_cache.  response_cache can be obtained from response. Does it mean the request&response mode is only applied to first iteration, next steps use response_cache?  another question is timeline for negotiate, I understand that if request&response mode is applied, only rank 0 called func "timeline_.NegotiateStart",  how timeline works if response_cache is used ?

**Comment by tgaddair** [comment]
Hey @gongjingcs, the response cache is basically a compression of the information sent during the "negotiation" step.  If your cache can fit, say, 100 tensors, and your model only has 96, then the only communication you need to do after populating the cache is perform a bitwise AND to determine which tensors are ready for allreduce across all the workers.  
However, that's not guaranteed to be the case, so if there are previously unseen tensors that come up, or if there are more tensors than fit in the cache, then we still need to communicate the metadata about which tensors outside the cache are ready (shape, type, etc.).  This is also done using collective operations (allgather, broadcast), though we do have a "coordinator" (rank 0) that does most of the in-process aggregation.

All of this, including the response cache hits/misses/updates, is what appears as the "Negotiation" time in the timeline.

cc @romerojosh who maintains the response cache for a better explanation :)

**Comment by gongjingcs** [comment]
thanks alot.
![image](https://user-images.githubusercontent.com/15030497/91248459-4c01a980-e787-11ea-9880-2e45fb9c75f5.png)

**Comment by gongjingcs** [comment]
As shown in the figure above，I want to deeply understand the negotiation mechanism of horovod is because the gradient negotiation time in my training is too long, which causes the training speed to decrease. So I want to know whether the long gradient negotiation time is caused by communication or calculation. Is there a way to print out the timeline of Horovod, for example, which rank entered the negotiation time late, or locate which rank is slow to calculate? Looking forward to your reply
