### ISSUE TITLE
Which set of parameters to use in autotune log file?

### ISSUE THREAD

**Issue by zhao1157** [horovod/horovod#2207]
Here is a silly question. When using `autotune` feature, am I supposed to use the parameters that produce the highest score or the ones in the last line of the log file?

**Comment by tgaddair** [comment]
Hey @zhao1157, if the autotuning process completes before training finishes, then the best set of parameters will be written to the end of the log file.  However, it sounds like in your case the training process finished before autotuning completed, so you would be better off using the entries with the highest score.

**Comment by zhao1157** [comment]
@tgaddair Thank you very much for your very helpful suggestion. If the training process is long enough, how would I know whether the autotuning process is finished or not? Another question is the log shows the `cache_enabled` entry, not `cache-capacity`, so `cache_enabled=0` refers to  `cache-capacity=0` while `cache_enabled=1` refers to `cache-capacity=1024` which is the default value. Right?

**Comment by zhao1157** [comment]
@tgaddair I did a test on resnet50 with 2 GPUs, the autotune flags are `--autotune --autotune-log-file autotune.csv --autotune-warmup-samples 5 --autotune-steps-per-sample 20 --autotune-bayes-opt-max-samples 40 `. After 30000 training steps, the log looks like the following:

>   1 hierarchical_allreduce,hierarchical_allgather,cache_enabled,cycle_time_ms,tensor_fusion_threshold,score
  2 0,0,0,5,4,424.129
  3 0,0,0,50,32,491.156
  4 0,0,0,25,16,480.917
  5 0,0,0,10,8,485.8
  6 0,0,0,9.45382,8.00599,482.054
  7 0,0,0,49.7936,32.1926,455.384
  8 0,0,0,90.2363,17.1619,415.855
  9 0,0,0,25.1083,14.81,549.07
 10 0,0,0,17.5125,19.6613,517.517
 11 0,0,0,14.4132,9.53127,481.214
 12 0,0,0,25.1145,14.7422,480.17
 13 0,0,0,17.5144,19.6653,533.932
 14 0,0,0,10.4467,5.16043,512.292
 15 0,0,0,17.5141,19.6657,558.825
 16 0,0,0,77.1377,40.1434,512.272
 17 0,0,0,17.5163,19.6705,517.266
 18 0,0,0,32.0931,45.8035,505.983
 19 0,0,0,74.1965,32.1354,475.498
 20 0,0,0,78.9409,19.9215,409.864
 21 0,0,0,10.5765,3.97448,437.92
 22 0,0,0,51.4852,30.052,445.078
 23 0,0,0,31.268,43.689,500.689
 24 0,0,0,26.5908,60.6231,527.695
 25 0,0,0,29.1035,42.4176,522.802
 26 0,0,0,29.7597,40.7958,521.198
 27 0,0,0,15.9409,31.9254,509.421
 28 0,0,0,29.5294,44.4259,514.766
 29 0,0,0,26.0446,47.2301,539.227
 30 0,0,0,14.5041,37.2728,585.899
 31 0,0,0,7.21995,43.598,564.092
 32 0,0,0,4.39542,45.7088,486.464
 33 0,0,0,70.298,36.9991,463.577
 34 0,0,0,13.6529,37.1402,525.9
 35 0,0,0,13.7104,37.4977,518.626
 36 0,0,0,14.083,37.9499,532.259
 37 0,0,0,14.0186,38.3458,524.26
 38 0,0,0,14.1489,38.4901,500.186
 39 0,0,0,15.002,37.8793,567.541
 40 0,0,0,14.2343,38.7517,558.476
 41 0,0,0,13.4632,39.0372,564.446
 42 0,0,0,12.8134,41.0228,524.103
 43 1,0,0,5,4,538.453
 44 1,0,0,50,32,611.911
 45 1,0,0,25,16,659.214
 46 1,0,0,10,8,447.151
 47 1,0,0,25.0004,16.0006,470.295
 48 1,0,0,28.2965,5.70378,621.476
 49 1,0,0,68.9326,50.8593,619.396
 50 1,0,0,1.39611,63.4534,641.817
 51 1,0,0,67.2944,43.3713,642.119
 52 1,0,0,1.33711,54.1917,672.502
 53 1,0,0,3.79051,28.3051,393.457
 54 1,0,0,19.6693,46.189,404.716
 55 1,0,0,48.5284,39.5087,372.815
 56 1,0,0,36.7249,50.9032,414.512
 57 1,0,0,43.75,7.18799,350.078
 58 1,0,0,43.5544,9.23579,368.494
 59 1,0,0,1.15461,57.6937,409.59
 60 1,0,0,63.9201,49.086,394.916
 61 1,0,0,88.2081,9.6078,373.396
 62 1,0,0,18.1026,6.94152,360.685
 63 1,0,0,28.295,5.70275,379.186
 64 1,0,0,33.495,59.7806,428.135
 65 1,0,0,46.9222,12.646,377.974
 66 1,0,0,34.2206,46.4196,422.026
 67 1,0,0,91.4198,50.5924,390.171
 68 1,0,0,77.535,18.6444,385.091
 69 1,0,0,98.9763,33.0452,358.59
 70 1,0,0,41.6854,21.212,428.757
 71 1,0,0,47.6325,11.1924,371.204
 72 1,0,0,1.35438,53.8717,402.78
 73 1,0,0,73.1908,45.6955,416.727
 74 1,0,0,81.3136,17.8013,399.933
 75 1,0,0,33.3411,41.5251,408.165
 76 1,0,0,55.8382,53.3991,398.954
 77 1,0,0,63.8726,31.9645,401.832
 78 1,0,0,14.3561,17.4366,417.56
 79 1,0,0,83.8528,57.9039,400.801
 80 1,0,0,74.203,34.6319,426.996
 81 1,0,0,4.14921,18.0436,421.433
 82 1,0,0,45.9742,25.3296,465.768
 83 1,0,0,75.0778,17.4812,397.681
 84 0,1,0,5,4,478.319
 85 0,1,0,50,32,491.398
 86 0,1,0,25,16,542.177
 87 0,1,0,10,8,507.595
 88 0,1,0,14.0606,2.94788,397.676
 89 0,1,0,25.0008,16.0003,483.235
 90 0,1,0,2.99095,61.3059,543.682
 91 0,1,0,93.3651,46.5007,359.504
 92 0,1,0,21.4242,19.4769,538.081
 93 0,1,0,21.2371,19.4316,543.647
 94 0,1,0,18.2891,20.9977,483.71
 95 0,1,0,66.9513,13.8628,485.707
 96 0,1,0,29.1526,33.4026,522.947
 97 0,1,0,21.2992,19.4142,512.784
 98 0,1,0,21.6238,19.988,518.094
 99 0,1,0,11.3368,52.5659,485.968
100 0,1,0,21.4943,16.8847,578.432
101 0,1,0,20.7958,15.9639,679.889
102 0,1,0,20.5517,15.6817,741.46
103 0,1,0,28.9291,47.966,700.784
104 0,1,0,28.9273,47.9774,722.671
105 0,1,0,19.9534,7.87402,684.698
106 0,1,0,20.268,15.3373,741.398
107 0,1,0,20.1217,15.1593,520.45
108 0,1,0,80.6525,63.1681,401.605
109 0,1,0,36.1794,45.7452,501.029
110 0,1,0,28.9304,47.9707,499.193
111 0,1,0,19.9529,7.86979,493.12
112 0,1,0,10.2505,63.9605,493.507
113 0,1,0,28.412,48.2407,543.475
114 0,1,0,20.0849,9.43194,467.175
115 0,1,0,4.04077,55.4479,547.315
116 0,1,0,20.6416,15.7877,496.444
117 0,1,0,28.9405,47.9666,478.854
118 0,1,0,43.1386,35.5368,497.658
119 0,1,0,71.0734,61.9333,472.463
120 0,1,0,28.8845,47.9786,483.612
121 0,1,0,26.8705,1.08703,383.945
122 0,1,0,79.7179,39.1342,460.836
123 0,1,0,28.9194,47.99,530.175
124 0,1,0,20.5482,15.6744,639.048
125 1,1,0,5,4,346.167
126 1,1,0,50,32,408.874
127 1,1,0,25,16,393.994
128 1,1,0,10,8,435.93
129 1,1,0,44.1712,33.516,411.728
130 1,1,0,43.7673,26.3094,401.265
131 1,1,0,44.8756,32.6624,402.67
132 1,1,0,51.267,29.6402,387.917
133 1,1,0,10.009,8.00723,380.538
134 1,1,0,11.3241,15.8344,387.946
135 1,1,0,61.1177,39.0176,410.757
136 1,1,0,62.8724,53.9598,379.589
137 1,1,0,49.7555,32.3539,403.566
138 1,1,0,39.1521,32.7348,421.936
139 1,1,0,35.7934,39.5814,402.644
140 1,1,0,12.0491,43.6455,393.388
141 1,1,0,50.4862,6.01241,364.984
142 1,1,0,31.9648,53.117,435.519
143 1,1,0,31.9642,53.116,402.557
144 1,1,0,48.6023,33.3174,392.922
145 1,1,0,78.1803,53.2648,389.054
146 1,1,0,27.3666,1.89741,284.778
147 1,1,0,33.9321,46.1887,389.257
148 1,1,0,30.213,63.8271,408.178
149 1,1,0,31.1408,56.7232,378.065
150 1,1,0,9.11663,9.36478,369.597
151 1,1,0,36.5842,38.8909,416.302
152 1,1,0,36.8491,38.6868,408.568
153 1,1,0,31.9941,53.0436,403.966
154 1,1,0,43.3217,33.3222,372.323
155 1,1,0,22.9544,15.5076,370.25
156 1,1,0,36.4584,38.9844,389.33
157 1,1,0,49.6461,31.4384,393.367
158 1,1,0,26.4478,50.1212,410.744
159 1,1,0,61.6938,38.9365,372.064
160 1,1,0,22.6864,40.7974,579.314
161 1,1,0,22.8308,39.7213,609.08
162 1,1,0,22.8324,39.1318,621.313
163 1,1,0,22.8069,38.5994,613.098
164 1,1,0,22.7661,38.1834,633.218
165 1,1,0,22.6902,37.6474,607.203
166 0,0,1,5,4,429.844
167 0,0,1,50,32,468.548
168 0,0,1,25,16,530.765
169 0,0,1,10,8,470.75
170 0,0,1,50.4848,20.3195,427.438
171 0,0,1,24.9992,15.9993,472.567
172 0,0,1,54.1723,5.74419,459.751
173 0,0,1,11.23,30.0589,464.727
174 0,0,1,87.9716,58.0508,397.625
175 0,0,1,9.42555,48.1801,554.927
176 0,0,1,22.4996,19.9152,495.13
177 0,0,1,46.4093,30.5798,422.259
178 0,0,1,36.1687,61.3221,458.673
179 0,0,1,95.0022,41.2615,360.228
180 0,0,1,6.79504,8.74035,529.983
181 0,0,1,15.9264,53.591,497.129
182 0,0,1,6.65888,9.11702,510.627
183 0,0,1,23.9795,17.612,484.172
184 0,0,1,6.38946,9.63798,485.261
185 0,0,1,9.43504,48.1853,496.191
186 0,0,1,9.42732,48.1854,509.32
187 0,0,1,9.40057,48.1615,532.973
188 0,0,1,19.1319,60.6595,484.349
189 0,0,1,6.78155,7.83442,464.515
190 0,0,1,12.76,53.9874,547.062
191 0,0,1,24.9077,18.5451,517.918
192 0,0,1,37.7317,0.705877,320.719
193 0,0,1,3.68278,55.0807,468.243
194 0,0,1,16.1553,46.7467,502.162
195 0,0,1,14.0809,47.82,478.716
196 0,0,1,1.0212,44.4636,475.883
197 0,0,1,11.6494,53.7115,488.106
198 0,0,1,80.3634,2.6627,358.178
199 0,0,1,11.2653,28.2293,495.205
200 0,0,1,19.7636,42.8291,521.189
201 0,0,1,27.2974,44.0431,560.461
202 0,0,1,17.4359,64,594.949
203 0,0,1,42.3652,52.0152,573.211
204 0,0,1,74.4037,63.474,489.703
205 0,0,1,37.0468,38.286,494.581
206 0,0,1,9.78987,18.8139,503.007
207 1,0,1,5,4,347.972
208 1,0,1,50,32,423.642
209 1,0,1,25,16,399.572
210 1,0,1,10,8,387.847
211 1,0,1,43.4938,32.8979,414.194
212 1,0,1,43.4135,33.0898,414.054
213 1,0,1,59.5647,26.8256,409.378
214 1,0,1,50.2047,49.4003,382.076
215 1,0,1,46.7935,10.68,373.467
216 1,0,1,49.8159,31.2114,395.043
217 1,0,1,26.2858,18.332,383.647
218 1,0,1,59.4251,21.0935,527.851
219 1,0,1,59.4181,20.672,589.689
220 1,0,1,59.4082,20.5002,598.546
221 1,0,1,59.4101,20.1772,638.872
222 1,0,1,59.3958,19.548,595.315
223 1,0,1,59.3975,18.8952,640.656
224 1,0,1,59.5391,17.7973,415.258
225 1,0,1,65.7511,57.5031,380.627
226 1,0,1,8.81316,59.3507,423.499
227 1,0,1,88.2342,27.4607,409.313
228 1,0,1,69.3559,22.2916,384.389
229 1,0,1,90.4799,41.901,394.68
230 1,0,1,59.348,19.9693,406.919
231 1,0,1,59.4145,20.3836,405.114
232 1,0,1,59.3132,20.2735,388.684
233 1,0,1,37.5098,58.2026,393.205
234 1,0,1,80.3012,3.81766,317.477
235 1,0,1,78.4659,45.8695,354.935
236 1,0,1,59.2684,19.9241,376.427
237 1,0,1,59.6005,20.0939,407.489
238 1,0,1,5.17101,41.246,381.107
239 1,0,1,59.362,20.0098,383.368
240 1,0,1,92.1772,27.6567,403.564
241 1,0,1,37.1291,28.866,428.246
242 1,0,1,7.92058,37.6832,394.738
243 1,0,1,32.4994,61.2179,398.752
244 1,0,1,38.2027,25.2714,400.779
245 1,0,1,59.4081,19.0224,369.614
246 1,0,1,59.4337,20.2135,371.802
247 1,0,1,62.0124,2.05626,326.933
248 0,1,1,5,4,448.665
249 0,1,1,50,32,480.657
250 0,1,1,25,16,470.559
251 0,1,1,10,8,479.946
252 0,1,1,21.2146,12.4939,503.36
253 0,1,1,47.9356,27.2391,527.144
254 0,1,1,24.4354,39.1279,520.384
255 0,1,1,47.9356,27.2391,522.61
256 0,1,1,29.0618,21.9694,530.864
257 0,1,1,30.6681,27.1019,548.352
258 0,1,1,24.5947,38.1273,557.376
259 0,1,1,25.546,54.8357,538.59
260 0,1,1,25.6861,43.3839,569.856
261 0,1,1,22.8866,46.1681,555.341
262 0,1,1,17.0097,48.4144,512.389
263 0,1,1,30.7565,44.0798,525.857
264 0,1,1,45.2078,37.7566,473.913
265 0,1,1,24.2864,38.4338,578.568
266 0,1,1,25.4236,54.0132,556.429
267 0,1,1,60.5054,19.9446,517.161
268 0,1,1,22.8339,38.2264,538.949
269 0,1,1,23.1924,39.1705,566.543
270 0,1,1,21.8489,38.1507,508.209
271 0,1,1,25.9616,45.8303,497.824
272 0,1,1,23.9603,38.2527,536.594
273 0,1,1,25.6326,43.0982,644.08
274 0,1,1,27.0399,33.1014,737.036
275 0,1,1,27.0393,33.1026,739.009
276 0,1,1,84.7734,51.4123,465.832
277 0,1,1,27.1864,32.9094,515.844
278 0,1,1,52.0283,24.4489,529.621
279 0,1,1,52.3003,10.0794,691.204
280 0,1,1,23.3276,52.6694,757.484
281 0,1,1,26.8217,33.3862,749.008
282 0,1,1,54.1335,6.76154,641.415
283 0,1,1,52.7717,9.22625,675.11
284 0,1,1,52.747,9.27015,600.81
285 0,1,1,22.4444,52.1901,556.223
286 0,1,1,26.8752,33.2739,479.08
287 0,1,1,52.4821,9.58184,459.865
288 0,1,1,57.2729,7.19811,464.864
289 1,1,1,5,4,348.53
290 1,1,1,50,32,407.772
291 1,1,1,25,16,413.278
292 1,1,1,10,8,397.633
293 1,1,1,11.4829,7.85286,367.108
294 1,1,1,39.8983,53.1074,446.028
295 1,1,1,86.5483,11.8662,390.692

It seems the autotuning process is not finished. But why does it take so long? What is the autotune log looks like if the tuning process is completed?

**Comment by tgaddair** [comment]
Hey @zhao1157, looks like some parameter combinations are significantly better than others, so that's a good start.

You have identified a few things we should fix:

1. I agree that it would make sense to use `cache_capacity` instead of having a binary value here.  @romerojosh what do you think?
2. We should get rid of hierarchical allreduce/allgather, as recent versions of NCCL make these unnecessary.  For now, you can workaround this by running with `--no-hierarchical-allreduce --no-hierarchical-allrgather` which will omit them from autotune and hopefully speed up the process.

**Comment by romerojosh** [comment]
As far as `cache_capacity` being treated as a binary option in the autotuner, I recall having a reason for doing this at the time but can't quite remember, though I believe it might have to do with the cache not handling dynamic resizing very well during autotuning. I will have to look more closely at that.

With that said, the benefits of using the cache should generally be pretty binary anyway (either everything fits in the cache and you see the full benefit, or you exceed the cache capacity and the performance will likely be about the same or possibly worse than not using it). 

I agree that we should at least drop the hierarchical options from the default autotuning procedure since they are fairly outdated at this point (and hierarchical allgather is not relevant in most cases anyway).

**Comment by zhao1157** [comment]
@tgaddair Just need to confirm with you about this 

> " Another question is the log shows the cache_enabled entry, not cache-capacity, so cache_enabled=0 refers to cache-capacity=0 while cache_enabled=1 refers to cache-capacity=1024 which is the default value"

Thanks.
