### ISSUE TITLE
Should we use the is_chief field when creating MonitoredTrainingSession

### ISSUE THREAD

**Issue by iamyangchen** [horovod/horovod#2214]
In horovod's examples (e.g., https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist.py), global variable initialization is taken care of by the `hvd.BroadcastGlobalVariablesHook(0)`. But then when creating MonitoredTrainingSession, seems there's a field called `is_chief` which defaults to `True`, and the comment says

```
If `True`, it will take care of initialization and recovery the
underlying TensorFlow session. If `False`, it will wait on a chief to
initialize or recover the TensorFlow session.
```
The example doesn't set this field, but seems it would affect the session creation. So I'm wondering if we should still set this field according to the rank or it doesn't matter?

**Comment by tgaddair** [comment]
Hey @iamyangchen, in Horovod, every worker manages its own TensorFlow session independently.  So it's okay for every worker to set `is_chief=True` in the `MonitoredTrainingSession`.  Horovod handles the multi-worker coordination through a separate mechanism.

**Comment by iamyangchen** [comment]
Thank you for the clarification!
