### ISSUE TITLE
undefined symbol: cudaLaunch  with cuda10.1

### ISSUE THREAD

**Issue by xzswater** [horovod/horovod#2224]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): tensorflow 
2. Framework version: 2.3.0
3. Horovod version: 0.19.5
4. MPI version: 3.1.0
5. CUDA version: 10.1.243
6. NCCL version: 2.4.7
7. Python version: 3.6.10
8. OS and version: CentOS 6.10
9. GCC version: 8.2.0

**Your question:**
mpi_lib.cpython-36m-x86_64-linux-gnu.so: **undefined symbol: cudaLaunch**

**There's no cudaLaunch in cuda-10.1, but in cuda-10.0 and below. However, tensorflow 2.3.0 need cuda-10.1.**

![image](https://user-images.githubusercontent.com/52267702/91929379-d52d5900-ed10-11ea-806c-c548a4bc151a.png)

**Comment by tgaddair** [comment]
Hey @xzswater, did you previously install Horovod with CUDA 10.0?  Can you try the following:

```
pip uninstall -y horovod
<HOROVOD INSTALL FLAGS> ... pip install --no-cache-dir horovod
```

Without `--no-cache-dir`, pip will not properly re-compile Horovod against your new environment.

**Comment by xzswater** [comment]
> Hey @xzswater, did you previously install Horovod with CUDA 10.0? Can you try the following:
> 
> ```
> pip uninstall -y horovod
> <HOROVOD INSTALL FLAGS> ... pip install --no-cache-dir horovod
> ```
> 
> Without `--no-cache-dir`, pip will not properly re-compile Horovod against your new environment.

I did install with --no-cache-dir at least 4~5 times, through pip or source, the errors always are the above.

Finally, i install tensorflow with cuda10.1, then install horovod with cuda10.0:
export HOROVOD_CUDA_INCLUDE=/usr/local/cuda-10.0/include
export HOROVOD_CUDA_LIB=/usr/local/cuda-10.0/lib64

It works.

libcudart.so.10.1 really has no cudaLaunch, i confirmed by install cuda10.1 / cuda10.1 update2 on different machines.

**Comment by tgaddair** [comment]
We do not call `cudaLaunch` in Horovod, that is likely coming from another library that's being linked against Horovod during compile.

To make sure I understand: when you say that it works, you mean you no longer get any runtime errors when using Horovod built with CUDA 10.0 and TensorFlow 2.3.0?  That is strange, are you sure your TensorFlow libraries were built with CUDA 10.1?  It sounds like you have a CUDA 10.0 version of TensorFlow somehow (is it possible you have multiple versions of TensorFlow on your system?).
