### ISSUE TITLE
can not run examples in  docker env with multiple machines

### ISSUE THREAD

**Issue by evi-Genius** [horovod/horovod#2246]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
I have two machines A and B , and I pull the docker file from horovod/horovod and run it 
`nvidia-docker run -itd --net host  -v /data/NFS:/data/NFS --name horovod  horovod/horovod:0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu bash`
then I exec docker container and  gen ssh key  `ssh-keygen`,
add 
`Port 1234
PermitRootLogin yes
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
`
to /etc/ssh/sshd_config. 
Next I change the passwd to 123. After that, I command 'cat .ssh/id_rsa.pub | ssh -p 1234 xxx 'cat >> .ssh/authorized_keys'' and input the passwd 123.
After that I can ssh each other without password. But when I run 
`mpirun -np 2 -H 164.90.89.19:1,164.90.89.16:1 -mca plm_rsh_args "-p 1234 -vvvv" --allow-run-as-root python pytorch_mnist.py`，the last few lines of output is

。。。。
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x08
debug2: client_session2_setup: id 0
debug1: Sending environment.
debug3: Ignored env LS_COLORS
debug3: Ignored env SSH_CONNECTION
debug3: Ignored env USER
debug3: Ignored env PWD
debug3: Ignored env HOME
debug3: Ignored env SSH_CLIENT
debug3: Ignored env SSH_TTY
debug3: Ignored env MAIL
debug3: Ignored env TERM
debug3: Ignored env SHELL
debug3: Ignored env SHLVL
debug3: Ignored env LOGNAME
debug3: Ignored env PATH
debug3: Ignored env _
debug3: Ignored env OLDPWD
debug3: Ignored env OMPI_MCA_plm_rsh_args
debug3: Ignored env IPATH_NO_BACKTRACE
debug3: Ignored env HFI_NO_BACKTRACE
debug3: Ignored env PMIX_MCA_mca_base_component_show_load_errors
debug3: Ignored env LD_LIBRARY_PATH
debug1: Sending command:     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "1343684608" -mca ess_base_vpid 1 -mca ess_base_num_procs "2" -mca orte_node_regex "jja-gpu[3:312],[3:164].90.89.19@0(2)" -mca orte_hnp_uri "1343684608.0;tcp://164.90.89.16,10.211.42.37,172.17.0.1,192.168.227.64:33941" -mca plm "rsh" --tree-spawn -mca orte_parent_uri "1343684608.0;tcp://164.90.89.16,10.211.42.37,172.17.0.1,192.168.227.64:33941" -mca plm_rsh_args "-p 1234 -vvvv" -mca pmix "^s1,s2,cray,isolated"
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: read<=0 rfd 4 len 0
debug2: channel 0: read failed
debug2: channel 0: close_read
debug2: channel 0: input open -> drain
debug2: channel 0: ibuf empty
debug2: channel 0: send eof
debug3: send packet: type 96
debug2: channel 0: input drain -> closed
--------------------------------------------------------------------------
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

  Local host: jja-gpu313
  PID:        422
  Message:    connect() to 192.168.227.64:1024 failed
  Error:      Operation now in progress (115)
--------------------------------------------------------------------------

Could you help me check if somewhere is wrong?

**Comment by EnricoMi** [comment]
Did you try `mpirun` without any Horovod involved, e.g.

    mpirun -np 2 -H 164.90.89.19:1,164.90.89.16:1 -mca plm_rsh_args "-p 1234 -vvvv" --allow-run-as-root hostname

You may have to open more ports between the docker containers as MPI uses not only ssh. The last line reads `Message: connect() to 192.168.227.64:1024 failed`, looks like it tries to connect to port 1024 as well.

**Comment by EnricoMi** [comment]
Please see #2043, it might be similar: https://github.com/horovod/horovod/issues/2043#issuecomment-648968252

**Comment by evi-Genius** [comment]
@EnricoMi Thank for your reply! I tryed `mpirun -np 2 -H 164.90.89.19:1,164.90.89.16:1 -mca plm_rsh_args "-p 1234 -vvvv" --allow-run-as-root hostname` and It's output looks well.
...
debug2: channel 0: input drain -> closed
jja-gpu312
jja-gpu313
debug3: receive packet: type 96
...
jja-gpu312 and jja-gpu313 are hostnames of the two machines.
I can't understand why mpirun is trying to connect 192.168.227.64, the two machines ip are 164.90.89.19 and 164.90.89.16

**Comment by Richie-yan** [comment]
@evi-Genius @EnricoMi 
I also encountered the same problem when running 20 nodes:
```
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

 Message:    connect() to 10.0.0.1:1024 failed
 Error:      Operation now in progress (115)
```
There is no 10.0.0.1 in my node. I don’t know why try to connect to this ip. 
Is there any solution?
