### ISSUE TITLE
Build error with #include "tensorflow/compiler/tf2xla/xla_op_kernel.h"

### ISSUE THREAD

**Issue by jianyinglang** [horovod/horovod#225]
Tried "pip install horovod" including the header file 'tensorflow/compiler/tf2xla/xla_op_kernel.h' in mpi_ops.cc file and got the following error message:
build/temp.linux-x86_64-3.5/test_compile/test_tensorflow_abi.cc:5:55: fatal error: tensorflow/compiler/tf2xla/xla_op_kernel.h: No such file or directory compilation terminated.
error: Unable to determine CXX11 ABI to use with TensorFlow (see error above).

Anyone knows how to fix this?

**Comment by alsrgv** [comment]
@jianyinglang, I'm not sure `xla_op_kernel.h` is packaged in the TensorFlow python package.  What functionality are you including from there?

**Comment by jianyinglang** [comment]
@alsrgv, Thanks a lot for the quick response! I am trying to use the function of `REGISTER_XLA_OP`. I wonder if there is a way to include `xla_op_kernel.h`.

**Comment by alsrgv** [comment]
@jianyinglang, I'd recommend making a PR for TensorFlow team to include headers in the python package.
