### ISSUE TITLE
Modifying MPI RMA: architecture diagram request

### ISSUE THREAD

**Issue by collinabidi** [horovod/horovod#2250]
**Environment:**
1. Framework: PyTorch
2. Framework version: (Pytorch) 1.6.0
3. Horovod version: 0.19.2
4. MPI version: OpenMPI 5.0.0a / MPI 3.1.0
5. CUDA version: NA
6. NCCL version: NA
7. Python version: 3.8.2
8. OS and version: Ubuntu 20.04
9. GCC version: GCC 9.3.0

**Your question:**
Hi there, I'm modifying Horovod to use a PGAS model that's an alternative to MPI. I'm having difficulty in attempting to track down all MPI functions and Horovod collectives that need to be modified/replaced. I've been using the pytorch_mnist.py test script as a base, from which I've gone through `mpi_ops.py`, `basics.py`, `operations.cc`/`.h`, `mpi_ops.cc`, `common.cc`/`.h`, and more.

I'm hoping that there's an architectural diagram of Horovod that you could share to make things easier for me.

**Comment by tgaddair** [comment]
Hey @collinabidi, because Horovod does not have a hard dependency on MPI, it should actually be pretty straightforward to add in support for an alternative.  Since MPI plays more than one role in Horovod, the question is which of these roles you want PGAS to play.

Specifically, MPI can be used in Horovod as the Control Plane and/or the Data Plane (for CPU tensors, GPU, or both):

![image3](https://user-images.githubusercontent.com/1742912/92504515-a2bfa800-f1b7-11ea-8986-ad3cddd959e7.png)

The role of the Control Plane in Horovod is to coordinate the set of tensors all the works will attempt to aggregate at each step based on readiness.  A new Control Plane can be added to Horovod by implementing the [Controller](https://github.com/horovod/horovod/blob/master/horovod/common/controller.h) interface (see #1181 for the implementation of the Gloo controller).

The Data Plane is what actually allreduces the tensors together.  In most cases, this is NCCL (not MPI) when the tensors are on GPU.  We also implement an MPI Data Plane for tensors on CPU and for GPU-accelerated MPI. A new Data Plane can be added by implementing the various [HorovodOp](https://github.com/horovod/horovod/blob/master/horovod/common/ops/collective_operations.h) subclasses for your framework (see #1120 for the implementation of the Gloo operations).

Let me know if you have additional questions, happy to help out and learn more about your use case.

**Comment by collinabidi** [comment]
Hey @tgaddair, thanks for the diagram! That clears up a lot of confusion that I was having about the layout of the code and how MPI is being used.

I'm attempting to replace the Broadcast, AllGather, and AllReduce functions with [SHMEM](https://en.wikipedia.org/wiki/SHMEM) versions. I'll update you as I proceed!

Thanks for all the help so far, the Horovod team has been fantastic at responding to questions and being helpful.

**Comment by tgaddair** [comment]
Sounds great, @collinabidi!  Looking forward to it.

**Comment by collinabidi** [comment]
Hey @tgaddair I generated some documentation using Doxygen for the `horovod/horovod` folder. Not sure if it'll be helpful but I found that the generated class/inheritance diagrams is helping me to speed up the development process.

**Comment by tgaddair** [comment]
Nice!  Would be happy to take a look, sounds useful!

**Comment by collinabidi** [comment]
[html.zip](https://github.com/horovod/horovod/files/5334949/html.zip)

Apparently I can only upload a .zip file. Totally understandable if you don't trust a zip, so here's the [Doxyfile.TXT](https://github.com/horovod/horovod/files/5334960/Doxyfile.TXT) text file (you need to remove the ".TXT" at the end since GitHub only allows that format to be uploaded). Not sure if you've used Doxygen before but it's pretty easy to use. [Here's a userguide](https://www.doxygen.nl/manual/starting.html).

My steps to generate the documentation:

1. Install Doxygen
`sudo apt-get install doxygen`
2. Generate Doxyfile in the `horovod/horovod` folder
`doxygen -g Doxyfile`
3. Fill extra variables and edit the Doxyfile
4. Use Doxygen to generate diagrams for any code in the directory specified in Doxygen file. Output will be stored in the specified format at the location specified in the Doxyfile.
`doxygen Doxyfile`
5. Point browser to the folder you generated if you output HTML format and there it is!

**Comment by collinabidi** [comment]
Hey @tgaddair I've finished a (naive) implementation for SHMEM on the Data Layer. I believe that I have made most of the proper modifications to the ```setup.py``` file to include new ```HOROVOD_CPU_OPERATIONS=SHMEM``` and ```HOROVOD_WITH_SHMEM=1``` flags at compile-time. However, when I run the ```examples/pytorch_mnist.py``` example, MPI is still being used.

I put a print statement in the ```mpi_operations.cc``` file at the top of ```Status MPIBroadcast::Execute(...)``` that confirms this. When I build horovod with 
```
HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MPI=1 HOROVOD_WITHOUT_GLOO=1 \
HOROVOD_BUILD_ARCH_FLAGS=-L  HOROVOD_CPU_OPERATIONS=SHMEM \
HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 \
HOROVOD_WITH_SHMEM=1 pip3 install --no-cache-dir dist/horovod-0.19.2.tar.gz
```

I can see that MPI broadcast is being called, and not my SHMEM_Broadcast. Do you know what the proper fixes are to get my SHMEM operations on the Data Layer?

**Comment by tgaddair** [comment]
Thanks @collinabidi, do you have a branch I can take a look at to help figure out where the issue is?

**Comment by collinabidi** [comment]
@tgaddair I actually forked it to my own repository [here](https://github.com/collinabidi/horovod)

**Comment by tgaddair** [comment]
Hey @collinabidi, looking through the code, it looks like the only missing piece is to add the ops to the `OperationManager` [here](https://github.com/collinabidi/horovod/blob/master/horovod/common/operations.cc#L192).  I suspect once that's done it should be wired up correctly.

**Comment by collinabidi** [comment]
Hey @tgaddair I made the appropriate changes to [operations.cc](https://github.com/collinabidi/horovod/blob/master/horovod/common/operations.cc), [env_parser.cc](https://github.com/collinabidi/horovod/blob/master/horovod/common/utils/env_parser.cc), and their respective .h files.

However, the MPI Broadcast function is still being called. As seen [here](https://github.com/collinabidi/horovod/blob/master/horovod/common/utils/env_parser.cc#L65), I have set the SHMEM library to be used. The MPI Broadcast still is called when the ```pytorch_mnist.py``` example is run.

Any thoughts on why MPI Broadcast is still called?

**Comment by tgaddair** [comment]
Hey @collinabidi, the problem looks to be the order of the ops in the `OperationManager`.  The way it works is that Horovod will go through every op in the list and check the `Enabled` function to decide whether it should use that op.  The first op to return true is used.  In your case, because the MPI ops come before the SHMEM ops, they're being executed instead.

If you move the ops just above [this line](https://github.com/collinabidi/horovod/blob/master/horovod/common/operations.cc#L202), it should work.

**Comment by collinabidi** [comment]
Hey @tgaddair awesome, I made that change and it worked!

I now have an interesting bug that now appears to be related to PyTorch:
```
Traceback (most recent call last):
  File "/ihome/ageorge/cba15/horovod/horovod/torch/__init__.py", line 21, in <module>
    __file__, 'mpi_lib_v2')
  File "/ihome/ageorge/cba15/horovod/horovod/common/util.py", line 56, in check_extension
    ext_name, full_path, ext_env_var
ImportError: Extension horovod.torch has not been built: /ihome/ageorge/cba15/horovod/horovod/torch/mpi_lib_v2.cpython-37m-x86_64-linux-gnu.so not f$
If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.
```

This error popped up after several successful runs, so I'm not sure what would cause this. My install command runs without errors, so I was wondering if you've seen this before/have a quick fix.

(This is what my build/install command and output is)
```
HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MPI=1 HOROVOD_WITHOUT_GLOO=1 HOROVOD_BUILD_ARCH_FLAGS=-L HOROVOD_CPU_OPERATIONS="MPI" HOROVOD_DEFAULT_CPU_OPERATIONS=M HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 pip3 install --no-cache-dir dist/horovod-0.19.2.tar.gz
Processing ./dist/horovod-0.19.2.tar.gz
Requirement already satisfied: cloudpickle in /ihome/ageorge/cba15/.virtualenvs/henv/lib/python3.7/site-packages (from horovod==0.19.2) (1.6.0)
Requirement already satisfied: psutil in /ihome/ageorge/cba15/.virtualenvs/henv/lib/python3.7/site-packages (from horovod==0.19.2) (5.7.3)
Requirement already satisfied: pyyaml in /ihome/ageorge/cba15/.virtualenvs/henv/lib/python3.7/site-packages (from horovod==0.19.2) (5.3.1)
Requirement already satisfied: cffi>=1.4.0 in /ihome/ageorge/cba15/.virtualenvs/henv/lib/python3.7/site-packages (from horovod==0.19.2) (1.14.3)
Requirement already satisfied: pycparser in /ihome/ageorge/cba15/.virtualenvs/henv/lib/python3.7/site-packages (from cffi>=1.4.0->horovod==0.19.2) (2.20)
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... done
  Created wheel for horovod: filename=horovod-0.19.2-cp37-cp37m-linux_x86_64.whl size=8721481 sha256=888804a2d0d933087b44606229b1f7838861da029792e5a57ddf7109b0ce8d15
  Stored in directory: /tmp/pip-ephem-wheel-cache-0rs9ysc2/wheels/cb/4d/27/588cfd4a8d61d706c2a88761dcb86282d72e37cc4b9f689aaf
Successfully built horovod
Installing collected packages: horovod
  Attempting uninstall: horovod
    Found existing installation: horovod 0.19.2
    Uninstalling horovod-0.19.2:
      Successfully uninstalled horovod-0.19.2
Successfully installed horovod-0.19.2

```

**Comment by tgaddair** [comment]
Hmm, looks like it's not able to find the native library where it expects to find it.

Have you checked for the existence of `/ihome/ageorge/cba15/horovod/horovod/torch/mpi_lib_v2.cpython-37m-x86_64-linux-gnu.so`?

**Comment by collinabidi** [comment]
Right, it appears not to be there. I can still run Horovod withou that file present though. I have two environments (laptop and a cluster) and my laptop is able to run it since the file is located at ```./build/lib.linux-x86_64-3.8/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so```
Is there some flag that might be missing when I build torch?

**Comment by collinabidi** [comment]
Hey @tgaddair that fix strangely helped even though I had my filed in another directory before. Oh well!

I found that the Tensor Fusion Buffer shares a lot of similarity with SHMEM's PGAS model. The modification isn't fully complete due to 1) some fun segfault issues and 2) full decoupling of Tensor Fusion Buffer memory assignment and SHMEM memory assignment.

Anyways, here's some preliminary numbers for benchmarking CPU version only.

![training_times](https://user-images.githubusercontent.com/29078081/105381814-66786b80-5bdd-11eb-8c16-8a959e939c80.PNG)

![speedup_numbers](https://user-images.githubusercontent.com/29078081/105381832-6aa48900-5bdd-11eb-9046-77ca69c436d2.PNG)

**Comment by tgaddair** [comment]
Nice!  Thanks for the update.
