### ISSUE TITLE
Add some demo of elastic horovod on real dataset.

### ISSUE THREAD

**Issue by jiaqianjing** [horovod/horovod#2252]
hi, @tgaddair 
Could you give me a real training demo of elastic horovod? Like training model with tensorflow on imagenet.

**Comment by jiaqianjing** [comment]
@tgaddair  Could you modify it based on this file [pytorch_imagenet_resnet50.py](https://github.com/horovod/horovod/blob/master/examples/pytorch_imagenet_resnet50.py) or [tf_cnn_benchmarks.py](https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py)

**Comment by jiaqianjing** [comment]
And dataset of [pytorch_imagenet_resnet50.py](https://github.com/horovod/horovod/blob/master/examples/pytorch_imagenet_resnet50.py) what can I found it.

**Comment by tgaddair** [comment]
Sure, we can make a full demo based on PyTorch ImageNet.

**Comment by tgaddair** [comment]
@jiaqianjing please try out the example from #2297.  This will require building Horovod from master.

**Comment by jiaqianjing** [comment]
3q~

**Comment by jiaqianjing** [comment]
> @jiaqianjing please try out the example from #2297. This will require building Horovod from master.

@tgaddair Now I can run [pytorch_imagenet_resnet50_elastic.py](https://github.com/horovod/horovod/blob/master/examples/elastic/pytorch_imagenet_resnet50_elastic.py)


my command:
```shell
sh discover_hosts.sh
horovod-pytorch-elastic-worker-0:2
horovod-pytorch-elastic-worker-1:2
horovod-pytorch-elastic-worker-2:2
horovod-pytorch-elastic-worker-3:2
horovod-pytorch-elastic-worker-4:2

horovodrun --elastic-timeout 1000 --verbose --log-level=DEBUG -np 8 --min-np 1 --max-np 9 --host-discovery-script ./discover_hosts.sh python pytorch_imagenet_resnet50_elastic.py --train-dir=/data/ImageNet/train --val-dir=/data/ImageNet/validation
```
But when I add new worker into hostfile, I found the new worker didn't worker.
```shell
sh discover_hosts.sh
horovod-pytorch-elastic-worker-0:2
horovod-pytorch-elastic-worker-1:2
horovod-pytorch-elastic-worker-2:2
horovod-pytorch-elastic-worker-3:2
horovod-pytorch-elastic-worker-4:2
horovod-pytorch-elastic-worker-5:2
horovod-pytorch-elastic-worker-6:2
```
This  is log:
![image](https://user-images.githubusercontent.com/16071449/93977202-b6b8fb80-fdac-11ea-825d-ccf77d3114b9.png)
