### ISSUE TITLE
Why is 'backward_passes_per_step' only available for AdaSum but not Average operation ?

### ISSUE THREAD

**Issue by lengoanhcat** [horovod/horovod#2256]
**Environment:**

Framework: Tensorlfow
Framework version: 1.15.0
Horovod version: 0.20.0
MPI version: 4.0.3
CUDA version: 10.1.243
NCCL version: 2.7.8-1
Python version: 3.7.7
Spark / PySpark version: -
OS and version: Ubuntu 18.04
GCC version: 7.5.0

**Your question:**
Why is 'backward_passes_per_step' only available for AdaSum but not Average operation ?

**Comment by tgaddair** [comment]
Hey @lengoanhcat, recent PRs have added `backward_passes_per_step` for non-AdaSum optimizers as well, so I will go ahead and close this.
