### ISSUE TITLE
Our benchmark on 64 GPUs 

### ISSUE THREAD

**Issue by gangliao** [horovod/horovod#226]
Our benchmark on 64 GPUs (8 GPUs per node):

https://gist.github.com/gangliao/235fe1f055cf4c944efb698ae1f67577

Thanks.

**Comment by alsrgv** [comment]
@gangliao, very nice, thanks for sharing!

**Comment by vilmara** [comment]
@ganglio nice job, thanks for sharing. I am working on similar project, can you help with the issue I posted ?: Docker hangs when using multiple hosts #272
