### ISSUE TITLE
Feed the model with Numpy array

### ISSUE THREAD

**Issue by orwa-te** [horovod/horovod#2268]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version: 2.3.0
3. Horovod version: 0.19.5
4. MPI version: 4.0.3
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7.7
8. OS and version: Centos 7
9. GCC version: 9.3.0

**Your question:**
I want to train a model on **Spark** using Horovod where my data features are NumPy arrays ( images ) with `shape=128*128*4` and labels are also images with `shape=128*128*5`.
Do I have to convert Numpy arrays to dataframe in order for **Horovod Estimator** to read the data and train the model?
Is there a better way to avoid this conversion process like using `tf.data` and how to implement it? 
I am highly concerned about **not consuming a lot of memory** because of hardware limitations

**Comment by WaterKnight1998** [comment]
@orwa-te how did you solve this at the end?
