### ISSUE TITLE
Horovod on CPU 

### ISSUE THREAD

**Issue by ashiqimranintel** [horovod/horovod#2294]
Framework: Tensorflow 2.X

For GPU's case we need to add the following lines to PIN GPU
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()]

I was wondering do we need to add any lines to PIN CPU or is it automatic?

**Comment by tgaddair** [comment]
Hi @ashiqimranintel, this is something you can control at the `horovodrun` or `mpirun` level (specified with `horovodrun --binding-args`).  See the [OpenMPI](https://www.open-mpi.org/doc/v3.0/man1/mpirun.1.php#sect9) docs for more details. 

By default, TensorFlow will use all the CPU and memory resources it has available to it, which in many cases will be okay.  The pinning / affinity is not as critical for CPU training as it is for GPU training.
