### ISSUE TITLE
Error: build C++ code using cmake

### ISSUE THREAD

**Issue by zhao1157** [horovod/horovod#2301]
I built a horovod image using the provided `Dockerfile.gpu` file and tested the `Tensorflow` code with no problem. Inside the horovod container, I tried to build the `c++` code using the `CMakeLists.txt` file provided and got the first error

> -- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build architecture flags: -mf16c -mavx -mfma
CMake Error at CMakeLists.txt:101 (find_package):
  By not providing "FindPython.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Python", but CMake did not find one.
  Could not find a package configuration file provided by "Python" (requested
  version 3.6) with any of the following names:
    PythonConfig.cmake
    python-config.cmake
  Add the installation prefix of "Python" to CMAKE_PREFIX_PATH or set
  "Python_DIR" to a directory containing one of the above files.  If "Python"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Configuring incomplete, errors occurred!

In `horovod/cmake/Modules/` directory, there is no such python-related cmake file. Later I tried to bypass this error by just commenting out that `find_package` line, I got another error

>-- Build architecture flags: -mf16c -mavx -mfma
-- Using command
CMake Error at CMakeLists.txt:226 (add_subdirectory):
  The source directory
    /home/source_code/horovod/third_party/gloo
  does not contain a CMakeLists.txt file.
CMake Error at CMakeLists.txt:228 (target_compile_definitions):
  Cannot specify compile definitions for target "gloo" which is not built by
  this project.
-- Could NOT find Tensorflow (missing: Tensorflow_LIBRARIES) (Required is at least version "1.15.0")
-- Could NOT find Pytorch: Found unsuitable version "", but required is at least "1.2.0" (found )
-- Could NOT find Mxnet (missing: Mxnet_LIBRARIES) (Required is at least version "1.4.0")
-- Configuring incomplete, errors occurred!

I'm very new to `cmake`, so I'm not sure if did anything wrong. Could you please help me with this issue? Thanks!

**Comment by tgaddair** [comment]
Hey @zhao1157, in most cases you shouldn't need to build the C++ code directly.  Horovod will already be built after building the container.  To re-build, you can run `python setup.py install`, which will build the C++ code and install Horovod as a Python package.

**Comment by zhao1157** [comment]
@tgaddair Thanks. It helped a lot!
