### ISSUE TITLE
Horovod Process not in synch TF 2.X model

### ISSUE THREAD

**Issue by ashiqimranintel** [horovod/horovod#2303]
**Environment:**
1. Framework: TensorFlow 
2. Framework version: 2.3
3. Horovod version: 0.19.5
4. MPI version: 3
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7
8. OS and version: Ubuntu 18.04
9. GCC version: 7.5

What could be the reason of mpi processes are not in synch? I am working on a model.  Currently, running 4 mpi_processes in CPU Device. I added the following lines for TF 2.X. I changed learning_rate and batch_size according to hvd.size(). My code is working. 
        
        if self.time_callback.on_batch_begin(0):
          logging.info("FIRST BATCH")
          hvd.broadcast_variables(self.model.variables, root_rank=0)
          hvd.broadcast_variables(self.optimizer.variables(), root_rank=0)

        tape = hvd.DistributedGradientTape(tape)
        grads = tape.gradient(loss, self.model.trainable_variables)
        optimizer.apply_gradients(zip(grads, self.model.trainable_variables))

But after 2000 steps, 1/2 processes are out of synch.  What could be the reason for the mpi process getting out of synch?

**Comment by tgaddair** [comment]
Hey @ashiqimranintel, are you calling the `hvd.broadcast_variables` functions after the first batch as shown here?

https://github.com/horovod/horovod/blob/master/examples/tensorflow2_mnist.py#L75

Otherwise, the optimizer will not be initialized yet, which could lead to this divergence.

**Comment by ashiqimranintel** [comment]
Hey @tgaddair, the training is leading to convergence, I added that initialization of hvd.broadcast_variables. I am running 4 mpi process, 1/2 mpi processes are running faster than other two processes. So, first 2 mpi processes are overtaking instead of waiting for the synch with other 2 processes.

**Comment by tgaddair** [comment]
Hey @ashiqimranintel, if the processes are not proceeding at the same rate, then either the MPI environment is not setup correctly, or the `DistributedGradientTape` is not being used correctly.  Can you try running the TensorFlow 2 MNIST example or synthetic benchmark [here](https://github.com/horovod/horovod/tree/master/examples) to see if you get the same behavior?

**Comment by ashiqimranintel** [comment]
I have get a fresh copy and installed horovod latest version (0.20.0). I think mpi processes are in synch. However, I am seeing performance degradation. I am checking out the implementation of resnet50 in TF2.X [https://github.com/tensorflow/models/blob/master/official/vision/image_classification/classifier_trainer.py]. To enable Horovod in this codebase, which version of horovod should I use (horovod.tensorflow.keras or horovod.tensorflow)?

**Comment by tgaddair** [comment]
You should use `horovod.tensorflow.keras`.

**Comment by ashiqimranintel** [comment]
Hi @tgaddair , I am trying to enable support of Horovod on the model. However, I am getting some errors with the following function.

def DistributedOptimizer(optimizer, name=None,
                         device_dense='', device_sparse='',
                         compression=Compression.none,
                         sparse_as_dense=False,
                         gradient_predivide_factor=1.0)

this are the default values of device_dense and device_sparse, HOROVOD_GPU_OPERATIONS. 

I am running on CPU, what should I put as device_dense?

**Comment by tgaddair** [comment]
It should be fine to leave it as is.  What's the error you're seeing?  Are you seeing the same error when running `tensorflow2_mnist.py`?

**Comment by ashiqimranintel** [comment]
I am getting issues, here
File "/localdisk/aimran/TF2.4bin/horovod/_keras/__init__.py", line 111, in create_distributed_optimizer
    return cls.from_config(optimizer.get_config())
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 976, in from_config
    config["learning_rate"], custom_objects=custom_objects)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/optimizer_v2/learning_rate_schedule.py", line 1007, in deserialize
    printable_module_name="decay")
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/utils/generic_utils.py", line 347, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/localdisk/aimran/TF2.4bin/tensorflow/python/keras/utils/generic_utils.py", line 296, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown decay: WarmupDecaySchedule



Here is my code snippet from [https://github.com/tensorflow/models/blob/master/official/vision/image_classification/classifier_trainer.py#L331]

    learning_rate = optimizer_factory.build_learning_rate(
        params=params.model.learning_rate,
        batch_size=train_builder.global_batch_size,
        train_epochs=train_epochs,
        train_steps=train_steps)
    optimizer = optimizer_factory.build_optimizer(
        optimizer_name=params.model.optimizer.name,
        base_learning_rate=learning_rate,
        params=params.model.optimizer.as_dict(),
        model=model)

   optimizer = hvd.DistributedOptimizer(optimizer)

**Comment by tgaddair** [comment]
Looks like it's failing on `from_config` because there are custom objects in the optimizer that cannot be loaded correctly.

There is a similar issue here: https://github.com/huggingface/transformers/issues/5554

The suggestion there is to create an intermediate optimizer class to override the `from_config` call.  Is that a workable solution in your case for now?

As a TODO on our side, we should allow passing in a dict of `custom_objects` when creasing the `DistributedOptimizer` so we can call `from_config` with these objects automatically.

**Comment by ashiqimranintel** [comment]
Thanks for the response. I am trying to follow the the steps that was mentioned in the huggingface/transformers#5554 . But, it's on the tensorflow side. Can you give me some patch which can I apply on horovod side?

**Comment by ashiqimranintel** [comment]
Hi @tgaddair, I am trying to enable horovod on transformer model of tensorflow. https://github.com/ashiqimranintel/models/blob/master/official/nlp/transformer/transformer_main.py 
Since this code tf.GradidentTape() 
I was trying to horovod.tensorflow 2.0 ? Is it correct?

**Comment by tgaddair** [comment]
Hey @ashiqimranintel, if you're using `tf.GradientTape()`, then your code should follow [this](https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py#L64) format, which means you don't need to worry about `from_config`.

**Comment by ashiqimranintel** [comment]
Hi @tgaddair, actually I was checking for tf.GradientTape() model. it's present in the  It's not present in the Resnet50 model. So for the resnet50, I still need to bypass from_config error. I will try to fix it on the TF side.

**Comment by ashiqimranintel** [comment]
Hi @tgaddair, can I integrate horovod with tf.DistributedStrategy? Distributed Strategy also is using all_reduce inside of it. Any comments or suggestions?

**Comment by tgaddair** [comment]
Hey @ashiqimranintel, Horovod does not use TF's DistributedStrategy.  They have a very different mechanism to enable distributed training.
