### ISSUE TITLE
Fail to import horovod.tensorflow.functions

### ISSUE THREAD

**Issue by heyuntian** [horovod/horovod#2306]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.15.0
3. Horovod version:0.19.5
4. MPI version:4.0.1
5. CUDA version:10.0
6. NCCL version:
7. Python version:2.7
8. OS and version:CentOS 
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

I am trying to use the broadcast_object function, but I failed to `import horovod.tensorflow.functions` module. 
`ImportError: No module named functions`.

**Comment by tgaddair** [comment]
Hey @heyuntian, please upgrade to the latest version of Horovod (v0.20.0) for this feature.

**Comment by heyuntian** [comment]
@tgaddair Hi when I use pip install horovod==0.20.0 (environment variable ignored here) it says

ERROR: Could not find a version that satisfies the requirement horovod==0.20.0 (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.10, 0.13.11, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.19.5)
ERROR: No matching distribution found for horovod==0.20.0

**Comment by tgaddair** [comment]
Hey @heyuntian, I missed that you were using Python 2.7.  Horovod 0.19.5 was the last version to support Python 2, as it has been officially deprecated since January.  Are you able to upgrade to Python 3?

**Comment by heyuntian** [comment]
I create a new python 3.7 conda environment, load the same modules and install TF of same version. Now I cannot even install horovod. 

/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/site-packages/tensorflow_core/include/tensorflow/core/protobuf/config.pb.h:3184:8: error: 'bool tensorflow::TensorConnection::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)' marked 'final', but is not virtual
     bool MergePartialFromCodedStream(
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/site-packages/tensorflow_core/include/tensorflow/core/protobuf/config.pb.h:3187:8: error: 'void tensorflow::TensorConnection::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const' marked 'final', but is not virtual
     void SerializeWithCachedSizes(
          ^~~~~~~~~~~~~~~~~~~~~~~~
  /home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/site-packages/tensorflow_core/include/tensorflow/core/protobuf/config.pb.h:3189:35: error: 'google::protobuf::uint8* tensorflow::TensorConnection::InternalSerializeWithCachedSizesToArray(google::protobuf::uint8*) const' marked 'final', but is not virtual
     ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/site-packages/tensorflow_core/include/tensorflow/core/protobuf/config.pb.h:3582:38: error: 'InternalMetadataWithArena' in namespace 'google::protobuf::internal' does not name a type
     ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
  /home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/site-packages/tensorflow_core/include/tensorflow/core/protobuf/config.pb.h:3379:42: error: 'google::protobuf::Arena* tensorflow::CallableOptions::GetArena() const' marked 'final', but is not virtual
     inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArena() const final {




Something weird I found is that it doesn't find an MPI_C, but the modules are the same as I used in the previous environment.

  -- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES)
  CMake Warning at third_party/gloo/cmake/Dependencies.cmake:72 (message):
    Not compiling with MPI support.  Suppress this warning with -DUSE_MPI=OFF.
  Call Stack (most recent call first):
    third_party/gloo/CMakeLists.txt:75 (include)

**Comment by tgaddair** [comment]
@heyuntian, it looks like your version of protobuf is incompatible with the version of TensorFlow.  What version of `protobuf` do you have in your environment?

**Comment by heyuntian** [comment]
The version of `protobuf`:
protobuf                  3.13.0           py37hf484d3e_0

**Comment by tgaddair** [comment]
For TensorFlow 1.15, I would recommend using protobuf 3.8.0 as indicated [here](https://github.com/tensorflow/tensorflow/blob/v1.15.0/tensorflow/workspace.bzl#L419).

**Comment by heyuntian** [comment]
Still the same, maybe I can provide more error information. Below is the last output before ending the installation.

gmake[2]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/mpi_ops.cc.o] Error 1
    gmake[2]: *** Waiting for unfinished jobs....
    gmake[2]: Leaving directory `/tmp/pip-install-h9t2mx3k/horovod/build/temp.linux-x86_64-3.7'
    gmake[1]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/all] Error 2
    gmake[1]: Leaving directory `/tmp/pip-install-h9t2mx3k/horovod/build/temp.linux-x86_64-3.7'
    gmake: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h9t2mx3k/horovod/setup.py", line 166, in <module>
        'horovodrun = horovod.runner.launch:run_commandline'
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-h9t2mx3k/horovod/setup.py", line 87, in build_extensions
        cwd=self.build_temp)
      File "/home/he.1773/miniconda2/envs/hvdpy3/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
