### ISSUE TITLE
Performance is worse after rebuilding C++ code

### ISSUE THREAD

**Issue by zhao1157** [horovod/horovod#2311]
I built a horovod image using the official `Dockerfile.gpu` file. In its container, I rebuilt horovod using the latest master branch of horovod source code, and compared the performance of the horovod I built from source (hereafter `horovod-rebuilt`)and the one in the original horovod docker image (hereafter `horovod-docker`). The result was quite a surprise. 

1. MNIST with 8 V100 GPUs: I did some tests with the script `tensorflow2_keras_mnist.py` in the docker container `/example` directory, and found `horovod-docker` got a performance of `~20 ms/step` while `horovod-rebuilt` got `~40 ms/step`. I thought this might be due to the `c++` code, so I exchanged the `.so` files in `horovod-docker` and `horovod-rebuilt` and redid the tests. It showed that the `.so` file in the original `horovod-docker` got `~20 ms/step` while the one in the original `horovod-rebuitl` got `~40 ms/step`.

2. Resnet50 with 8/1 V100 GPUs: I also did some tests on `Resnet50`. All my tests showed that the `.so` file from the original `horovod-docker` always performed better than the one I built myself did. For 8 GPUs, the former reached `~2200 images/s` and the latter `~1400 images/s`. For 1 GPU, the former `~366 images/s` and the latter `~ 355 images/s`.

So I think there must be something I missed when building horovod from the current master branch. The command I used is just `python setup.py install`. I am not sure what I missed that is included in the `.so` file in `horovod-docker`.

**Comment by tgaddair** [comment]
Hey @zhao1157, can you run `horovodrun --check-build` to verify that NCCL support is properly enabled?

**Comment by zhao1157** [comment]
Hi @tgaddair, thanks for your help. For both `horovod-docker` and `horovod-rebuilt`, `horovodrun --check-build` gives the following output:

> Available Frameworks:
    [X] TensorFlow
    [X] PyTorch
    [X] MXNet

>Available Controllers:
    [X] MPI
    [X] Gloo

> Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo

**Comment by zhao1157** [comment]
@tgaddair I tried to enable `NCLL` by manually setting the following line to `true`
https://github.com/horovod/horovod/blob/32e5fdbf33fb2dac9d725028a886a093984c3618/CMakeLists.txt#L176

I also commented out the following lines to test only `tensorflow`
https://github.com/horovod/horovod/blob/32e5fdbf33fb2dac9d725028a886a093984c3618/CMakeLists.txt#L280-L283

I saw some compiling output about `NCCL`
> -- Linking against static NCCL library
-- Found NCCL: /usr/include
-- Determining NCCL version from the header file: /usr/include/nccl.h
-- NCCL_MAJOR_VERSION: 2
-- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl_static.a)

But it stopped at about 85% of the compiling process
> [ 85%] Building CXX object horovod/tensorflow/CMakeFiles/tensorflow.dir/\__/common/optim/gaussian_process.cc.o
*** a super long compiling command line here ***
horovod/tensorflow/CMakeFiles/tensorflow.dir/build.make:206: recipe for target 'horovod/tensorflow/CMakeFiles/tensorflow.dir/\__/common/operations.cc.o' failed
make[2]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/\__/common/operations.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Hope that might help you in some way.

**Comment by zhao1157** [comment]
@tgaddair Update: `Torch` and `MXNet` can pass the `NCCL` compiling.

**Comment by zhao1157** [comment]
@tgaddair After a little bit of debugging, I fixed the above error by adding a line `ADD_CUDA()` behind the definition of `macro(ADD_CUDA)`.
https://github.com/horovod/horovod/blob/32e5fdbf33fb2dac9d725028a886a093984c3618/CMakeLists.txt#L137-L156

And `horovodrun --check-build` returns
> Available Frameworks:
    [X] TensorFlow
    [ ] PyTorch
    [ ] MXNet

>Available Controllers:
    [X] MPI
    [X] Gloo

>Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo

However, the performance of the rebuilt horovod still can not match `horovod-docker`. Maybe I did not manage to get `NCCL` built into horovod?

**Comment by zhao1157** [comment]
@tgaddair I used `tensorboard` to check if `NCCL` was built properly. Compared with the kernel output information using both `horovod-docker` and `NGC-tf-image`, the rebuilt horovod does not show the `NCCL` kernel `ncclAllReduceRingLLKernel_sumf32(ncclColl)`. So I guess my trial did not build `NCCL` correctly.

**Comment by zhao1157** [comment]
@tgaddair I just found to be able to activate `NCCL`, I need to set an environment variable `HOROVOD_GPU_OPERATIONS=NCCL`. Now everything clicks.

**Comment by tgaddair** [comment]
Thanks for digging into this, @zhao1157.  So sounds like there are at least a few issues on our side here.  One is that NCCL support seemed to be compiled in but was not being used at runtime.  And it sounds like you needed to modify the CMakeLists file in order to get NCCL to work with TensorFlow.  Is that all correct?

**Comment by zhao1157** [comment]
@tgaddair With `HOROVOD_GPU_OPERATIONS=NCCL`, I think the original `CMakeLists.txt` works just fine without needing to be modified. I changed a few things in the `CMakeLists.txt` file before I realizing I should set that environment variable. With that environment variable and the original `CMakeLists.txt`, I reproduced the performance of `horovod-docker`.

**Comment by tgaddair** [comment]
Gotcha, thanks for clarifying!
