### ISSUE TITLE
Is it possible to hide/adjust Stalled ranks errors?

### ISSUE THREAD

**Issue by austinmw** [horovod/horovod#2315]
**Your question:**

Is there a way to hide (or preferably increase time until) Stalled ranks error messages?

While my model is performing periodic evaluation every 10 epochs I get spammed with these messages.

**Comment by tgaddair** [comment]
Hey @austinmw, as I commented on #342, you can provide args to `horovodrun` to configure this:

- `--stall-check-warning-time-seconds`
- `--stall-check-shutdown-time-seconds`

**Comment by Lihengwannafly** [comment]
> Hey @austinmw, as I commented on #342, you can provide args to `horovodrun` to configure this:
> 
> * `--stall-check-warning-time-seconds`
> * `--stall-check-shutdown-time-seconds`

Hi, @tgaddair , i wanna know if the waiting time exceed stall-check-shutdown-time-seconds, gradient update of the certain step will be ignored or the running train task will be killed?

**Comment by tgaddair** [comment]
Hey @Lihengwannafly, if the shutdown time is exceeded, the entire training process will be killed.
