### ISSUE TITLE
ld returned 1 exit status during installation

### ISSUE THREAD

**Issue by heyuntian** [horovod/horovod#2317]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow
2. Framework version: 1.15
3. Horovod version: 0.19.5
4. MPI version: MVAPICH2-GDR-2.3.4
5. CUDA version: 10.2
6. NCCL version: 2.7.8
7. Python version: 2.7
8. OS and version: CentOS 7.8
9. GCC version: 4.8.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

/home/he.1773/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lcuda
    /home/he.1773/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lcuda
    collect2: error: ld returned 1 exit status
    error: command '/home/he.1773/miniconda2/bin/x86_64-conda_cos6-linux-gnu-c++' failed with exit status 1

**Comment by tgaddair** [comment]
Hey @heyuntian, is CUDA on your `LD_LIBRARY_PATH`?

**Comment by heyuntian** [comment]
@tgaddair Yes. `LD_LIBRARY_PATH` has mvapich2, nccl, gcc, and cuda.

**Comment by tgaddair** [comment]
Can you check that `libcuda.so.1` is also available in that directory?  See https://github.com/apache/incubator-mxnet/issues/8436.

**Comment by heyuntian** [comment]
I tried to install on other nodes and now finished. However, it is not working with my MPI library, but I'm not sure it's due to Horovod.
