### ISSUE TITLE
what is the meaning of "num_partitions , train_data_path , val_data_path , train_partitions,  train_rows"

### ISSUE THREAD

**Issue by WangHeguan** [horovod/horovod#2319]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
num_partitions=120
writing dataframes
train_data_path=file:///tmp/intermediate_train_data.0
val_data_path=file:///tmp/intermediate_val_data.0
train_partitions=120
train_rows=2

what is the meaning of "num_partitions , train_data_path , val_data_path , train_partitions,  train_rows", and how can I edit them?

**Comment by WangHeguan** [comment]
And why the train_rows=2, ,my train dataframe has thounds rows.

**Comment by tgaddair** [comment]
Hey @WangHeguan, to answer your questions:

1. `num_partitions` can be configured by the [partitions_per_process](https://github.com/horovod/horovod/blob/543c4be18a5f2e32d7023e9d5e20c7dfe8cf9899/horovod/spark/common/params.py#L77) param to `Estimator`.
2. `train_data_path` and `val_data_path` are configured by the [Store](https://github.com/horovod/horovod/blob/master/horovod/spark/common/store.py#L30).
3. `train_rows` is determined automatically.  If only two rows are being listed, then there may be an issue with your DataFrame.  You may want to try reducing the number of partitions and see if that has an effect.  You can also use `parquet-tools` to check that output `file:///tmp/intermediate_train_data.0` for correctness.

**Comment by WangHeguan** [comment]
@tgaddair I reduce the number of partitions but noting effect, still two rows are listed. And I used parquet-tools to check the .parquet file, shows below:
features:
.list:
..element = 0.6747189888132679
.list:
..element = 0.6764690456324719
.list:
..element = 0.6770257091378709
label_vec:
.list:
..element = 0.6772735092781896

features:
.list:
..element = 0.6764690456324719
.list:
..element = 0.6770257091378709
.list:
..element = 0.6772735092781896
label_vec:
.list:
..element = 0.6807579137052481

features:
.list:
..element = 0.6770257091378709
.list:
..element = 0.6772735092781896
.list:
..element = 0.6807579137052481
label_vec:
.list:
..element = 0.6738015201955847

features:
.list:
..element = 0.6772735092781896
.list:
..element = 0.6807579137052481
.list:
..element = 0.6738015201955847
label_vec:
.list:
..element = 0.6710475940962757
.
.
.
.
.
.
is it something incorrect ?

**Comment by orwa-te** [comment]
> Hey @WangHeguan, to answer your questions:
> 
> 1. `num_partitions` can be configured by the [partitions_per_process](https://github.com/horovod/horovod/blob/543c4be18a5f2e32d7023e9d5e20c7dfe8cf9899/horovod/spark/common/params.py#L77) param to `Estimator`.
> 2. `train_data_path` and `val_data_path` are configured by the [Store](https://github.com/horovod/horovod/blob/master/horovod/spark/common/store.py#L30).
> 3. `train_rows` is determined automatically.  If only two rows are being listed, then there may be an issue with your DataFrame.  You may want to try reducing the number of partitions and see if that has an effect.  You can also use `parquet-tools` to check that output `file:///tmp/intermediate_train_data.0` for correctness.

What is the relationship between `train_df.rdd.getNumPartitions()` and `num_partitions` param in `fit` function?
For [mnist example](https://github.com/horovod/horovod/blob/master/examples/spark/keras/keras_spark_mnist.py) the first one returns 2 partitions, but the second returns 10 partitions for `num_proc=1` and 20 partitions when `num_proc=2` !
