### ISSUE TITLE
How to save a h5 model

### ISSUE THREAD

**Issue by WangHeguan** [horovod/horovod#2323]
I use horovod KerasEstimator to train a keras lstm model，now I want to save it into h5 model. I can not find related API. How can I do . Please help me.

**Comment by tgaddair** [comment]
Hey @WangHeguan, one you have the trained model from `transformer = estimator.fit(...)`, you can call `transformer.getModel()` to obtain the underlying Keras model.  So something like:

```
transformer = estimator.fit(...)
trained_model = transformer.getModel()
with h5py.File(filename) as f:
    trained_model.save(f)
```
