### ISSUE TITLE
documentation question about advanced mpi4py usage

### ISSUE THREAD

**Issue by denfromufa** [horovod/horovod#2324]
This is a documentation question about advanced mpi4py usage. It is mentioned that mpi4py can be used with Horovod in 2 modes: mixed Horovod/MPI communication with MPI multi-threading support, and sub-communicator approach with each independent Horovod "ring":

https://github.com/horovod/horovod#mpi4py

What is not clear, if I can mix both approaches?

For example, I plan to re-use Horovod broadcasting for `Tensor` objects in the "main" communicator since mpi4py does not support this out-of-the box.

**Comment by tgaddair** [comment]
Hey @denfromufa, could you clarify the approach a bit?  You wish to have a Horovod session using the main communicator (for broadcasting) as well as a second Horovod session using a subcommunicator?  Will these Horovod sessions need to run at the same time?

**Comment by denfromufa** [comment]
@tgaddair 
> You wish to have a Horovod session using the main communicator (for broadcasting) as well as a second Horovod session using a subcommunicator?

Yes!

> Will these Horovod sessions need to run at the same time?

I can close the main communicator horovod session after horovod broadcasting is complete and just keep Horovod sessions in sub-communicators.

**Comment by tgaddair** [comment]
That should be fine then.  Where I suspect you would run into trouble is if you wanted to have a two Horovod sessions with different communicators simultaneously.  Since Horovod maintains global state, this would not work.  But so long as you call `hvd.shutdown()` at the end of the global broadcasting, it should be fine.

**Comment by FruVirus** [comment]
@tgaddair 

By multiple Horovod sessions, do you mean something like the following?

Suppose we have 2 nodes, 2 gpus each

```
color = 0 if MPI.COMM_WORLD.rank < MPI.COMM_WORLD.Get_size() // 2 else 1
comm = MPI.COMM_WORLD
subcomm = MPI.COMM_WORLD.Split(color=color)

hvd.init(subcomm)
do some stuff on ranks 0 and 1 on both subcomms
hvd.shutdown()

hvd.init(comm)
do some stuff across all 4 ranks on the main comm
```
