### ISSUE TITLE
does horovod support tensorflow（AMP） traing？

### ISSUE THREAD

**Issue by wpf19911118** [horovod/horovod#2349]
**Environment:**
1. Framework: 
(TensorFlow, Keras)

2. Framework version:
1.15 （NGC docker）
3. Horovod version:
latest 0.19.1
4. MPI version:
3.1.6
5. CUDA version:
11.0
6. NCCL version:
2.7.5
7. Python version:
3.6
8. OS and version:
18.04
9. GCC version:
7.5.0
**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

yes

**Your question:**
Please ask your question here.
horovod support tensorflow（AMP） traing？

         model = tf.keras.models.Model(inputs=model_input, outputs=[cls_pred, re_pred])

        optim = tf.keras.optimizers.Adam(learning_rate * hvd.size())

        # optim = tf.train.AdamOptimizer(learning_rate = learning_rate * hvd.size())

        # optim = hvd.DistributedOptimizer(optim)

        # optim = tf.train.experimental.enable_mixed_precision_graph_rewrite(optim)

        optim = tf.keras.mixed_precision.experimental.LossScaleOptimizer(optim, "dynamic")
        model.compile(optimizer=hvd.DistributedOptimizer(optim),

[1,7]<stderr>:Traceback (most recent call last):
[1,7]<stderr>:  File "fbp.py", line 61, in <module>
[1,7]<stderr>:    model.train()
[1,7]<stderr>:  File "/workspace/code/model.py", line 134, in train
[1,7]<stderr>:    model = self.get_model()
[1,7]<stderr>:  File "/workspace/code/model.py", line 121, in get_model
[1,7]<stderr>:    model.compile(optimizer=hvd.DistributedOptimizer(optim),
[1,7]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod-0.19.1-py3.6-linux-x86_64.egg/horovod/tensorflow/keras/__init__.py", line 67, in DistributedOptimizer
[1,7]<stderr>:    sparse_as_dense)
[1,7]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/horovod-0.19.1-py3.6-linux-x86_64.egg/horovod/_keras/__init__.py", line 85, in create_distributed_optimizer
[1,7]<stderr>:    return cls.from_config(optimizer.get_config())
[1,7]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/mixed_precision/experimental/loss_scale_optimizer.py", line 292, in get_config
[1,7]<stderr>:    raise NotImplementedError('get_config() is not yet implemented for '
[1,7]<stderr>:NotImplementedError: get_config() is not yet implemented for LossScaleOptimizers

**Comment by tgaddair** [comment]
Hey @wpf19911118, yes Horovod does work with `LossScaleOptimizer`, though it may vary somewhat depending on TensorFlow version.  @DEKHTIARJonathan may be able to provide more info on usage.

**Comment by DEKHTIARJonathan** [comment]
You use AMP incorrectly with Keras, shall be use as follow:

```python
import tensorflow as tf

policy = tf.keras.mixed_precision.experimental.Policy("mixed_float16", loss_scale="dynamic")
tf.keras.mixed_precision.experimental.set_policy(policy)

print('Compute dtype: %s' % policy.compute_dtype)  # Compute dtype: float16
print('Variable dtype: %s' % policy.variable_dtype)  # Variable dtype: float32
```

You want to define the policy **before** you define your keras model.

**Comment by wpf19911118** [comment]
> You use AMP incorrectly with Keras, shall be use as follow:
> 
> ```python
> import tensorflow as tf
> 
> policy = tf.keras.mixed_precision.experimental.Policy("mixed_float16", loss_scale="dynamic")
> tf.keras.mixed_precision.experimental.set_policy(policy)
> 
> print('Compute dtype: %s' % policy.compute_dtype)  # Compute dtype: float16
> print('Variable dtype: %s' % policy.variable_dtype)  # Variable dtype: float32
> ```
> 
> You want to define the policy **before** you define your keras model.



> You use AMP incorrectly with Keras, shall be use as follow:
> 
> ```python
> import tensorflow as tf
> 
> policy = tf.keras.mixed_precision.experimental.Policy("mixed_float16", loss_scale="dynamic")
> tf.keras.mixed_precision.experimental.set_policy(policy)
> 
> print('Compute dtype: %s' % policy.compute_dtype)  # Compute dtype: float16
> print('Variable dtype: %s' % policy.variable_dtype)  # Variable dtype: float32
> ```
> 
> You want to define the policy **before** you define your keras model.

I have tried your function, but the programm tells me "The global policy can only set to a non-infer policy in TF 2",But acctually I used the Tf in Version 1.15

**Comment by DEKHTIARJonathan** [comment]
If you use Keras. Why using TF1.x ? TF2.x will give you so much more.
I'm not sure AMP is supported with Keras in TF1.x, I would need to double check

**Comment by wpf19911118** [comment]
> If you use Keras. Why using TF1.x ? TF2.x will give you so much more.
> I'm not sure AMP is supported with Keras in TF1.x, I would need to double check

enen，I‘ll pull a new docker images with tf 2.x and try it
