### ISSUE TITLE
pip install fails. ubuntu 20.04 cuda 10.1 python3.8 tensorflow 2.2

### ISSUE THREAD

**Issue by maxlacourchristensen** [horovod/horovod#2353]
[ 67%] Built target compatible_gloo
    make[1]: Leaving directory '/tmp/pip-install-b45r3x6k/horovod/build/temp.linux-x86_64-3.8'
    make: *** [Makefile:130: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b45r3x6k/horovod/setup.py", line 142, in <module>
        setup(name='horovod',
      File "/home/rig/Downloads/envs/tf2.2/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/rig/Downloads/envs/tf2.2/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/rig/Downloads/envs/tf2.2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-b45r3x6k/horovod/setup.py", line 90, in build_extensions
        subprocess.check_call([cmake_bin, '--build', '.'] + cmake_build_args,
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/rig/Downloads/envs/tf2.2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b45r3x6k/horovod/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b45r3x6k/horovod/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l9bdfggq/install-record.txt --single-version-externally-managed --compile --install-headers /home/rig/Downloads/envs/tf2.2/include/site/python3.8/horovod Check the logs for full command output.

Seems subprocess call to cmake fails. cmake version 3.16.3 is installed. Can you assist?

**Comment by maxlacourchristensen** [comment]
just tried with python 3.7.9, same error

**Comment by tgaddair** [comment]
Hey @maxlacourchristensen, can you share the full log output?  The true error is hidden somewhere above.

You may also want to try installing with `MAKEFLAGS="-j1"` so the error is closer to the bottom of the log.

**Comment by maxlacourchristensen** [comment]
thx for helping @tgaddair. I have looked for the logs but can't find them. all the files in /tmp are gone. where do i find the logs?

**Comment by tgaddair** [comment]
Just the output of stdout/stderr.  If your terminal window keeps enough history, you can just copy/paste.  Otherwise, you can redirect to a file when calling `pip install horovod`.

**Comment by maxlacourchristensen** [comment]
@tgaddair ah ok. found the problem. i forgot to switch to gcc-8. thanks

**Comment by tgaddair** [comment]
Great!  I'll go ahead and close this issue, then.

**Comment by George0112** [comment]
I'm using TF1.15 and python3.6 and ran into the same error.
I install horovod by 
`HOROVOD_GPU_OPERATIONS=NCCL MAKEFLAGS="-j1" python3.6 -m pip install --no-cache-dir horovod`
I've tried to use gcc-8 but still the same, is there anything also need to be changed?

`python3.6 -m pip install --no-cache-dir horovod` can successfully install horovod but I need NCCL...

I also have libnccl2, libnccl-dev 2.7.8-1+cuda10.1 installed.

**Comment by tgaddair** [comment]
Hey @George0112, we will need to take a look at the log output to know what's going on.  The error message that was shown here is just a generic "something didn't work" message.

**Comment by wjy3326** [comment]
i got the same problem, this is my error log.
 [ 41%] Building CXX object third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/buffer.cc.o
    cd /tmp/pip-0da6qhiq-build/build/temp.linux-x86_64-3.6/third_party/compatible_gloo/gloo && /usr/bin/c++  -DEIGEN_MPL2_ONLY=1 -DGLOO_USE_MPI=1 -DHAVE_CUDA=1 -DHAVE_GLOO=1 -DHAVE_GPU=1 -DHAVE_MPI=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE=78 -D_GLIBCXX_USE_CXX11_ABI=0 -I/tmp/pip-0da6qhiq-build/third_party/HTTPRequest/include -I/tmp/pip-0da6qhiq-build/third_party/boost/assert/include -I/tmp/pip-0da6qhiq-build/third_party/boost/config/include -I/tmp/pip-0da6qhiq-build/third_party/boost/core/include -I/tmp/pip-0da6qhiq-build/third_party/boost/detail/include -I/tmp/pip-0da6qhiq-build/third_party/boost/iterator/include -I/tmp/pip-0da6qhiq-build/third_party/boost/lockfree/include -I/tmp/pip-0da6qhiq-build/third_party/boost/mpl/include -I/tmp/pip-0da6qhiq-build/third_party/boost/parameter/include -I/tmp/pip-0da6qhiq-build/third_party/boost/predef/include -I/tmp/pip-0da6qhiq-build/third_party/boost/preprocessor/include -I/tmp/pip-0da6qhiq-build/third_party/boost/static_assert/include -I/tmp/pip-0da6qhiq-build/third_party/boost/type_traits/include -I/tmp/pip-0da6qhiq-build/third_party/boost/utility/include -I/tmp/pip-0da6qhiq-build/third_party/eigen -I/tmp/pip-0da6qhiq-build/third_party/flatbuffers/include -I/tmp/pip-0da6qhiq-build/third_party/lbfgs/include -isystem /usr/local/include -isystem /usr/local/cuda/include -isystem /usr/local/nccl_2.5.6/include -I/tmp/pip-0da6qhiq-build/third_party/gloo -I/tmp/pip-0da6qhiq-build/third_party/compatible_gloo -I/tmp/pip-0da6qhiq-build/build/temp.linux-x86_64-3.6/third_party/compatible_gloo  -pthread -fPIC -Wall -ftree-vectorize -mf16c -mavx -mfma -std=c++11 -fPIC -O3 -g -DNDEBUG   -std=c++11 -o CMakeFiles/compatible_gloo.dir/transport/tcp/buffer.cc.o -c /tmp/pip-0da6qhiq-build/third_party/compatible_gloo/gloo/transport/tcp/buffer.cc
    In file included from /tmp/pip-0da6qhiq-build/third_party/compatible_gloo/gloo/transport/tcp/address.cc:9:0:
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    [ 42%] Building CXX object third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/context.cc.o
    cd /tmp/pip-0da6qhiq-build/build/temp.linux-x86_64-3.6/third_party/compatible_gloo/gloo && /usr/bin/c++  -DEIGEN_MPL2_ONLY=1 -DGLOO_USE_MPI=1 -DHAVE_CUDA=1 -DHAVE_GLOO=1 -DHAVE_GPU=1 -DHAVE_MPI=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE=78 -D_GLIBCXX_USE_CXX11_ABI=0 -I/tmp/pip-0da6qhiq-build/third_party/HTTPRequest/include -I/tmp/pip-0da6qhiq-build/third_party/boost/assert/include -I/tmp/pip-0da6qhiq-build/third_party/boost/config/include -I/tmp/pip-0da6qhiq-build/third_party/boost/core/include -I/tmp/pip-0da6qhiq-build/third_party/boost/detail/include -I/tmp/pip-0da6qhiq-build/third_party/boost/iterator/include -I/tmp/pip-0da6qhiq-build/third_party/boost/lockfree/include -I/tmp/pip-0da6qhiq-build/third_party/boost/mpl/include -I/tmp/pip-0da6qhiq-build/third_party/boost/parameter/include -I/tmp/pip-0da6qhiq-build/third_party/boost/predef/include -I/tmp/pip-0da6qhiq-build/third_party/boost/preprocessor/include -I/tmp/pip-0da6qhiq-build/third_party/boost/static_assert/include -I/tmp/pip-0da6qhiq-build/third_party/boost/type_traits/include -I/tmp/pip-0da6qhiq-build/third_party/boost/utility/include -I/tmp/pip-0da6qhiq-build/third_party/eigen -I/tmp/pip-0da6qhiq-build/third_party/flatbuffers/include -I/tmp/pip-0da6qhiq-build/third_party/lbfgs/include -isystem /usr/local/include -isystem /usr/local/cuda/include -isystem /usr/local/nccl_2.5.6/include -I/tmp/pip-0da6qhiq-build/third_party/gloo -I/tmp/pip-0da6qhiq-build/third_party/compatible_gloo -I/tmp/pip-0da6qhiq-build/build/temp.linux-x86_64-3.6/third_party/compatible_gloo  -pthread -fPIC -Wall -ftree-vectorize -mf16c -mavx -mfma -std=c++11 -fPIC -O3 -g -DNDEBUG   -std=c++11 -o CMakeFiles/compatible_gloo.dir/transport/tcp/context.cc.o -c /tmp/pip-0da6qhiq-build/third_party/compatible_gloo/gloo/transport/tcp/context.cc
    [ 43%] Building CXX object third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/device.cc.o
    cd /tmp/pip-0da6qhiq-build/build/temp.linux-x86_64-3.6/third_party/compatible_gloo/gloo && /usr/bin/c++  -DEIGEN_MPL2_ONLY=1 -DGLOO_USE_MPI=1 -DHAVE_CUDA=1 -DHAVE_GLOO=1 -DHAVE_GPU=1 -DHAVE_MPI=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE=78 -D_GLIBCXX_USE_CXX11_ABI=0 -I/tmp/pip-0da6qhiq-build/third_party/HTTPRequest/include -I/tmp/pip-0da6qhiq-build/third_party/boost/assert/include -I/tmp/pip-0da6qhiq-build/third_party/boost/config/include -I/tmp/pip-0da6qhiq-build/third_party/boost/core/include -I/tmp/pip-0da6qhiq-build/third_party/boost/detail/include -I/tmp/pip-0da6qhiq-build/third_party/boost/iterator/include -I/tmp/pip-0da6qhiq-build/third_party/boost/lockfree/include -I/tmp/pip-0da6qhiq-build/third_party/boost/mpl/include -I/tmp/pip-0da6qhiq-build/third_party/boost/parameter/include -I/tmp/pip-0da6qhiq-build/third_party/boost/predef/include -I/tmp/pip-0da6qhiq-build/third_party/boost/preprocessor/include -I/tmp/pip-0da6qhiq-build/third_party/boost/static_assert/include -I/tmp/pip-0da6qhiq-build/third_party/boost/type_traits/include -I/tmp/pip-0da6qhiq-build/third_party/boost/utility/include -I/tmp/pip-0da6qhiq-build/third_party/eigen -I/tmp/pip-0da6qhiq-build/third_party/flatbuffers/include -I/tmp/pip-0da6qhiq-build/third_party/lbfgs/include -isystem /usr/local/include -isystem /usr/local/cuda/include -isystem /usr/local/nccl_2.5.6/include -I/tmp/pip-0da6qhiq-build/third_party/gloo -I/tmp/pip-0da6qhiq-build/third_party/compatible_gloo -I/tmp/pip-0da6qhiq-build/build/temp.linux-x86_64-3.6/third_party/compatible_gloo  -pthread -fPIC -Wall -ftree-vectorize -mf16c -mavx -mfma -std=c++11 -fPIC -O3 -g -DNDEBUG   -std=c++11 -o CMakeFiles/compatible_gloo.dir/transport/tcp/device.cc.o -c /tmp/pip-0da6qhiq-build/third_party/compatible_gloo/gloo/transport/tcp/device.cc
    gmake[2]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/address.cc.o] Error 1
    gmake[2]: *** Waiting for unfinished jobs....
    In file included from /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/pair.h:30:0,
                     from /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/buffer.h:20,
                     from /tmp/pip-0da6qhiq-build/third_party/compatible_gloo/gloo/transport/tcp/buffer.cc:9:
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    gmake[2]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/buffer.cc.o] Error 1
    In file included from /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/pair.h:30:0,
                     from /tmp/pip-0da6qhiq-build/third_party/compatible_gloo/gloo/transport/tcp/context.cc:14:
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    In file included from /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/pair.h:30:0,
                     from /tmp/pip-0da6qhiq-build/third_party/compatible_gloo/gloo/transport/tcp/device.cc:20:
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:17: error: ‘is_trivially_copyable’ is not a member of ‘std’
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                     ^
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:48: error: expected primary-expression before ‘>’ token
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                    ^
    /tmp/pip-0da6qhiq-build/third_party/gloo/gloo/transport/tcp/address.h:64:49: error: ‘::value’ has not been declared
       static_assert(std::is_trivially_copyable<Impl>::value, "!");
                                                     ^
    gmake[2]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/device.cc.o] Error 1
    gmake[2]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/transport/tcp/context.cc.o] Error 1
    gmake[2]: Leaving directory `/tmp/pip-0da6qhiq-build/build/temp.linux-x86_64-3.6'
    gmake[1]: *** [third_party/compatible_gloo/gloo/CMakeFiles/compatible_gloo.dir/all] Error 2
    gmake[1]: Leaving directory `/tmp/pip-0da6qhiq-build/build/temp.linux-x86_64-3.6'
    gmake: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-0da6qhiq-build/setup.py", line 191, in <module>
        'horovodrun = horovod.runner.launch:run_commandline'
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-0da6qhiq-build/setup.py", line 91, in build_extensions
        cwd=self.build_temp)
      File "/u01/isi/wangjunyan/envs/py36/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
Can you fix it? Thanks!

**Comment by tgaddair** [comment]
Hey @wjy3326, looks like your version of GCC is out of date.  Please try upgrading to at least GCC 7.  If you need more assistance, please create a new issue so we can better understand the specifics of your environment.

**Comment by PJ-Finlay** [comment]
I have a similar issue. It seems like cmake is returning with a non-zero exit code but there isn't much information on why:
```
$ python3 setup.py install
Building wheel torch-1.9.0a0+git2668149
-- Building version 1.9.0a0+git2668149
cmake --build . --target install --config Release -- -j 2
make: *** No rule to make target 'install'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 876, in <module>
    build_deps()
  File "setup.py", line 354, in build_deps
    build_caffe2(version=version,
  File "/home/argosopentech/argos-translate-dependencies/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/home/argosopentech/argos-translate-dependencies/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/home/argosopentech/argos-translate-dependencies/pytorch/tools/setup_helpers/cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '2']' returned non-zero exit status 2.
```

**Comment by tgaddair** [comment]
Hey @PJ-Finlay, does this issue also occur with released versions of PyTorch (e.g., 1.7 or 1.8)?

**Comment by xbinglzh** [comment]
Can you fix it? Thanks!

**Comment by xbinglzh** [comment]
gmake[1]: *** [horovod/torch/CMakeFiles/pytorch.dir/all] Error 2
  gmake[1]: Leaving directory `/tmp/pip-install-8uv7gg9d/horovod_e5d8bef9e7964384b3ab733f5986b01e/build/temp.linux-x86_64-3.6/RelWithDebInfo'
  gmake: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-8uv7gg9d/horovod_e5d8bef9e7964384b3ab733f5986b01e/setup.py", line 253, in <module>
      'horovodrun = horovod.runner.launch:run_commandline'
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/local/lib64/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-8uv7gg9d/horovod_e5d8bef9e7964384b3ab733f5986b01e/setup.py", line 144, in build_extensions
      subprocess.check_call(command, cwd=cmake_build_dir)
    File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
  ----------------------------------------

**Comment by xbinglzh** [comment]
# cmake --version
cmake version 3.22.5

# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
