### ISSUE TITLE
Horovod Build Failed with Tensorflow master 

### ISSUE THREAD

**Issue by ashiqimranintel** [horovod/horovod#2355]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.4
3. Horovod version: 0.20.3
4. MPI version: 3.0.0
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7
8. Spark / PySpark version: N/A
9. OS and version: Ubuntu 18.04
10. GCC version: 7.5
11. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Yes
4. Did you check if you question is answered in the [troubleshooting guide(https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? No

**Bug report:**
  horovod/tensorflow/CMakeFiles/tensorflow.dir/build.make:734: recipe for target 'horovod/tensorflow/CMakeFiles/tensorflow.dir/mpi_ops.cc.o' failed
  make[2]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/mpi_ops.cc.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  make[2]: Leaving directory '/tmp/pip-install-tnsdnjow/horovod/build/temp.linux-x86_64-3.7'
  CMakeFiles/Makefile2:259: recipe for target 'horovod/tensorflow/CMakeFiles/tensorflow.dir/all' failed
  make[1]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/all] Error 2
  make[1]: Leaving directory '/tmp/pip-install-tnsdnjow/horovod/build/temp.linux-x86_64-3.7'
  Makefile:129: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-tnsdnjow/horovod/setup.py", line 191, in <module>
      'horovodrun = horovod.runner.launch:run_commandline'
    File "/localdisk/aimran/private-tensorflow2.4bin/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/localdisk/aimran/private-tensorflow2.4bin/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/localdisk/aimran/private-tensorflow2.4bin/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-tnsdnjow/horovod/setup.py", line 91, in build_extensions
      cwd=self.build_temp)
    File "anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for horovod

**Comment by tgaddair** [comment]
Hey @ashiqimranintel, TensorFlow made an update to Eigen on master that required us to upgrade.  This has been fixed on master, so please install Horovod from master to use TensorFlow master.

**Comment by ashiqimranintel** [comment]
Hey @tgaddair, when will you publish the latest master on pypi.org ?

**Comment by tgaddair** [comment]
Since this version of TensorFlow is unreleased, I don't think we should push a hotfix release for this right now.

In the meantime, you can install Horovod from master like so:

```
[HOROVOD args...] pip install --no-cache-dir git+https://github.com/horovod/horovod.git@master
```

**Comment by Flamefire** [comment]
IMO this just hints at a much larger problem: You are mixing 2 different versions of Eigen: The one TF installed and which gets included via `-I<prefix>/lib/python3.7/site-packages/tensorflow/include` and the one you vendored as a submodule and include too.

Now depending on the file included you get either of (or even mix) those which can lead to ODR violations. Now updating the Eigen submodule to the same version TF uses resolves the problem but only for that combinations of versions. But it makes it unable to use the next Horovod with the currently released TF or any prior version. Even worse: It may work. And fail at some point under almost impossible to track conditions.

Similar reasoning applies to flatbuffers: TF uses flatbuffers itself any may use another version than Horovod includes again causing ODR violations. However this will only manifest at runtime as TF doesn't seem to install the flatbuffer headers.

I'd strongly suggest to search for a TF or system installed version of the vendored libraries before using them. `find_path` in combination with `NO_DEFAULT_PATH` can be used for that.

**Comment by tgaddair** [comment]
Hey @Flamefire, I agree with the high level idea, which is something the maintainers have been discussing lately, so thanks for raising the issue.  I've opening #2429 to track.
