### ISSUE TITLE
Passing horovodrun timeline option to IBM Watson "ddlrun"

### ISSUE THREAD

**Issue by anubhavj87** [horovod/horovod#2362]
**Environment:**
1. Framework: IBM Watson ML community edition
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version: Redhat
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I am using IBM Watson ML community edition. I want to do performance analysis using horovod timeline. 
ddlrun command can't recognise --timeline-filename option. It only works with horovodrun. Is there any way to pass it to ddlrun command?

**Comment by tgaddair** [comment]
Hey @anubhavj87, yes, you can set environment variables instead, same as how you would do it when using [mpirun](https://github.com/horovod/horovod/blob/master/docs/mpi.rst#horovod-parameter-knobs).

In this case, the variable you want to set it `HOROVOD_TIMELINE`.

**Comment by anubhavj87** [comment]
> Hey @anubhavj87, yes, you can set environment variables instead, same as how you would do it when using [mpirun](https://github.com/horovod/horovod/blob/master/docs/mpi.rst#horovod-parameter-knobs).
> 
> In this case, the variable you want to set it `HOROVOD_TIMELINE`.

Thanks @tgaddair . This environment variable works with ddlrun .
