### ISSUE TITLE
How to use multiple optimizer with multiple GPU?

### ISSUE THREAD

**Issue by Hanzy1996** [horovod/horovod#2368]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) PyTorch
2. Framework version: 1.12
3. Horovod version:  0.20.3
4. MPI version: 4.0.5
5. CUDA version: 10.0
6. NCCL version: 2.6.4
7. Python version: 3.6
8. OS and version: ubuntu 18.04
9. GCC version: 7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? No
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? It does not contain my question.
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? It does not contain my question.
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? It does not contain my question.

**Your question:**
My code contains multiple networks. When I did not use horovod, the optimizers are as below:
optimizer1 = optim.Adam(itertools.chain(netA.parameters(), netB.parameters(), netC.parameters()), lr=opt.lr,
                        betas=(opt.beta1, 0.999))
optimizer2 = optim.Adam(netD.parameters(), lr=opt.lr, betas=(opt.beta1, 0.999))

optimizer1 can update the parameters of multiple networks at the same time.

As far as I understood, to use hvd.DistributedOptimizer and hvd.broadcast_parameters, I have to use more optimizers as below:

optimizerA = optim.Adam(netA.parameters(), lr=opt.lr,betas=(opt.beta1, 0.999))
optimizerB = optim.Adam(netB.parameters(), lr=opt.lr,betas=(opt.beta1, 0.999))
optimizerC = optim.Adam( netC.parameters(), lr=opt.lr,betas=(opt.beta1, 0.999))
optimizerD = optim.Adam(netD.parameters(), lr=opt.lr, betas=(opt.beta1, 0.999))

optimizerA = hvd.DistributedOptimizer(optimizerA, named_parameters=netA.named_parameters())
optimizerB = hvd.DistributedOptimizer(optimizerB, named_parameters=netB.named_parameters())
optimizerC = hvd.DistributedOptimizer(optimizerC, named_parameters=netC.named_parameters())
optimizerD = hvd.DistributedOptimizer(optimizerD, named_parameters=netD.named_parameters())

hvd.broadcast_parameters(netA.state_dict(), root_rank=0)
hvd.broadcast_parameters(netB.state_dict(), root_rank=0)
hvd.broadcast_parameters(netC.state_dict(), root_rank=0)
hvd.broadcast_parameters(netD.state_dict(), root_rank=0)

**First, I am not sure whether these operations are correct.**

A brief of my code is as below:

#define the dataloader
kwargs = {'num_workers': 4, 'pin_memory': True} if opt.cuda else {}
train_set=dataset_hvd.Dataset(data)
train_sampler = torch.utils.data.distributed.DistributedSampler(train_set, num_replicas=hvd.size(), rank=hvd.rank())
train_loader = torch.utils.data.DataLoader(train_set, batch_size=opt.batch_size,sampler=train_sampler, **kwargs)

#The training phase is as below:
batch = next(iter(train_loader)) # I have to use this way to get my batch

netA.zero_grad()
netB.zero_grad()
netC.zero_grad()
netD.zero_grad()
...
#get loss1
...
loss1.backward()  #**raise value error here.**
optimizerA.step()
optimizerB.step()
optimizerC.step()

...
#get loss2
...
loss2.backward()
optimizerD.step()

**Everything works well when I use only one GPU. However,  when I use more than 2 GPUS, I have the following error during loss1.backward():**
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train.py", line 306, in <module>
[1,0]<stderr>:    loss1.backward()
[1,0]<stderr>:  File "/root/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
[1,0]<stderr>:    torch.autograd.backward(self, gradient, retain_graph, create_graph)
[1,0]<stderr>:  File "/root/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
[1,0]<stderr>:    allow_unreachable=True)  # allow_unreachable flag
[1,0]<stderr>:  File "/root/anaconda3/lib/python3.6/site-packages/horovod/torch/optimizer.py", line 147, in hook
[1,0]<stderr>:    handle, ctx = self._allreduce_grad_async(p)
[1,0]<stderr>:  File "/root/anaconda3/lib/python3.6/site-packages/horovod/torch/optimizer.py", line 130, in _allreduce_grad_async
[1,0]<stderr>:    postscale_factor=postscale_factor)
[1,0]<stderr>:  File "/root/anaconda3/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 252, in allreduce_async_
[1,0]<stderr>:    return _allreduce_async(tensor, tensor, name, op, prescale_factor, postscale_factor)
[1,0]<stderr>:  File "/root/anaconda3/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 123, in _allreduce_async
[1,0]<stderr>:    prescale_factor, postscale_factor)
[1,0]<stderr>:**ValueError**: Requested to allreduce, allgather, or broadcast a tensor with the same name as another tensor that is currently being processed.  If you want to request another tensor, use a different tensor name.

Besides, I can run the PyTorch test example you provided on multiple GPUs. Maybe it is not caused by the environment but the multiple optimizers?
I have Google for a long time but cannot find the solution. Could you please help me with this problem?

**Comment by Hanzy1996** [comment]
Emmmmm.......I have solved this problem :

optimizer1 = optim.Adam(itertools.chain(netA.parameters(), netB.parameters(), netC.parameters()), lr=opt.lr,
betas=(opt.beta1, 0.999))
optimizer2 = optim.Adam(netD.parameters(), lr=opt.lr, betas=(opt.beta1, 0.999))

optimizer1 = hvd.DistributedOptimizer(optimizer1) ** named_parameters is not necessary**
optimizer2 = hvd.DistributedOptimizer(optimizer2, named_parameters=netD.named_parameters())

hvd.broadcast_parameters(netA.state_dict(), root_rank=0)
hvd.broadcast_parameters(netB.state_dict(), root_rank=0)
hvd.broadcast_parameters(netC.state_dict(), root_rank=0)
hvd.broadcast_parameters(netD.state_dict(), root_rank=0)

This DO WORK for me.

**Comment by tgaddair** [comment]
Hey @Hanzy1996, please take a look at [this](https://github.com/horovod/horovod/issues/1417#issuecomment-588367250) example for using multiple optimizers with PyTorch.

Basically, the things we need to watch out for are:

1. Make sure the named parameters we give to each optimizer are filtered correctly.
2. Call `optimizer2.synchronize()` and `optimizer2.zero_grad()` on every other optimizer after calling `optimizer.step()`.
