### ISSUE TITLE
Horovod with tf.data.Dataset input pipeline (num_parallel_calls argument)

### ISSUE THREAD

**Issue by msinto93** [horovod/horovod#237]
I am training a model in Tensorflow using 4 V100 GPUs. I am using 'tf.data.Dataset' code (https://www.tensorflow.org/api_docs/python/tf/data/Dataset) for my input pipeline. Within this code I use the dataset.map() function shown below to map `map_func` across the dataset.

```
map(
    map_func,
    num_parallel_calls
)
```
The Tensorflow documentation suggests to set `num_parallel_calls` to be equal to the number of CPU cores available on the machine. When running standard Tensorflow multi-GPU training, I set this variable to be 40 (as I have 40 CPU cores available). My question is whether or not I should divide this by 4 (the number of processes) when running using the Horovod code, as Horovod appears to be running the code in each process separately (i.e. will create 4 input pipelines seperately each using `num_parallel_calls ` cores, instead of just the 1 in standard Tensorflow multi-GPU code).

**Comment by alsrgv** [comment]
@msinto93, yes, I would recommend dividing this number by the number of GPUs.  You can use `hvd.local_size()` to make it more generic so you could move between 4-GPU and 8-GPU machines.
