### ISSUE TITLE
How to run horovod in multiple servers with same IP and  with different ports

### ISSUE THREAD

**Issue by samitshiv** [horovod/horovod#2377]
Environment:

Framework: (TensorFlow, Keras, PyTorch, MXNet)
TensorFlow
Framework version:
2.3
Horovod version:
0.20
MPI version:
mpiexec (OpenRTE) 4.0.0
CUDA version:
10.2
NCCL version:
2.7.8
Python version:
3.7.5
OS and version:

Checklist:

Did you search issues to find if somebody asked this question before?
If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?

Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

I have two server machines A and B on the same IP address, but different ports. I pull the docker file from horovod/horovod and run it. I am successfully able to run the 
`horovodrun -np 2 -H localhost:2 python tensorflow2_keras_mnist.py `successfully on each of servers individually. However when I tried  to  modify the following command  `horovodrun -np 4 -H host1:2,host2:2 -p 12345 python keras_mnist_advanced.py` to 
`horovodrun -np 4 -H 'host1 -p 22':2,'host2 -p 9922':2 -p 12345 python tensorflow2_keras_mnist.py`, it does not seem to recognize the ports specified in the command.

Below is the error that i am coming across:--

Traceback (most recent call last):
 ```
 File "/usr/local/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 723, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 713, in _run
    return _run_static(args)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/launch.py", line 529, in _run_static
    all_host_names, _ = hosts.parse_hosts_and_slots(args.hosts)
  File "/usr/local/lib/python3.7/dist-packages/horovod/runner/common/util/hosts.py", line 79, in parse_hosts_and_slots
    raise ValueError('Invalid host input, please make sure it has '
ValueError: Invalid host input, please make sure it has format as : worker-0:2,worker-1:2.
```

**Comment by tgaddair** [comment]
Hey @samitshiv, you should be able to configure custom hostnames / ports in your [~/.ssh/config](https://linuxize.com/post/using-the-ssh-config-file/) file for each container.

**Comment by Qiuzhuang** [comment]
> Hey @samitshiv, you should be able to configure custom hostnames / ports in your [~/.ssh/config](https://linuxize.com/post/using-the-ssh-config-file/) file for each container.

Can we put this custom hostnames solution into doc (https://github.com/horovod/horovod/blob/master/docs/docker.rst) since I think a lot of  distributed DL training would be container based. 

Thanks!

**Comment by tgaddair** [comment]
Good suggestion @Qiuzhuang.  Let me know what you think of the changes in #2393.  Does that clarify the usage?
