### ISSUE TITLE
Collectives performance

### ISSUE THREAD

**Issue by bureddy** [horovod/horovod#2379]
**Environment:**
Framework: TensorFlow-CPU
Framework version: 2.3.1
Horovod version: 0.20.3
MPI version: OpenMPI 4.0.4rc3
CUDA version: N/A
NCCL version: N/A
Python version: 3.6.9
Spark / PySpark version:
OS and version: Ubuntu 18.04
GCC version:
CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

I'm seeing Collective performance is significantly lower with TF-CPU/HOROVOD compared to native MPI performance with OSU microbenchmarks. In this specific case, it is a simple 5MB all to all .

the below results are with 1 process per node, process bind to CPU socket, 8 nodes, message size:5MB.
MPI : ~ 3000 us
TF/HOROVOD : ~30000 us

I have put the timers inside MPI library around the MPI_Alltoallv to get accurate timings in both cases.
It seems the Issue looks like related to the noise coming from existing of many threads in TF.
is this expected behavior? is there any tining will improve the collective performance?

**Comment by tgaddair** [comment]
Hey @bureddy, do you have a Horovod timeline file you can share?

@romerojosh do you have any experience with all-to-all performance over MPI?
