### ISSUE TITLE
Output is annoying

### ISSUE THREAD

**Issue by wangxianliang** [horovod/horovod#2382]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version: 2.0
3. Horovod version: up-to-date
4. MPI version:
5. CUDA version: 10.1
6. NCCL version: 2.4
7. Python version: 3.8
8. OS and version: ubuntu 18.04
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Is it possible to remove the leading timestamp in the output?
**Mon Oct 19 20:44:09 2020[0]<stderr>**:I1019 20:44:09.594008 139669443786560 hvd_controller.py:30] Step: 1400/329817, steps_per_second: 4.89, {train_loss: 50.83835, lr: 0.00246, accuracy: 0.00000}

I tried set environment variable HOROVOD_LOG_HIDE_TIME="1", but have no effect.
Thanks.

**Comment by tgaddair** [comment]
Hey @wangxianliang, how are you running Horovod?  With `horovodrun`, you should be able to specify `--log-hide-timestamp`.

**Comment by wangxianliang** [comment]
> Hey @wangxianliang, how are you running Horovod? With `horovodrun`, you should be able to specify `--log-hide-timestamp`.
Yes I specify the flags, yet it still appears.

horovodrun -np 4 -H localhost:4 --log-hide-timestamp python ${CODE_PATH}/train_recognition_hvd.py ...

**Comment by tgaddair** [comment]
Thanks for clarifying, let me see if I can reproduce.

**Comment by tgaddair** [comment]
Hey @wangxianliang, can you try #2388 and let me know if it addresses the issue?

**Comment by wangxianliang** [comment]
The PR does address the issue, thanks a lot.
