### ISSUE TITLE
Failed to load the native TensorFlow runtime

### ISSUE THREAD

**Issue by Queequeg92** [horovod/horovod#239]
I'm trying to install horovod with tf 1.6, cuda 9.0, python3.6, ubuntu 16.04. The tensorflow runtime can be loaded normally from terminal. But when I install horovod, it always reports the following error:
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.

Can anyone help me?

**Comment by alsrgv** [comment]
@Queequeg92, are you installing Horovod with `sudo`?  If you do, you may need to put `sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH HOROVOD_GPU_ALLREDUCE=NCCL [other flags] pip install horovod`

**Comment by Queequeg92** [comment]
Adding LD_LIBRARY_PATH=$LD_LIBRARY_PATH helps. Thank you very much! I think you should update     your docs here https://github.com/uber/horovod/blob/master/docs/gpus.md. There is no LD_LIBRARY_PATH=$LD_LIBRARY_PATH in the suggested command.

**Comment by alsrgv** [comment]
Good suggestion.  Seems more suited for the [Troubleshooting](https://github.com/uber/horovod/blob/master/docs/troubleshooting.md) section though.
