### ISSUE TITLE
Alltoall takes a long time to negotiate for wide&deep model.

### ISSUE THREAD

**Issue by kelvinzou** [horovod/horovod#2391]
**Environment:**
1. Framework:  Tensorflow(TensorFlow, Keras, PyTorch, MXNet)
2. Framework version: 2.3.1
3. Horovod version: latest
4. MPI version: 4.2

I am using CPU version for the Horovod all2all training a wide and deep model with both allreduce for dense and all2allv for the spase, and I observed this issue during the  timeline where a lot of time is wasted on negotiate_alltoall, not sure what  does this mean and can this be improved? The whole model took less than 20 ms per epoch but the all2all itself took about 20+ ms due to this.

Please see attached image.
![image](https://user-images.githubusercontent.com/5438895/96790014-f6263800-13aa-11eb-8d36-edd8bde084f7.png)

**Comment by tgaddair** [comment]
Hey @kelvinzou, long negotiation periods usually mean that the different workers are not perfectly in sync with one another.  For example, it could occur if one worker is 20ms ahead of the other worker, leading to a 20ms "negotiation" period during which the faster worker is waiting for the other the catch up.

I am not aware of anything specific to all-to-all that would increase the negotiation time, but cc @romerojosh who implemented all-to-all in case he is aware of anything unique.

**Comment by romerojosh** [comment]
There shouldn't be anything unique about the negotiation for all-to-all vs the other collective types. @kelvinzou, have you tried reducing the cycle time (via the `--cycle-time-ms` to `horovodrun` or `HOROVOD_CYCLE_TIME` environment variable) to see if it reduces the negotiation time?  The default value of this cycle time is 5 ms which is probably much to large for your model if it takes 20 ms.

**Comment by kelvinzou** [comment]
Wow, romerojosh, your trick works! Now I can almost squeeze the NEGOTIATE_ALLTOALL time to somewhere 1~2 ms.

Now I got some issue with NEGOTIATE_ALLREDUCE, any idea which flag to tune for this part?

Also, is it possible to run allreduce and alltoall in parallel time during training?

Thank you a bunch!
