### ISSUE TITLE
Debugging with the VS Code.

### ISSUE THREAD

**Issue by sschangi** [horovod/horovod#2392]
I am just wondering how we can debug a code which uses Horovod to run, with the VS Code and by putting breakpoints? Is that possible at all?

**Comment by aavbsouza** [comment]
The use of MPI complicates the debugging procedure. See for instance these instructions to debug MPI applications that uses the OpenMPI library.
https://www.open-mpi.org/faq/?category=debugging

Depending of what are you intending to debug you can attach a debugger to only one MPI rank that is already running.

**Comment by HongLouyemeng** [comment]
> The use of MPI complicates the debugging procedure. See for instance these instructions to debug MPI applications that uses the OpenMPI library. https://www.open-mpi.org/faq/?category=debugging
> 
> Depending of what are you intending to debug you can attach a debugger to only one MPI rank that is already running.

I have the same questionQAQ , [distirbuted debug](https://github.com/pytorch/pytorch/issues/115476)
