### ISSUE TITLE
Horovod Allreduce on GPU or CPU?

### ISSUE THREAD

**Issue by vibhatha** [horovod/horovod#2400]
**Horovod AllReduce**

I am new to Horovod allreduce. When the models of PyTorch or Tensorflow runs on GPU, how does the Horovod Allreduce work?

Does it take tensors from device to host and do MPI allreduce and push back or does it happen in the device itself?

If it happens in the device itself, does it use NCCL AllReduce? 

Thank You,
Vibhatha.

**Comment by tgaddair** [comment]
Hey @vibhatha, if the models are on GPU, and Horovod has been built with NCCL support, then we will use NCCL to perform the allreduce.  Only if NCCL is unavailable will we fall-back to using MPI/Gloo, which will copy the buffer into host memory to perform the allreduce.

Let me know if you have additional questions, happy to help.

**Comment by vibhatha** [comment]
@tgaddair 
Is it possible to use Horovod distributed with an existing MPI application, given that data preprocessing is an MPI4PY. And Horovod is doing distributed training, using MPI or NCCL.
