### ISSUE TITLE
How  does response_cache_ guarantee same tensor name to bit mapping order across all ranks 

### ISSUE THREAD

**Issue by whatdhack** [horovod/horovod#2406]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.3
3. Horovod version: 19.5
4. MPI version: 
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7
8. OS and version: 
9. GCC version: 7,5

**Your question:**
Looks like response_cache_ is the  look up used by all ranks to map an incoming vector to a bit (in bitvector_).  This respons_cache_ is filled in the order tensors are sent from the  DL framework (TF in this case)  to a queue read by Horovod.   This order may not be same in all ranks.  How does Horovod  make sure the mapping is same in all ranks, else  collective based on bitvector_  may not be correct.

**Comment by tgaddair** [comment]
Hey @whatdhack, if you look at the `tensor_name_to_bit_` mapping in [response_cache.cc](https://github.com/collinabidi/horovod/blob/master/horovod/common/response_cache.cc), you'll notice that this mapping is based off of the tensor names from the `Response` objects.  The Responses come from the coordinator (rank 0) and are sent to the workers in a defined order.  So the mappings are guaranteed to be consistent across the workers.  Once we have this mapping, we can use the tensor name n the `Request` object to update a bit, but not change the name to bit mapping.

**Comment by whatdhack** [comment]
@tgaddair, thanks .  Would it be possible to point to the code that does the sending to the workers ?

**Comment by tgaddair** [comment]
Sure, most of this logic will be in the Controller [here](https://github.com/collinabidi/horovod/blob/master/horovod/common/controller.cc#L62).

**Comment by whatdhack** [comment]
@tgaddair,  thanks.  The controller code is certainly non-trivial. Is it a broadcast collective call that  goes to the  workers or something else is used ?

**Comment by tgaddair** [comment]
Yes, that's correct.  It's implementation-specific (MPI or Gloo), but here's an example of the MPI implementation: https://github.com/horovod/horovod/blob/master/horovod/common/mpi/mpi_controller.cc#L153

**Comment by whatdhack** [comment]
@tgaddair , thanks again.  Looks like SendFinalTensors is called once during NEGOTIATE_BROADCAST phase, then once more till the first mini-batch  iteration, and then repeatedly during  first mini-batch iteration.  Rank 0 also runs MPI_Gather() in RecvReadyTensors repeatedly exactly same number of times.  It  will be great to have an overview of this initial  hand-shake algorithm  ( e.g. a call flow diagram or  psuedo code) .  If it it based on  any publication, please point  to that.   

One of the reasons for looking at it is  because NEGOTIATE_ALLREDUCE seems to be the long pole during back-prop.  One of the  hypotheses  is that  the imbalance is caused by TF's dynamic ordering of tensors that effect Horovod adversely and hence the NEGOTIATE_ALLREDUCE phase gets dialated.   But, from what you are pointing  to in SendFinalTensors and RecvReadyTensors, the ordering of tensors seems to fixed at the beginning, hence should not be a concern.

**Comment by tgaddair** [comment]
Hey @whatdhack, the bitvector approach was introduced in the paper [Exascale Deep Learning for Scientific Inverse Problems](https://arxiv.org/pdf/1909.11150.pdf).  In it, they also discuss the grouped allreduce technique to address long negotiation times which is being introduced in #1130.

TensorFlow's async ops is one culprit for long negotiation times, but there are other possibilities like some workers lagging behind the others.

**Comment by whatdhack** [comment]
@tgaddair , thanks for  pointing to the paper.   It is useful  for high level  understanding.  The paper does not really go into the details of how the response_cache is filled up, if and how are start and finish of each minibatch represented,  etc.    Looks  like there is an implicit assumption also that every tensor is reduced  once and only once during a minibatch and processing can not  proceed to the next minibatch until  the  current one is finished.    I do not recall seeing the  the grouping feature  in code,  has it been released  ?  

Wonder if any of the features mentioned in this paper,  [Alleviating Load Imbalance in Data Processing
for Large-Scale Deep Learning](http://synergy.cs.vt.edu/pubs/papers/pumma-alleviating-learning-ccgrid2020.pdf), is in the works also ?

**Comment by tgaddair** [comment]
Hey @whatdhack, I had not seen that paper. I will take a look, thanks!

The Grouped Allreduce has not landed yet, as the API is still being iterated upon.  @romerojosh may be able to provide more details on that PR as well as the response cache.

**Comment by whatdhack** [comment]
@tgaddair , thanks .  @romerojosh , how are you doing ?  Wondering   if you have any words on when Grouped Allreduce goes live. Also, would  be great to have a flow-diagram/pseudocode on how the response_cache_ gets populated the same way across all ranks,  how are each mini-batch demarcated,  is it possible for 2  consecutive mini-batches to be active at the same time ?

**Comment by whatdhack** [comment]
@tgaddair ,  any thoughts of  the paper ?  @romerojosh ,  any comments ?
