### ISSUE TITLE
Two Different datasets has to run on two different machines and use respective GPUs of those machines only

### ISSUE THREAD

**Issue by samitshiv** [horovod/horovod#2411]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Hello,
I have two different datasets on two different machines. My aim is to run train those datasets on distributed platform using same model. Machine one has to use it's own GPUs only while training dataset which is on that machine. Machine two has to use it's own GPUs only while training dataset which is on that machine. Both machines has to use same model for training. For data privacy, machine one GPUs should not use other dataset which is there on machine two. Machine two GPUs should not have to use other dataset which is there on machine one.
I am using Horovod. what should I have to make changes in the code to make it run. My code as below
`import pandas as pd
import os
import fnmatch
from netCDF4 import Dataset,MFDataset
import numpy as np
import datetime
import sys
import tensorflow as tf
import horovod.keras as hvd
hvd.init()
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')

print('number of hvd.size ', hvd.size())

import os 
    
if hvd.rank()==0:
    
    dirpath="/PBLH_Data/Ceilometer/U_CATONSVILLE_CHM_20161204_20200910"
 
    path, dirs, files = next(os.walk(dirpath))
    file_count = len(files)
    print("file_count : ",file_count)
    
    for filename in files:
        singleFilepath=dirpath+'/'+filename
        u = Dataset(singleFilepath,'r')
 
beta_raw = u.variables['beta_raw'][:]
beta_raw = pd.DataFrame(beta_raw)
beta_raw = beta_raw.select_dtypes(include = ['int32', 'int64', 'float32', 'float64'])

pbl=u.variables['pbl'][:]
pblDF=pd.DataFrame(pbl, columns = ['first', 'second', 'third'])

if hvd.rank()==1:
    
    dirpath="/PBLH_Data/Ceilometer/U_FAIRHILL_STAT_20161210_20200520"
 
    path, dirs, files = next(os.walk(dirpath))
    file_count = len(files)
    print("file_count : ",file_count)
    
    for filename in files:
        singleFilepath=dirpath+'/'+filename
        u = Dataset(singleFilepath,'r')
 
beta_raw = u.variables['beta_raw'][:]
beta_raw = pd.DataFrame(beta_raw)
beta_raw = beta_raw.select_dtypes(include = ['int32', 'int64', 'float32', 'float64'])

pbl=u.variables['pbl'][:]
pblDF=pd.DataFrame(pbl, columns = ['first', 'second', 'third'])

learning_rate=0.0001
epochs = 100

inputs = {key: tf.keras.layers.Input(shape=(), name=str(key)) for key in beta_raw.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model= tf.keras.Model(inputs=inputs, outputs=output)

opt = tf.keras.optimizers.Adadelta(1.0 * hvd.size())

opt = hvd.DistributedOptimizer(opt)

model.compile(loss='mean_squared_error',
                    optimizer=opt,
                    experimental_run_tf_function=False)

callbacks = [
    
    hvd.callbacks.BroadcastGlobalVariablesCallback(0),

    hvd.callbacks.MetricAverageCallback(),

    
]

if hvd.rank() == 0:
    callbacks.append(tf.keras.callbacks.ModelCheckpoint('./checkpoint-{epoch}.h5'))
  
    
  
verbose = 1 if hvd.rank() == 0 else 0

dict_slices = tf.data.Dataset.from_tensor_slices((beta_raw.to_dict('list'), pblDF['first'].values)).batch(8)

model.fit(dict_slices, steps_per_epoch=50 // hvd.size(), callbacks=callbacks, epochs=15, verbose=verbose)
`

**Comment by tgaddair** [comment]
Hey @samitshiv, based on your description, as long as the datasets are formatted the same, you should be able to just give them the same name and everything should work correctly.  If for whatever reason they need to be handled separately, you can handle each dataset differently at runtime:

```
if hvd.rank() == 0:
    # machine / GPU 0
    dataset = read_dataset_0()
else:
    # machine / GPU 1
    dataset = read_dataset_1()
```

This assumes you have one process / GPU per machine, but it's pretty simple to extend it to multiple GPUs per host.

**Comment by samitshiv** [comment]
Basically, my first dataset has total 514 .nc files and second dataset has total 499 .nc  files.

When I am using second dataset then it throws me error as below :---
Thu Nov  5 02:25:22 2020[2]<stderr>:Traceback (most recent call last):
Thu Nov  5 02:25:22 2020[2]<stderr>:  File "ClaudeNew.py", line 94, in <module>
Thu Nov  5 02:25:22 2020[2]<stderr>:    umbc = netCDF4.MFDataset(a)
Thu Nov  5 02:25:22 2020[2]<stderr>:  File "netCDF4/_netCDF4.pyx", line 6281, in netCDF4._netCDF4.MFDataset.__init__
Thu Nov  5 02:25:22 2020[2]<stderr>:OSError: master dataset /nfs/PBLH_Data/Ceilometer/Fairhill-Test/fairhillCL020211.l2.20200915.0710.nc does not have a aggregation dimension
Thu Nov  5 02:25:22 2020[0]<stderr>:2020-11-05 02:25:22.573074: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA


`import pandas as pd
import os
import fnmatch
import netCDF4
from netCDF4 import Dataset,MFDataset
import numpy as np
import datetime
import sys
import tensorflow as tf
import horovod.keras as hvd
import xarray as xr
import socket
hvd.init()
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
i=0
a = []
bc = None
if hvd.rank()==0 or hvd.rank()==1:
    dirpath="/PBLH_Data/Ceilometer/Test"
    path, dirs, files = next(os.walk(dirpath))
    file_count = len(files)
    print("file_count : ",file_count)
    
    for filename in files:
        singleFilepath=dirpath+'/'+filename
        a.append(singleFilepath)
    print("len(a) : ",len(a))
    bc = netCDF4.MFDataset(a)
    print(bc)

if hvd.rank()==2 or hvd.rank()==3:
    dirpath="/nfs/PBLH_Data/Ceilometer/Fairhill-Test"
    path, dirs, files = next(os.walk(dirpath))
    file_count = len(files)
    print("file_count : ",file_count)
    
    for filename in files:
        singleFilepath=dirpath+'/'+filename
        a.append(singleFilepath)
    print("len(a) : ",len(a))
    bc = netCDF4.MFDataset(a)

beta_raw=bc.variables['beta_raw'][:]
beta_raw = pd.DataFrame(beta_raw)

print("HEAD : ",beta_raw.head())

beta_raw = beta_raw.select_dtypes(include = ['int32', 'int64', 'float32', 'float64'])
pbl=bc.variables['pbl'][:]

pblDF=pd.DataFrame(pbl, columns = ['first', 'second', 'third'])
print("HEAD pblDF : ",pblDF.head())

learning_rate=0.0001
epochs = 100

inputs = {key: tf.keras.layers.Input(shape=(), name=str(key)) for key in beta_raw.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model= tf.keras.Model(inputs=inputs, outputs=output)
opt = tf.keras.optimizers.Adadelta(1.0 * hvd.size())

opt = hvd.DistributedOptimizer(opt)


model.compile(loss='mean_squared_error',
                    optimizer=opt,
                    experimental_run_tf_function=False)

callbacks = [
    
    hvd.callbacks.BroadcastGlobalVariablesCallback(0),

   
    hvd.callbacks.MetricAverageCallback(),
]
if hvd.rank() == 0:
    callbacks.append(tf.keras.callbacks.ModelCheckpoint('./checkpoint-{epoch}.h5'))
verbose = 1 if hvd.rank() == 0 else 0
dict_slices = tf.data.Dataset.from_tensor_slices((beta_raw.to_dict('list'), pblDF['first'].values)).batch(8)
model.fit(dict_slices, steps_per_epoch=50 // hvd.size(), callbacks=callbacks, epochs=15, verbose=verbose)
`

**Comment by tgaddair** [comment]
Hey @samitshiv, it looks like this error is not coming from Horovod.  Are you certain this code works without Horovod?

**Comment by samitshiv** [comment]
@tgaddair when I am using 
if hvd.rank()==2 or hvd.rank()==3:
dirpath="/nfs/PBLH_Data/Ceilometer/Test"

then it works fine. Here I am just accessing Test dataset from another server using nfs (network file system). Basically it's same dataset like first one. Then it works fine.
When I am using same dataset separately copied on server 2 with less number of files (382) 
if hvd.rank()==2 or hvd.rank()==3:
    dirpath="/home/samit1/pblh/Test"

then it will throw error too as below :--

Thu Nov  5 02:55:24 2020[2]<stdout>:number of hvd.size  3
Thu Nov  5 02:55:24 2020[2]<stdout>:hvd.rank() :   2
Thu Nov  5 02:55:24 2020[2]<stderr>:2020-11-05 02:55:24.690834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
Thu Nov  5 02:55:24 2020[2]<stdout>:file_count :  382
Thu Nov  5 02:55:24 2020[2]<stdout>:len(b) :  382
Thu Nov  5 02:55:25 2020[2]<stderr>:Traceback (most recent call last):
Thu Nov  5 02:55:25 2020[2]<stderr>:  File "ClaudeNew.py", line 94, in <module>
Thu Nov  5 02:55:25 2020[2]<stderr>:    umbc = MFDataset(a)
Thu Nov  5 02:55:25 2020[2]<stderr>:  File "netCDF4/_netCDF4.pyx", line 6317, in netCDF4._netCDF4.MFDataset.__init__
Thu Nov  5 02:55:25 2020[2]<stderr>:  File "netCDF4/_netCDF4.pyx", line 2358, in netCDF4._netCDF4.Dataset.__init__
Thu Nov  5 02:55:25 2020[2]<stderr>:  File "netCDF4/_netCDF4.pyx", line 1926, in netCDF4._netCDF4._ensure_nc_success
Thu Nov  5 02:55:25 2020[2]<stderr>:OSError: [Errno -51] NetCDF: Unknown file format: b'/home/samit1/pblh/Test/umbcCHM160112.l1.20200909.1235.nc'

**Comment by samitshiv** [comment]
@tgaddair you are correct. Problem is not with Horovod but with different variables of the two different datasets.

**Comment by tgaddair** [comment]
Great to here @samitshiv!  I'll close this issue for now, then.
