### ISSUE TITLE
hvd.size() is always 1 when using Docker

### ISSUE THREAD

**Issue by zhanqiuzhang** [horovod/horovod#2417]
Docker Tag: 0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1 (The latest one)
GPU: 2080ti * 8

The server has 8 GPUs. However, the result of hvd.size() is always 1. Is there any bug when building the docker image?

**Comment by tgaddair** [comment]
Hey @zhanqiuzhang, can you share the command you're using to run Horovod within the Docker container?

**Comment by zhanqiuzhang** [comment]
Hi @tgaddair, thanks for your reply.

I run Horovod using the following command
`docker run --gpus all -v /etc/localtime:/etc/localtime:ro --volume ~/codes/:/root/codes/ -it --name spell horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1  /bin/bash`

**Comment by tgaddair** [comment]
Hey @zhanqiuzhang, this is to launch the Bash shell into the container, right?  What is the `horovodrun` command you run once inside the container?

**Comment by zhanqiuzhang** [comment]
@tgaddair I ran Horovod with Tensorflow.

```
import horovod.tensorflow as hvd

hvd.init()
print(hvd.size())
print(hvd.local_rank())
```

The outputs of the above script are always 1 and 0.

**Comment by tgaddair** [comment]
@zhanqiuzhang, what I'm asking is, how are you running this script?  Is it just `python train.py`?

**Comment by zhanqiuzhang** [comment]
@tgaddair Yes. I use `python train.py` following the instruction of another project, which uses Horovod.

**Comment by tgaddair** [comment]
@zhanqiuzhang, can you try running `horovodrun -np 8 python train.py` instead and share the result?

**Comment by zhanqiuzhang** [comment]
@tgaddair It works! Now hvd.size() is 8. Thanks a lot!

**Comment by tgaddair** [comment]
@zhanqiuzhang no problem!  Glad you got it working.
