### ISSUE TITLE
how to split dataset in keras

### ISSUE THREAD

**Issue by stevenheleah** [horovod/horovod#2422]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

hello, i know we can split dataset by distributedsampler in pytorch. I wonder how to split dataset in keras since each worker should has different train data？Look forward to your soonest reply，thanks

**Comment by tgaddair** [comment]
Hey @stevenheleah, one common approach would be to create a [tf.data.Dataset](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) and call `dataset.shard(hvd.size(), hvd.rank())` to split it among the Horovod workers.

If your dataset is in Parquet format, I would recommend taking a look at [Petastorm](https://github.com/uber/petastorm/tree/master/petastorm), which further simplifies much of this process.

**Comment by stevenheleah** [comment]
Thank you very much for your reply.The problem is solved.
