### ISSUE TITLE
program block when train horovod keras model

### ISSUE THREAD

**Issue by wwwa** [horovod/horovod#2432]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version: tensorflow==2.3.0
3. Horovod version: 0.20.0
4. MPI version: 4.0.5
5. CUDA version: no
6. NCCL version: no
7. Python version: 3.6.4
8. OS and version: Linux version 3.10.0-1127.10.1.el7.x86_64
9. GCC version: gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)

spark2-submit --conf "spark.rpc.message.maxSize=512" --driver-memory 3g --executor-cores 2 --num-executors 1 di/model/ke.py

Program blocking in "horovod/runner/common/util/safe_shell_exec.py" 
line : "os.read(r.fileno(), 1)

Here's the code:

 def kill_executor_children_if_parent_dies():
        # This read blocks until the pipe is closed on the other side
        # due to parent process termination (for any reason, including -9).
        os.read(r.fileno(), 1)
        terminate_executor_shell_and_children(executor_shell.pid)

console output:

DEBUG:/usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py:mpirun --allow-run-as-root --tag-output -np 2 -H node101-68eabd6d08fc5bfd3c659e8a2dbfc390:2 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_include ens192,lo -x NCCL_SOCKET_IFNAME=ens192,lo  -x AUTOJUMP_ERROR_PATH -x AUTOJUMP_SOURCED -x CLASSPATH -x HADOOP_COMMON_HOME -x HADOOP_CONF_DIR -x HADOOP_HOME -x HISTCONTROL -x HISTSIZE -x HOME -x HOSTNAME -x INFOPATH -x JAVA_HOME -x LANG -x LD_LIBRARY_PATH -x LESS -x LESSOPEN -x LIBHDFS_OPTS -x LIB_HDFS -x LIB_JVM -x LOGNAME -x LOG_HOST -x LSCOLORS -x LS_COLORS -x MAIL -x MANPATH -x MASTER -x NLSPATH -x PAGER -x PATH -x PCP_DIR -x PERL5LIB -x PKG_CONFIG_PATH -x PWD -x PYLIB -x PYSPARK_ARCHIVES_PATH -x PYSPARK_DRIVER_PYTHON -x PYSPARK_GATEWAY_PORT -x PYSPARK_GATEWAY_SECRET -x PYSPARK_PYTHON -x PYTHONHASHSEED -x PYTHONPATH -x PYTHONUNBUFFERED -x PYTHON_ROOT -x QUEUE -x SELF -x SHELL -x SHLVL -x SPARK_CONF_DIR -x SPARK_DIST_CLASSPATH -x SPARK_ENV_LOADED -x SPARK_EXTRA_LIB_PATH -x SPARK_HOME -x SPARK_KAFKA_VERSION -x SPARK_PYTHON_PATH -x SPARK_SCALA_VERSION -x SSH_CLIENT -x SSH_CONNECTION -x SSH_TTY -x TERM -x TF2_BEHAVIOR -x TMP_PYSPARK_DRIVER_PYTHON -x TMP_PYSPARK_PYTHON -x TMUX -x TMUX_PANE -x USER -x VIRTUALENVWRAPPER_HOOK_DIR -x VIRTUALENVWRAPPER_PROJECT_FILENAME -x VIRTUALENVWRAPPER_SCRIPT -x VIRTUALENVWRAPPER_WORKON_CD -x WORKON_HOME -x XDG_RUNTIME_DIR -x XDG_SESSION_ID -x XFILESEARCHPATH -x ZSH -x lib  -x NCCL_DEBUG=INFO -mca plm_rsh_agent "/usr/local/python3.6.4/bin/python3 -m horovod.spark.driver.mpirun_rsh gASVYAAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTcJRhpRhjAZlbnMxOTKUXZSMDjE5Mi4xNjguMjEuMTAxlE3CUYaUYYwHZG9ja2VyMJRdlIwLMTcyLjE3LjQyLjGUTcJRhpRhdS4= gASVlgIAAAAAAACMI2hvcm92b2QucnVubmVyLmNvbW1vbi51dGlsLnNldHRpbmdzlIwIU2V0dGluZ3OUk5QpgZR9lCiMCG51bV9wcm9jlEsCjAd2ZXJib3NllEsBjAhzc2hfcG9ydJROjBFzc2hfaWRlbnRpdHlfZmlsZZROjA5leHRyYV9tcGlfYXJnc5ROjAh0Y3BfZmxhZ5ROjAxiaW5kaW5nX2FyZ3OUTowDa2V5lE6MDXN0YXJ0X3RpbWVvdXSUjCJob3Jvdm9kLnJ1bm5lci5jb21tb24udXRpbC50aW1lb3V0lIwHVGltZW91dJSTlCmBlH2UKIwLX3RpbWVvdXRfYXSUR0HX6pfRsSLpjAhfbWVzc2FnZZRYDgEAAFRpbWVkIG91dCB3YWl0aW5nIGZvciB7YWN0aXZpdHl9LiBQbGVhc2UgY2hlY2sgdGhhdCB5b3UgaGF2ZSBlbm91Z2ggcmVzb3VyY2VzIHRvIHJ1biBhbGwgSG9yb3ZvZCBwcm9jZXNzZXMuIEVhY2ggSG9yb3ZvZCBwcm9jZXNzIHJ1bnMgaW4gYSBTcGFyayB0YXNrLiBZb3UgbWF5IG5lZWQgdG8gaW5jcmVhc2UgdGhlIHN0YXJ0X3RpbWVvdXQgcGFyYW1ldGVyIHRvIGEgbGFyZ2VyIHZhbHVlIGlmIHlvdXIgU3BhcmsgcmVzb3VyY2VzIGFyZSBhbGxvY2F0ZWQgb24tZGVtYW5kLpR1YowPb3V0cHV0X2ZpbGVuYW1llE6MDXJ1bl9mdW5jX21vZGWUiIwEbmljc5ROjAdlbGFzdGljlImMBWhvc3RzlIwqbm9kZTEwMS02OGVhYmQ2ZDA4ZmM1YmZkM2M2NTllOGEyZGJmYzM5MDoylHViLg==" /usr/local/python3.6.4/bin/python3 -m horovod.spark.task.mpirun_exec_fn gASVYAAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTcJRhpRhjAZlbnMxOTKUXZSMDjE5Mi4xNjguMjEuMTAxlE3CUYaUYYwHZG9ja2VyMJRdlIwLMTcyLjE3LjQyLjGUTcJRhpRhdS4= gASVHwcAAAAAAACMI2hvcm92b2QucnVubmVyLmNvbW1vbi51dGlsLnNldHRpbmdzlIwIU2V0dGluZ3OUk5QpgZR9lCiMCG51bV9wcm9jlEsCjAd2ZXJib3NllEsBjAhzc2hfcG9ydJROjBFzc2hfaWRlbnRpdHlfZmlsZZROjA5leHRyYV9tcGlfYXJnc5RYhAQAACAteCBOQ0NMX0RFQlVHPUlORk8gLW1jYSBwbG1fcnNoX2FnZW50ICIvdXNyL2xvY2FsL3B5dGhvbjMuNi40L2Jpbi9weXRob24zIC1tIGhvcm92b2Quc3BhcmsuZHJpdmVyLm1waXJ1bl9yc2ggZ0FTVllBQUFBQUFBQUFCOWxDaU1BbXh2bEYyVWpBa3hNamN1TUM0d0xqR1VUY0pSaHBSaGpBWmxibk14T1RLVVhaU01EakU1TWk0eE5qZ3VNakV1TVRBeGxFM0NVWWFVWVl3SFpHOWphMlZ5TUpSZGxJd0xNVGN5TGpFM0xqUXlMakdVVGNKUmhwUmhkUzQ9IGdBU1ZsZ0lBQUFBQUFBQ01JMmh2Y205MmIyUXVjblZ1Ym1WeUxtTnZiVzF2Ymk1MWRHbHNMbk5sZEhScGJtZHpsSXdJVTJWMGRHbHVaM09VazVRcGdaUjlsQ2lNQ0c1MWJWOXdjbTlqbEVzQ2pBZDJaWEppYjNObGxFc0JqQWh6YzJoZmNHOXlkSlJPakJGemMyaGZhV1JsYm5ScGRIbGZabWxzWlpST2pBNWxlSFJ5WVY5dGNHbGZZWEpuYzVST2pBaDBZM0JmWm14aFo1Uk9qQXhpYVc1a2FXNW5YMkZ5WjNPVVRvd0RhMlY1bEU2TURYTjBZWEowWDNScGJXVnZkWFNVakNKb2IzSnZkbTlrTG5KMWJtNWxjaTVqYjIxdGIyNHVkWFJwYkM1MGFXMWxiM1YwbEl3SFZHbHRaVzkxZEpTVGxDbUJsSDJVS0l3TFgzUnBiV1Z2ZFhSZllYU1VSMEhYNnBmUnNTTHBqQWhmYldWemMyRm5aWlJZRGdFQUFGUnBiV1ZrSUc5MWRDQjNZV2wwYVc1bklHWnZjaUI3WVdOMGFYWnBkSGw5TGlCUWJHVmhjMlVnWTJobFkyc2dkR2hoZENCNWIzVWdhR0YyWlNCbGJtOTFaMmdnY21WemIzVnlZMlZ6SUhSdklISjFiaUJoYkd3Z1NHOXliM1p2WkNCd2NtOWpaWE56WlhNdUlFVmhZMmdnU0c5eWIzWnZaQ0J3Y205alpYTnpJSEoxYm5NZ2FXNGdZU0JUY0dGeWF5QjBZWE5yTGlCWmIzVWdiV0Y1SUc1bFpXUWdkRzhnYVc1amNtVmhjMlVnZEdobElITjBZWEowWDNScGJXVnZkWFFnY0dGeVlXMWxkR1Z5SUhSdklHRWdiR0Z5WjJWeUlIWmhiSFZsSUdsbUlIbHZkWElnVTNCaGNtc2djbVZ6YjNWeVkyVnpJR0Z5WlNCaGJHeHZZMkYwWldRZ2IyNHRaR1Z0WVc1a0xwUjFZb3dQYjNWMGNIVjBYMlpwYkdWdVlXMWxsRTZNRFhKMWJsOW1kVzVqWDIxdlpHV1VpSXdFYm1samM1Uk9qQWRsYkdGemRHbGpsSW1NQldodmMzUnpsSXdxYm05a1pURXdNUzAyT0dWaFltUTJaREE0Wm1NMVltWmtNMk0yTlRsbE9HRXlaR0ptWXpNNU1Eb3lsSFZpTGc9PSKUjAh0Y3BfZmxhZ5ROjAxiaW5kaW5nX2FyZ3OUTowDa2V5lE6MDXN0YXJ0X3RpbWVvdXSUjCJob3Jvdm9kLnJ1bm5lci5jb21tb24udXRpbC50aW1lb3V0lIwHVGltZW91dJSTlCmBlH2UKIwLX3RpbWVvdXRfYXSUR0HX6pfRsSLpjAhfbWVzc2FnZZRYDgEAAFRpbWVkIG91dCB3YWl0aW5nIGZvciB7YWN0aXZpdHl9LiBQbGVhc2UgY2hlY2sgdGhhdCB5b3UgaGF2ZSBlbm91Z2ggcmVzb3VyY2VzIHRvIHJ1biBhbGwgSG9yb3ZvZCBwcm9jZXNzZXMuIEVhY2ggSG9yb3ZvZCBwcm9jZXNzIHJ1bnMgaW4gYSBTcGFyayB0YXNrLiBZb3UgbWF5IG5lZWQgdG8gaW5jcmVhc2UgdGhlIHN0YXJ0X3RpbWVvdXQgcGFyYW1ldGVyIHRvIGEgbGFyZ2VyIHZhbHVlIGlmIHlvdXIgU3BhcmsgcmVzb3VyY2VzIGFyZSBhbGxvY2F0ZWQgb24tZGVtYW5kLpR1YowPb3V0cHV0X2ZpbGVuYW1llE6MDXJ1bl9mdW5jX21vZGWUiIwEbmljc5ROjAdlbGFzdGljlImMBWhvc3RzlIwqbm9kZTEwMS02OGVhYmQ2ZDA4ZmM1YmZkM2M2NTllOGEyZGJmYzM5MDoylHViLg==
2020-11-10 17:27:11,143 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py - execute - 207 : 22
DEBUG:/usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py:22
2020-11-10 17:27:11,150 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py - execute - 223 : 33
DEBUG:/usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py:33
2020-11-10 17:27:11,153 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py - execute - 234 : 44
DEBUG:/usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py:44
2020-11-10 17:27:11,181 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py - kill_executor_children_if_parent_dies - 151 : @@@@@@@@@@
DEBUG:/usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py:@@@@@@@@@@
2020-11-10 17:27:11,182 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py - _exec_middleman - 158 : ('wait', 25907)
DEBUG:/usr/local/python3.6.4/lib/python3.6/site-packages/horovod/runner/common/util/safe_shell_exec.py:('wait', 25907)
2020-11-10 17:27:17,496 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/driver/mpirun_rsh.py - <module> - 41 : mpirun_rsh
2020-11-10 17:27:17,507 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/driver/rsh.py - rsh - 79 : rsh-5
20/11/10 17:27:18 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 11.0 (TID 13) in 7193 ms on node101 (executor 1) (1/2)
20/11/10 17:27:18 INFO scheduler.TaskSetManager: Finished task 1.0 in stage 11.0 (TID 14) in 7252 ms on node101 (executor 1) (2/2)
20/11/10 17:27:18 INFO cluster.YarnScheduler: Removed TaskSet 11.0, whose tasks have all completed, from pool
20/11/10 17:27:18 INFO scheduler.DAGScheduler: ResultStage 11 (collect at /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/runner.py:145) finished in 7.264 s
20/11/10 17:27:18 INFO scheduler.DAGScheduler: Job 11 finished: collect at /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/runner.py:145, took 7.266095 s
/usr/local/python3.6.4/lib/python3.6/socket.py:657: ResourceWarning: unclosed <socket.socket fd=151, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 55654), raddr=('127.0.0.1', 41707)>
  self._sock = None
2020-11-10 17:27:18,101 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/runner.py - run_spark - 146 : [None, None]
DEBUG:/usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/runner.py:[None, None]
2020-11-10 17:27:18,101 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/runner.py - run_spark - 148 : tttttt

**Comment by tgaddair** [comment]
Hey @wwwa, `kill_executor_children_if_parent_dies ` runs in a background thread, which should not affect the main execution of the program.  From the logs, it looks like the return values are getting propagated correctly:

```
2020-11-10 17:27:18,101 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/runner.py - run_spark - 146 : [None, None]
DEBUG:/usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/runner.py:[None, None]
2020-11-10 17:27:18,101 - DEBUG - /usr/local/python3.6.4/lib/python3.6/site-packages/horovod/spark/runner.py - run_spark - 148 : tttttt
```

Can you share the Horovod code you're running?

**Comment by wwwa** [comment]
Thank you very much for your reply.

Here is part of my code:

```python
    def train(self, model_rdd, data_rdd, work_dir, batch_size=128, epochs=1):
        model_row = model_rdd.first()
        model_config = json.loads(model_row.model)
        opt_str = json.loads(model_row.compile)
        model = tf.keras.Sequential.from_config(model_config)

        optimizer = deserialize(opt_str)
        loss = keras.losses.categorical_crossentropy

        # Setup our store for intermediate data
        store = Store.create(work_dir)

        # Train a Horovod Spark Estimator on the DataFrame
        keras_estimator = hvd.KerasEstimator(
            # num_proc=4,
            store=store,
            model=model,
            optimizer=optimizer,
            loss=loss,
            metrics=['accuracy'],
            feature_cols=['features'],
            label_cols=['label_vec'],
            batch_size=batch_size,
            epochs=epochs,
            verbose=1)
        keras_model = keras_estimator.fit(data_rdd).setOutputCols(['label_prob'])

        history = keras_model.getHistory()
        print(history)
```

The program is going to block on this line :
"exit_code = executor_shell.wait()"
in the file
"horovod/runner/common/util/safe_shell_exec.py" 

The command will always be executed in the background:
mpirun --allow-run-as-root --tag-output -np 2 XXXX

I tried the following solution:
https://www.gitmemory.com/issue/horovod/horovod/1222/516063144

> I used gdb to debug and finally find the root cause. It's because in our system there are two openmpi versions (one is 1.xx which is quite old, the other is 4.0.1) co-exist. Even already set the runtime PATH/LD_LIBRARY_PATH, the horovod c library still refer to old libmpi.so. The key-point to note is, when install horovod, environment variable OPAL_PREFIX should be assigned to openmpi home once it install on some custom path. So pip installation command should be
> 
> OPAL_PREFIX=<path to custom openmpi directory> pip install horovod --upgrade --no-cache-dir

But it's still the same problem

**Comment by wwwa** [comment]
Exit code not correct to execute orted order

![image](https://user-images.githubusercontent.com/17785818/98786127-9c101400-2438-11eb-8df1-dad603c8e238.png)

**Comment by wwwa** [comment]
@tgaddair 

horovod/lib/python3.6/site-packages/horovod/spark/task/mpirun_exec_fn.py was not called after mpirun executed

**Comment by iideas18** [comment]
I met the same situation just like you, are you finished this problem?

**Comment by tgaddair** [comment]
Looks like the underlying issue is `horovod.runner.common.util.network.NoValidAddressesFound: Horovod was unable to connect to task service #1 on any of the following addresses: {'ens192': [('192.168.21.50', 8394)]}.`, so seems there is some communication problem between the nodes.  Can you verify that these nodes are reachable on this interface?

**Comment by EnricoMi** [comment]
You are running this on a spark cluster of docker containers? The spark worker nodes need random port access between each other. Can you confirm this is granted?
