### ISSUE TITLE
Unit Test: Ray Colocator test gives flaky resource availability results

### ISSUE THREAD

**Issue by tgaddair** [horovod/horovod#2438]
Starting from nightly build 2020/11/10, the `test_ray.py::test_colocator` has been failing sporadically with the following error:

```
assert resources.get(f"node:{ip_address}", 0) == 1 - 4 * 0.01
assert 1.0 == 0.96
  +1.0
  -0.96
```

See: https://buildkite.com/horovod/horovod/builds/4274#3f5eddde-efbd-4078-861a-8d79205d8478

cc @richardliaw

**Comment by richardliaw** [comment]
this slipped my mind - let me take a look today.

**Comment by EnricoMi** [comment]
This is still enabled and still flaky: https://github.com/horovod/horovod/runs/1659627755

**Comment by richardliaw** [comment]
@EnricoMi thanks for the ping! I've opened a PR to disable in #2628.
