### ISSUE TITLE
How can you setup a Horovod cluster with Docker on Ubuntu?

### ISSUE THREAD

**Issue by steven-mi** [horovod/horovod#2442]
**Environment:**
1. Framework: Tensorflow
2. Framework version: 1.14
3. Horovod version: 0.18.1
4. MPI version: -
5. CUDA version: -
6. NCCL version: -
7. Python version: 3.X
8. OS and version: Ubuntu 18.04
9. GCC version: -

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
Yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?
Yes

**Your question:**
Hi, I am new to Horovod and I wanted to ask if there are any instructions to setup a cluster with docker.

Currently, I tried following the guide in [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst) but it seems to not work for me. I did following:
- created a shared filesystem on `/mnt/share`
- added ssh-key to /mnt/share/ssh
- added the public key in `/mnt/share/ssh` to `authorized_keys` in same folder.
- on main worker: `docker run --gpus all -v /mnt/share/ssh/:/root/.ssh --network=host --name horovod_main -it horovod/horovod:0.18.1-tf1.14.0-torch1.2.0-mxnet1.5.0-py3.6 bash`
- on primary worker: `nvidia-docker run -v /media/nas/horovod/ssh/:/root/.ssh -p --network=host -it --name horovod horovod/horovod:0.18.1-tf1.14.0-torch1.2.0-mxnet1.5.0-py3.6 bash -c "/usr/sbin/sshd -p 12345; sleep infinity"`

After trying to run horovod with:
```
horovodrun -np 4 -H SECONDARY_WORKER_HOSTNAME:4 -p 12345 python tensorflow_keras_mnist.py         
```
I get `Permission denied (publickey,password).`

Are there steps that I am missing?

**Comment by tgaddair** [comment]
Hey @steven-mi, sounds like the key to getting this working is to enable passwordless SSH between the hosts. Assuming you're able to `ssh $SECONDARY_WORKER_HOSTNAME -p 12345` without a password prompt, the rest should work.

**Comment by steven-mi** [comment]
@tgaddair ssh SECONDARY works but ssh with specifying the port fails. Any suggestions on how I can make it work?

**Comment by tgaddair** [comment]
@steven-mi, sounds like the SSHD server is running on a different port.  If running without specifying the port works, can you try just running like this without the port:

```
horovodrun -np 4 -H SECONDARY_WORKER_HOSTNAME:4 python tensorflow_keras_mnist.py  
```

**Comment by steven-mi** [comment]
@tgaddair Okay. I will give it a try tomorrow.

I am wondering though, what the expected outcome is. So on my worker node I have a SSH server on the default port and on port 12345 in my docker container. If I don't provide a port, then I would connect to the default server, which is given by my host system. Is this what I need? I though I need to be able to connect to the docker container on my worker node, which would require me to connect to the server on port 12345

**Comment by tgaddair** [comment]
@steven-mi, when Horovod starts, the driver (localhost) needs to be able to SSH (without password) into all the worker nodes in order to launch the worker processes.  So long as that condition is met, it should work.

**Comment by steven-mi** [comment]
Thanks. I got it to work. I think the documentation should include setting up a ssh config (https://linuxize.com/post/using-the-ssh-config-file/). This makes setting up Horovod very easy with Docker

**Comment by tgaddair** [comment]
Glad you got it working, @steven-ml.  We do have [this](https://github.com/horovod/horovod/blob/master/docs/docker.rst#running-containers-with-different-ports) section which talks about this topic, but let me know if it can be improved to be more clear.

**Comment by steven-mi** [comment]
Ah I didn't see that. I was looking at https://horovod.readthedocs.io/en/stable/docker_include.html when I was setting up Horovod.

Maybe something similar like this https://github.com/horovod/horovod/pull/2454? It would be some kind of instructions that would work out of the box
