### ISSUE TITLE
how to import hvd in multiple python files

### ISSUE THREAD

**Issue by stevenheleah** [horovod/horovod#2445]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

hello，i want to use hvd in multi python files，should i initialize hvd in each python file like 
"import horovod.tensorflow.keras as hvd"
"hvd.init()"? 
Is there any easy approachs? Look forward to your soonest reply，thanks

**Comment by tgaddair** [comment]
Hey @stevenheleah, do you mean multiple Python processes, or just files that are imported within the same process?  So long as you're in the same process, you don't need to call `hvd.init()` a second time.  If you spawn a new process, then yes, you need to call `hvd.init()` again.
