### ISSUE TITLE
how to run keras-resnet50?

### ISSUE THREAD

**Issue by thyeros** [horovod/horovod#245]
I found the script horovod/examples/keras_imagenet_resnet50.py, but not sure what input it requires. Does it need TFRecord or LMDB or raw file? Any help would be appreciated.

**Comment by alsrgv** [comment]
@thyeros, that specific example uses raw JPEG files in a standard structure: `train/<class>/<example>.jpeg` & `validation/<class>/<example>.jpeg`.

**Comment by thyeros** [comment]
Got it, I tried with raw files, but it failed perhaps I have "val"/class instead of "validation". Do you have a recommended command line options to reach 75% in 100 epochs?

**Comment by alsrgv** [comment]
@thyeros, I ran it as easily as `mpirun -np N [... other flags ...] python keras_imagenet_resnet50.py`, with flags based on https://github.com/uber/horovod/blob/master/docs/running.md.
