### ISSUE TITLE
Horovod with PyTorch 1.7.0 and/or TensorFlow 2.4.0 (CUDA 11.0 is required)

### ISSUE THREAD

**Issue by AZadora** [horovod/horovod#2451]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.7.0
3. Horovod version: --
4. MPI version: 4.0.0
5. CUDA version: 11.0
6. NCCL version: 2.8.3
7. Python version: 3.8
8. OS and version: Ubuntu 20.04 LTS
9. GCC version: 7

I would like to use Horovod with the latest PyTorch version 1.7.0 (which supports CUDA 11.0) and/or TensorFlow 2.4.0. Have you tried building and running Horovod with any of these configurations? Do you have Dockerfiles for them?

I need this because I have multiple RTX 3080 cards. What do you think about it?

**Comment by tgaddair** [comment]
Hey @AZadora, thanks for raising this issue.  This week, we're going to be updating the CI and Dockerfiles for CUDA 11.  We can use this issue to track that progress.

**Comment by weihaosky** [comment]
same here. I also need horovod with RTX3080, Pytorch 1.7.0. Thanks!

**Comment by tgaddair** [comment]
Hey @AZadora @weihaosky, to clarify, there should not be any incompatibilities with PyTorch 1.7.0 or CUDA 11.  Let me know if you run into any issues.

**Comment by weihaosky** [comment]
I think there are some problems with RTX3080 (sm_86). But I finally succeed by all kinds of trying and `HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir horovod horovod[pytorch]`. Hope this is helpful.

**Comment by jasstionzyf** [comment]
@tgaddair 
i have installed pytorch 1.7.1  and horovod, though succeed, horovod+pytorch run, but very slow,  as long as i switch pytorch to <=1.6.0,  the program run  normally.
install command :
HOROVOD_WITH_PYTORCH=1  HOROVOD_WITH_TENSORFLOW=1  pip install --no-cache-dir horovod
pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by tgaddair** [comment]
Hey @jasstionzyf, can you run `horovodrun --check-build` and share the results?  It may be that NCCL is not enabled.

**Comment by jasstionzyf** [comment]
> Hey @jasstionzyf, can you run `horovodrun --check-build` and share the results? It may be that NCCL is not enabled.

`
Available Frameworks:
    [X] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo`

i run HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir horovod to enable ncc , 
and still very slow compare with pytorch 1.4.0 without ncc enable
use pytorch 1.4.0 + horovod ,  with or without ncc  enabled both much faster then pytorch 1.7.0+horovod with ncc enabled

**Comment by tgaddair** [comment]
Thanks @jasstionzyf, I'll try running a benchmark today.

What versions of NCCL and CUDA are you using?

**Comment by jasstionzyf** [comment]
@tgaddair   

libnccl-dev:  2.4.8-1+cuda10.1 amd64
libnccl2:  2.4.8-1+cuda10.1 amd64
CUDA Version: 10.1

**Comment by g-karthik** [comment]
@tgaddair somewhat unrelated to this thread, but I am using one of your base [images](https://hub.docker.com/layers/horovod/horovod/0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu/images/sha256-f675e5b16e90935526703acce06b55b78e43b2f53a0a69cafb1db1d064e13bef?context=explore) from Docker Hub, and I see from the layers that it has `libnccl2` and `libnccl-dev` installed. But for the life of me, I am unable to find where NCCL has actually been installed when I try to create a pod on Kubernetes and search for it in `/usr/`.

Could you please help a poor guy out? I've spent hours and hours frustrated at not being able to find the actual location where it is installed. All I can see is `/usr/include/nccl.h`, which doesn't account for much.

(Context: I want to install libfabric and AWS's OFI NCCL plugin on top of your base image, but I need to know the build paths to NCCL for this to work.)

Let me know if you'd like me to create a new issue.
