### ISSUE TITLE
Add tensor() in  TFTensor class. For user to get the tensor_.

### ISSUE THREAD

**Issue by lianghongkey** [horovod/horovod#2452]
**Is your feature request related to a problem? Please describe.**
When integrating into tensorflow xla, we need to get the:: tensorflow::Tensor tensor_  of TFTensor class, to get xla tensor to  be used by custom definition operator.

**Describe the solution you'd like**
Add in TFTensor class:
    `virtual const void* tensor() const override;`
Impl:
   `const void* TFTensor::tensor() const { return (const void*)tensor_; }`

**Comment by Hizhaoyuan** [comment]
@lianghongkey **Excellent proposal！**

**Comment by Hizhaoyuan** [comment]
> **Is your feature request related to a problem? Please describe.**
> When integrating into tensorflow xla, we need to get the:: tensorflow::Tensor tensor_ of TFTensor class, to get xla tensor to be used by custom definition operator.
> 
> **Describe the solution you'd like**
> Add in TFTensor class:
> `virtual const void* tensor() const override;`
> Impl:
> `const void* TFTensor::tensor() const { return (const void*)tensor_; }`

class TFTensor : public common::Tensor{};
Need to add in common::Tensor class:
virtual const void* tensor() const override;

**Comment by tgaddair** [comment]
Hey @lianghongkey @Hizhaoyuan thanks for the suggestion!  I think as long as the usage is limited to the scope of the `tensorflow` module, then it sounds like a good idea.

I think we would want to avoid something like a common interface `virtual const void* tensor() const = 0;`, however, as the definition of the Tensor object is non-standard.  The TensorFlow, PyTorch, and MXNet implementations will all return different types.

If certain framework-specific functionality needs to be implemented in the generic Horovod code, we should instead provide a callback into the framework-specific code to handle that processing.

**Comment by Hizhaoyuan** [comment]
@tgaddair Thanks a lot for your prompt response. I understand what you mean. It is also a good idea to add a methods tensor() only in TFTensor class，there is no need to modify the interface common::Tensor{};
Add in TFTensor class:
`class TFTensor : public common::Tensor {
public:
  const void* tensor() const;
};`
Impl:
`const void* TFTensor::tensor() const { return (const void*)&tensor_; }`

**Comment by tgaddair** [comment]
Sounds good.  @lianghongkey @Hizhaoyuan , would either of you be interested in putting together a PR?

**Comment by Hizhaoyuan** [comment]
@tgaddair @lianghongkey I have created a PR.

**Comment by Hizhaoyuan** [comment]
@tgaddair I resubmitted a patch,  tensor() directly returned the pointer of tensor_. If type conversion is needed, I'll do it somewhere else. please review it, thanks.
