### ISSUE TITLE
Question on benchmark baseline

### ISSUE THREAD

**Issue by Zhaojp-Frank** [horovod/horovod#246]
A quick question about the baseline (original TensorFlow) shown in the benchmark. 
what's the distributed param used in baseline test at that moment? e.g., using --server_protocol=grpc or grpc+mpi, or gdr? distributed_replicated or parameter_server?

**Comment by alsrgv** [comment]
@Zhaojp-Frank, that was plain `grpc` + `parameter_server` as of TensorFlow 1.3.0.
