### ISSUE TITLE
pytorch gradient accumulation error

### ISSUE THREAD

**Issue by DuckJ** [horovod/horovod#2466]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.3.0
3. Horovod version: 0.19.4
4. MPI version: 3.0.4
5. CUDA version: 10.1
6. NCCL version:
7. Python version: 3.6
8. OS and version:  Ununtu 
9. GCC version: 7.3.0

I used the following code to implement gradient accumulatio，

```
accumulation_steps=8
for i,(images,target) in enumerate(train_loader):
    # 1. input output
    images = images.cuda(non_blocking=True)
    target = torch.from_numpy(np.array(target)).float().cuda(non_blocking=True)
    outputs = model(images)
    loss = criterion(outputs,target)
    # 2.1 loss regularization
    loss = loss/accumulation_steps
    # 2.2 back propagation
    loss.backward()

    # 3. update parameters of net
    if((i+1)%accumulation_steps)==0:
        # optimizer the net
        optimizer.step()        # update parameters of net
        optimizer.zero_grad()   # reset gradient
```

and I also set the horovod code below
`optimizer = hvd.DistributedOptimizer(
        optimizer, named_parameters=model.named_parameters(),
        backward_passes_per_step=8)`
But when I was training to the end of the first epoch, the  error is
 `AssertionError: Gradients were computed more than backward_passes_per_step times before call to step(). Increase backward_passes_per_step to accumulate gradients locally` 

I am confused.  How to solve this problem?
I also tried according to [https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_imagenet_resnet50.py](https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_imagenet_resnet50.py), but when I set the 
`args.batch-size = 6 
args.batches-per-allreduce =3
`
CUDA OOM. Any one can help me ? Thanks .

**Comment by Piscabo** [comment]
I wanted to continue my embedding and I get this error:
![image](https://user-images.githubusercontent.com/123719842/215059257-8a321e2f-e456-4ccd-98a6-6801ddc5a38c.png)
