### ISSUE TITLE
How many GPUs does a horovod process see?

### ISSUE THREAD

**Issue by rohit497** [horovod/horovod#2472]
**Environment:**
1. Framework: Pytorch
2. Framework version: 1.5.0
3. Horovod version: 0.19.5
4. MPI version: 4.0.4
5. CUDA version: 10.2
6. NCCL version:
7. Python version: 3.7.6
8. OS and version: Ubuntu 18.04
9. GCC version: 7.5

**Your question:**
Hi, I'm trying to launch a distributed training process on Azure Databricks using `horovod.spark` on 2 nodes with 2 GPUs each using the following command:
```
import horovod.spark
horovod.spark.run(train_hvd, num_proc=4, verbose=2)
```

However, when I print out the value of `torch.cuda.device_count()`, I find that it's always 1 even though each node should have 2 gpus. I have 3 questions regarding this:

1) Does each horovod process see only 1 GPU?
2) What if I were to see `num_proc` to 2? Would 2 GPUs be left unused?
3) What if I were to set `num_proc` to 8? How would the GPUs be allocated?

Thanks in advance!

**Comment by tgaddair** [comment]
Hey @rohit497, this depends primarily on how your Spark cluster is configured.  My guess is that you may be in a situation where you have 4 executors (2 on each node), and each executor has set `CUDA_VISIBLE_DEVICES` to a single GPU.  If that's true, then it wouldn't matter what you set as `num_proc`, the result would always be 1 GPU.

In general, with Horovod, we don't have a set relationship between number of processes and number of GPUs, though it's most common to run with 1 GPU per process (as you are doing).  It's standard practice to call `torch.cuda.set_device(hvd.local_rank())` from user code as shown [here](https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_mnist.py#L120) to enforce this behavior.
