### ISSUE TITLE
0.20.3 FOUND_LIB_cudart is not set while using pip to install horovod

### ISSUE THREAD

**Issue by jihuacao** [horovod/horovod#2474]
**Environment:**
1. Framework:  PyTorch
2. Framework version:1.7
3. Horovod version:0.20.3
4. MPI version:4.0.4
5. CUDA version:11.1
6. NCCL version:2.8.3
7. Python version:3.6.2
8. Spark / PySpark version:None
9. OS and version:ubuntu 16.4
10. GCC version:5.4.0
11. CMake version:3.18.4

command： 
 HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITHOUT_GLOO=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_CUDA_HOME=/usr/local/cuda proxychains pip install horovod
got：    
    -- Configuring done
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    FOUND_LIB_cudart
        linked by target "pytorch" in directory /tmp/pip-install-a7n3i33r/horovod/horovod/torch

use  command（install 0.19.5）：
HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITHOUT_GLOO=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_CUDA_HOME=/usr/local/cuda FOUND_LIB_cudart=/usr/local/cuda/lib64/libcudart.so proxychains pip install horovod==0.19.5
got：

Installing collected packages: horovod
Successfully installed horovod-0.19.5

**Comment by tgaddair** [comment]
Hey @jihuacao, can you share the full log output in a file / gist from the failing install?

@nvcastet any thoughts on why CMake is failing to find cudart here?

**Comment by jihuacao** [comment]
> Hey @jihuacao, can you share the full log output in a file / gist from the failing install?
> 
> @nvcastet any thoughts on why CMake is failing to find cudart here?
[install_hvd_0.20.3.log](https://github.com/horovod/horovod/files/5588061/install_hvd_0.20.3.log)

**Comment by tgaddair** [comment]
Hey @jihuacao, thanks for sharing the log.  Did you try running with `FOUND_LIB_cudart=/usr/local/cuda/lib64/libcudart.so` when installing the latest Horovod?  Can you also verify that `/usr/local/cuda/lib64/libcudart.so` exists in that location?

Looks like your PyTorch version was built for CUDA 11.0 (`1.7.0+cu110`).  I'm wondering if that could be a factor here.  Have you tried running with CUDA 11.0 instead?

I'll see if I can reproduce this with CUDA 11.1 locally.

**Comment by jihuacao** [comment]
@tgaddair 
Thanks.
The problem happens while cmake. Libcudart is indeed exists. Compiling successful when I cmake manually with -DFOUND_LIB_cudart=/usr/local/cuda/lib64/libcudart.so, but I do not know how to install in python.

**Comment by jihuacao** [comment]
@tgaddair 
The same problem happens while using torch1.17 from source with cuda11.1

**Comment by jihuacao** [comment]
Very Sorry. @tgaddair It is my own mistake. I forgot that I have wrote the different CUDA_HOME to ~/.bashrc.
Installing successful after I removed it.
