### ISSUE TITLE
Integrating Horovod in an MPI parallelized system

### ISSUE THREAD

**Issue by weidler** [horovod/horovod#2479]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.3.1
3. Horovod version: 0.20.3
4. MPI version: 4.0.3
5. CUDA version: 11
6. NCCL version: -
7. Python version: 3.8
8. OS and version: Ubuntu 20 LTS
9. GCC version: 9

**Your question:**
I have a python script in which I use with MPI (mpi4py) to parallelize CPU accelerated parts of my program: rolling out the policy in a reinforcement learning system. Currently, the optimization of the policy network is performed on a single GPU, but I would like to parallelize this part too, using Horovod with TF (sadly, TF's own distribution strategies do not support stateful RNNs). How can I integrate both the CPU parallelization and the GPU parallelization? Intuitively, I would expect to need a communicator consisting only of processes with GPU next to COMM_WORLD and initialize horovod on it. But at the same time, this feels overly complicated with the communicator then not existing on all processes etc.

What would be the best practice for such a case?

**Comment by tgaddair** [comment]
Hey @weidler, if I understand the situation correctly, it sounds like you should be able to do this pretty simply using the approach described [here](https://github.com/horovod/horovod#mpi4py).  As long as you maintain a mapping of which ranks are the GPU / Horovod workers, you can use a single conditional to separate the Horovod training from the rest of the logic.  Would that work?

**Comment by weidler** [comment]
Thanks for the answer. I tried this before but didn't succeed, probably because I did not fully understand how `MPI.COMM_WORLD.Split` works. I now managed to make it run, the main realization was that I can initialize horovod on both sub communicators although it will use only one (the one fulfilling the GPU condition. At least I hope that this is the way:

```python
mpi_comm = MPI.COMM_WORLD
gpus = tf.config.experimental.list_physical_devices('GPU')
is_gpu_process = mpi_comm.rank < len(gpus)

# create subcomm with GPUs
gpu_subcomm = mpi_comm.Split(color=int(is_gpu_process))
hvd.init(comm=gpu_subcomm)

for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus and hvd.local_rank() < len(gpus):
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
```
If I only initiate horovod on the GPU processes, then I get a deadlock. Is that intended?

**Comment by tgaddair** [comment]
Hey @weidler, that's not intended, but it shouldn't be an issue.  Horovod initialization is pretty lightweight.  Glad you got it working.

**Comment by weidler** [comment]
@tgaddair after some experimenting I noticed that horovod seemingly slows down the parallel MPI job execution. I am running the following for setup now 

```python
HOROVOD = False

# get COMM and find gpus
mpi_comm = MPI.COMM_WORLD
gpus = tf.config.experimental.list_physical_devices('GPU')
is_gpu_process = MPI.COMM_WORLD.rank < len(gpus)

if not is_gpu_process:
    tf.config.experimental.set_visible_devices([], "GPU")

if HOROVOD:
    import horovod.tensorflow as hvd

    # create subcomm with GPUs
    gpu_subcomm = mpi_comm.Split(color=int(is_gpu_process))
    hvd.init(comm=gpu_subcomm)

    # prevent full blockage of VRAM
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)

    if is_gpu_process:
        if gpus:
            tf.config.experimental.set_visible_devices(gpus[mpi_comm.rank], 'GPU')
```

to test the script with and without horovod. The individual parts in the training loop (tape wrapper etc.) are also conditioned on `HOROVOD`. With `HOROVOD=True` one epoch takes about 12s but with `HOROVOD=False` it takes around 8s. Note that I only test on a single GPU at the moment so I cannot make use of horovods GPU parallelization but I would still not expect it to slow down anything. Looking at the runtimes of individual parts, it also shows that both the optimization on GPU, and the simulation on 4 CPU cores is slower by about an equal fraction of the original runtime (and simulation is the bottleneck here).

Do you have any idea what is going wrong? It seems not to matter if I execute using `mpirun` or `horovodrun` but adding `bind-to none` and `-map-by slot` even raises runtime to about 25s.

**Comment by tgaddair** [comment]
Hey @weidler, are you running multiple Horovod workers on this same GPU?  If so, then that would explain the slow down, in my opinion.  Or do you mean that you only have a single Horovod worker and a single GPU?

**Comment by weidler** [comment]
I start horovodrun/mpirun with 4 workers, but the split in the code of my previous post will only dedicate a single worker to gpu_subcomm which I use to initialize horovod. However, indeed on the other processes that are not allocated GPUs (3 of the 4), the split will allocate each of these CPU ranks to gpu_subcomm. My following implementation will then ignore/do nothing on them, though. Thats what I meant  earlier when I said I get a deadlock if I do not initialize the gpu_subcomm on the non-gpu processes. Is this maybe the issue? If so, how can I only have horovod initialized/allocated ranks on the GPU processes but not on the CPU processes?

**Comment by tgaddair** [comment]
@weidler, my suspicion is that somehow the GPU isn't being used effectively in this setup, leading to degraded performance.  With only one process (`hvd.size() == 1`), there should be no communication overhead, so Horovod should basically be doing nothing.  As a test, you could try commenting out the Horovod parts and see if that has an effect.  I would also check the output of `nvidia-smi` to verify you're getting good utilization of the GPU.

**Comment by weidler** [comment]
@tgaddari I tested this in three setups now. For this the implementation is as follows:

### Setup
```python
HOROVOD = False
INIT_HOROVOD = True

# get COMM and find gpus
mpi_comm = MPI.COMM_WORLD
gpus = tf.config.experimental.list_physical_devices('GPU')
is_gpu_process = MPI.COMM_WORLD.rank < len(gpus)

if not is_gpu_process:
    tf.config.experimental.set_visible_devices([], "GPU")

if INIT_HOROVOD:
    import horovod.tensorflow as hvd

    # create subcomm with GPUs
    gpu_subcomm = mpi_comm.Split(color=int(is_gpu_process))

    hvd.init(comm=gpu_subcomm)

    # prevent full blockage of VRAM
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)

    if is_gpu_process:
        if gpus:
            tf.config.experimental.set_visible_devices(gpus[mpi_comm.rank], 'GPU')
```

### Horovod Parts of The Code

```python
if HOROVOD:
        tape = hvd.DistributedGradientTape(tape)
```

```python
if HOROVOD:
        dataset = dataset.take(dataset.cardinality() // hvd.size())
```

```python
if first_batch and HOROVOD:
        hvd.broadcast_variables(self.joint.variables, root_rank=0)
        hvd.broadcast_variables(self.optimizer.variables(), root_rank=0)
```

### Results

Both False: ~8.8s per cycle
INIT_HOROVOD=True: ~13.5s
INIT_HOROVOD=True + HOROVOD=True: ~13.5s

The Volatile GPU-Utilization is always about the same ~30%

**Comment by tgaddair** [comment]
@weidler, that's interesting, so if I understand your results correctly, the source of the slowdown is coming from this section:

```
import horovod.tensorflow as hvd

    # create subcomm with GPUs
    gpu_subcomm = mpi_comm.Split(color=int(is_gpu_process))

    hvd.init(comm=gpu_subcomm)

    # prevent full blockage of VRAM
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)

    if is_gpu_process:
        if gpus:
            tf.config.experimental.set_visible_devices(gpus[mpi_comm.rank], 'GPU')
```

If you're only running with 1 GPU, can you try a few different tests:

1. Horovod init without creating / passing in subcomm.
2. Creating subcomm without initializing Horovod
3. Comment out init section below "prevent full blockage of VRAM"

Also, can you change the `set_visible_devices` line to the following:

```
tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')
```

**Comment by tgaddair** [comment]
Hey @weidler, this is interesting, I'm wondering if you could try creating a [Horovod Timeline](https://github.com/horovod/horovod/blob/master/docs/timeline.rst) and share it here?  It may be that there is some communication bottleneck being introduced that I'm not seeing.
