### ISSUE TITLE
what protobuf  version can I install Horovod

### ISSUE THREAD

**Issue by Crystal-wxy** [horovod/horovod#2485]
**Environment:**
1. Framework: (TensorFlow 2.4.0rc3, Keras, PyTorch1.7.0gpu, MXNet) 
2. Framework version:
3. Horovod version:0.21.0
4. MPI version:4.0.5
5. CUDA version:11
6. NCCL version:
7. Python version:3.8
8. OS and version:ubuntu20.04
9. GCC version:7.5 

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
when i install ，an error appended  ，it is about  i have an error protoc vesion ，but what version is sure
error This file was generated by a older version of protoc which is

**Comment by tgaddair** [comment]
Hey @Crystal-wxy, generally this problem occurs when the version of protoc that is shipped with TensorFlow is different from what you have installed.  Your version of protoc should match the one used by TensorFlow [here](https://github.com/tensorflow/tensorflow/blob/v2.4.0-rc3/tensorflow/workspace.bzl#L580) (3.9.2).
