### ISSUE TITLE
Horovod Allgather

### ISSUE THREAD

**Issue by anweshpanda** [horovod/horovod#2490]
For all-reduce operation horovod uses ring all-reduce. Can anyone please tell me which algorithm is used for doing allgather?

**Comment by tgaddair** [comment]
Hey @anweshpanda, for Allreduce, the exact implementation will depend on your version of NCCL.  In newer versions of NCCL, it will switch between ring or tree allreduce depending on the topology of the communicator.  Similarly for Allgather, the exact implementation will depend on NCCL.  I would suggest following up with them for more details.

**Comment by niranjansuthar70** [comment]
@anweshpanda 
Hello,
I am planning to use Horovod for distribution training with host machine (1 GPU), and other 3 machine with 1 GPU each.
So should I install Horovod on each machine? and how can I create these server1,2,3,4 mention here? "$ horovodrun -np 4 -H server1:1,server2:1,server3:1,server4:1 python train.py"

Also how can I pin these 4 GPUs in these lines:

"config = tf.ConfigProto()
config.gpu_options.visible_device_list = str(hvd.local_rank())"

thanks!
