### ISSUE TITLE
Install oneCCL from official GitHub in CI

### ISSUE THREAD

**Issue by tgaddair** [horovod/horovod#2499]
In #2433, CI installs oneCCL from personal GitHub.  This should be changed to official repo following oneCCL Gold release.

cc @shirosankaku @mshiryaev

**Comment by shirosankaku** [comment]
@tgaddair Could you, please, revert those changes? I mean, the merge. The issue here is that we were planning to make a cleaner branch after official release on Tue next week with a cleaner history to mark @fschlimb as a contributor of the code.

**Comment by mshiryaev** [comment]
I believe this can be closed
