### ISSUE TITLE
Failed to biuld wheel for horovod

### ISSUE THREAD

**Issue by zechao-zhang** [horovod/horovod#2504]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) PYTORCH
2. Framework version:1.7
3. Horovod version:0.21
4. MPI version:4.0.5
5. CUDA version:10.2
6. NCCL version:2.8.3
7. Python version:3.8
8. Spark / PySpark version:none
9. OS and version: ubuntu1804
10. GCC version:4.9.3
11. CMake version:3.18

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I have installed nccl-2.8.3 and openmpi-4.0.5 in the environment, and the version detected by 'mpirun -version' is 4.0.5,

Howerver, it showsFound MPI: TRUE (found version "3.1") during installing horovod and it always fails to build wheel for horovod

I use command : CUDA_INCLUDE_DIRS=/usr/local/cuda-10.2/include HOROVOD_WITH_PYTORCH=1 HPROVOD_WITH_MPI=1 HOROVOD_GPU_ALLREDUCE=NCCL pip install --verbose --no-cache-dir horovod
and the full report is in the report.txt

Can you help me with this problem? thanks a lot.

[report.txt](https://github.com/horovod/horovod/files/5648355/report.txt)

**Comment by tgaddair** [comment]
Hey @zechao-zhang, looks like you're running in this issue: https://stackoverflow.com/questions/25123458/is-trivially-copyable-is-not-a-member-of-std

Can you try upgrading your version of GCC?
