### ISSUE TITLE
'pyarrow.lib.Schema' object has no attribute 'field'

### ISSUE THREAD

**Issue by yikuanli** [horovod/horovod#2507]
I use Pyspark to generate a DataFrame and save it in parquet.

when I use petastorm to read the parquet file, it shows this error
'pyarrow.lib.Schema' object has no attribute 'field'

this is my code

`
from petastorm import make_batch_reader
from pathlib import Path
dataset = make_batch_reader(Path("/home/valid.parquet").absolute().as_uri(), workers_count=4)
`

I got the error as following:
![image](https://user-images.githubusercontent.com/40010984/101375957-e655ab00-38a7-11eb-872b-48235a1ffc03.png)

can anyone help me to read the file, I v been struggling to figure out how to read this for a few days.

**Comment by tgaddair** [comment]
Hey @yikuanli, can you share your version of Petastorm and PyArrow?

**Comment by yikuanli** [comment]
Hi @tgaddair I am using 
pyarrow                 0.13.0
petastorm               0.9.2

**Comment by yikuanli** [comment]
sorry my bad, I thought I am using a package, but not, I now upgrade my pyarrow and now it works

**Comment by tgaddair** [comment]
Great, glad you got it working.
