### ISSUE TITLE
Horovod on Spark (Keras) overhead and performance is extremely slow when connected to VPN

### ISSUE THREAD

**Issue by OscarDPan** [horovod/horovod#2512]
**Environment:**
1. Framework: TF
2. Framework version: 2.3.1
3. Horovod version:0.21.0
4. MPI version: N/A
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7.7
8. OS and version: MacOS 10.15.7
9. GCC version: 4.2.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before? YES
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I followed mostly the tutorials from "End-to-End Deep Learning with Horovod on Apache Spark 2020" and made a simple unittest to test run Keras DNN on spark with Horovod in local mode.

Everything was blissful except when my Mac connects to (Open)VPN...
The time it took to finish the unittest increased from 10s to 7min

I found it spent most of the time in 
https://github.com/horovod/horovod/blob/master/horovod/spark/runner.py#L268
and 
https://github.com/horovod/horovod/blob/master/horovod/runner/gloo_run.py#L261

I wasn't able to find any extra log for me to debug what is going on.
Why would the performance deteriorate so much when my Mac logs into a VPN?

**Comment by OscarDPan** [comment]
When I connected to VPN I have this extra interface

utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 100.64.0.1 --> 100.64.0.1 netmask 0xffff0000
	nd6 options=201<PERFORMNUD,DAD>

And the existence of it seems to be the cause of the slowness.

**Comment by tgaddair** [comment]
Hey @OscarDPan, in the case of a VPN, you're adding an additional hop for communication between workers, as well as encrypting the messages, which can significantly degrade performance.
