### ISSUE TITLE
Using --gloo normal but --mpi not

### ISSUE THREAD

**Issue by SicleBoypy** [horovod/horovod#2516]
**Environment:**
1. Framework:Pytorch
2. Framework version:1.7.0
3. Horovod version:v0.21.0
4. MPI version:4.0.5
5. CUDA version:11.0
6. NCCL version:2.8.3
7. Python version:3.7
8. OS and version:ubuntu18.04
9. GCC version:7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.
ip:10.19.250.170
Horovod v0.21.0:

Available Frameworks:
    [ ] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo

ip:10.19.250.171
Horovod v0.21.0:

Available Frameworks:
    [ ] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [X] Gloo

Available Tensor Operations:
    [X] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [X] Gloo

horovodrun -np 8 -p 22 -H 10.19.250.171:4,10.19.250.170:4  --network-interface "bond0,bond0" --gloo  python pytorch_mnist.py is OK
but  horovodrun -np 8 -p 22 -H 10.19.250.171:4,10.19.250.170:4  --network-interface "bond0,bond0" --mpi  python pytorch_mnist.py will stuck
why???

**Comment by tgaddair** [comment]
Hey @SicleBoypy, can you try running with `--verbose`?  It may be that MPI is not configured correctly.   I would suggest sticking with Gloo unless you need to use MPI for some reason.

**Comment by SicleBoypy** [comment]
> 
> 
> Hey @SicleBoypy, can you try running with `--verbose`? It may be that MPI is not configured correctly. I would suggest sticking with Gloo unless you need to use MPI for some reason.

Thanks, I have solved the problem with reinstalling horovod

**Comment by tgaddair** [comment]
Glad you got it working!  I'll close this issue.
