### ISSUE TITLE
How can I be sure that the data is entered in parallel?

### ISSUE THREAD

**Issue by jinsu-kim** [horovod/horovod#2520]
**Environment:**
1. Framework: TensorFlow
2. Framework version: tf2.0
3. Horovod version:0.20.0
4. MPI version:2.1.1
5. CUDA version:10.0
6. NCCL version: x
7. Python version:3.7.4
8. OS and version: ubuntu 18.04
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

Hi,
I am running the code 'horovod/examples/tensorflow2/tensorflow2_mnist.py' in 2 pcs in parallel with this command.
`$ horovodrun -np 2 -H localhost:1,c002:1 python tensorflow2_mnist.py`

I wonder if the replicated model in c002 is learning from the same data in localhost or not.
So my question is,
how do I know that each model is training on a different subset of MNIST data???
how can I check it??

**Comment by tgaddair** [comment]
Hey @jinsu-kim, in the case of the MNIST examples, we're not training on different subsets of data.  Every worker simply selects a random batch at each step.  However, you certainly can ensure that each worker gets a distinct subset of the data using something like [Petastorm](https://github.com/uber/petastorm) of TF Dataset's `.shard()` API.
