### ISSUE TITLE
Problem with pytorch on CPU container

### ISSUE THREAD

**Issue by nicolalandro** [horovod/horovod#2521]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.6.0
3. Horovod version: 0.20.0
4. MPI version: unknown
5. CUDA version: No
6. NCCL version: No
7. Python version: 3.6
8. OS and version: unknown
9. GCC version: unknown

**Pytorch on cpu container does not work:**
I try to use horovond on cpu with the official container, but it get an error:
```
Illegal instruction (core dumped)
```
did I do something wrong?

To replicate do the following:
```
docker run --rm -it horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.5.0-py3.7-cpu bash 
$ python
$ >>> import horovod.torch
$ Illegal instruction (core dumped)
```

What I do wrong?

**Comment by tgaddair** [comment]
Hey @nicolalandro, looks like there may be an issue with the container.  I will take a look.

**Comment by nicolalandro** [comment]
I try it now, perfect It work correctly! Thank you!
