### ISSUE TITLE
HOROVOD_THREAD_AFFINITY

### ISSUE THREAD

**Issue by whatdhack** [horovod/horovod#2525]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.4
3. Horovod version: 19.5
4. MPI version:  ?
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.7.8
8. OS and version: N/A
9. GCC version: N/A

**Your question:**
How is HOROVOD_THREAD_AFFINITY supposed to be used ?  From what Horovod version is it supposed to work ?

**Comment by tgaddair** [comment]
Hey @whatdhack, my understanding is that you can have the Horovod background thread loop run on a specific CPU core to have more fine-grained control of thread placement.

cc @shirosankaku who added this feature, can you provide additional details?

**Comment by whatdhack** [comment]
@tgaddair , thanks. @shirosankaku , would appreciate any detail  - the code does not have much really.  Is it supposed to work with any collectives library ?

**Comment by shirosankaku** [comment]
Hello, @whatdhack !

This variable was introduced to use with pinning functionality to separate computing (cpu operations) from Horovod background thread loop (frameworks messages processing and so on) to free from the influence of one another, to get better performance. E.g. if you have one physical core with hyper-threading on, you can pin cpu_operations processor (i.e. collective library) to one virtual core and Horovod background loop related activity to another virtual core.

Here, in docs [section](https://github.com/horovod/horovod/blob/master/docs/oneccl.rst) is a piece of information (at the bottom of the page) about the variable usage with oneCCL, as an example. 

It is supposed to work with any collectives library that provides a pinning option but setting it without proper pinning on libraries side just doesn't make sense.

**Comment by whatdhack** [comment]
@shirosankaku , thanks for the explanation.   Wondering how this variable interacts with _mpirun --bind-to_ command  ?  If there are more than one Horovod ranks per node, can this variable  provide unique core assignment to each of the ranks.  An example command for such a situation will be great for understanding the usage of this  variable.

Also,  wondering if you can  say few more words on "without proper pinning on libraries side just doesn't make sense".  At a high level what does the collectives library needs to support this?  So, the next  obvious question is what collectives libraries currently known to support this ?

**Comment by mshiryaev** [comment]
@whatdhack  - if there are more than one Horovod ranks per node then you still can use HOROVOD_THREAD_AFFINITY.
This variable accepts comma separated list of cores, one core per one local rank.

The link from @shirosankaku comment covers this case, 2 nodes, each with 2 Horovod processes.
https://github.com/horovod/horovod/blob/master/docs/oneccl.rst#affinity

In performant case we expect Horovod process (containing also compute threads from framework level) will be pinned, e.g. with MPI pinning settings like "--bind-to" in OpenMPI or I_MPI_PIN_* knobs in IntelMPI (https://software.intel.com/content/www/us/en/develop/documentation/mpi-developer-reference-linux/top/environment-variable-reference/process-pinning/environment-variables-for-process-pinning.html). 
HOROVOD_THREAD_AFFINITY allows to dedicate core for Horovod background thread to avoid intersection with compute threads.
