### ISSUE TITLE
the meaning of the log prefix

### ISSUE THREAD

**Issue by vanillar7** [horovod/horovod#2527]
i use horovod in docker, and run the example code. 
the prefix of log is "[1,0]",  what the meaning of it?

the command : horovodrun  -np 2 -H localhost:2 python tensorflow2_mnist.py
log:
[1,0]<stdout>:Step #0	Loss: 2.324532
[1,0]<stdout>:Step #10	Loss: 0.924903
[1,0]<stdout>:Step #20	Loss: 0.522037
[1,0]<stdout>:Step #30	Loss: 0.505868
[1,0]<stdout>:Step #40	Loss: 0.351588

**Comment by tgaddair** [comment]
Hey @vanillar7, this is just telling you which rank is printing the log message.  You can run a test like:

```
print(hvd.rank())
```

To see how different ranks are given different prefixes.

**Comment by vanillar7** [comment]
> Hey @vanillar7, this is just telling you which rank is printing the log message. You can run a test like:
> 
> ```
> print(hvd.rank())
> ```
> 
> To see how different ranks are given different prefixes.

the second num is the local rank of workers, but  i still don't know the meaning of  the first number

**Comment by tgaddair** [comment]
Hey @vanillar7, it may vary depending on your MPI implementation, but assuming you're using OpenMPI, this is coming from the `--tag-output` option described [here](https://www.open-mpi.org/doc/v3.0/man1/mpirun.1.php):

> -tag-output, --tag-output
> Tag each line of output to stdout, stderr, and stddiag with [jobid, MCW_rank]<stdxxx> indicating the process jobid and MPI_COMM_WORLD rank of the process that generated the output, and the channel which generated it.

**Comment by vanillar7** [comment]
@tgaddair i got it，thank you

**Comment by SysuJayce** [comment]
Hi @tgaddair , is it necessary to keep the prefix? Can we disable the prefix?

If yes, then how?
If no, then why?
