### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SicleBoypy** [horovod/horovod#2545]
**Environment:**
1. Framework: Pytorch
2. Framework version: 1.7.0
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

When Using a small datasets is normal ,but using a large datsets appear memory leak

**Comment by tgaddair** [comment]
Hey @SicleBoypy, can you provide more details, like a minimal repro script or similar?

**Comment by SicleBoypy** [comment]
> 
> 
> Hey @SicleBoypy, can you provide more details, like a minimal repro script or similar?

Thanks for your replying，I have solved the Mem Leak for checking the training code not in horovod

**Comment by SicleBoypy** [comment]
> 
> 
> Hey @SicleBoypy, can you provide more details, like a minimal repro script or similar?
but I have another question how to use IB Network Card for accelerating speed？

**Comment by tgaddair** [comment]
Hey @SicleBoypy, if using Docker, see [this](https://github.com/horovod/horovod/blob/master/docs/docker.rst#adding-mellanox-rdma-support) section of the docs.  For MPI specific considerations, see [here](https://github.com/horovod/horovod/blob/master/docs/mpi.rst#open-mpi-with-rdma).
