### ISSUE TITLE
Build Error TF Nightly with Horovod 0.21.0

### ISSUE THREAD

**Issue by ashiqimranintel** [horovod/horovod#2546]
**Environment:**
1. Framework: TensorFlow,
2. Framework version: nightly
3. Horovod version: 0.21.0
4. MPI version: 3
5. CUDA version:
6. NCCL version:
7. Python version: 3.6.9
8. Spark / PySpark version:
9. OS and version: Ubuntu 
10. GCC version: 7.5
11. CMake version:

**Bug report:**
horovod/tensorflow/CMakeFiles/tensorflow.dir/build.make:758: recipe for target 'horovod/tensorflow/CMakeFiles/tensorflow.dir/mpi_ops.cc.o' failed
  make[2]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/mpi_ops.cc.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  make[2]: Leaving directory '/tmp/pip-install-f8bbk9ut/horovod_bc48e7b26d9c4b679e9e8eaa544af2ed/build/temp.linux-x86_64-3.6'
  CMakeFiles/Makefile2:259: recipe for target 'horovod/tensorflow/CMakeFiles/tensorflow.dir/all' failed
  make[1]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/all] Error 2
  make[1]: Leaving directory '/tmp/pip-install-f8bbk9ut/horovod_bc48e7b26d9c4b679e9e8eaa544af2ed/build/temp.linux-x86_64-3.6'
  Makefile:129: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-f8bbk9ut/horovod_bc48e7b26d9c4b679e9e8eaa544af2ed/setup.py", line 193, in <module>
      'horovodrun = horovod.runner.launch:run_commandline'
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-f8bbk9ut/horovod_bc48e7b26d9c4b679e9e8eaa544af2ed/setup.py", line 91, in build_extensions
      cwd=self.build_temp)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for horovod

**Comment by tgaddair** [comment]
Hey @ashiqimranintel, can you try running with `MAKEFLAGS="-j1"` and share the full log output?

**Comment by ashahba** [comment]
Hi @tgaddair the full log is attached:
[horovod_install.log](https://github.com/horovod/horovod/files/5767060/horovod_install.log)

**Comment by ashahba** [comment]
However this works fine:
```
python3 -m pip install git+https://github.com/horovod/horovod.git@bb4e4cf7
Collecting git+https://github.com/horovod/horovod.git@bb4e4cf7
  Cloning https://github.com/horovod/horovod.git (to revision bb4e4cf7) to /tmp/pip-req-build-z1z3v8cl
  WARNING: Did not find branch or tag 'bb4e4cf7', assuming revision or ref.
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.6/dist-packages (from horovod==0.20.3) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.6/dist-packages (from horovod==0.20.3) (5.8.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from horovod==0.20.3) (5.3.1)
Requirement already satisfied: dataclasses in /usr/local/lib/python3.6/dist-packages (from horovod==0.20.3) (0.8)
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... done
  Created wheel for horovod: filename=horovod-0.20.3-cp36-cp36m-linux_x86_64.whl size=12030534 sha256=b41906472c0ba3312d0b18db8787e66f61f489a3808d2ae1b97013f9a4ad6cd1
  Stored in directory: /tmp/pip-ephem-wheel-cache-nnvb2jbp/wheels/18/fe/a2/18c1c620c203393b09c585295ef844f73a823d25a304e945fe
Successfully built horovod
Installing collected packages: horovod
Successfully installed horovod-0.20.3
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by ashahba** [comment]
Surprisingly enough:
```
python3 -m pip install git+https://github.com/horovod/horovod.git@v0.21.0
```
Works as expected.

**Comment by tgaddair** [comment]
Hey @ashahba, do you see the same issue with v0.21.1?
