### ISSUE TITLE
horovod.run.common.util.network.NoValidAddressesFound: Horovodrun was unable to connect to driver service on any of the following addresses

### ISSUE THREAD

**Issue by iideas18** [horovod/horovod#2547]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.1.0
3. Horovod version: 0.19.1 and 0.21.0
4. MPI version: 4.0.2
5. CUDA version: None
6. NCCL version: None
7. Python version: 3.6
8. OS and version: Linux -CentOS
9. GCC version: gcc-4.8.5
10. Spark version: PySpark 2.4.0 and Pyspark 3.0.1
**Checklist:**
1. Did you search issues to find if somebody asked this question before?
YES
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? YES
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? YES
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? YES

**Your question:**
Please ask your question here.
When I using spark-submit **--master yarn or --master spark://172.168.0.1:7077**, it happened.
```
[1,96]<stderr>:  File "horovod/run/common/util/network.py", line 174, in __init__
[1,96]<stderr>:    'Linux.'.format(service_name=service_name, addresses=addresses))
[1,96]<stderr>:horovod.run.common.util.network.NoValidAddressesFound: Horovodrun was unable to connect to driver service on any of the following addresses: {'lo': [('127.0.0.1', 1053)], 'eno1': [('', 1053)], 'ib0': [('172.168.0.1', 1053)]}.
```
For the spark-submit **--master local[*]**, it ran successfully.

I also check the "one routable network interface with the same name across all of the hosts", all workers using same network interface **ib0**.
like, 
ifconfig -a:
      node1 :  ib0：'172.168.0.1'
      node2 :  ib0：'172.168.0.2'
      node3 :  ib0：'172.168.0.3'
      node4 :  ib0：'172.168.0.4'

Actually, I use **netstat -ano | grep 1053**, I saw the connection between hosts. But it still failed.

**Comment by iideas18** [comment]
When I change the version to 0.19.3, it hangs on yarn mode, failed for the client mode:

[1,0]<stderr>:Original exception was:
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62750,1],19]
  Exit code:    1

**Comment by iideas18** [comment]
Is that possible the horovod does not support yarn mode ????

**Comment by tgaddair** [comment]
Hey @iideas18, to clarify, were you able to reach the node at 172.168.0.1:7077 (the driver) on some interface from the workers?

cc @EnricoMi, any thoughts on this issue?

**Comment by iideas18** [comment]
> Hey @iideas18, to clarify, were you able to reach the node at 172.168.0.1:7077 (the driver) on some interface from the workers?
> 
> cc @EnricoMi, any thoughts on this issue?

Yes, I can reach the driver.
Actually, for this one:
`[1,96]<stderr>:horovod.run.common.util.network.NoValidAddressesFound: Horovodrun was unable to connect to driver service on any of the following addresses: {'lo': [('127.0.0.1', 1053)], 'eno1': [('', 1053)], 'ib0': [('172.168.0.1', 1053)]}.`
I saw the connection between nodes, using **netstat -apn | grep 1053**, it showed some connection, like:
172.168.0.2:xxxx connect to 172.168.0.1:1053
172.168.0.3:xxxx connect to 172.168.0.1:1053
172.168.0.4:xxxx connect to 172.168.0.1:1053

but it still failed. I checked **unlimit**. It's enough for those connections.

**Comment by iideas18** [comment]
> Hey @iideas18, to clarify, were you able to reach the node at 172.168.0.1:7077 (the driver) on some interface from the workers?
> 
> cc @EnricoMi, any thoughts on this issue?

When I install the horovod in conda, using: **pip install --no-cache-dir horovod**. It can not find the openmpi-4.0.3, which I installed before, I tried **conda install horovod** (refer to this [one ](https://github.com/horovod/horovod/issues/2240)).
![image](https://user-images.githubusercontent.com/44938480/103618363-cd095280-4f6a-11eb-948b-c888f40f6e59.png)


But, when I using **horovodrun -H node1:4,node2:2,node3:2,node4:1**, like this one in the conda environment, it shows:
![image](https://user-images.githubusercontent.com/44938480/103618535-178acf00-4f6b-11eb-8442-35f18eb94a7c.png)

**Comment by EnricoMi** [comment]
We should focus here on the newer versions as v0.19.1 is very old w.r.t. Spark integration.

With 0.20.3, what is the root cause for `mpirun` to error? There must be some Spark job failure to cause this. Also we should look into running with `spark-submit --master spark://172.168.0.1:7077` first, as this is something I can test on my side (other than Yarn).

We could also first exclude MPI and use the much simpler gloo. What do you think?
