### ISSUE TITLE
About hvd.tensorflow.elastic.TensorFlowState

### ISSUE THREAD

**Issue by woodlgz** [horovod/horovod#2550]
Hi, I have question about hvd.tensorflow.elastic.TensorFlowState.
In case of TF2 eager mode, isn't that global variables boardcast only happened at contruction?

**Comment by tgaddair** [comment]
Hey @woodlgz, the global variables broadcast will also occur any time `TensorFlowState.sync()` is called, which includes the beginning of `horovod.elastic.run`.  Hope that answers your question.
