### ISSUE TITLE
how Hierarchical allgather is implemented

### ISSUE THREAD

**Issue by gongjingcs** [horovod/horovod#2551]
Hello, I want to know how Hierarchical allgather of horovod is implemented, does it depend on mpi or only nccl？Looking forward to your reply

**Comment by karakusc** [comment]
Hi @gongjingcs, hierarchical allgather only uses MPI.

**Comment by niranjansuthar70** [comment]
@karakusc 
Hello,
I am planning to use Horovod for distribution training with host machine (1 GPU), and other 3 machine with 1 GPU each.
So should I install Horovod on each machine? and how can I create these server1,2,3,4 mention here? "$ horovodrun -np 4 -H server1:1,server2:1,server3:1,server4:1 python train.py"

Also how can I pin these 4 GPUs in these lines:

"config = tf.ConfigProto()
config.gpu_options.visible_device_list = str(hvd.local_rank())"

thanks!
