### ISSUE TITLE
centos install horovod failed

### ISSUE THREAD

**Issue by Echo9573** [horovod/horovod#2552]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.0.0a1
3. Horovod version:
4. MPI version:4.0.1
5. CUDA version:10.0
6. NCCL version:2.4.8
7. Python version:Python 3.6.3
8. Spark / PySpark version:
9. OS and version:
10. GCC version:gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
11. CMake version:GNU Make 3.82

**Bug report:**
I have used **HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL pip install --no-cache-dir horovod**to install, but always got the error message as follows. Please help check this error. Thanks very much!

subpyrocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-tgrxoctf/horovod_cf245c9a82d6425e9958134962b33cc4', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-install-tgrxoctf/horovod_cf245c9a82d6425e9958134962b33cc4/build/lib.linux-x86_64-3.6', '-DPYTHON_EXECUTABLE:FILEPATH=/home/luban/miniconda3/bin/python']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/luban/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tgrxoctf/horovod_cf245c9a82d6425e9958134962b33cc4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tgrxoctf/horovod_cf245c9a82d6425e9958134962b33cc4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3d8mpj9s/install-record.txt --single-version-externally-managed --compile --install-headers /home/luban/miniconda3/include/python3.6m/horovod Check the logs for full command output.

**Comment by tgaddair** [comment]
Hey @Echo9573, please share the full log output in a gist, the true error message is usually hidden somewhere above this.

Also, try running with `MAKEFLAGS="-j1"` as an environment variable.
