### ISSUE TITLE
Print bindings for `gloo`

### ISSUE THREAD

**Issue by tonyreina** [horovod/horovod#2558]
For MPI I can use `--print-bindings` to confirm that the correct cores and nodes are bound to the workers. Is there a similar switch for `gloo`?

**Comment by tgaddair** [comment]
Hey @tonyreina, we don't have this at the moment, unfortunately, you would need to print it from the workers themselves.  It's also worth mentioning that Gloo does not currently do any CPU binding / affinity when launching the process, though this may be something worth exploring.
