### ISSUE TITLE
error: attempting to use an MPI routine after finalizing MPI

### ISSUE THREAD

**Issue by weiliu620** [horovod/horovod#256]
I'm new to MPI programming but I have a small script called `test_hvd.py`:
```
from mpi4py import MPI
 
import mpi4py.rc
import sys; sys.path.insert(0, '/users/wliu8/.local/lib/python3.6/site-packages')
 
import horovod.tensorflow as hvd
import horovod
 
print(hvd.__file__)
print(horovod.__version__)
 
hvd.init()
```

I run it by
```
mpirun -n 1  -bind-to none -map-by slot python ~/test_hvd.py
```

And get output like this: 
```
/users/wliu8/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py
0.12.1
Attempting to use an MPI routine after finalizing MPI
```

The last line `Attempting to use an MPI routine after finalizing MPI` seem an error because of the `hvd.init()`. 

I'm using the latest hvd library from master branch. 

I'm on CentOS 7.4, and my MPI is Intel MPI library version 2018, update 1.

**Comment by alsrgv** [comment]
@weiliu620, there's a PR #218 that will allow passing an option to Horovod to not re-initialize MPI.  For now, you can follow the example here https://github.com/uber/horovod#mpi4py that shows how to tell mpi4py to skip initialization.
