### ISSUE TITLE
the nccl versions between building and using are different

### ISSUE THREAD

**Issue by wuyujiji** [horovod/horovod#2561]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) PyTorch
2. Framework version: PyTorch1.4.0
3. Horovod version:0.19.2
4. MPI version:4.0.0
5. CUDA version:10.0
6. NCCL version:2.7.8
7. Python version:3.6.8
8. GCC version:5.3.1

**Your question:**
Excuse me!  I build the horovod with nccl2.7.8 version, but when I use `NCCL_DEBUF=INFO` to print nccl log and find the output nccl version is 2.4.8, it feels like  the pytorch's original nccl version, and I do not know why.

**Comment by chongxiaoc** [comment]
It seems that you have two nccl versions on the system, and the one linked with pytorch (nccl 2.4.8) is placed in more preferred path.

What if you set `LD_LIBRARY_PATH` to have `nccl2.7.8` in the first, then run again?

**Comment by wuyujiji** [comment]
I set `LD_LIBRARY_PATH` to nccl2.7.8, but the output is still `nccl2.4.8`.  However，when I run the `horovod.tensorflow `demo, the output show the `nccl2.7.8`.

**Comment by chongxiaoc** [comment]
It looks like a pytorch issue.
Pytorch is not support with `2.7.8` internally.
See pytorch issue here:
https://github.com/pytorch/pytorch/issues/35363
