### ISSUE TITLE
Does Horovod support multithread job submission 

### ISSUE THREAD

**Issue by OscarDPan** [horovod/horovod#2563]
I am experimenting with Horovod on Spark(Keras) and I wanted to use python's ThreadPoolExecutor to submit multiple training jobs. However I bumped into an issue during Gloo runner's register_shutdown_event() where it says "signal only works in main thread".

I suspect it's because I used ThreadPoolExecutor to submit the training job and Signal doesn't like it. Is there a way to circumvent this?

**Comment by tgaddair** [comment]
Hey @OscarDPan, are you using `horovod.run` to launch the jobs in each thread?  You may want to try using a multiprocessing executor instead of a thread pool.

**Comment by OscarDPan** [comment]
Hi @tgaddair,

I used KerasEstimator to train on spark dataframe and I am only using CPU.
Ideally I'd want to use threadPoolExecutor to submit multiple spark/horovod training jobs in one sparkContext.

Any suggestion?

**Comment by tgaddair** [comment]
Hey @OscarDPan, did you try this with MPI?  There may be a way to do this using MPI subcommunicators.
