### ISSUE TITLE
Release pre-compiled binaries

### ISSUE THREAD

**Issue by eaplatanios** [horovod/horovod#257]
Hi,

I was wondering if there is any chance you guys can release pre-compiled binaries so that the custom ops library you have developed can be used by other libraries (in my case, [TensorFlow Scala](https://github.com/eaplatanios/tensorflow_scala)). I would be more than happy to support and use Horovod in TensorFlow Scala, if the pre-compiled binaries were somehow available. :)

Thanks,
Anthony

**Comment by alsrgv** [comment]
@eaplatanios, unfortunately, it's hard to release pre-compiled binaries - everyone has a different version of MPI, TensorFlow, and NCCL.  Can you elaborate more on how does the absence of pre-compiled binaries make your life harder?

**Comment by alsrgv** [comment]
Perhaps this may interest you - https://hub.docker.com/r/uber/horovod
