### ISSUE TITLE
Reworking test space combinations

### ISSUE THREAD

**Issue by EnricoMi** [horovod/horovod#2570]
The buildkite pipeline currently tests the following parameter combinations:

|processor|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|cpu|openmpi_gloo|py3_6|tf1_15_0|keras2_2_4|torch1_2_0|mxnet1_4_1|pyspark2_3_2|
|cpu|gloo|py3_6|tf2_0_0|keras2_2_4|torch1_3_0|mxnet1_4_1|pyspark2_3_2|
|cpu|openmpi|py3_6|tf2_1_0|keras2_2_4|torch1_4_0|mxnet1_4_1|pyspark2_4_7|
|cpu|openmpi|py3_6|tf2_2_0|keras2_3_1|torch1_5_0|mxnet1_5_0|pyspark2_4_7|
|cpu|gloo|py3_7|tf2_3_1|keras2_3_1|torch1_6_0|mxnet1_5_0|pyspark2_4_7|
|cpu|gloo|py3_8|tf2_4_0|keras2_3_1|torch1_7_1|mxnet1_5_0|pyspark3_0_1|
|cpu|openmpi|py3_6|tfhead|kerashead|torchhead|mxnethead|pyspark2_4_7|
|cpu|mpich|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|oneccl|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|oneccl_ofi|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|gpu|openmpi|py3_6|tf1_15_0|keras2_2_4|torch1_3_0|mxnet1_4_1|pyspark2_4_7|
|gpu|gloo|py3_6|tf2_0_0|keras2_3_1|torch1_4_0|mxnet1_4_1|pyspark2_4_7|
|gpu|openmpi|py3_6|tf2_3_1|keras2_3_1|torch1_6_0|mxnet1_6_0|pyspark2_4_7|
|gpu|openmpi_gloo|py3_6|tf2_4_0|keras2_3_1|torch1_7_1|mxnethead|pyspark2_4_7|
|gpu|openmpi|py3_6|tfhead|kerashead|torchhead|mxnethead|pyspark2_4_7|
|mixed|openmpi|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|

From this, it is not clear why we test which combination of py, tf, keras, torch and mxnet. Is there any dependency between them?

I propose to rework these combinations or at least clearly document where we have dependencies and where we simply pick a combination.

The test space is spawn by these parameters. For each we should define a default value. This set of default values is the base feature axis across the test space:

|processor|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|cpu|gloo|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|

From there, we ideally vary only one dimension at a time, e.g. the python version:
|processor|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|cpu|gloo|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|gloo|py3_7|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|gloo|py3_8|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|

Some dimension (e.g. pyspark3_0_1) may require a specific value for another dimension (e.g. py3_8):

|processor|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|cpu|gloo|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_3_2|
|cpu|gloo|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|gloo|py3_8|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark3_0_0|

The dimensions have the following values in the current test combinations:

|dimension|values|
|:---|:---|
|processor|cpu, gpu, mixed|
|mpi kind|gloo, openmpi, openmpi_gloo, mpich, oneccl, oneccl_ofi|
|python|py3_6, py3_7, py3_8|
|tensorflow|tf1_15_0, tf2_0_0, tf2_1_0, tf2_2_0, tf2_3_0, tfhead|
|keras|keras2_2_4, keras2_3_1, kerashead|
|pytorch|torch1_2_0, torch1_3_0, torch1_4_0, torch1_5_0, torch1_6_0, torchhead|
|mxnet|mxnet1_4_1, mxnet1_5_0, mxnethead|
|pyspark|pyspark2_3_2, pyspark2_4_7, pyspark3_0_1|

This spans a combinatorial space of over 52k test points. Varying only one dimension at a time still spans 25 combinations, more than currently tested.

Dimensions tf, keras, torch and mxnet can be combined to likely or "progressing" combinations, e.g. for cpu:

|tensorflow|keras|pytorch|mxnet|
|:---:|:---:|:---:|:---:|
|tf1_15_0|keras2_2_4|torch1_2_0|mxnet1_4_1|
|tf2_0_0|keras2_3_1|torch1_3_0|mxnet1_4_1|
|tf2_1_0|keras2_3_1|torch1_4_0|mxnet1_5_0|
|tf2_2_0|keras2_3_1|torch1_5_0|mxnet1_5_0|
|tf2_3_0|keras2_3_1|torch1_6_0|mxnet1_6_0|
|tfhead|kerashead|torchhead|mxnethead|

For gpu we currently vary tf along with torch and mxnet and fix keras, but different combinations than for cpu:
|tensorflow|pytorch|mxnet|
|:---:|:---:|:---:|
|tf1_15_0|torch1_3_0|mxnet1_4_1|
|tf2_0_0|torch1_4_0|mxnet1_4_1|
|tf2_2_0|torch1_5_0|mxnet1_4_1|
|tf2_3_0|torch1_6_0|mxnet1_6_0|
|tfhead|torchhead|mxnethead|

The gpu versions of torch and mxnet could be aligned with cpu combinations, or they could differ on purpose to allow for testing other combinations.

The processor mixed tests only a single combination right now. That should be the default values for all other dimensions.

Dimensions python and pyspark can be combined, though there is no strict dependency (other than pyspark3_0_1 -> py3_8):
|python|pyspark|
|:---:|:---:|
|py3_6|pyspark2_2_3|
|py3_7|pyspark2_4_7|
|py3_8|pyspark3_0_1|

This brings us to 21 combinations, more than we currently have, but well defined:

|processor|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|cpu|openmpi-gloo|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
||
|cpu|gloo|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|openmpi|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|mpich|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|oneccl|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|oneccl_ofi|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
||
|cpu|gloo|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_2_3|
|cpu|gloo|py3_7|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|gloo|py3_8|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark3_0_0|
||
|cpu|gloo|py3_6|tf1_15_0|keras2_2_4|torch1_2_0|mxnet1_4_1|pyspark2_4_7|
|cpu|gloo|py3_6|tf2_0_0|keras2_3_1|torch1_3_0|mxnet1_4_1|pyspark2_4_7|
|cpu|gloo|py3_6|tf2_1_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|
|cpu|gloo|py3_6|tf2_2_0|keras2_3_1|torch1_5_0|mxnet1_5_0|pyspark2_4_7|
|cpu|gloo|py3_6|tf2_3_0|keras2_3_1|torch1_6_0|mxnet1_6_0|pyspark2_4_7|
|cpu|gloo|py3_6|tfhead|torchhead|mxnethead|pyspark2_4_7|
||
|gpu|openmpi_gloo|py3_6|tf1_15_0|keras2_3_1|torch1_3_0|mxnet1_4_1|pyspark2_4_7|
|gpu|gloo|py3_6|tf2_0_0|keras2_3_1|torch1_4_0|mxnet1_4_1|pyspark2_4_7|
|gpu|gloo|py3_6|tf2_2_0|keras2_3_1|torch1_5_0|mxnet1_4_1|pyspark2_4_7|
|gpu|gloo|py3_6|tf2_3_0|keras2_3_1|torch1_6_0|mxnet1_6_0|pyspark2_4_7|
|gpu|gloo|py3_6|tfhead|kerashead|torchhead|mxnethead|pyspark2_4_7|
||
|mixed|openmpi_gloo|py3_6|tf1_15_0|keras2_3_1|torch1_4_0|mxnet1_5_0|pyspark2_4_7|

Open questions:
- Is there a correlation between processor and mpi kind? Do we have to test different mpi kinds with gpu once we have tested them all for cpu?
- Is there a correlation between mpi kind and the (tf, keras, torch, mxnet) space? Otherwise both could be combined, though specific combinations would not make much (more) sense (than others).
- Should openmpi_gloo be the default mpi kind so that both are always tested?
- What is the rational behind gpu,openmpi_gloo tested with mxnet head only, and gpu,openmpi tested with all heads?

**Comment by tgaddair** [comment]
Great idea @EnricoMi!  To answer your questions:

- We shouldn't need to test different MPI versions for GPU, as most of the changes will be handled by NCCL.
- MPI should be decoupled from the frameworks.
- Having both OpenMPI and Gloo gives us the most test coverage, but is also somewhat redundant since we run the same PyTests twice.  I'm leaning towards making Gloo the default and only using MPI for one CPU / one GPU combination.
- The openmpi_gloo for mxnet head was I believe an artifact of replacing a previous test that used openmpi_gloo.  There isn't a good reason to divide the frameworks like that.

**Comment by EnricoMi** [comment]
Which framework combinations would you suggest?

|tensorflow|keras|pytorch|mxnet|
|:---:|:---:|:---:|:---:|
|tf1_15_0|keras2_2_4|torch1_2_0|mxnet1_4_1|
|tf2_0_0|keras2_3_1|torch1_3_0|mxnet1_4_1|
|tf2_1_0|keras2_3_1|torch1_4_0|mxnet1_5_0|
|tf2_2_0|keras2_3_1|torch1_5_0|mxnet1_5_0|
|tf2_3_0|keras2_3_1|torch1_6_0|mxnet1_6_0|
|tfhead|kerashead|torchhead|mxnethead|

Are there any versions that you would like to deprecate to be supported?

Should GPU test with the same combinations? Or a subset?

|tensorflow|keras|pytorch|mxnet|
|:---:|:---:|:---:|:---:|
|tf1_15_0|keras2_2_4|torch1_2_0|mxnet1_4_1|
|tf2_2_0|keras2_3_1|torch1_5_0|mxnet1_5_0|
|tfhead|kerashead|torchhead|mxnethead|

**Comment by tgaddair** [comment]
The CPU list looks good, though I would use the most recent patch version for each minor version (e.g., tf2_3_1), and throw in tf2_4_0 with torch1_7_0 in addition to the versions above.  Additionally, Keras is now deprecated outside of TF, so no need to kerashead (2_3_1 is the last supported version, I believe).

For GPU, we should try to have good coverage of multiple CUDA versions, so something like:

tf1_15_0 = CUDA 10.0
tf2_3_1 = CUDA 10.1
tf2_4_0 = CUDA 11.0
tfhead = CUDA 11.0

**Comment by EnricoMi** [comment]
Latest keras version is 2.4.3, so I presume that is the latest supported version. What replaces keras outside TF?

**Comment by EnricoMi** [comment]
This leads us to these framework combinations for CPU:

|tensorflow|keras|pytorch|mxnet|
|:---:|:---:|:---:|:---:|
|tf1_15_5|keras2_2_4|torch1_2_0|mxnet1_4_1|
|tf2_0_4|keras2_3_1|torch1_3_1|mxnet1_4_1|
|tf2_1_3|keras2_3_1|torch1_4_0|mxnet1_5_1|
|tf2_2_2|keras2_3_1|torch1_5_1|mxnet1_6_0|
|tf2_3_2|keras2_3_1|torch1_6_0|mxnet1_7_0_p1|
|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|
|tfhead|keras2_4_3|torchhead|mxnethead|

And these for GPU:

|tensorflow|keras|pytorch|mxnet|CUDA|
|:---:|:---:|:---:|:---:|:---:|
|tf1_15_5|keras2_2_4|torch1_2_0|mxnet1_4_1|10.0|
|tf2_3_2|keras2_3_1|torch1_6_0|mxnet1_7_0_p1|10.1|
|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|11.0|
|tfhead|keras2_4_3|torchhead|mxnethead|11.0|

I suggest this as our baseline (latest releases everywhere):

|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|gloo|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|3.0.1|

Then we have 19 test permutations as follows (base line with CPU is mention three times):

Our MPI variation:

|processor|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|cpu|gloo|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|
|cpu|openmpi|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|
|cpu|openmpi_gloo|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|
|cpu|mpich|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|
|cpu|oneccl|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|
|cpu|oneccl_ofi|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|

NOTE: MPI kinds other than `gloo` and `openmpi_gloo` should not compile with Gloo so we do not accidentally fall back to Gloo. This is why there is `gloo`, `openmpi` and `openmpi_gloo` for CPU.

Our Python and Spark variation (pyspark 2.2.3 replaced with 2.3.4):

|processor|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|cpu|gloo|py3_6|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_2_3_4|
|cpu|gloo|py3_7|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_2_4_7|
|cpu|gloo|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|

Our framework variation for CPU, GPU and mixed:

|processor|mpi kind|python|tensorflow|keras|pytorch|mxnet|pyspark|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|cpu|gloo|py3_8|tf1_15_5|keras2_2_4|torch1_2_0|mxnet1_4_1|pyspark_3_0_1|
|cpu|gloo|py3_8|tf2_0_4|keras2_3_1|torch1_3_1|mxnet1_4_1|pyspark_3_0_1|
|cpu|gloo|py3_8|tf2_1_3|keras2_3_1|torch1_4_0|mxnet1_5_1|pyspark_3_0_1|
|cpu|gloo|py3_8|tf2_2_2|keras2_3_1|torch1_5_1|mxnet1_6_0|pyspark_3_0_1|
|cpu|gloo|py3_8|tf2_3_2|keras2_3_1|torch1_6_0|mxnet1_7_0_p1|pyspark_3_0_1|
|cpu|gloo|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|
|cpu|gloo|py3_8|tfhead|keras2_4_3|torchhead|mxnethead|pyspark_3_0_1|
||
|gpu|gloo|py3_8|tf1_15_5|keras2_2_4|torch1_2_0|mxnet1_4_1|pyspark_3_0_1|
|gpu|gloo|py3_8|tf2_3_2|keras2_3_1|torch1_6_0|mxnet1_7_0_p1|pyspark_3_0_1|
|gpu|openmpi_gloo|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|
|gpu|gloo|py3_8|tfhead|keras2_4_3|torchhead|mxnethead|pyspark_3_0_1|
||
|mixed|openmpi_gloo|py3_8|tf2_4_1|keras2_4_3|torch1_7_1|mxnet1_7_0_p1|pyspark_3_0_1|

**Comment by leezu** [comment]
>  EnricoMi commented 4 hours ago
> Testing mxnet-1.7.0 is also addressed in #2570.

Thank you @EnricoMi. But the 1.7 wheels do not include the required headers and the test will fail. The upcoming 1.8 release should fix this. I think for now, CI can test 1.6

**Comment by EnricoMi** [comment]
I am using version `mxnet-cu101==1.7.0b20200813` from https://github.com/apache/incubator-mxnet/issues/19575. Good enough until they release a new `1.7.x`.

**Comment by EnricoMi** [comment]
@leezu Horovod tests [pass](https://buildkite.com/horovod/horovod/builds/4783) with `mxnet-cu101==1.7.0b20200813`, so the next 1.7.x release should officially move Horovod to mxnet 1.7.

**Comment by leezu** [comment]
> so the next 1.7.x release should officially move Horovod to mxnet 1.7.

What do you mean?

**Comment by EnricoMi** [comment]
There is currently no mxnet-1.7 release that contains mkldnn headers, so they don't work with horovod: https://github.com/apache/incubator-mxnet/issues/19575.

**Comment by leezu** [comment]
@EnricoMi patched wheels are now available https://github.com/apache/incubator-mxnet/issues/19575#issuecomment-771187700

**Comment by EnricoMi** [comment]
Thanks, I am on it (#2641).
