### ISSUE TITLE
The speed of multi-node is slower than single-node

### ISSUE THREAD

**Issue by Rivendile** [horovod/horovod#2581]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): PyTorch
2. Framework version: 1.0.0
3. Horovod version: 0.16.1
4. MPI version: 
5. CUDA version: 10.0
6. NCCL version: 7.4.5
7. Python version: 2.7
8. OS and version: Ubuntu18.04
9. GCC version: 5.4.0
10. Machine: AWS p3dn.24xlarge (8x V100, bandwidth 100Gbps)

**Your question:**
Hi, I tried to run Horovod on multi-node. When I run on a single machine using code https://github.com/horovod/horovod/blob/master/examples/pytorch/pytorch_synthetic_benchmark.py, the speed is 1531.9 img/sec for 8 GPUs. But when I run on two machines, the speed is 546.9 img/sec for 16 GPUs. I use the following command: horovodrun -np 16 -H localhost:8,3.85.80.174:8 -p 2022 python pytorch_horovod_benchmark.py --model vgg16 --num-batches-per-iter 10 --num-iters 10 --train-dir /home/cluster/data/imagenet
Besides, I use nload to show the network utilization, and it shows 10Gbps only.
Any suggestions? Thanks a lot.

**Comment by chongxiaoc** [comment]
It shouldn't be. Normally per-GPU throughput should keep the same.
You can compare to see is the slowdown comes from inter-node or intra-node:
```
 horovodrun -np 4 -H localhost:4
 horovodrun -np 8 -H localhost:8
 horovodrun -np 8 -H localhost:4,3.85.80.174:4
```

**Comment by chongxiaoc** [comment]
BTW, I just tried with `master` branch.

**Comment by Rivendile** [comment]
@chongxiaoc  Thanks to your reply. I tried  `horovodrun -np 4 -H localhost:4` and get the throughput 814.8 img/sec. I think this shows that the slowdown comes from inter-node. Besides, due to some reasons, I have to use the 0.16.1 version.

**Comment by chongxiaoc** [comment]
I agree some communication bottleneck happens in inter-node communication.

**Comment by Rivendile** [comment]
The machine I used can provide 100Gbps bandwidth. But when I run horovod, it only used 15Gbps. Are there some methods to improve the network utilization?

**Comment by chongxiaoc** [comment]
I think you can benchmark mpi and nccl bandwidth test on this machine.
For mpi, osu benchmark is an option.
