### ISSUE TITLE
ImportError: Extension horovod.torch has not been built:  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

### ISSUE THREAD

**Issue by chauncygu** [horovod/horovod#2589]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

**Comment by tgaddair** [comment]
Hey @chauncygu, did you do what was suggested and reinstall with `HOROVOD_WITH_PYTORCH=1`?  What was the result?

**Comment by chauncygu** [comment]
> Hey @chauncygu, did you do what was suggested and reinstall with `HOROVOD_WITH_PYTORCH=1`? What was the result?

Hi, Thank you for your reply, I have done it as a suggestion, but it still does not work.

**Comment by tgaddair** [comment]
Hey @chauncygu, can you share the full error log so we can take a look?

**Comment by chauncygu** [comment]
> Hey @chauncygu, can you share the full error log so we can take a look?

Hi, Thank you for your help, I have shared the full error log:
(sdriving) andrew@andrew-Precision-3541:~/MySoft20201108$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod
>>> import horovod.torch as hvd
Traceback (most recent call last):
  File "/home/andrew/anaconda3/envs/sdriving/lib/python3.6/site-packages/horovod/torch/__init__.py", line 21, in <module>
    __file__, 'mpi_lib_v2')
  File "/home/andrew/anaconda3/envs/sdriving/lib/python3.6/site-packages/horovod/common/util.py", line 59, in check_extension
    ext_name, full_path, ext_env_var
ImportError: Extension horovod.torch has not been built: /home/andrew/anaconda3/envs/sdriving/lib/python3.6/site-packages/horovod/torch/mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so not found
If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/anaconda3/envs/sdriving/lib/python3.6/site-packages/horovod/torch/__init__.py", line 24, in <module>
    __file__, 'mpi_lib', '_mpi_lib')
  File "/home/andrew/anaconda3/envs/sdriving/lib/python3.6/site-packages/horovod/common/util.py", line 59, in check_extension
    ext_name, full_path, ext_env_var
ImportError: Extension horovod.torch has not been built: /home/andrew/anaconda3/envs/sdriving/lib/python3.6/site-packages/horovod/torch/mpi_lib/_mpi_lib.cpython-36m-x86_64-linux-gnu.so not found
If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

**Comment by chauncygu** [comment]
> Hey @chauncygu, can you share the full error log so we can take a look?

I have tried it according to your suggestion, but it does not work, I hope someone can help me to fix it.
