### ISSUE TITLE
Information from Timeline Framework

### ISSUE THREAD

**Issue by abidmalikwaterloo** [horovod/horovod#259]
I am using the Timeline framework for analyzing Horovod performance. I am using two GPUs. When I visualize it, I don't see any information related to GPU. How can I extract the information related to GPU? I am also attaching the JASON file for your convenience.
[out_put.json.gz](https://github.com/uber/horovod/files/1972059/out_put.json.gz)

**Comment by alsrgv** [comment]
@abidmalik1967, GPU-level information is surfaced at negotiation phase.  E.g. in your example:

![image](https://user-images.githubusercontent.com/16640218/39609194-cec2e068-4efb-11e8-82fd-eeec64696063.png)

Those two ticks under `NEGOTIATE_ALLREDUCE` correspond to ranks that became ready at that time.  You can select them to see which ranks they represent.

In you want to get in-GPU view of all the other computational operations happening, you can use [TensorFlow timeline](https://www.tensorflow.org/performance/xla/jit#step_2_run_without_xla)

**Comment by alsrgv** [comment]
It's actually going to be somewhat overlapped.  Ideally, data IO is happening in a separate thread and is not blocking anything.  A lot of gradient computation usually will happen overlapped with gradient communication (ALLREDUCE).
