### ISSUE TITLE
Dependency links in setup.py causing issues with private registry 

### ISSUE THREAD

**Issue by samj1912** [horovod/horovod#2592]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) all
2. Framework version: n/a
3. Horovod version: 0.20.1+
4. MPI version: n/a
5. CUDA version: n/a
6. NCCL version:
7. Python version:
8. Spark / PySpark version:
9. OS and version:
10. GCC version:
11. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

In horovod 0.20.x the setup.py was updated to add dependency links. Although it says it is removed from pip, it still causes issues in enterprise settings when a private registry is used as pip for some reason tries to connect to download.pytorch.org. This causes horovod versions 0.20.x to be uninstallable as pip just waits for a timeout on these for a long long time. Can we please remove these from the setup.py?

**Comment by samj1912** [comment]
Fwiw Im on pip version 20.3

**Comment by EnricoMi** [comment]
You are talking about these lines?

https://github.com/horovod/horovod/blob/4099c2b7f34f709f0db1c09f06b2594d7b4b9615/setup.py#L179-L185

I will remove them then. Will try to document that elsewhere.
