### ISSUE TITLE
How to specify the parameters in `horovodrun` when using horovod on spark？

### ISSUE THREAD

**Issue by maqy1995** [horovod/horovod#2598]
**Environment:**
1. PyTorch
2. Framework version: 1.6.0
3. Horovod version: 0.21.1
4. MPI version: 4.0.5
5. CUDA version: 10.2
6. NCCL version: 2.7.8
7. Python version: 3.7
8. OS and version: centos7
9. GCC version:

**Your question:**
How to specify the parameters in `horovodrun`(such as `--network-interface`) when using horovod on spark？

**Comment by EnricoMi** [comment]
You are right, the programmatic way to run Horovod on Spark (`horovod.spark.run`) as well as without Spark (`horovod.run`) both are limited compared to `horovodrun`. You can see all options in [horovod/spark/runner.py](https://github.com/horovod/horovod/blob/master/horovod/spark/runner.py).

https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/spark/runner.py#L195-L218

The last argument `nics` refers to `--network-interface`. If you need anything else, more arguments would be needed to populate `Settings`: https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/spark/runner.py#L234-L239

**Comment by EnricoMi** [comment]
You are right, the programmatic way to run Horovod on Spark (`horovod.spark.run`) as well as without Spark (`horovod.run`) both are limited compared to `horovodrun`. You can see all options in [horovod/spark/runner.py](https://github.com/horovod/horovod/blob/master/horovod/spark/runner.py).

https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/spark/runner.py#L195-L218

The last argument `nics` refers to `--network-interface`. If you need anything else, more arguments would be needed to populate `Settings`: https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/spark/runner.py#L234-L239

**Comment by maqy1995** [comment]
Thank you for your reply.
I use torchEstimator, and `horovod.spark.run` seems is called in code below, which parameters like `nics` not be set. 
https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/spark/torch/estimator.py#L279-282
If I want to use this parameter, do I need to modify this part of the source code?

**Comment by EnricoMi** [comment]
You are right, the programmatic way to run Horovod on Spark (`horovod.spark.run`) as well as without Spark (`horovod.run`) both are limited compared to `horovodrun`. You can see all options in [horovod/spark/runner.py](https://github.com/horovod/horovod/blob/master/horovod/spark/runner.py).

https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/spark/runner.py#L195-L218

The last argument `nics` refers to `--network-interface`. If you need anything else, more arguments would be needed to populate `Settings`: https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/spark/runner.py#L234-L239

**Comment by EnricoMi** [comment]
If `horovod.spark.run` has all arguments that you need, then you can pass those arguments by providing a backend instance to the TorchEstimator like:

    backend = SparkBackend(use_gloo=True, nics=['eth0'])
    torch_estimator = hvd.TorchEstimator(..., backend=backend, ...)

https://github.com/horovod/horovod/blob/a9dea74abc1f0b8e81cd2b6dd9fe81e2c4244e39/horovod/spark/common/backend.py#L56-L65

**Comment by maqy1995** [comment]
get, thanks again for your reply！
