### ISSUE TITLE
Cmake failed [WinError 5] Access is denied

### ISSUE THREAD

**Issue by trikiamine23** [horovod/horovod#2599]
**Environment:**
1. Framework: TensorFlow, Keras
2. Framework version: last
3. Horovod version: last
4. MPI version: v10
5. CUDA version: 11.2
6. NCCL version: no NCCL (windows)
7. Python version: 3.7 / 3.8
8. Spark / PySpark version: No
9. OS and version: Windows server 2016/2019
10. GCC version: 8.3.0
11. CMake version: 3.19.2

**Bug report:**
this is the error I get when I try to install horovod : pip install horovod[tensorflow,keras]
`
 File "C:\Users\AMINE\AppData\Local\Temp\2\pip-install-0q21sm8i\horovod\setup.py", line 93, in build_extensions
        raise RuntimeError('CMake failed: {}'.format(str(e)))
    RuntimeError: CMake failed: [WinError 5] Access is denied
`
Is this a normal behaviour ? I am administrator in the machine

**Comment by tgaddair** [comment]
Hey @trikiamine23, looks you're running on a Windows machine, correct?  At this time, Horovod is not supported on Windows.

**Comment by trikiamine23** [comment]
thank you for your response. Is there any project for that ?
Any framework that works with windows ?

**Comment by tgaddair** [comment]
Hey @trikiamine23, I am not aware of any personally, though I will say that Windows support is something we would like to support, in case you know of any Windows devs who would be interested in contributing.
