### ISSUE TITLE
All MPI Processes running all GPUs

### ISSUE THREAD

**Issue by raj-brown** [horovod/horovod#2610]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version: TensorFlow
3. Horovod version:0.19.1
4. MPI version: 4.0.0
5. CUDA version:10.0.130
6. NCCL version:
7. Python version:3.6
8. OS and version:linux
9. GCC version:8.3

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

I am trying to run my code 4 mpi process and each process mapping to one GPU. Code runs but when I see the output of nvidia-smi the all the 4 processes are bound to each of the 4GPUs.
I am using 
```mpirun -np 4 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python3 -u xPINN    _2D_GPU.py```

I was of the view that one cpu processe will attched to One GPU. I will really appreciate your help.

Thanks!

**Comment by chongxiaoc** [comment]
What if you run with `horovodrun`?

**Comment by raj-brown** [comment]
@chongxiaoc No It runs same does not change.

**Comment by chongxiaoc** [comment]
sorry I misunderstood your quesiton.
The above scenario should be correct, `horovod` doesn't pin any GPUs to a particular process.

Instead, `hovorod` uses `local_rank` to assign GPU distribution.

See the example of `pytorch_mnist.py`:
https://github.com/horovod/horovod/blob/b794659cb9c70703678326633cb0a7538914dfa2/examples/pytorch/pytorch_mnist.py#L120
