### ISSUE TITLE
How does horovod distribute (TF) datasets?

### ISSUE THREAD

**Issue by Flamefire** [horovod/horovod#2623]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.4.0
3. Horovod version: 0.21.1

**Your question:**

I'm running horovod on a cluster via SLURMs `srun` (which IIUC is equivalent to `horovodrun`)

From reading the documentation I do not understand exactly how horovod distributes data (the samples/labels). When using a TensorFlow 2 "strategy" one increases the batch_size (in `dataset.batch(...)`)  by `strategy.num_replicas_in_sync` and adjusts the learning rate by the same amount. TF will then split this large batch into a small batch per replica

Looking at the horovod samples and description this is not clear to me. The linked article at https://spell.ml/blog/distributed-model-training-using-horovod-XvqEGRUAACgAa5th says:
> In data parallelization, each GPU in the job receives its own independent slice of the data batch

This sounds like the batch is split. However the horovod docs say
> Effective batch size in synchronous distributed training is scaled by the number of workers

This sounds like more like what you expect from MPI applications: As each process is "independent" each gets a batch of the same size the total size is what was passed to `dataset.batch` times the number of processes/workers.

The example then has `for batch, (images, labels) in enumerate(dataset.take(10000 // hvd.size())):` which then also makes sense.

From this I conclude that horovod does not distribute data at all and indeed if fixing `tf.random.set_seed` all replicas see the exact same data which means you don't get any increased learning speed by the parallel execution as all run the same calculations with the same data.

This sounds like a serious caveat as I'd guess at least for model design evaluation data scientists would use `tf.random.set_seed` to be able to compare the training process (e.g. when tuning hyper-parameters).

So I think this should be mentioned in the docs somewhere prominent, especially as the dataset distribution in e.g. TF is automatic (by splitting up the scaled-up batch). Maybe it's also possible to only use every n-th element and shuffle-seeds get synchronized.

**Comment by tgaddair** [comment]
Hey @Flamefire, when using Horovod you want to have every Horovod worker operate on an independent partition of the dataset.  This can be achieved with TF datasets using the [shard](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shard) function.  For example:

```
tf.data.Dataset(...).shard(num_shards=hvd.size(), index=hvd.rank())
```

There is some confusion over the meaning of "batch size" in distributed training.  We typically distinguish between the "local batch size" (per worker / GPU) and the "total" or "effective batch size", which takes into consideration all the local batches across all the workers.  So from the TF dataset perspective, it is also working in terms of the local batch size, which does not change with the number of workers.

**Comment by Flamefire** [comment]
I figured that and that's indeed what I meant with my last sentence, just didn't know about the `shard` function yet.

I think it makes sense to put this information somewhere prominent in the docs and use this in the examples. I really searched hard for this but wasn't able to find anything and the TF examples simply shuffle the whole dataset, so that works likely OK when all workers have different seeds.

**Comment by tgaddair** [comment]
Yes, I agree this should be documented somewhere in an example / the TensorFlow guide.  I'll mark this as a doc update request so we can track it.

**Comment by jom317** [comment]
@tgaddair I would agree with this. While looking out for example script in the documentation, I was really confused with how the dataset should be handled. The `shard` function makes sense now. However, I have a question, so if for example, I have 4 ranks each with 8 gpus (total 32 GPUs), I am using `shard` to split the dataset over 4 ranks ( I suppose) and then use shuffle and batch function to split the subset of the data in each rank (split over 8 GPUs)... Does this make sense? 

In that context, I would also like to make sure the following. I have a tensorflow model which I trained using 1 node (8 GPUs) where the optimal batch size was considered to be 128 while using tensorflow MirroredStrategy. So I guess now with the shard-ed datasets for each worker, I would still be able to use the 128 batch size as that does remain the same for each rank. Please let me know if I am wrong. Thanks.

**Comment by Flamefire** [comment]
> I am using shard to split the dataset over 4 ranks ( I suppose) and then use shuffle and batch function to split the subset of the data in each rank (split over 8 GPUs

This has 2 issues: sharding first means, that each rank will see a deterministic part of the data which may affect training performance. Secondly I had issues mixing horovod and TF distribution and reverted to 1 GPU/rank when using horovod

> I would still be able to use the 128 batch size as that does remain the same for each rank

This depends what you meant by "optimal". If you mean training performance (not runtime performance) you should make sure, the global batch size stays the same, i.e. divide the 128 by the number of ranks. As this becomes too small soon, you should try adjusting the learning rate to cater for bigger batch sizes.

**Comment by jom317** [comment]
@Flamefire Thanks for response. I have not mixed TF distribute and horovod...So what I am trying to is using horovod to do the whole thing over 32 gpus distributed in 4 ranks. While I am starting the training.py script I am sharding the dataset and then sending deterministic subset of the dataset to each of the rank...Are you sure that is going to have issues with training, as, what I understood from horovod is that, when we use the hvd `DistributedOptimizer` horovod does global all-reduce to take care my network is actually able to see all the data through the 4 ranks...If I do not shard, on the contrary, the network might see same data over and over again. I am not sure if I am wrong....

**Comment by tgaddair** [comment]
Hey @jom317, generally you would want to shard reshard the data each epoch to decrease the chance of examples ending up in the same batches repeatedly. Depending on your model, you may not have an issues if you only shard the data once (which has the beneficial property of reducing network overhead), but we've definitely seen cases where the model was very sensitive to these issues. And of course, the more workers you have, the fewer examples per worker, which increases the odds your batches are going to repeat. So my suggestion would be to try your approach and see how the model performs, if you find that convergence is a lot worse, then we may need to consider ways to better distribute the data.

**Comment by jom317** [comment]
Thanks @tgaddair  for your response. Currently I am facing another issue while trying to to run horovod. So I have a setup where I have data stored in h5 files. In the python script, I initially load the h5 files and then create tf datasets (plan is to augment the data as well through the tf dataset.map). However, when I run the script in 2 nodes with 8 v100 GPUs/node, i ran into out of memory issues. My training dataset size in h5 file is ~ 60GB and validation data is ~ 8 GB. Just to understand what is happening, I tried to just use 1000 images from the training dataset and it still gives me same out of memory error from all the GPUs. I am not sure if I am doing something wrong with initial data loading which is making a lot of copies of the same data in different GPUs. Here is the snippet of the script which loads and creates the tf dataset and shard it... I have attached the batch slurm script as well for your reference.

if __name__ == '__main__':
    print("Initializing Horovod ... \n")
    hvd.init()

    if hvd.rank() == 0:
        print('Size of the training, validation and test dataset: \n')
        print(training_probe.shape)
        print(val_probe.shape)
        print(test_probe.shape)

        print("Successfully started Horovod ... \n ")
        print("local ranks are : {}".format(hvd.local_rank()))

    # Pin GPU to be used to process local rank (one GPU per process)
    gpus = tf.config.experimental.list_physical_devices('GPU')
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)
    if gpus:
        tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], 'GPU')


    if hvd.rank() == 0:
        print("size of the available workers is : {}".format(hvd.size()))


    trainData = h5py.File('../h5Training/unrotated_train_small.hdf5','r')
    testData = h5py.File('../h5Training/unrotated_test_small.hdf5','r')

    training_cbed = np.array(trainData.get('cbed').get('cbed_data'))
    training_probe = np.array(trainData.get('probe').get('probe_data'))
    training_pot = np.array(trainData.get('pot').get('pot_data'))

    val_cbed = np.array(testData.get('cbed').get('cbed_data')
    val_probe = np.array(testData.get('probe').get('probe_data')
    val_pot = np.array(testData.get('pot').get('pot_data')

 #Dataset initialization
    #Batch size will vary with hvd.size()
    BATCH_SIZE = 8
    SHUFFLE_BUFFER_SIZE = training_cbed.shape[0] // 10

    train_dataset = tf.data.Dataset.from_tensor_slices(((training_cbed, training_probe), training_pot))
    val_dataset = tf.data.Dataset.from_tensor_slices(((val_cbed, val_probe), val_pot))
    #test_dataset = tf.data.Dataset.from_tensor_slices(((test_cbed, test_probe), test_pot))

    train_dataset = train_dataset.shard(hvd.size(), hvd.rank())
    val_dataset = val_dataset.shard(hvd.size(), hvd.rank())
    #test_dataset = test_dataset.shard(hvd.size(), hvd.rank())

    train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)
    val_dataset = val_dataset.batch(BATCH_SIZE)
    #test_dataset = test_dataset.batch(BATCH_SIZE)

**I am deleting the numpy arrays just to release the memory**

    del training_cbed
    del training_probe
    del training_pot
    del val_cbed
    del val_probe
    del val_pot


**HERE is the Slurm script**

#!/bin/bash
#SBATCH -C gpu
#SBATCH -c 10
#SBATCH --nodes 2
#SBATCH --ntasks-per-node 8
#SBATCH --gpus-per-task 1
#SBATCH --exclusive
#SBATCH -t 00:30:00
#SBTACH -J horovod_tf_multinode
#SBATCH -o hvd_tf_complex_cnn.out
#SBATCH -e hvd_tf_complex_cnn.err

#set up modules
module load cgpu
module load python

conda activate tf-v2.4.1-gpu

#set up environment
export HOROVOD_GPU_ALLREDUCE=NCCL #MPI <nccl should work and shoudld be faster>
export HOROVOD_GPU_ALLGATHER=NCCL #MPI
export HOROVOD_GPU_BROADCAST=NCCL #MPI
set -x 

#run job
echo "Job started at: "
date
srun -l -u python -u 4Dcrystal_unet_complex_spectral_horovod_version8.py
echo "Job finished at: "
date

**Comment by tgaddair** [comment]
Hey @jom317, how are you restricting the training to 1000 images? Is it possible that you're actually reading the whole dataset into memory first? Also, bear in mind that when running 8 Horovod workers per node, you will be using 8x the memory of a single worker.

**Comment by niranjansuthar70** [comment]
Hello @tgaddair , I have also some concerns in dataset splitting with while using horovod.
So in my case I am using 8 individual workers each with 1 GPU and I have shared a folder with` train.py `and dataset using` NFS` lets say directory `storage`. Now I didnt use `tf.data.shard ` and ran using `mpirun - np 8 -hosts client1..8 python train.py`. 
1. Will all machines see same set of dataset in each epoch?
2. If I use `tf.data.shard` then will it automatically give different set of dataset in all workers [remember that I am using NFS for dataset and train.py]
3. I did one experiment with 1 worker and 8 workers and here are the results:
a. only 1 worker: 10 mins =  1000 steps
b. 8 workers each with 1 gpu:  10 mins = 700 steps
can you comment on performance that distribution is really working when see those steps comparison?

Thanks

**Comment by Flamefire** [comment]
@niranjansuthar70 
1. Yes. But if you use shuffle, then the order might be different. If you don't use shuffle, your training with 8 workers will likely yield the same result as with 1 worker but is much slower (see 3)
2. Yes
3. As expected: 1 worker doesn't need to communicate and is hence faster. The difference is that 8 workers do 8 times the training, i.e. in your case they basically train 700*8=5600 steps

**Comment by niranjansuthar70** [comment]
Hello @Flamefire  thanks for the response, can you please confirm that does horovod uses internet during training?
I have my all 8 machines at local LAN connected and they have internet connection too. And how do I check inter computers speed?

Thanks

**Comment by tomigee** [comment]
Hi @tgaddair , could we please summarize the key points of this discussion and include them prominently (ideally with examples) in the horovod documentation? I've been searching the internet for days now trying to fix a problem and this thread has. I can't imagine I'm the only one.
