### ISSUE TITLE
Extra processes and extra gpu memory on rank=0

### ISSUE THREAD

**Issue by zhby99** [horovod/horovod#2625]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow
2. Framework version: 1.15.2
3. Horovod version: 0.19.3
4. MPI version: 4.0.0
5. CUDA version: 10.0.130
6. NCCL version: 2.8.3
7. Python version: 3.6
8. OS and version: ubuntu 18.04
9. GCC version: 7.5.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I am training the network using command `horovodrun -np 8 -H localhost:8`, and found that there are several processes on the gpu 0(which is the master node and rank = 0), and they takes a lot gpu memory, I want to know if this is normal, because this would lead to insufficient gpu memory for the model training on rank=0. I pasted the nvidia-smi result below, as you can see rank=0 can only use 13G for training while others can use 16G, and sometimes it will lead to OOM on rank=0.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:08.0 Off |                    0 |
| N/A   36C    P0   180W / 300W |  16083MiB / 16160MiB |     54%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:09.0 Off |                    0 |
| N/A   36C    P0    68W / 300W |  15754MiB / 16160MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:0A.0 Off |                    0 |
| N/A   35C    P0    71W / 300W |  15754MiB / 16160MiB |      7%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:0B.0 Off |                    0 |
| N/A   36C    P0    69W / 300W |  15732MiB / 16160MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:0C.0 Off |                    0 |
| N/A   35C    P0    77W / 300W |  15774MiB / 16160MiB |     56%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:0D.0 Off |                    0 |
| N/A   36C    P0   113W / 300W |  15774MiB / 16160MiB |     40%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:0E.0 Off |                    0 |
| N/A   35C    P0    73W / 300W |  15734MiB / 16160MiB |     45%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:0F.0 Off |                    0 |
| N/A   39C    P0    75W / 300W |  15774MiB / 16160MiB |     59%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     10015      C   python3                         12983MiB |
|    0   N/A  N/A     10016      C   python3                           441MiB |
|    0   N/A  N/A     10017      C   python3                           441MiB |
|    0   N/A  N/A     10018      C   python3                           441MiB |
|    0   N/A  N/A     10019      C   python3                           441MiB |
|    0   N/A  N/A     10020      C   python3                           441MiB |
|    0   N/A  N/A     10021      C   python3                           441MiB |
|    0   N/A  N/A     10022      C   python3                           441MiB |
|    1   N/A  N/A     10016      C   python3                         15749MiB |
|    2   N/A  N/A     10017      C   python3                         15749MiB |
|    3   N/A  N/A     10018      C   python3                         15729MiB |
|    4   N/A  N/A     10019      C   python3                         15769MiB |
|    5   N/A  N/A     10020      C   python3                         15769MiB |
|    6   N/A  N/A     10021      C   python3                         15729MiB |
|    7   N/A  N/A     10022      C   python3                         15769MiB |
+-----------------------------------------------------------------------------+
```

**Comment by zhby99** [comment]
same issue in other machines: 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.88       Driver Version: 418.88       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN RTX           On   | 00000000:01:00.0 Off |                  N/A |
| 49%   69C    P2   123W / 280W |  18762MiB / 24190MiB |     78%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN RTX           On   | 00000000:1B:00.0 Off |                  N/A |
| 47%   67C    P2   125W / 280W |  17265MiB / 24190MiB |     71%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN RTX           On   | 00000000:3E:00.0 Off |                  N/A |
| 46%   66C    P2   123W / 280W |  17265MiB / 24190MiB |     80%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN RTX           On   | 00000000:88:00.0 Off |                  N/A |
| 65%   83C    P2   122W / 280W |  17265MiB / 24190MiB |     77%      Default |
+-------------------------------+----------------------+----------------------+
|   4  TITAN RTX           On   | 00000000:89:00.0 Off |                  N/A |
|100%   88C    P2   114W / 280W |  17265MiB / 24190MiB |     62%      Default |
+-------------------------------+----------------------+----------------------+
|   5  TITAN RTX           On   | 00000000:DA:00.0 Off |                  N/A |
| 65%   82C    P2   153W / 280W |  17266MiB / 24190MiB |     76%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     12516      C   python3                                    17259MiB |
|    0     12517      C   python3                                      297MiB |
|    0     12518      C   python3                                      297MiB |
|    0     12519      C   python3                                      297MiB |
|    0     12520      C   python3                                      297MiB |
|    0     12521      C   python3                                      297MiB |
|    1     12517      C   python3                                    17255MiB |
|    2     12518      C   python3                                    17255MiB |
|    3     12519      C   python3                                    17255MiB |
|    4     12520      C   python3                                    17255MiB |
|    5     12521      C   python3                                    17255MiB |
+-----------------------------------------------------------------------------+

```

**Comment by Quentin-Anthony** [comment]
@zhby99 -- We're seeing similar issues. What was your horovod install command? 

We find that setting HOROVOD_GPU_BROADCAST=[NCCL or MPI] or HOROVOD_GPU_OPERATIONS=[NCCL or MPI] appears to resolve this, but we're still investigating. Does setting this resolve your issue?

**Comment by feevos** [comment]
Same issue here, the solution proposed by @Quentin-Anthony  did not work for me: 


```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  On   | 00000000:04:00.0 Off |                    0 |
| N/A   46C    P0    45W / 300W |  16168MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   43C    P0    53W / 300W |  13601MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   45C    P0    58W / 300W |  13601MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  On   | 00000000:08:00.0 Off |                    0 |
| N/A   50C    P0    57W / 300W |  13589MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     55573      C   python                                     13579MiB |
|    0     55574      C   python                                       859MiB |
|    0     55575      C   python                                       859MiB |
|    0     55576      C   python                                       859MiB |
|    1     55574      C   python                                     13591MiB |
|    2     55575      C   python                                     13591MiB |
|    3     55576      C   python                                     13579MiB |
+-----------------------------------------------------------------------------+

```

mxnet version: mxnet_cu101-2.0.0b20210121
horovod version: 0.21.1
modules list: 

```
Currently Loaded Modulefiles:                                                                                                            
  1) SC                         4) intel-cc/16.0.4.258        7) cudnn/v7.6.4-cuda101      10) openmpi/4.0.0-simple-gcc  13) cmake/3.7.2 
  2) slurm/current              5) intel-fc/16.0.4.258        8) nccl/2.4.8-cuda101        11) hpc-x/2.4.0                               
  3) cuda-driver/current        6) cuda/10.1.168              9) gcc/7.3.0                 12) ninja/1.10.0                              

```

Horovod installation (tried both NCCL or MPI, without square brackets): 

```
HOROVOD_CUDA_HOME=$CUDA_HOME HOROVOD_NCCL_HOME=$NCCL_HOME HOROVOD_GPU_BROADCAST=[NCCL or MPI] HOROVOD_GPU_ALLGATHER=[NCCL or MPI] HOROVOD_GPU_ALLREDUCE=[NCCL or MPI]  HOROVOD_WITH_MXNET=1 pip install -t . --no-cache-dir horovod==0.21.1                                                     
```
Run command (under slurm): 

```
mpirun -np $SLURM_NTASKS  -bind-to none -map-by slot -x HOROVOD_CACHE_CAPACITY  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -mca pml ob1 -mca btl ^openib 
python ./main.py ######## SUCCESSS 

```

full job submission file:

```
#!/bin/bash

### debugging
#SBATCH --nodes=2 # 14
#SBATCH -t 00:20:00  
#SBATCH --cpus-per-task=5
#SBATCH --gres=gpu:4
#SBATCH --ntasks-per-node=4 
#SBATCH --mem=32gb 

##### Number of total processes 
echo " "
echo " Nodelist:= " $SLURM_JOB_NODELIST
echo " Number of nodes:= " $SLURM_JOB_NUM_NODES
echo " NGPUs per node:= " $SLURM_GPUS_PER_NODE 
echo " Ntasks per node:= "  $SLURM_NTASKS_PER_NODE
echo " "

#### Load modules 
module load cuda/10.1.168
module load nccl/2.4.8-cuda101
module load cudnn/v7.6.4-cuda101
module load gcc/7.3.0
module load openmpi/4.0.0-simple-gcc ### Working 
module load hpc-x/2.4.0

module list

source ~/.bashrc

####    Use MPI for communication with Horovod
export HOROVOD_GPU_ALLREDUCE=MPI
export HOROVOD_GPU_ALLGATHER=MPI
export HOROVOD_GPU_BROADCAST=MPI

export HOROVOD_CACHE_CAPACITY=4096

ulimit -s 20480 ####### Horovod recommends 10240 for this

echo "Running on multiple nodes and GPU devices"
echo ""
echo "Run started at:- "
date


mpirun -np $SLURM_NTASKS  -bind-to none -map-by slot -x HOROVOD_CACHE_CAPACITY  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -mca pml ob1 -mca btl ^openib 
python ./main.py ######## SUCCESSS 

echo "Run completed at:- "
date

```

**Comment by tgaddair** [comment]
One thing to try is setting `CUDA_VISIBLE_DEVICES=$OMPI_COMM_WORLD_LOCAL_RANK` before importing TensorFlow (assuming you're using OpenMPI).  With recent versions of NCCL, we no longer need to avoid setting CUDA_VISIBLE_DEVICES.

**Comment by zhby99** [comment]
> @zhby99 -- We're seeing similar issues. What was your horovod install command?
> 
> We find that setting the install flags `HOROVOD_GPU_BROADCAST=[NCCL or MPI]` **or** `HOROVOD_GPU_OPERATIONS=[NCCL or MPI]` appears to resolve this, but we're still investigating. Does setting this resolve your issue?

This does not work for me either. I tried all combinations for the installation.

**Comment by zhby99** [comment]
> One thing to try is setting `CUDA_VISIBLE_DEVICES=$OMPI_COMM_WORLD_LOCAL_RANK` before importing TensorFlow (assuming you're using OpenMPI). With recent versions of NCCL, we no longer need to avoid setting CUDA_VISIBLE_DEVICES.

Thanks @tgaddair this works for me. Now I have same memory usage for all gpus.

p.s. don't forget to comment out `config.gpu_options.visible_device_list = str(hvd.local_rank())` after setting `CUDA_VISIBLE_DEVICES=$OMPI_COMM_WORLD_LOCAL_RANK`.

**Comment by feevos** [comment]
Thanks @tgaddair  setting in the beginning of my python executable: 

```Python
from mpi4py import MPI
rank = MPI.COMM_WORLD.Get_rank()
num_devices=4 # 4 is the number of GPUs available per node. 
local_rank = rank % num_devices  

import os
os.environ['CUDA_VISIBLE_DEVICES']=str(local_rank)
```
and changing 

```
ctx = mx.gpu(hvd.local_rank()) if mx.util.get_gpu_count() > 0 else mx.cpu(hvd.local_rank())
```
to
```
ctx = mx.gpu(0)
```
fixed the problem for me too on mxnet. 

MANY thanks!!!!!

**Comment by Quentin-Anthony** [comment]
> One thing to try is setting `CUDA_VISIBLE_DEVICES=$OMPI_COMM_WORLD_LOCAL_RANK` before importing TensorFlow (assuming you're using OpenMPI). With recent versions of NCCL, we no longer need to avoid setting CUDA_VISIBLE_DEVICES.

Thanks! This worked for us as well. For anyone else wondering, this is the exact patch we used with PyTorch (you can replace MV2_COMM_WORLD_LOCAL_RANK with whatever *_COMM_WORLD_LOCAL_RANK your MPI library uses):

```
diff --git a/examples/pytorch/pytorch_synthetic_benchmark.py b/examples/pytorch/pytorch_synthetic_benchmark.py
index d645a20..e2fc81f 100644
--- a/examples/pytorch/pytorch_synthetic_benchmark.py
+++ b/examples/pytorch/pytorch_synthetic_benchmark.py
@@ -1,9 +1,5 @@
+import os
 import argparse
-import torch.backends.cudnn as cudnn
-import torch.nn.functional as F
-import torch.optim as optim
-import torch.utils.data.distributed
-from torchvision import models
 import horovod.torch as hvd
 import timeit
 import numpy as np
@@ -33,13 +29,20 @@ parser.add_argument('--use-adasum', action='store_true', default=False,
                     help='use adasum algorithm to do reduction')

 args = parser.parse_args()
-args.cuda = not args.no_cuda and torch.cuda.is_available()
+os.environ['CUDA_VISIBLE_DEVICES'] = os.environ.get('MV2_COMM_WORLD_LOCAL_RANK','')

 hvd.init()

+import torch.backends.cudnn as cudnn
+import torch.nn.functional as F
+import torch.optim as optim
+import torch.utils.data.distributed
+from torchvision import models
+
+args.cuda = not args.no_cuda and torch.cuda.is_available()
 if args.cuda:
-    # Horovod: pin GPU to local rank.
-    torch.cuda.set_device(hvd.local_rank())
+    # Horovod: pin GPU to local rank
+    torch.cuda.set_device(0)

 cudnn.benchmark = True
```

**Comment by Quentin-Anthony** [comment]
@tgaddair -- While setting CUDA_VISIBLE_DEVICES fixes the process mapping issue, it disables CUDA IPC, which leads to a significant performance degradations in our experience.

Has NCCL worked around this issue with IPC? Is that what you mean by:

> **With recent versions of NCCL, we no longer need to avoid setting CUDA_VISIBLE_DEVICES.**

If not, will there be a more permanent fix to Horovod that enables CUDA IPC?

**Comment by tgaddair** [comment]
Good question, @Quentin-Anthony.  

@romerojosh, do you have insight into the CUDA IPC question above?

**Comment by romerojosh** [comment]
Hi @Quentin-Anthony. Yes, NCCL works with IPC even with `CUDA_VISIBLE_DEVICES` set, so long as you are using NCCL 2.4.6 or newer and CUDA 10.1. This was not true in prior versions and performance would be degraded if you set `CUDA_VISIBLE_DEVICES` to a subset of GPUs on the node.

**Comment by boydad** [comment]
Is there a permanent solution to this problem rather than a trick with `CUDA_VISIBLE_DEVICES`? It seems additional memory is allocated on zero GPU during the `broadcast_parameters` function. Following code can reproduce the problem
```
import time
import torch
import horovod.torch  as hvd

hvd.init()
torch.cuda.set_device(hvd.local_rank())
torch.set_default_tensor_type(torch.cuda.FloatTensor)

tmp = torch.nn.Linear(100, 110)
hvd.broadcast_parameters(tmp.state_dict(), root_rank=0)

print("Check gpu usage")
time.sleep(100)

```
with horovod=0.22.0 and pytorch=1.9.0a0+git5268b5a

**Comment by StillerPatrick** [comment]
@Quentin-Anthony @tgaddair  How I can resolve that issue with nccl backend. NCCL dornt have enviorment variables like COMM_WORLD_LOCAL_RANK. Can you give me a small snippet how i have to set the CUDA_VISIBLE_DEVICES ?

**Comment by feevos** [comment]
Hi @StillerPatrick  , in mxnet (easy to adapt to pytorch) this works without mpi4py

```python
import os 
import horovod.mxnet as hvd # import horovod.torch as hvd # for pytorch
hvd.init()

os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())

... # More code 

context = mx.gpu(0) # instead of mx.gpu(hvd.local_rank()) 
# In torch this is   
# device = torch.device('cuda:0')

... # Code as usual 


```

Regards

**Comment by StillerPatrick** [comment]
> 
> 
> Hi @StillerPatrick , in mxnet (easy to adapt to pytorch) this works without mpi4py
> 
> ```python
> import os 
> import horovod.mxnet as hvd # import horovod.torch as hvd # for pytorch
> hvd.init()
> 
> os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())
> 
> ... # More code 
> 
> context = mx.gpu(0) # instead of mx.gpu(hvd.local_rank()) 
> # In torch this is   
> # device = torch.device('cuda:0')
> 
> ... # Code as usual 
> ```
> 
> Regards

@feevos  thanks for your fast reply. but whats the purpose of `device = torch.device('cuda:0')` is this line not included in this line ``torch.cuda.set_device(hvd.local_rank())` which is recommended on the readthedocs page of horovod ?

**Comment by feevos** [comment]
Hi @StillerPatrick, 

when you set ```os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())``` in the beginning, means that the worker sees only a single gpu. When it starts counting, this will always have the id value of zero. Therefore, you need to manually say to the worker that the device used (e.g. with ```net.to(device)``` ) in the computations, is the one that it sees, and that's 0. At least, this is my understanding. If you use hvd.local_rank() instead of 0, the ID will be different than the device used (except first gpu at ID = 0) and you should get an error. You can use hvd.local_rank() in the case where the cuda visible devices is a list of strings, corresponding to the list of gpus, but in this case, all gpus are visible from all workers which is different than the hack here. And saying again, this is my (perhaps limited) understanding of the issue. 

The above procedure is working on mxnet versions of the code, I haven't tested with pytorch, but I don't see a reason why it may not work. 

Regards

**Comment by StillerPatrick** [comment]
Hi @feevos,

thanks foru your explaination. That helped me a lot.

With kind regards,
Patrick

**Comment by TiankaiHang** [comment]
> > Hi @StillerPatrick , in mxnet (easy to adapt to pytorch) this works without mpi4py
> > ```python
> > import os 
> > import horovod.mxnet as hvd # import horovod.torch as hvd # for pytorch
> > hvd.init()
> > 
> > os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())
> > 
> > ... # More code 
> > 
> > context = mx.gpu(0) # instead of mx.gpu(hvd.local_rank()) 
> > # In torch this is   
> > # device = torch.device('cuda:0')
> > 
> > ... # Code as usual 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Regards
> 
> @feevos thanks for your fast reply. but whats the purpose of `device = torch.device('cuda:0')` is this line not included in this line `torch.cuda.set_device(hvd.local_rank())` which is recommended on the readthedocs page of horovod ?

But could this be useful for multi-node training?

**Comment by TiankaiHang** [comment]
> same issue in other machines:
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 418.88       Driver Version: 418.88       CUDA Version: 10.1     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  TITAN RTX           On   | 00000000:01:00.0 Off |                  N/A |
> | 49%   69C    P2   123W / 280W |  18762MiB / 24190MiB |     78%      Default |
> +-------------------------------+----------------------+----------------------+
> |   1  TITAN RTX           On   | 00000000:1B:00.0 Off |                  N/A |
> | 47%   67C    P2   125W / 280W |  17265MiB / 24190MiB |     71%      Default |
> +-------------------------------+----------------------+----------------------+
> |   2  TITAN RTX           On   | 00000000:3E:00.0 Off |                  N/A |
> | 46%   66C    P2   123W / 280W |  17265MiB / 24190MiB |     80%      Default |
> +-------------------------------+----------------------+----------------------+
> |   3  TITAN RTX           On   | 00000000:88:00.0 Off |                  N/A |
> | 65%   83C    P2   122W / 280W |  17265MiB / 24190MiB |     77%      Default |
> +-------------------------------+----------------------+----------------------+
> |   4  TITAN RTX           On   | 00000000:89:00.0 Off |                  N/A |
> |100%   88C    P2   114W / 280W |  17265MiB / 24190MiB |     62%      Default |
> +-------------------------------+----------------------+----------------------+
> |   5  TITAN RTX           On   | 00000000:DA:00.0 Off |                  N/A |
> | 65%   82C    P2   153W / 280W |  17266MiB / 24190MiB |     76%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0     12516      C   python3                                    17259MiB |
> |    0     12517      C   python3                                      297MiB |
> |    0     12518      C   python3                                      297MiB |
> |    0     12519      C   python3                                      297MiB |
> |    0     12520      C   python3                                      297MiB |
> |    0     12521      C   python3                                      297MiB |
> |    1     12517      C   python3                                    17255MiB |
> |    2     12518      C   python3                                    17255MiB |
> |    3     12519      C   python3                                    17255MiB |
> |    4     12520      C   python3                                    17255MiB |
> |    5     12521      C   python3                                    17255MiB |
> +-----------------------------------------------------------------------------+
> ```

Hi, have you tried the method on multi-node training?

**Comment by feevos** [comment]
> > > Hi @StillerPatrick , in mxnet (easy to adapt to pytorch) this works without mpi4py
> > > ```python
> > > import os 
> > > import horovod.mxnet as hvd # import horovod.torch as hvd # for pytorch
> > > hvd.init()
> > > 
> > > os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())
> > > 
> > > ... # More code 
> > > 
> > > context = mx.gpu(0) # instead of mx.gpu(hvd.local_rank()) 
> > > # In torch this is   
> > > # device = torch.device('cuda:0')
> > > 
> > > ... # Code as usual 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Regards
> > 
> > 
> > @feevos thanks for your fast reply. but whats the purpose of `device = torch.device('cuda:0')` is this line not included in this line `torch.cuda.set_device(hvd.local_rank())` which is recommended on the readthedocs page of horovod ?
> 
> But could this be useful for multi-node training?

Yes, I have used it with SLURM in CSIRO HPC cluster, training models with up to 40 nodes (each x4 GPUs). 

Regards

**Comment by TiankaiHang** [comment]
> > > > Hi @StillerPatrick , in mxnet (easy to adapt to pytorch) this works without mpi4py
> > > > ```python
> > > > import os 
> > > > import horovod.mxnet as hvd # import horovod.torch as hvd # for pytorch
> > > > hvd.init()
> > > > 
> > > > os.environ['CUDA_VISIBLE_DEVICES'] = str(hvd.local_rank())
> > > > 
> > > > ... # More code 
> > > > 
> > > > context = mx.gpu(0) # instead of mx.gpu(hvd.local_rank()) 
> > > > # In torch this is   
> > > > # device = torch.device('cuda:0')
> > > > 
> > > > ... # Code as usual 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Regards
> > > 
> > > 
> > > @feevos thanks for your fast reply. but whats the purpose of `device = torch.device('cuda:0')` is this line not included in this line `torch.cuda.set_device(hvd.local_rank())` which is recommended on the readthedocs page of horovod ?
> > 
> > 
> > But could this be useful for multi-node training?
> 
> Yes, I have used it with SLURM in CSIRO HPC cluster, training models with up to 40 nodes (each x4 GPUs).
> 
> Regards

Hi,

Thanks for your reply!
You mean that you didn't start your process with `mpirun` or `horovodrun` ?

I have made each gpu see its own gpu. However, there's something wrong with hvd.local_rank(). 
![image](https://user-images.githubusercontent.com/52823230/135006059-db924409-d4df-4159-b155-66e9bc62d9e8.png)
![image](https://user-images.githubusercontent.com/52823230/135006081-22c0a769-e2c4-41b1-a290-04a7898437ba.png)

Any sugestions?

Best.

**Comment by feevos** [comment]
Hi @TiankaiHang , I cannot understand with the information provided what may be going wrong. In my case the launch is done with mpirun (horovodrun is a wrapper of the mpirun), and the communication of the machines is handled by SLURM in ways I do not fully understand to be honest. But the point is that I am using the same command to run my code be it on a single node with N gpus or with M nodes, each having N gpus. The only difference is the number of processes specified on the mpirun command. 

```
mpirun -np $SLURM_NTASKS  -bind-to none -map-by slot -x HOROVOD_CACHE_CAPACITY  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -mca pml ob1 -mca btl ^openib python ./main.py
```

This works for me.

**Comment by TiankaiHang** [comment]
> Hi @TiankaiHang , I cannot understand with the information provided what may be going wrong. In my case the launch is done with mpirun (horovodrun is a wrapper of the mpirun), and the communication of the machines is handled by SLURM in ways I do not fully understand to be honest. But the point is that I am using the same command to run my code be it on a single node with N gpus or with M nodes, each having N gpus. The only difference is the number of processes specified on the mpirun command.
> 
> ```
> mpirun -np $SLURM_NTASKS  -bind-to none -map-by slot -x HOROVOD_CACHE_CAPACITY  -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH  -mca pml ob1 -mca btl ^openib python ./main.py
> ```
> 
> This works for me.

Hi,

I submit a job with 4 gpus per node (2 nodes). If i changed nothing, there will be extra process like that in this issue thread. Then i follow the suggestions above. (set CUDA_VISIBLE_DEVICES as hvd.local_rank() at the beginning, set_device(0)). The extra process disappeared.

However, one node with 4 gpus worked well. On another node, each gpu should have its own process. I found that one gpu is idle and one gpu have two processes. That's so weird.

I hope I make the question clear to understand.

Best.

**Comment by surak** [comment]
I have a problem with this in the sense that my versions of horovod started showing me the wrong local rank. It's always zero now and codes I had running stopped. The sysadmins don't know what failed. MPI, NCCL and Horovod are all unchanged.

I do this:
```python
print("DEBUG Horovod Local rank:%d | OpenMPI local rank: %s |  COMM_WORLD rank: %s | Horovod rank: %s" % (hvd.local_rank(),os.environ["OMPI_COMM_WORLD_LOCAL_RANK"], MPI.COMM_WORLD.rank, hvd.rank() ))
```

The last time I tried this some months ago, horovod local rank match the mpi one. Now, it's always zero. This is for 2 nodes with 4 mpi tasks:

```
DEBUG Horovod Local rank:0 | OpenMPI local rank: 2 |  COMM_WORLD rank: 6 | Horovod rank: 6
DEBUG Horovod Local rank:0 | OpenMPI local rank: 0 |  COMM_WORLD rank: 0 | Horovod rank: 0
DEBUG Horovod Local rank:0 | OpenMPI local rank: 1 |  COMM_WORLD rank: 1 | Horovod rank: 1
DEBUG Horovod Local rank:0 | OpenMPI local rank: 3 |  COMM_WORLD rank: 7 | Horovod rank: 7
DEBUG Horovod Local rank:0 | OpenMPI local rank: 3 |  COMM_WORLD rank: 3 | Horovod rank: 3
DEBUG Horovod Local rank:0 | OpenMPI local rank: 0 |  COMM_WORLD rank: 4 | Horovod rank: 4
DEBUG Horovod Local rank:0 | OpenMPI local rank: 2 |  COMM_WORLD rank: 2 | Horovod rank: 2
DEBUG Horovod Local rank:0 | OpenMPI local rank: 1 |  COMM_WORLD rank: 5 | Horovod rank: 5
```

My question is: how does horovod determine the local rank?
