### ISSUE TITLE
Wrong default for horovod.tensorflow.keras.allreduce(average...

### ISSUE THREAD

**Issue by Flamefire** [horovod/horovod#2627]
In Horovod 0.21.1 the default for `average` in `allreduce` is still `True` leading to 

> ValueError: The op parameter supersedes average. Please provide only one of them.

when using `op=...` (only).

This is only in in `horovod.tensorflow.keras`, not in `horovod.tensorflow`

BTW: In TF2, is there any benefit of using `horovod.tensorflow.keras` over `horovod.tensorflow` when not disabling eager execution (which in my tests is pretty much unfeasible)

**Comment by yuduber** [comment]
Hi Flamefire,

Thanks for reporting the bug.  I am here to help with a fix.  May I know the steps to repro this bug?  And if you can provide your running environment, that will be helpful as well.

**Comment by Flamefire** [comment]
As written the function `horovod.tensorflow.keras.allreduce` has a default value of `allreduce=True` while it should be `None`. To "reproduce" it is enough to look at the source code and compare e.g.:
https://github.com/horovod/horovod/blob/2f154afad39a0ef6d4f337a0da7e422d43961325/horovod/tensorflow/keras/__init__.py#L122
https://github.com/horovod/horovod/blob/2f154afad39a0ef6d4f337a0da7e422d43961325/horovod/tensorflow/__init__.py#L54

If you check the condition when the quoted error is shown it should be clear why `None` is correct here and why it fails when you pass any `op` to `horovod.tensorflow.keras.allreduce` : https://github.com/horovod/horovod/blob/994913a2abc5812042a5c3540ced5b3316d23b72/horovod/common/util.py#L230-L232

**Comment by yuduber** [comment]
Thanks for the comment.   It makes sense.  I suppose in the "`allreduce=True`" you mean  "`average=True`", right?  The fix should be very straight forward by change it to `average=None`.  We will fix this soon.
