### ISSUE TITLE
Where is MPI_LIB.horovod_alltoall() implemented ?

### ISSUE THREAD

**Issue by kimchitsigai** [horovod/horovod#2633]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.3.1
3. Horovod version: 0.21.0
4. MPI version: 4.0.2
5. CUDA version: 10.1
6. NCCL version: 2.5.6
7. Python version: 3.7.9
8. OS and version: RHEL 8.1
9. GCC version: 8.3.1

**Your question:**
In horovod/tensorflow/mpi_ops.py , there are calls to MPI_LIB.horovod_alltoall(), MPI_LIB.horovod_allreduce(), etc.
My guess was that:
- these functions are TensorFlow Ops which are registered with the REGISTER_OP and REGISTER_KERNEL_BUILDER macros.
- these functions are implemented in horovod/tensorflow/mpi_ops.cc

However, when I look at mpi_ops.cc, the names which are used for REGISTER_OP and REGISTER_KERNEL_BUILDER are HorovodAlltoall and HorovodAlltoallOp, instead of horovod_allreduce.
What is the explanation for the difference?

Thanks a lot.

**Comment by maxhgerlach** [comment]
There's some automatic name convention conversion going on with TensorFlow. Ops are named in CamelCase for C++, but in snake_case for Python. So you correctly identified the implementation code.

**Comment by kimchitsigai** [comment]
Thank you.
