### ISSUE TITLE
Horovod questions (ssh)

### ISSUE THREAD

**Issue by inespancorbo** [horovod/horovod#2648]
I am new to setting up multi-node training jobs and was hoping to use Horovod. However, I am trying to understand a couple of points in terms of implementation.

From the documentation, to run Horovod on 4 machines with 4 gpus each the command would be 

```
horovodrun -np 16 -H server1:4,server2:4,server3:4,server4:4 python train.py
```

where serverx:x stands for the appropriate IP address and port? 

Also, could someone explain "the host where horovodrun is executed must be able to SSH to all other hosts without any prompts"? I am on a Mac remoting with VPN into my work's workstation (Windows OS) and from the workstation I have access to a shared server (Windows OS) too. Both the workstation and the shared server have a GPU each and would like to leverage both of them using Horovod. If the host where I were to run Horovod is my workstation how can I check if I can ssh into the shared server?

EDIT: To remote from my workstation into the shared server I am using RDP, in particular the GUI so not SSH.

**Comment by tgaddair** [comment]
Hey @inespancorbo, the `server1:4` means run 4 processes on server1, so server1 should be the full hostname.  The no-prompt thing just means that when you run `ssh server1`, you should not need to enter a password or accept any other stdin.

It should be mentioned that Horovod only support Linux and macOS at this time, so it would not be able to train a model on a cluster of Windows servers today.

**Comment by inespancorbo** [comment]
Thanks @tgaddair! Are there any alternatives for this? For example, Horovod on a Linux container (for reproducibility among the remaining machines in the cluster) on a Linux virtual machine on Windows OS?

**Comment by tgaddair** [comment]
Hey @inespancorbo, it should work to have a Linux VM or container on Windows, though I've heard mixed things about performance (I've not tried it myself).  The cleanest way would probably be to have a dual boot setup with Windows and Linux OS's, but I understand that is not ideal.  Long term, I think the Windows subsystem for Linux is the most promising route, but I'm not sure how well supported this is yet (there are some docs on it [here](https://developer.nvidia.com/cuda/wsl)).
