### ISSUE TITLE
How does horovod detect whether process exits?

### ISSUE THREAD

**Issue by zpcalan** [horovod/horovod#2656]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) PyTorch
2. Framework version:1.7.1
3. Horovod version:0.21.1
4. MPI version:4.0.3
5. CUDA version:10.1
6. NCCL version:2.7.6
7. Python version:3.7.4
8. OS and version:ubuntu-16.04
9. GCC version:7.3.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes, but I couldn't find similar questions.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Yes, but this doc doen't seem to help.
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Not about docker.
4. Did you check if you question is answered in the [troubleshooting guide] yes
(https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**

Hi, developers of Horovod.
When I run 8-GPU training, one GPU memory is not enough. So training tasks fail with message of mpi:
```
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[22366,1],3]
  Exit code:    1

```
It's all good because this is normal that one subprocess failed so the whole task should abort.

But according to [this question](https://stackoverflow.com/questions/62539362/mpi-check-whether-any-processes-have-been-terminated), if using MPI_Finalize instead of MPI_Abort, the parent process like horovodrun or mpirun can't detect the failure so other subprocesses can proceed. In this case, the training task shouldn't exit.

But I notice horovod doesn't use MPI_Abort but the whole traning process can still exit which confuses me.

**Comment by tgaddair** [comment]
Hey @zpcalan, my understanding from that thread is that MPI will only avoid exiting the entire job if the failing ranks call `MPI_Finalize` to gracefully shutdown before exiting.  But in most cases the ranks will exit suddenly without finalizing, which is why what causes the whole training process to exit.

**Comment by zpcalan** [comment]
@tgaddair Thank you. I will test on your point about exiting without calling `MPI_Finalize`. Issue closed
