### ISSUE TITLE
How to solve the error "Failed to determine if Gloo support has been built"

### ISSUE THREAD

**Issue by AnandInguva** [horovod/horovod#2668]
**Environment:**
1. Framework: Tensorflow
2. Framework version: 2.3.0
3. Horovod version: 0.21.3
4. MPI version:3.0
5. CUDA version:10.1
6. NCCL version:2.5
7. Python version:3.7
8. Spark / PySpark version: No spark
9. OS and version:Ubuntu, 16.04
10. GCC version: 9.3.0
11. CMake version:3.16

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
I used the  setting below to build the docker file. I am running horovod on GCP by using this docker image.

YML file used to download dependencies
name: test_horovod
channels:
- defaults
- conda-forge # needed for the newer pip version
dependencies:
- python=3.7 # 3.5 too old
- pip>20.0
- cmake=3.16
- cxx-compiler=1.0
- mpi4py=3.0
- nccl=2.5
- nodejs=13
- nvcc_linux-64=10.1
- pip:
  - ipdb==0.13.4
  - matplotlib==3.3.2
  - ipython==7.16.1
  - grpcio==1.33.1
  - scipy==1.4.1
  - tensorflow-gpu==2.3.0
  - tensorflow-probability==0.11.1
  - tensorflow-addons==0.11.2
  - pandas==1.2.1
  - pyquaternion==0.9.9
  - prompt-toolkit==3.0.8
  - pyyaml==5.3.1
  - seaborn==0.11.0
  - scikit-image==0.17.2
  - sklearn
  - openpyxl
  - opencv-python
  - h5py<3.0.0
  - horovod

There are the environment variables I am using:

export HOROVOD_WITH_TENSORFLOW=1 && export ENV_PREFIX=$PWD/env' \
                  ' && export HOROVOD_CUDA_HOME=$CUDA_HOME' \
                  ' && export HOROVOD_NCCL_HOME=$ENV_PREFIX' \
                  ' && export HOROVOD_GPU_OPERATIONS=NCCL' \
                  ' && export HOROVOD_WITH_GLOO=1 && export HOROVOD_WITH_MPI=1' \
                  ' && export HOROVOD_WITHOUT_PYTORCH=1 && export HOROVOD_WITHOUT_MXNET=1' \
                  ' && export HOROVOD_CONTROLLER=GLOO'

The error:

Operation completed over 1 objects/1008.0 B.                                     
Filtering local host names.
Remote host found: 
All hosts are local, finding the interfaces with address 127.0.0.1
Local interface found lo
Traceback (most recent call last):
  File "/opt/conda/envs/aioptics/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/opt/conda/envs/aioptics/lib/python3.7/site-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/opt/conda/envs/aioptics/lib/python3.7/site-packages/horovod/runner/launch.py", line 758, in _run
    return _run_static(args)
  File "/opt/conda/envs/aioptics/lib/python3.7/site-packages/horovod/runner/launch.py", line 615, in _run_static
    _launch_job(args, settings, nics, command)
  File "/opt/conda/envs/aioptics/lib/python3.7/site-packages/horovod/runner/launch.py", line 731, in _launch_job
    args.verbose)
  File "/opt/conda/envs/aioptics/lib/python3.7/site-packages/horovod/runner/launch.py", line 679, in run_controller
    if not gloo_built(verbose=verbose):
  File "/opt/conda/envs/aioptics/lib/python3.7/site-packages/horovod/common/util.py", line 122, in wrapper
    retval = f(*args, **kwargs)
  File "/opt/conda/envs/aioptics/lib/python3.7/site-packages/horovod/common/util.py", line 155, in gloo_built
    raise RuntimeError('Failed to determine if Gloo support has been built. '
RuntimeError: Failed to determine if Gloo support has been built. Run again with --verbose for more details.
Finished experiment. Terminating

I am trying to call horovodrun --verbose but I am still getting the same error.

**Comment by chongxiaoc** [comment]
PR #2689 should solve this issue.
The runtime error exception related to gloo check is removed there.

So even gloo is not successfully built with any framework, `horovod --check` would show the check result as False, rather than rising up an runtime error.
