### ISSUE TITLE
Bug in _DistributedOptimizer: named_parameters is None and multiple param groups

### ISSUE THREAD

**Issue by vfdev-5** [horovod/horovod#2670]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.7.1
3. Horovod version: master
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. Spark / PySpark version:
9. OS and version:
10. GCC version:
11. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**

I have an impression that this part of code is a bit wrong if multiple param_groups are used:
https://github.com/horovod/horovod/blob/6916985c9df111f36864724e2611827f64de8e11/horovod/torch/optimizer.py#L46-L48
and if checked then for duplicates:
https://github.com/horovod/horovod/blob/6916985c9df111f36864724e2611827f64de8e11/horovod/torch/optimizer.py#L55

For example:
```python
param_groups = [
    {"params": ["a", "b", "c"]},
    {"params": ["e", "f", "g"]},    
]

named_parameters = [('allreduce.noname.%s' % i, v)
                    for param_group in param_groups
                    for i, v in enumerate(param_group['params'])]

print("named_parameters:", named_parameters)

def find_duplicates(lst):
    seen = set()
    dups = set()
    for el in lst:
        if el in seen:
            dups.add(el)
        seen.add(el)
    return dups

dups = find_duplicates([k for k, _ in named_parameters])
print("duplicates:", dups)
```
Output:
```
named_parameters: [('allreduce.noname.0', 'a'), ('allreduce.noname.1', 'b'), ('allreduce.noname.2', 'c'), ('allreduce.noname.0', 'e'), ('allreduce.noname.1', 'f'), ('allreduce.noname.2', 'g')]

duplicates: {'allreduce.noname.0', 'allreduce.noname.1', 'allreduce.noname.2'}
```

Here is a complete code snippet to repro the issue:
```python
    hvd.init()
    torch.cuda.set_device(hvd.local_rank())

    model = nn.Sequential(nn.Linear(10, 10), nn.Linear(10, 10)).cuda()

    optimizer = optim.SGD(
        [{"params": model[0].parameters()}, {"params": model[1].parameters()},],
        lr=0.001,
    )

    optimizer = hvd.DistributedOptimizer(
        optimizer,
        # named_parameters=model.named_parameters()
    )

> ValueError: Parameter names in named_parameters must be unique. Found duplicates: allreduce.noname.0, allreduce.noname.1
```

**Comment by tgaddair** [comment]
Thanks for the repro @vfdev-5!  I'll take a look.

**Comment by vfdev-5** [comment]
@tgaddair maybe, it can be easily fixed with adding param group index like : 
```python
named_parameters = [('allreduce.noname.%s.%s' % (j, i), v)
                    for j, param_group in enumerate(param_groups)
                    for i, v in enumerate(param_group['params'])]
```

**Comment by vfdev-5** [comment]
@tgaddair any updates on that ?

**Comment by tgaddair** [comment]
Hey @vfdev-5, sorry for the delay. I tested your proposed fix, and it worked for me. Please take a look at #2712 and let me know if it works for you as well!
