### ISSUE TITLE
Modify gradient in each node

### ISSUE THREAD

**Issue by densechen** [horovod/horovod#2675]
**Environment:**
1. Framework: (PyTorch)

**Your question:**
Hi, if I want to modify the grad in each node before all-reduce, does it mean that: we should modify the gradient before synchronize() is called?

**Comment by tgaddair** [comment]
Hey @densechen, my suggestion would be to use the `Compression` hooks defined here: https://github.com/horovod/horovod/blob/master/horovod/torch/compression.py#L20

This will allow you to modify grads before and/or after allreduce.

**Comment by densechen** [comment]
@tgaddair Thanks a lot. By the way, does horovod provide any methods that compression tensors to a 1bit one?
In official pytorch implementation, it is not supported a 1bit data type yet.

**Comment by tgaddair** [comment]
You mean like [signSGD](https://arxiv.org/abs/1802.04434)? We had some conversations at one point about this, but have not gotten around to implementing it. Happy to discuss the idea though if it's of interest!

**Comment by densechen** [comment]
Yes, and here also provide some discussion about this (https://github.com/pytorch/pytorch/issues/32867)
