### ISSUE TITLE
Fail in training in docker, but succeed in geting rid of docker 

### ISSUE THREAD

**Issue by SicleBoypy** [horovod/horovod#2681]
**Environment:**
1. Framework: PyTorch
2. Framework version:1.7.0
3. Horovod version:0.21.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here:

I experiment mnist in docker, 
primary worker:  docker run -it --gpus all --shm-size 512g   -v /root/.ssh:/root/.ssh --network=host asr_horovod:v3
Secondary workers: docker run -it --gpus all --shm-size 512g  -v /root/.ssh:/root/.ssh --network=host asr_horovod:v3 bash -c "/usr/sbin/sshd -p 22; sleep infinity" ( appear "Missing privilege separation directory: /run/sshd")
command for mnist: horovodrun -np 8 --gloo --verbose -H 10.19.250.171:4,10.19.250.170:4 -p 22 --network-interface "bond0,bond0" python pytorch_mnist.py

error:
Filtering local host names.Remote host found: 10.19.250.171Checking ssh on all remote hosts.SSH was successful into all the remote hosts.ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no 10.19.250.171 -p 22   'cd /home/horovod/examples/pytorch > /dev/null 2>&1 ; HOROVOD_HOSTNAME=10.19.250.171 HOROVOD_RANK=0 HOROVOD_SIZE=2 HOROVOD_LOCAL_RANK=0 HOROVOD_LOCAL_SIZE=1 HOROVOD_CROSS_RANK=0 HOROVOD_CROSS_SIZE=2 NVIDIA_VISIBLE_DEVICES=all HOSTNAME=haoweilai NVIDIA_REQUIRE_CUDA='"'"'cuda>=11.0 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441'"'"' PWD=/home/horovod/examples/pytorch NVIDIA_DRIVER_CAPABILITIES=compute,utility NCCL_HOME=/usr/local/cuda HOME=/root LS_COLORS='"'"'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'"'"' LESSCLOSE='"'"'/usr/bin/lesspipe %s %s'"'"' TERM=xterm LESSOPEN='"'"'| /usr/bin/lesspipe %s'"'"' SHLVL=0 LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/lcoal/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 CUDA_HOME=/usr/local/cuda PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/local/bin/horovodrun LC_CTYPE=C.UTF-8 HOROVOD_STALL_CHECK_TIME_SECONDS=60 HOROVOD_STALL_SHUTDOWN_TIME_SECONDS=0 HOROVOD_NUM_NCCL_STREAMS=1 HOROVOD_CCL_BGT_AFFINITY=0HOROVOD_GLOO_TIMEOUT_SECONDS=30 PYTHONUNBUFFERED=1 HOROVOD_GLOO_RENDEZVOUS_ADDR=10.19.250.170 HOROVOD_GLOO_RENDEZVOUS_PORT=27181 HOROVOD_CONTROLLER=gloo HOROVOD_CPU_OPERATIONS=gloo HOROVOD_GLOO_IFACE=bond0 NCCL_SOCKET_IFNAME=bond0 python pytorch_mnist.py'
HOROVOD_HOSTNAME=10.19.250.170 HOROVOD_RANK=1 HOROVOD_SIZE=2 HOROVOD_LOCAL_RANK=0 HOROVOD_LOCAL_SIZE=1 HOROVOD_CROSS_RANK=1 HOROVOD_CROSS_SIZE=2 NVIDIA_VISIBLE_DEVICES=all HOSTNAME=haoweilai NVIDIA_REQUIRE_CUDA='cuda>=11.0 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441' PWD=/home/horovod/examples/pytorch NVIDIA_DRIVER_CAPABILITIES=compute,utility NCCL_HOME=/usr/local/cuda HOME=/root LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:' LESSCLOSE='/usr/bin/lesspipe %s %s' TERM=xterm LESSOPEN='| /usr/bin/lesspipe %s' SHLVL=0 LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/lcoal/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 CUDA_HOME=/usr/local/cuda PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/local/bin/horovodrun LC_CTYPE=C.UTF-8 HOROVOD_STALL_CHECK_TIME_SECONDS=60 HOROVOD_STALL_SHUTDOWN_TIME_SECONDS=0 HOROVOD_NUM_NCCL_STREAMS=1 HOROVOD_CCL_BGT_AFFINITY=0 HOROVOD_GLOO_TIMEOUT_SECONDS=30 PYTHONUNBUFFERED=1 HOROVOD_GLOO_RENDEZVOUS_ADDR=10.19.250.170 HOROVOD_GLOO_RENDEZVOUS_PORT=27181 HOROVOD_CONTROLLER=gloo HOROVOD_CPU_OPERATIONS=gloo HOROVOD_GLOO_IFACE=bond0 NCCL_SOCKET_IFNAME=bond0 python pytorch_mnist.py
[0]<stderr>:bash: python: command not found

It seem to python has been found.
But when I get rid of docker , and experment in physical machine successful. The two node has same docker. Why only rank0 not found python? When I change primary worker to secondary worker, It also happens to secondary worker not found python, and two node has same directory tree.

**Comment by tgaddair** [comment]
Hey @SicleBoypy, that is weird. Can you try running the horovodrun command you had before `horovodrun -np 8 --gloo --verbose -H 10.19.250.171:4,10.19.250.170:4 -p 22 --network-interface "bond0,bond0"` but with `which python` instead of `python pytorch_mnist.py`. That should help us understand what Python executable each of the workers is seeing.

**Comment by SicleBoypy** [comment]
> 
> 
> Hey @SicleBoypy, that is weird. Can you try running the horovodrun command you had before `horovodrun -np 8 --gloo --verbose -H 10.19.250.171:4,10.19.250.170:4 -p 22 --network-interface "bond0,bond0"` but with `which python` instead of `python pytorch_mnist.py`. That should help us understand what Python executable each of the workers is seeing.

which python show the python is /usr/bin/python, when I use command horovodrun -np 2 --gloo --verbose -H 10.19.250.171:1,10.19.250.170:1 -p 22 --network-interface "bond0,bond0" /usr/bin/python pytorch_mnist.py, it also appear the  error :  [0]<stderr>:bash: /usr/bin/python: No such file or directory.
I confuse with the two node with docker.  I enter into the docker of primary worker , how horovodrun run secondary workers? If I don't start the docker of secondary worker, The secondary worker will be used  in physical machine. What will be happend? In the other way, when I start docker with docker run -it --gpus all --shm-size 512g -v /root/.ssh:/root/.ssh --network=host asr_horovod:v3 bash -c "/usr/sbin/sshd -p 22; sleep infinity" ,  whether it will make sure the secondary worker using docker  instead of physical machine？If it use docker，will it go into docker directory tree to find python ？

**Comment by SicleBoypy** [comment]
> 
> 
> Hey @SicleBoypy, that is weird. Can you try running the horovodrun command you had before `horovodrun -np 8 --gloo --verbose -H 10.19.250.171:4,10.19.250.170:4 -p 22 --network-interface "bond0,bond0"` but with `which python` instead of `python pytorch_mnist.py`. That should help us understand what Python executable each of the workers is seeing.



> 
> 
> Hey @SicleBoypy, that is weird. Can you try running the horovodrun command you had before `horovodrun -np 8 --gloo --verbose -H 10.19.250.171:4,10.19.250.170:4 -p 22 --network-interface "bond0,bond0"` but with `which python` instead of `python pytorch_mnist.py`. That should help us understand what Python executable each of the workers is seeing.

When I use command horovodrun -np 2 --gloo --verbose -H 10.19.250.171:1,10.19.250.170:1 -p 22 --network-interface "bond0,bond0" which python, the error is that:
Filtering local host names.Remote host found: 10.19.250.171Checking ssh on all remote hosts.SSH was successful into all the remote hosts.HOROVOD_HOSTNAME=10.19.250.170 HOROVOD_RANK=1 HOROVOD_SIZE=2 HOROVOD_LOCAL_RANK=0 HOROVOD_LOCAL_SIZE=1 HOROVOD_CROSS_RANK=1 HOROVOD_CROSS_SIZE=2 NVIDIA_VISIBLE_DEVICES=all HOSTNAME=haoweilai NVIDIA_REQUIRE_CUDA='cuda>=11.0 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441' PWD=/home/horovod/examples/pytorch NVIDIA_DRIVER_CAPABILITIES=compute,utility NCCL_HOME=/usr/local/cuda HOME=/root LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:' LESSCLOSE='/usr/bin/lesspipe %s %s' TERM=xterm LESSOPEN='| /usr/bin/lesspipe %s' SHLVL=0 LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/lcoal/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 CUDA_HOME=/usr/local/cuda PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/local/bin/horovodrun LC_CTYPE=C.UTF-8 HOROVOD_STALL_CHECK_TIME_SECONDS=60 HOROVOD_STALL_SHUTDOWN_TIME_SECONDS=0 HOROVOD_NUM_NCCL_STREAMS=1 HOROVOD_CCL_BGT_AFFINITY=0 HOROVOD_GLOO_TIMEOUT_SECONDS=30 PYTHONUNBUFFERED=1 HOROVOD_GLOO_RENDEZVOUS_ADDR=10.19.250.170 HOROVOD_GLOO_RENDEZVOUS_PORT=53609 HOROVOD_CONTROLLER=gloo HOROVOD_CPU_OPERATIONS=gloo HOROVOD_GLOO_IFACE=bond0 NCCL_SOCKET_IFNAME=bond0 which python
ssh -o PasswordAuthentication=no -o StrictHostKeyChecking=no 10.19.250.171 -p 22   'cd /home/horovod/examples/pytorch > /dev/null 2>&1 ; HOROVOD_HOSTNAME=10.19.250.171 HOROVOD_RANK=0 HOROVOD_SIZE=2 HOROVOD_LOCAL_RANK=0 HOROVOD_LOCAL_SIZE=1 HOROVOD_CROSS_RANK=0 HOROVOD_CROSS_SIZE=2 NVIDIA_VISIBLE_DEVICES=all HOSTNAME=haoweilai NVIDIA_REQUIRE_CUDA='"'"'cuda>=11.0 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441'"'"' PWD=/home/horovod/examples/pytorch NVIDIA_DRIVER_CAPABILITIES=compute,utility NCCL_HOME=/usr/local/cuda HOME=/root LS_COLORS='"'"'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'"'"' LESSCLOSE='"'"'/usr/bin/lesspipe %s %s'"'"' TERM=xterm LESSOPEN='"'"'| /usr/bin/lesspipe %s'"'"' SHLVL=0 LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/lcoal/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 CUDA_HOME=/usr/local/cuda PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin _=/usr/local/bin/horovodrun LC_CTYPE=C.UTF-8 HOROVOD_STALL_CHECK_TIME_SECONDS=60 HOROVOD_STALL_SHUTDOWN_TIME_SECONDS=0 HOROVOD_NUM_NCCL_STREAMS=1 HOROVOD_CCL_BGT_AFFINITY=0HOROVOD_GLOO_TIMEOUT_SECONDS=30 PYTHONUNBUFFERED=1 HOROVOD_GLOO_RENDEZVOUS_ADDR=10.19.250.170 HOROVOD_GLOO_RENDEZVOUS_PORT=53609 HOROVOD_CONTROLLER=gloo HOROVOD_CPU_OPERATIONS=gloo HOROVOD_GLOO_IFACE=bond0 NCCL_SOCKET_IFNAME=bond0 which python'
[1]<stdout>:/usr/bin/python
Process 0 exit with status code 1
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 8, in <module>
    sys.exit(run_commandline())
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 768, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 758, in _run
    return _run_static(args)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 615, in _run_static
    _launch_job(args, settings, nics, command)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 728, in _launch_job
    run_controller(args.use_gloo, gloo_run_fn,
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 682, in run_controller
    gloo_run()
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/launch.py", line 720, in gloo_run_fn
    gloo_run(settings, nics, env, driver_ip, command)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/gloo_run.py", line 284, in gloo_run
    launch_gloo(command, exec_command, settings, nics, env, server_ip)
  File "/usr/local/lib/python3.8/dist-packages/horovod/runner/gloo_run.py", line 268, in launch_gloo
    raise RuntimeError('Horovod detected that one or more processes exited with non-zero '
RuntimeError: Horovod detected that one or more processes exited with non-zero status, thus causing the job to be terminated. The first process to do so was:
Process name: 0
Exit code: 1

**Comment by SicleBoypy** [comment]
> 
> 
> Hey @SicleBoypy, that is weird. Can you try running the horovodrun command you had before `horovodrun -np 8 --gloo --verbose -H 10.19.250.171:4,10.19.250.170:4 -p 22 --network-interface "bond0,bond0"` but with `which python` instead of `python pytorch_mnist.py`. That should help us understand what Python executable each of the workers is seeing.

Hey@tgaddair ，Thanks your reply. I have solved the problem using other port instead of port 22 and mkdir /run/sshd in the docker of secondary workers.
