### ISSUE TITLE
Failed to run the end-to-end-example with rossmann dataset in Horovod Spark Estimators in single node

### ISSUE THREAD

**Issue by JkSelf** [horovod/horovod#2694]
**Environment:**
1. Framework: (TensorFlow, PyTorch)
2. Framework version: 
3. Horovod version: v0.21.3
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version: 3.6
8. OS and version: centos 7
9. GCC version: 9.3

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
I am new to Horovod. And when I run [the end to end example](https://horovod.readthedocs.io/en/stable/spark_include.html#end-to-end-example) with Horovod Spark Estimators in single node. I encountered the following exception with command `python keras_spark_rossmann_estimator.py --master spark://bdpe814un3.sh.intel.com:7077` when executing the `keras_estimator.fit()`  method. 

`Traceback (most recent call last):
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Thu Feb 25 21:29:09 2021[3]<stderr>:    "__main__", mod_spec)
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/runpy.py", line 85, in _run_code
Thu Feb 25 21:29:09 2021[3]<stderr>:    exec(code, run_globals)
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/horovod/spark/task/gloo_exec_fn.py", line 30, in <module>
Thu Feb 25 21:29:09 2021[3]<stderr>:    main(codec.loads_base64(sys.argv[1]), codec.loads_base64(sys.argv[2]))
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/horovod/spark/task/gloo_exec_fn.py", line 23, in main
Thu Feb 25 21:29:09 2021[3]<stderr>:    task_exec(driver_addresses, settings, 'HOROVOD_RANK', 'HOROVOD_LOCAL_RANK')
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/horovod/spark/task/__init__.py", line 61, in task_exec
Thu Feb 25 21:29:09 2021[3]<stderr>:    result = fn(*args, **kwargs)
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/horovod/spark/keras/remote.py", line 234, in train
Thu Feb 25 21:29:09 2021[3]<stderr>:    if should_validate else empty_batch_reader() as val_reader:
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/petastorm/reader.py", line 327, in make_batch_reader
Thu Feb 25 21:29:09 2021[3]<stderr>:    filters=filters)
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/petastorm/reader.py", line 462, in __init__
Thu Feb 25 21:29:09 2021[3]<stderr>:    ventilator=self.ventilator)
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/petastorm/workers_pool/process_pool.py", line 201, in start
Thu Feb 25 21:29:09 2021[3]<stderr>:    self._wait_for_workers_to_start()
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/petastorm/workers_pool/process_pool.py", line 212, in _wait_for_workers_to_start
Thu Feb 25 21:29:09 2021[3]<stderr>:    lambda: self._results_receiver.recv_pyobj(flags=zmq.constants.NOBLOCK))
Thu Feb 25 21:29:09 2021[3]<stderr>:  File "/home/minicoda3/envs/intel-arrow-dev/lib/python3.7/site-packages/petastorm/workers_pool/process_pool.py", line 111, in _keep_retrying_while_zmq_again
Thu Feb 25 21:29:09 2021[3]<stderr>:    raise RuntimeError('Timeout ({} [sec]) has elapsed while keep getting \'zmq.Again\''.format(timeout))
Thu Feb 25 21:29:09 2021[3]<stderr>:RuntimeError: Timeout (20 [sec]) has elapsed while keep getting 'zmq.Again'
`

**Comment by tgaddair** [comment]
Thanks for the report @JkSelf, seems like the Petastorm workers are timing out for some reason. 

@selitvin have you seen this error before?

**Comment by selitvin** [comment]
Hard to say what's the exact reason for the timeout. Could be some catastrophic failure of the worker process or just a very long IO operation? Some ideas to try and figure out what's really going on:
- Try increasing the [timeout value](https://github.com/uber/petastorm/blob/f8c427c759522aa8efb56bbe015c23e7c5dfd356/petastorm/workers_pool/process_pool.py#L41) unfortunately hardcoded in petastorm.
- Try using threadpool (`process` -> `thread`. Unfortunately also hardcoded :) ): https://github.com/horovod/horovod/blob/7f7a02e5c00037445fbd58b60e03be1dc0a8a329/horovod/spark/keras/remote.py#L217 (there are couple of additional places in the same file. @tgaddair : did I miss some place?)
- You can also try a 'dummy' pool (which is not really a pool, just a mechanism that allows to run everything on the main thread). This makes debugging easier, so maybe we'll discover something by using this trivial setup.

**Comment by JkSelf** [comment]
@tgaddair @selitvin Thanks for your help.
This issue is fixed after setting the `--num-proc ` value same with the spark executor instances.

**Comment by tgaddair** [comment]
Thanks @selitvin for looking into it! And glad you got it working @JkSelf, I'll close this issue for now.
