### ISSUE TITLE
no horovod.torch.init in latest docs

### ISSUE THREAD

**Issue by ydcjeff** [horovod/horovod#2695]
I can go directly to `horovod.torch.init` in v0.21.0 docs : https://horovod.readthedocs.io/en/v0.20.0/api.html#horovod.torch.init
But, can't anymore in https://horovod.readthedocs.io/en/latest/api.html#horovod.torch.init
Traced down and found at it didn't start existing at https://horovod.readthedocs.io/en/v0.21.1/api.html#horovod.torch.init

**Comment by tgaddair** [comment]
Thanks for reporting @ydcjeff. This is pretty strange, as I cannot reproduce the error locally, or even using the same Docker image that's used to build the docs in our CI system.

@sblotner, do you have thoughts on what might cause this? I did see that there was an update to the sphinx dependency in the window when the issue started (#2539), but it doesn't look like that is the issue.

**Comment by sblotner** [comment]
It looks like in api.rst (https://github.com/horovod/horovod/blob/master/docs/api.rst) it's pulling in the API docs for horovod.torch.elastic successfully, but not horovod.torch. 

@tgaddair when you generate the docs locally, do you see horovod.torch.init, etc.? 

It looks like with sphinx 3 there were some changes to how automodule determines if code is public or private (to generate docs or ignore): https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html?highlight=automodule

**Comment by tgaddair** [comment]
Thanks for the response @sblotner. Yeah, the docs look fine when running locally, as well as in the Docker, so not sure where the difference is at this point.

**Comment by sblotner** [comment]
Really strange that it's not reproducing in those environments. 
I'm seeing gaps in autogenerated docs for horovod.torch, horovod.spark, horovod.mxnet, horovod.keras, horovod.tensorflow

The only other thing I can think of is maybe it has something to do with sphinx 3.x and the conf.py settings? https://github.com/horovod/horovod/blob/master/docs/conf.py#L59

**Comment by tgaddair** [comment]
Looks like we may not need to build the docs in Buildkite, should be possible to do it directly through ReadTheDocs: https://docs.readthedocs.io/en/latest/pull-requests.html

**Comment by tgaddair** [comment]
Okay, I think I fixed it in #2711 @sblotner.  Looks like ReadTheDocs was using an older version of Sphinx by default, so by forcing it to use version 3 and above, the issue appears to be fixed.

**Comment by tgaddair** [comment]
Fixed by #2711.

**Comment by sblotner** [comment]
Nice, thanks @tgaddair ! The latest doc build is generating docs as expected: https://horovod.readthedocs.io/en/latest/api.html#horovod.torch.init
