### ISSUE TITLE
[Horovod on Ray] cpu isolation when setting cpus_per_slot in RayExecutor

### ISSUE THREAD

**Issue by lchu-ibm** [horovod/horovod#2705]
For `RayExecutor` using cpu (i.e. `use_gpu=False`), `cpus_per_slot` seems not working - it always uses as many cpus as possible on that node in my experiments.

I have been testing this on both ray cluster (spinned up on Kubernetes) as well as local, both has the same issue.  E.g. for local testing, I have a local machine that has 72 vcpus, and not matter I set `RayExecutor(settings, num_hosts=1, num_slots=1, use_gpu=False, cpus_per_slot=1)` or `RayExecutor(settings, num_hosts=1, num_slots=1, use_gpu=False, cpus_per_slot=32)` or `RayExecutor(settings, num_hosts=1, num_slots=1, use_gpu=False, cpus_per_slot=whatever-number-here-less-or-equal-to-72)`, all cpus are being used.  This has been validated from two observations:  1. when I monitor the activities (say, use `htop`), all cpus are running fully even I requested only one cpu   2. cpus_per_slot=1 and cpus_per_slot=72 and cpus_per_slot=any-number all have exact the same performance (as both use all cpus).

@richardliaw could you help on this?

**Comment by tgaddair** [comment]
Hey @lchu-ibm, my understanding of how Ray does allocation is that it does not provide CPU isolation directly, the `cpus_per_slot` param is only used for placement. 

This is something you should be able to control at the application level, for example in TensorFlow:

```
tf.config.threading.set_intra_op_parallelism_threads(n)
tf.config.threading.set_inter_op_parallelism_threads(m)
```

@richardliaw correct me if I'm wrong.

**Comment by richardliaw** [comment]
Hey @lchu-ibm sorry for the slow reply. Travis is right, you need to set this at the framework level (or the underlying cluster provider level). Ray does not isolate/control CPU usage of the processes.

**Comment by lchu-ibm** [comment]
@tgaddair @richardliaw thank you both for the explanation, this is very helpful and solved my problem.
