### ISSUE TITLE
Diffrenet Data in different machine

### ISSUE THREAD

**Issue by hangxu124** [horovod/horovod#2717]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) pytorch
2. Framework version: 1.6.0
3. Horovod version: v0.21.0
4. MPI version: 4.0.5
5. CUDA version: 10.0
6. NCCL version: 2.7.6
7. Python version: 3.7
8. OS and version: ubuntu 16.04
9. GCC version: 5.4.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

I have a  relatively large dataset (about 3T), however, I have 2 machines and each only have 2T disk，so I cannot put the dataset in one machine.
I split the dataset into 2 parts, each machine stores 1.5T data, and I decide to use horovod for distributed training.
The traditional tutorial does not hold this situation in dataloader. I cannot get data1 on machine2.
So I have some questions on dataloader.
`train_sampler = torch.utils.data.distributed.DistributedSampler(
    train_dataset, num_replicas=hvd.size(), rank=hvd.rank())`
here num_replicas=hvd.size(), however, in this situation I think it should be num_replicas=hvd.size()/2, because I have 2 machines, and the rank=hvd.rank()%num_gpus_per_node.
I'm not sure whether it's right and I also want to know if there is a tutorial for this situation or what should I write this data sampler.

Thanks a lot!

**Comment by tgaddair** [comment]
Hey @hangxu124, assuming the datasets are split evenly, this should not be an issue. You can just use some conditional logic to decide which dataset to read:

```
if hvd.cross_rank() == 0: # machine 1
    train_dataset = read_dataset_a()
else: # machine 2
    train_dataset = read_dataset_b()
train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset, num_replicas=hvd.local_size(), rank=hvd.local_rank())
```

Note the use of `local_rank` here, because we're dividing each dataset among the workers on a single host.

**Comment by hangxu124** [comment]
hi @tgaddair , thanks for your reply, I'll try this, and I'd like to know how can I get information about... like hvd.cross_rank(). I try to search "hvd.cross_rank()" in https://horovod.readthedocs.io/  and google but find nothing..

**Comment by tgaddair** [comment]
Hey @hangxu124, looks like we actually don't expose that function in Python, so I added #2718 to address that.
