### ISSUE TITLE
Documentation to run tests should be updated

### ISSUE THREAD

**Issue by maxhgerlach** [horovod/horovod#2722]
**Environment:**
3. Horovod version: master
4. MPI version: mpirun (Open MPI) 4.0.2
7. Python version: 3.7.5
11. CMake version: 3.5.1

```
$ pytest --version
pytest 6.0.2
```

**Bug report:**
https://horovod.readthedocs.io/en/stable/contributors_include.html#testing says:

> Horovod has unit tests for all frameworks you can run from the tests directory:
> 
> $ cd test
> $ mpirun -np 2 pytest -v

But that doesn't seem to work for all tests, for instance
```
$ mpirun -np 2 pytest -v integration/test_interactiverun.py::InteractiveRunTests::test_happy_run
```
fails with this message:
```
mpirun does not support recursive calls
```

**Comment by tgaddair** [comment]
Thanks for raising this issue, @maxhgerlach. Yes, each of the different directories in tests is handled separately. The documentation is only correct for the `parallel` subdirectory.
