### ISSUE TITLE
Support MXNet with oneDNN replacing MKLDNN

### ISSUE THREAD

**Issue by EnricoMi** [horovod/horovod#2726]
Horovod supports MXNet only with MKLDNN headers. Version 2.0.0 renames [MKLDNN to oneDNN](https://github.com/apache/incubator-mxnet/commit/aa92db02201799841bf52db5a0b8507719f04e61) ([mxnet issue #20054](https://github.com/apache/incubator-mxnet/issues/20054)).

An approach for Horovod to work with MXNet pre 2.0.0 (MKLDNN) and post 2.0.0 (oneDNN) is to duplicate how Horovod builds against MKLDNN, including [CMake detection code](https://github.com/horovod/horovod/blob/master/cmake/Modules/FindMxnet.cmake). Depending on the MXNet version, we can than build it with MKLDNN or oneDNN support.

**Comment by EnricoMi** [comment]
@tgaddair @leezu what are your thoughts?

**Comment by tgaddair** [comment]
Sounds good to me! I think some minor duplication in CMake is fine.

**Comment by EnricoMi** [comment]
#2728 fixes this clean enough, once mxnet fully renames the feature to onednn, there will be some more work to be done. Closing for now.
