### ISSUE TITLE
TensorFlow_LIRARIES not being found?

### ISSUE THREAD

**Issue by PowellTravis** [horovod/horovod#2729]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version: TensorFlow 2.4.1 AARCH64 build
3. Horovod version: 0.21.3
4. MPI version: 3.3.2
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.8
8. OS and version: Ubuntu 20.04 aarch64
9. GCC version: 9.3.0

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? 
3. If your question is about docker, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/docker.rst)? No
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Your question:**
Please ask your question here.
I keep getting the error     Could NOT find Tensorflow (missing: Tensorflow_LIBRARIES) (Required is at least version "1.15.0") But I have already installed TensorFlow from a cross compiled aarm64 .whl file. I am running the command 
```
HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_MPI=1 pip3 install -v horovod[tensorflow] --no-cache-dir
```
But with no success has it complied yet.

**Comment by chongxiaoc** [comment]
@PowellTravis 
Can you try below scripts to see what tenforflow provides on your system?
`python -c "import tensorflow as tf; print(tf.__version__); print(tf.sysconfig.get_include()); print(' '.join(tf.sysconfig.get_link_flags())); print(' '.join(tf.sysconfig.get_compile_flags()))"`

That's CMake FindTensorflow function is doing in horovod.

**Comment by PowellTravis** [comment]
I get this as the output from the command previously mentioned
```
2.4.1
/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/include

-I/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
```

**Comment by chongxiaoc** [comment]
You have `get_link_flags()` missing. That's why TF libs cannot be found. Only headers were found.

**Comment by chongxiaoc** [comment]
For example, it should be something like this:
```
1.15.3
/Users/chongxiaoc/build/hvd-py3.7/lib/python3.7/site-packages/tensorflow_core/include
-L/Users/chongxiaoc/build/hvd-py3.7/lib/python3.7/site-packages/tensorflow_core -ltensorflow_framework.1
-I/Users/chongxiaoc/build/hvd-py3.7/lib/python3.7/site-packages/tensorflow_core/include -D_GLIBCXX_USE_CXX11_ABI=0
```

**Comment by PowellTravis** [comment]
Is there a possible way to fix this?

**Comment by chongxiaoc** [comment]
The below issue might be helpful.
https://github.com/horovod/horovod/issues/2322

**Comment by PowellTravis** [comment]
I am recompiling my tensorflow package without the monolithic configuration.

**Comment by PowellTravis** [comment]
I recompiled my tensorflow package and now I get this in response to the python -c command listed above 
```
2.4.1
/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/include
-L/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow -l:libtensorflow_framework.so.2
-I/home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
```

**Comment by PowellTravis** [comment]
Sorry for the many responses but it does look to be building horovod properly now. Thank You for your help. I am going to close this issue. The horovod package did build successfully.
