### ISSUE TITLE
A question about horovod tensorflow backend allreduce op execution

### ISSUE THREAD

**Issue by Superjomn** [horovod/horovod#2732]
**Environment:**
1. Framework: TensorFlow
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

Hi, developers:

I am recently read Horovod code but failed to understand the workflow of the `HorovodAllreduceOp`.

In my understanding, the [HorovodAllreduceOp](https://github.com/horovod/horovod/blob/master/horovod/tensorflow/mpi_ops.cc#L421)  enqueues all the gradient tensors into some target queue and returns ok immediately(because it is an AsyncOp), and the background thread will process the messages in the queue  communicate with the coordinator node and schedule some actual collective Allreduce tasks later.

My question is, how Horovod make the TensorFlow `ApplyGradients` actions wait(hang) until the gradient tensors modified after the actual Allreduce actions (for that the `HorovodAllreduceOp` does not make sure the collective Allreduce has performed and returns immediately)?

**Comment by Superjomn** [comment]
After reading the documentation of TensorFlow `AsyncOpKernel`, I found the code https://github.com/horovod/horovod/blob/master/horovod/tensorflow/mpi_ops.cc#L417-L418, and this solved my issue.

The `HorovodAllReduceOp` will suspend and record the `done` callback in the message record. The background thread will process the message and perform the actual `allreduce` task later with the help of the coordinator. After that, the `done` will be triggered, and the TensorFlow runtime will continue running the operators depend on the outputs of the `HorovodAllReduceOp`.

**Comment by tgaddair** [comment]
Hey @Superjomn, glad you found the details you were looking for. Yes, Horovod implements the allreduce as an async callback so that parallel ops can be submitted together. Once the callback is called, ops that depend on the allreduce can proceed.
