### ISSUE TITLE
Compute, Communication, and Overlap Time

### ISSUE THREAD

**Issue by aruhela** [horovod/horovod#2737]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:
9. GCC version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Your question:**
Please ask your question here.

Is it possible to calculate programmatically the time spent in Compute, Communication, and their overlap from the horovod timeline? How accurate is the time compared to other profilers like nvprof and mpiP?

Has anyone created a script to determine these timings?

Thanks,
Amit

**Comment by tgaddair** [comment]
Hey @aruhela, you may want to check out #2723, which adds some profiling features that may provide what you're looking for.

@romerojosh do you have any additional tips for profiling Horovod overlap of compute / communication?
