### ISSUE TITLE
Horovod runtime problem mpi_lib.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by adavanisanti** [horovod/horovod#274]
I have successfully installed horovod using the instructions. But when I try to run any example, I see the following error:

`import horovod.tensorflow  as hvd`

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/horovod/local/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 32, in <module>
    from horovod.common import init
  File "/home/ubuntu/horovod/local/lib/python2.7/site-packages/horovod/common/__init__.py", line 47, in <module>
    'mpi_lib' + get_ext_suffix()), mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ubuntu/horovod/local/lib/python2.7/site-packages/horovod/common/mpi_lib.so: undefined symbol: __cudaPopCallConfiguration
```

Environment:

Ubuntu 1604
CUDA 9.0
Python 2.7
Tensorflow 1.8.0
MPI 3.1.0

Any pointers on where to look?

Thanks
Santi

**Comment by adavanisanti** [comment]
Does MPI have to build `with-cuda` support?

**Comment by alsrgv** [comment]
@adavanisanti, no, MPI does not need to be built with CUDA support.  Can you check `ldd /home/ubuntu/horovod/local/lib/python2.7/site-packages/horovod/common/mpi_lib.so` ?

**Comment by adavanisanti** [comment]
@alsrgv Reinstalled everything from scratch and it is working now on a single GPU machine. I think the problem was with running.

`sudo apt install libnccl2 libnccl-dev`
instead of
`sudo apt install libnccl2=2.2.12-1+cuda9.0 libnccl-dev=2.2.12-1+cuda9.0`

**Comment by alsrgv** [comment]
@adavanisanti, ah - that's possible.  Glad you got it working.
