### ISSUE TITLE
Undefined ompi symbols because mpi_lib.so fails to link to OpenMPIs libmpi.so

### ISSUE THREAD

**Issue by casparvl** [horovod/horovod#279]
**Issue**
When compiling Horovod with OpenMPI 2.1.1, the compilation completes without errors. However, when running e.g.
`import horovod.tensorflow as hvd`
I get the error
`OSError: /home/casparl/virtualenvs/tensorflow_cpu_oldmods_openmpi/lib/python2.7/site-packages/horovod/common/mpi_lib.so: undefined symbol: ompi_mpi_op_sum`

**Cause**
mpi_lib.so is not being linked to libmpi.so of the OpenMPI installation. The reason is that the setup.py for horovod relies on 'mpicxx -show' to pick up the include dirs, library dirs, and libraries that are linked by the mpicxx wrapper. However, mpicxx -show for OpenMPI only returns the compiler, include directories, and library directories, but NOT the libraries to be linked (e.g. no -lmpi). Thus, mpi is not being linked. According to the man pages of mpicxx in OpenMPI, the  invocation mpicxx --showme:link will return the desired result (similar to mpicxx -show for Intel MPI).

**Ugly workaround**
Using LDPRELOAD=.../libmpi.so (the libmpi of OpenMPI) before starting Python, the symbols are defined and the problem goes away, but this is clearly an ugly solution.

**First attempt at a fix**
With the following patch to setup.py, the problem also goes away, but this makes the setup.py only suitable for OpenMPI, and no longer for Intel MPI

`@@ -187,7 +187,7 @@`

` def get_mpi_flags():`
`-    show_command = os.environ.get('HOROVOD_MPICXX_SHOW', 'mpicxx -show')`
`+    show_command = os.environ.get('HOROVOD_MPICXX_SHOW', 'mpicxx --showme:link')`
`     try:`
`         mpi_show_output = subprocess.check_output(`
`             shlex.split(show_command), universal_newlines=True).strip()`

Note that, with this patch, the .../mpi_lib.so of horovod is now correctly being linked with the libmpi.so of OpenMPI.

Probably, the issue could be fixed combining the above patch with an if-statement that tests whether mpicxx is the Intel MPI mpicxx or OpenMPI mpicxx.

**Comment by alsrgv** [comment]
@casparvl, what output does `mpicxx -show` give you?

On my system I see the following, which does contain `-lmpi`.
```
root@98e2fc0bff76:/# mpicxx -show
g++ -I/usr/local/openmpi-2.1.1/include -pthread -Wl,-rpath -Wl,/usr/local/openmpi-2.1.1/lib -Wl,--enable-new-dtags -L/usr/local/openmpi-2.1.1/lib -lmpi
```

**Comment by alsrgv** [comment]
@casparvl, I see - that makes sense.  We use `mpicxx -show` because it's supported by MPICH as well - https://www.mpich.org/static/docs/v3.1/www1/mpicxx.html

Does specifying HOROVOD_MPICXX_SHOW environment variable with custom show command help in your wrapper case?

**Comment by casparvl** [comment]
How could I completely overlook that environment variable when I looked at the source code... Yes, setting that to 'mpicxx --showme:link' works!

Is it an idea to document somewhere a comprehensive list of all environment variables that Horovod uses? A number are mentioned in the troubleshooting.md, but they don't always stand out (HOROVOD_MPICXX_SHOW is only present in the Note that you apparently get if mpicxx -show fails completely). 

Anyway, thanks a lot for your help!

**Comment by alsrgv** [comment]
@casparvl, can you elaborate when people usually use compiler wrapper, like in your case?  That would help update documentation in a right way.  I also hope that users search for existing issues :-)

**Comment by casparvl** [comment]
@alsrgv, I work on the Dutch national supercomputer and cluster computer. Since these are large, shared systems, we generally have many different versions of the same software installed. Users can change between versions by loading TCL modules. These modules prepend the .../lib and .../include dirs of the corresponding software to custom environment variables (SURFSARA_LIBRARY_PATH and SURFSARA_INCLUDE_PATH). The compiler wrappers ensure that all paths in SURFSARA_LIBRARY_PATH and SURFSARA_INCLUDE_PATH are passed to the compiler through -L and -I options.

**Comment by alsrgv** [comment]
@casparvl, thanks.  Will incorporate this in the next doc update.
