### ISSUE TITLE
Segmentation fault when running the keras_spark_rossmann_estimator.py with MLflow model serving

### ISSUE THREAD

**Issue by JkSelf** [horovod/horovod#2800]
**Environment:**
Framework: (TensorFlow, PyTorch)
Framework version:
Horovod version: v0.21.3
MPI version:
CUDA version:
NCCL version:
Python version: 3.6
OS and version: centos 7
GCC version: 9.3
**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Hi all,

I can run the keras_spark_rossmann_estimator.py in standalone mode with 1 node. But when I integrated with the MLflow model serving by adding the following code, I encountered the segmentation fault issue and cannot find any stack info.
`with mlflow.start_run() as run:   
      keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales_output'])
      mlflow.keras.log_model(keras_model , "horovod keras models")
    mlflow.end_run()`

@tgaddair  Can you help me with this issue? Thanks for your help very much!

**Comment by tgaddair** [comment]
Hey @JkSelf, are you calling `model = keras_model.getModel()` before `mlflow.keras.log_model(model, ...)`? Do you know if the segfault occurs on or before this line?

**Comment by JkSelf** [comment]
@tgaddair 
It is my fault for passing the `keras_model ` to `mlflow.keras.log_model(keras_model , ...)`. And I have not calling the `model = keras_model.getModel()` in my code.

The segfault occurs after successfully execute the `keras_model = keras_estimator.fit(train_df).setOutputCols(['Sales_output'])`.  There is no error in Spark UI after execute the `fit()` method and throw segfault in python side.

**Comment by tgaddair** [comment]
We should try to isolate the part of the code that's raising the error. It sounds like it happens when you call `mlflow.keras.log_model`, is that right? And it still happens when you pass in the result of `keras_model.getModel()`?
