### ISSUE TITLE
Is model parallelism supported for PyTorch?

### ISSUE THREAD

**Issue by liaopeiyuan** [horovod/horovod#2812]
If I write my own multi-GPU model or use `torch.distributed.pipeline.sync.Pipe`, would multi-node training still work with horovod?

**Comment by tgaddair** [comment]
Hey @liaopeiyuan, Horovod can still work in model parallel scenarios. The important thing to watch out for is that every Horovod worker needs to submit the same set of tensors as the others. So we usually implement model parallelism by having the parallelism branch out from the Horovod worker (for example, each Horovod worker gets 2 GPUs).
