### ISSUE TITLE
Segment fault when running the rossman dataset in distribution mode

### ISSUE THREAD

**Issue by JkSelf** [horovod/horovod#2823]
**Environment:**
Framework: (TensorFlow, PyTorch)
Framework version:
Horovod version: v0.21.3
MPI version:
CUDA version:
NCCL version:
Python version: 3.6
OS and version: centos 7
GCC version: 9.3

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
When I run the rossman dateset using distribution mode, I get the following error when connect the hdfs file system.
![image](https://user-images.githubusercontent.com/11972570/113679926-e6997200-96f2-11eb-866f-6053b00b6ce3.png)

The start command is :
![image](https://user-images.githubusercontent.com/11972570/113680438-6a535e80-96f3-11eb-9feb-4509c51db7f0.png)

Spark Version: 2.4
Hadoop Version: 2.7.3
Pyarrow Version: 3.0

@tgaddair Can you help me with this issue? Thanks for your help !

**Comment by JkSelf** [comment]
@tgaddair  Do you have some suggestions? Thanks for your help!

**Comment by tgaddair** [comment]
It's hard to say from the stack trace. Are you able to connect to HDFS using PyArrow without Horovod?

**Comment by JkSelf** [comment]
@tgaddair 
Yes, I can connect to HDFS using PyArrow with and without Horovod.

I found the issue is caused by  `from horovod.tensorflow.keras.callbacks import BestModelCheckpoint` code.

When I run the following code , it can run successfully.
```
from horovod.spark.common.store import Store
if __name__ == '__main__':
    store = Store.create('hdfs://10.1.2.201:9000/horovod-work-dir')
```

But when adding the code `from horovod.tensorflow.keras.callbacks import BestModelCheckpoint` as following, it will throw the above segment fault error.
```
from horovod.spark.common.store import Store
from horovod.tensorflow.keras.callbacks import BestModelCheckpoint
if __name__ == '__main__':
    store = Store.create('hdfs://10.1.2.201:9000/horovod-work-dir')
```

Whether is it a tensorflow  and hadoop version issue or not ?
