### ISSUE TITLE
Task/Actor cannot be scheduled even though resources are available

### ISSUE THREAD

**Issue by cupdike** [horovod/horovod#2827]
On Horovod 0.21.3 (Ray 1.2.0), a WARNING is incorrectly reporting lack of resources trying to run the Horovod/Ray Mnist example (tensorflow2_mnist_ray.py) on SLURM.  It's a warning but it prevents training from running.  It's running on a single node with 40 CPU and 3 GPU.  I launch it like this:

```
# HEAD
srun  --nodes=1  --ntasks=1 -w apl-redd-ai02.datalake.jhuapl.edu --cpus-per-task=5 singularity run ~/horovodDocker/native_horray.sif  ray start  --head  --node-ip-address=30.30.30.30  --port=6379  --redis-password=supersecret  --num-cpus 5 --num-gpus 0  --include-dashboard False  --block &

# WORKER
srun  --nodes=1  --ntasks=1  --cpus-per-task=5 --gres=gpu:1 -w apl-redd-ai02.datalake.jhuapl.edu singularity run ~/horovodDocker/native_horray.sif ray start --address 30.30.30.30:6379  --redis-password=supersecret --num-cpus 5 --num-gpus 0  --block &

# Training script
srun --nodes=1 --ntasks=1 singularity run ~/horovodDocker/native_horray.sif python horray_mnist.py --address 30.30.30.30:6379 --redis_password supersecret
```

I stripped down the RayExecutor to use barely any resources:

```
executor = RayExecutor(settings, num_hosts=1, num_slots=3, use_gpu=False, cpus_per_slot=4)`
```

I'm getting this:

```2021-04-07 14:10:01,526	WARNING worker.py:1107 -- The actor or task with ID ffffffffffffffffa01c95bc3d119e36e40b31b204000000 cannot be scheduled right now. It requires {CPU: 12.000000} for placement, however the cluster currently cannot provide the requested resources. The required resources may be added as autoscaling takes place or placement groups are scheduled. Otherwise, consider reducing the resource requirements of the task.```

Even though there are plenty of resources available:

```
scontrol show node
NodeName=************* Arch=x86_64 CoresPerSocket=12 
   CPUAlloc=12 CPUTot=48 CPULoad=0.16
   AvailableFeatures=(null)
   ActiveFeatures=(null)
   Gres=gpu:3(S:0-1)
   RealMemory=90185 AllocMem=0 FreeMem=6034 Sockets=2 Boards=1
   State=MIXED ThreadsPerCore=2 TmpDisk=0 Weight=1 Owner=N/A MCS_label=N/A
   Partitions=batch 
   BootTime=2020-12-07T20:50:20 SlurmdStartTime=2021-01-15T14:47:14
   CfgTRES=cpu=48,mem=90185M,billing=48,gres/gpu=3
   AllocTRES=cpu=12,gres/gpu=1
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s
```

Any ideas what is causing this?

TIA @richardliaw

**Comment by richardliaw** [comment]
Hi @cupdike I believe the main issue is that you are trying to place 3 workers with 4 CPUs on 1 host, but all of your hosts only have 5 CPUs total. Instead, you should consider placing 3 workers with 4 CPU on *3 separate hosts* (num_hosts=3).

Specifically:

```
RayExecutor(settings, num_hosts=3, num_slots=1, use_gpu=False, cpus_per_slot=4)
```

Could you try to see if that works?

**Comment by cupdike** [comment]
Sorry if I wasn't clear, but there is only a single worker node but it has 48 CPUs (as shown by the CPUTotal=48.  The ray head and worker are each using 6:
```
squeue -j -t R -o '%j %C'
NAME CPUS
singularity 6
singularity 6
```
Which is the CPUAlloc=12.  So there should be 36 CPU available and the training job is asking for 12 (3 slots x 4 CPU).  

Unless I'm missing something, there should be plenty of resources to run it.

**Comment by richardliaw** [comment]
Sorry I think I wasn’t clear. Ray will see each “ray start” command as a
node. So, you’re actually creating 3 Ray “nodes” (on one machine) and Ray
can’t place its workers on any of its “nodes”.

Instead, you should only have 1 ray start command (which will create 1
“node”) and give it 18 CPUs.

Unlike SLURM, ray does not require you to start each worker process via
srun.

**Comment by cupdike** [comment]
Ah, ok.  I will give that a try.  I was loosely following the example in here using which uses srun's for the workers:
https://docs.ray.io/en/master/cluster/examples/slurm-basic.html#slurm-basic

**Comment by cupdike** [comment]
Now it runs--thanks!

So is it correct to say that `start` should only be called once on each compute node, and the total number of RayExecutors should be the total number of CPUs allocated to the job?

**Comment by richardliaw** [comment]
Awesome!

> So is it correct to say that start should only be called once on each compute node

Yes!

> and the total number of RayExecutors should be the total number of CPUs allocated to the job?

Hmm, it should be RayExecutor(
   num_hosts=# compute nodes
   num_cpus * num_slots == # CPUs per compute node
)
