### ISSUE TITLE
 Building horovod - Error Messages

### ISSUE THREAD

**Issue by Nafees-060** [horovod/horovod#2845]
**Environment:**
1. Framework: (TensorFlow, Keras,)
2. Framework version: 2.4.1, 2.3.1
3. Horovod version: trying to install
4. MPI version:
5. CUDA version:   11.2 
6. NCCL version:   2.8.4
7. Python version:  3.8.8 
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version:   4.8.5 
12. CMake version:  2.8.12.2

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/running.rst)? yes
3. If your question is about docker, did you read [this doc] (https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?  yes

**Bug report:**
File Error messages .txt attached 

[Horovod Error Messages.txt](https://github.com/horovod/horovod/files/6333191/Horovod.Error.Messages.txt)

**Comment by chongxiaoc** [comment]
By looking your error file, your system has lots of missing definitions from tensorflow, for example:
```
research/dept8/gds/anafees/anaconda3/lib/python3.8/site-packages/tensorflow/include/tensorflow/stream_executor/dnn.pb.h: In member function 'void stream_executor::dnn::ConvolutionDescriptorProto::set_allocated_name(std::string*)':
    /research/dept8/gds/anafees/anaconda3/lib/python3.8/site-packages/tensorflow/include/tensorflow/stream_executor/dnn.pb.h:1161:9: error: 'struct google::protobuf::internal::ArenaStringPtr' has no member named 'SetAllocatedNoArena'; did you mean 'SetAllocated'?
       name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
             ^~~~~~~~~~~~~~~~~~~
             SetAllocated
```
