### ISSUE TITLE
Elastic horovod raise 'Illegal instruction' on CPU container

### ISSUE THREAD

**Issue by hgx1991** [horovod/horovod#2858]
## Environment
1. tensorflow-gpu 2.0.0
2. horovod 0.20.0
3. openmpi 4.0.3
4. CUDA 10.0
5. cudnn 7.6
6. python 3.6

## Problem
When using elastic horovod, we want driver to run in cpu containers.  But it get an error:
```
Illegal instruction (core dumped)
```
![20210422204232](https://user-images.githubusercontent.com/9511326/115716008-4d818100-a3ab-11eb-989c-799548e0363a.png)

![20210422203959](https://user-images.githubusercontent.com/9511326/115715670-f380bb80-a3aa-11eb-91e7-7e684ee0ca0b.png)

This is the structure of our task. 
Is elastic horovod designed to run drivers in containers that are created on gpu hosts?
Can they run in containers that are created on hosts without GPUs?
![20210422205653](https://user-images.githubusercontent.com/9511326/115718042-54a98e80-a3ad-11eb-8573-aa448f3fd10d.png)
:

**Comment by chongxiaoc** [comment]
hmmm, usually this seems like changing libraries after building horovod.
Did you change mpi libs after installation?

Also, you can run cpus only tests in GPU container.
