### ISSUE TITLE
2 nodes equipped with 8 *v100 slower than 1 node with 8* v100

### ISSUE THREAD

**Issue by keshawnhsieh** [horovod/horovod#2869]
By running the [tf2 synthetic benchmark](https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_synthetic_benchmark.py)
I don't get the proming speed up with 2 nodes equipped with 8 *v100 each compared with 1 node with 8 * v100.

Even stranger, 2 nodes runs slower than 1 node. The results shows below.
1 node with 8 * v100
![image](https://user-images.githubusercontent.com/29997158/116061651-b1f75580-a6b5-11eb-970e-ad5dc7953ab5.png)
2nodes with 16 * v100
![image](https://user-images.githubusercontent.com/29997158/116061682-bc195400-a6b5-11eb-87cd-627a79ae2578.png)
 
I run this demo in [Nvidia NGC Docker ](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_21-03.html#rel_21-03)
The machine I test with is provided by Tencent Cloud.  The specification of machine can be found [here](https://intl.cloud.tencent.com/document/product/560/19700).
![image](https://user-images.githubusercontent.com/29997158/116062699-bc661f00-a6b6-11eb-8590-a6b8d1b378b9.png)

Could this test result caused by limited network bandwidth as shown of 25Gbps?

**Comment by chongxiaoc** [comment]
Is is possible to use Nsight profiler to compare traces?
https://developer.nvidia.com/nsight-systems
