### ISSUE TITLE
How to use horovod when custom training and test with keras.Model?

### ISSUE THREAD

**Issue by Bonsen** [horovod/horovod#2880]
If I define a new model like https://github.com/keras-team/keras-io/blob/master/examples/vision/knowledge_distillation.py and  use my own train_step and val_step, how to use horovod with keras? Should I use it like tensorflow2 example?

**Comment by Bonsen** [comment]
cc @DEKHTIARJonathan @romerojosh @EnricoMi @thuningxu @chengscott

**Comment by DEKHTIARJonathan** [comment]
Please do not tag the whole Horovod team to answer a simple question. Your question is not a critical issue that needs to be seen immediately. 

https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py

**Comment by Bonsen** [comment]
@DEKHTIARJonathan Sorry, i will get it.
If I define train_step and val_step in keras.Model like https://github.com/keras-team/keras-io/blob/master/examples/vision/knowledge_distillation.py and run model.fit, then I can't use the horovod example of keras and I should use tf examples?

**Comment by romerojosh** [comment]
Hi @Bonsen, 
There are also Keras examples using the `model.fit` API, like this one, for reference on how to use Horovod with Keras: https://github.com/horovod/horovod/blob/master/examples/keras/keras_mnist.py
Similarly, there are TF-Keras examples, like this one, if you want to use TF-Keras instead:
https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_keras_mnist.py

**Comment by Bonsen** [comment]
@romerojosh @DEKHTIARJonathan Thanks! I will try it.
