### ISSUE TITLE
Crashing PyTorch loaders with multiple workers and nodes

### ISSUE THREAD

**Issue by henrique** [horovod/horovod#2898]
**Environment:**
1. Framework: (PyTorch)
2. Framework version: 1.6.0 / 1.7.1 / 1.8.1
3. Horovod version: 0.20.0 / 0.21.1 / 0.21.3 (respectively)
4. MPI version: OpenMPI 4.0.1 / cray-mpich-7.7.16 / =
5. CUDA version: 10.1 (docker) / 11.0 (native)
6. NCCL version: 2.8.3
7. Python version: 3.8.5
11. GCC version: 9.3.0
12. CMake version: 3.10.2

**Bug report:**
We have been supporting Horovod for a while (thanks for the great work!) but a user found an issue with the imagenet dataset when using many workers (required to scale the training). It also seems to happen with the default num_workers=4 as in the example, but less often.

The dataloader workers may crash when running pytorch_imagenet_resnet50.py on multiple nodes and multiple forked workers with MPI. The chances of this happen seems to increase when using more nodes and more workers (e.g. 12 workers on 32x 1-gpu nodes).
multiprocessing_context=fork gives our well known segfault.
multiprocessing_context=forkserver (as in the example) sometimes works, but might end up with Bus error/Broken pipe and leaked semaphores:
```
python3.8/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
  File "pytorch_imagenet_resnet50.py", line 68, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File ".../torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File ".../torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File ".../torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File ".../python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File ".../python3.8/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File ".../python3.8/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File ".../python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File ".../python3.8/multiprocessing/popen_forkserver.py", line 58, in _launch
    f.write(buf.getbuffer())
BrokenPipeError: [Errno 32] Broken pipe
python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 14 leaked semaphore objects to clean up at shutdown
```
multiprocessing_context=spawn gets extremely slow, and also crashes.

num_workers=0 solves the issue, but results in a massive IO bottleneck even when setting PyTorch to use lot of threads (e.g. torch.set_num_threads(24)). Therefore, making it unusable.
The native PyTorch DDP doesn't seem to have the same issue, not even with multiprocessing_context=fork, which seems intriguing... 

I've been struggling to understand this for a while, so I wonder if anyone here could give us some idea of what could be causing this?
The idea of forking the workers after the MPI initialisation seems already odd. Btw, we also get these warnings when running without a container:
```
[PE_29]:inet_listen_socket_setup:inet_setup_listen_socket: bind failed port 24389 listen_sock = 6 Address already in use
[PE_29]:_pmi_inet_listen_socket_setup:socket setup failed
```
which disappear when setting PMI_NO_FORK=1  PMI_NO_PREINITIALIZE=1 but that doesn't seem to solve the problem with the dying workers

We are mainly using the pip installation with cray-mpich on SLURM (srun instead of horovodrun), but I was also able to reproduce the errors using horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1 and OpenMPI 4.0.1 (I have to use sarus as we don't have docker in our env but I believe that shouldn't make a difference)
We have 64 GB of RAM on the nodes and 32 GB of /dev/shm so it shouldn't be a memory issue from my calculation (batch size 64/128).
Using the validation dataset for training is enough to reproduce it.

I also was trying to test with Gloo only, but I am not sure how to force Horovod to use it without horovodrun. Setting HOROVOD_GLOO=1 doesn't seem to do the trick (hvd.gloo_built() == True, hvd.gloo_enabled() == False).

Thanks already for any input you can give us!

**Comment by chongxiaoc** [comment]
I saw you tried `HOROVOD_GLOO=1`. But what `horovodrun --gloo`? Is it also failing?

**Comment by henrique** [comment]
Thanks for the reply @chongxiaoc 

Indeed horovodrun detects gloo, but I am not sure how we can use horovodrun with SLURM's srun or mpirun (on multiple nodes)

neither `horovodrun --gloo -np $SLURM_NNODES --hostfile` nor `mpirun horovodrun --gloo -np 1 --hostfile` will work
with MPI/MPICH we simply run `srun python ...` (which executes the command in all nodes simultaneously) but I guess gloo will need the hostfile and I couldn't find an env var for that...

**Comment by chongxiaoc** [comment]
Can this https://towardsdatascience.com/distributed-deep-learning-with-horovod-2d1eea004cb2 help?
They ran a resnet50 using horovod on a supercomputer with SLURM

**Comment by henrique** [comment]
Thanks @chongxiaoc that worked without any problems
We're still chasing the issue with the forkserver on MPI/InfiniBand... it seems to crash often on the first rank before it even loads much data at all. But sometimes it doesn't crash for a very long time.

Another alternative is to use the Nvidia DALI dataloader, which doesn't use forks.

**Comment by henrique** [comment]
anyway, I think it's probably an issue with the Cray stack and not Horovod itself, so we can close this ticket
Thank you!
