### ISSUE TITLE
Supporting ADLS storage

### ISSUE THREAD

**Issue by umashankark** [horovod/horovod#2905]
Currently, access to ADLS (Azure Data Lake filesystem) is not there. Is there any plans of adding support to ADLS in near term ?

**Comment by tgaddair** [comment]
Hey @umashankark, Horovod itself is agnostic to where the data is coming from. One way to use it with ADLS is to use a framework like [Petastorm](https://github.com/uber/petastorm) to read Parquet data. I recently added support for reading from ADLS in v0.10.  Check it out, and let me know if you run into any issues.

**Comment by umashankark** [comment]
Thanks for your suggestions, @tgaddair.  Appreciate some inputs from you on these:
1. In Horovod on Spark  scenario, with Petastorm, Horovod will not be using any intermediate storage - is this understanding correct ?
2. Regarding ADLS in v0.10, I don't see Store classes supporting 'abfs' URI. Can you please point me to details ?
3.  In Horovod on Spark scenario, it should be advisable to  use a distributed data store - is that right ?

**Comment by umashankark** [comment]
TorchEstimator() seems to invoke Petastorm->fsspec->adlfs for accessing ADLS, for reading train data.
Is there anyway to pass authentication parameters (like account_name, storage_options, sas_token) to fsspec ?

**Comment by tgaddair** [comment]
Hey @umashankark, yes you're right the stores have not been updated to use Petastorm's new features. I'm putting together #2927 to address this. Feel free to check it out and let me know how it goes.

**Comment by umashankark** [comment]
Thanks @tgaddair. Will test and update you.
