### ISSUE TITLE
backward_passes_per_step >1, error: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by roshni-kamath** [horovod/horovod#2922]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.13
3. Horovod version: 0.21
4. Python version: 3.8
5. OS and version: Linux

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
I am trying to implement gradient accumulation using:

step = tf.contrib.framework.get_or_create_global_step()
opt = hvd.DistributedOptimizer(opt,backward_passes_per_step=4,average_aggregated_gradients=True)
grads=opt.compute_gradients(total_loss,var_list=tf.trainable_variables())
train_op = opt.apply_gradients(grads_and_vars=grads, global_step=step)

But I get the following error:

File “/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/gradient_aggregation.py”, line 233, in apply_gradients
  flattended_args0 = [item for tup in args[0] for item in tup]
IndexError: tuple index out of range

Is the implementation correct?

**Comment by rb-determined-ai** [comment]
Hi, @roshni-kamath, it looks to me like there's some `*args, **kwargs` magic happening here and there may be a subtle bug.

The horovod DistributedOptimizer is meant to be API-transparent.  The original optimizer has a function like:
```
def apply_gradients(self, grads_and_vars, global_step=None, name=None)
```

the horovod DistributedOptimizer has an API like:
```
def apply_gradients(self, *args, **kwargs)
```

Ultimately, I think when you pass `grads_and_vars=grads`, that value goes into `kwargs`, not `args`, and then later we assume to find it at `args[0]` but it's not there.

Try calling `opt.apply_gradients(grads, global_step=step)` instead and let me know if it works.  If it does, I'll push a fix to make the API-transparency work right.

**Comment by rb-determined-ai** [comment]
Oh @ioga already fixed this in https://github.com/horovod/horovod/pull/2879.

@chongxiaoc we can just close this I think, and the user can update to v0.22.

Full example for verification:
```python
#!/usr/bin/env python3

import tensorflow as tf
import horovod.tensorflow as hvd

ds = tf.data.Dataset.range(100).batch(3, drop_remainder=False)
data = ds.make_one_shot_iterator().get_next()
label = ds.make_one_shot_iterator().get_next()

def build_graph(data, label):
    w = tf.get_variable("weight", [1], dtype=tf.float32, initializer=tf.zeros_initializer)
    out = w * tf.cast(data, tf.float32)
    loss = tf.losses.mean_squared_error(tf.cast(label, tf.float32), out)
    return out, loss

out, loss = build_graph(data, label)
params = tf.trainable_variables()
opt = tf.train.GradientDescentOptimizer(.001)

hvd.init()

step = tf.contrib.framework.get_or_create_global_step()
opt = hvd.DistributedOptimizer(opt, backward_passes_per_step=4, average_aggregated_gradients=True)
grads=opt.compute_gradients(loss,var_list=params)

# works on 0.21 or 0.22
train_op = opt.apply_gradients(grads, global_step=step)

# fails on 0.21, succeeds on 0.22
train_op = opt.apply_gradients(grads_and_vars=grads, global_step=step)
```

**Comment by chongxiaoc** [comment]
sounds good.
FYI @tgaddair
