### ISSUE TITLE
Horovod incompatible with TensorFlow nightly

### ISSUE THREAD

**Issue by tgaddair** [horovod/horovod#2924]
TensorFlow removed `PersistentTensor` from their API in https://github.com/tensorflow/tensorflow/commit/f8153ae87a88586ac1c364116208cfb144c9b64a#diff-b35354f62819de66aaa049a9498cccc261c108a7c488d39e04882110bdee65b5. We rely on this functionality for creating the fusion buffer, which needs to span across multiple ops. We need to find a workaround or work with the TF team to revert this change.

cc @romerojosh @DEKHTIARJonathan

**Comment by tgaddair** [comment]
https://github.com/tensorflow/tensorflow/issues/49467

**Comment by DEKHTIARJonathan** [comment]
Alright let me take it to the right people.
