### ISSUE TITLE
3D CNN model with large input image size

### ISSUE THREAD

**Issue by Hoileong89** [horovod/horovod#293]
Hi, I would like to train a 3D model with large input image size (e.g. 512x512x512), which can't train using a single GPU. How could I use horovod to train my model if I have 4 GPUs?

**Comment by alsrgv** [comment]
@Hoileong89, are you not able to train it on a single GPU because you're running out of GPU memory, or because it's too slow?

**Comment by Hoileong89** [comment]
I am running out of GPU memory. I am training it based on a FCN model.

**Comment by alsrgv** [comment]
@Hoileong89, one way to solve this is to do hybrid model/data parallel approach - place the first couple of layers on one GPU and the rest on another, or split among 4 GPUs.  See [this thread](https://github.com/uber/horovod/issues/96#issuecomment-360964021) for more examples.
