### ISSUE TITLE
[MAC OS] libc++abi.dylib: terminating with uncaught exception of type gloo::EnforceNotMet

### ISSUE THREAD

**Issue by ericxsun** [horovod/horovod#2940]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: 2.4.1
3. Horovod version: 0.22.0
4. MPI version: (NO, with gloo)
5. CUDA version: 
6. NCCL version:
7. Python version: 3.7
8. Spark / PySpark version:
9. Ray version:
10. OS and version: macOS Big Sur 11.2.3
11. GCC version:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
```
12. CMake version: 3.20.1

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.
```python
import horovod.tensorflow as hvd

hvd.init()
```

then, the python command line terminated, with the following exception message:
```
libc++abi.dylib: terminating with uncaught exception of type gloo::EnforceNotMet: [enforce fail at /private/var/folders/l3/18pljl2s6q3d3h_kk1y5nv8h0000gn/T/pip-install-xy0ow8d0/horovod_98a796e5f3cf40929f5431d36dccb56b/third_party/compatible_gloo/gloo/transport/uv/device.cc:129] rp != nullptr. Unable to find address for: 314159
```

In other platform: linux (cpu), linux(NCCL2 + GPU), works fine.

So why such error occurred in mac, and how to solve it? Any help will be highly appreciated.

**Comment by chongxiaoc** [comment]
Can this help? https://github.com/horovod/horovod/issues/1341

**Comment by ericxsun** [comment]
> Can this help? #1341

Thanks a lot. I've tried, but not work.

**Comment by tgaddair** [comment]
I ran into a similar issue with my Mac: `rp != nullptr. Unable to find address for: 314159`.

In my case, at least for the first issue, I needed to add the hostname to `/etc/hosts`, so something like:

```
127.0.0.1    314159
```
