### ISSUE TITLE
How to install Gloo on Ubuntu 18.04v?

### ISSUE THREAD

**Issue by harrytrinh96** [horovod/horovod#2941]
I was trying to train my model on different hosts using this command:

`HOROVOD_WITH_TENSORFLOW=1  horovodrun --gloo -np 10 -H workstation-1:4,localhost:4 python train.py
`
However, I got this error:
`ValueError: Gloo support has not been built.  If this is not expected, ensure CMake is installed and reinstall Horovod with HOROVOD_WITH_GLOO=1 to debug the build error.`

I searched google how to install gloo but found nothing. Could someone guide me how to install it on ubuntu 18.04?

**Comment by chongxiaoc** [comment]
1. `Gloo` comes with submodule of horovod. run `git submodule update --init --recursive` to checkout all submodules. Enable `HOROVOD_WITH_GLOO=1` during installation.
2. If you want to install gloo from source: https://github.com/facebookincubator/gloo

**Comment by harrytrinh96** [comment]
I was stucking with 
`cmake ../ -DBUILD_TEST=1 -DGTEST_ROOT=/some/path (if using custom install)
` step. How do i assign to DGTEST_ROOT?

**Comment by chongxiaoc** [comment]
Is option 1 working for you?
