### ISSUE TITLE
the reference Dockerfile is not find

### ISSUE THREAD

**Issue by xxyp** [horovod/horovod#2946]
To streamline the installation process on GPU machines, we have published the reference Dockerfile so you can get started with Horovod in minutes. The container includes Examples in the /examples directory.

Pre-built Docker containers with Horovod are available on DockerHub.

Building
Before building, you can modify Dockerfile.gpu to your liking, e.g. select a different CUDA, TensorFlow or Python version.

$ mkdir horovod-docker-gpu
$ wget -O horovod-docker-gpu/Dockerfile https://raw.githubusercontent.com/horovod/horovod/master/Dockerfile.gpu
$ docker build -t horovod:latest horovod-docker-gpu
For users without GPUs available in their environments, we've also published a CPU Dockerfile you can build and run similarly.

**Comment by tgaddair** [comment]
Hey @xxyp, I created a PR to update the docs, but in the meantime you can find the new Dockefiles here: https://github.com/horovod/horovod/tree/master/docker
