### ISSUE TITLE
error: Your TensorFlow version is outdated.  Horovod requires tensorflow>=1.1.0

### ISSUE THREAD

**Issue by wangguangyuan** [horovod/horovod#295]
HOROVOD_NCCL_HOME=/home/guangyuan/nccl_2.2.13-1+cuda9.0_x86_64 HOROVOD_WITH_TENSORFLOW=1 H                                  OROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod --user
Collecting horovod
  Downloading https://files.pythonhosted.org/packages/ea/3d/4f36c30798d6feb5e81234693a8e5f4b57e02539603ffb1bc8af47b723b7                                  /horovod-0.13.3.tar.gz (93kB)
    100% |████████████████████████████████| 102kB 423kB/s
Requirement already satisfied: cffi>=1.4.0 in ./anaconda3/lib/python3.6/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.6/site-packages (from cffi>=1.4.0->horovod) (2.18)
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /home/guangyuan/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/                                  pip-install-el91qsr7/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f                                  .close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-90zucdl6/install-record.txt --single-ve                                  rsion-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    running build_ext
    gcc -pthread -B /home/guangyuan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wa                                  ll -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/guangyuan/anaconda3/include/python3.6m -c build/temp.linux-x86                                  _64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /home/guangyuan/anaconda3/compiler_compat -L/home/guangyuan/anaconda3/lib -Wl,-rpath=/home/g                                  uangyuan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o b                                  uild/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    gcc -pthread -B /home/guangyuan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wa                                  ll -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/local/cuda/include -I/home/guangyuan/anaconda3/include/python3.                                  6m -c build/temp.linux-x86_64-3.6/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /home/guangyuan/anaconda3/compiler_compat -L/home/guangyuan/anaconda3/lib -Wl,-rpath=/home/g                                  uangyuan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cuda.o -L/usr/lo                                  cal/cuda/lib -L/usr/local/cuda/lib64 -lcudart -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.so
    gcc -pthread -B /home/guangyuan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wa                                  ll -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/guangyuan/nccl_2.2.13-1+cuda9.0_x86_64/include -I/usr/local/cu                                  da/include -I/home/guangyuan/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_nccl.cc -o bu                                  ild/temp.linux-x86_64-3.6/test_compile/test_nccl.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /home/guangyuan/anaconda3/compiler_compat -L/home/guangyuan/anaconda3/lib -Wl,-rpath=/home/g                                  uangyuan/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_nccl.o -L/home/g                                  uangyuan/nccl_2.2.13-1+cuda9.0_x86_64/lib -L/home/guangyuan/nccl_2.2.13-1+cuda9.0_x86_64/lib64 -L/usr/local/cuda/lib -L/                                  usr/local/cuda/lib64 -lnccl_static -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.so
    error: Your TensorFlow version is outdated.  Horovod requires tensorflow>=1.1.0

    ----------------------------------------
Command "/home/guangyuan/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-el91qsr7/hor                                  ovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(co                                  de, __file__, 'exec'))" install --record /tmp/pip-record-90zucdl6/install-record.txt --single-version-externally-managed                                   --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-el91qsr7/horovod/

**Comment by wangguangyuan** [comment]
my tensorflow version is 1.6.0

**Comment by alsrgv** [comment]
@wangguangyuan, can you provide an output of `pip freeze` immediately after the failure?
