### ISSUE TITLE
PyTorch sparse allreduce fails with torch nightly

### ISSUE THREAD

**Issue by tgaddair** [horovod/horovod#2961]
Repro:

```
pip install --no-cache-dir --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
# install horovod
horovodrun -np 2 pytest -vs "test/parallel/test_torch.py::TorchTests::test_async_sparse_allreduce"
```

The test hangs, which has been causing test failures.

cc @chongxiaoc @romerojosh 

@chongxiaoc can you or @irasit take a look?

**Comment by chongxiaoc** [comment]
hmmm, only for nightly? I'm curious what's recent change from pytorch nightly.

**Comment by chongxiaoc** [comment]
Without fusion, it can pass:

(hvd-py3.7) chongxiaoc@chongxiaoc-C02DL7WPMD6R parallel % horovodrun --fusion-threshold-mb 0 -np 2 pytest -vs test_torch.py::TorchTests::test_async_sparse_allreduce
