### ISSUE TITLE
Horovod in industry application

### ISSUE THREAD

**Issue by janhuang6** [horovod/horovod#299]
My team is evaluating using Horovod. We want to know is Horovod ready for industrial application, or is it more academic for research purpose? Does anyone use it in industrial customer facing product and how did that do? Thanks!

**Comment by alsrgv** [comment]
@janhuang6, is the product a platform for deep learning training or deep learning is used to train the model used in the product?

In either case, many companies like [AWS](https://aws.amazon.com/blogs/machine-learning/aws-deep-learning-amis-now-include-horovod-for-faster-multi-gpu-tensorflow-training-on-amazon-ec2-p3-instances/), [Databricks](https://docs.databricks.com/applications/deep-learning/distributed-deep-learning/horovod/index.html), [IBM](https://datascience.ibm.com/docs/content/analyze-data/ml_dlaas_distributed.html), and many others include it in their production DL training platforms.  We're using it internally at Uber as the only way of distributed deep learning for both experimental and production training.

**Comment by janhuang6** [comment]
Thank you alsrgv for replying!
We are doing both: building a platform for deep learning and also use deep learning to train.
Understand that your team is developing Horovod. Is that right the latest and greatest code from your developer is publicly available (after some reasonable and necessary time for it to go public, of course)?
Do you have any restriction for others to use your open source Horovod? Thanks!

**Comment by alsrgv** [comment]
@janhuang6, great!  Yes, Horovod development is done in the open and there are no restrictions for the usage, as dictated by the [Apache 2 license](https://github.com/uber/horovod/blob/master/LICENSE).
