### ISSUE TITLE
Running Horovod on p2.8xlarge (8 GPUs)

### ISSUE THREAD

**Issue by pablete** [horovod/horovod#300]
I am using the latest Dockerfile from master (as of June 8 2018)
And running the examples (say /examples/tensorflow_mnist.py) with

```
mpirun -np 8 -H localhost:8 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python tensorflow_mnist.py
```

Works fine, uses all gpus (8) and finish as expected.
But the output is full of errors like these:

```
[96c7e3d99641:24984] Read -1, expected 122880, errno = 1
[96c7e3d99641:24986] Read -1, expected 122880, errno = 1
[96c7e3d99641:24988] Read -1, expected 122880, errno = 1
[96c7e3d99641:24987] Read -1, expected 122880, errno = 1
[96c7e3d99641:24983] Read -1, expected 122880, errno = 1
[96c7e3d99641:24985] Read -1, expected 122880, errno = 1
```

I do not know if this is introduced by horovod , nccl, or it is a glitch of the hardware used.

Is this normal? 
where should I look in order to find out if this error is important or not?

Thanks

**Comment by alsrgv** [comment]
@pablete, it's [expected](https://github.com/uber/horovod/blob/master/docs/docker.md).  If you run docker in privileged mode, it will disappear, but AFAIK it's not harmful.

**Comment by pablete** [comment]
Thanks for the response, dropping a --privileged=true fixed it.

 (ie `nvidia-docker run --priviledged=true -i -t uber/horovod /bin/bash`)

**Comment by luomai** [comment]
Hi @alsrgv I got the same error when running in a Linux server as a root user. Is it also expected?
