### ISSUE TITLE
[Horovod Keras] flow_from_directory Error with Multi GPUS

### ISSUE THREAD

**Issue by burness** [horovod/horovod#302]
When I use a large dataset, I got an error like this:
![image](https://user-images.githubusercontent.com/3112825/41193236-f8df388a-6c3b-11e8-8ee7-2b7ac54a2c34.png)
I got an different image size with a dataset, It seems to be an bug with keras flow_from_directory, Have you met it and how to resolve it  ?

**Comment by alsrgv** [comment]
@burness, any idea why different workers find a different number of images?

**Comment by burness** [comment]
@alsrgv  Maybe this is the bug of keras `preprocessing.image.DirectoryIteror`. The `theadpool` cause the count error, I have fixed this with 1 thead but it too slow

**Comment by alsrgv** [comment]
@burness, which version of Keras are you using?

**Comment by burness** [comment]
@alsrgv  2.1.6

**Comment by alsrgv** [comment]
@burness, so if you use the single thread, do all threads report the same # of examples?  Do you see an exception?

**Comment by burness** [comment]
@alsrgv  As shown in the picture, when I use  all thread, it report the diferent examples, and No exception happened, It maybe the bug with Keras Multi-thread and Ceph

**Comment by burness** [comment]
yes， It's ok when use single thread and train succssfully. 

```
train_gen = image.ImageDataGenerator(width_shift_range=config.width_shift_range, height_shift_range=config.height_shift_range, zoom_range=config.zoom_range, horizontal_flip=config.horizontal_flip, vertical_flip=config.vertical_flip, preprocessing_function=preprocess_image)
train_iter = train_gen.flow_from_directory(config.train_dir, batch_size=config.batch_size, target_size=config.target_size)
```
I change here in `/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py` to use single thread.
![image](https://user-images.githubusercontent.com/3112825/41574068-73e1d0ba-73b2-11e8-881e-5b62a7cecd4f.png)

**Comment by alsrgv** [comment]
@burness, nothing really jumps out in the source code as a potentially suspicious.  What kind of data store are you reading those images from?  Is it local disk, NFS?

**Comment by burness** [comment]
@alsrgv we use the ceph to store our dataset
