### ISSUE TITLE
build image by dockerfile (following), then run 'pytorch_imagenet_resnet50.py',however I get 'RuntimeError: DataLoader worker (pid 18255) is killed by signal: Killed.'

### ISSUE THREAD

**Issue by ybbthou8** [horovod/horovod#3046]
MAINTAINER Jerry_Hou
ARG PYTORCH_VERSION=1.8.1+cu102
ARG PYTORCH_LIGHTNING_VERSION=1.2.9
ARG TORCHVISION_VERSION=0.9.1+cu102
ARG NCCL_VERSION=2.9.6-1+cuda10.2

# Python 3.7 is supported by Ubuntu Bionic out of the box
ARG PYTHON_VERSION=3.7

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

RUN sudo sed -i s/archive.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list
RUN sudo apt-get clean

RUN sudo apt-get update && sudo apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        cmake \
        g++-7 \
        git \
        curl \
        ca-certificates \
        libjpeg-dev \
        libpng-dev \
        librdmacm1 \
        libibverbs1 \
        ibverbs-providers \
        openjdk-8-jdk-headless \
        openssh-client \
        openssh-server \
    && sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*

RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends libnccl2=${NCCL_VERSION} libnccl-dev=${NCCL_VERSION}

# Install Open MPI
RUN sudo wget --no-check-certificate --progress=dot:mega -O /tmp/openmpi-3.0.0-bin.tar.gz http://github.com/horovod/horovod/files/1596799/openmpi-3.0.0-bin.tar.gz && \
    cd /usr/local && \
    sudo tar -zxf /tmp/openmpi-3.0.0-bin.tar.gz && \
    sudo ldconfig && \
    sudo mpirun --version

# Allow OpenSSH to talk to containers without asking for confirmation
RUN sudo mkdir -p /var/run/sshd
RUN sudo touch /etc/ssh/ssh_config.new && \
         sudo chmod 777 /etc/ssh/ssh_config.new &&\
         sudo chmod 777 /etc/ssh/ssh_config &&\
         sudo cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
         sudo echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new &&\
         sudo mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

#RUN curl -O http://bootstrap.pypa.io/get-pip.py && \
#    python get-pip.py && \
#    rm get-pip.py

# Install PyTorch, TensorFlow, Keras and MXNet
RUN pip install --no-cache-dir \
    torch==${PYTORCH_VERSION} \
    torchvision==${TORCHVISION_VERSION} \
    -f https://download.pytorch.org/whl/${PYTORCH_VERSION/*+/}/torch_stable.html -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
RUN pip install --no-cache-dir pytorch_lightning==${PYTORCH_LIGHTNING_VERSION} -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com

# Install Horovod
RUN bash -c "HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir horovod -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com"

# Check all frameworks are working correctly. Use CUDA stubs to ensure CUDA libs can be found correctly
#RUN python -c "import horovod.torch as hvd; hvd.init()"

**Comment by Tixxx** [comment]
Hi @ybbthou8 thanks for reporting the issue. I tried building and running a container from your dockerfile and it ran fine. From your error message, it looks like one of the loader processes is killed by the system which most likely indicates out of resource. A couple of suggestions here:
1. make sure when you start up your container, a sufficient amount of shared memory is assigned to it. i.e. docker run (other options) --shm-size **128g**.
2. try using the main process to load data. i.e. set num_workers in pytorch loader to 0. If it runs fine with 0, you may want to use a small number of processes to load.
