### ISSUE TITLE
All rank is zero

### ISSUE THREAD

**Issue by feifeibear** [horovod/horovod#307]
I tried to install horovod on multiple-node system, each of which has one GPU card. The system uses slurm to submit task.

My code is very simple:

```
import tensorflow as tf
import horovod.tensorflow as hvd
hvd.init()
print(hvd.local_rank())
print(hvd.size())
```

My submit script test.py is like this:

```
#!/bin/bash -l
#
#SBATCH --job-name=dist_google_benchmark
#SBATCH --time=00:30:00
#SBATCH --nodes=8
#SBATCH --constraint=gpu

# load virtualenv
export WORKON_HOME=~/virtualenv3
source $WORKON_HOME/pytorch-horovod/bin/activate

srun -N 8 -n 8 python test.py

deactivate

```

The output is 
0
8
0
8
0
8
0
8
0
8
0
8
0
8
0
8

all process is assigned to rank 0!!!

**Comment by alsrgv** [comment]
@feifeibear, makes sense - `hvd.local_rank()` is the rank within node.  You should use `hvd.rank()` to extract rank of the process across all nodes.

**Comment by feifeibear** [comment]
@alsrgv  Thank you for your quick response. It solves my problem. I still have two questions.
1. On multi-node system, where each node has one card, should I set the device as local_rank for all node?
torch.cuda.set_device(hvd.local_rank())

2. should I compile openmpi3.0 with --with-cuda

**Comment by alsrgv** [comment]
@feifeibear,
1. Doesn't matter, it's going to be no-op since there's only one GPU.  Doesn't hurt.
2. It's not necessary, better to skip as NCCL could potentially conflict with CUDA-aware MPI in certain scenarios.
