### ISSUE TITLE
Extension horovod.tensorflow has not been built.

### ISSUE THREAD

**Issue by franz101** [horovod/horovod#314]
Has anyone an Idea how to fix this? Would be really thankful ;)

ImportError                               Traceback (most recent call last)
<ipython-input-1-a577c1fce70c> in <module>()
      1 import tensorflow as tf
----> 2 import horovod.keras as hvd

~/.local/lib/python3.6/site-packages/horovod/keras/__init__.py in <module>()
     17 import tensorflow as tf
     18 
---> 19 import horovod.tensorflow as hvd
     20 from horovod.common import init
     21 from horovod.common import size

~/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py in <module>()
     38 from horovod.common import check_extension
     39 
---> 40 check_extension('horovod.tensorflow', 'HOROVOD_WITH_TENSORFLOW', __file__, 'mpi_lib')
     41 
     42 from horovod.tensorflow.mpi_ops import allgather

~/.local/lib/python3.6/site-packages/horovod/common/__init__.py in check_extension(ext_name, ext_env_var, pkg_path, *args)
     40         raise ImportError(
     41             'Extension %s has not been built.  If this is not expected, reinstall '
---> 42             'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
     43 
     44 

ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.

**Comment by alsrgv** [comment]
@franz101, can you try reinstalling Horovod via:
```
$ HOROVOD_WITH_TENSORFLOW=1 [other flags you used before] pip install -v --no-cache-dir horovod
```

It will fail.  Please paste the log here.

**Comment by franz101** [comment]
Thanks for your quick reply:
My flags are as follows:
HOROVOD_GPU_ALLREDUCE=NCCL  HOROVOD_WITH_TENSORFLOW=1 HOROVOD_NCCL_HOME=/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64 pip install --no-cache-dir horovod

No returns the following error:
`Command "/students/home/user/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7i0fytgz/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ipevqd2g/install-record.txt --single-version-externally-managed --compile" failed with error code -11 in /tmp/pip-install-7i0fytgz/horovod/`

**Comment by franz101** [comment]
`gcc -pthread -shared -B /students/home/user/anaconda3/compiler_compat -L/informatik2/students/home/6krekele/anaconda3/lib -Wl,-rpath=/students/home/user/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_nccl.o -L/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64/lib -L/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64/lib64 -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lnccl_static -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.so`

that is the last output from the compiler...  problem might be i have no root access?

**Comment by alsrgv** [comment]
@franz101, can you share the full output starting with `pip install` command?

**Comment by franz101** [comment]
Sure! Can you see a problem here? Can also post the installation of the other dependencies.
Or the tensorflow Version etc.

user@ubuntu:~$ pip uninstall horovod -y
Uninstalling horovod-0.13.4:
Successfully uninstalled horovod-0.13.4
user@ubuntu:~$ HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_NCCL_HOME=/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64 pip install --no-cache-dir horovod
Collecting horovod
  Downloading https://files.pythonhosted.org/packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz (93kB)
    100% |████████████████████████████████| 102kB 2.9MB/s 
Requirement already satisfied: cffi>=1.4.0 in ./anaconda3/lib/python3.6/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.6/site-packages (from cffi>=1.4.0->horovod) (2.18)
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /students/home/user/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2oesp7mg/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-oa6dy9oz/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    running build_ext
    gcc -pthread -B /students/home/user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/students/home/user/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /students/home/user/anaconda3/compiler_compat -L/students/home/user/anaconda3/lib -Wl,-rpath=/students/home/user/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    gcc -pthread -B /students/home/user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/local/cuda/include -I/students/home/user/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cuda.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /students/home/user/anaconda3/compiler_compat -L/students/home/user/anaconda3/lib -Wl,-rpath=/students/home/user/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lcudart -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.so
    gcc -pthread -B /students/home/user/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64/include -I/usr/local/cuda/include -I/students/home/user/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_nccl.cc -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /students/home/user/anaconda3/compiler_compat -L/students/home/user/anaconda3/lib -Wl,-rpath=/students/home/user/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_nccl.o -L/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64/lib -L/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64/lib64 -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lnccl_static -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.so
    
    ----------------------------------------
Command "/students/home/user/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2oesp7mg/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-oa6dy9oz/install-record.txt --single-version-externally-managed --compile" failed with error code -11 in /tmp/pip-install-2oesp7mg/horovod/

**Comment by franz101** [comment]
Running python setup.py install

I get:

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -shared -B /students/home/user/anaconda3/compiler_compat -L/students/home/user/anaconda3/lib -Wl,-rpath=/students/home/user/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_nccl.o -L/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64/lib -L/students/home/user/ncc/nccl_2.2.13-1+cuda9.0_x86_64/lib64 -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lnccl_static -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.so

Segmentation fault

**Comment by franz101** [comment]
I think it is because openmpi 3.0 is I. The export variable but openmpi 1.0 is in usr/ and used instead of the new one.

**Comment by alsrgv** [comment]
@franz101, if you do `export PATH=/path/to/mpi3:$PATH`, you should be able to force it to use OpenMPI 3.0 instead of the system one.
