### ISSUE TITLE
Questions about Running Horovod on Aurora

### ISSUE THREAD

**Issue by gtbai** [horovod/horovod#315]
Hi Alex,

In [this issue](https://github.com/uber/horovod/issues/60), you mentioned that you are running Horovod on Mesos cluster with Aurora, which is exactly what I am trying to do now. However, there are still some places I have no clue about:

1. In the issue (https://github.com/uber/horovod/issues/60) you mentioned that Aurora spins up only **one** container per host. Is there a way to explicitly specify that?
2. How can I know where all the containers "will" locate so that I could correctly parameterize the `mpirun` command in the Aurora job configuration? It seems to me that only after you submit the job to Aurora will Mesos assign each task to a specific host?
3. Shall each container be launched by a seperate Aurora job, or one Aurora job launches a multi-task job, and each task corresponds to one container?

Lots of questions, thanks for your time!

**Comment by alsrgv** [comment]
@gtbai, we're not running in Aurora anymore - we've switched to an internal scheduler we built on top of Mesos, and to Kubernetes.  That said, here are ideas for your questions:

1. We ensured that by specifying # gpus per task = # gpus on host.
2. We had a custom registry where every container registers its IP address and ports.  The container that executes mpirun waits for all other containers to register, and then it knows all the addresses and ports.
3. We launched a single job with a number of instances.

**Comment by gtbai** [comment]
@alsrgv Thanks for the enlightening ideas.

For 1, it seems that this demands for a specialized cluster. If we do that on a shared cluster, then the tasks may never get assigned?

For 2, does that mean you have a server-like program running on some host, and then each container client will register with it, after which it will broadcast the ip and port info to all containers?

Previously I saw it from somewhere on the Internet that you can fetch the host address info from Zookeeper after tasks get assigned, do you think this is a feasible approach?

**Comment by alsrgv** [comment]
@gtbai,

1. That was part of the reason we went away from Aurora to a scheduler that supports gang scheduling.

2. Yes, Zookeeper can be used for that purpose.

**Comment by gtbai** [comment]
@alsrgv I see. Still,

For 1, are there any specific reasons to keep only one container on each host? It seems to me that running multiple gradient workers on a host can get the work done as well.

For 2, may I ask why you did not choose to use ZooKeeper to get the host address info, while decided to write some extra registry logic?

Thanks.

**Comment by alsrgv** [comment]
@gtbai,

1. We still run one process per GPU, but we run all processes in a single container to allow CUDA IPC.  CUDA IPC does not work between containers.

2. The registry service we used was a wrapper around ZK and Cassandra.  It provides convenient REST API for such registration and querying, and it's used by multiple projects.

**Comment by gtbai** [comment]
@alsrgv ,

For 1: Got it. How about if I only train with CPUs? Will communication be a problem if I run multiple containers on a host?

For 2: That is a cool idea, sounds very neat!

**Comment by alsrgv** [comment]
@gtbai,

1. There's a similar problem - by default containers will not be able to communicate with each other using shared memory.

2. No plans at the moment.  It should be pretty straightforward to re-implement it with Zookeeper.

**Comment by gtbai** [comment]
@alsrgv ,

For 1: In this case, are containers using loopback networks to communicate with each other? And this would only hurt the performance, while not break down the training process, right?

For 2: Could you please provide me with some pointers to relative docs? I tried to google it for a while but did get much...

Thanks!

**Comment by alsrgv** [comment]
1. That's right.

2. See e.g. http://blog.arungupta.me/zookeeper-microservice-registration-discovery.  It's a Java implementation, but the ideas are quite generic and can be implemented in Python as well.

**Comment by gtbai** [comment]
@alsrgv, Thanks a lot for your great help!

I suspect I would encounter more issues as I try further to run Horovod on Aurora. Considering this, as well as to preserve the context, I would leave this issue open for now.

**Comment by gtbai** [comment]
@alsrgv , one question:

You mentioned that processes in different containers could not communicate via IPC. I am wondering, why did you choose to run horovod within containers then? Why not directly run native processes on the agent host, so that different processes on the same host could communicate via shared mem?

Thanks.

**Comment by gtbai** [comment]
I see, thanks! @alsrgv
