### ISSUE TITLE
Horovod on CPU taking 80% total time.

### ISSUE THREAD

**Issue by jojivk73** [horovod/horovod#3163]
**Environment:**
1. Framework: TensorFlow
2. Framework version:2.7
3. Horovod version:0.22
4. MPI version:2.1.1
5. CUDA version:
6. NCCL version:
7. Python version: 3.6
8. Spark / PySpark version:
9. Ray version:
10. OS and version: Ubuntu 18.05
11. GCC version: 7.5
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
      Found simlar questions but for GPU. Didn't solve the CPU issue.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
     Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?
 Yes
**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

  I am runinng a model with horovod using following command on CPU (no GPUs available)

mpirun --allow-run-as-root -np 4 \
             --bind-to none \
             -map-by slot  \
             -mca btl_tcp_if_exclude lo,docker0 \
             -mca pml ob1 \
             -mca btl ^openib \
             -x NCCL_DEBUG=INFO \
             -x HOROVOD_MPI_THREADS_DISABLE=1 -x PATH \
             -x HOROVOD_CYCLE_TIME=1 \
             -x HOROVOD_FUSION_THRESHOLD=16777216 \
             python train.py job_param.json perf_param.json
             
             
Horovod take 80% of time. Profile shows almost 100% allreduce time is spent on NEGOTIATE_BROADCAST. Any help appreciated. The issues showed after some changes to the original model.

**Comment by Tixxx** [comment]
Are you doing a broadcast at every step for each parameter in your model? AFAIK, allreduce shouldn't do NEGOTIATE_BROADCAST.
