### ISSUE TITLE
allgather() method needs to be changed 

### ISSUE THREAD

**Issue by Mahbubalam4545** [horovod/horovod#3169]
**Is your feature request related to a problem? Please describe.**
The output of horovod.torch.allgather(tensor, name=None) is a tensor of concatenation of tensor on different rank processes. While the output of torch.distributed.all_gather(tensor_list, tensor) is a tensor list.

Pytorch output (Two GPUs):
before all_gather(): Input tensors
#tensor([1, 2]) # Rank 0
#tensor([3, 4]) # Rank 1
After all_gather(): Output tensor list
#[tensor([1, 2]), tensor([3, 4])] # Rank 0
#[tensor([1, 2]), tensor([3, 4])] # Rank 1

Horovod output (Two GPUs):
before all_gather(): Input tensors
#tensor([1, 2]) # Rank 0
#tensor([3, 4]) # Rank 1
After all_gather(): Output tensor
#tensor([1, 2, 3, 4]) # Rank 0
#tensor([1, 2, 3, 4]) # Rank 1

How can I get the output as in pytorch using horovod.torch.allgather(tensor, name=None)?

**Describe the solution you'd like**
I've tried passing two-dimensional tensors into hvd.allgather(). However, it didn't wrok as the pytorch.
Input:
tensor([[7, 8]], device='cuda:3')
tensor([[3, 4]], device='cuda:1')
tensor([[5, 6]], device='cuda:2')
tensor([[1, 2]], device='cuda:0')

Output:
tensor([[1, 2], [3, 4], [5, 6], [7, 8]], device='cuda:0')
tensor([[1, 2], [3, 4], [5, 6], [7, 8]], device='cuda:1')
tensor([[1, 2], [3, 4], [5, 6], [7, 8]], device='cuda:3')
tensor([[1, 2], [3, 4], [5, 6], [7, 8]], device='cuda:2')

**Describe alternatives you've considered**

**Additional context**

**Comment by maxhgerlach** [comment]
https://github.com/horovod/horovod/discussions/3167
