### ISSUE TITLE
Is NCCL needed if installing horovod with MVAPICH ??

### ISSUE THREAD

**Issue by JKChun** [horovod/horovod#317]
I want to use MVAPICH to peform allreduce operation on horovod, then do I still need to install NCCL?

All I need to do is to use the command $ HOROVOD_GPU_ALLREDUCE=MPI pip install --no-cache-dir horovod ?

How does the system know that my MPI is MVAPICH? (because I have OpenMPI and MVAPICH installed in my computer)

**Comment by alsrgv** [comment]
@JKChun, in this case, you don't need to have NCCL.  In order to point the installation to MVAPICH, make sure that `which mpirun` and `which mpicxx` point to MVAPICH installation, i.e. it must be in `$PATH`.

**Comment by fightbob** [comment]
> thanks, it works.

Hi @JKChun ,  horovod with MVAPICH has better performance  than openmpi?
