### ISSUE TITLE
Horovod stalled ranks when using hvd.SyncBatchNorm in pytorch amp mode

### ISSUE THREAD

**Issue by wuyujiji** [horovod/horovod#3181]
Excuse me! Recently I use hvd.SyncBatchNorm to train pytorch resnet50, followed [this pr](https://github.com/horovod/horovod/pull/3018/files) and find the phenomenon that the horovod stalled rank when using pytorch amp mode. When disabling amp, it workes normly. All above experiments using `single machine 8gpus`. 

![image](https://user-images.githubusercontent.com/25579435/134865726-2712a1c6-30b1-43da-8abd-ad9b61896ab6.png)

### Environment
horovod: 0.19.2
pytorch: 1.7.0
nccl: 2.7.8

### The relevant code
```python
from torchvision import models
model = models.resnet50(norm_layer=hvd.SyncBatchNorm)
optimizer = torch.optim.SGD(model.parameters(), lr=args.learning_rate, momentum=args.momentum, weight_decay=args.weight_decay)
optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=model.named_parameters())

# amp code
scaler = amp.grad_scaler.GradScaler()
...
with amp.autocast_mode.autocast():
     output = model(data)
     loss = loss_fn(output)
scaler.scale(loss).backward()
scaler.step(optimizer)
scaler.update()
```

The reason is the incompatibility between pytoch amp and horovod?

**Comment by chongxiaoc** [comment]
I don't expect horovod to be working with torch.amp.
Did you have a working example without `SyncBatchNorm` ?

**Comment by Tixxx** [comment]
Horovod hasn't integrated with amp yet which will result in incorrect results. But in your case, the incompatibility is actually between amp and our syncBatchNorm function, hvd.syncBatchNorm registers a custom forward function which cannot be autocasted by amp so it's not called at all in forward pass. It needs to be decorated @custom_fwd when we fully support amp in horovod.
