### ISSUE TITLE
Horovod Timeline & Scalability

### ISSUE THREAD

**Issue by SHEELE41** [horovod/horovod#3189]
**Environment:**
1. Framework: (TensorFlow, Keras)
2. Framework version: Tensorflow-gpu 2.1.0 / Keras 2.3.1
3. Horovod version: 0.21.3
4. MPI version: OpenMPI 4.1.1 / MPI API 3.1.0
5. CUDA version: 10.1
6. NCCL version: 2.5.7.1
7. Python version: 3.7
8. Spark / PySpark version:
9. Ray version:
10. OS and version: Ubuntu 16.04
11. GCC version: 7.3.0
12. CMake version: 3.16.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Yes
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Question:**
Hi, I'm using Horovod for scaling some deep learning project with two servers. (Server1 has three 1080Ti GPUs and Server2 has two 1080Ti GPUs)

This is performance measurement results of [my code](https://github.com/SHEELE41/Benchmarks/blob/03e5505cf77f690c60959d902d6a38a3dabde535/Pilot1/P1B2/p1b2_baseline_keras2.py).

![image](https://user-images.githubusercontent.com/24821303/135569863-5a83a97f-b4d7-4b7d-901e-508569e4bbee.png)

np 1-3 means that the number of GPUs was used only on Server1(Single Node, Multi-GPU), and distributed-np2~5 means that the number of GPUs was used including Server1 and Server2(Multi-Node, Multi-GPU).

I used Infiniband for Node to Node Communication.

As shown in table, total runtime doesn't decrease proportionately when increasing number of workers and I already know that this is mostly due to constant data loading times.

I increased the number of epochs to decrease data loading time rate in total time, but still showed low improvement rate.

![image](https://user-images.githubusercontent.com/24821303/135572383-c5e65826-3761-418b-85fa-d6ec47bd2f61.png)

I thought Remainder Time (Total - Data Loading - Horovod communication) is same with GPU computation time and it looks to decrease well (1 / GPUs).

So, I have three questions.

1. I saw that each case has same number(8) of allreduce panes regardless of number of GPUs at Horovod timeline. Is not number of panes determined by number of GPUs? Then what determines it? (I've got same number of panes at tensorflow2_keras_mnist.py)

![image](https://user-images.githubusercontent.com/24821303/135575169-e04156e4-c00e-484d-8909-d256a9d4fe6d.png)

2. Each pane has different total allreduce time and ALLREDUCE looks like wrapping all of sub works (NCCL_ALLREDUCE, QUEUE, MEMCPY_IN_FUSION_BUFFER, etc... ). So I estimated total allreduce time by getting Total Wall Duration time of first row in HorovodAllreduce_grads_0 pane (biggest total allreduce time, not HorovodAllreduce_grads_x_0). Is it right way to estimate Horovod communication time?

![image](https://user-images.githubusercontent.com/24821303/135575963-b3c4085a-3f90-49ac-9673-b345131f3f12.png)

![image](https://user-images.githubusercontent.com/24821303/135577080-b6d6f814-e720-4696-a7e1-b5a08c1f28fa.png)

3. How can I reduce horovod communication time? I'm not sure I use Horovod in the right way.

Thanks for reading.

**Comment by PurvangL** [comment]
@SHEELE41

Thank you for posting issue. Did you find any solution for your problem or any learning you got, would be helpful if you share.
