### ISSUE TITLE
one question about benchmarks

### ISSUE THREAD

**Issue by yogurfrul** [horovod/horovod#320]
I want to reproduce the benchmarks from [benchmark](https://github.com/uber/horovod/blob/master/docs/benchmarks.md)

But I don't know if horovod with tcp is horovod_mpi which is installed by 
HOROVOD_GPU_ALLREDUCE=MPI pip install --no-cache-dir horovod

and horovod with RDMA is horovod_nccl which is installed by 
HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod

**Comment by alsrgv** [comment]
@yogurfrul, these benchmarks were run with `HOROVOD_GPU_ALLREDUCE=NCCL` for both TCP and RDMA.  Assuming your NIC supports RDMA, you can turn off RDMA (and run TCP) by setting `-x NCCL_IB_DISABLE=1`.
