### ISSUE TITLE
Events in Horvovd TimeLine 

### ISSUE THREAD

**Issue by abidmalikwaterloo** [horovod/horovod#321]
I am looking into the JSON file: I see the following events:

1. Negotiated Borat cast
2. MPI_Bcast
3. MPI_ALL_REDUCE
4. MEMCOPY_OUT_FUSION
5. NEGOCIATED_ALL_REDUCE

These events are associated with a time stamp and process ID (PID). Does Pid mean CUDA thread?
If I need to calculate the total communication time for the ring All reduce approach, which event should I look into? What is MEMCOPY_OUT_FUSE?

**Comment by alsrgv** [comment]
@abidmalik1967, `pid` in Horovod Timeline does not relate to CUDA threads, but rather to tensor name.  Each tensor gets a unique `pid`, e.g.:
```
 {"name": "process_name", "ph": "M", "pid": 2, "args": {"name": "HorovodBroadcast_global_step_0"}},
```

Realistically, you should count time of `MEMCPY_IN_FUSION_BUFFER`, `MPI_ALLREDUCE` and `MEMCPY_OUT_FUSION_BUFFER` as a communication.   More details are available here - https://github.com/uber/horovod/blob/master/docs/timeline.md

**Comment by abidmalik1967** [comment]
@alsrgv Should all the flags be present in the trace? For example, I could n't find WAIT_FOR_DATA etc. I am using NCCL and couldn't find NCCL_ALLREDUCE in the trace.

**Comment by alsrgv** [comment]
@abidmalik1967, if you see `MPI_ALLREDUCE` and don't see `WAIT_FOR_DATA` and you're reducing GPU tensors, that means that Horovod was not compiled with NCCL.  What command did you use to install Horovod?

**Comment by abidmalik1967** [comment]
@alsrgv I used the following:

HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/sdcc/u/amalik/Tensorflow/nccl_2.1.15-1+cuda9.0_x86_64 pip install --user --no-cache-dir horovod

**Comment by alsrgv** [comment]
@abidmalik1967, looks reasonable.  Can you re-install horovod with these settings just to make sure?  Also, do you see GPU utilization spike up during your tests?  Last, you can pass `device_dense='/gpu:0'` option to `hvd.DistributedOptimizer()` to make sure allreduce is placed on GPU.

**Comment by abidmalik1967** [comment]
@alsrgv it works now. Now I can see other flags that are related to NCCL.

**Comment by zarzen** [comment]
hey @alsrgv 
Thanks for you previous clarification about the communication time. But why negotiate_allreduce time is not counted as communication time? Currently, I often observe a longer time spend on `negotiate_allreduce` comparing to `MPI_Allreduce`, is this reasonable?

**Comment by tgaddair** [comment]
Hey @zarzen, if you network is fast or your model is small, or you have imbalanced performance between the workers, it's possible for long negotiation phases.
