### ISSUE TITLE
Segmentation fault in horovod_shutdown when running a job along several nodes

### ISSUE THREAD

**Issue by msdlr** [horovod/horovod#3224]
**Environment:**
1. Framework: tensorflow-**cpu**
2. Framework version: 2.6.0
3. Horovod version: v0.23.0
4. MPI version: 4.1.2 (locally built)
5. CUDA version: None - I want to use CPU training to get information about the MPI communications.
6. NCCL version: None - Same as above.
7. Python version: 3.9.6 (Installed via pyenv, **I don't have root access** on this cluster I try to run Horovod on) 
8. Spark / PySpark version: None
9. Ray version: None
10. OS and version: Ubuntu 16.04.3 LTS
11. GCC version: 5.4.0
12. CMake version: 3.18.4

Hello, I'm trying to execute the benchmark `tf_cnn_benchmarks.py` as follows:

```
mpirun --display-map \
  $TRANSP \
 -bind-to none -map-by node \
 -x LD_LIBRARY_PATH -x PATH -x HOROVOD_MPI_THREADS_DISABLE=1 \
  python $benchmark --variable_update horovod --batch_size 64 --horovod_device cpu --device=CPU
```

I don't specify `-N` or `-np` parameters to `mpirun` because they are passed by Slurm (I configured ompi with the `--with-slurm` option, although the issue persisted before and after that). When running other toy MPI programs everything works out of the box this way. I need to use the `mpirun`-type command because I use a wrapper to it which uses PMPI and folllows the same syntax; so using `horovodrun` is out of question.

The program executes correctly when running on a single cluster node, however, when I run it over several nodes I get a segmentation fault before finishing:

```
Thread 0x00007fd1c07f9700 (most recent call first):
  File "/home/msanchez/.pyenv/versions/3.9.6/lib/python3.9/site-packages/horovod/common/basics.py", line 149 in shutdown
Fatal Python error: Segmentation fault
```
I only get the trace this deep in calls, so I guess the library it references is somehow not being appropriately dyn-linked?

I have the setup automated because some other colleages may need to run horovod too, and asure we have the same environment: 

```
$ pip3 install --no-cache-dir --upgrade tensorflow-cpu

export HOROVOD_WITH_MPI=1
export HOROVOD_WITHOUT_GLOO=1
	
export HOROVOD_WITH_TENSORFLOW=1
export HOROVOD_WITHOUT_PYTORCH=1
export HOROVOD_WITHOUT_MXNET=1

export HOROVOD_CPU_OPERATIONS=MPI
```

I've tried insalling both via pip3 and building the source material:

```
$ git clone --recursive https://github.com/horovod/horovod.git /tmp/horovod_$USER
$ cd /tmp/horovod_$USER
$ python3 setup.py clean build sdist
$ pip3 install dist/horovod*tar.gz
```

```
pip3 install --no-cache-dir horovod[tensorflow]
```

When I clone the repo I do have the C++ code to build the library:

```
$ git clone https://github.com/horovod/horovod.git--recursive /tmp/horovod_$USER
$ cd /tmp/horovod_$USER
$ grep -iRI "horovod_shutdown"
horovod/common/basics.py:        self.MPI_LIB_CTYPES.horovod_shutdown()
horovod/common/operations.cc:void horovod_shutdown() {
horovod/common/operations.h:void horovod_shutdown();
```

My `PATH` variable does contain Python, Python3, pip, pip3 (the ones installed via pyenv), ompi on `~/.local/bin`
My `LD_LIBRARY_PATH` includes `~/.local/lib` for ompi. Maybe there's a directory I'm missing? I'm checking standard and error output from compilation and I don't see any `.so` files being generated.

When I check the Horovod build everything seems okay.
```
$ horovodrun --check-build
Horovod v0.23.0:

Available Frameworks:
    [X] TensorFlow
    [X] PyTorch
    [ ] MXNet

Available Controllers:
    [X] MPI
    [ ] Gloo

Available Tensor Operations:
    [ ] NCCL
    [ ] DDL
    [ ] CCL
    [X] MPI
    [ ] Gloo
```
This is the location horovodrun is installed at: 
```
$ which horovodrun 
/home/msanchez/.pyenv/shims/horovodrun
```
Any help would be appreciated.

**Comment by Tixxx** [comment]
Hi @msdlr thanks for reporting the issue, could you try with -map-by slot instead of node? We recommend easing the resource assignment for horovod([doc](https://horovod.readthedocs.io/en/stable/mpi_include.html#mpirun)), otherwise the behavior is non-deterministic on different topologies.

**Comment by msdlr** [comment]
Hello @Tixxx. First of all sorry for taking so long to answer.
I changed to map by slot but it does not matter. I forgot to mention that the tasks assignment is taking N nodes with just one task per node for the moment. I still get the segmentation fault. Interestingly, every node gives a different address for the fault.

```
Thread 0x00007f9634e5e700 (most recent call first):
  File "/home/msanchez/.pyenv/versions/3.9.6/lib/python3.9/site-packages/horovod/common/basics.py", line 149 in shutdown
Fatal Python error: Segmentation fault

Thread 0x00007f6ed789b700 (most recent call first):
  File "/home/msanchez/.pyenv/versions/3.9.6/lib/python3.9/site-packages/horovod/common
/basics.py", line 149 in shutdown
Fatal Python error: Segmentation fault

Thread 0x00007fc97409d700 (most recent call first):
  File "/home/msanchez/.pyenv/versions/3.9.6/lib/python3.9/site-packages/horovod/common/basics.py", line 149 in shutdown
Fatal Python error: Segmentation fault

Thread 0x00007f276a7e7700 (most recent call first):
  File "/home/msanchez/.pyenv/versions/3.9.Fatal Python error: Segmentation fault

Thread 0x00007faab4c7c700 (most recent call first):
  File "/home/msanchez/.pyenv/versions/3.9.6/lib/python3.9/s6/lib/python3.9/site-packages/horovod/common/basics.py", line 149 in shutdite-packages/horovod/common/basics.py", line 149 in shutdownown
```
The output is interlaced but it is readable.
