### ISSUE TITLE
CUDA OOM when using horovod.torch to training multi-machine's task

### ISSUE THREAD

**Issue by wuyujiji** [horovod/horovod#3247]
Excuse me! Recently I met the strange problem. The original code uses pytorch DDP, when fixing `single_gpu_batch_size=4`, the `1 machine 8gpus` （total batch size is 32）and `2 machines 16gpus` (total batch size is 64) both work normally. After modifying into horovod and fixing `single_gpu_batch_size=4 `too, `the 1 machine 8gpus` （total batch size is 32）works normally., but the `2 machines 16gpus` (total batch size is 64) causes CUDA OOM:

<img width="1164" alt="截屏2021-10-28 下午8 12 20" src="https://user-images.githubusercontent.com/25579435/139252997-8c8cd62a-cc2e-4be3-9ae6-d3ac7e5aeed5.png">

What reasons could cause this problem? Looking forward to your reply!

### Environment:
Horovod: 0.19.2 or 0.22.1
PyTorch: 1.7.1
NCCL: 2.7.8
CUDA: 11.0

**Comment by chongxiaoc** [comment]
can you share reproducible examples?
