### ISSUE TITLE
Support NCCL for Elastic Horovod

### ISSUE THREAD

**Issue by vycezhong** [horovod/horovod#3254]
The documentation says that Elastic Horovod only works with Gloo. But NCCL is the state-of-the-art collective communication library with GPUs and has been widely adopted in distributed data-parallel DNN training. Therefore, I hope Elastic Horovod can will support NCCL. BTW, I wonder why you choose Gloo rather than NCCL. 

> Horovod >= 0.20.0 with Gloo support (install Horovod using HOROVOD_WITH_GLOO=1 to ensure it is installed)

**Comment by maxhgerlach** [comment]
Hi @vycezhong,

if NCCL is available, all distributed Horovod operations that actually transfer sizable amounts of data (Allreduce, Allgather, Alltoall, Broadcast) will use NCCL. This is true independently from whether Horovod runs in elastic mode or not.

Besides that, some extra communication between Horovod processes is necessary to coordinate those high-volume transfers. This coordination is implemented with MPI and Gloo, but MPI is not available for elastic Horovod. These only require really low-bandwidth communication with negligible performance impact.

Does this address your concerns?

**Comment by vycezhong** [comment]
I see. Thanks!
