### ISSUE TITLE
Unable to load most recent checkpoint for Pytorch and Pytorch lightning Estimator

### ISSUE THREAD

**Issue by kamalsharma2** [horovod/horovod#3268]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.8.1
3. Horovod version: 0.23.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version: 3.8
8. Spark / PySpark version: 3.1.2
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

**Bug report:**
In case of pytorch lightning estimator, the _read_checkpoint() API does not return the latest checkpoint stored in the run path. 
Reason: Pytorch lightning estimator calls store.get_checkpoints() which looks for a folder named 'checkpoint' in run path while there is no folder named checkpoint, instead there is a temp folder generated via tempfile.TemporaryDirectory()

In case of pytorch estimator, the checkpoint stored in run path is not overwritten if multiple iterations are done using the same run path, which leads to _load_checkpoint() API returning the stale checkpoint.

**Comment by chongxiaoc** [comment]
I don't think `_read_checkpoint ` is working, at least for lighting estimator.
cc @irasit

**Comment by irasit** [comment]
I think it should work for lighting estimator. Not working only if the model graph changed outside the __init__() of the LightningModule.

**Comment by irasit** [comment]
nvm, I see a PR is made.
