### ISSUE TITLE
[Ray] hvd.size() incorrect in 2GPU x 1Instance case for lightning + ray

### ISSUE THREAD

**Issue by irasit** [horovod/horovod#3278]
**Environment:**
1. Framework:  PyTorch + lightningSparkEstimator
2. Framework version: 1.5
3. Horovod version: current
4. MPI version: 
5. CUDA version:
6. NCCL version:
7. Python version: 3.6.9
8. Spark / PySpark version: 2.4
9. Ray version: 2.0
10. OS and version:
11. GCC version:
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Find a problem in 2GPU x 1Instance case for lightning+ray. Seems the hvd.size() is only 1 even it specified 2 GPU x 1 instance in ray.
```
RayClientDLContext num_workers:1 gpus_per_worker:2 job_config.max_workers:1 cpus_per_horovod_worker:40
and we got 35735 steps,
```
Train rows: 1786757465, Train batch size: 50000, Train_steps_per_epoch: 35735
which should be 17867 steps. hvd.size() should be 2, but instead, ray only start 1 horovod process.
```
_train_steps_per_epoch = int(math.floor(float(train_rows) / batch_size / hvd.size()))
```
log is here: https://code.uberinternal.com/P296321

It is unlikely related to lighning. because lightning trainer is not started yet. Also lightning trainer should not affect hvd.size() , aka, how many horovod instance are created. The problem is most likely at the place where Ray started horovod process.

I do not think the issue is in the place to creating the context, but more likely in the ray.remote to create horovod workers.
If 2GPU x 1 instance is configured, it is correct for ray to start 1 ray worker, but that worker need to start 2 horovod process in [here](https://github.com/horovod/horovod/blob/0715c2210647a515a8c49b1f72f575880e522269/horovod/spark/lightning/estimator.py#L415) and each will call the remote [train function](https://github.com/horovod/horovod/blob/0715c2210647a515a8c49b1f72f575880e522269/horovod/spark/lightning/remote.py#L97)

Suspecting the error in [here](https://github.com/horovod/horovod/blob/0715c2210647a515a8c49b1f72f575880e522269/horovod/ray/strategy.py#L182), we should create a separate worker for each GPU ?

**Comment by richardliaw** [comment]
What is `num_workers` here? 

If it is RayExecutor(num_workers) then you will get 1 process. If you want 2 GPUs on 1 single physical machine, you can do `num_workers=2, gpus_per_worker=1`.

**Comment by irasit** [comment]
yes, `num_workers=1, gpus_per_worker=2` that is the config we give to RayExecutor. And it is expected for ray to start only 1 instance. 

If I configure `num_workers=2, gpus_per_worker=1`, how Ray guarantee they are from a same physical machine? 

Normally for horovod, if we want to start the 2 GPU in 1 instance, we can do
```horovodrun -np 2 python train.py```
But seems Ray is only creating 1 process.

**Comment by richardliaw** [comment]
workers == "processes" for Ray. 

If you really want colocation, you should be able to do:

```
num_workers=2
num_workers_per_node=1
num_gpus_per_worker=1
```

That being said, you only have 1 container right? If you have 1 container, all horovod/ray processes will be started within the container

**Comment by irasit** [comment]
Is node == container? For 2GPU in 1 container case, shouldn't it be like:
```
num_workers=2
num_workers_per_node=2
num_gpus_per_worker=1
```

For current test only 1 container. but layer we may need to run 2GPU x 4 container, in that case we should set up like this, right?
```
num_workers=8
num_workers_per_node=2
num_gpus_per_worker=1
```
And ray will figured out that it needs 4 containers?

**Comment by richardliaw** [comment]
Ah sorry; yes. that's right.

**Comment by irasit** [comment]
Got it, thanks.

**Comment by tgaddair** [comment]
@irasit, sounds like this isn't a bug in Horovod on Ray, can we close this issue?
