### ISSUE TITLE
performance drops with 128 GPUS

### ISSUE THREAD

**Issue by abidmalikwaterloo** [horovod/horovod#328]
I am using ImageNet data with Alexnet with Horovod. With  64 GPUS image/sec is 16000 and it drops to 8000 images/sec with 128 GPUs. Batch size is 128 and I am using K80. Any comments

**Comment by abidmalik1967** [comment]
[hostname_239227_128_128_k80.pdf](https://github.com/uber/horovod/files/2126863/hostname_239227_128_128_k80.pdf)
@alsrgv network seems okay as no more crash with more than 100 nodes. I am attaching the output for your information.

**Comment by alsrgv** [comment]
@abidmalik1967, you can try to use an early version of hierarchical allreduce (#329):

Install:
```
$ [regular flags] pip install -v --no-cache-dir git+https://github.com/uber/horovod@hierarchical_allreduce
```

Use:
```
$ mpirun [regular flags] -x HOROVOD_HIERARCHICAL_ALLREDUCE=1 [program]
```

Depending on how well your MPI works with multithreading + RDMA, you may also benefit from forcing it to use a single thread:
```
$ mpirun [regular flags] -x HOROVOD_HIERARCHICAL_ALLREDUCE=1 -x HOROVOD_MPI_THREADS_DISABLE=1 [program]
```

**Comment by abidmalik1967** [comment]
@alsrgv OK. I will try this one. https://github.com/uber/horovod/blob/master/docs/benchmarks.md results use synthetic data. Did you try with ImageNet? Do the synthetic data have the same effect on system performance (especially on I/0) as real data?

**Comment by alsrgv** [comment]
@abidmalik1967, assuming the input pipeline is not bottlenecked and CPU is able to do all the data augmentation fast enough, it should not be an issue.  I saw around 5% performance degradation with real data.

**Comment by abidmalik1967** [comment]
@alsrgv I think we are looking at performance portability problem here. The cluster here doesn't have NVLink. However, NCCL2+PCIe should degrade the performance that much. What OpenMP did you use for the experimentation? I am using OpenMPI 3 built with gnu compiler. I see that you used some option for MPI. Are these essential for performance enhancement? I see time per epoch about 2 min. with 64 GPUs and shot up to  10 min with 128. I am assuming that Horovod might still be doing the good work. But, computation time and I/O time managed by  Tensorflow pipeline might be the bottleneck.

**Comment by alsrgv** [comment]
@abidmalik1967, I'm wondering if the network may have hotspots or inconsistent behavior over time.  Can you try to install Horovod with hierarchical allreduce and check whether it makes it better or worse?

**Comment by abidmalik1967** [comment]
@alsrgv It seems we are looking at the performance variability issue here. This is well known in scientific simulations. Running scientific workflow on large core gives different runtime performance when running at a different time because of network and other infrastructure behavior. I was able to see throughput around 25000 images/sec using 128 GPUs with Alexnet when the job was allowed to run during the weekend. I wonder if anyone has observed this behavior with machine learning application before. I will check the hierarchical approach as well.

**Comment by abidmalik1967** [comment]
@alsrgv Do I have to install hierarchical all reduce above the horovod framework?

I am trying to reinstall horovod again and getting the following error:

---

 export HOROVOD_NCCL_INCLUDE=/home/amalik/nccl_2.1.4-1+cuda8.0_x86_64 
(/home/amalik/tenENV) [amalik@node04 ~]$ export HOROVOD_NCCL_LIB=/home/amalik/nccl_2.1.4-1+cuda8.0_x86_64 
(/home/amalik/tenENV) [amalik@node04 ~]$  pip install --no-cache-dir horovod
Collecting horovod
  Downloading https://files.pythonhosted.org/packages/8a/1b/43a2a16e05db68cfbc9eefee0d6af6066eb2a32f512a596371b3f104b48e/horovod-0.13.4.tar.gz (93kB)
    100% |████████████████████████████████| 102kB 4.0MB/s 
Requirement already satisfied: cffi>=1.4.0 in ./tenENV/lib/python2.7/site-packages (from horovod) (1.11.5)
Requirement already satisfied: pycparser in ./tenENV/lib/python2.7/site-packages (from cffi>=1.4.0->horovod) (2.18)
mxnet-cu90 1.1.0 requires requests==2.18.4, which is not installed.
mxnet-cu90 1.1.0 has requirement numpy<=1.13.3, but you'll have numpy 1.14.5 which is incompatible.
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /home/amalik/tenENV/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i2t3Hr/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6KDXcg/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
    creating build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch
    creating build/lib.linux-x86_64-2.7/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-2.7/horovod/common
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    running build_ext
    mpicc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/amalik/tenENV/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /home/amalik/tenENV/compiler_compat -L/home/amalik/tenENV/lib -Wl,-rpath=/home/amalik/tenENV/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -L/home/amalik/tenENV/lib -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
    mpicc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/local/cuda/include -I/home/amalik/tenENV/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cuda.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cuda.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -B /home/amalik/tenENV/compiler_compat -L/home/amalik/tenENV/lib -Wl,-rpath=/home/amalik/tenENV/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -L/home/amalik/tenENV/lib -lcudart -o build/temp.linux-x86_64-2.7/test_compile/test_cuda.so
    mpicc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/amalik/nccl_2.1.4-1+cuda8.0_x86_64/include -I/home/amalik/nccl_2.1.4-1+cuda8.0_x86_64 -I/usr/local/cuda/include -I/home/amalik/tenENV/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_nccl.cc -o build/temp.linux-x86_64-2.7/test_compile/test_nccl.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    build/temp.linux-x86_64-2.7/test_compile/test_nccl.cc:1:18: fatal error: nccl.h: No such file or directory
     #include <nccl.h>
                      ^
    compilation terminated.
    error: NCCL 2.0 library or its later version was not found (see error above).
    Please specify correct NCCL location with the HOROVOD_NCCL_HOME environment variable or combination of HOROVOD_NCCL_INCLUDE and HOROVOD_NCCL_LIB environment variables.
    
    HOROVOD_NCCL_HOME - path where NCCL include and lib directories can be found
    HOROVOD_NCCL_INCLUDE - path to NCCL include directory
    HOROVOD_NCCL_LIB - path to NCCL lib directory
    
    ----------------------------------------
Command "/home/amalik/tenENV/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i2t3Hr/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6KDXcg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-i2t3Hr/horovod/
--------

I exported the variables for NCCL.

**Comment by alsrgv** [comment]
@abidmalik1967, it's definitely possible to have variability when the system is used by multiple workloads.

**Comment by hewei1990102** [comment]
@alsrgv I have tried ` HOROVOD_HIERARCHICAL_ALLREDUCE=1` this option with new horovod, which effect is not going well. The speed decreses significantly from around 400 images/sec to 85 images/sec with a cluster of 256 P40 GPUs. Our training model is Alexnet running with Openmpi, NCCL and GPUDirect RDMA. Have you tested that large cluster before?
