### ISSUE TITLE
Error when trying to install horovod

### ISSUE THREAD

**Issue by n-balla** [horovod/horovod#3306]
Hello,
I've been working on this for awhile, but couldn't figure it out yet. I would appreciate your help.

I am still not able to install horovod, although I did install all the requirements specified in the documentation. 

I am getting this long error:

> Installing collected packages: psutil, cloudpickle, cffi, horovod
    Running setup.py install for psutil ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Munira\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Munira\\AppData\\Local\\Temp\\pip-install-_cqd15u3\\psutil_f9f6130583a240c5833aaefb1d9da5e6\\setup.py'"'"'; __file__='"'"'C:\\Users\\Munira\\AppData\\Local\\Temp\\pip-install-_cqd15u3\\psutil_f9f6130583a240c5833aaefb1d9da5e6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Munira\AppData\Local\Temp\pip-record-o4cdua9y\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Munira\AppData\Local\Programs\Python\Python310\Include\psutil'
         cwd: C:\Users\Munira\AppData\Local\Temp\pip-install-_cqd15u3\psutil_f9f6130583a240c5833aaefb1d9da5e6\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.10
    creating build\lib.win32-3.10\psutil
    copying psutil\_common.py -> build\lib.win32-3.10\psutil
    copying psutil\_compat.py -> build\lib.win32-3.10\psutil
    copying psutil\_psaix.py -> build\lib.win32-3.10\psutil
    copying psutil\_psbsd.py -> build\lib.win32-3.10\psutil
    copying psutil\_pslinux.py -> build\lib.win32-3.10\psutil
    copying psutil\_psosx.py -> build\lib.win32-3.10\psutil
    copying psutil\_psposix.py -> build\lib.win32-3.10\psutil
    copying psutil\_pssunos.py -> build\lib.win32-3.10\psutil
    copying psutil\_pswindows.py -> build\lib.win32-3.10\psutil
    copying psutil\__init__.py -> build\lib.win32-3.10\psutil
    creating build\lib.win32-3.10\psutil\tests
    copying psutil\tests\runner.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_aix.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_bsd.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_connections.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_contracts.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_linux.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_memleaks.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_misc.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_osx.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_posix.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_process.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_sunos.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_system.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_testutils.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_unicode.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\test_windows.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\__init__.py -> build\lib.win32-3.10\psutil\tests
    copying psutil\tests\__main__.py -> build\lib.win32-3.10\psutil\tests
    running build_ext
    building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Munira\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Munira\\AppData\\Local\\Temp\\pip-install-_cqd15u3\\psutil_f9f6130583a240c5833aaefb1d9da5e6\\setup.py'"'"'; __file__='"'"'C:\\Users\\Munira\\AppData\\Local\\Temp\\pip-install-_cqd15u3\\psutil_f9f6130583a240c5833aaefb1d9da5e6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Munira\AppData\Local\Temp\pip-record-o4cdua9y\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Munira\AppData\Local\Programs\Python\Python310\Include\psutil' Check the logs for full command output.
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\Munira\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.<

I tried to reinstall the most recent g++ but still getting the same error.

Can anyone help please?

Thank you,

**Comment by n-balla** [comment]
my device specification:
Processor	Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz   2.90 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by n-balla** [comment]
@tgaddair I would really appreciate your help.

Also, I am very new to this. I've been reading the documentation for the past few days, but I still need some help. Is there anyway to hire someone to help me to setup a mini distributed environment in a single machine (using horovod with tensorFlow)? I wrote a new class for compression, that I need to test. 
Thanks a lot!

**Comment by maxhgerlach** [comment]
Hi @n-balla, you can't use Horovod on Windows.

**Comment by floatshadow** [comment]
Similar error on Debian 11 with Pytorch @n-balla @maxhgerlach

**Comment by maxhgerlach** [comment]
That's a very different error message and doesn't match this thread. It also does not look related to NCCL. Is this with PyTorch master or with a released version? We might have a build problem with nightly torch at the moment.

**Comment by floatshadow** [comment]
@maxhgerlach  Much thanks : )
I have 2 Telsa K40m to profile different multi-GPU strategies on models
As CC 3.5 is not supported by pytorch, we compile pytorch from source with conda

I clone from official github repo last month and  built the 1.10 released version with gcc 10.2.1

**Comment by maxhgerlach** [comment]
@floatshadow, I just took a look at this again. You might want to try again with the current master version of Horovod. The dependence on `THCudaCheck` has been removed in November (to fix build issues with torch):  #3242
