### ISSUE TITLE
[Error] horovod.common.exceptions.HorovodInternalError: ncclCommInitRank failed: unhandled system error

### ISSUE THREAD

**Issue by RossStream** [horovod/horovod#3343]
Hello, I am using the latest horovod docker for training deep learning models:

**Environment:**
1. Framework: (PyTorch)
2. Framework version:
3. Horovod version: Horovod v0.22.1
4. MPI version: mpirun (Open MPI) 3.0.0
5. CUDA version: cuda_11.2
6. NCCL version:
7. Python version: Python 3.7.5
10. OS and version: Ubuntu 18.04
11. GCC version: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
12. CMake version: cmake version 3.10.2

**Checklist:**
1. Did you search issues to find if somebody asked this question before? -- Yes, but not help.
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? -- Yes.
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? -- Yes
4. Did you check if you question is answered in the [troubleshooting guide] -- Yes (https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**

Hello, I am using the latest horovod docker for training deep learning models on a single machine:

I run the following command:
$ nvidia-docker exec -it stoic_hermann bash
root@d7944d7xxxx: /PATH/TO/TRAIN/CODE# horovodrun -np 6 -H localhost:6 python train.py

AND got the error like:
[1,3]<stddiag>:[d7944d77ef3c:16492] Read -1, expected 27600, errno = 1
[1,4]<stddiag>:[d7944d77ef3c:16493] Read -1, expected 27601, errno = 1
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/local/lib/python3.7/dist-packages/horovod/torch/mpi_ops.py", line 878, in synchronize
[1,0]<stderr>:    mpi_lib.horovod_torch_wait_and_clear(handle)
[1,0]<stderr>:RuntimeError: ncclCommInitRank failed: unhandled system error

Full error report:
[log-sub.txt](https://github.com/horovod/horovod/files/7806535/log-sub.txt)

May I ask how to solve this problem?
Thanks!!

Best,
Ross.

**Comment by maxhgerlach** [comment]
Some troubleshooting ideas:

- How did you build the container?
- What's the output of `nvidia-smi` in your container?
- You could set the environment variable `NCCL_DEBUG=info` to get more useful log messages.

**Comment by RossStream** [comment]
@maxhgerlach 
Thank you for your advice!
And I tried you ideas:
1. I build the container by:
   $ nvidia-docker run --gpus all -v /home:/home -it horovod/horovod:latest bash
2. the output of `nvidia-smi` :
![image](https://user-images.githubusercontent.com/89726673/148047527-161cba8b-c79a-4f40-8536-a0c78a7c8b48.png)

3. Set the environment variable `NCCL_DEBUG=info`  and the useful log messages:  
[log-debug.txt](https://github.com/horovod/horovod/files/7807015/log-debug.txt)

4. Output of `tests/parallel/test_torch.py`:
[log-test.txt](https://github.com/horovod/horovod/files/7807036/log-test.txt)

Do you know where the problem is?
Thank you!

Best,
Ross.

**Comment by maxhgerlach** [comment]
For the unit tests you lack `[test]` dependencies: https://horovod.readthedocs.io/en/stable/contributors_include.html#build-and-install

Anyway, these log messages seem to indicate a problem with how you run your container
```
[1,5]<stdout>:d7944d77ef3c:19539:19564 [5] include/shm.h:28 NCCL WARN Call to posix_fallocate failed : No space left on device
[1,5]<stdout>:d7944d77ef3c:19539:19564 [5] NCCL INFO include/shm.h:41 -> 2
[1,5]<stdout>:
[1,5]<stdout>:d7944d77ef3c:19539:19564 [5] include/shm.h:48 NCCL WARN Error while creating shared memory segment nccl-shm-recv-35e7cd01966b7127-0-4-5 (size 9637888)
```
Maybe checkout https://github.com/NVIDIA/nccl/issues/290 or similiar

**Comment by RossStream** [comment]
@maxhgerlach 
Thanks for your quick reply!

I am trying to run a new container with a larger shared memory size (24G) and will give you feedback when I get any results.

Hope the problem could be solved.
Thanks!

**Comment by maxhgerlach** [comment]
That's great, thanks for reporting back! Good luck with your trainings! :)
