### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [horovod/horovod#3354]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by EnricoMi** [comment]
Hi @JamieSlome,

thanks for getting in touch. We are working out a secure channel. Please bear with us a bit more.

Regards,
Enrico

**Comment by JamieSlome** [comment]
@EnricoMi - no worries, feel free to take your time. In the meantime, you can view the report directly here:

https://huntr.dev/bounties/7e50397b-dd63-4bb5-b56d-704094a7da45/

It is private and only accessible to maintainers with repository write permissions. Let me know if you have any questions regarding it!

**Comment by EnricoMi** [comment]
This has been attended to. Thanks for reporting.
