### ISSUE TITLE
can horovod work only with Gloo，without MPI?

### ISSUE THREAD

**Issue by yongqiangz** [horovod/horovod#3355]
I'm trying install horovod with tensorflow, I read the doc and found out that horovod controller has two options: MPI and Gloo, so i try to use Gloo only, my cmd is
```
HOROVOD_WITHOUT_MPI=1  HOROVOD_WITH_GLOO=1 HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod[tensorflow]
```
but when install success, check-build show like this:
![image](https://user-images.githubusercontent.com/4211003/148707244-7070d04e-2a4b-41be-890b-30343926c865.png)
when i run horovod demo, eror log:
```
ValueError: Gloo support has not been built.  If this is not expected, ensure CMake is installed and reinstall Horovod with HOROVOD_WITH_GLOO=1 to debug the build error.
``` 
my question is：
- can i use horovod without install MPI ?
- i have set HOROVOD_WITH_TENSORFLOW=1 and install success, why check-build show no tensorflow?

**Environment:**
1. Framework: Tensorflow
2. Framework version: 1.15
3. Horovod version: 0.23.0
4. MPI version: No MPI
5. CUDA version:10.0
6. NCCL version: 2.6.4
7. Python version: 3.6
8. Spark / PySpark version: No Spark
9. Ray version: No Ray
10. OS and version: Centos 7.6
11. GCC version: 7.2.1
12. CMake version: 3.20

**Comment by maxhgerlach** [comment]
That's quite strange! Could you add an `-v` to your `pip install` line to get more logs?

**Comment by yongqiangz** [comment]
I found out that it's probably because my tensorflow was installed through `conda install`, but horovod was installed through `pip install`(pip in the conda env)， I will try more and get more log, tks~

**Comment by maxhgerlach** [comment]
Please reopen if necessary
