### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by jontremblay** [horovod/horovod#339]
Hello, this is probably a beginner mistake that I should be able to quickly fix, but I cannot find an answer. 

I have a dgx workstation and I am trying to run the pytorch example locally on my machine as follow: 
```
mpirun -np 4 -H localhost:4 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=^docker0 -mca btl_tcp_if_exclude lo,docker0 -mca pml ob1 -mca btl ^openib python train.py
```
I get the following mistake: 
```
ssh: Could not resolve hostname localhost:1: Temporary failure in name resolution
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
```
I have added my rsa key to my local computer, e.g., I can run `ssh localhost` with no problems. I don't see what else is missing. Thank you for your help, I am a little lost at sea.

**Comment by alsrgv** [comment]
@jontremblay, I believe `Could not resolve hostname localhost:1` is a sign that you're using an old version of Open MPI.  Can you upgrade to the latest version, 3.1.0?

**Comment by ChangingFond** [comment]
@alsrgv  Thank you, I upgrade openmpi to 3.1.0, and it succeed.

**Comment by LeavesLei** [comment]
@ChangingFond  Hi, do you know how to update openmpi on Ubuntu16.04？

**Comment by LeavesLei** [comment]
@sumedhvdatar  Hi, I have the same problem. Did you solve it?

**Comment by alsrgv** [comment]
Please see [this command](https://github.com/horovod/horovod/blob/master/Dockerfile#L40) for installing Open MPI 4.0.0 on Ubuntu 16.04.
