### ISSUE TITLE
When would be next release of Horovod available?

### ISSUE THREAD

**Issue by Tony-Feng** [horovod/horovod#3404]
Hello Horovod Team,

Just curious, I'm wondering when the next release of Horovod would be available on PyPI? And would it be a major or minor release?

Thank you very much and feel free to correct anything

**Comment by ertrue** [comment]
Share the same thought. I think we need to prioritize this, as a lot of existing code is not working with the latest pytorch, such as THC.

**Comment by Tony-Feng** [comment]
> Share the same thought. I think we need to prioritize this, as a lot of existing code is not working with the latest pytorch, such as THC.

Yes, agreed with that. It'd be nice to have good features from the official and stable release.

**Comment by EnricoMi** [comment]
You are right, the next release should happen rather soon. It will 0.24.0.

**Comment by Tony-Feng** [comment]
> You are right, the next release should happen rather soon. It will 0.24.0.

It's great to know that! Thanks for your confirmation!

**Comment by ertrue** [comment]
@EnricoMi thanks, do we have a timeline about this new release?

**Comment by EnricoMi** [comment]
Today or tomorrow.
