### ISSUE TITLE
Support P2P communication

### ISSUE THREAD

**Issue by Richie-yan** [horovod/horovod#3418]
Happy to use horovod for distributed training.
Are there plans to support P2P communication, similar to Pytorch's P2POp.
Supporting P2P I believe will greatly facilitate horovod's model parallel training.

**Comment by maxhgerlach** [comment]
Hi @Richie-yan,
you can achieve some P2P communication in Horovod with `alltoall` ops (example API link: https://horovod.readthedocs.io/en/stable/api.html?highlight=alltoall#horovod.tensorflow.alltoall). Note the `splits` parameter which you can set to 0 or a finite value for all participating processes.
