### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by Arij-Aladel** [horovod/horovod#3420]
Hello! I have followed all the stps though I can not install horovod properly until now
I have built these two files :
yml 

> name: adel
> 
> channels:
>   - pytorch=1.9.0
>   - conda-forge
>   - defaults
> 
> dependencies:
>   - ccache
>   - cmake
>   - cudatoolkit=11.3
>   - cudnn
>   - cxx-compiler
>   - jupyterlab
>   - mpi4py # installs cuda-aware openmpi
>   - nccl
>   - nvcc_linux-64
>   - openmpi
>   - pip
>   - pip:
>     - tensorflow-gpu==2.4.*
>     - -r requirements.txt
>   - python=3.8
>   - tensorboard=2.6.0
>   - torchaudio=0.9.0
>   - torchvision=0.10.0
>   - numpy
>   - tqdm
>   - tokenizers=0.10.3
>   - prettytable=2.2.1
>   - einops=0.3.2

and requirements 

> 
> horovod==0.22.1
> transformers==4.8.2
> datasets==1.8.0
> jupyterlab-nvdashboard==0.2.*
> jupyter-tensorboard==0.2.*
> jupyterlab-nvdashboard==0.2.*
> jupyter-tensorboard==0.2.*
> sacrebleu==2.0.0 

Then `export HOROVOD_GPU_OPERATIONS=NCCL`   after that    `conda env create --file horovod.yml --force`  

to get the error 
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: pytorch=1.9.0
  channel url: https://conda.anaconda.org/pytorch=1.9.0
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
Do I miss something?

**Comment by maxhgerlach** [comment]
#3428
