### ISSUE TITLE
Error: UCXP2P UCP worker does not support MPI_THREAD_MULTIPLE

### ISSUE THREAD

**Issue by Hannah-xxl** [horovod/horovod#344]
I use openmpi-3.1.0rc2 from mlnx4.3-1.0.1 to run horovod with tensorflow benchmark. This is my command.
`mpirun --allow-run-as-root -np 4 -H centos20:2,centos71:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x MPI_THREAD_MULTIPLE=0 -mca pml ob1 -mca btl ^openib python tf_cnn_benchmarks.py --model=resnet50 --batch_size=128 --variable_update=horovod`
There are two gpus on centos20 and centos71 respectively. I have setted the two hostname to use GE network in /etc/hosts file.
But I always get this error when I run this command.

> [centos20:11554][coll_ml_mca.c:779:hmca_coll_ml_register_params] COLL-ML ATTENTION: Available IPoIB interface was not found. MCAST capability will be disabled.
[centos20:11555][coll_ml_mca.c:779:hmca_coll_ml_register_params] COLL-ML ATTENTION: Available IPoIB interface was not found. MCAST capability will be disabled.
[centos71:179711][coll_ml_mca.c:779:hmca_coll_ml_register_params] COLL-ML ATTENTION: Available IPoIB interface was not found. MCAST capability will be disabled.
[centos71:179710][coll_ml_mca.c:779:hmca_coll_ml_register_params] COLL-ML ATTENTION: Available IPoIB interface was not found. MCAST capability will be disabled.
[centos20:11554:0][bcol_ucx_p2p_component.c:808:ucx_p2p_init] UCXP2P UCP worker does not support MPI_THREAD_MULTIPLE
[centos20:11554:0][bcol_ucx_p2p_component.c:584:hmca_bcol_ucx_p2p_init_query] UCXP2P failed to init ucx
[centos20:11555:1][bcol_ucx_p2p_component.c:808:ucx_p2p_init] UCXP2P UCP worker does not support MPI_THREAD_MULTIPLE
[centos20:11555:1][bcol_ucx_p2p_component.c:584:hmca_bcol_ucx_p2p_init_query] UCXP2P failed to init ucx
[centos20:11555] Error: coll_hcoll_module.c:310 - mca_coll_hcoll_comm_query() Hcol library init failed
[centos20:11554] Error: coll_hcoll_module.c:310 - mca_coll_hcoll_comm_query() Hcol library init failed
[centos71:179711:3][bcol_ucx_p2p_component.c:808:ucx_p2p_init] UCXP2P UCP worker does not support MPI_THREAD_MULTIPLE
[centos71:179711:3][bcol_ucx_p2p_component.c:584:hmca_bcol_ucx_p2p_init_query] UCXP2P failed to init ucx
[centos71:179711] Error: coll_hcoll_module.c:310 - mca_coll_hcoll_comm_query() Hcol library init failed
[centos71:179710:2][bcol_ucx_p2p_component.c:808:ucx_p2p_init] UCXP2P UCP worker does not support MPI_THREAD_MULTIPLE
[centos71:179710:2][bcol_ucx_p2p_component.c:584:hmca_bcol_ucx_p2p_init_query] UCXP2P failed to init ucx
[centos71:179710] Error: coll_hcoll_module.c:310 - mca_coll_hcoll_comm_query() Hcol library init failed
[centos71][[7626,1],2][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[7626,1],3]

It seems there is a module not supporting MPI_THREAD_MULTIPLE so that UCXP2P and Hcol library fails to init themselves, but I don't know how to switch off this flag. Or are there some libraries I have missed to install on?
Thank you all.

**Comment by alsrgv** [comment]
@brave-hannah, if you're not using `mpi4py` in your deep learning training, you can make Horovod single-threaded by installing recently released 0.13.5 and setting `-x HOROVOD_MPI_THREADS_DISABLE=1`.  That should help with these warnings.

**Comment by brave-hannah** [comment]
How can I tell whether I use mpi4py or not? I use horovod 0.13.4 which installed by pip. I have tried to add this flag on with 0.13.4 but nothing help.

**Comment by alsrgv** [comment]
@brave-hannah, you can grep source code for `mpi4py`. The flag was introduced in 0.13.5, so you'd need to upgrade to try it.

**Comment by brave-hannah** [comment]
@alsrgv It works, thank you very much.
