### ISSUE TITLE
Where can I find documentation about timeline?

### ISSUE THREAD

**Issue by zhaozheng09** [horovod/horovod#3448]
![image](https://user-images.githubusercontent.com/33950866/156780072-fbf3d82f-0346-4f79-917e-b07e8c5e97d4.png)
1. Is there official documentation for NEGOTIATE_ALLREDUCE WAIT_FOR_DATA  WAIT_FOR_OTHER_TENSOR_DATA MEMCPY_IN_FUSION_BUFFER NCCL_ALLREDUCE ?
2. My alltoall is too slow, where is the bottleneck?

**Comment by EnricoMi** [comment]
@tgaddair @romerojosh can you provide some insights here, please?

**Comment by maxhgerlach** [comment]
We have official documentation and it's not exactly hidden. https://horovod.readthedocs.io/en/stable/timeline.htm

Your timeline shows that one NCCL_ALLTOALL is executed after the other as expected. See the greenish rectangles in your timeline screenshot.

Can we move this to discussions?

**Comment by zhaozheng09** [comment]
> We have official documentation and it's not exactly hidden. https://horovod.readthedocs.io/en/stable/timeline.html
> 
> Your timeline shows that one NCCL_ALLTOALL is executed after the other as expected. See the greenish rectangles in your timeline screenshot.
> 
> Can we move this to discussions?

OK，So alltoall is sync executable ?  How to explain this?
![image](https://user-images.githubusercontent.com/33950866/156974097-05521b17-d89b-4494-a0a9-21e9aaf05843.png)
