### ISSUE TITLE
Build MXNet1.9 from source , install horovod will report cannot find mxnet 

### ISSUE THREAD

**Issue by Gao-HaoYuan** [horovod/horovod#3455]
## Description
environment：
python 3.8
ubuntu 18.04 
gcc 7.5     g++7.5
mxnet1.9(build from source)
openmpi 4.0
horovod 0.24

instructions
HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITH_MXNET=1 pip install dist/horovod-0.24.1.tar.gz

HOROVOD_WITH_MXNET=1 pip install --no-cache-dir horovod[MXNET]

Horovod cannot be installed or compile

### Error Message
```
 Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/root/miniconda3/lib/python3.8/site-packages/mxnet-1.9.0-py3.8.egg/mxnet/libinfo.py", line 108, in find_include_path
          raise RuntimeError('Cannot find the MXNet include path in either ' + pip_incl_path +
      RuntimeError: Cannot find the MXNet include path in either /root/miniconda3/lib/python3.8/site-packages/mxnet-1.9.0-py3.8.egg/mxnet/include/ or /root/miniconda3/lib/python3.8/site-packages/mxnet-1.9.0-py3.8.egg/mxnet/../../include/

      CMake Error at /tmp/horovod-cmake-tmpaicqjfxp/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
        Could NOT find Mxnet (missing: Mxnet_LIBRARIES) (Required is at least
        version "1.4.0")
      Call Stack (most recent call first):
        /tmp/horovod-cmake-tmpaicqjfxp/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
        cmake/Modules/FindMxnet.cmake:65 (find_package_handle_standard_args)
        horovod/mxnet/CMakeLists.txt:12 (find_package)


      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-sz62zlyv/build/temp.linux-x86_64-3.8/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-sz62zlyv/setup.py", line 209, in <module>
          setup(name='horovod',
        File "/root/miniconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/root/miniconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/root/miniconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/root/miniconda3/lib/python3.8/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/root/miniconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/root/miniconda3/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/root/miniconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/root/miniconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-req-build-sz62zlyv/setup.py", line 144, in build_extensions
          subprocess.check_call(command, cwd=cmake_build_dir)
        File "/root/miniconda3/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/tmp/horovod-cmake-tmpaicqjfxp/bin/run_cmake', '/tmp/pip-req-build-sz62zlyv', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO=/tmp/pip-req-build-sz62zlyv/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE:FILEPATH=/root/miniconda3/bin/python']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of horovod
  Moving to /root/miniconda3/bin/horovodrun
   from /tmp/pip-uninstall-ddcttzju/horovodrun
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> horovod

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

## To Reproduce

HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITH_MXNET=1 pip install dist/horovod-0.24.1.tar.gz

HOROVOD_WITH_MXNET=1 pip install --no-cache-dir horovod[MXNET]

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. compile the mxnet 1.9 
         apt-get update 
         sudo apt-get install -y build-essential libopenblas-dev libopencv-dev graphviz
         make -j8
         sudo python setup.py install
         export PYTHONPATH="/root/mxnet/python:$PYTHONPATH"   and source ~/.bashrc
2. conda install openmpi (4.0.2) 
3. HOROVOD_WITH_MXNET=1 pip install --no-cache-dir horovod[MXNET] 

## What have you tried to solve it?

1. compile the horovod 
2. compile the openmpi

## Environment

python 3.8
ubuntu 18.04 
gcc 7.5     g++7.5
mxnet1.9(build from source)
openmpi 4.0
horovod 0.24

<details>
<summary>Environment Information</summary>

```
# Paste the diagnose.py command output here
```

</details>

**Comment by EnricoMi** [comment]
Are there any errors before this line:

    Could NOT find Mxnet (missing: Mxnet_LIBRARIES) (Required is at least version "1.4.0")

Can you please run the following in the same environment where you installed mxnet and run `pip install horovod`?

    python -c "import os; import mxnet as mx; import build_utils; print(mx.__version__); print(mx.libinfo.find_include_path()); print(' '.join(mx.libinfo.find_lib_path())); print(build_utils.is_mx_mkldnn()); print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda())"

**Comment by Gao-HaoYuan** [comment]
> Are there any errors before this line:
> no other errors
> but the mxnet 1.9 in my environment

Requirement already satisfied: cloudpickle in /root/miniconda3/lib/python3.8/site-packages (from horovod==0.24.0) (2.0.0)
Requirement already satisfied: psutil in /root/miniconda3/lib/python3.8/site-packages (from horovod==0.24.0) (5.9.0)
Requirement already satisfied: pyyaml in /root/miniconda3/lib/python3.8/site-packages (from horovod==0.24.0) (6.0)
Requirement already satisfied: mxnet>=1.4.1 in /root/mxnet/python (from horovod==0.24.0) (1.9.0)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /root/miniconda3/lib/python3.8/site-packages/graphviz-0.8.4-py3.8.egg (from mxnet>=1.4.1->horovod==0.24.0) (0.8.4)
Requirement already satisfied: numpy<2.0.0,>1.16.0 in /root/miniconda3/lib/python3.8/site-packages (from mxnet>=1.4.1->horovod==0.24.0) (1.21.2)
Requirement already satisfied: requests<3,>=2.20.0 in /root/miniconda3/lib/python3.8/site-packages (from mxnet>=1.4.1->horovod==0.24.0) (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /root/miniconda3/lib/python3.8/site-packages (from requests<3,>=2.20.0->mxnet>=1.4.1->horovod==0.24.0) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/lib/python3.8/site-packages (from requests<3,>=2.20.0->mxnet>=1.4.1->horovod==0.24.0) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/lib/python3.8/site-packages (from requests<3,>=2.20.0->mxnet>=1.4.1->horovod==0.24.0) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/miniconda3/lib/python3.8/site-packages (from requests<3,>=2.20.0->mxnet>=1.4.1->horovod==0.24.0) (1.26.8)

> and the horovod checked it
> Can you please run the following in the same environment where you installed mxnet and run `pip install horovod`?
> 
> ```
> python -c "import os; import mxnet as mx; import build_utils; print(mx.__version__); print(mx.libinfo.find_include_path()); print(' '.join(mx.libinfo.find_lib_path())); print(build_utils.is_mx_mkldnn()); print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda())"
> ```

(base) root@container-085311853c-e91e5dc0:~/build_utils-0.3.0# python -c "import os; import mxnet as mx; import build_utils; print(mx.__version__); print(mx.libinfo.find_include_path()); print(' '.join(mx.libinfo.find_lib_path())); print(build_utils.is_mx_mkldnn()); print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda())"
1.9.0
/root/mxnet/python/mxnet/../../include/
/root/mxnet/python/mxnet/../../lib/libmxnet.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'build_utils' has no attribute 'is_mx_mkldnn'

Sorry, i sleepd to late last night to reply to you so slowly, this is the out , thanks for your reply

**Comment by Gao-HaoYuan** [comment]
i installed the build_utils through build_utils-0.3.2-py3-none-any.whl   

i try to run the  print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda()) and get the same results 

when i compiled the mxnet1.9  ,  i set the  "use_cuda=1           use_cudnn=    use_mkldnn=1   use_kvstroe=1" in the config.mk

so I am very confused about this question.

**Comment by EnricoMi** [comment]
Right, you have to run that `python` command inside `horovod/cmake`. There is the `build_utils.py` that is imported by that `python` command. What is the output then?

**Comment by Gao-HaoYuan** [comment]
> 

I get the result


(base) root@container-065311b73c-58f0edc5:~/horovod-0.24.1/cmake# python -c "import os; import mxnet as mx; import build_utils; print(mx.__version__); print(mx.libinfo.find_include_path()); print(' '.join(mx.libinfo.find_lib_path())); print(build_utils.is_mx_mkldnn()); print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda())"
1.9.0
/root/mxnet/python/mxnet/../../include/
/root/mxnet/python/mxnet/../../lib/libmxnet.so
True
False
True

**Comment by Gao-HaoYuan** [comment]
> Right, you have to run that `python` command inside `horovod/cmake`. There is the `build_utils.py` that is imported by that `python` command. What is the output then?

I get the result

(base) root@container-065311b73c-58f0edc5:~/horovod-0.24.1/cmake# python -c "import os; import mxnet as mx; import build_utils; print(mx.__version__); print(mx.libinfo.find_include_path()); print(' '.join(mx.libinfo.find_lib_path())); print(build_utils.is_mx_mkldnn()); print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda())"
1.9.0
/root/mxnet/python/mxnet/../../include/
/root/mxnet/python/mxnet/../../lib/libmxnet.so
True
False
True

onednn is missing?   what should i do?  can you give me some suggestions?

**Comment by Gao-HaoYuan** [comment]
i install the mxnet through pip , and run the code .
``python -c "import os; import mxnet as mx; import build_utils; print(mx.__version__); print(mx.libinfo.find_include_path()); print(' '.join(mx.libinfo.find_lib_path())); print(build_utils.is_mx_mkldnn()); print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda())"

the output :
1.9.0
/root/miniconda3/lib/python3.8/site-packages/mxnet/include/
/root/miniconda3/lib/python3.8/site-packages/mxnet/libmxnet.so
True
False
False

i install the openmpi and horovod, this is no problem ,  maybe the problem comes from the mxnet compilation process.

**Comment by EnricoMi** [comment]
And running `HOROVOD_WITH_MXNET=1 pip install --no-cache-dir horovod[MXNET]` in the very same environment gives you

      CMake Error at /tmp/horovod-cmake-tmpaicqjfxp/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
        Could NOT find Mxnet (missing: Mxnet_LIBRARIES) (Required is at least version "1.4.0")

**Comment by EnricoMi** [comment]
How do you install mxnet from sources?

**Comment by Gao-HaoYuan** [comment]
> How do you install mxnet from sources?

i download the sources through git    
``git clone -b v1.9.x --recursive https://github.com/apache/incubator-mxnet ~/mxnet
``

and move the config.mk from `mxnet/make` to `mxnet`, then  I modified it. 
USE_CUDA = 1  USE_CUDA_PATH = /usr/local/cuda-11.1  USE_CUDNN=1   USE_DIST_KVSTORE=1 USE_MKLDNN=1

I execute command in the `~/mxnet`
apt-get update 
sudo apt-get install -y build-essential libatlas-base-dev libopencv-dev graphviz
make -j8
sudo apt-get install -y python-setuptools python-pip
sudo pip install -U pip
cd python; sudo python setup.py install
and add the export PYTHONPATH="/root/mxnet/python:$PYTHONPATH" by myself
then source ~/.bashrc

as the `/root/mxnet/setup-utils/install-mxnet-ubuntu-python.sh` wrote

**Comment by EnricoMi** [comment]
That looks alright, and when you execute the above `python` command right after that (without ever pip install mxnet), what is the output? I got confused with the multiple attempts that you posted above.

**Comment by Gao-HaoYuan** [comment]
> That looks alright, and when you execute the above `python` command right after that (without ever pip install mxnet), what is the output? I got confused with the multiple attempts that you posted above.

when i execute the command make -j8 , it give me many warnning, and about four hours later, it will stop

then i execute the python command

**Comment by Gao-HaoYuan** [comment]
> And running `HOROVOD_WITH_MXNET=1 pip install --no-cache-dir horovod[MXNET]` in the very same environment gives you
> 
> ```

>   CMake Error at /tmp/horovod-cmake-tmpaicqjfxp/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>     Could NOT find Mxnet (missing: Mxnet_LIBRARIES) (Required is at least version "1.4.0")
> ```

i running  `HOROVOD_WITH_MXNET=1 pip install --no-cache-dir horovod[MXNET]`

it will install another mxnet, as shown below 

`root@container-065311b73c-58f0edc5:~/incubator-mxnet/python# HOROVOD_WITH_MXNET=1 pip install --no-cache-dir horovod[MXNET]
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: horovod[MXNET] in /root/miniconda3/lib/python3.8/site-packages (0.24.1)
Requirement already satisfied: cloudpickle in /root/miniconda3/lib/python3.8/site-packages (from horovod[MXNET]) (2.0.0)
Requirement already satisfied: psutil in /root/miniconda3/lib/python3.8/site-packages (from horovod[MXNET]) (5.9.0)
Requirement already satisfied: pyyaml in /root/miniconda3/lib/python3.8/site-packages (from horovod[MXNET]) (6.0)
Collecting mxnet>=1.4.1
  Downloading http://mirrors.aliyun.com/pypi/packages/67/9d/3d9191e88171feeba367882786098036dc11adb634d3d14368f5df891898/mxnet-1.9.0-py3-none-manylinux2014_x86_64.whl (47.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 MB 783.4 kB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2.20.0 in /root/miniconda3/lib/python3.8/site-packages (from mxnet>=1.4.1->horovod[MXNET]) (2.25.1)
Requirement already satisfied: numpy<2.0.0,>1.16.0 in /root/miniconda3/lib/python3.8/site-packages (from mxnet>=1.4.1->horovod[MXNET]) (1.21.2)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /root/miniconda3/lib/python3.8/site-packages (from mxnet>=1.4.1->horovod[MXNET]) (0.8.4)
Requirement already satisfied: chardet<5,>=3.0.2 in /root/miniconda3/lib/python3.8/site-packages (from requests<3,>=2.20.0->mxnet>=1.4.1->horovod[MXNET]) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/miniconda3/lib/python3.8/site-packages (from requests<3,>=2.20.0->mxnet>=1.4.1->horovod[MXNET]) (1.26.6)
Requirement already satisfied: idna<3,>=2.5 in /root/miniconda3/lib/python3.8/site-packages (from requests<3,>=2.20.0->mxnet>=1.4.1->horovod[MXNET]) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/lib/python3.8/site-packages (from requests<3,>=2.20.0->mxnet>=1.4.1->horovod[MXNET]) (2021.10.8)
Installing collected packages: mxnet
Successfully installed mxnet-1.9.0
`

**Comment by EnricoMi** [comment]
Sorry, with "the `python` command", I meant

    python -c "import os; import mxnet as mx; import build_utils; print(mx.__version__); print(mx.libinfo.find_include_path()); print(' '.join(mx.libinfo.find_lib_path())); print(build_utils.is_mx_mkldnn()); print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda())"

**Comment by Gao-HaoYuan** [comment]
> 

this is the output , i never pip install mxnet

(base) root@container-065311b73c-58f0edc5:~/horovod-0.24.1/cmake# python -c "import os; import mxnet as mx; import build_utils; print(mx.version); print(mx.libinfo.find_include_path()); print(' '.join(mx.libinfo.find_lib_path())); print(build_utils.is_mx_mkldnn()); print(build_utils.is_mx_onednn()); print(build_utils.is_mx_cuda())"
1.9.0
/root/mxnet/python/mxnet/../../include/
/root/mxnet/python/mxnet/../../lib/libmxnet.so
True
False
True

**Comment by EnricoMi** [comment]
>  i never pip install mxnet
yes, but your [above comment](https://github.com/horovod/horovod/issues/3455#issuecomment-1059993696) show that `pip install horovod[mxnet]` made pip install mxnet:

    Successfully installed mxnet-1.9.0

So that messed up diagnostics I am trying to do here.

**Comment by Gao-HaoYuan** [comment]
> > i never pip install mxnet
> > yes, but your [above comment](https://github.com/horovod/horovod/issues/3455#issuecomment-1059993696) show that `pip install horovod[mxnet]` made pip install mxnet:
> 
> ```
> Successfully installed mxnet-1.9.0
> ```
> 
> So that messed up diagnostics I am trying to do here.

sorry ,  due to my message is too messy to add to your troubles. i guess that , will the source code of mxnet be incomplete?

**Comment by EnricoMi** [comment]
I think the problem is that MXNet cannot find the include path:

    `python3 -c "import mxnet as mx; print(mx.libinfo.find_include_path());"`

This is a problem with the MXNet installation, not Horovod. So best would be to check with MXNet project why their instructions install MXNet in a way thet `mx.libinfo.find_include_path()` raises an exception.

**Comment by EnricoMi** [comment]
You already did: https://github.com/apache/incubator-mxnet/issues/20936

**Comment by Gao-HaoYuan** [comment]
> I think the problem is that MXNet cannot find the include path:
> 
> ```
> python3 -c "import mxnet as mx; print(mx.libinfo.find_include_path());"
> ```
> 
> This is a problem with the MXNet installation, not Horovod. So best would be to check with MXNet project why their instructions install MXNet in a way that `mx.libinfo.find_include_path()` fails.

OK, i think you are right, i will check the MXNet project , thank you very much

**Comment by Gao-HaoYuan** [comment]
> You already did

yes , but nobody answer me.........

**Comment by EnricoMi** [comment]
I'd recommend renaming the issue, simplifying the context and specifying the problem helps to get someone looking into it:

    Building MXNet 1.9 from sources breaks `mxnet.libinfo.find_include_path()`

**Comment by Gao-HaoYuan** [comment]
> 

i get it, your idea is good, i will modified it

**Comment by Gao-HaoYuan** [comment]
i have solved this problem , refer to https://github.com/apache/incubator-mxnet/issues/20936#issuecomment-1060720641
