### ISSUE TITLE
On the clang-format check of the project

### ISSUE THREAD

**Issue by GHGmc2** [horovod/horovod#3465]
I noticed that horovod use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to format C++ code.

But when I check the project with clang-format-12, I still got many errors. The cmd I used as below:
```bash
#!/usr/bin/env bash

for src in $(find ./horovod -name "*.h" -or -name "*.cc")
do
 clang-format-12 -style=file ${src}
done
```

And the output as attached [hvd_cf12.txt](https://github.com/horovod/horovod/files/8220236/hvd_cf12.txt).

May I know did I use the wrong clang-format version, or the cmd is not right?

**Comment by maxhgerlach** [comment]
While we strive to change the code base in line with clang-format, there is no automated process to do so and portions that haven't been touched in a while may differ in formatting a bit
