### ISSUE TITLE
Question about running horovod

### ISSUE THREAD

**Issue by sheepjin11** [horovod/horovod#347]
Hello, I want to run tensorflow_mnist_estimator.py with single CPU (on my Mac)
I just copied and pasted the horovod/examples/tensorflow_mnist_estimator.py code and installed Open MPI and horovod.(pip install horovod)

`(tensorflow) mpirun -np 4 -H localhost:4 -bind-to none -map-by slot -x PATH -mca pml ob1 -mca btl ^openib python cnn_mnist.py
`

but it failed

```
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       jin-ui-MacBook-Pro
Executable: cnn_mnist.py
--------------------------------------------------------------------------
```

What is the problem? How can I fix it? thanks.

**Comment by alsrgv** [comment]
@sheepjin11, you'd typically get this error if you miss `python` in your command line.  Can you copy-paste the command line and output verbatim?

**Comment by sheepjin11** [comment]
Every time I change the command, I get a different error, and I'll show you some. I input the following command

1))

(tensorflow) mpirun -np 4 -H localhost:4 --bind-to none -map-by slot -x LD_LIBRARY_PATH -mca pml ob1 -mca btl ^openib python cnn_mnist.py

and the result was

[yangjin-ui-MacBook-Pro.local:01077] Warning: could not find environment variable "LD_LIBRARY_PATH"
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       yangjin-ui-MacBook-Pro
Executable: cnn_mnist.py
--------------------------------------------------------------------------


2)) 
input : 
mpirun -np 4 -H localhost:4 -bind-to none -map-by slot -x PATH -mca pml ob1 -mca btl ^openib python cnn_mnist.py

output :
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       yangjin-ui-MacBook-Pro
Executable: cnn_mnist.py
--------------------------------------------------------------------------
4 total processes failed to start

3)) 
input : 
mpirun -np 2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO python3 cnn_mnist.py

output :
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node yangjin-ui-MacBook-Pro exited on signal 4 (Illegal instruction: 4).
--------------------------------------------------------------------------


Do you know what the problem is?

**Comment by alsrgv** [comment]
@sheepjin11, the last error is a known issue in Open MPI (see #319), the workaround is to run:
```
$ mpirun -np 2 -mca btl ^tcp python3 cnn_mnist.py
```
(you don't really need other flags on the MacBook)

**Comment by sheepjin11** [comment]
I put your code
`$ mpirun -np 2 -mca btl ^tcp python3 cnn_mnist.py`

and output is
```
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       yangjin-ui-MacBook-Pro
Executable: cnn_mnist.py
--------------------------------------------------------------------------
2 total processes failed to start
```

**Comment by sheepjin11** [comment]
and I have more questions, when I run cnn_mnist.py by inputting python3 cnn_mnist.py in command line, there create 2 folders named checkpoints and MNIST-data-0.

After these folders have been created, the following results are obtained when I put the same code

input
`mpirun -np 2 -mca btl ^tcp python3 cnn_mnist.py` 

output
`--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       yangjin-ui-MacBook-Pro
Executable: MNIST-data-0
--------------------------------------------------------------------------
2 total processes failed to start`

so, Executable file changed from cnn_mnist.py to MNIST-data-0.
I have no idea why this is happening.

**Comment by alsrgv** [comment]
@sheepjin11, I feel like your shell does not like `^` character.  What if you escape `^tcp` like this:
```
$ mpirun -np 2 -mca btl "^tcp" python3 cnn_mnist.py
```

**Comment by sheepjin11** [comment]
The problem has been fixed! Thank you :)

**Comment by wyf0414** [comment]
> 问题已修复！谢谢:)
Hello, I have a question similar to yours.
I encountered this issue while replicating bevfusion.
I have configured the environment and dataset according to the readme of bevfusion.
Could you tell me how you solved it?
Thanks very much!

Input:
`torchpack dist-run -np 1 python tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth --load_from pretrained/lidar-only-det.pth`

error:
Warning: could not find environment variable "-x"
--------------------------------------------------------------------------
mpirun was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
      line parameter option (remember that mpirun interprets the first
      unrecognized command line token as the executable).

Node:       autodl-container-e7f311abe8-00947946
Executable: AgentHost

![image](https://github.com/horovod/horovod/assets/137131028/ca1d42ba-a80d-4918-84a4-56af11cb0d49)
