### ISSUE TITLE
install horoved hangs

### ISSUE THREAD

**Issue by csaimd** [horovod/horovod#3488]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch)
2. Framework version:
    tensorflow-gpu=1.15
   keras=2.2.4
   pytorch==1.1.0
3 Horovod version: 0.21.0
   
6. MPI version: NA
7. CUDA version: cuda10.0
8. NCCL version:  2.6.4
9. Python version: 3.6.5
10. Spark / PySpark version: NA
11. Ray version: NA
12. OS and version:  centos 3.10.0-957
13. GCC version: 5.2.0
14. CMake version: 3.13

**Bug report:**

when i install the horovod with the command  "HOROVOD_GPU_OPERATIONS=NCCL pip install  horovod==0.21.0", it stay on this step forever

/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Looking in indexes: http://repo.htzq.htsc.com.cn/repository/htscpypi/simple/
Collecting horovod==0.21.0
  Downloading http://repo.htzq.htsc.com.cn/repository/htscpypi/packages/horovod/0.21.0/horovod-0.21.0.tar.gz (3.2 MB)
     |################################| 3.2 MB 44.4 MB/s            
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cloudpickle in /opt/anaconda3/lib/python3.6/site-packages (from horovod==0.21.0) (0.5.3)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.6/site-packages (from horovod==0.21.0) (5.4.5)
Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.6/site-packages (from horovod==0.21.0) (3.12)
Requirement already satisfied: cffi>=1.4.0 in /opt/anaconda3/lib/python3.6/site-packages (from horovod==0.21.0) (1.11.5)
Collecting dataclasses
  Downloading http://repo.htzq.htsc.com.cn/repository/htscpypi/packages/dataclasses/0.8/dataclasses-0.8-py3-none-any.whl (19 kB)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.6/site-packages (from cffi>=1.4.0->horovod==0.21.0) (2.18)
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... |

it sesms hangs when building the wheel for horovod

**Comment by EnricoMi** [comment]
please try with `pip install -v ...` to get some more insights in the building process

**Comment by csaimd** [comment]
Yes, it is a conda env, I can install tensorflow, pytorch, and other package through pip install. I try install horovod=0.19.0 and it success, 
I try install horvorod==0.24 later, After waiting for a long time, I found an error in output:

**Comment by maxhgerlach** [comment]
Yes, you will need at least one of TensorFlow 1.15 or later, PyTorch 1.2 or later, or MXNet 1.4.0 or later.

**Comment by EnricoMi** [comment]
> Does this mean I have to upgrade the tf and torch? if i don't need mxnet, i should install horovod[tensorflow,pytorch]?

That is perfectly right.

**Comment by EnricoMi** [comment]
Please reopen if this is still an issue.
