### ISSUE TITLE
Is there a problem with ProcessSetTable Finalize when elastic?

### ISSUE THREAD

**Issue by Richie-yan** [horovod/horovod#3501]
Background:
Suppose there are currently 4 ranks on 4 machines
Due to the failure of machine 1, rank1 exits directly, and the final shutdown: logic is not executed
Then the remaining machines will perform the shutdown operation in the case of  elasticity, and will call process_set_table.Finalize function. this function uses allgather to determine whether the process set needs to be removed, but at this time rank1 has already exited, then allgather operation should theoretically cause the remaining processes to be abnormal, so that the shutdown cannot be normal and elastic cannot be normal.
@maxhgerlach

**Comment by maxhgerlach** [comment]
Hey @Richie-yan, sorry for the late reply. 

Personally I haven't ever tried multiple process sets with elastic mode and I haven't given much thought to the combination. So it's very likely that there will be issues. Also please note that there currently is no provision to remove a process from an existing set (or add a new one).
