### ISSUE TITLE
can horovod DistributedOptimizer support multi optimizers in one training

### ISSUE THREAD

**Issue by ydp** [horovod/horovod#351]
In tensorflow high level API estimator, there is a DNNLinearCombined, which is wide and deep model. As you know tensorflow also has sync training, leveraged by SyncReplicasOptimizer. However, this SyncReplicasOptimizer does not support multi optimizer, like wide and deep model.

So I am wondering if horovod supports multi optimizers? If yes, how its model parameters will be updated? And more, what is the implementation?

I have simple usage here, but not sure if it is the right way to do?  Has anyone tested this use case? Any reply will be appreciated.

```
hvd_linear_optimizer = hvd.DistributedOptimizer(tf.train.FtrlOptimizer(learning_rate=lr))
hvd_dnn_optimizer = hvd.DistributedOptimizer(tf.train.AdagradOptimizer(learning_rate=lr))

 estimator = tf.estimator.DNNLinearCombinedClassifier(
            model_dir=model_dir,
            linear_feature_columns=linear_feature_columns,
            linear_optimizer=hvd_linear_optimizer,
            dnn_feature_columns=dnn_feature_columns,
            dnn_optimizer=hvd_dnn_optimizer,
            dnn_hidden_units=dnn_hidden_units,
            dnn_activation_fn=tf.nn.relu,
            dnn_dropout=dnn_dropout,
            n_classes=2,
            weight_column=None,
            label_vocabulary=None,
            input_layer_partitioner=None,
            config=run_config
 )
```

Thanks very much!

**Comment by ydp** [comment]
here is the dnn_linear_combined and syncreplicaoptimizer

https://github.com/OAID/TensorFlow-HRT/blob/master/tensorflow/python/estimator/canned/dnn_linear_combined.py

https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/training/sync_replicas_optimizer.py

**Comment by alsrgv** [comment]
@ydp, from quick scan of `dnn_linear_combined.py`, I believe that Horovod optimizer should be compatible with that code.  Do you see any issues when you're trying to run the code?

**Comment by OverDriveMC** [comment]
@ydp   have you succeed to use  horvod to speed up the wide & deep model?

I found that when I run in multi gpu, the gpu-util is lower than one gpu,  when I run in one gpu, the util can up to 90%.
![image](https://user-images.githubusercontent.com/9543552/43256505-7793b4f2-90ff-11e8-9f51-6e56facc8daf.png)

I also found that the %cpu  will become smaller along with I adding more mpi process, when I use two gpu, the %cpu of each process  will in the range between 1400~1800.
![image](https://user-images.githubusercontent.com/9543552/43256647-f3bd07ea-90ff-11e8-92a6-ab4f4605feb9.png)

So I want to know how can I get better performance by adjusting some parameters?

**Comment by ydp** [comment]
@OverDriveMC  there are 2 ways to improve GPU utility you can try

1  optimize IO with tensorflow pipline (dataset API) 
 https://www.tensorflow.org/performance/datasets_performance
2  run multiple process on one GPU, set GPU memory fraction for each process, (pre condition might be you better use kubernetes or yarn to manage resources)
