### ISSUE TITLE
[Q] Support for PyTorch SparseAdam and Adasum?

### ISSUE THREAD

**Issue by mickvanhulst-TomTom** [horovod/horovod#3529]
I am trying to look into if Horovod supports sparse gradients using the SparseAdam optimizer as well as AdaSum. As it stands, I can't get it to work nor can I find any documentation on whether this is supported or not? What seems to happen is that when I use the SparseAdam optimizer, it complains that it can't use dense gradients, which I assume is due to how Horovod passes along the tensors between devices? Reducing with `Average` seems to work just fine!

Before I elaborate further on the ticket, I wanted to make sure if it is even supported or not.

I found a ticket that seems related, see: https://github.com/horovod/horovod/issues/1230

**Comment by chongxiaoc** [comment]
Sparse tensor should be supported since we always convert sparse to dense before calling comm functions.
See https://github.com/horovod/horovod/blob/7707267a4bef79e09a9df1d41b0652feb61b76c7/test/parallel/test_torch.py#L3087

Do you have a reproducer?
