### ISSUE TITLE
hangs with tf mnist example

### ISSUE THREAD

**Issue by twangnh** [horovod/horovod#354]
I installed horovod with the gradients branch, openmpi 3.1.1, nccl 2.2.13, cuda-8.0, running the tensorflow_mnist.py example with 
`mpirun -np 4     -H localhost:4     -bind-to none -p-by slot     -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH     -mca pml ob1 -mca btl ^openib     python horovod_example_mnist.py `
the process hangs there with no output, I can see there are processes with htop:
![image](https://user-images.githubusercontent.com/18298163/42210822-8bca9b52-7ee4-11e8-8091-979c0b0dc0d0.png)
I have 4 TiTan X on the machine

**Comment by tgaddair** [comment]
Hey @MrWanter, I just ran `tensorflow_mnist.py` with the parameters you specified on the gradients branch (now merged into master) without issue.  Sounds like this may be environment issue.

Could you try running with `strace -f -e 'trace=!poll' mpirun ...` and uploading it into a gist as suggested in #280?

**Comment by tgaddair** [comment]
Also, you may want to verify that password-less SSH works by running `ssh localhost` as suggested in #125.

**Comment by MrWanter** [comment]
Hi ssh localhost works with no problem, after reinstall horovod with` nccl_2.2.13-1+cuda9.0_x86_64`, and rerun the same code, I get:
`OSError: libcudart.so.9.1: cannot open shared object file: No such file or directory`

**Comment by tgaddair** [comment]
Looks like you have CUDA 9.0 installed, but TensorFlow is expecting CUDA 9.1.  Could you try [installing CUDA 9.1](https://medium.com/@xinh3ng/install-cuda-9-1-and-cudnn-7-for-tensorflow-1-5-0-cda36239bc68)?  Altneratively, you can try changing your version of tensorflow-gpu.

You can also try checking the dynamic libraries Horovod + TensorFlow will use by running the following:

```
ldd `find /home/wangtao/anaconda2/envs/tensorflow_/lib/python2.7/site-packages | grep horovod/tensorflow/mpi_lib.so`
```

**Comment by MrWanter** [comment]
I'm using TF 1.8.0 which is installed by pip install tensorflow-gpu, by default it use CUDA 9.0, so here is Horovod that required cuda 9.1? 
the ldd `find /home/wangtao/anaconda2/envs/tensorflow_/lib/python2.7/site-packages | grep horovod/tensorflow/mpi_lib.so` command returns
```
	linux-vdso.so.1 =>  (0x00007ffdfe547000)
	libcudart.so.9.1 => not found
	libpython2.7.so.1.0 => /home/wangtao/anaconda2/envs/tensorflow_/lib/libpython2.7.so.1.0 (0x00007fc768052000)
	libmpi.so.40 => /home/wangtao/.openmpi/lib/libmpi.so.40 (0x00007fc767d51000)
	libtensorflow_framework.so => not found
	libstdc++.so.6 => /home/wangtao/anaconda2/envs/tensorflow_/lib/libstdc++.so.6 (0x00007fc767a17000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc76770e000)
	libgcc_s.so.1 => /home/wangtao/anaconda2/envs/tensorflow_/lib/libgcc_s.so.1 (0x00007fc7674fc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc7672df000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc766f15000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc766d11000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fc766b0e000)
	libopen-rte.so.40 => /home/wangtao/.openmpi/lib/libopen-rte.so.40 (0x00007fc766857000)
	libopen-pal.so.40 => /home/wangtao/.openmpi/lib/libopen-pal.so.40 (0x00007fc76654c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc766344000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc768643000)
	libz.so.1 => /home/wangtao/anaconda2/envs/tensorflow_/lib/libz.so.1 (0x00007fc76612d000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fc765f22000)
```

**Comment by tgaddair** [comment]
It looks like Horovod was previously built with a specific version of TensorFlow and CUDA, which are no longer there.  When reinstalling, `pip` will use the cached build to save time, which could result in these links being broken.  With `pip`, you can use `pip install --no-cache-dir horovod` to force it to rebuild, which should get it to pick up the new version of TensorFlow.

I'd suggest trying that, and seeing if the `ldd` command picks up `libtensorflow_framework.so` and `libcudart.so.9.1.` (which are currently "not found").  You could also try creating an entirely new virtualenv.

**Comment by tgaddair** [comment]
One more thing I forgot to mention: if you're building from source (as it appears you are), you will need to remove the `build` and `dist` directories in the project root before running `python setup.py install`.  So something like this:

```
rm -rf build
rm -rf dist
python setup.py install
python setup.py build
```

Otherwise, you'll end up with cached libraries pointing to old versions of TensorFlow or CUDA, which may be the issue you're seeing here.

**Comment by Aki57** [comment]
Could you please help me with this[#656](https://github.com/uber/horovod/issues/656)
