### ISSUE TITLE
Pytorch_lightning's TorchEstimator doesn't pass transformation_fn correctly

### ISSUE THREAD

**Issue by serena-ruan** [horovod/horovod#3540]
**Environment:**
1. Framework: Pytorch Lightning
2. Framework version: 1.5.0
3. Horovod version: 0.23.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. Spark / PySpark version: 3.2.0
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

Pytorch_lightning's TorchEstimator accepts `transformation_fn` as a parameter but it's not actually passing it through petaStormDataModule so that the transformation_fn used in the training/validation is always the default value of `torch.as_tensor`. From the source code I found here (https://github.com/horovod/horovod/blob/464c82ef5307986531909861e01ee1c5b235640a/horovod/spark/lightning/datamodule.py#:~:text=transform_spec%20%3D%20TransformSpec,%3DFalse)) it assigned a value to `transform_spec` but only used it to distinguish the reader type and didn't pass it as a parameter to the reader.

A reproduce of the problem would be assigning a transformation_fn to horovod.spark.lightning.TorchEstimator and it doesn't use my transformation_fn to transform the row; the same transformation_fn works for horovod.spark.torch.TorchEstimator.

**Comment by serena-ruan** [comment]
@chongxiaoc Hey could you take a look at this issue cuz it seems you're the owner of that datamodule file 😃

**Comment by chongxiaoc** [comment]
@serena-ruan 

Do you have a user case and example scripts for `transformation_fn`?
When we introduced `datamodule`, we found that we didn't use `transformation_fn` (from Spark Estimator users we know), so it was taken out for simplicity.

Also, feel free to contribute a PR if you find out where to insert `transformation_fn`.

**Comment by serena-ruan** [comment]
I guess we can just pass it in here:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/82044803/167557563-5fd0d6c6-dfdc-4f9c-b705-c65272e6b9db.png">

This should pass through the param `transform_spec` into the Reader, so that when it runs PyDictReaderWorker to generate the reader it can call the transform_spec internally and changed the data schema. I don't have the dev environment setup ready so could you check if the above change works? Or could you guide me about the developing environment for raising a PR in this repo? 

Besides, when you say `we didn't use transformation_fn from Spark Estimator users` do you mean they just don't use this parameter at all? Because from my side I'm seeing the use case for example I want to pass in a dataframe for training but the dataframe just includes the paths to my dataset images, and I want to pass in a transformation_fn to read the image and transform it to tensors then work with my model.

**Comment by chongxiaoc** [comment]
@serena-ruan Our test cases are most recommendation system models which don't need `transform_spec`.
It is kind of supervised to me Spark estimator is used outside of Uber, which is a good sign though.

**Comment by serena-ruan** [comment]
Ah I see, if we make the transform_spec work then it must be more useful for TorchEstimator usage in general!

**Comment by chongxiaoc** [comment]
See https://github.com/horovod/horovod/pull/3543

**Comment by serena-ruan** [comment]
Thanks!

**Comment by serena-ruan** [comment]
Hey @chongxiaoc Do you have regular SNAPSHOT releases that I can use to test this fix?

**Comment by chongxiaoc** [comment]
@serena-ruan Can you test with building from src or installing via pip from git commit?

**Comment by serena-ruan** [comment]
Yea it's a bit complicated to build from source, but I tested the fix works! Thanks!
