### ISSUE TITLE
Installing Horovod on M1 (Ultra and Laptops)

### ISSUE THREAD

**Issue by abhimanyuchadha96** [horovod/horovod#3578]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): TF-Metal
2. Framework version: 2.9
3. Horovod version: 0.24
7. Python version: 3.9
10. OS and version: macOS 12 and macOS13
12. CMake version: 3.23.2

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I have tried `pip install horovod` and making it from source but everytime I get this error.
Tried switching OS's too. 

I am trying to replicate the demo showed in this year's WWDC for distributed training along different M1 chips. 
https://developer.apple.com/videos/play/wwdc2022/10063/

No matter what combination I try I get the following error:-

![Screen Shot 2022-06-13 at 4 00 52 PM](https://user-images.githubusercontent.com/37940438/173435192-0d100e2f-ffe7-4624-bc81-01b86beaa2bf.png)

Any help would be appreaciated.

**Comment by abhimanyuchadha96** [comment]
`    /Users/abhimanyuchadha/miniforge3/lib/python3.9/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
    #include <google/protobuf/port_def.inc>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make[2]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/mpi_ops.cc.o] Error 1
    make[1]: *** [horovod/tensorflow/CMakeFiles/tensorflow.dir/all] Error 2
    make: *** [all] Error 2`

Follow-up to the previous one.

**Comment by maxhgerlach** [comment]
Hi @abhimanyuchadha96,  this bit is your root error: 
![image](https://user-images.githubusercontent.com/1778667/173567501-6698ecf4-86cb-4367-aa78-cf0107f851c2.png)
See instructions at https://horovod.readthedocs.io/en/stable/install_include.html#gloo

**Comment by abhimanyuchadha96** [comment]
I was missing the `pkg-config` and not `libuv`
Thanks for the help though.
