### ISSUE TITLE
SSH between containers - Horovod multi-container training

### ISSUE THREAD

**Issue by bluepra** [horovod/horovod#3596]
**Here is what I am working with:**
2 separate docker containers, each on a different VM
Both VM's have 1 GPU each

I am trying to follow "Running on multiple machines" from [https://horovod.readthedocs.io/en/stable/docker_include.html ](url)

**On VM 1:**
nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest

**On VM 2:**
nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest bash -c "/usr/sbin/sshd -p 6006; sleep infinity"

**Back on VM 1:**
horovodrun -np 2 -H {first_VM_IP}:6006:1, {second_VM_IP}:6006:1 -p 6006 python multi_worker_training.py

I get an error that says
![image](https://user-images.githubusercontent.com/71447892/177842942-f367d824-7697-4279-9cbb-8f4607f1b973.png)

What am I doing wrong? Something is going wrong between SSH-ing between the 2 containers. Any tips are appreciated!

**Comment by EnricoMi** [comment]
With `{first_VM_IP}:6006` you are telling `horovodrun` to connect via SSH to the first container, but you are not running SSH on it, so it fails testing the SSH connection.

You could start ssh first and then run `horovodrun`:

```
bash -c "/usr/sbin/sshd -p 6006; horovodrun -np 2 -H {first_VM_IP}:6006:1, {second_VM_IP}:6006:1 -p 6006 python multi_worker_training.py"
```

Further, I am not sure if providing the port with `-H` works.

**Comment by EnricoMi** [comment]
You can create a docker network with `docker network create --internal horovod`.

Then you can start the docker containers with `--name horovod-1 --network=horovod` and `--name horovod-2 --network=horovod`, respectively. No need to use a bespoke SSH port then:

```
horovodrun -H horovod-1:2,horovod-2:2 ...
```

**Comment by bluepra** [comment]
If my containers are on 2 separate VMs, wont I need to use docker swarm and then an overlay network?

**Comment by EnricoMi** [comment]
Right, I presumed those docker containers were on the same host. In that case you will need something like that, yes.

**Comment by bluepra** [comment]
So here is what I tried:
on the same VM, I made 2 containers (first and second) and attached them to the same bridge network (net).

Then on container first, I try to run this command:
horovodrun -np 2 -H first:1 second:1 python training.py

And I get this:

--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 2
slots that were requested by the application:

second:1

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------

My VM has 3 GPUs so I don't why this is causing an issue.

**Comment by EnricoMi** [comment]
The hosts option (`-H`) is a comma-separated string, you have a space between `first:1` and `second:1`.

**Comment by bluepra** [comment]
So on the same VM I set up a internal bridge network like you mentioned. Then I spun up to 2 containers first and second and put them both in the network. 

From the first network I run the command:
horovodrun -np 2 -H first:1,second:1 --verbose python horovod_training.py

And I get this:
![image](https://user-images.githubusercontent.com/71447892/180450728-70016b95-42b6-4bb2-aa89-8513b66390a5.png)

Still having SSH issues with containers, any help appreciated!

**Comment by EnricoMi** [comment]
Does the following work in either of the containers (`first` and `second`)?
```
ping first
ping second
ssh first
ssh second
```

**Comment by bluepra** [comment]
from within first, I can successfully "ping second", but doing "ssh second" does not work.

I am guessing second can also ping first since they are in the same network.

**Comment by EnricoMi** [comment]
On which port did you start the ssh service on `second`?

**Comment by bluepra** [comment]
From within second, I try to ssh into second and I get this:
ssh: connect to host second port 22: Connection refused

In my docker compose this is what I have for second's ports:
![image](https://user-images.githubusercontent.com/71447892/180859741-e68e0a19-58d2-478b-bd70-c69fa096cf63.png)

Also how do I start the ssh service on second?

**Comment by EnricoMi** [comment]
As above: `/usr/sbin/sshd -p 6006`, but this will start SSH on port 6006, not the default 22.
