### ISSUE TITLE
torch.utils.ffi was removed but is still used in horovod

### ISSUE THREAD

**Issue by adamjstewart** [horovod/horovod#3606]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.12.0
3. Horovod version: 0.25.0
4. MPI version: OpenMPI 4.1.4
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.9.13
8. Spark / PySpark version: N/A
9. Ray version: N/A
10. OS and version: macOS 12.4
11. GCC version: Apple Clang 13.1.6
12. CMake version: 3.23.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

In `torch/mpi_lib/__init__.py` and `torch/mpi_lib_impl/__init__.py`, horovod imports `torch.utils.ffi`. But this module was deprecated in PyTorch 1.0 (https://github.com/pytorch/pytorch/pull/12122) almost 5 years ago and finally removed completely in PyTorch 1.12.

**Comment by maxhgerlach** [comment]
I believe that should be dead code remaining from an earlier refactoring. Removing it makes sense of course, but does its presence actually cause a problem on your end?

**Comment by adamjstewart** [comment]
Presence doesn't cause problems, I discovered this when I added a test to try to import all subpackages to make sure everything was installed correctly.
