### ISSUE TITLE
fatal error: cuda_runtime.h: No such file or directory when install horovod0.25.0 for pytorch 1.12.0

### ISSUE THREAD

**Issue by Vaisual** [horovod/horovod#3607]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.12.0+cu102
3. Horovod version: 0.25.0
4. MPI version: 3.3.2
5. CUDA version: 11.4
6. NCCL version: 2708
7. Python version: 3.7.11
8. Spark / PySpark version: -
9. Ray version: -
10. OS and version: Ubuntu 20.04
11. GCC version: 9.4.0
12. CMake version: 3.16.3

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

The log message is:
...
```
 -- Check for working CUDA compiler: /usr/bin/nvcc
  -- Check for working CUDA compiler: /usr/bin/nvcc -- broken
  CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCUDACompiler.cmake:46 (message):
    The CUDA compiler

      "/usr/bin/nvcc"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: /tmp/pip-install-sdc92xa_/horovod_13655bbc44644fc592f95afa5f211799/build/temp.linux-x86_64-3.7/RelWithDebInfo/CMakeFiles/CMakeTmp

      Run Build Command(s):/usr/bin/make cmTC_be0ec/fast && /usr/bin/make -f CMakeFiles/cmTC_be0ec.dir/build.make CMakeFiles/cmTC_be0ec.dir/build
      make[1]: Entering directory '/tmp/pip-install-sdc92xa_/horovod_13655bbc44644fc592f95afa5f211799/build/temp.linux-x86_64-3.7/RelWithDebInfo/CMakeFiles/CMakeTmp'
      Building CUDA object CMakeFiles/cmTC_be0ec.dir/main.cu.o
      /usr/bin/nvcc -ccbin=/home/zorn/miniconda3/envs/vai/bin/x86_64-conda-linux-gnu-c++    -x cu -c /tmp/pip-install-sdc92xa_/horovod_13655bbc44644fc592f95afa5f211799/build/temp.linux-x86_64-3.7/RelWithDebInfo/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_be0ec.dir/main.cu.o
      **cc1plus: fatal error: cuda_runtime.h: No such file or directory**
      compilation terminated.
      make[1]: *** [CMakeFiles/cmTC_be0ec.dir/build.make:66: CMakeFiles/cmTC_be0ec.dir/main.cu.o] Error 1
      make[1]: Leaving directory '/tmp/pip-install-sdc92xa_/horovod_13655bbc44644fc592f95afa5f211799/build/temp.linux-x86_64-3.7/RelWithDebInfo/CMakeFiles/CMakeTmp'
      make: *** [Makefile:121: cmTC_be0ec/fast] Error 2

 CMake will not be able to correctly generate this project.
```
Full log can be found [here](https://drive.google.com/file/d/14kGgRCquRTtK9Eq2JMDSqMqbihngH5IQ/view?usp=sharing).

I tried setting these paths but it didn't help:
```
export PATH=/usr/lib/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/lib/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

```
p.s. The "cuda_runtime.h" file is located at:
/usr/include/cuda_runtime.h
I also tried adding this folder to path but nothing changed:
`export PATH=/usr/include${PATH:+:${PATH}}
`

Please help to solve this issue!
Thank you in advance!

**Comment by maxhgerlach** [comment]
Have you tried to set the `HOROVOD_CUDA_HOME` environment variable? Cf. https://horovod.readthedocs.io/en/stable/install_include.html#environment-variables
