### ISSUE TITLE
horovod can't run on kubernetes's flannel which network model is host-gw

### ISSUE THREAD

**Issue by kinglion811** [horovod/horovod#365]
I run horovod on kubernetes,the network I use flannel,and use host-gw,when I run the example of tensorflow_word2vec.py,the job can not run in right.the information like this:

![image](https://user-images.githubusercontent.com/6119243/42454578-70a4e2d2-83c2-11e8-8211-942bbff1bc2f.png)

the flannel network is 172.30.x.x the host network is 10.28.x.x

**Comment by alsrgv** [comment]
@kinglion811, can you determine interface name of the flannel network using `ifconfig`, and specify `-mca_btl_tcp_if_include <that interface>` instead of `-mca btl_tcp_if_exclude docker0,lo`?

**Comment by zwqjoy** [comment]
@kinglion811  If use flannel, https://github.com/uber/horovod/issues/645

**Comment by zwqjoy** [comment]
@kinglion811 If use flannel with vxlan, #645,    also failed.    mpirun -np 2 -H 127.0.0.1,172.17.91.2  --mca btl ^tcp  -mca btl_base_verbose 100 python keras_mnist_advanced.py

**Comment by kinglion811** [comment]
@zwqjoy seam as it

**Comment by zwqjoy** [comment]
@xychu https://github.com/uber/horovod/issues/645
