### ISSUE TITLE
Collective ops: support for GatherOP for model parallel use cases.

### ISSUE THREAD

**Issue by MrAta** [horovod/horovod#3655]
**Is your feature request related to a problem? Please describe.**
In model parallel use cases where each rank trains a part of model, after training, for constructing and saving the full model, usually on rank 0, it needs to gather the weights from other ranks.

**Describe the solution you'd like**
An ideal solution would be horovod supporting Gatherop for this use case.

**Describe alternatives you've considered**
Currently the alternative is using existing broadcast op which is slightly wasteful because other ranks also receive the weights for full model while they don't need to.

**Additional context**
N/A

**Comment by maxhgerlach** [comment]
Could you use `hvd.alltoall` to the same effect, with the `splits` argument set in such a way that every process only sends to the root rank? 

Presumably it would be less efficient than a dedicated `gather` op, where the backend would use more optimized communication patterns. But there's a chance it would be less wasteful than `broadcast`.
