### ISSUE TITLE
Do we have to pass experimental_run_tf_function = False for model.compile()

### ISSUE THREAD

**Issue by bluepra** [horovod/horovod#3656]
So I am using tensorflow 2.7.1 with a keras model to train a model on 2 VMs (1 GPU each).

I am confused if I am supposed to pass experimental_run_tf_function = False for model.compile() before calling model.fit().

I looked at the tf.keras.Model API and the .compile() function does not have a experimental_run_tf_function argument.

**Comment by chongxiaoc** [comment]
We have TF 2.7 in CI for example https://github.com/horovod/horovod/runs/8065886938?check_suite_focus=true

But I don't think `experimental_run_tf_function` is explicitly set there.
