### ISSUE TITLE
Can't Install Horovod for TensorFlow on M1 Platform (TF 1.15)

### ISSUE THREAD

**Issue by ZhiyeTang** [horovod/horovod#3668]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow
2. Framework version: 1.14.0
3. Horovod version: 0.25.0
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version: 3.6.6
8. Spark / PySpark version:
9. Ray version:
10. OS and version: macOS Monterey
11. GCC version: Apple clang version 13.1.6
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I'm using a MacBook Pro with M1 Pro chip. I was following the guide docs and issues, pre-installed `libuv` and `pkg-config`. Then I tried `pip install horovod` which works well, installed horovod-0.25.0 for me. But then I tried:
`import horovod.tensorflow`
I got a `ImportError`, showing "ImportError: Extension horovod.tensorflow has not been built". Great. I tried to reinstall horovod. But neither
`HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod`
nor
`HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod[tensorflow]`
can solve my issue.

**Comment by TongChiYip** [comment]
Ok after I turned down the no match for `zsh`, and then switched to tf-1.15, I could finally build horovod for TensorFlow. But when I tried again to `import horovod.tensorflow`, another error occurred:
`tensorflow.python.framework.errors_impl.NotFoundError: dlopen(horovod/tensorflow/mpi_lib.cpython-36m-darwin.so, 0x0006): symbol not found in flat namespace (_uv_accept)`

What is it mean? And how could I solve it? Thanks a lot.

**Comment by maxhgerlach** [comment]
I think you are better of using `tensorflow-macos` on M1 Pro, with a recent version like 2.9. Is TF 1.x even supported with aarch64?

Here is a guide from: https://developer.apple.com/metal/tensorflow-plugin/

**Comment by TongChiYip** [comment]
Yes, I've installed tf-1.x via Anaconda and it seems that nothing goes wrong.

**Comment by maxhgerlach** [comment]
Is that Rosetta or native arm64?

If you want to debug your build problems, have you tried to add a `-v` to your pip install lines?

**Comment by TongChiYip** [comment]
Just via a command in `zsh`: `pip install tensorflow-1.x`, and the installation goes well.
I don't exactly know how to debug by adding a `-v`? Can you offer some related docs?

**Comment by maxhgerlach** [comment]
`pip install -v horovod` or similar will give you more output logs. Else it's hard to tell anything about the build error.
