### ISSUE TITLE
Number of epochs division on number of GPU

### ISSUE THREAD

**Issue by Nafees-060** [horovod/horovod#3675]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version: 2.2.0
3. Horovod version:  v0.21.3
4. MPI version:  (Open MPI) 2.1.1
5. CUDA version: 10.1, V10.1.243
6. NCCL version:  2.11.4
7. Python version: 3.6.9
11. CMake version:  3.10.2

I am trying to train a model using data parallelism on multiple GPUs on a single machine. As I think, in data parallelism, we divide the data into batches, and then batches are deployed parallel. Afterward, the average gradient is calculated based on the current batch errors (for example, if there are 2 GPUs: errors will be 2 batches) and updated based on the average gradient. 

Now, when I implemented horovod, I observed some other things. For example, I observed that the number of epochs trained is divided according to the number of GPUs. For example, if I train the model on 300 epochs, then, on 1 GPU, the number of epochs is 300, but on 2 GPUs, it is divided into 150 epochs (150 epochs process GPU1 and remains 150 epochs process 2nd GPU), and similarly, on 3 GPUs, it is 100 epochs. Is this correct? If it is correct, then how does it achieve data parallelism?

**Here is my code:**

```
import math
import sys
import time
import scipy.io
import numpy as np
import pandas as pd
from sklearn import metrics
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()
from tensorflow.compat.v1.keras import backend as K
import horovod.tensorflow.keras as hvd

from tensorflow.keras.models import Sequential

# Horovod: initialize Horovod.
hvd.init()
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
physical_gpus = tf.config.list_physical_devices('GPU')
tf.config.set_visible_devices([physical_gpus[hvd.local_rank()]], "GPU")



def main():
    input_shape = (seg_train_x.shape[1], seg_train_x.shape[2], seg_train_x.shape[3])
    print(f'input shape {input_shape}')
    epochs = int(math.ceil(300.0 / hvd.size()))
    batch_size = 100
    model = Sequential()
    model.add(Conv2D(16, kernel_size=(3, 3),
                     activation='relu',
                     input_shape=input_shape))
    model.add(Conv2D(32, (3, 3), activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01),
                     bias_regularizer=tf.keras.regularizers.l1(0.01)))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
    model.add(Flatten())
    model.add(Dense(64, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(num_classes, activation='softmax'))
    # Horovod: adjust learning rate based on number of GPUs.
    scaled_lr = 0.00001 * hvd.size()
    opt = tf.keras.optimizers.Adam(scaled_lr)
    # Horovod: add Horovod Distributed Optimizer.
    opt = hvd.DistributedOptimizer(opt, backward_passes_per_step=1)

    model.compile(loss=tf.keras.losses.categorical_crossentropy,
                  optimizer=opt,
                  metrics=['accuracy'])

    callbacks = [
        # Horovod: broadcast initial variable states from rank 0 to all other processes.
        # This is necessary to ensure consistent initialization of all workers when
        # training is started with random weights or restored from a checkpoint.
        hvd.callbacks.BroadcastGlobalVariablesCallback(0),
    ]
    print(f'input shape {seg_train_x.shape}')
    # Horovod: save checkpoints only on worker 0 to prevent other workers from corrupting them.
    if hvd.rank() == 0:
        callbacks.append(tf.keras.callbacks.ModelCheckpoint('./checkpoint-{epoch}.h5'))

    csv_logger = tf.keras.callbacks.CSVLogger('training.log')

    start = time.time()
    model.fit(
        seg_train_x,
        seg_train_y,
        batch_size=batch_size,
        callbacks=[callbacks, csv_logger],
        epochs=epochs,
        validation_data= (seg_val_x, seg_val_y),
        verbose=1 if hvd.rank() == 0 else 0,
    )
    end = time.time()
    if hvd.rank() == 0:
        print('Total Training Time:', round((end - start), 2), '(s)')

    score = model.evaluate(seg_test_x, seg_test_y, verbose=0)
    y_pred_test = model.predict(seg_test_x)
    # Take the class with the highest probability from the test predictions
    max_y_pred_test = np.argmax(y_pred_test, axis=1)
    max_y_test = np.argmax(seg_test_y, axis=1)  # actual test labels
    fScore = metrics.f1_score(max_y_test, max_y_pred_test, average='macro')
    print('Test loss:', score[0])
    print('Test accuracy:', score[1])
    print('F1-Score:', fScore)
if __name__ == '__main__':
    main()
```

**Comment by chongxiaoc** [comment]
Using n GPUs is equivalent to using nX batch size on a single GPU.
Assuming you have 1000 samples, batch_size = 10.
n_steps_per_epoch = 1000/ 10 =100 for a single GPU training.

Equivalently, n_steps_per_epoch = 1000 / n / 10 for n GPUs training.\
You need to modify `seg_train_x ` to be sharded by horovod rank (that is GPU id) so every GPU can get different samples in a single epoch, you can refer from examples in Horovod. This is a good one: https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_keras_mnist.py#L97

You can keep epochs to be the same, while expecting n_steps_per_epoch to be nX smaller.

**Comment by Nafees-060** [comment]
@chongxiaoc Thank you so much for the answer. Other than that I want to see the model convergence on The effect of shuffling the data and Without shuffling the data instances. There may be a situation where a batch with label-1 is fed to a GPU and another batch consisting of label-2 is fed to another GPU. It will be interesting to see how the model converges in the case of shuffling and not shuffling. Now the concern is how to feed the validation dataset after each training epoch and which GPU will process the validation dataset if multiple GPUs are available.

**Comment by Nafees-060** [comment]
> Using n GPUs is equivalent to using nX batch size on a single GPU. Assuming you have 1000 samples, batch_size = 10. n_steps_per_epoch = 1000/ 10 =100 for a single GPU training.
> 
> Equivalently, n_steps_per_epoch = 1000 / n / 10 for n GPUs training. You need to modify `seg_train_x ` to be sharded by horovod rank (that is GPU id) so every GPU can get different samples in a single epoch, you can refer from examples in Horovod. This is a good one: https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_keras_mnist.py#L97
> 
> You can keep epochs to be the same, while expecting n_steps_per_epoch to be nX smaller.

You mentioned that I need to modify seg_train_x to be sharded by horovod rank (that is GPU id) so every GPU can get different samples in a single epoch, and you refer examples. In example, we can see 
```
    (mnist_images, mnist_labels), _ = \
        tf.keras.datasets.mnist.load_data(path='mnist-%d.npz' % hvd.rank())
```
I cannot understand that what happening inside here, can you please help me to clear this line, so I can modify my `seg_train_x`.

**Comment by chongxiaoc** [comment]
Hi @Nafees-060 
In the example above, input is a list of files, so we use `load_data(path='mnist-%d.npz' % hvd.rank())` to split different files to different GPUs (using Horovod rank).

How to split your input depends on your case, you can do `sample_id % hvd.rank()` to select samples to each GPU/rank, this really depends on input type and it is user's configuraton.

As you mentioned above, validation data needs to be split as well, same is training data.

**Comment by Nafees-060** [comment]
@ch

> @chongxiaoc Thank you so much for the answer. Other than that I want to see the model convergence on The effect of shuffling the data and Without shuffling the data instances. There may be a situation where a batch with label-1 is fed to a GPU and another batch consisting of label-2 is fed to another GPU. It will be interesting to see how the model converges in the case of shuffling and not shuffling. Now the concern is how to feed the validation dataset after each training epoch and which GPU will process the validation dataset if multiple GPUs are available.

@chongxiaoc I am eagerly awaiting an answer to this question.

**Comment by chongxiaoc** [comment]
```
Now the concern is how to feed the validation dataset after each training epoch and which GPU will process the validation dataset if multiple GPUs are available.
```

Validation data is split on multiple GPUs and the metric should be an avg of multiple GPUs training.
Please use this `hvd.callbacks.MetricAverageCallback()`  callback as in the example: https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_keras_mnist.py#L80

**Comment by Nafees-060** [comment]
> Using n GPUs is equivalent to using nX batch size on a single GPU. Assuming you have 1000 samples, batch_size = 10. n_steps_per_epoch = 1000/ 10 =100 for a single GPU training.
> 
> Equivalently, n_steps_per_epoch = 1000 / n / 10 for n GPUs training. You need to modify `seg_train_x ` to be sharded by horovod rank (that is GPU id) so every GPU can get different samples in a single epoch, you can refer from examples in Horovod. This is a good one: https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_keras_mnist.py#L97
> 
> You can keep epochs to be the same, while expecting n_steps_per_epoch to be nX smaller.

Thank you so much for the help. I am confused in `steps_per_epoch=500 `  in `mnist_model.fit(dataset, steps_per_epoch=500 // hvd.size(), callbacks=callbacks, epochs=24, verbose=verbose)`. Can you please provide me a bit detail about this 500. Thank you

**Comment by chongxiaoc** [comment]
`steps_per_epoch` is a pamater of keras fit function to tell how many batches to use per epoch on single GPU.
Users use this paramter to explicitly force model to be trained with 500 batches per epoch.
This doesn't conflict with splitting inputs on multiple GPUs.
Duplicated samples might be introduced in a single epoch if input doesn't have 500 batches for a single epoch, depends on how input dataset is setup and this is user's decision.

Explained at https://keras.io/api/models/model_training_apis/

```steps_per_epoch: Integer or None. Total number of steps (batches of samples) before declaring one epoch finished and starting the next epoch. When training with input tensors such as TensorFlow data tensors, the default None is equal to the number of samples in your dataset divided by the batch size, or 1 if that cannot be determined. If x is a [tf.data](https://www.tensorflow.org/api_docs/python/tf/data) dataset, and 'steps_per_epoch' is None, the epoch will run until the input dataset is exhausted. When passing an infinitely repeating dataset, you must specify the steps_per_epoch argument. If steps_per_epoch=-1 the training will run indefinitely with an infinitely repeating dataset. This argument is not supported with array inputs. When using [tf.distribute.experimental.ParameterServerStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/ParameterServerStrategy): * steps_per_epoch=None is not supported.
```

**Comment by Nafees-060** [comment]
> `steps_per_epoch` is a pamater of keras fit function to tell how many batches to use per epoch on single GPU. Users use this paramter to explicitly force model to be trained with 500 batches per epoch. This doesn't conflict with splitting inputs on multiple GPUs. Duplicated samples might be introduced in a single epoch if input doesn't have 500 batches for a single epoch, depends on how input dataset is setup and this is user's decision.
> 
> Explained at https://keras.io/api/models/model_training_apis/

It means it is not compulsory to mention, right?

**Comment by chongxiaoc** [comment]
> It means it is not compulsory to mention, right?

Right. But users have to make every GPU has equivalent data to train per epoch (depends on data distribution).  Horovod doesn't control it.

**Comment by Nafees-060** [comment]
It means I  can set steps_per_epoch value in the following way:

`total_train_data = 1000, Batchsize=20, Number of GPUs=2 Then step_per_epoch=1000/20=50/Number of GPUs= 25 `

right?

**Comment by Nafees-060** [comment]
Thank you so much for the help. Resolving horovod issues, I've encountered a weird error; if you know how to fix it, kindly help me.
```
[1,2]<stderr>:    my_model.compile(loss=tf.losses.SparseCategoricalCrossentropy(),
[1,2]<stderr>:AttributeError: 'list' object has no attribute 'compile'
```
**here is the code:**
```
my_model = tf.keras.Sequential()([
        tf.keras.layers.Conv2D(16, kernel_size=(3, 3),
                      activation='relu'),
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01),
                               bias_regularizer=tf.keras.regularizers.l1(0.01)),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
        tf.keras.layers.Dropout(0.25),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dropout(0.5),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    # Horovod: adjust learning rate based on number of GPUs.
    scaled_lr = 0.00001 * hvd.size()
    opt = tf.keras.optimizers.Adam(scaled_lr)
    # opt = tf.keras.optimizers.Adam(0.00001 * hvd.size())
    print("Pakistan")
    # Horovod: add Horovod DistributedOptimizer.
    opt = hvd.DistributedOptimizer(
        opt, backward_passes_per_step=1, average_aggregated_gradients=True)

    # Horovod: Specify `ex  perimental_run_tf_function=False` to ensure TensorFlow
    # uses hvd.DistributedOptimizer() to compute gradients.
    my_model.compile(loss=tf.losses.SparseCategoricalCrossentropy(),
                      optimizer=opt,
                      metrics=['accuracy'],
                      experimental_run_tf_function=False)
```

**Comment by Nafees-060** [comment]
> is a pamater of keras fit function to tell how many batches to use per epoch on single GPU.

Hi @chongxiaoc  I tried to modify seg_train_x to be sharded by horovod rank (that is GPU id) in the following way:
```
 dataset_train = tf.data.Dataset.from_tensor_slices((seg_train_x, seg_train_y))
 dataset_train = dataset_train.repeat().shuffle(10000).batch(256)
 dataset_train = dataset_train.shard(hvd.size(), hvd.rank())
dataset_val = tf.data.Dataset.from_tensor_slices((seg_val_x, seg_val_y))
dataset_val = dataset_val.shard(hvd.size(), hvd.rank())
```
Can you please verify and acknowledge me  about its correctness?
