### ISSUE TITLE
Getting error with mpirun

### ISSUE THREAD

**Issue by tremblerz** [horovod/horovod#368]
I am having some trouble with starting tensorflow_mnist example on horovod. The setup has two gpu servers, `server1` and `server2` with installation performed on both of them as described in https://github.com/uber/horovod/blob/master/docs/gpus.md

I run the following command on both server
`mpirun -np 2 -H server1:1,server2:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python tensorflow_mnist.py`

Output on server1 is:
```
[CPSG-AI-GPU-2:46613] [[17593,0],1] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[17593,0],1] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)

This is something that should be reported to the developers.
--------------------------------------------------------------------------
```
Output on server2 is:
```
[CPSG-AI-GPU-2:46486] [[26619,0],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file base/plm_base_launch_support.c at line 1180
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
```
After doing some bug hunt, found this issue https://github.com/open-mpi/ompi/issues/4437, and the only difference I can find between two servers is as following(both commands have been run from server1) -

`ssh server2 ompi_info|grep oob:` gives output as 

> MCA oob: tcp (MCA v2.1.0, API v2.0.0, Component v3.1.1)

while `ompi_info|grep oob:` gives output as

>MCA oob: tcp (MCA v2.1.0, API v2.0.0, Component v3.1.1)
  MCA oob: ud (MCA v2.1.0, API v2.0.0, Component v3.1.1)

I installed openmpi on both servers separately but installation and everything is same as far as I remember.

**Comment by alsrgv** [comment]
@tremblerz, I suspect there may be an issue with MPI version mismatch.  Couple of things to check:
1. Did you install both Open MPI in the same location?  
2. Did you specify `--enable-mpirun-prefix-by-default` option to `./configure`?  If not, I'd recommend doing that.
