### ISSUE TITLE
Specify MPI compiler, compiler flags, library flags

### ISSUE THREAD

**Issue by felker** [horovod/horovod#3696]
**Environment:**
1. Framework: TensorFlow and PyTorch
2. Framework version: TF 2.10.0, PyTorch 1.12.1
3. Horovod version: 0.26
4. MPI version: Cray MPICH 8.1.16
5. CUDA version: 11.6.2
6. NCCL version: 2.14.3
7. Python version: 3.8
8. Spark / PySpark version: N/A
9. Ray version: N/A
10. OS and version: SLES 15.3
11. GCC version: 11.2
12. CMake version: 3.22.1

**Bug report:**
I am currently trying to build Horovod from support with NCCL and MPI support. My build command is something along the lines of 
```
MPI_ROOT=/opt/cray/pe/mpich/8.1.16/ofi/gnu/9.1 HOROVOD_WITH_MPI=1 HOROVOD_CUDA_HOME=/soft/compilers/cudatoolkit/cuda-11.6.2 HOROVOD_NCCL_HOME=/soft/libraries//nccl/nccl_2.14.3-1+cuda11.6_x86_64 HOROVOD_CMAKE=/soft/datascience/conda/2022-09-08/mconda3/bin/cmake HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 python setup.py bdist_wheel
```
From what I can decipher from the build process, Horovod never uses `mpicc` but instead uses the underlying wrapped `g++` compiler and adds the MPI library e.g. 
```
-- Found MPI_CXX: /opt/cray/pe/mpich/8.1.16/ofi/gnu/9.1/lib/libmpi_gnu_91.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
...
```
Thus `/opt/cray/pe/mpich/8.1.16/ofi/gnu/9.1/lib/libmpi_gnu_91.so` added in the link steps. However, Cray MPICH uses wrapper compilers `cc` `CC` and often adds other essential compiler flags and libraries such as `-lmpi_gtl_cuda` for CUDA-Aware MPICH (which I know isnt necessary for Horovod operations, but to build Horovod with it regardless).

I could not find a way to specify MPI-only compiler flags and/or link flags. What is the easiest way to add this?

I tried `HOROVOD_BUILD_ARCH_FLAGS='-shared -target-accel=nvidia80'`, but this does not work likely since it is only accepts `gcc` flags: 
```
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
-- Could NOT find MPI (missing: MPI_CXX_FOUND)
```

**Comment by maxhgerlach** [comment]
Hmm, indeed we currently only pick up MPI includes and libraries in CMake at https://github.com/horovod/horovod/blob/e4146b54fa39010f8e1129d42226367173d3947f/CMakeLists.txt#L138

Would [FindMPI](https://cmake.org/cmake/help/latest/module/FindMPI.html) pick up these extra flags and libraries set by Cray's wrapper into one of the additional variables?
> MPI_\<lang\>_COMPILER
> 
>     MPI compiler for \<lang\> if such a program exists.
> MPI_\<lang\>_COMPILE_OPTIONS
> 
>     Compilation options for MPI programs in \<lang\>, given as a [;-list](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#cmake-language-lists).
> MPI_\<lang\>_COMPILE_DEFINITIONS
> 
>     Compilation definitions for MPI programs in \<lang\>, given as a [;-list](https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#cmake-language-lists).
> MPI_\<lang\>_INCLUDE_DIRS
> 
>     Include path(s) for MPI header.
> MPI_\<lang\>_LINK_FLAGS
> 
>     Linker flags for MPI programs.
> 
>

**Comment by felker** [comment]
Hi @maxhgerlach , thanks for the pointer--- indeed I was able to specify the wrapper compilers via 
```
MPI_C_COMPILER="cc" MPI_CXX_COMPILER="CC"
```

I think it might be worth adding a note to: https://horovod.readthedocs.io/en/stable/install_include.html#environment-variables 

Unlike [FindCUDAToolkit](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#module:FindCUDAToolkit), which I think is the only other Find Module in the CMake distribution that Horovod uses, FindMPI refers to many environment variables to control how it locates the MPI library (which isnt exposed by any Horovod-specific env vars described in the docs). 

Perhaps something along the lines of:
> For a list of additional environment variables for specifying the location and configuration of the MPI library during the installation process, consult the CMake [FindMPI](https://cmake.org/cmake/help/latest/module/FindMPI.html) documentation.

**Comment by maxhgerlach** [comment]
Great to hear that you found a workaround, @felker!

But if you can compile programs via `mpicxx` on the command line without further options, you ideally shouldn't have to specify `MPI_CXX_COMPILER` manually when building Horovod. What I meant to ask was if we should adapt Horovod's CMake script to make use of `MPI_CXX_COMPILE_OPTIONS`, `MPI_CXX_COMPILE_DEFINITIONS`, (etc.) variables, which are populated by `FindMPI`.

Alternatively it might be possible to make use of the fact that we are on CMake 3.13+ now and there are some more modern facilities available, e.g., https://cliutils.gitlab.io/modern-cmake/chapters/packages/MPI.html
If I understand that correctly it might be possible to just add `MPI::MPI_CXX` as an extra target to `target_link_libraries` without using any of the more specific option variables.

**Comment by AlexisEspinosaGayosso** [comment]
Dear @felker and @maxhgerlach , the suggestion here is not working for me on a HPE-CRAY EX with AMD GPUs. So I'm using the following for installation:
```
export HOROVOD_WITHOUT_MXNET=1
export HOROVOD_WITHOUT_PYTORCH=1
export HOROVOD_GPU=ROCM
export HOROVOD_GPU_OPERATIONS=NCCL
export HOROVOD_WITHOUT_GLOO=1
export HOROVOD_WITH_TENSORFLOW=1
export HOROVOD_ROCM_PATH=$ROCM_PATH
export HOROVOD_RCCL_HOME=$HOROVOD_ROCM_PATH/rccl
export RCCL_INCLUDE_DIRS=$HOROVOD_RCCL_HOME/include
export HOROVOD_RCCL_LIB=$HOROVOD_RCCL_HOME/lib
export HOROVOD_MPICXX_SHOW="CC --cray-print-opts=all"
export HCC_AMDGPU_TARGET=gfx90a
export MPI_C_COMPILER=cc
export MPI_CXX_COMPILER=CC
pip install --verbose horovod
```

And still getting the errors:
```
  -- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
  -- Could NOT find MPI (missing: MPI_CXX_FOUND)
  .
  .
  .
    /tmp/pip-install-m05v44lf/horovod_ea75e954a3b349f899fd1d6135434463/horovod/common/process_set.cc:173:10: error: 'struct horovod::common::ProcessSet' has no member named 'Initialize'; did you mean 'Finalize'?
    173 |   Get(0).Initialize(global_context);
        |          ^~~~~~~~~~
        |          Finalize
  /tmp/pip-install-m05v44lf/horovod_ea75e954a3b349f899fd1d6135434463/horovod/common/process_set.cc: In member function 'int32_t horovod::common::ProcessSetTable::InitializeRegisteredAndRemoveMarkedIfReady_(const Context&, const horovod::common::Status&)':
  /tmp/pip-install-m05v44lf/horovod_ea75e954a3b349f899fd1d6135434463/horovod/common/process_set.cc:209:39: error: 'struct horovod::common::ProcessSet' has no member named 'Initialize'; did you mean 'Finalize'?
    209 |       bool newly_registered = Get(id).Initialize(global_context);
        |                                       ^~~~~~~~~~
        |                                       Finalize
  /tmp/pip-install-m05v44lf/horovod_ea75e954a3b349f899fd1d6135434463/horovod/common/process_set.cc:212:13: error: 'TRACE' was not declared in this scope
    212 |         LOG(TRACE, global_controller.GetRank())
        |             ^~~~~
  /tmp/pip-install-m05v44lf/horovod_ea75e954a3b349f899fd1d6135434463/horovod/common/process_set.cc:212:9: error: there are no arguments to 'LOG' that depend on a template parameter, so a declaration of 'LOG' must be available [-fpermissive]
    212 |         LOG(TRACE, global_controller.GetRank())
        |         ^~~
```

Do you have any further suggestions on how to guide FindMPI to find the `cray-mpich`?

Many thanks.
