### ISSUE TITLE
Does Horovod + Ray support `all_gather`?

### ISSUE THREAD

**Issue by vedantroy** [horovod/horovod#3723]
Hi! I noticed elastic horovod requires gloo. My model, uses an `all_gather` operation, which doesn't seem to be supported by `Gloo`. Does this mean I can't train my model using elastic horovod + GPUs, or is there maybe another solution?

**Comment by maxhgerlach** [comment]
Why do you think Horovod doesn't support Allgather operations with Gloo? The implementation is here: https://github.com/horovod/horovod/blob/4323663f25f98dc6e6deaa72e0e061d7e0c4672b/horovod/common/ops/gloo_operations.h#L87

It's also tested regularly in CI.

Moreover, Gloo would only be used for collective operations on CPU tensors. With GPUs you would most likely use the NCCL backend.

**Comment by vedantroy** [comment]
Ah my bad, I was wondering because [Pytorch's distributed backend doesn't support gloo](https://pytorch.org/docs/stable/distributed.html) for `all_gather`, but I didn't realize this was not true of Horovod.

One thing to note is, the Elastic Horovod docs say Horovod must be installed with Gloo support:
> Horovod >= 0.20.0 with Gloo support (install Horovod using HOROVOD_WITH_GLOO=1 to ensure it is installed)

Does this mean Elastic Horovod must use Gloo at runtime (thus relegating it to CPU-only training), or can it still be used with NCCL?
