### ISSUE TITLE
Pytorch-MPIAllreduce-ROCM installation error: undefined horovod symbol in horovodrun [HOROVOD_GPU_ALLREDUCE=MPI]

### ISSUE THREAD

**Issue by R0n12** [horovod/horovod#3728]
**Environment:**
1. Framework: **Pytorch**
2. Framework version: **1.12.0a0+git664058f** (v1.12.1 release source)
3. Horovod version: **commit 141f41ea93731b9e3d2d7ecbac70fc10e0a8ec7e** **PR** [**#3588**](https://github.com/horovod/horovod/pull/3588)
4. MPI version: MVAPICH2-GDR 2.3.7
5. CUDA version: **N/A**
6. NCCL version: **N/A**
7. ROCM version: **5.1.1**
8. Python version: **3.8.13**
9. Spark / PySpark version: **N/A**
10. Ray version: **N/A**
11. OS and version:
```
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```
13. GCC version: **10.3.0**
14. CMake version: **3.22.2**

**Checklist:**
1. Did you search issues to find if somebody asked this question before?  **Yes**
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I was able to build horovod on top of pytorch with mpiallreduce rocm support, however when I ran `horovodrun --check-build --verbose`, it is not able to detect built pytorch because of the following error:

`ImportError: /home/xu.3304/miniconda3/envs/hvd-torch-rocm/lib/python3.8/site-packages/horovod-0.25.0-py3.8-linux-x86_64.egg/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN7horovod6common16MPI_GPUAllreduceC1EPNS0_10GPUContextEPNS0_18HorovodGlobalStateE`

Horovod build command:  
```
HOROVOD_ROCM_HOME=/opt/rocm-5.1.1 CC=$(which mpicc) CXX=$(which mpicxx) HOROVOD_WITHOUT_GLOO=1 HOROVOD_WITH_MPI=1 HOROVOD_GPU=ROCM HOROVOD_GPU_ALLREDUCE=MPI HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 /home/xu.3304/miniconda3/envs/hvd-torch-rocm/bin/python setup.py install > "${outfile}" 2>&1
```

the horovod build log:  
[hvd_build.log](https://github.com/horovod/horovod/files/9721281/hvd_build.log)
the horovodrun checkbuild verbose output:  
[hvdrun_checkbuild_verbose.log](https://github.com/horovod/horovod/files/9721282/hvdrun_checkbuild_verbose.log)

**Comment by maxhgerlach** [comment]
Hi @R0n12,

thanks for the report!

In demangled form the error message states that the symbol `horovod::common::MPI_GPUAllreduce::MPI_GPUAllreduce(horovod::common::GPUContext*, horovod::common::HorovodGlobalState*)` is not found. That's caused apparently by `horovod/common/ops/mpi_gpu_operations.cc` not being linked in.

In CMake we incorporate that source file if Horovod is being built with both CUDA and MPI here: https://github.com/horovod/horovod/blob/4323663f25f98dc6e6deaa72e0e061d7e0c4672b/CMakeLists.txt#L193

Would you be able to test a build with a slightly patched `CMakeLists.txt` file on your end? Then you could try to add an equivalent block below `elseif(HOROVOD_GPU STREQUAL "ROCM")` at approximately https://github.com/horovod/horovod/blob/master/CMakeLists.txt#L212 and test that.

For example:
```
if(DEFINED HOROVOD_GPU_ALLREDUCE OR DEFINED HOROVOD_GPU_ALLGATHER OR DEFINED HOROVOD_GPU_BROADCAST OR DEFINED HOROVOD_GPU_ALLTOALL OR DEFINED HOROVOD_GPU_REDUCESCATTER)
    if(NOT DEFINED HOROVOD_GPU OR HOROVOD_GPU STREQUAL "CUDA")
        add_cuda()
    elseif(HOROVOD_GPU STREQUAL "ROCM")
        find_package(ROCM REQUIRED)
        include_directories(SYSTEM ${ROCM_INCLUDE_DIRS})
        list(APPEND LINKER_LIBS ${ROCM_LIBRARIES})
        set(CMAKE_CXX_FLAGS "${ROCM_COMPILE_FLAGS} ${CMAKE_CXX_FLAGS}")
        list(APPEND SOURCES "${PROJECT_SOURCE_DIR}/horovod/common/ops/hip_operations.cc"
                            "${PROJECT_SOURCE_DIR}/horovod/common/ops/gpu_operations.cc")
# new lines start:
        if(HAVE_MPI)
            list(APPEND SOURCES "${PROJECT_SOURCE_DIR}/horovod/common/ops/mpi_gpu_operations.cc")
        endif()
# new lines end
        add_definitions(-DHAVE_ROCM=1 -DHAVE_GPU=1)
        set(HAVE_ROCM TRUE)
    else()
        message(FATAL_ERROR "Unknown HOROVOD_GPU type: ${HOROVOD_GPU}")
    endif()
endif()
```

As far as I know nobody of the Horovod maintainers works with ROCm themselves at this time.

**Comment by R0n12** [comment]
Hi @maxhgerlach 

I apologize for the late reply. The additional block in `CMakeLists.txt` worked like a charm. I have created a pull request based on the changes.

Thank You!

**Comment by maxhgerlach** [comment]
Great, thanks for giving that a try and posting the PR!
