### ISSUE TITLE
static tsl::Status tsl::Status::OK() is deprecated warning when build with Tensorflow 2.11.0rc1

### ISSUE THREAD

**Issue by pfierek-hb-ai** [horovod/horovod#3757]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version: 2.11.0rc1
3. Horovod version: 0.26.1
4. MPI version: 4.1.2
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.8.10
8. Spark / PySpark version: N/A
9. Ray version: N/A
10. OS and version: ubuntu 20.04
11. GCC version: 9.4.0
12. CMake version: 3.16.3

**Bug report:**
When i install (build) horovod with tensorflow-cpu==2.11.0rc1 i get a lot of warnings, like: 
```horovod/tensorflow/mpi_ops.cc:1771:25: warning: ‘static tsl::Status tsl::Status::OK()’ is deprecated: Use `OkStatus()` (preferred) or `Status()` (wh
ich is backward compatible with TF v2.9 and lower) instead. [-Wdeprecated-declarations]                                                                                                     
 1771 |       return Status::OK();```

This problem did not appear in previous versions of Tensorflow.

**Comment by maxhgerlach** [comment]
Thanks for the report! Clearing warnings is very worthwhile.

Would you like to contribute a PR to update this? (Note that Horovod maintains compatibility with TF 1.15, so the code cannot only use idioms for TF 2.10+)

**Comment by maxhgerlach** [comment]
Builds now fail on `tfhead` because of this refactoring.
