### ISSUE TITLE
Huge amount of MPI_Allreduces when using NCCL

### ISSUE THREAD

**Issue by Anlubi** [horovod/horovod#3760]
**Environment:**
I used [NGC TensorFlow 1 container 22-09](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel-22-09.html#rel-22-09) 

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**

I tried running my application distributed by horovod. I got poor performance when getting inter connection between two nodes running each 2 A100 GPUs.
Taking a look into it by Nvidia Nsight System I get a bit confused. I thought of Horovod using NCCL Allreduce and MPI for some setup stuff. But in my Nsight profile i can see a lot of `MPI_Allreduce` operation with high runtimes and just a small amount of short running `NCCL_Allreduce`.
Is this a problem in my setup?
Can you please clarify for which purpose MPI and NCCL are used?
Any hints to get a better performance? I tried to set `HOROVOD_AUTOTUNE` but no improvement

![Screenshot from 2022-10-30 15-04-52](https://user-images.githubusercontent.com/109974897/198883706-a3b9fd8b-7d51-4992-b0db-be740e751a11.png)

![Screenshot from 2022-10-30 15-05-19](https://user-images.githubusercontent.com/109974897/198883710-df41eb58-0ee7-4765-95e7-ae8d66e30b3e.png)

**Comment by maxhgerlach** [comment]
I suppose some of your tensors or TF operations may accidentally be placed on CPU rather than GPU. Typically, NCCL will be used to allreduce GPU tensors, MPI for CPU tensors.

Have you checked the example code at https://github.com/horovod/horovod/tree/master/examples/tensorflow ?
