### ISSUE TITLE
Multinode training is slower compared to single node training

### ISSUE THREAD

**Issue by PurvangL** [horovod/horovod#3788]
I have scaled up my training from 
single node (8 x A100 (40G each)) to 
multi node (2 node) connected over ROcE
(node 1:  8 x A100 (40G each) .    
node 2:   8 x A100 (80G each)).

For 100 epoch training of deep learning model using horovod docker image, (all things kept similar) 
1 node takes 22.3 minute 
2 node takes 24.4 minute. (using Mellanox support arguments) (also scaling hyperparameters based on world size)

Below I have attached single node and multi node timeline as well.

1) single node timeline.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/104454645/205209938-fb3a9f80-8032-40ec-b572-71aa60c647d1.png">

2) multi node timeline.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/104454645/205210038-618e9918-4b16-40d0-a2f2-88989b5c934a.png">

How can I find the the root cause for this slowness? 
Also, what is this empty space (grey space between operation)? seems like multi node has more of grey space between operations in timeline and much more scattered?

horovod command for multinode training:

horovodrun --verbose -np=16 -H=localhost1:8,localhost2:8 -p=8505 --start-timeout=20 --timeline-filename ./multinode_timeline.json --fusion-threshold-mb 256 --mpi-args="-x NCCL_DEBUG=INFO -x NCCL_IB_DISABLE=0 -x NCCL_IB_CUDA_SUPPORT=1 --map-by numa --mca btl=openib,self,vader btl_openib_cpc_include=rdmacm" python3 script.py

Also even nccl installed, why libnccl-net.so not found? can it have impact on total training time?

"NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation" 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/104454645/205359898-bcc6ef14-ed3f-4af9-8bc8-5d51ec866dc5.png">

Thank you

**Comment by ArtificialZeng** [comment]
sovled？
