### ISSUE TITLE
CI: Docker image build for horovod-nvtabular runs into time out

### ISSUE THREAD

**Issue by maxhgerlach** [horovod/horovod#3797]
Ex.: https://github.com/horovod/horovod/actions/runs/3656223581/jobs/6181962659

```
#12 151.5 Solving environment: ...working... 
Error: The action has timed out.
```

If Docker time stamps in that log are to be believed, then it seems to hang there at the Conda environment stage for > 50 minutes.

**Comment by EnricoMi** [comment]
@leewyang do you mind taking a look? This reproduces locally. Miniconda is not able to install, `solving environment` takes forever.
