### ISSUE TITLE
some doubt about horovod timeline

### ISSUE THREAD

**Issue by yogurfrul** [horovod/horovod#380]
1. When I run horovod with tensorflow timeline ,the horovod timeline get wrong time.
I just add some code to examples/tensorflow_mnist.py
```
options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
        run_metadata = tf.RunMetadata()

 mon_sess.run(train_op, feed_dict={image: image_, label: label_},
                     options=options,
                     run_metadata=run_metadata)
            fetched_timeline = timeline.Timeline(run_metadata.step_stats)
            chrome_trace = fetched_timeline.generate_chrome_trace_format()
            with open('timeline_02_step_%d.json' % i, 'w') as f:
                f.write(chrome_trace)
```
my whole step duration are about 150ms ,while the negotiation duration can be about 1000ms

2.when I remove the tensorflow timeline code ,I get the horovod timeline seems right,
I found that there is about 10ms from the negotiation end to the allreduce start ,the duration are longer than then negotiation and allreduce operation actually  happens.
what happened in the duration,why not allreduce when  all the rank read immediately.

**Comment by yogurfrul** [comment]
Name▿ | Wall Duration▿ | Self time▿ | Average Wall Duration▿ | Occurrences▿
-- | -- | -- | -- | --
NEGOTIATE_ALLREDUCE | 131,788.770 ms | 131,788.770 ms | 1,317.888 ms | 100

**Comment by alsrgv** [comment]
@yogurfrul, sorry for the late reply.  Did you resolve your problem?  If not, do you mind sharing the timeline so we could take a look?
