### ISSUE TITLE
Which version of FlatBuffers is used to generate head file?

### ISSUE THREAD

**Issue by GHGmc2** [horovod/horovod#3812]
I built FlatBuffers from source with the commit in third_party: https://github.com/google/flatbuffers/tree/a9a295fecf3fbd5a4f571f53b01f63202a3e2113
```bash
cmake -G "Unix Makefiles"
make
make install
```

And then generated the head file from `fbs`:
```bash
flatc -c -o ~/ ./horovod/common/wire/message.fbs
```

And I found the the generated `message_generated.h` file is not the same as the one in Horovod repo: https://github.com/horovod/horovod/blob/master/horovod/common/wire/message_generated.h

May I know which version of FlatBuffers is used to get the head file in Horovod repo?

**Comment by maxhgerlach** [comment]
What's the diff between your generated file and the version that's checked in?

I believe I've used flatbuffers 2.0 (that's the commit you posted https://github.com/google/flatbuffers/tree/a9a295fecf3fbd5a4f571f53b01f63202a3e2113) when I last updated the file, but the copyright header that's at the top of it is maintained manually.

Probably it would be good to have some build process with clearly versioned dependencies generate `message_generated.h`...

**Comment by GHGmc2** [comment]
The file I got manually: 
[message_generated.h.manual.txt](https://github.com/horovod/horovod/files/10407608/message_generated.h.manual.txt)

Please help to confirm.

**Comment by maxhgerlach** [comment]
Interesting! So the first part of the diff concerns the copyright / license comment header that we maintain manually. 

The second part showcases an actual discrepancy. But I don't think it's related to the version of the FlatBuffers compiler. I think it's more likely that the enum was renamed from `PROD` to `PRODUCT` in `message.fbs`, but then accidentally the header file wasn't regenerated.

As all tests pass, this doesn't appear to cause any actual problems now. But for the sake of consistency we should probably update `message_generated.h` so the enum names match those in: https://github.com/horovod/horovod/blob/bfe96f8cc239be5fbb75836db8682e040021d858/horovod/common/message.h#L43-L50

**Comment by GHGmc2** [comment]
@maxhgerlach Thanks.

Can you help to confirm the other file: https://github.com/horovod/horovod/blob/master/horovod/tensorflow/custom_call_config.fbs ? I got more discrepancies with this file.

**Comment by maxhgerlach** [comment]
> Can you help to confirm the other file: https://github.com/horovod/horovod/blob/master/horovod/tensorflow/custom_call_config.fbs ? I got more discrepancies with this file.

```
# ...
 struct TensorShape;
+struct TensorShapeBuilder;
 
 struct CustomCallConfig;
+struct CustomCallConfigBuilder;
 
 struct TensorShape FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
+  typedef TensorShapeBuilder Builder;
# ...
 ```

This one seems to produce more structural differences so in this case there probably was a version difference. Note that it may be necessary to align with the FlatBuffers used internally in TensorFlow (https://github.com/horovod/horovod/issues/2429, but I do not fully understand the ramifications right now).

**Comment by GHGmc2** [comment]
@maxhgerlach Thanks for the fixing.

@trentlo Do you know the where the gap lies? I noticed that you brought [it](https://github.com/horovod/horovod/blob/master/horovod/tensorflow/custom_call_config.fbs) in PR on XLA.

**Comment by trentlo** [comment]
I don't recall the version. But I used the Flatbuffers back then under Horovod/third_party/flatbuffers/.

If I judge by the date, it may be ~1.10.

**Comment by trentlo** [comment]
If all the regression tests pass, it's fine to continue using whatever is under Horovod/third_party/flatbuffers/.

**Comment by GHGmc2** [comment]
@trentlo thanks for the info.
