### ISSUE TITLE
Problem running benchmarks

### ISSUE THREAD

**Issue by adavanisanti** [horovod/horovod#382]
I am trying to run benchmarks based on documentation [here](https://github.com/uber/horovod/blob/8318a898a2f03fb22664ca8f5353361974f8a693/docs/benchmarks.md). In specific, I ran the following:
```
$mpirun -np 16 \
    -H server1:4,server2:4,server3:4,server4:4 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    \
    python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py \
        --model resnet101 \
        --batch_size 64 \
        --variable_update horovod
```
I get the following error:
```
 import benchmark_cnn
  File "/home/ubuntu/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 53, in <module>
    import variable_mgr
  File "/home/ubuntu/benchmarks/scripts/tf_cnn_benchmarks/variable_mgr.py", line 25, in <module>
    import allreduce
  File "/home/ubuntu/benchmarks/scripts/tf_cnn_benchmarks/allreduce.py", line 28, in <module>
    from tensorflow.python.ops import collective_ops
ImportError: cannot import name collective_ops
```
I see the same error with `master` and `cnn_tf_v1.8_compatible` branches of benchmarks.

Could anyone help resolve this?

**Comment by tgaddair** [comment]
Hey @adavanisanti, the second error is usually indicative of lack of GPU support in your TensorFlow installation.  Did you install the `tensorflow` package or `tensorflow-gpu`?
