### ISSUE TITLE
No Controller and Tensor Operations in --check-build command output

### ISSUE THREAD

**Issue by PurvangL** [horovod/horovod#3821]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) : Tensorflow
2. Framework version: 2.9
3. Horovod version: latest
4. MPI version: mpi4py=3.1.4 
5. CUDA version: 11.6
6. NCCL version: 2.16.2-1+cuda12.0 
7. Python version: 3.8.10
8. Spark / PySpark version:
9. Ray version:
10. OS and version: Ubuntu 20
11. GCC version:
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? na
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? no
4. Did you check if you question is answered in the [troubleshooting guide] yes (https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod[tensorflow]

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/104454645/213785064-13e3bf60-5c5d-43fc-a9ff-2c666ba87320.png">

No controller is present as well as tensor operations library.

**Comment by zxysbsbzxy** [comment]
I have the same problem with you when installing horovod yesterday and I haven't solved yet. It seemed environment variants does not make effect.

**Comment by zxysbsbzxy** [comment]
> I have the same problem with you when installing horovod yesterday and I haven't solved yet. It seemed environment variants does not make effect.

whoops.I updated tensor flow to the latest version just now and it can output correct check-build info now. Maybe you can have a try.

**Comment by PurvangL** [comment]
Thank you for your answer. I tried uninstalling both tensorflow and horovod and updated to latest version, still no change in check-build output.

Interesting part as shown in picture above is, even there i no installation of pytorch on system, and I use
```
HOROVOD_GPU_OPERATIONS=NCCL HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod
```
still it shows it's built with pytorch.

**Comment by PurvangL** [comment]
closing as it is fixed.
uninstalled tensorflow and horovod 
reinstall tensorflow
installed horovod with following

```
pip install --no-cache horovod[tensorflow,keras]
```
worked for me.
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/104454645/214676742-aac210f7-6102-4eec-bb64-932ca061cefa.png">
