### ISSUE TITLE
I can run the script on one machine, but error occurs on two machines.

### ISSUE THREAD

**Issue by caiduoduo12138** [horovod/horovod#3844]
**Environment:**
1. Framework:  PyTorch
2. Framework version:1.12
3. Horovod version:0.22.0
4. MPI version:4.0.7
5. CUDA version:11.6
6. NCCL version:2.11.4
7. Python version:3.8
8. Spark / PySpark version:
9. Ray version:
10. OS and version:ubuntu20.04
11. GCC version:9.4.0
12. CMake version:3.16.3

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? it is not hang
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? 
it is not docker
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? yes

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.
The script is successfully running on the single macniche.(horovodrun -np 8 -H localhost:8  python3 pytorch_mnist.py)
However, when I run the script(horovodrun -np 2 -H 10.250.2.12:1,10.250.2.8:1 python3 pytorch_mnist.py), error occurs. The log is before(NCCL_DEBUG=info)
The ssh can connect the other machine(eg: ssh 10.250.2.12 or ssh 10.250.2.8)

[log-debug.txt](https://github.com/horovod/horovod/files/10720682/log-debug.txt)

**Comment by maxhgerlach** [comment]
Hi @caiduoduo12138!

> 3. Horovod version:0.22.0

That's quite old. Would you mind trying the latest release 0.27?

> 6. NCCL version:2.11.4

This doesn't match your log. There it says: `[1,0]<stdout>:NCCL version 2.12.12+cuda11.6` Where does that message come from? Apparently only rank 0 prints it.

I'd suggest to double check your environment. Rebuild Horovod with the version of NCCL that you want to use. Make sure the environment is exactly the same on both nodes.

**Comment by caiduoduo12138** [comment]
Thanks
