### ISSUE TITLE
Horovod with MPI and NCCL

### ISSUE THREAD

**Issue by yjiangling** [horovod/horovod#3857]
If I have installed NCCL and MPI, and want to install horovod from source code. But I'm confused about some parameters.

**HOROVOD_GPU_OPERATIONS**，**HOROVOD_GPU_ALLREDUCE** and **HOROVOD_GPU_BROADCAST**

How to set this three parameters ? Which use NCCL and which use MPI ? Anyone can help to answer this question? Thanks a lot in advance!!!

**Comment by maxhgerlach** [comment]
`HOROVOD_GPU_OPERATIONS` supersedes the other two parameters. If you install Horovod with `HOROVOD_GPU_OPERATIONS=NCCL`, all collective GPU ops (including Allreduce and Broadacst) will use NCCL. That's generally what you want to do unless you are in a special situation, where you explicitly need to use GPU-based MPI on your compute cluster.

If you have MPI, Horovod can still use it for CPU-based communication, no matter how `HOROVOD_GPU_OPERATIONS` is configured.

**Comment by yjiangling** [comment]
> `HOROVOD_GPU_OPERATIONS` supersedes the other two parameters. If you install Horovod with `HOROVOD_GPU_OPERATIONS=NCCL`, all collective GPU ops (including Allreduce and Broadacst) will use NCCL. That's generally what you want to do unless you are in a special situation, where you explicitly need to use GPU-based MPI on your compute cluster.
> 
> If you have MPI, Horovod can still use it for CPU-based communication, no matter how `HOROVOD_GPU_OPERATIONS` is configured.

Oh, I see, thanks a lot for the detail reply, thank you very much.
