### ISSUE TITLE
Somehow NCCLAllreduce is Replaced by GlooAllreduce in My Training?

### ISSUE THREAD

**Issue by hercule24** [horovod/horovod#3879]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.4.2.3
3. Horovod version: 0.26.1.5
4. MPI version:
5. CUDA version:
6. NCCL version: 
7. Python version: 
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

**Checklist:** 
1. Did you search issues to find if somebody asked this question before? Y
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)? N/A
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Hi Hovorod team, I am new to Horovod, and I read the codebase but still couldn't figure out why.
In my first few iterations of training, NCCLAllreduce was used as seen in the horovod timeline, 
![image](https://user-images.githubusercontent.com/3295695/229322084-ea54cccc-9151-4c96-b1b9-36c3fa606773.png)

However, after I made some optimization changes to my model, it was replaced by GlooAllreduce.
![image](https://user-images.githubusercontent.com/3295695/229322343-e0c9caf8-6094-4412-9add-55d8678ea103.png)

According to this issue: https://github.com/horovod/horovod/issues/1741, NCCL allreduce should be more performant than gloo allreduce, that's why I would like to use the former.

There was no change to my horovod container image, so it should be compiled with the same `HAVE_NCCL` directive.

I discovered that operations.cc, both allreduces are pushed into the `OperationManager` because we set both `HAVE_GLOO` and `HAVE_NCCL`, however why do we need two different allreduce operations if we already have GPUs? 

It looks like that the only way `NCCLAllreduce` is not enabled is that the tensor's device is specified as CPU: https://github.com/horovod/horovod/blob/v0.26.1/horovod/common/ops/gpu_operations.cc#L154, however when we use `DistributedOptimizer`, we didn't set `device_sparse or` `device_dense`, so GPU should be used by default.

This is very confusing to me, and it's blocking me from making progress, it will be super helpful if you could take a look. Thanks!

**Comment by maxhgerlach** [comment]
> after I made some optimization changes to my model

Probably some TF device placements of your ops or tensors accidentally changed from GPU to CPU in your code. I'd suggest to review that, maybe at an explicit `tf.device`.

**Comment by hercule24** [comment]
@maxhgerlach , Thank you for taking a look! This somehow happens to all my tensors, there may be a more fundamental issue that I am not aware of.

**Comment by hercule24** [comment]
@maxhgerlach , because we use multiple nodes, each has multiple GPUs, should I use: `hvd.rank()` to determine the rank, then do something like?

```
rank = hvd.rank()
with tf.device(f"/device:GPU:{rank}"):
  ...
```
or if using `DistributedOptimizer`:
```
rank = hvd.rank()
opt = hvd.DistributedOptimizer(opt, device_dense=f"/device:GPU:{rank}", device_sparse=f"/device:GPU:{rank}")
```

**Comment by maxhgerlach** [comment]
It should be `hvd.local_rank()`, not the global `hvd.rank()`. 

I'd configure TensorFlow similarly to the examples (https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py#L32). Then just `"gpu"` should suffice as a device string.

**Comment by hercule24** [comment]
It looks like we are already doing this.

A n00b question, why is `local_rank` used but not `rank`? I thought we have multiple nodes, so we should figure out the global rank across all GPUs for each GPU?
