### ISSUE TITLE
question about intel-openmp-2018.0.3 from pytorch

### ISSUE THREAD

**Issue by bapriddy** [horovod/horovod#389]
What does pytorch do with intel-openmp-2018.0.3?  Secondly, I noticed the install also downloads a cudatoolkit-8.0-3.  So how does this cudatoolkit interacte with global system installs?  If I

`export PKG_CONFIG_PATH=/global_path_to/nvidia/cudatoolkit8.0/8.0.61_2.3.13_g32c34f9-2.1/lib64/pkgconfig:$PKG_CONFIG_PATH`

will this cause a problem.

**Comment by alsrgv** [comment]
@bapriddy, could you provide more context about your question - are you installing PyTorch via Conda?  What steps are you following?

**Comment by alsrgv** [comment]
@bapriddy, gotcha.  `intel-openmp` is the [library](https://software.intel.com/en-us/articles/getting-started-with-openmp) for multithreaded computations - PyTorch can use it for computing of NN layers on CPU.  OpenMP is not related to MPI.

**Comment by bapriddy** [comment]
@alsrgv Okay.  Thanks yet again.  So ~intel-openMP~  probably ties in with mkf, mkl-fft and/or other processes that run on cpu threads.  Nothing to do with the gpu (i assume).  Sorry, I'm coming at this from pure math and don't always have the terminology correct. I think someone mentioned openMP might be needed for compiling.  So if I have a node with two cpu sockets this might be useful for openMP provided I know how to use it.

I'm running the facebook-Soumith resnet50 code on a 4 P100 IBM node and its REALLY slow compared to your resnet50 on 4 single P100 nodes.  Same batch-size.  It seems they didn't tweak it very much or I'm doing something wrong.

**Comment by alsrgv** [comment]
@bapriddy, it does - I just ran Horovod on Power 9 boxes and got great performance.  I believe I'd get similar performance on Power 8.

Did you install NCCL on your ppc64el nodes?

**Comment by bapriddy** [comment]
@alsrgv Yes, nccl is installed but I can't install pytorch or horovod because the arch isn't "officially" supported.  Very interested in how you got it running.   BTW, nccl loads via a module.  You probably have more flexibility with the installation.

**Comment by alsrgv** [comment]
@bapriddy, I did not try PyTorch on IBM - you may have to [install from source](https://github.com/pytorch/pytorch#from-source).

**Comment by bapriddy** [comment]
@alsrgv Yes, I'm working on it now.  Having trouble with the MPI portion.  Is it possible to just run with nccl 1.0 on a 4 P100 gpu node which I'm assuming has 2 cpu-sockets /node?  Eventually I was planning to install nccl 2.0 and get mpi working but is it really using mpi on the single node? I should probably make a diagram of where thing get computed so I can make better sense of this.  

Facebook said they were not planning to support the ppc64el arch.  I'm sure there is a way to get it running from ./local on the cluster.

**Comment by alsrgv** [comment]
@bapriddy, unfortunately, NCCL 1.x is deprecated and Horovod does not support it.  NCCL 2 now has a public release for Power PC that you can use, as long as your nodes run CUDA 9.2.  And yes, MPI is necessary for a single node as well.

**Comment by ghltshubh** [comment]
@alsrgv can you point me to the public release of nccl 2 for power PC

**Comment by alsrgv** [comment]
@ghltshubh, I just found NCCL v2.3.4 available in https://developer.nvidia.com/nccl/nccl-legacy-downloads for POWER. I will ask about the latest version for POWER.
