### ISSUE TITLE
how to build hovovod with some tensorflow versions ?

### ISSUE THREAD

**Issue by south-ocean** [horovod/horovod#3901]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version:  2.11
3. Horovod version:  0.26.1
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version: 3.8 
8. Spark / PySpark version:
9. Ray version:
10. OS and version: centos
11. GCC version:  9.3
12. CMake version:3.20

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

I change the source code with tensorflow2.9 and tensorflow2.11, so i must compile twice to generate two horovod whl package for tensorflow2.9 and  tensorflow2.11? Does any solution can let me  compile once  to generate one whl package, and it can be used for tensorflow2.9 and tensorflow2.11?
![1682302568235](https://user-images.githubusercontent.com/30514703/233884799-5a70a7d2-7264-4ec2-91e8-4eabcc5d3057.png)

**Comment by maxhgerlach** [comment]
> Does any solution can let me compile once to generate one whl package, and it can be used for tensorflow2.9 and tensorflow2.11?

No, you will have to build separate wheels for each version of TensorFlow. Horovod's C++ core depends on TF implementation details.
