### ISSUE TITLE
Horovod distributed optimizer is not working.

### ISSUE THREAD

**Issue by Shup-46** [horovod/horovod#3903]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 2.12.0
3. Horovod version: 0.27.0

**Bug report:**
Horovod distributed optimizer is not working even after trying  SGD, Optimizer, etc. nothing is working.
![image](https://user-images.githubusercontent.com/102753110/234783409-b354b07b-451f-4d4c-9c04-2b890df63187.png)

**Comment by maxhgerlach** [comment]
See https://github.com/horovod/horovod/issues/3726

It will be fixed in the upcoming release. In the mean time Horovod master should work.
