### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_30'

### ISSUE THREAD

**Issue by vish119** [horovod/horovod#3922]
I'm seeing following error while installing horovod on system with CUDA 11.2 installed. 

```
Make Error at horovod_cuda_kernels_generated_cuda_kernels.cu.o.cmake:206 (message):
  Error generating
  /tmp/tmpia79t69p/horovod/build/temp.linux-x86_64-3.7/horovod/common/ops/cuda/CMakeFiles/horovod_cuda_kernels.dir//./horovod_cuda_kernels_generated_cuda_kernels.cu.o


nvcc fatal   : Unsupported gpu architecture 'compute_30'
gmake[2]: *** [horovod/common/ops/cuda/CMakeFiles/horovod_cuda_kernels.dir/./horovod_cuda_kernels_generated_cuda_kernels.cu.o] Error 1
gmake[2]: Leaving directory `/storage/tmp/tmpia79t69p/horovod/build/temp.linux-x86_64-3.7'
CMake Error at compatible_horovod_cuda_kernels_generated_cuda_kernels.cu.o.cmake:206 (message):
  Error generating
  /tmp/tmpia79t69p/horovod/build/temp.linux-x86_64-3.7/horovod/common/ops/cuda/CMakeFiles/compatible_horovod_cuda_kernels.dir//./compatible_horovod_cuda_kernels_generated_cuda_kernels.cu.o


gmake[1]: *** [horovod/common/ops/cuda/CMakeFiles/horovod_cuda_kernels.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at horovod_cuda_kernels_generated_cuda_kernels.cu.o.cmake:206 (message):
  Error generating
  /tmp/tmpia79t69p/horovod/build/temp.linux-x86_64-3.7/horovod/common/ops/cuda/CMakeFiles/horovod_cuda_kernels.dir//./horovod_cuda_kernels_generated_cuda_kernels.cu.o


gmake[2]: *** [horovod/common/ops/cuda/CMakeFiles/compatible_horovod_cuda_kernels.dir/./compatible_horovod_cuda_kernels_generated_cuda_kernels.cu.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [horovod/common/ops/cuda/CMakeFiles/horovod_cuda_kernels.dir/./horovod_cuda_kernels_generated_cuda_kernels.cu.o] Error 1
gmake[2]: Leaving directory `/storage/tmp/tmpia79t69p/horovod/build/temp.linux-x86_64-3.7'
gmake[1]: *** [horovod/common/ops/cuda/CMakeFiles/compatible_horovod_cuda_kernels.dir/all] Error 2
gmake[1]: Leaving directory `/storage/tmp/tmpia79t69p/horovod/build/temp.linux-x86_64-3.7'
gmake: *** [all] Error 2
```

**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) : PyTorch
2. Framework version: 
3. Horovod version:  We are building using  horovod repository 
4. MPI version: 4.1.1 
5. CUDA version: 11.2 
6. NCCL version: 2.8.4
7. Python version:  ython 2.7.18 
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version: 7.3.1
12. CMake version:  3.22.1

**Comment by maxhgerlach** [comment]
The issue template had some questions about your build environment. That's useful information to help you out here. Full build logs from `pip install -v` would also be good.

Have you tried `HOROVOD_BUILD_CUDA_CC_LIST`? https://horovod.readthedocs.io/en/stable/install_include.html#environment-variables Don't know why it would be necessary, though.

**Comment by vish119** [comment]
I ran get_nvcc_flags() on my system as an independent script and it  returns this set of flag:

`['--std=c++11', '-O3', '-Xcompiler', '-fPIC', '-gencode', 'arch=compute_35,code=sm_35', '-gencode', 'arch=compute_37,code=sm_37', '-gencode', 'arch=compute_50,code=sm_50', '-gencode', 'arch=compute_52,code=sm_52', '-gencode', 'arch=compute_53,code=sm_53', '-gencode', 'arch=compute_60,code=sm_60', '-gencode', 'arch=compute_61,code=sm_61', '-gencode', 'arch=compute_62,code=sm_62', '-gencode', 'arch=compute_70,code=sm_70', '-gencode', 'arch=compute_72,code=sm_72', '-gencode', 'arch=compute_75,code=sm_75', '-gencode', 'arch=compute_80,code=sm_80', '-gencode', 'arch=compute_80,code=compute_80']`

But when i run python setup.py install it ends up generating different set of flag:


`arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_53,code=sm_53 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_62,code=sm_62 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_72,code=sm_72 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_75,code=compute_75` 

And yes I was able to install it on CUDA 10.0 but I want to install it on CUDA 11.0

**Comment by maxhgerlach** [comment]
I'd check which copy of nvcc is run in either case. There's a mismatch when run through CMake.
