### ISSUE TITLE
fail to build horovod 0.28.0 from the source with gcc 12 due to gloo issue

### ISSUE THREAD

**Issue by hubutui** [horovod/horovod#3923]
**Environment:**
1. Framework: tensorflow 2.12.0, pytorch 2.0.1
2. Framework version:
3. Horovod version: 0.28.0
4. MPI version:
5. CUDA version:  12.1.1
6. NCCL version: 2.17.1
7. Python version: 3.11
8. Spark / PySpark version:
9. Ray version:
10. OS and version: ArchLinux
11. GCC version: 12.3.0
12. CMake version: 3.26.3

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
```bash
git clone https://github.com/horovod/horovod.git
  cd horovod
  git submodule update --init --recursive
# modify these environment variable as you need, see also https://github.com/horovod/horovod/blob/master/docs/install.rst
  export HOROVOD_CUDA_HOME=/opt/cuda
  export HOROVOD_CPU_OPERATIONS=GLOO
  export HOROVOD_GPU=CUDA
  export HOROVOD_GPU_ALLREDUCE=NCCL
  export HOROVOD_GPU_BROADCAST=NCCL
  export HOROVOD_WITH_GLOO=1
  export HOROVOD_WITH_MPI=1
  export HOROVOD_WITHOUT_MXNET=0
  export HOROVOD_WITH_PYTORCH=1
  export HOROVOD_WITH_TENSORFLOW=1
  export HOROVOD_BUILD_CUDA_CC_LIST="60,61,62,70,72,75,80,86,89,90"
  export CC=gcc-12
  export CXX=g++-12
python setup.py build
```
error logs:
```text
/build/python-horovod/src/horovod-0.28.0/third_party/gloo/gloo/mpi/context.cc:43:3: note: in expansion of macro ‘GLOO_ENFORCE_EQ’
   43 |   GLOO_ENFORCE_EQ(rv, MPI_SUCCESS);
      |   ^~~~~~~~~~~~~~~
make[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo.dir/build.make:300: third_party/gloo/gloo/CMakeFiles/gloo.dir/common/linux.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/build/python-horovod/src/horovod-0.28.0/third_party/gloo/gloo/transport/tcp/device.cc: In function ‘gloo::transport::tcp::attr gloo::transport::tcp::CreateDeviceAttr(const attr&)’:
/build/python-horovod/src/horovod-0.28.0/third_party/gloo/gloo/transport/tcp/device.cc:151:39: error: aggregate ‘std::array<char, 64> hostname’ has incomplete type and cannot be defined
  151 |       std::array<char, HOST_NAME_MAX> hostname;
      |                                       ^~~~~~~~
make[2]: *** [third_party/gloo/gloo/CMakeFiles/gloo.dir/build.make:524: third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o] Error 1
make[2]: Leaving directory '/build/python-horovod/src/horovod-0.28.0/build/temp.linux-x86_64-cpython-311/RelWithDebInfo'
make[1]: *** [CMakeFiles/Makefile2:524: third_party/compatible17_gloo/gloo/CMakeFiles/compatible17_gloo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
According to gloo upstream issue https://github.com/facebookincubator/gloo/issues/332, this is fixed by https://github.com/facebookincubator/gloo/commit/4a5e339b764261d20fc409071dc7a8b8989aa195. We only need to update submodule `third_party/gloo` to at least this commit. I could confirm that this works by:
```bash
cd third_party/gloo
git pull https://github.com/facebookincubator/gloo.git
```
I update the submodule, and then I could build it.

**Comment by Naozumi520** [comment]
Hi, I'm currently encounting the same issue. Can you please tell me as a user how can I install horovod without issues?

**Comment by hubutui** [comment]
@Naozumi520 You have 2 options:
1. build and install horovod with older compiler, gcc <= 10 might work.
2. manually update submodule gloo to the latest commit of upstream, and then build horovod from the source with gcc 12.
```bash
git clone https://github.com/horovod/horovod.git
  cd horovod
  git submodule update --init --recursive
# modify these environment variable as you need, see also https://github.com/horovod/horovod/blob/master/docs/install.rst
  export HOROVOD_CUDA_HOME=/opt/cuda
  export HOROVOD_CPU_OPERATIONS=GLOO
  export HOROVOD_GPU=CUDA
  export HOROVOD_GPU_ALLREDUCE=NCCL
  export HOROVOD_GPU_BROADCAST=NCCL
  export HOROVOD_WITH_GLOO=1
  export HOROVOD_WITH_MPI=1
  export HOROVOD_WITHOUT_MXNET=0
  export HOROVOD_WITH_PYTORCH=1
  export HOROVOD_WITH_TENSORFLOW=1
  export HOROVOD_BUILD_CUDA_CC_LIST="60,61,62,70,72,75,80,86,89,90"
  export CC=gcc-12
  export CXX=g++-12
cd third_party/gloo
git pull https://github.com/facebookincubator/gloo.git
cd -
python setup.py build
```
hope this help. see also this [PKGBUILD](https://github.com/archlinuxcn/repo/blob/f65ac96c168e49508da4410e423814d8a1b27bd9/archlinuxcn/python-horovod/PKGBUILD) which I used to build horovod 0.28.0 with gcc 12 from the source for ArchLinux.

**Comment by maxhgerlach** [comment]
Thanks for the report!
