### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by loveafy** [horovod/horovod#3930]
**Environment:**
1. Framework: pytoch
2. Framework version:1.12.1+cu113
3. Horovod version:
4. MPI version:
5. CUDA version:11.7
6. NCCL version:
7. Python version:3.8.10
8. Spark / PySpark version:
9. Ray version:
10. OS and version:Linux gxnzx9517 5.15.0-71-generic #78~20.04.1-Ubuntu SMP Wed Apr 19 11:26:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
11. GCC version:9.4.0
12. CMake version:3.16.3

**Checklist:**
1. Did you search issues to find if somebody asked this question before?  yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.
I run my process in single computor have the problem:
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
the run commond is horovodrun -np 2 -H localhost:2 -p 12345 python -m torch.distributed.launch --nproc_per_node 2 train.py
But i run the officia example pytorch_mnist.py don't have that problem.

**Comment by romerojosh** [comment]
You should not use `torch.distributed.launch` with Horovod as that is the utility to launch processes for PyTorch's native distributed backend. In your command above, you are launching two processes with `horovodrun` that are each trying to launch two additional processes with `torch.distributed.launch` which is probably not what you want. If you remove `-m torch.distributed.launch --nproc_per_node 2` from your command, does it work?

**Comment by loveafy** [comment]
Thanks, it doesn’t have than error.
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: romerojosh ***@***.***>
发送时间: Wednesday, May 24, 2023 4:45:52 AM
收件人: horovod/horovod ***@***.***>
抄送: loveafy ***@***.***>; Author ***@***.***>
主题: Re: [horovod/horovod] Address already in use (Issue #3930)


You should not use torch.distributed.launch with Horovod as that is the utility to launch processes for PyTorch's native distributed backend. In your command above, you are launching two processes with horovodrun that are each trying to launch two additional processes with torch.distributed.launch which is probably not what you want. If you remove -m torch.distributed.launch --nproc_per_node 2 from your command, does it work?

―
