### ISSUE TITLE
Missing `-iface` argument in mpirun command generated by Horovod runner

### ISSUE THREAD

**Issue by alumik** [horovod/horovod#3933]
**Environment:**
1. Framework: TensorFlow, PyTorch
2. Framework version: 2.12.0, 2.0.1
3. Horovod version: 0.28.0
4. MPI version: MPICH (HYDRA) 4.1.1
5. CUDA version: 11.8
6. NCCL version: 2.16.5
7. Python version: 3.11.3
8. Spark / PySpark version: N/A
9. Ray version: N/A
10. OS and version: Ubuntu 22.04
11. GCC version: 11.3.0
12. CMake version: 3.26.3

**Bug report:**

**Issue Description:**

The current implementation of the Horovod runner translates the command

```
horovodrun -n 3 --network-interface enp94s0 -H server2:3
```

into an mpirun command. However, it seems that the generated mpirun command

```
mpirun -l -np 3 -ppn 3 -hosts server2 -bind-to none -map-by slot -genv NCCL_SOCKET_IFNAME=enp94s0
```

is missing the `-iface enp94s0` argument. This omission can cause errors in setups with multiple servers.

**Steps to Reproduce:**

- Install MPICH and Horovod.
- Run the command `horovodrun -n 3 --network-interface enp94s0 -H server2:3 echo hello`.

**Error Message:**

```
[proxy:0:0@server1] HYDU_sock_connect (lib/utils/sock.c:110): unable to get host address for server1
[proxy:0:0@server1] main (proxy/pmip.c:105): unable to connect to server server2 at port 39647 (check for firewalls!)
[mpiexec@server2] ui_cmd_cb (mpiexec/pmiserv_pmci.c:51): Launch proxy failed.
[mpiexec@server2] HYDT_dmxu_poll_wait_for_event (lib/tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@server2] HYD_pmci_wait_for_completion (mpiexec/pmiserv_pmci.c:181): error waiting for event
[mpiexec@server2] main (mpiexec/mpiexec.c:247): process manager error waiting for completion
```

**Expected Fix:**

The mpirun command generated by the Horovod runner should include the `-iface` argument to ensure proper network interface binding and avoid the mentioned error.

**References:**

Possible culprit code snippet:

https://github.com/horovod/horovod/blob/b93a87a6c79233d85113b8a42f5bd513d6c0de91/horovod/runner/mpi_run.py#L169-L170

**Workaround:**

To work around this issue, I can manually add the `--mpi-args="-iface enp94s0"` flag to the horovodrun command. This flag allows me to pass custom arguments directly to the underlying mpirun command. I am not sure if this is the intended way to work with MPICH.

**Comment by maxhgerlach** [comment]
Thank you for the report and the investigation!

Looks like a way to go may be to add a variation of
``` python
 tcp_intf_arg = '-mca btl_tcp_if_include {nics}'.format( 
     nics=','.join(nics)) if nics and not impi_or_mpich else '' 
```
for Intel MPI or MPICH. Like setting `tcp_intf_arg` to `f'-iface {nics[0]}'`. Not sure if multiple values for `-iface` are supported.

**Comment by maxhgerlach** [comment]
In this case I'd suggest to abort with an error if `nics` has more than one element and the user is running with `impi_or_mpich`.

**Comment by alumik** [comment]
OK, I have opend a [PR](https://github.com/horovod/horovod/pull/3946) to address this issue. Please review the proposed changes.
