### ISSUE TITLE
horovod slower than pytorch DDP

### ISSUE THREAD

**Issue by purvang3** [horovod/horovod#3938]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) : pytorch
2. Framework version: 2.0
3. Horovod version: 0.28
4. MPI version: 
5. CUDA version: 
6. NCCL version:
7. Python version:
8. Spark / PySpark version:
9. Ray version:
10. OS and version:
11. GCC version:
12. CMake version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**

I have two questions 
1) I am running [yolox_ddp](https://github.com/Megvii-BaseDetection/YOLOX) on 8 A100 gpus. Then I modified code to use horovod and also modified data loader accordingly as per [example](https://horovod.readthedocs.io/en/stable/pytorch.html). During my training, horovod result seems **5x slower** than pytorch DDP result. any reason why this much slower?

2) I am trying to run same code on habana gaudi2 using hccl collective ops. but installing horovod using pip doesn't have option to build with hccl. how can build horovod with hccl?

Thanks

**Comment by romerojosh** [comment]
1. Can you verify that you've built Horovod with NCCL support? 5x seems like more than I would expect here.
2. I am not familiar with HCCL nor any Habana Gaudi 2 support added to this repository. Looking at the `habana-horovod` PyPI project description (https://pypi.org/project/habana-horovod/), it sounds like support for this hardware platform is within a fork maintained by Habana. You may need to reach out to them directly for help with that.

**Comment by purvang3** [comment]
<img width="366" alt="image" src="https://github.com/horovod/horovod/assets/39809304/2eac75d6-6e3d-4bbb-8f1c-32bdc77b5a4f">

**Comment by romerojosh** [comment]
Can you share a comparison of the training iteration times you are getting with DDP vs. Horovod? Depending on the model size/latency, there might need to be adjustments to the Horovod cycle time to achieve good performance.

NVIDIA Nsight Systems is also very useful tool for these kinds of comparisons and can be used to better identify where the two implementations differ.
