### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by etoilestar** [horovod/horovod#3955]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.15.0
3. Horovod version:0.19.5
4. MPI version:4.0.0
5. CUDA version:10.0
6. Python version:3.6.8

**Bug report:**
When I was running the example at https://github.com/horovod/horovod/blob/master/examples/tensorflow/tensorflow_word2vec.py it raises me an Segmentation fault error

**Comment by etoilestar** [comment]
another problem is when I was running the example https://github.com/horovod/horovod/blob/master/examples/tensorflow/tensorflow_mnist.py, it will be freezed at "Saving checkpoints for 0 into ./checkpoints/model.ckpt."

**Comment by maxhgerlach** [comment]
Hi, your environment is pretty old unfortunately. I doubt anybody will be able to help you easily. Could you update to current Horovod and a recent version of TensorFlow and try there?
