### ISSUE TITLE
How to write tensorflow custom training loop with using horovod.

### ISSUE THREAD

**Issue by PurvangL** [horovod/horovod#3987]
Hi, is there any example which uses horovod and custom training loop in tensorflow and not using .fit function to train on multiple gpus?

**Comment by fuhailin** [comment]
@PurvangL Welcome to use https://github.com/deepray-AI/deepray , it supports custom training loop with horovod

**Comment by MrAta** [comment]
Please checkout the examples directory. One such example for tensorflow custom training loop can be found here:
https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_mnist.py

**Comment by PurvangL** [comment]
Thanks @MrAta .
