### ISSUE TITLE
which  Algorithm is used in horovod ? (AllRecude or Ring Allreduce? )

### ISSUE THREAD

**Issue by wu-yy** [horovod/horovod#399]
I have read a Paper which name is "Buttery Mixing: Accelerating Incremental-Update Algorithms on
Clusters". I think Buttery Mixing Algorithm is better than Ringreduce Algorithm.

But when I see the code of horovod "operations.cc",there is a coordinator Rank Zero, 

I can't understand which  Algorithm is used in horovod ? (AllRecude or Ring Allreduce )

**Comment by tgaddair** [comment]
Hey @wu-yy, Horovod is based on the Ring-Allreduce algorithm.  You can read more on the specifics [here](https://arxiv.org/pdf/1802.05799.pdf).

Thanks for sharing the paper on Butterfly Mixing, reading it now!

**Comment by wu-yy** [comment]
@tyvsmith  wow, thank you very much!
