### ISSUE TITLE
Horovod 0.28.1 incompatibility with PyTorch 2.1.0

### ISSUE THREAD

**Issue by rithwik-db** [horovod/horovod#3996]
**Environment:**
1. Framework: PyTorch
3. Framework version: 2.1.0
4. Horovod version: 0.28.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)? Yes
3. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)? Yes

**Bug report:**

I created the following Dockerfile to test out whether the latest Horovod version (0.28.1) is compatible with the latest PyTorch version (2.1.0):

```
# Use the official Python image as the base image
FROM python:3.10-slim-buster

# Update the system and install necessary libraries
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    curl \
    ca-certificates \
    libjpeg-dev \
    libpng-dev && \
    rm -rf /var/lib/apt/lists/*

# Install PyTorch
RUN pip install torch==2.1.0

# Install Horovod
RUN HOROVOD_WITH_PYTORCH=1 pip install horovod==0.28.1
```

And it returned various errors that I am unable to decipher. Here is the full build trace: [error.txt](https://github.com/horovod/horovod/files/13168927/error.txt)

**Comment by matbun** [comment]
> Hi there. I also encountered similiar issue. It seems there are some compatibility issues between torch and horovod. I have tried to use latest version torch (2.3.0 or 2.2.x or 2.1.x) but I got same error info like:
> 
> ```
>       subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebInfo', '--', '-j8', 'VERBOSE=1']' returned non-zero exit status 2.
> ```
> 
> A exeception is torch==2.0.1, I can install horovod with torch 2.0.1. Any suggestions ?

Same here!

**Comment by matbun** [comment]
I solved it by noticing the existing PR to fix it (https://github.com/horovod/horovod/pull/3998), and undertaking the following steps:

- Check that my GCC installation supports C++17 ([Reference](https://stackoverflow.com/a/65483397)):
  ```bash
  gcc -v --help 2> /dev/null | sed -n '/^ *-std=\([^<][^ ]\+\).*/ {s//\1/p}'
  ```
- Set [CMAKE_CXX_STANDARD](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html) env variable: `export CMAKE_CXX_STANDARD=17`

Working snipped (in a python virtual env):

```bash
pip install torch
env CMAKE_CXX_STANDARD=17 bash -c 'pip install horovod[pytorch]'
```

Tested with `torch==2.3.0`

**Comment by matbun** [comment]
Issue persists as #3998 is still unmerged. However, as a temporary quick fix, you can run:

```bash
pip install --no-cache-dir git+https://github.com/thomas-bouvier/horovod.git@compile-cpp17
```
