### ISSUE TITLE
Error while loading shared libraries: libopen-rte.so.40

### ISSUE THREAD

**Issue by yangJirui** [horovod/horovod#400]
hello, 
I can run the distributed tensorflow with 4 GPU in one node. But it does not work when i run with 8 GPU in two nodes(each have 4GPUs). And each node can communicate with another node with ssh( without password). 
The erro information reveals that "error while loading shared libraries: libopen-rte.so.40: cannot open shared object file: No such file or directory". 
But the LD_LIBRARY_PATH has already include "usr/local/lib", and the "libopen-rte.so.40"　does exist in the 'usr/local/lib'.
My LD_LIBRARY_PATH shows below:
`
echo $LD_LIBRARY_PATH
 /usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
`

Files in "/usr/local/lib" are following:
![files](https://user-images.githubusercontent.com/18682747/43130554-7f2fc6de-8f69-11e8-8076-842c7cdb0ec7.png)

+++++++++++++++++++++++++++++++++++
The shell i used to run is : 
`
mpirun --allow-run-as-root -np 8 \
       -H localhost:4,10.34.0.81:4 \
       -bind-to none -map-by slot \
       -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
       -mca plm_rsh_args "-p 10001 -v"  \
       python test.py
`

And the Error message are:

OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016^M
debug1: Reading configuration data /etc/ssh/ssh_config^M
debug1: /etc/ssh/ssh_config line 19: Applying options for *^M
debug1: Connecting to 10.34.0.81 [10.34.0.81] port 10001.^M
debug1: Connection established.^M
debug1: permanently_set_uid: 0/0^M
debug1: identity file /root/.ssh/id_rsa type 1^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /root/.ssh/id_rsa-cert type -1^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /root/.ssh/id_dsa type -1^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /root/.ssh/id_dsa-cert type -1^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /root/.ssh/id_ecdsa type -1^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /root/.ssh/id_ecdsa-cert type -1^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /root/.ssh/id_ed25519 type -1^M
debug1: key_load_public: No such file or directory^M
debug1: identity file /root/.ssh/id_ed25519-cert type -1^M
debug1: Enabling compatibility mode for protocol 2.0^M
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4^M
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.4^M
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4 pat OpenSSH* compat 0x04000000^M
debug1: Authenticating to 10.34.0.81:10001 as 'root'^M
debug1: SSH2_MSG_KEXINIT sent^M
debug1: SSH2_MSG_KEXINIT received^M
debug1: kex: algorithm: curve25519-sha256@libssh.org^M
debug1: kex: host key algorithm: ecdsa-sha2-nistp256^M
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none^M
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none^M
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY^M
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:CDkXPYjacQMxlP/T0ZS8quoFM9cjhVYMV3lQVocnSp8^M
debug1: Host '[10.34.0.81]:10001' is known and matches the ECDSA host key.^M
debug1: Found key in /root/.ssh/known_hosts:2^M
debug1: rekey after 134217728 blocks^M
debug1: SSH2_MSG_NEWKEYS sent^M
debug1: expecting SSH2_MSG_NEWKEYS^M
debug1: rekey after 134217728 blocks^M
debug1: SSH2_MSG_NEWKEYS received^M
debug1: SSH2_MSG_EXT_INFO received^M
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>^M
debug1: SSH2_MSG_SERVICE_ACCEPT received^M
debug1: Authentications that can continue: publickey,password^M
debug1: Next authentication method: publickey^M
debug1: Offering RSA public key: /root/.ssh/id_rsa^M
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279^M
debug1: Authentication succeeded (publickey).^M
Authenticated to 10.34.0.81 ([10.34.0.81]:10001).^M
debug1: channel 0: new [client-session]^M
debug1: Requesting no-more-sessions@openssh.com^M
debug1: Entering interactive session.^M
debug1: pledge: network^M
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0^M
debug1: Sending environment.^M
debug1: Sending command:  orted -mca ess "env" -mca ess_base_jobid "2914779136" -mca ess_base_vpid 1 -mca ess_base_num_procs "2" -mca orte_node_regex "yz[1:1]-mc-face-alg00,[2:10].34.0.81@0(2)" -mca orte_hnp_uri "2914779136.0;tcp://10.34.0.77,180.97.191.77,172.17.0.1:24692" -mca plm "rsh" -mca plm_rsh_args "-p 10001 -v" -mca hwloc_base_binding_policy "none" -mca rmaps_base_mapping_policy "slot" -mca pmix "^s1,s2,cray,isolated"^M
orted: error while loading shared libraries: libopen-rte.so.40: cannot open shared object file: No such file or directory
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0^M
debug1: channel 0: free: client-session, nchannels 1^M
debug1: fd 0 clearing O_NONBLOCK^M
debug1: fd 2 clearing O_NONBLOCK^M
Transferred: sent 3064, received 2932 bytes, in 0.1 seconds^M
Bytes per second: sent 57452.4, received 54977.3^M
debug1: Exit status 127^M
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------

Can someone help me? Thank you!

**Comment by TimYuenior** [comment]
Does running it from the other machine work? When I got this error it was only on one machine and running `sudo ldconfig` solved it then.

**Comment by yangJirui** [comment]
It works in the other machine. 
But `sudo ldconfig` does not  work. Thank you.  @TimYuenior

**Comment by yangJirui** [comment]
Does anyone have a similar experience?

**Comment by Stonesjtu** [comment]
Can you try upload the result of `ssh {target_node} echo
$LD_LIBRARY_PATH`, I'm faced with such env problems when the remote
machine is not initialized properly by `.bashrc`

2018-07-26 14:56 GMT+08:00, yangJirui <notifications@github.com>:

**Comment by yangJirui** [comment]
The result of `ssh {target_node} echo $LD_LIBRARY_PATH` is : 
`
/usr/local/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
`
And same as local machine, "libopen-rte.so.40"　does exist in the 'usr/local/lib' of target_node. @Stonesjtu
