### ISSUE TITLE
Use pytorch from pip installed but get "#error You need C++17 to compile PyTorch" when installing horovod

### ISSUE THREAD

**Issue by pcjiang1998** [horovod/horovod#4014]
Install failed on Ubuntu 22.04 (with pytorch2.1, openmpi 5.0, cuda 12.3).
Use pytorch from pip installed but get "#error You need C++17 to compile PyTorch" when installing horovod

**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet): PyTorch
2. Framework version: torch==2.1.1+cu121
3. Horovod version: 0.28.1
4. MPI version: Open MPI 5.0.0
5. CUDA version: cuda-12.3
6. NCCL version: nccl_2.19.3-1+cuda12.3_x86_64
7. Python version: 3.10.13
8. Spark / PySpark version: None
9. Ray version: None
10. OS and version: Linux server-4090 6.2.0-34-generic #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
11. GCC version: gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04
12. CMake version: cmake version 3.22.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.rst)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.rst)?
4. Did you check if you question is answered in the [troubleshooting guide](https://github.com/horovod/horovod/blob/master/docs/troubleshooting.rst)?

**Bug report:**
Please describe erroneous behavior you're observing and steps to reproduce it.

Install command: 
CUDA_HOME=/usr/local/cuda-12.3 \
HOROVOD_WITHOUT_GLOO=1 \
HOROVOD_CUDA_HOME=/usr/local/cuda-12.3 \
HOROVOD_NCCL_LINK=SHARED \
HOROVOD_NCCL_HOME=/home/pcjiang/tools/nccl_2.19.3-1+cuda12.3_x86_64 \
HOROVOD_GPU_OPERATIONS=NCCL \
HOROVOD_WITH_MPI=1 \
HOROVOD_WITH_PYTORCH=1 \
HOROVOD_WITHOUT_TENSORFLOW=1 \
HOROVOD_WITHOUT_MXNET=1 \
MAKEFLAGS="-j1" pip install --no-cache-dir horovod  &> install_horovod2.log

install_horovod2.log content:
see attachment
[install_horovod2.log](https://github.com/horovod/horovod/files/13850175/install_horovod2.log)

**Comment by pcjiang1998** [comment]
CUDA_HOME=/usr/local/cuda-12.3 \
HOROVOD_WITHOUT_GLOO=1 \
HOROVOD_CUDA_HOME=/usr/local/cuda-12.3 \
HOROVOD_NCCL_LINK=SHARED \
HOROVOD_NCCL_HOME=/home/pcjiang/tools/nccl_2.19.3-1+cuda12.3_x86_64 \
HOROVOD_GPU_OPERATIONS=NCCL \
HOROVOD_WITH_MPI=1 \
HOROVOD_WITH_PYTORCH=1 \
HOROVOD_WITHOUT_TENSORFLOW=1 \
HOROVOD_WITHOUT_MXNET=1 \
pip install --no-cache-dir git+https://github.com/thomas-bouvier/horovod.git@compile-cpp17

https://github.com/horovod/horovod/pull/3998

it works

**Comment by kf-cuanschutz** [comment]
This was very helpful, thank you! I was trying to install horovod for an AMD GPU (torch 2.2.0+rocm5.6) and I had a similar error and once I applied your fix with https://github.com/thomas-bouvier/horovod.git@compile-cpp17 it worked.
