### ISSUE TITLE
cudaMemcpyAsync failed: invalid argument during training

### ISSUE THREAD

**Issue by ppwwyyxx** [horovod/horovod#404]
Software:
horovod 0.13.10 
TF: v1.9.0-0-g25c197e023 1.9.0
cuda 9.0
openmpi 2.1.1
NCCL 2.2.13

I ran a job on 6 nodes (48 GPUs). It's a very normal horovod job with a allreduce every step, and a broadcast once a while. It runs well for 17 hours until horovod throws this error on rank 3:

```
Caused by op 'HVDAllReduce/HorovodAllreduce_gradients_maskrcnn_conv_BiasAdd_grad_BiasAddGrad_0', defined at:
  File "./train.py[1,3]<stderr>:", line 607, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/HOME/tensorpack/tensorpack/train/interface.py", line 83, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/HOME/tensorpack/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/HOME/tensorpack/tensorpack/train/tower.py", line 172, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/HOME/tensorpack/tensorpack/train/trainers.py", line 378, in _setup_graph
  File "/HOME/tensorpack/tensorpack/train/trainers.py", line 369, in allreduce
    avg_grad = hvd.allreduce(grad, average=self._average)
  File "/HOME/.local/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 82, in allreduce
    summed_tensor = _allreduce(tensor)
  File "/HOME/.local/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 78, in _allreduce
    return MPI_LIB.horovod_allreduce(tensor, name=name)
  File "<string>", line 50, in horovod_allreduce
  File "/HOME/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/HOME/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/HOME/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): cudaMemcpyAsync failed: invalid argument
   [[Node: HVDAllReduce/HorovodAllreduce_gradients_maskrcnn_conv_BiasAdd_grad_BiasAddGrad_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/maskrcnn/conv/BiasAdd_grad/BiasAddGrad)]]
```

Post it in case someone sees similar issues. I understand this is probably not a reproducible error, or perhaps it's not a horovod issue.

**Comment by winwinJJiang** [comment]
I met the same issue when training and stops.

**Comment by alsrgv** [comment]
@ppwwyyxx, @winwinJJiang, anything in `dmesg`?

**Comment by ppwwyyxx** [comment]
No, nothing was printed in dmesg on the day the error happens.

**Comment by alsrgv** [comment]
I'd recommend running the job with `NCCL_DEBUG=INFO`.  That may shed some light next time it happens.

**Comment by ppwwyyxx** [comment]
The job was run with NCCL_DEBUG=INFO. It only prints some normal stuff at the very beginning of the training and nothing afterwards:
```
INFO NET : Using interface enp1s0f0:xx.xx.xx.xx<0>
INFO NET/IB : Using interface enp1s0f0 for sideband communication
INFO NET/IB: [0] mlx5_3:1/IB
INFO NET/IB: [1] mlx5_2:1/IB
INFO NET/IB: [2] mlx5_1:1/IB
INFO NET/IB: [3] mlx5_0:1/IB
INFO Using internal Network IB
INFO Using NCCL Low-latency algorithm for sizes below 16384
INFO comm 0x7f9faeec2b80 rank 3 nranks 48
INFO NET : Using interface enp1s0f0:xx.xx.xx.xx<0>
INFO NET/Socket : 1 interfaces found
INFO CUDA Dev 3, IB Ports : mlx5_3/1(SOC) mlx5_2/1(SOC) mlx5_1/1(PIX) mlx5_0/1(PHB)
INFO Ring 00 : 3[3] -> 1[1] via P2P/IPC
INFO Ring 01 : 3[3] -> 7[7] via P2P/IPC
INFO NET/IB: Dev 2 Port 1 qpn 5285 mtu 5 LID 194
INFO Ring 03 : 3[3] -> 2[2] via P2P/IPC
```

**Comment by alsrgv** [comment]
Gotcha. Actually, since it's failing at `cudaMemcpyAsync`, I'm guessing it's either [this](https://github.com/uber/horovod/blob/587aef22e68e7a7381dcc07b6b8d365db2fbc267/horovod/common/operations.cc#L953) or [this](https://github.com/uber/horovod/blob/587aef22e68e7a7381dcc07b6b8d365db2fbc267/horovod/common/operations.cc#L1066) operation.  It may be a race condition or a CUDA issue.  Do you have any sort of repro for it?

**Comment by ppwwyyxx** [comment]
I'm afraid I don't know how to reproduce it. Right now I've only seen it once.

Today I saw an issue (https://github.com/tensorflow/tensorflow/issues/21338) which basically says some unchecked cuda error in a buggy TensorFlow op may leak to other ops, making the other op appear to fail. I guess this is a possible explanation.

**Comment by andfoy** [comment]
I'm receiving this error also in PyTorch, but I'm unable to find a reproduction scenario, it occurs randomly some time after starting a new epoch.

**Comment by abidmalikwaterloo** [comment]
The following messgae is interesting:

  In file included from /home/amalik/Pytorch_virtual_enviornment/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                     from _test_cuda.c:493:
    /home/amalik/Pytorch_virtual_enviornment/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:10: fatal error: cuda.h: No such file or directory
     #include "cuda.h"
              ^~~~~~~~
    compilation terminated.
    INFO: Above error indicates that this PyTorch installation does not support CUDA.
    INFO: Unable to build PyTorch plugin, will skip it.

    Traceback (most recent call last):
      File "/tmp/pip-req-build-QFl6Ac/setup.py", line 720, in build_extensions
        build_torch_extension(self, options, torch_version)
      File "/tmp/pip-req-build-QFl6Ac/setup.py", line 587, in build_torch_extension
        'Horovod build with GPU support was requested, but this PyTorch '
    DistutilsPlatformError: Horovod build with GPU support was requested, but this PyTorch installation does not support CUDA.

    error: Neither TensorFlow nor PyTorch plugins were built. See errors above.
error



I installed Pytorch from the following the instruction on the site:

https://pytorch.org/

I used
pip install --user torch torchvision

**Comment by mrfox321** [comment]
Also got the same error:

`Caused by op u'DistributedAdamOptimizer_Allreduce/HorovodAllreduce_gradients_cudnn_rnn_stack_cudnn_gru_CudnnRNN_grad_tuple_control_dependency_3_0', defined at:`
...
`
UnknownError (see above for traceback): cudaMemcpyAsync failed: invalid argument
         [[Node: DistributedAdamOptimizer_Allreduce/HorovodAllreduce_gradients_cudnn_rnn_stack_cudnn_gru_CudnnRNN_grad_tuple_control_dependency_3_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/cudnn_rnn_stack/cudnn_gru/CudnnRNN_grad/CudnnRNNBackprop:3)]]`

**Comment by alsrgv** [comment]
@abidmalikwaterloo, could you try specifying `HOROVOD_CUDA_HOME=/path/to/your/cuda` in your installation flags?

**Comment by alsrgv** [comment]
@mrfox321, could you try running from debug branch, as described in https://github.com/uber/horovod/issues/404#issuecomment-425282711, to help narrow down this issue?

**Comment by abidmalikwaterloo** [comment]
@alsrgv  I tried as to build from scratch

-------------------

conda install pytorch torchvision -c pytorch
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/amalik/nccl_2.1.15-1+cuda9.0_x86_64/lib
export HOROVOD_NCCL_HOME=/home/amalik/nccl_2.1.15-1+cuda9.0_x86_64/
export HOROVOD_GPU_ALLREDUCE=NCCL
export HOROVOD_CUDA_HOME= /software/cuda/
export PATH=$PATH:/software/openmpi/3.0.0-gnu/bin/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/software/openmpi/3.0.0-gnu/lib/
pip install --user -v --no-cache-dir git+https://github.com/uber/horovod@debug_before_memcpy


I am getting the following message:
--------------------------------------------------

(/home/amalik/PyTorchHorovod) [amalik@node04 PyTorchHorovod]$ pip install --user -v --no-cache-dir git+https://github.com/uber/horovod@debug_before_memcpy
Created temporary directory: /tmp/pip-ephem-wheel-cache-v94wl1es
Created temporary directory: /tmp/pip-install-6s89svrr
Collecting git+https://github.com/uber/horovod@debug_before_memcpy
  Created temporary directory: /tmp/pip-req-build-vlcqfrb8
  Cloning https://github.com/uber/horovod (to revision debug_before_memcpy) to /tmp/pip-req-build-vlcqfrb8
  Running command git clone -q https://github.com/uber/horovod /tmp/pip-req-build-vlcqfrb8
  Running command git show-ref debug_before_memcpy
  2d423104c47de36605847c804563cde6dd9109b7 refs/remotes/origin/debug_before_memcpy
  Running command git rev-parse HEAD
  8d72d66738037acad8517da95d5d76e773e7117a
  Running command git checkout -q 2d423104c47de36605847c804563cde6dd9109b7
  Running setup.py (path:/tmp/pip-req-build-vlcqfrb8/setup.py) egg_info for package from git+https://github.com/uber/horovod@debug_before_memcpy
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/horovod.egg-info
    writing pip-egg-info/horovod.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/horovod.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/horovod.egg-info/requires.txt
    writing top-level names to pip-egg-info/horovod.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching '.eggs'
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-vlcqfrb8 has version 0.14.1, which satisfies requirement horovod==0.14.1 from git+https://github.com/uber/horovod@debug_before_memcpy
Requirement already satisfied: cffi>=1.4.0 in ./lib/python3.6/site-packages (from horovod==0.14.1) (1.11.5)
Requirement already satisfied: pycparser in ./lib/python3.6/site-packages (from cffi>=1.4.0->horovod==0.14.1) (2.18)
Installing collected packages: horovod
  Created temporary directory: /tmp/pip-record-db5v6nte
  Running setup.py install for horovod ...     Running command /home/amalik/PyTorchHorovod/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-vlcqfrb8/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-db5v6nte/install-record.txt --single-version-externally-managed --compile --user --prefix=
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.6/horovod
    creating build/lib.linux-x86_64-3.6/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.6/horovod/common
    creating build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks_impl.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/keras
    copying horovod/keras/impl.py -> build/lib.linux-x86_64-3.6/horovod/keras
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow
    creating build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.6/horovod/torch
    creating build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.6/horovod/tensorflow/keras
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib
    creating build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.6/horovod/torch/mpi_lib_impl
    running build_ext
    gcc -pthread -B /home/amalik/PyTorchHorovod/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/amalik/PyTorchHorovod/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /home/amalik/PyTorchHorovod/compiler_compat -L/home/amalik/PyTorchHorovod/lib -Wl,-rpath=/home/amalik/PyTorchHorovod/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    gcc -pthread -B /home/amalik/PyTorchHorovod/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/amalik/PyTorchHorovod/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.6/test_compile/test_link_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /home/amalik/PyTorchHorovod/compiler_compat -L/home/amalik/PyTorchHorovod/lib -Wl,-rpath=/home/amalik/PyTorchHorovod/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.6/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_link_flags.so
    error: /software/openmpi/3.0.0-gnu/ failed (see error below), is MPI in $PATH?
    Note: If your version of MPI has a custom command to show compilation flags, please specify it with the HOROVOD_MPICXX_SHOW environment variable.

    Traceback (most recent call last):
      File "/tmp/pip-req-build-vlcqfrb8/setup.py", line 221, in get_mpi_flags
        shlex.split(show_command), universal_newlines=True).strip()
      File "/home/amalik/PyTorchHorovod/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/amalik/PyTorchHorovod/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/amalik/PyTorchHorovod/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/amalik/PyTorchHorovod/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: '/software/openmpi/3.0.0-gnu/'

error
Cleaning up...
  Removing source in /tmp/pip-req-build-vlcqfrb8
Command "/home/amalik/PyTorchHorovod/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-vlcqfrb8/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-db5v6nte/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-vlcqfrb8/
Exception information:
Traceback (most recent call last):
  File "/home/amalik/PyTorchHorovod/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/amalik/PyTorchHorovod/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/amalik/PyTorchHorovod/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/amalik/PyTorchHorovod/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/home/amalik/PyTorchHorovod/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/amalik/PyTorchHorovod/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-vlcqfrb8/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-db5v6nte/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-vlcqfrb8/
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


It is complaining about the MPI ??

**Comment by alsrgv** [comment]
@abidmalikwaterloo, do you have HOROVOD_MPICXX_SHOW set?  It appears that it's set to `/software/openmpi/3.0.0-gnu/`.  Can you set it to `export HOROVOD_MPICXX_SHOW="/software/openmpi/3.0.0-gnu/bin/mpicxx -show"`

**Comment by abidmalikwaterloo** [comment]
@alsrgv It seems that I didn't get any error yet with this new setting. I also changed the virtual environment. Currently, I am testing it extensively with different runtime variables just to ensure that if the breaking has to do with the nondeterministic behavior.

**Comment by abidmalikwaterloo** [comment]
@alsrgv  Finally
 got the same error. FYI, I ran a whole training with 5 GPUs with 10 epochs. Now I tried with  6GPUs and got the error. I think shows an undeterministic behavior. I am attaching the error log for your convenience.

[err_4559.log.pdf](https://github.com/uber/horovod/files/2446560/err_4559.log.pdf)

**Comment by andfoy** [comment]
@alsrgv I managed to replicate the error once again using your debugging build, here is the error traceback:

```python
Traceback (most recent call last):
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/runpy.py", line 193, in _run_module_as_main
Traceback (most recent call last):
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/runpy.py", line 85, in _run_code
    "__main__", mod_spec)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    exec(code, run_globals)
  File "/media/SSD1/score-textseg/ref_score_net/train.py", line 495, in <module>
  File "/media/SSD1/score-textseg/ref_score_net/train.py", line 495, in <module>
    train_loss = train(epoch)
  File "/media/SSD1/score-textseg/ref_score_net/train.py", line 363, in train
    train_loss = train(epoch)
  File "/media/SSD1/score-textseg/ref_score_net/train.py", line 363, in train
    optimizer.step()
    optimizer.step()
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/horovod/torch/__init__.py", line 88, in step
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/horovod/torch/__init__.py", line 88, in step
    self.synchronize()
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/horovod/torch/__init__.py", line 84, in synchronize
    self.synchronize()
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/horovod/torch/__init__.py", line 84, in synchronize
    synchronize(handle)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 417, in synchronize
    synchronize(handle)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 417, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    mpi_lib.horovod_torch_wait_and_clear(handle)
  File "/home/eamargffoy/anaconda3/envs/parallel/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: cudaMemcpyAsync1 failed: invalid argument
torch.FatalError: cudaMemcpyAsync1 failed: invalid argument

```

**Comment by alsrgv** [comment]
@abidmalikwaterloo, @andfoy, thanks for reproducing this issue.  It certainly narrows it down to a single `cudaMemcpyAsync` statement.  I've updated the `debug_before_memcpy` branch with additional debug information, could you re-install and reproduce again?

**Comment by abidmalikwaterloo** [comment]
@alsrgv  I am setting my CUDA flag using HOROVOD_CUDA_HOME. I am still getting the following error:

generating /tmp/tmpw_a9k1rr/_test_cuda.c
    setting the current directory to '/tmp/tmpw_a9k1rr'
    running build_ext
    building '_test_cuda' extension
    mpicc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/amalik/PyTorchHorovod/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/amalik/PyTorchHorovod/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/amalik/PyTorchHorovod/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/home/amalik/PyTorchHorovod/include/python3.6m -c _test_cuda.c -o ./_test_cuda.o -std=c99 -std=c11 -fPIC -O2
    In file included from /home/amalik/PyTorchHorovod/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                     from _test_cuda.c:493:
    /home/amalik/PyTorchHorovod/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory
     #include "cuda.h"
                      ^
    compilation terminated.
    INFO: Above error indicates that this PyTorch installation does not support CUDA.
    INFO: Unable to build PyTorch plugin, will skip it.

    Traceback (most recent call last):
      File "/tmp/pip-req-build-qkvrizgc/setup.py", line 720, in build_extensions
        build_torch_extension(self, options, torch_version)
      File "/tmp/pip-req-build-qkvrizgc/setup.py", line 587, in build_torch_extension
        'Horovod build with GPU support was requested, but this PyTorch '
    distutils.errors.DistutilsPlatformError: Horovod build with GPU support was requested, but this PyTorch installation does not support CUDA.

    error: Neither TensorFlow nor PyTorch plugins were built. See errors above.
error


Why it is not detecting the CUDA?

**Comment by abidmalikwaterloo** [comment]
@alsrgv FYI, Running the experiments. Unable to get the resources because of the long queue on the cluster. Will update as soon as I see the crash.

**Comment by ppwwyyxx** [comment]
Haven't seen such errors afterwards. So closing
