### ISSUE TITLE
Cross-compiled Tensorflow for Intel KNL inside Singularity Container

### ISSUE THREAD

**Issue by jtchilders** [horovod/horovod#405]
I have cross-compiled Tensorflow 1.9.0 with the AVX512 optimizations inside a Singularity container based on the Centos OS. After installing the tensorflow wheel I call 
```bash
HOROVOD_WITH_TENSORFLOW=1 CXXFLAGS='-mavx -mavx2 -mfma -mavx512f -mavx512pf -mavx512cd -mavx512er' pip install horovod
``` 
but see this error:
```bash
copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-2.7/horovod/torch/mpi_lib_impl
    running build_ext
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -mavx -mavx2 -mfma -mavx512f -mavx512pf -mavx512cd -mavx512er -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    gcc -pthread -shared -Wl,-z,relro -mavx -mavx2 -mfma -mavx512f -mavx512pf -mavx512cd -mavx512er build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -L/usr/lib64 -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
    2018-07-27 16:10:19.089500: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX512F instructions, but these aren't available on your machine.

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-YmoL6v/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Pl9pKr/install-record.txt --single-version-externally-managed --compile" failed with error code -6 in /tmp/pip-install-YmoL6v/horovod/
```

Obviously this error makes sense given my situation, Horovod is trying to build itself against a tensorflow cross-compiled for another architecture while running on a different architecture. Is there a way to tell Tensorflow to ignore this error?

**Comment by jtchilders** [comment]
@alsrgv Thanks for the suggestion. I ran it with and without, but got the same result. The error is coming from Tensorflow because I've built it for the Intel KNL. I'm sure it is triggered when horovod imports tensorflow or tries to compile against it. I'm not sure how to disable it.

**Comment by alsrgv** [comment]
@jtchilders, one workaround I can think of is to:
1. Install vanilla `tensorflow==1.9.0` or `tensorflow-gpu==1.9.0`
2. Install Horovod
3. Replace TensorFlow installed in (1) with your KNL TensorFlow.

Would that work?

**Comment by jtchilders** [comment]
Thanks for the idea. I did this, but now see this error from `python -c "import horovod.tensorflow as hvd"`:

```
tensorflow.python.framework.errors_impl..NotFoundErrorNotFoundError: /usr/lib64/python2.7/site-packages/horovod/tensorflow/mpi_lib.so: undefined symbol:_ZNK10tensorflow8OpKernel4nameEv
```

**Comment by jtchilders** [comment]
In the end I could not get this working. I tried hacking the `tensorflow/core/platform/cpu_feature_guard.cc` file to replace the `LOG(FATAL)` with `LOG(WARN)` so Horovod would build without exiting. This worked, but when I ran on the KNL it still gave me the 'NotFoundError' as above. 

So then I git cloned horovod outside the container, but ran the horovod build command `python setup.py build` inside the container while running on an actual Intel KNL chip and that worked. But now Horovod is living outside the container and you must mount it into the container when you run. This is not ideal, but works for the moment.

**Comment by alsrgv** [comment]
Can you do `[flags] python setup.py install` inside the container running on KNL chip?  Alternatively, you can do `[flags] python setup.py bdist_wheel` inside the KNL container and create a binary wheel file that you can install quicker than source installation.

**Comment by tonyreina** [comment]
I think I have a similar error using the new Anaconda wheel (which has MKL-DNN included). 

I ended up rebuilding both TensorFlow (with MKL-DNN) and OpenMPI on the Xeon and it works.  My guess is that the glibc included with CentOS 7 is just too out of date compared with the compiler being used to create the official TensorFlow wheels. 

If anyone knows differently, please let me know.

Thanks.
-Tony

**Comment by utke1** [comment]
I am currently in a similar situation with TF 1.13.1 cross compiled to support AVX2 and other instructions for a target hardware that is different from the build hardware (where I build my docker images)  and this works fine for TF itself but then the install for horovod 0.16.1 fails with ```tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.``` 
IOW - is it true that the horovod install simply cannot deal with cross compile situations because as part of the install you absolutely have to import tensorflow at some point which would then imply that I would have to change the behavior of TF's cpu_feature_guard to avoid that failure
