### ISSUE TITLE
Horovod Configuration error

### ISSUE THREAD

**Issue by hamzafar** [horovod/horovod#412]
Hi,

I am configuring horovod on my three machine cluster, and I am following the below link provided:

https://github.com/uber/horovod/blob/master/docs/docker.md

But I am not able to configure it even on my single machine. As, when I am building horovod with the following commands: 

$ mkdir horovod-docker
$ wget -O horovod-docker/Dockerfile https://raw.githubusercontent.com/uber/horovod/master/Dockerfile
$ docker build -t horovod:latest horovod-docker

The last command **$ docker build -t horovod:latest horovod-docker** always gives me error. you can see the snapshot of error below:
![horovod-docker-error](https://user-images.githubusercontent.com/6842017/43447322-4f1bbdb0-94bc-11e8-9b52-1e263b86cc34.png)

I am using python 3.5.2 version.

Although, its really generic question, but it will be highly appreciated if you can recommend me some steps to cofigure it.

Regards
Hamza Zafar

**Comment by tgaddair** [comment]
Hey @hamzafar, sounds like there's already a version of NCCL installed.  You could try allowing downgrades by modifying the `apt-get install` line like so:

```
RUN apt-get update && apt-get install -y --no-install-recommends --allow-downgrades \
        build-essential \
        cmake \
        git \
        curl \
        vim \
        wget \
        ca-certificates \
        libcudnn7=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION} \
        libnccl-dev=${NCCL_VERSION} \
        libjpeg-dev \
        libpng-dev \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-dev
```

Let me know if that works for you.

**Comment by hamzafar** [comment]
Hi @tgaddair, thanks I have ran horovod successfully.

But, Now I am not figuring out how I can run horovod on multiple machines; the error I have identified is that I am unable to ssh from primary container to secondary container. Would you please guide me how I can ssh secondary machine container at port 12345.
