### ISSUE TITLE
I meet an error when i used horovod

### ISSUE THREAD

**Issue by wu-yy** [horovod/horovod#429]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Stalled ops:
allreduce.avg_loss [missing ranks: 1]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Stalled ops:
allreduce.avg_loss [missing ranks: 1]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. 
Stalled ops:
allreduce.avg_loss [missing ranks: 1]

my GPU is Quadro。But I don't meet this error when my GPU is GeForce GTX 1080

**Comment by tgaddair** [comment]
Hey @wu-yy, can you share what code you're running, and how many workers you're running?  This type of error usually indicates that different workers are running different code (in this case, worker 1 is not calling allreduce on the avg_loss tensors).

**Comment by wu-yy** [comment]
Thank you for you reply @tgaddair .My code is [here](https://github.com/wu-yy/horovod/blob/master/examples/pytorch_mnist.py) which is the example of horovod. I just run the example on Pytorch .
And my command is:` mpirun -np 2 \
    -H localhost:2 \
    -bind-to none -map-by slot \
    -mca pml ob1 -mca btl ^openib \
    python3.6 pytorch_mnist.py`

**Comment by tgaddair** [comment]
Hmmm, so you're running it all locally.  That's curious.  Have you verified that password-less ssh works with `ssh localhost`?

If that doesn't work, could you try making a gist with `strace` as shown in this comment [here](https://github.com/uber/horovod/issues/110#issuecomment-347737251)?

**Comment by wu-yy** [comment]
@tgaddair when I run `ssh localhost`，it works and it print
 `Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
`and more

1. when I run the command 1
`strace  -o out.txt mpirun -np 2 \
    -H localhost:2 \
    -bind-to none -map-by slot \
    -x NCCL_SOCKET_IFNAME=enp11s0\
    -mca pml ob1 -mca btl ^openib \
    -mca btl_tcp_if_exclude lo \
    python3.6 pytorch_mnist.py`
The ouput is [here](https://github.com/wu-yy/OutputFile/blob/master/out.txt)

2. when I run the command2
` strace -f -e 'trace=!poll' -o out2.txt mpirun -np 2     -H localhost:2     -bind-to none -map-by slot     -x NCCL_SOCKET_IFNAME=enp11s0    -mca pml ob1 -mca btl ^openib     -mca btl_tcp_if_exclude lo     python3.6 pytorch_mnist.py 
`
The output is[ here](https://drive.google.com/open?id=17s9TvczI1Chf50iqRwkp9Ai6CqZ1Jy_6).

**Comment by alsrgv** [comment]
@wu-yy, could you also share the complete output of the script, starting with `mpirun` command?

**Comment by wu-yy** [comment]
@alsrgv Thank you very much! There is no errors when I set the test_batch_size to 100.
And my program is [here](https://github.com/wu-yy/OutputFile/blob/master/pytorch_mnist.py).

**Comment by alsrgv** [comment]
I see.  It's possible that you were running out of memory with test_batch_size of 1000.

**Comment by wu-yy** [comment]
@alsrgv yep, Thanks!

**Comment by jacobhinkle** [comment]
I am not sure if this is happening in the current case, but I have also found this particular deadlock happens whenever the number of iterations per epoch is different for different ranks. This happens for example if the number of training samples is equal to k*batch_size*world_size+1 for some integer k. In that case, one of the ranks will have to perform an extra iteration to cover the extra sample, causing a deadlock in the first epoch. The problem can be solved by changing parameters, skipping the extra iteration, or adding an "empty" iteration to the other ranks, but there should probably be a warning if it's detected that some ranks have different number of iterations than others.

**Comment by wjxiz1992** [comment]
> I am not sure if this is happening in the current case, but I have also found this particular deadlock happens whenever the number of iterations per epoch is different for different ranks. This happens for example if the number of training samples is equal to `k * batch_size * world_size+1` for some integer k. In that case, one of the ranks will have to perform an extra iteration to cover the extra sample, causing a deadlock in the first epoch. The problem can be solved by changing parameters, skipping the extra iteration, or adding an "empty" iteration to the other ranks, but there should probably be a warning if it's detected that some ranks have different number of iterations than others.

Your answer still shines in 2021.
