### ISSUE TITLE
mpi_lib.so: undefined symbol: _ZNK10tensorflow8OpKernel4nameEv on  CPU nodes

### ISSUE THREAD

**Issue by karthikvadla** [horovod/horovod#431]
Hi, We are running into below issue with CPU nodes where we installed `anaconda` and inside `horovod`. 
We are using `tensorflow 1.9` and `openmpi 3.0.0` (tired with `3.1.1` too, have the same issue).

```>>> import horovod.keras as hvd
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mlt_user/anaconda3/envs/tf/lib/python2.7/site-packages/horovod/keras/__init__.py", line 19, in <module>
    import horovod.tensorflow as hvd
  File "/home/mlt_user/anaconda3/envs/tf/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 43, in <module>
    from horovod.tensorflow.mpi_ops import allgather
  File "/home/mlt_user/anaconda3/envs/tf/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 57, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/home/mlt_user/anaconda3/envs/tf/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 44, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/mlt_user/anaconda3/envs/tf/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/mlt_user/anaconda3/envs/tf/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so: undefined symbol: _ZNK10tensorflow8OpKernel4nameEv```

**Comment by tgaddair** [comment]
Hey @karthikvadla, looks like a TensorFlow install issues.  Can you try installing TensorFlow and Horovod in a fresh virtualenv?

**Comment by tonyreina** [comment]
I've been helping Karthik with this. A little more info. 

We're using an Anaconda environment which now picks up the Intel TensorFlow MKL-DNN version via `conda install tensorflow`. That's good because we are doing everything on a CPU (without GPU). The machine has CentOS 7 which comes with the older gcc 4.8.5.

I've confirmed that Horovod works when I use the non-MKL-DNN version via `pip install tensorflow` so there seems to be something different about how the .so are being built in that version.

When I do the `pip install horovod` is it building the source or just installing pre-built libs? I'm wondering if I re-build the libraries on this machine whether it will help.

Thanks.
Best,
-Tony

**Comment by tonyreina** [comment]
Followup:  I built TensorFlow from source (including MKL-DNN) on the machine. This seems to work. So there's something weird about the TensorFlow wheel we were using.

**Comment by alsrgv** [comment]
Could this by any chance be related to #405?

**Comment by YFwang1992** [comment]
@tonyreina   pip install help me too. thx.have u had any idea about differ between pip install and conda install.

**Comment by nicolefinnie** [comment]
I hit the very same problem on `RHEL 7` with `openMPI 3.0.0` , it seems the pre-built tensorflow version does not work with horovod which is built from source, when `pip install horovod` is issued. I see this problem on `RHEL` but not on `Ubuntu`, so I do think the statement of @tonyreina might be very close to the truth,  glibc on CentOS/RHEL might be out of date. `2.24` on my Ubuntu versus `2.17` on my RHEL. 

And thanks to @tonyreina, at least I can work around the problem by installing the non-MKL DNN version of tensorflow as follows:

```
1. Load CUDNN/CUDA in 9.0 because it's required by newer tensorflow versions such as 1.10, 1.11, 1.12. However, 1.13 requires CUDNN/CUDA 10. 
2. pip install tensorflow==1.11 tensorflow-gpu==1.11 (or whatever version compatible with CUDA 9.0)
3. pip install --no-cache-dir horovod
4. python -c "import horovod.tensorflow as hvd" to test if you still hit this runtime error.
```
However, this is not a viable solution for `RHEL/CentOS`, if we need the performance boost from `MKL DNN`. It'd be great if `MKL DNN tensorflow` could work with horovod on `RHEL/CentOS` without us rebuilding tensorflow from scratch, since lots of companies' servers are on RHEL.

**Comment by nicolefinnie** [comment]
@alsrgv  It's interesting to see an Intel white paper pointed out the very same problem, check out the page 13.

[Best Known Methods for Scaling Deep Learning with Tensorflow on Intel Xeon Processor Based Clusters](https://www.intel.ai/ai/wp-content/uploads/sites/69/Intel_Xeon_HPC_AI_TensorFlow_Scaleout_Package_V_Saletore_AIPG_v0.85_04302018.pdf )

```
Ensure that the same GCC version that was using to build TensorFlow is in PATH when
installing Horovod. If different versions were used, especially GCC versions older than
5.1, then object files get compiled with for different versions of the ABI
(_GLIBCXX_USE_CXX11_ABI), resulting in this error at link time. To fix this, uninstall
Horovod, fix PATH and LD_LIBRARY_PATH to point to the correct GCC, and then reinstall
Horovod.
```

**Comment by andrewor14** [comment]
I had the same issue. The problem for me was that horovod was installed with a different tensorflow installation from the one I have now. All you have to do to fix it is simply uninstalling horovod and re-installing it again through pip using the `--no-cache-dir` flag.

**Comment by anishagartia** [comment]
I faced the same problem with `gcc 4.8.5` on a `CentOS 7.6`. 
The libraries `openmpi 3.0` and `intel-tensorflow 1.13.1` are installed using conda. 

Thanks to @nicolefinnie's note and [Intel's paper](https://www.intel.ai/ai/wp-content/uploads/sites/69/Intel_Xeon_HPC_AI_TensorFlow_Scaleout_Package_V_Saletore_AIPG_v0.85_04302018.pdf), I resolved it by ensuring GCC was consistent throughout.

> It could be caused by different compiler versions, so if tensorflow is not going to provide a compatible version in anaconda, horovod would have to compile their own mpi_lib differently to match the anaconda tensorflow library

> Ensure that the same GCC version that was using to build TensorFlow is in PATH when
installing Horovod. If different versions were used, especially GCC versions older than
5.1, then object files get compiled with for different versions of the ABI
(_GLIBCXX_USE_CXX11_ABI), resulting in this error at link time. To fix this, uninstall
Horovod, fix PATH and LD_LIBRARY_PATH to point to the correct GCC, and then reinstall
Horovod.


I installed all dependencies like openMPI BEFORE installing tensorflow and horovod. GCC's location `/usr/bin`  was already in my path at this point. 

Making ANY changes to the conda environment between tensorflow and horovod installations gave me the same error - even installing unrelated libraries like nb-conda. Here's the sequence of installations that worked for me.


```
conda activate myenv
yum install openmpi openmpi-devel
module add mpi/openmpi-x86_64
source /etc/profile.d/modules.sh
conda install -c intel tensorflow
pip install horovod
python -c "import horovod.tensorflow as hvd"
```

**Comment by dengc367** [comment]
@nicolefinnie 
I first run the following commands and fix the problem: 
`
pip uninstall horovod
conda install gcc_linux-64 gxx_linux-64
conda run pip install --no-cache-dir horovod
`
I think you should run the pip install command in the conda environment and can find the tensorflow_framework.so shared library.

good lucks.

**Comment by anishagartia** [comment]
If you see see the same error, you have to remove the prereq libraries. If you attempted to install horovod before then it would have installed the prereqs as well. Remove the "Requirement satisfied" libraries you see manually and try this again. This removed the error for me when I faced it again recently.  

> I faced the same problem with `gcc 4.8.5` on a `CentOS 7.6`.
> The libraries `openmpi 3.0` and `intel-tensorflow 1.13.1` are installed using conda.
> 
> Thanks to @nicolefinnie's note and [Intel's paper](https://www.intel.ai/ai/wp-content/uploads/sites/69/Intel_Xeon_HPC_AI_TensorFlow_Scaleout_Package_V_Saletore_AIPG_v0.85_04302018.pdf), I resolved it by ensuring GCC was consistent throughout.
> 
> > It could be caused by different compiler versions, so if tensorflow is not going to provide a compatible version in anaconda, horovod would have to compile their own mpi_lib differently to match the anaconda tensorflow library
> 
> > Ensure that the same GCC version that was using to build TensorFlow is in PATH when
> > installing Horovod. If different versions were used, especially GCC versions older than
> > 5.1, then object files get compiled with for different versions of the ABI
> > (_GLIBCXX_USE_CXX11_ABI), resulting in this error at link time. To fix this, uninstall
> > Horovod, fix PATH and LD_LIBRARY_PATH to point to the correct GCC, and then reinstall
> > Horovod.
> 
> I installed all dependencies like openMPI BEFORE installing tensorflow and horovod. GCC's location `/usr/bin` was already in my path at this point.
> 
> Making ANY changes to the conda environment between tensorflow and horovod installations gave me the same error - even installing unrelated libraries like nb-conda. Here's the sequence of installations that worked for me.
> 
> ```
> conda activate myenv
> yum install openmpi openmpi-devel
> module add mpi/openmpi-x86_64
> source /etc/profile.d/modules.sh
> conda install -c intel tensorflow
> pip install horovod
> python -c "import horovod.tensorflow as hvd"
> ```

**Comment by denfromufa** [comment]
I had the same issue with powerai environment when switching from spectrum mpi in powerai environment to spectrum mpi in lfs suite. It looks like the same gcc compiler mismatch issue between tensorflow and horovod compilations. Not sure what is the resolution, unless I have to compile even tensorflow from source with the same compiler.

**Comment by Excalibur0214** [comment]
> @nicolefinnie
> I first run the following commands and fix the problem:
> 
> ```
> pip uninstall horovod
> 
> conda install gcc_linux-64 gxx_linux-64
> 
> conda run pip install --no-cache-dir horovod
> ```
> 
> I think you should run the `pip install` command in the conda environment and can find the libtensorflow_framework.so shared library.
> 
> good lucks.

As the above discussion says, this problem may be caused by gcc version. This solution is simple and useful, no need to compile from source or something like that.

**Comment by fanbeatsman** [comment]
I am having this problem too and none of the above steps are solving it for me. Nor did any of the solutions in https://github.com/horovod/horovod/issues/656

Ubuntu 18.04
OpenMpi 4.0.2
Python 3.6.10
Cuda 10.0
Tensorflow 1.14

To install Horovod, I did
conda create --name myenv3
conda activate myenv3
conda install python=3.6
conda install gcc_linux-64 gxx_linux-64
conda install pip
pip install --no-cache-dir tensorflow-gpu==1.14
pip install --no-cache-dir  horovod


```
python
>>> import horovod.tensorflow

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 28, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 49, in <module>
    MPI_LIB = _load_library('mpi_lib' + get_ext_suffix())
  File "/home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 45, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/fanma/anaconda2/envs/myenv4/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4gloo3mpi7ContextC1ERKP19ompi_communicator_t 
```

**Comment by anishagartia** [comment]
Remove the dependencies as well:
pip-autoremove horovod -y

**Comment by fanbeatsman** [comment]
It didn't work. I kept making virtual envs which should remove dependencies.

What worked for me is completely removing Anaconda (because of it's compilers), recompiling openmpi (with system compilers) using https://www.open-mpi.org/faq/?category=building#easy-build, 
making a clean python virtual env 
pip install tensorflow==1.14
sudo apt-get install g++-4.8 (Needed because Horovod can't build tensorflow 1.14 with any g++>5)
pip install horovod

I think the cause is that I was compiling Horovod and Tensorflow with Anaconda compilers using pip inside an Anaconda environment and Anaconda installed libraries. My new way at least ensures a certain amount of cohesion between those.

But honestly I have no idea...

**Comment by yeamusic21** [comment]
Hitting this issue on Azure Data Science Virtual Machine :-(
