### ISSUE TITLE
Training on multiple hosts using synthetic data

### ISSUE THREAD

**Issue by MukundKhandelwal** [horovod/horovod#436]
Hi,

I am trying to run distributed training using Horovod on multiple hosts with CPU only. The process halts after running this command and there is no initiation of model generation or warm ups. The command that I am using is:

mpirun -np 12 -H server 1: 4, server 2: 4, server 3: 4 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod --horovod_device cpu

Please correct me if I am wrong.

Additionally, I would also like to confirm my understanding of the command i.e. a total of 12 processes are launched on 3 machines where each machine runs 4 processes (for example, server 1: 4). 

Thanks,
Mukund Khandelwal

**Comment by MukundKhandelwal** [comment]
@alsrgv Could you please help me with the issue. Thanks.

**Comment by alsrgv** [comment]
@MukundKhandelwal, could you check if anything mentioned in [here](https://github.com/uber/horovod/blob/master/docs/running.md#hangs-due-to-non-routed-network-interfaces) or [here](https://github.com/uber/horovod/blob/master/docs/troubleshooting.md) is applicable to you?  Also, if you're using CPU you may want to run # of processes = # of sockets per server, or even one process per server.  Finally, you should NOT have space between `server3:` and `4`, or after commas.  I.e. no spaces in this: `-H server1:2,server2:2,server3:2`

**Comment by MukundKhandelwal** [comment]
Hi,
I ran the command after removing spaces but it still hangs. As far as the network interfaces are concerned, I have a Local Loopback and Ethernet. 
However, I do see a similar prompt (shown below) while trying to SSH to other hosts.
![image](https://user-images.githubusercontent.com/31802591/44149298-995743d2-a069-11e8-9fce-35774ff40efe.png)
Could this be the reason why the process hangs and do I need to enable passwordless authentication?

Thanks for all the help.
Mukund

**Comment by tgaddair** [comment]
Hey @MukundKhandelwal, you should definitely enable passwordless authentication.  This is most likely what's causing the hanging you're experiencing.
