### ISSUE TITLE
MPI_Finalize() called after exit during shutdown

### ISSUE THREAD

**Issue by wlepera** [horovod/horovod#439]
We are seeing an issue with horovod and IBM Spectrum MPI, with fatal errors and aborts/core dumps at termination.  I work on the Spectrum MPI team at IBM and was asked to investigate.  What I found was the Linux exit handlers were being invoked before MPI_Finalize() was called.

I looked at the horovod code, and although I'm not fluent in Python, it appears that the horovod_shutdown() routine defined in common/operations.cc (where MPI_Finalize() is called) is being called from a registered exit handler, based on the following code from \_\_init\_\_.py:

```     51 def init(comm=None):
     52     """A function that initializes Horovod.
     53 
     54     Args:
     55       comm: List specifying ranks for the communicator, relative to the MPI_COMM_WORLD
     56         communicator OR the MPI communicator to use. Given communicator will be duplicated.
     57         If None, Horovod will use MPI_COMM_WORLD Communicator.
     58 
     59     """
     60     if comm is None:
     61         comm = []
     62 
     63     atexit.register(shutdown)
     64 
     65     if not isinstance(comm, list):
     66         from mpi4py import MPI
     67         if MPI._sizeof(MPI.Comm) == ctypes.sizeof(ctypes.c_int):
     68             MPI_Comm = ctypes.c_int
     69         else:
     70             MPI_Comm = ctypes.c_void_p
     71             MPI_COMMON_LIB_CTYPES.horovod_init_comm.argtypes = [MPI_Comm]
     72 
     73         comm_obj = MPI_Comm.from_address(MPI._addressof(comm))
     74         return MPI_COMMON_LIB_CTYPES.horovod_init_comm(comm_obj)
     75     else:
     76         comm_size = len(comm)
     77         return MPI_COMMON_LIB_CTYPES.horovod_init(
     78             (ctypes.c_int * comm_size)(*comm), ctypes.c_int(comm_size))
     79 
     80 
     81 def shutdown():
     82     return MPI_COMMON_LIB_CTYPES.horovod_shutdown()
     83 
``` 

If true, this means that exit has been called before MPI_Finalize(), which is what our debug of the issue is showing.  This is a violation of the MPI standard, which states that MPI_Finalize() must be called _before_ a program exits.  We believe this is the root cause of the issue.

Our customer has pointed out they do not see the issue with other MPI implementations.  We are investigating a way to work around the issue in Spectrum MPI, but were wondering:

1. If our interpretation of the shutdown sequence was correct.

2. If there was a reason why the MPI_Finalize path was coded in this way.  Could horovod_shutdown() be removed from the at_exit handlers and instead called explicitly from horovod's exit routine, after the BackgroundThreadLoop terminates and joins but before exit is called?

Thanks in advance for any insight you can offer.

Bill

**Comment by alsrgv** [comment]
Hi Bill,

Your interpretation of Horovod behavior is correct.  It seems that most MPI implementations are OK with `MPI_Finalize()` being called in exit hooks.  [mpi4py](https://mpi4py.scipy.org/) uses [similar behavior](https://mpi4py.readthedocs.io/en/stable/overview.html#initialization-and-exit), since it makes it convenient for users.

To workaround, users could add `hvd.shutdown()` at the end of their script, but it would be preferable to fix this in Spectrum MPI.

Thanks,
Alex

**Comment by alsrgv** [comment]
If that's the case, users can add an explicit `hvd.shutdown()` command at the end of their script to prevent an error.
