### ISSUE TITLE
Questions about WAIT_FOR_DATA 

### ISSUE THREAD

**Issue by SunnyBeike** [horovod/horovod#449]
Hi, 

I use a Four GTX1080 GPs machine to test Horovod using ResNet50 (https://github.com/alsrgv/benchmarks/tree/horovod). I found that the time duration of WAITH_FOR_DATA is very long and varies dramatically.

![image](https://user-images.githubusercontent.com/3234818/44183184-9b468580-a13c-11e8-948d-12f357e57085.png)

In the Horovod source code, the WAIT_FOR_DATA is monitored in the PerformOperation() function. In my opinion, PerformOperation is called only if all the tensors have been computed and become ready to do the allreduce operation, because the coordinator wouldn't call this function until it receives the ready notifications from all of the workers. However, why do we have to WAIT so long time to carry out the final allreduce operation?

The timeline readme on the github says that
`WAIT_FOR_DATA indicates time taken to wait for GPU to finish computing input to the allreduce, allgather, or broadcast operations. This happens because TensorFlow tries to smartly interleave scheduling and GPU computation. This is only applicable to situations where the Horovod operation is placed on GPU.`

Would you please explain what exactly do we have to wait for during WAIT_FOR_DATA?
In addition, the NEGOTIATE_ALLREDUCE duration is also very long and varies greatly. Does that mean that tensor computations on different GPUs may finish asynchronously? 

Much appreciated for any suggestions.

**Comment by alsrgv** [comment]
@SunnyBeike, please check recent discussion #442.

**Comment by SunnyBeike** [comment]
Thanks @alsrgv .

Another question, will the negotiation time increase linearly with the number of GPUs?
Since I only have four GPUs, I can not do such experiments.

**Comment by alsrgv** [comment]
@SunnyBeike, we don't see such an increase in practice with up to 512 GPUs scaling experiment.
