### ISSUE TITLE
OpenMPI GPUDirect: setting cuda rdma limit slowed down horovod app

### ISSUE THREAD

**Issue by LiweiPeng** [horovod/horovod#452]
I am running a machine translation (nmt) app using horovod on 3 nodes, 2 GPU/node, with GPUDirect. I am testing on how to improve the performance by tuning OpenMPI parameters.  The parameter I tried is btl_openib_cuda_rdma_limit. However, this parameter didn't work as expected when using horovod.

I tested btl_openib_cuda_rdma_limit with same mpirun parameters but using osu benchmarks (osu_latency, osu_allgatherv, etc). It works as expected: when GDR is used, the latency is lower.

When running horovod + nmt app, I set different values for this parameter (0, 4096, 30000, 1MB, 1000GB, etc). All of these values makes the application runs slower significantly (~20%). The strange thing is that even the default value 30000 (https://www.open-mpi.org/faq/?category=runcuda) slowed down the app. 

Shouldn't the default value not affect the application behavior? Can someone share some insights on this?

My environment:
- 3 nodes, 2 P100 GPU/node.
- MLX cx4 RDMA RoCE v2
- Cuda 9.2, GDR (nv_peer_memory)
- OpenMPI 3.1.1
- NCCL 2.2, IB, GDR

mpirun command line:
mpirun --machinefile mach.txt -bind-to none -map-by slot -np 6 --mca coll_tuned_use_dynamic_rules 1 --mca coll_tuned_allgatherv_algorithm 3 --mca coll_tuned_allgather_algorithm 4 -x HOROVOD_MPI_THREADS_DISABLE=1 --mca mpi_warn_on_fork false --mca btl openib,self,smcuda --mca btl_openib_cpc_include rdmacm --mca btl_openib_rroce_enable 1 --mca btl_openib_want_cuda_gdr 1 --mca btl_smcuda_use_cuda_ipc 0 --mca btl_smcuda_use_cuda_ipc_same_gpu 0 --mca btl_openib_receive_queues P,256,256::S,128,256,192,128:S,2048,1024,1008,64:S,12288,1024,1008,64:S,131072,1024,1008,64 --mca btl_openib_cuda_async_recv false -x NCCL_CHECKS_DISABLE=1 -x NCCL_IB_DISABLE=0 -x NCCL_IB_HCA=mlx5_bond_0 -x NCCL_IB_GID_INDEX=3 -x NCCL_IB_CUDA_SUPPORT=1 <command>

There are 3 machines in mach.txt, each one has 'slots=2'

**Comment by alsrgv** [comment]
@LiweiPeng, did you figure out a solution for your problem?  If not, maybe this queue setting will help: `-mca btl_openib_receive_queues P,128,32:P,2048,32:P,12288,32:P,65536,32`
