### ISSUE TITLE
Stalled Ops in Horovod_Allreduce when running on 128 nodes in TACC

### ISSUE THREAD

**Issue by kdatta** [horovod/horovod#457]
Error:
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
Stalled ops:
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_37_0 [missing ranks: 815]
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_44_0 [missing ranks: 815]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
Stalled ops:
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_37_0 [missing ranks: 815]
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_44_0 [missing ranks: 815]
I0821 01:57:42.623394 47595311335168 tf_logging.py:115] Saving checkpoint to path /work/05479/kdatta/stampede2/results/new_tf_cnn_128nodes_bs2_2018-08-21-01-37-10/model.ckpt
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
Stalled ops:
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_37_0 [missing ranks: 815]
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_44_0 [missing ranks: 815]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
Stalled ops:
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_37_0 [missing ranks: 815]
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_44_0 [missing ranks: 815]
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
Stalled ops:
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_37_0 [missing ranks: 815]
v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_44_0 [missing ranks: 815]
[proxy:0:0@c477-014.stampede2.tacc.utexas.edu] HYDT_bscu_wait_for_completion (../../tools/bootstrap/utils/bscu_wait.c:151): one of the processes terminated badly; aborting
[proxy:0:0@c477-014.stampede2.tacc.utexas.edu] HYDT_bsci_wait_for_completion (../../tools/bootstrap/src/bsci_wait.c:36): launcher returned error waiting for completion
[proxy:0:0@c477-014.stampede2.tacc.utexas.edu] HYD_pmci_wait_for_childs_completion (../../pm/pmiserv/pmip_utils.c:2002): bootstrap server returned error waiting for completion
[proxy:0:0@c477-014.stampede2.tacc.utexas.edu] main (../../pm/pmiserv/pmip.c:525): error waiting for event children completion
[mpiexec@c477-014.stampede2.tacc.utexas.edu] control_cb (../../pm/pmiserv/pmiserv_cb.c:798): connection to proxy 0 at host c477-014 failed
[mpiexec@c477-014.stampede2.tacc.utexas.edu] HYDT_dmxu_poll_wait_for_event (../../tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@c477-014.stampede2.tacc.utexas.edu] HYD_pmci_wait_for_completion (../../pm/pmiserv/pmiserv_pmci.c:501): error waiting for event

Command Line:
$ mpiexec --machinefile /work/05479/kdatta/stampede2/results/new_tf_cnn_128nodes_bs2_2018-08-21-01-37-10/host_128 -np 1024 --ppn 8 -genv OMP_NUM_THREADS 6 -genv I_MPI_PIN_DOMAIN 48:compact -genv KMP_BLOCKTIME 1 python /work/05479/kdatta/stampede2/skx-128n/Novartis/Code/MCNN/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model=$MODEL --batch_size=2 --data_format=NCHW --data_dir=$DATA_DIR --data_name=$DATANAME --use_datasets=True --num_intra_threads=6 --num_inter_threads=8 --num_epochs=20 --num_warmup_batches=5 --display_every=5 --momentum=0.9 --weight_decay=0.00005 --optimizer=momentum --distortions=False --sync_on_finish=True --device=cpu --mkl=True --summary_verbosity=1 --save_summaries_steps=10 --save_model_secs=1200 --variable_update=horovod --local_parameter_device=cpu --kmp_blocktime=1 --horovod_device=cpu --image_height=724 --image_width=724 --init_learning_rate=0.001 --train_dir=$TRAIN_DIR

Software Versions:
TensorFlow 1.9
Horovod 0.13.11
Python 2.7.13
OpenMPI v3.0.0

**Comment by tgaddair** [comment]
Hey @kdatta, looks like worker 815 may have been killed somehow.  Does this issue continue to happen around the same point over multiple runs?

**Comment by tonyreina** [comment]
Is there a way to increase the timeout to a few minutes instead of just 60 seconds?  I've got a 3D network with very large tensors and it is taking a few minutes per training step. I'm wondering if I can increase the timeout that it might get rid of this.

**Comment by alsrgv** [comment]
@tonyreina, there's no timeout at the moment, but you can set `HOROVOD_STALL_CHECK_DISABLE=1`. Would that work?

**Comment by zone21** [comment]
@kdatta did you fix it? how to fix it
@tgaddair I get the same issue and it continue to happen after finish validation in 2nd or 3rd epochs, but not the same point. like one example as below training stalled from missing ranks:4 

MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 3, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 3, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 3, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 3, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 3, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 3, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 3, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 0, 1, 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
MetricAverageCallback/HorovodAllreduce_MetricAverageCallback_acc_0 [missing ranks: 4]
Command Line:
        nohup mpirun -np 8 \
          -H 192.168.13.211:2,192.168.12.239:2,192.168.12.239:2,192.168.12.235:2\
          -mca pml ob1 \
          -mca btl ^openib \
          -bind-to none \
          -map-by slot \
          -x NCCL_DEBUG=INFO \
          -x LD_LIBRARY_PATH \
          -x NCCL_IB_CUDA_SUPPORT=1 \
          -x PATH \
          python3 $RUN_PATH/densenet_car_distr.py 2>&1 &

Software Versions:
tensorflow-gpu 1.10.1  
horovod  0.14.1
Python 3.6.5
OpenMPI 3.1.2

**Comment by alsrgv** [comment]
@zone21, if your training progresses after the validation step completes, you can disable the warning by setting `HOROVOD_STALL_CHECK_DISABLE=1`.

**Comment by zone21** [comment]
> @zone21, if your training progresses after the validation step completes, you can disable the warning by setting `HOROVOD_STALL_CHECK_DISABLE=1`.

Hi alsrgv, we continue train the model and add the setting HOROVOD_STALL_CHECK_DISABLE=1 you mention. The message do not occur in validation but occur in trainning stage instead. With below message, any suggestion?

training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv5_block16_2_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_100_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv4_block17_2_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_99_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv5_block17_1_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv4_block33_2_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_97_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_96_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv5_block17_2_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_94_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_93_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv5_block18_1_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_393_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_91_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_90_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv5_block18_2_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_88_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_87_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv5_block19_1_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_85_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_AddN_84_0 [missing ranks: 2]
training/SGD/DistributedSGD_Allreduce/HorovodAllreduce_training_SGD_gradients_conv5_block19_2_conv_convolution_grad_Conv2DBackpropFilter_0 [missing ranks: 2]

**Comment by alsrgv** [comment]
@zone21,  sorry for delayed response - do you run separate scripts for training & validation? Can you set this flag for both of them?

**Comment by kdatta** [comment]
Updating to tensorflow-1.12.0 and horovod-0.15.2 stopped the errors for me. Trying a different model on large nodes. I'll report here if I see them again.
