### ISSUE TITLE
can horovod run distributed without using mpirun

### ISSUE THREAD

**Issue by chengdianxuezi** [horovod/horovod#460]
I want to run horovod  in yarn cluster,but in yarn cluster,each instance start alone. can distributed horovod start not use mpirun?

**Comment by tgaddair** [comment]
Hey @chengdianxuezi, I don't know of any way to get around using `mpirun`, but you should be able to use Horovod on Yarn.  One option would be to wait until all instances are ready before launching your training job.  If that doesn't work for you, can you describe your specific problem in a bit more detail?
