### ISSUE TITLE
 ompi_mpi_init: ompi_rte_init failed   --> Returned "(null)" (-43) instead of "Success" (0) 

### ISSUE THREAD

**Issue by guptaraman540** [horovod/horovod#465]
Hi,
I am trying to run keras_mnsit.py example on localhost, but I'm getting following error:

*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[leo:7039] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)

Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58566,1],0]
  Exit code:    1
---------------------------------------------------------------------------------------------------------------------------------

Machine is running Ubuntu 18.04 with no GPU.
mpirun (Open MPI) 3.1.1

Can someone please help?

Thank you.

**Comment by tgaddair** [comment]
Hey @guptaraman540, can you provide the full `mpirun` command?  Also, can you create a gist with the full output log?  Thanks.

**Comment by guptaraman540** [comment]
Hi @tgaddair, Thank you for responding.
I tried following command. The same command is working on other system. Also, I'm able to successfully run sample hello_world program of open mpi between this master machine and another client machine.

mpirun -np 1 -H localhost python mpi_cloud/keras_mnsit.py

Error has occurred in hvd.init() function. It appears initialization of  ompi rte failed. 
I searched the  open-mpi code at https://github.com/open-mpi/ompi/blob/97da19f20361f2b48907f020efe31d4af887eb9c/ompi/runtime/ompi_mpi_init.c
and found  it failed while setting up RTE.

  /* Setup RTE */
    if (OMPI_SUCCESS != (ret = ompi_rte_init(NULL, NULL))) {
        error = "ompi_mpi_init: ompi_rte_init failed";
        goto error;
}

In error log:
  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)

**Comment by y-bai** [comment]
I have the same error when using the mpirun command as follows:

mpirun -np 12     
-H host1:4,host3:4,host2:4     
-bind-to none -map-by slot    
 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH     -mca pml ob1 -mca btl ^openib     python model_train_main.py

*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[host1:71142] Local abort before MPI_INIT completed completed successfully,
 but am not able to aggregate error messages, and not able to guarantee that all other processes
 were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[host1:71144] Local abort before MPI_INIT completed completed successfully,
 but am not able to aggregate error messages, and not able to guarantee that all other processes
 were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[host1:71141] Local abort before MPI_INIT completed completed successfully,
 but am not able to aggregate error messages, and not able to guarantee that all other processes
 were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[host1:71143] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[host2:61643] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[host2:61644] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[host2:61645] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[host2:61646] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[60107,1],4]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by abditag2** [comment]
Can you try using horovodrun command?

**Comment by karthikvadla** [comment]
Anyone able to resolve this? I see the same issue. 
I'm on `Ubuntu 18.04` with `openmpi -4.0.1`
My mpirun command looks as below
```
mpirun --allow-run-as-root -H localhost -np 2 --oversubscribe --report-bindings \
numactl --localalloc python3 /usr/share/doc/ngraph/examples/tensorflow_scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py \
--model=resnet50 \
--batch_size=128 \
--data_format=NCHW \
--display_every=1 \
--init_learning_rate=0.001 \
--optimizer=sgd \
--data_name=imagenet \
--num_intra_threads=20 \
--num_inter_threads=1 \
--datasets_num_private_threads=2 \
--horovod_device gpu \
--variable_update=horovod \
--num_batches=10 
```

**Comment by jakubzitny** [comment]
I have the same with both `horovodrun` and `mpiprun`.

**Comment by tgaddair** [comment]
Hey @karthikvadla and @jakubzitny, does the error also occur when you run one of the Horovod example scripts, or only when you run your custom training code?

**Comment by jakubzitny** [comment]
I was only trying it with the example code @tgaddair  - [keras_mnist.py](https://github.com/horovod/horovod/blob/master/examples/keras_mnist.py) for example.

**Comment by tgaddair** [comment]
Thanks for the response @jakubzitny.  I suspect there is an issue with the MPI configuration in your environment.  Can you try running with `horovodrun --gloo` to see if things can run without MPI?

**Comment by jakubzitny** [comment]
Can't really get install it with `gloo`. Tried the following without luck, installation finished successfully.

```
HOROVOD_WITH_GLOO=1 HOROVOD_GPU_ALLREDUCE=NCCL pip install --user --no-cache-dir horovod
```

Horovodrun with `--gloo` is returning
```
$python .local/bin/horovodrun --gloo -np 2 repos/horovod/examples/keras_mnist.py

Traceback (most recent call last):
  File ".local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/storage/praha1/home/zitnyjak/.local/lib/python3.6/site-packages/horovod/run/run.py", line 722, in run
    raise ValueError('Gloo support has not been built.  If this is not expected, ensure CMake is installed '
ValueError: Gloo support has not been built.  If this is not expected, ensure CMake is installed and reinstall Horovod with HOROVOD_WITH_GLOO=1 to debug the build error.
```

**Comment by tgaddair** [comment]
Hey @jakubzitny, do you have CMake installed?  If not, can you try `pip install cmake`?

**Comment by jakubzitny** [comment]
I do, version `3.6.1`.

**Comment by tgaddair** [comment]
That's strange, so installing Horovod did not raise an error, but running `horovodrun` did?

Are you certain that Horovod installed the `horovodrun` binary to `.local/bin`?  Is it possible you have more than one version of Horovod installed?

**Comment by oakkas** [comment]
Any resolution yet?

**Comment by Asciotti** [comment]
We bumping, this is still an issue. I am on ubuntu 18.04, torch 1.11.0, horovod 0.24.2, cuda 10.2, openmpi-4.0.7.

**Comment by lizihanov17** [comment]
Still an issue, ubuntu 18.04, torch 1.8.1, horovod 0.28.0, cuda 11.3, openmpi 4.0.7
