### ISSUE TITLE
Random hangs of Horovod in AWS DLAMI Version 13

### ISSUE THREAD

**Issue by markmp** [horovod/horovod#474]
I'm seeing random hangs using horovod/mpirun on the latest AWS DLAMU Version 13 Ubuntu:
tensorflow 1.10
horovod 0.13.11
openmpi 3.1.0
 
I'm training a resnet50 model using the preprocessed and resized imagenet data. (i.e. used both of their scripts). Cmd to mpirun is same in this AWS doc:
https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-horovod.html
E.g:
mpirun.openmpi -np 8 
--hostfile hostfile --bind-to none --map-by slot -x NCCL_DEBUG=INFO 
-x NCCL_MIN_NRINGS=4 -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib 
python aws_tf_hvd_cnn.py --batch_size=256 --num_epochs=90 --fp16 
--data_dir train --model resnet50 --log_dir results --display_every 100 --save_interval=3600

My main challenge so far is that often when I try mpirun several the of the processes won't start, and it just seems to hang. I've tried changing the hostfile to set the appropriate GPUs, but it seemingly hangs at random..maybe I'll get 3 or 4 that report in , or 5 of 8... And then sometimes it just works. I don't know the cause and it's the main thing I'm trying to figure out.

Attached is an example on their p3.8xlarge machine, trying to run with 4 GPUs. You can see that only 3 of 4 processes reported in (log attached).
[aws-tf-hvd-cnn.log](https://github.com/uber/horovod/files/2338361/aws-tf-hvd-cnn.log)

**Comment by markmp** [comment]
I was able to reproduce this error with a run on 8 GPUs. Only 7 managed to start and then hung on "Initializing Variables"...

mpirun -np 8 --hostfile hostfile --bind-to none --map-by slot -x NCCL_DEBUG=INFO -x NCCL_MIN_NRINGS=4 -x LD_LIBRARY_PATH -x PATH  -mca orte_base_help_aggregate 0 -mca pml ob1 -mca btl ^openib python aws_tf_hvd_cnn.py --batch_size=256 --num_epochs=90 --fp16 --data_dir /mnt/ram_disk/train-resized --model resnet50 --log_dir results_8xgpu_ramdisk --display_every 100 --save_interval=3600

I did some digging with nvidia-smi and ps - and found that 7 processes were able to attach and grab GPUs. There was 1 GPU that was empty..and it looks like it was process 91750 which wasn't able to get its GPU. I also attached process stack log for 91747 which I think was the GPU/rank0 one.

I ran this to get the process logs below:
gdb -p <pid> -ex "thread apply all bt" --batch

[aws-tf-hvd-cnn.fail.log](https://github.com/uber/horovod/files/2338745/aws-tf-hvd-cnn.fail.log)
[process_stack_91747.txt](https://github.com/uber/horovod/files/2338738/process_stack_91747.txt)
[process_stack_91750.txt](https://github.com/uber/horovod/files/2338739/process_stack_91750.txt)

**Comment by alsrgv** [comment]
@markmp, were you able to resolve your problem?
