### ISSUE TITLE
How to verify the examples of Horovod have applied NCCL2 and openmpi?

### ISSUE THREAD

**Issue by thhsiao** [horovod/horovod#491]
My environments are:

Ubuntu 1604
CUDA 8.0
Python 2.7
Tensorflow 1.8.0
libnccl2=2.2.13-1+cuda8.0 libnccl-dev=2.2.13-1+cuda8.0
openmpi-3.1.2

I have successful install NCCL2, openmpi and horovod; moreover,  I executed tensorflow_mnist.py in /examples, how can I verify this program has applied NCCL2 and openmpi?

B.R.
TH Hsiao

**Comment by tgaddair** [comment]
Hey @thhsiao, if you ran with `mpirun` and and two or more processes, and everything worked, then your openmpi setup should be fine.  As for NCCL, you can try running with `-x NCCL_DEBUG=INFO` and look for NCCL output.  It should tell you that it's running.

**Comment by thhsiao** [comment]
Hi tgaddair,
Thanks a lot, I have got these 2 information.

**Comment by thhsiao** [comment]
Another questions:
When I run tensorflow_mnist.py on 2 GPUs/2 processes environments, the link between 2 GPUs is NVLink; however, the utilization.gpu (nvidia-smi) only 47~50%.
1. What are the reasons that utilization.gpu cannot approach to 99%? the bottleneck is NVLink, NCCL2 or GPU?
2. The displayed message: NCCL_SINGLE_RING_THRESHOLD=262144, what is the meaning of this number? can I change "NCCL_SINGLE_RING_THRESHOLD" for expending the bandwidth of NCCL2?
3. The displayed message: "Using NCCL Low-latency algorithm for sizes below 16384" is the payload size of NCCL2? Can I change this size for expending throughput?

My both GPUs are Tesla V100-SXM2-16GB, when I executed  mpirun -np 2 -H localhost:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python tensorflow_mnist.py

It display messages:
m160:58917:59056 [0] INFO NET : Using interface eth0:10.244.13.31<0>
m160:58917:59056 [0] INFO NET/IB : Using interface eth0 for sideband communication
m160:58917:59056 [0] INFO Using internal Network Socket
m160:58917:59056 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
m160:58917:59056 [0] INFO NET : Using interface eth0:10.244.13.31<0>
m160:58917:59056 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.2.13+cuda8.0
m160:58918:59053 [1] INFO NET : Using interface eth0:10.244.13.31<0>
m160:58918:59053 [1] INFO NET/IB : Using interface eth0 for sideband communication
m160:58918:59053 [1] INFO Using internal Network Socket
m160:58918:59053 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
m160:58917:59056 [0] INFO comm 0x7f9828277570 rank 0 nranks 2
m160:58918:59053 [1] INFO comm 0x7f8458277350 rank 1 nranks 2
m160:58918:59053 [1] INFO NET : Using interface eth0:10.244.13.31<0>
m160:58918:59053 [1] INFO NET/Socket : 1 interfaces found
m160:58917:59056 [0] INFO Using 256 threads
m160:58917:59056 [0] INFO Min Comp Cap 7
m160:58917:59056 [0] INFO NCCL_SINGLE_RING_THRESHOLD=262144
m160:58917:59056 [0] INFO Ring 00 :    0   1

The nvidia-smi run on another terminal:
nvidia-smi --query-gpu=timestamp, name, pci.bus_id, utilization.gpu, utilization.memory, memory.free, memory.used --format=csv -l 5

timestamp,      name,                              pci.bus_id           utilization.gpu, utilization.memory, memory.free, memory.used
13:48:01.812, Tesla V100-SXM2-16GB, 00000000:06:00.0, 47 %,            56 %,                    15288 MiB,   864 MiB    
13:48:01.813, Tesla V100-SXM2-16GB, 00000000:86:00.0, 49 %,            58 %,                    15032 MiB,   1120 MiB   
13:48:06.814, Tesla V100-SXM2-16GB, 00000000:06:00.0, 49 %,            58 %,                    15288 MiB,   864 MiB    
13:48:06.816, Tesla V100-SXM2-16GB, 00000000:86:00.0, 48 %,            57 %,                    15032 MiB,   1120 MiB

**Comment by tgaddair** [comment]
It looks like you've disabled infiniband.  Possibly you're network bound, and cannot fully utilize GPU resources due to network bottleneck.

**Comment by alsrgv** [comment]
@thhsiao, it should be noted that MNIST example is an extremely small model that can be trained on laptop w/o GPU.  In order to see scaling/utilization, you can try adding Horovod to one of the real models you're training or [running a benchmark](https://github.com/uber/horovod/blob/master/docs/benchmarks.md).
