### ISSUE TITLE
ORTE does not know how to route a message to the specified daemon

### ISSUE THREAD

**Issue by vilmara** [horovod/horovod#504]
Hi, I am trying to run my custom script in multi node mode using horovod, but I got the below error:

root@64a93cf4440e:/workspace/chest-x-ray# `mpirun -np 8 -H 192.168.11.1:4,192.168.11.2:4 -x NCCL_IB_DISABLE=0 -x NCCL_IB_CUDA_SUPPORT=1 -x NCCL_SOCKET_IFNAME=ib0 -x NCCL_D                                                   EBUG=INFO --bind-to none --map-by slot --mca plm_rsh_args "-p 50000" python multiclass_horovod_optimizers.py`
ssh: connect to host 192.168.11.1 port 50000: Connection refused

ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).

ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   64a93cf4440e
  target node:  192.168.11.2

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.

So, I changed mpa option to --mca routed=direct, but now the system is hanging
root@5781e7c91f6f:/workspace/chest-x-ray# `mpirun -np 8 -H 192.168.11.1:4,192.168.11.2:4 -x NCCL_IB_DISABLE=0 -x NCCL_IB_CUDA_SUPPORT=1 -x NCCL_SOCKET_IFNAME=ib0 -x NCCL_D                                                   EBUG=INFO --bind-to none --map-by slot --mca routed=direct "-p 50000" python multiclass_horovod_optimizers.py`
Warning: Permanently added '192.168.11.1' (ECDSA) to the list of known hosts.
Warning: Permanently added '192.168.11.2' (ECDSA) to the list of known hosts.

P.S.: I have run the tensorflow benchmarks in distributed mode using horovod from comman line without problem, but getting the above errors when using my own code 
Some tips?

**Comment by tgaddair** [comment]
Hey @vilmara, can you verify that when you ran the tensorflow benchmarks it worked with the same parameters to `mpirun`?  It looks like there's an issue with the ssh server on 192.168.11.1, can you verify that it's running on that machine and listening on that port?

**Comment by vilmara** [comment]
hi @tgaddair, yes, it worked with the same parameters to mpirun using tensorflow benchmarks. 

The problem is with my code. As recommended by horovod, I changed the parameter from --mca plm_rsh_args to --mca routed=direct, but now the system hangs, see below:

root@5781e7c91f6f:/workspace/chest-x-ray# `mpirun -np 8 -H 192.168.11.1:4,192.168.11.2:4 -x NCCL_IB_DISABLE=0 -x NCCL_IB_CUDA_SUPPORT=1 -x NCCL_SOCKET_IFNAME=ib0 -x NCCL_D EBUG=INFO --bind-to none --map-by slot --mca routed=direct "-p 50000" python multiclass_horovod_optimizers.py`
 Warning: Permanently added '192.168.11.1' (ECDSA) to the list of known hosts.
 Warning: Permanently added '192.168.11.2' (ECDSA) to the list of known hosts.

**Comment by vilmara** [comment]
hi @tgaddair, yes it works when I run the tensorflow benchmarks with the same parameters to mpirun. As horovod recommended, I changed the parameter from `--mca plm_rsh_args` to `--mca routed=direct`

root@5781e7c91f6f:/workspace/chest-x-ray# mpirun -np 8 -H 192.168.11.1:4,192.168.11.2:4 -x NCCL_IB_DISABLE=0 -x NCCL_IB_CUDA_SUPPORT=1 -x NCCL_SOCKET_IFNAME=ib0 -x NCCL_D EBUG=INFO --bind-to none --map-by slot --mca routed=direct "-p 50000" python multiclass_horovod_optimizers.py
 Warning: Permanently added '192.168.11.1' (ECDSA) to the list of known hosts.
 Warning: Permanently added '192.168.11.2' (ECDSA) to the list of known hosts.

**Comment by tgaddair** [comment]
Hi @vilmara, it is surprising that you're able to run this command successfully on the Horovod examples but not your own code.  This looks a lot like an MPI / environment issue.

I noticed your command has `-x NCCL_D EBUG=INFO` with a space in it.  Is that how it was run on the command line?

I think you should be able to run without specifying `-mca routed=direct`.  It may be that your networking setup doesn't support direct routing.  

Can you try running without `-mca routed=direct` and with `-mca plm_rsh_args "-p 50000 -vvv"` and share the output in a gist?

**Comment by alsrgv** [comment]
@vilmara, we have observed this issue internally and were able to resolve by upgrading to Open MPI 3.1.2.

**Comment by scotthuang1989** [comment]
@alsrgv  I upgrade Open MPI from 3.0.0 to 4.0.0, it works.  Do you have any luck identify the root cause of this issue?

**Comment by alsrgv** [comment]
@scotthuang1989, no - we just recommend installing Open MPI 3.1.2 or 4.0.0 at this point.

**Comment by Geof23** [comment]
@vilmara, have you resolved this issue?

**Comment by vilmara** [comment]
Hi @Geof23, yes it was solved, closing the issue

**Comment by konnase** [comment]
> Hi @Geof23, yes it was solved, closing the issue
Could you please show us how you solved this problem?
