### ISSUE TITLE
Synchronous or asynchronous？

### ISSUE THREAD

**Issue by NO2-yh** [horovod/horovod#508]
Horovod is Synchronous or asynchronous？

**Comment by Kevinwenya** [comment]
I think it just supports Synchronous SGD

**Comment by tgaddair** [comment]
Hey @yh673025667, though gradients can be submitted for reduction asynchronously, we always synchronize the individual workers at each mini batch. Due to the way the allreduce works, it wouldn't make sense to allreduce, say, only some of the ranks but not others.
