### ISSUE TITLE
Reading multiple files

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#509]
In the examples, each rank reads from a different file (for 2 ranks, MNIST-0 and MNIST-1).
Why is this done, why not read from a single file for all gpus?
If the file is very big say 10 GB and we want to operate on 8 gpus, then making 8 copies would  require 80 GB which is massive.

**Comment by tgaddair** [comment]
Hey @UditGupta10, it's just to simplify the examples and make them easy to use.  Normally, you wouldn't do data prep in your training code, you'd handle that separately.  But we wanted the training examples to be self-contained.  If you want to see an example where things are setup more similar to how it would be done in practice, take a look at [keras_imagenet_resnet50.py](https://github.com/uber/horovod/blob/master/examples/keras_imagenet_resnet50.py).

**Comment by UditGupta10** [comment]
Ok. What if in the below example (tensorflow_mnist) instead of mnist-data-0 and mnist-data-1 we simply used mnist-data only. If we use only 1 file, then can it still be read by multiple gpus ?
The reason why i am asking this is if i am using say 16 gpus then it shouldn't need 16 different copies i.e. from mnist-data-0 to mnist-data-15.

**Comment by tgaddair** [comment]
If you replaced `read_data_sets('MNIST-data-%d' % hvd.rank())` with `read_data_sets('MNIST-data')`, then you would have multiple processes attempting to write the same file at once, which could result in a corrupted file.

If you were to call `read_data_sets('MNIST-data')` in a separate _process_, then run your Horovod training job _after_ the data has been downloaded, then yes, that file could be read by all processes on the system.  That's what is done in the example I linked you to in my previous response, [keras_imagenet_resnet50.py](https://github.com/uber/horovod/blob/master/examples/keras_imagenet_resnet50.py), where you'll note that all processes are reading from the same files.

**Comment by tgaddair** [comment]
Yes.  You can think of `hvd.rank()` like a process ID.  Every process you run has a unique rank that starts from 0 and goes up based on the number of processes.  The purpose of putting rank in the filename in the example is to ensure that every process is writing and reading its own unique file.
