### ISSUE TITLE
Q: Running horovod on single machine with multiple GPUs?

### ISSUE THREAD

**Issue by Snapple49** [horovod/horovod#518]
I have some questions about horovod and how it improves the performance in TF. My background in these topics is limited, I am new to ML, TF and in general how performance is looked at in machine learning and training.

1. Will horovod improve performance in a single machine multiple GPU setup? I've been reading about horovod and MPI for a bit but I have not found any conclusive answers, is there any straight yes/no answer or is it dependant on more than just the resources?

2. What exactly is it that horovod improves upon, so that I might read more about this and get a better understanding of how things work without it and what it brings? It makes sense that it improves the network utilization with the communication model that it adapts (ring-reduce rather than parameter server if I understand correctly?), but since I lack knowledge in what happens during training it's hard to understand what implications this has on a single machine setting. 

So, I'm very generic, but mainly what I would like is either an indication whether horovod is useful for single machine, and/or pointers on good resources to read about to understand this better.

**Comment by alsrgv** [comment]
@Snapple49, Horovod does allow you to train models on a single machine with multiple GPUs faster.  It will launch one TensorFlow process per GPU, so your TensorFlow script can remain agnostic of the fact that you have multiple GPUs.  I.e., you do not need to use [towers](https://datascience.stackexchange.com/questions/16361/what-is-a-tower).

To get more background about Horovod, I'll direct you to our [arXiv paper](https://arxiv.org/abs/1802.057990) and [blog post](https://eng.uber.com/horovod/).

**Comment by Snapple49** [comment]
@alsrgv Thank you! I appreciate the direct answer, although I'll need to research a bit more about towers. Is that the main benefit in this scenario or are there other things I can look at as well? 

I've read your blog post a few times already, and it does explain some things but it still left me with some questions, hence my post here. A lot of the talk about the network optimizations thanks to MPI is not clear to me, for example when you mention the baidu article and how the ring-allreduce algorithm, does bandwidth and network here also include interconnects between GPUs on a single machine or is it more aimed at network between machines? I can see how between machine networks would perform better under this algorithm but I imagine you would need quite a large amount of data to pass around to saturate the bandwidth between local GPUs? Or are there other factors involved?

I'll try to read some more about these things and I appreciate any further help/pointers!

**Comment by alsrgv** [comment]
@Snapple49, the usability of Horovod and having the same API across various flavors of TensorFlow (tf.Session, Estimator), Keras and PyTorch is one of the main benefits.  Nice APIs are make-or-break for ML engineers to start scaling their model. Having a good scaling efficiency is nice as well :-)

Bandwidth saturation usually happens on network layer rather than inside the server, however, it's possible to have some silly situations inside the server, too.  For instance, if GPU P2P communication or access to shared memory are not available, performance would greatly suffer.

**Comment by Snapple49** [comment]
@alsrgv Thank you again! I see, I can definitely see the niceness of good usability. 

Since I'm mainly interested in performance I was looking at the benchmarks you did for the paper with tf-cnn-benchmarks, and I tried running the same benchmark with mpi and horovod versus without mpi and replicated/parameter server to see the throughput with various amounts of GPU. I thought that this would give some indication whether horovod improves the performance, and interestingly I had a higher throughput with horovod at 10 GPUs, but higher without _horovod_ (using replicated) on fewer GPUs (4 or less).

So by the looks of it, there is some performance boost here but it was a bit difficult to understand why. Maybe you worked some magic :) Either way thanks for your time, at least I have a better idea what to look into now!
