### ISSUE TITLE
rank:0 is always failed

### ISSUE THREAD

**Issue by zshy1205** [horovod/horovod#525]
I try change one TF code with horovod, but when I add the horovod in this code and take a try use only one GPU .I find that it was always failed.
`with tf.train.MonitoredTrainingSession(checkpoint_dir=checkpoint_dir,
                                         save_checkpoint_secs = 3600,
                                         hooks=hooks,
                                         config=config) as sess:
    try:
      for var in tf.trainable_variables():
        print(var.name, var.shape.as_list())
      log("###########1")
      log(str(hvd.rank()) + str(sess.run('model/inference/embedding:0')[0][:10]))
      log("###########2")`
the parameter 'model/inference/embedding:0' is in the trainable_variables(). But It only run at log("#########1"). the process will be stuck in the sess.run('model/inference/embedding:0')[0][:10]).
the out is :
`INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./logs-tacotron_horovod/model.ckpt-13
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
(u'model/inference/embedding:0', [149, 512])
(u'model/inference/encoder/conv_0/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/encoder/conv_0/conv1d/bias:0', [512])
(u'model/inference/encoder/conv_0/batch_normalization/gamma:0', [512])
(u'model/inference/encoder/conv_0/batch_normalization/beta:0', [512])
(u'model/inference/encoder/conv_1/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/encoder/conv_1/conv1d/bias:0', [512])
(u'model/inference/encoder/conv_1/batch_normalization/gamma:0', [512])
(u'model/inference/encoder/conv_1/batch_normalization/beta:0', [512])
(u'model/inference/encoder/conv_2/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/encoder/conv_2/conv1d/bias:0', [512])
(u'model/inference/encoder/conv_2/batch_normalization/gamma:0', [512])
(u'model/inference/encoder/conv_2/batch_normalization/beta:0', [512])
(u'model/inference/encoder/encoder_lstm/fw/lstm_cell/kernel:0', [768, 1024])
(u'model/inference/encoder/encoder_lstm/fw/lstm_cell/bias:0', [1024])
(u'model/inference/encoder/encoder_lstm/bw/lstm_cell/kernel:0', [768, 1024])
(u'model/inference/encoder/encoder_lstm/bw/lstm_cell/bias:0', [1024])
(u'model/inference/memory_layer/kernel:0', [512, 128])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/decoder_prenet_wrapper/decoder_prenet/dense_1/kernel:0', [592, 256])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/decoder_prenet_wrapper/decoder_prenet/dense_1/bias:0', [256])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/decoder_prenet_wrapper/decoder_prenet/dense_2/kernel:0', [256, 128])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/decoder_prenet_wrapper/decoder_prenet/dense_2/bias:0', [128])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/decoder_prenet_wrapper/lstm_cell/kernel:0', [256, 512])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/decoder_prenet_wrapper/lstm_cell/bias:0', [512])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/location_sensitive_attention/location_conv/kernel:0', [7, 1, 20])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/location_sensitive_attention/location_layer/kernel:0', [20, 128])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/location_sensitive_attention/query_layer/kernel:0', [128, 128])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_0/concat_output_and_attention_wrapper/attention_wrapper/location_sensitive_attention/attention_v:0', [128])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_1/lstm_cell/kernel:0', [1664, 4096])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_1/lstm_cell/bias:0', [4096])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/kernel:0', [2048, 4096])
(u'model/inference/decoder/output_projection_wrapper/multi_rnn_cell/cell_2/lstm_cell/bias:0', [4096])
(u'model/inference/decoder/output_projection_wrapper/kernel:0', [1024, 400])
(u'model/inference/decoder/output_projection_wrapper/bias:0', [400])
(u'model/inference/decoder_postnet/postnet_conv_0/conv1d/kernel:0', [5, 80, 512])
(u'model/inference/decoder_postnet/postnet_conv_0/conv1d/bias:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_0/batch_normalization/gamma:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_0/batch_normalization/beta:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_1/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/decoder_postnet/postnet_conv_1/conv1d/bias:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_1/batch_normalization/gamma:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_1/batch_normalization/beta:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_2/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/decoder_postnet/postnet_conv_2/conv1d/bias:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_2/batch_normalization/gamma:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_2/batch_normalization/beta:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_3/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/decoder_postnet/postnet_conv_3/conv1d/bias:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_3/batch_normalization/gamma:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_3/batch_normalization/beta:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_4/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/decoder_postnet/postnet_conv_4/conv1d/bias:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_4/batch_normalization/gamma:0', [512])
(u'model/inference/decoder_postnet/postnet_conv_4/batch_normalization/beta:0', [512])
(u'model/inference/dense/kernel:0', [512, 80])
(u'model/inference/dense/bias:0', [80])
(u'model/inference/expand/conv_0/conv1d/kernel:0', [5, 80, 512])
(u'model/inference/expand/conv_0/conv1d/bias:0', [512])
(u'model/inference/expand/conv_0/batch_normalization/gamma:0', [512])
(u'model/inference/expand/conv_0/batch_normalization/beta:0', [512])
(u'model/inference/expand/conv_1/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/expand/conv_1/conv1d/bias:0', [512])
(u'model/inference/expand/conv_1/batch_normalization/gamma:0', [512])
(u'model/inference/expand/conv_1/batch_normalization/beta:0', [512])
(u'model/inference/expand/conv_2/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/expand/conv_2/conv1d/bias:0', [512])
(u'model/inference/expand/conv_2/batch_normalization/gamma:0', [512])
(u'model/inference/expand/conv_2/batch_normalization/beta:0', [512])
(u'model/inference/expand/conv_3/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/expand/conv_3/conv1d/bias:0', [512])
(u'model/inference/expand/conv_3/batch_normalization/gamma:0', [512])
(u'model/inference/expand/conv_3/batch_normalization/beta:0', [512])
(u'model/inference/expand/conv_4/conv1d/kernel:0', [5, 512, 512])
(u'model/inference/expand/conv_4/conv1d/bias:0', [512])
(u'model/inference/expand/conv_4/batch_normalization/gamma:0', [512])
(u'model/inference/expand/conv_4/batch_normalization/beta:0', [512])
(u'model/inference/expand/encoder_lstm/fw/lstm_cell/kernel:0', [768, 1024])
(u'model/inference/expand/encoder_lstm/fw/lstm_cell/bias:0', [1024])
(u'model/inference/expand/encoder_lstm/bw/lstm_cell/kernel:0', [768, 1024])
(u'model/inference/expand/encoder_lstm/bw/lstm_cell/bias:0', [1024])
(u'model/inference/dense_1/kernel:0', [512, 1025])
(u'model/inference/dense_1/bias:0', [1025])
############

`

**Comment by zshy1205** [comment]
why it can not do this code: sess.run('model/inference/embedding:0')

**Comment by alsrgv** [comment]
@zshy1205, is there some small piece of code that reproduces your problem that you could share?
