### ISSUE TITLE
one rank can not be ready

### ISSUE THREAD

**Issue by lxl910915** [horovod/horovod#530]
We start 7 workers, and the workers restore from a checkpoint. They hang with log:
Stalled ops: HorovodBroadcast_InceptionV3_Logits_Conv2d_1c_1x1_weights_0 [ready ranks: 5, 6, 3, 1, 4, 0]。

The log says rank 2 is not ready, _but the process of rank 2 works well_.

What's more, Stalled ops are all HorovodBroadcast variables, such as:

HorovodBroadcast_InceptionV3_AuxLogits_Conv2d_2a_5x5_BatchNorm_moving_variance_0 [ready ranks: 5, 6, 3, 1, 4, 0], 
HorovodBroadcast_InceptionV3_AuxLogits_Conv2d_2a_5x5_weights_0 [ready ranks: 5, 6, 3, 1, 4, 0], 
HorovodBroadcast_InceptionV3_Mixed_7c_Branch_2_Conv2d_0d_3x1_BatchNorm_moving_variance_0 [ready ranks: 5, 6, 3, 1, 4, 0], 
HorovodBroadcast_InceptionV3_Mixed_7c_Branch_2_Conv2d_0d_3x1_BatchNorm_moving_mean_0 [ready ranks: 5, 6, 3, 1, 4, 0], 
HorovodBroadcast_InceptionV3_Mixed_7c_Branch_2_Conv2d_0b_3x3_BatchNorm_moving_variance_0 [ready ranks: 5, 6, 3, 1, 4, 0], 

From other log, we find other ranks loged "Found device 0 with properties ...  pciBusID:...", "tensorflow:Running local_init_op." and "tensorflow:Done running local_init_op.". But rank 2 not.

Fri Sep 28 11:14:00 2018[1,5]<stderr>:INFO:tensorflow:Running local_init_op.
Fri Sep 28 11:14:00 2018[1,5]<stderr>:INFO:tensorflow:Done running local_init_op.
Fri Sep 28 11:14:00 2018[1,3]<stderr>:INFO:tensorflow:Running local_init_op.
Fri Sep 28 11:14:00 2018[1,1]<stderr>:INFO:tensorflow:Running local_init_op.
....

**Comment by lxl910915** [comment]
It we start 7 workers on one host, it works well.

**Comment by alsrgv** [comment]
@lxl910915, sorry for the delayed response.  Have you resolved the issue?  If not, is it possible that there's HW issue with GPU on rank 2?  Also, it may be helpful to upgrade Horovod to latest version 0.15.0 in case you're hitting a bug that we've fixed.
