### ISSUE TITLE
horovod + tensorflow on AMD MI25 GPU 

### ISSUE THREAD

**Issue by computingdolas** [horovod/horovod#531]
Guys I tried running Tensorflow + Horovod on AMD MI25 GPU node. I got this very strange error Cam somebody help me with this : 

mpirun --allow-run-as-root -bind-to none -map-by ppr:4:node -np 4 python benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod
TensorFlow:  1.8
Model:       resnet101
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  256 global
             64 per device
Num batches: 100
Num epochs:  0.02
Devices:     ['horovod/gpu:0', 'horovod/gpu:1', 'horovod/gpu:2', 'horovod/gpu:3']
Data format: NCHW
Layout optimizer: False
Optimizer:   sgd
Variables:   horovod
==========
TensorFlow:  1.8
Model:       resnet101
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  256 global
             64 per device
Num batches: 100
Num epochs:  0.02
Devices:     ['horovod/gpu:0', 'horovod/gpu:1', 'horovod/gpu:2', 'horovod/gpu:3']
Data format: NCHW
Layout optimizer: False
Optimizer:   sgd
Variables:   horovod
==========
TensorFlow:  1.8
Model:       resnet101
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  256 global
             64 per device
Num batches: 100
Num epochs:  0.02
Devices:     ['horovod/gpu:0', 'horovod/gpu:1', 'horovod/gpu:2', 'horovod/gpu:3']
Data format: NCHW
Layout optimizer: False
Optimizer:   sgd
Variables:   horovod
==========
TensorFlow:  1.8
Model:       resnet101
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  256 global
             64 per device
Num batches: 100
Num epochs:  0.02
Devices:     ['horovod/gpu:0', 'horovod/gpu:1', 'horovod/gpu:2', 'horovod/gpu:3']
Data format: NCHW
Layout optimizer: False
Optimizer:   sgd
Variables:   horovod
Generating model
==========
Generating model
Generating model
Generating model
W0928 10:11:20.759840 140560082335488 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1608: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W0928 10:11:20.848386 140207099684608 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1608: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W0928 10:11:20.963244 139647808390912 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1608: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
W0928 10:11:21.017491 140253541791488 tf_logging.py:125] From /root/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py:1608: __init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-09-28 10:11:22.697062: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-28 10:11:22.710228: W tensorflow/stream_executor/rocm/rocm_driver.cc:404] creating context when one is currently active; existing: 0x7f8399eab700
2018-09-28 10:11:22.710571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1451] Found device 0 with properties:
name: Device 6860
AMDGPU ISA: gfx900
memoryClockRate (GHz) 1.5
pciBusID 0000:44:00.0
Total memory: 15.98GiB
Free memory: 15.73GiB
2018-09-28 10:11:22.710590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 2
2018-09-28 10:11:22.710609: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-28 10:11:22.710615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      2
2018-09-28 10:11:22.710621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 2:   N
2018-09-28 10:11:22.710674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15306 MB memory) -> physical GPU (device: 2, name: Device 6860, pci bus id: 0000:44:00.0)
2018-09-28 10:11:22.823046: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-28 10:11:22.835726: W tensorflow/stream_executor/rocm/rocm_driver.cc:404] creating context when one is currently active; existing: 0x7fd6663bc710
2018-09-28 10:11:22.836367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1451] Found device 0 with properties:
name: Device 6860
AMDGPU ISA: gfx900
memoryClockRate (GHz) 1.5
pciBusID 0000:06:00.0
Total memory: 15.98GiB
Free memory: 15.73GiB
2018-09-28 10:11:22.836388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 0
2018-09-28 10:11:22.836414: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-28 10:11:22.836422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      0
2018-09-28 10:11:22.836428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 0:   N
2018-09-28 10:11:22.836467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15306 MB memory) -> physical GPU (device: 0, name: Device 6860, pci bus id: 0000:06:00.0)
2018-09-28 10:11:22.938830: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-28 10:11:22.952909: W tensorflow/stream_executor/rocm/rocm_driver.cc:404] creating context when one is currently active; existing: 0x7f017bbd9480
2018-09-28 10:11:22.953213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1451] Found device 0 with properties:
name: Device 6860
AMDGPU ISA: gfx900
memoryClockRate (GHz) 1.5
pciBusID 0000:63:00.0
Total memory: 15.98GiB
Free memory: 15.73GiB
2018-09-28 10:11:22.953232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 3
2018-09-28 10:11:22.953257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-28 10:11:22.953265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      3
2018-09-28 10:11:22.953271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 3:   N
2018-09-28 10:11:22.953322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15306 MB memory) -> physical GPU (device: 3, name: Device 6860, pci bus id: 0000:63:00.0)
2018-09-28 10:11:23.322574: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-09-28 10:11:23.339341: W tensorflow/stream_executor/rocm/rocm_driver.cc:404] creating context when one is currently active; existing: 0x7f8e5b1d6c20
2018-09-28 10:11:23.339684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1451] Found device 0 with properties:
name: Device 6860
AMDGPU ISA: gfx900
memoryClockRate (GHz) 1.5
pciBusID 0000:23:00.0
Total memory: 15.98GiB
Free memory: 15.73GiB
2018-09-28 10:11:23.339703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1562] Adding visible gpu devices: 1
2018-09-28 10:11:23.339726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:989] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-28 10:11:23.339734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:995]      1
2018-09-28 10:11:23.339739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1008] 1:   N
2018-09-28 10:11:23.339778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1124] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15306 MB memory) -> physical GPU (device: 1, name: Device 6860, pci bus id: 0000:23:00.0)
I0928 10:11:24.930931 140207099684608 tf_logging.py:115] Running local_init_op.
I0928 10:11:25.181705 140560082335488 tf_logging.py:115] Running local_init_op.
I0928 10:11:25.393335 139647808390912 tf_logging.py:115] Running local_init_op.
I0928 10:11:25.531301 140207099684608 tf_logging.py:115] Done running local_init_op.
I0928 10:11:25.745073 140560082335488 tf_logging.py:115] Done running local_init_op.
I0928 10:11:26.014358 139647808390912 tf_logging.py:115] Done running local_init_op.
I0928 10:11:26.104157 140253541791488 tf_logging.py:115] Running local_init_op.
I0928 10:11:26.674724 140253541791488 tf_logging.py:115] Done running local_init_op.
[P47-01:57134] Read -1, expected 18816, errno = 14
[P47-01:57132] Read -1, expected 18816, errno = 14
[P47-01:57133] Read -1, expected 18816, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 294912, errno = 14
[P47-01:57134] Read -1, expected 294912, errno = 14
[P47-01:57133] Read -1, expected 294912, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 262144, errno = 14
[P47-01:57134] Read -1, expected 262144, errno = 14
[P47-01:57132] Read -1, expected 262144, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57133] Read -1, expected 131072, errno = 14
[P47-01:57134] Read -1, expected 131072, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57132] Read -1, expected 8192, errno = 14
[P47-01:57134] Read -1, expected 8192, errno = 14
[P47-01:57133] Read -1, expected 8192, errno = 14

**Comment by alsrgv** [comment]
@computingdolas, just to confirm - what flags did you install Horovod with?

**Comment by computingdolas** [comment]
I installed openmpi and then did pip install Horovod --user. Did not use RCCL. What do you guys recommend ?

**Comment by alsrgv** [comment]
@computingdolas, unfortunately, we don't have any AMD GPUs to try reproducing the issue.  Ignoring the read errors, does training actually proceeds?

**Comment by witeko** [comment]
@computingdolas You should try the "hipped" version of horovod: https://github.com/ROCmSoftwarePlatform/horovod

**Comment by computingdolas** [comment]
@witeko 👍 Thank you. Looks promising .. Do we have any performance results ?

Would be interested too.

**Comment by 401qingkong** [comment]
@computingdolas @witeko Have you ever tried to run pytorch with horovod  on AMD GPUs?

**Comment by boniek83** [comment]
Anybody got guide how to run horovod with AMD gpus?
