### ISSUE TITLE
ImportError: Extension horovod.tensorflow has not been built

### ISSUE THREAD

**Issue by summer2rain** [horovod/horovod#551]
When I execute the command      python -c "import horovod.tensorflow as hvd"  , I have encountered the above problem, how can I solve it?

My install command:
HOROVOD_WITH_TENSORFLOW=1 HOROVOD_GPU_ALLREDUCE=MPI HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI HOROVOD_CUDA_HOME=/usr/local/cuda/cuda-9.1/  python setup.py install

**Comment by tgaddair** [comment]
Hey @summer2rain, can you try reinstalling and pasting the full log into a gist?  Looks like something failed to link during installation.

**Comment by summer2rain** [comment]
Sorry, I have a problem with the description, I found that I encountered problems when executing the command  (python -c "import horovod.tensorflow as hvd") in the source code directory. When in other directories, executing the command will encounter the following problems.

tensorflow.python.framework.errors_impl.NotFoundError: /home/me/miniconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeENS_11StringPieceE

--------------------------------------------------------------------------------------------------------
ldd  /home/me/miniconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so
        linux-vdso.so.1 =>  (0x00007fff9a1fd000)
        libpython2.7.so.1.0 => /home/me/miniconda2/lib/libpython2.7.so.1.0 (0x00007f49fa287000)
        libmpi_cxx.so.1 => /home/me/software/openmpi-1.10.2/install_bin/lib/libmpi_cxx.so.1 (0x00007f49fa06c000)
        libmpi.so.12 => /home/me/software/openmpi-1.10.2/install_bin/lib/libmpi.so.12 (0x00007f49f9d93000)
        libtensorflow_framework.so => /home/me/lib/libtensorflow_framework.so (0x00007f49f9071000)
        libstdc++.so.6 => /home/me/miniconda2/lib/libstdc++.so.6 (0x00007f49f8f2f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f49f8c21000)
        libgcc_s.so.1 => /home/me/miniconda2/lib/libgcc_s.so.1 (0x00007f49f8c0c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f49f89ef000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f49f8622000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f49f841e000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f49f821a000)
        libopen-rte.so.12 => /home/me/software/openmpi-1.10.2/install_bin/lib/libopen-rte.so.12 (0x00007f49f7f9e000)
        libopen-pal.so.13 => /home/me/software/openmpi-1.10.2/install_bin/lib/libopen-pal.so.13 (0x00007f49f7cc0000)
        libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f49f7ab3000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f49f78ab000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f49fa876000)

**Comment by alsrgv** [comment]
@summer2rain, seems like you have one TensorFlow installed in `/home/me/lib/libtensorflow_framework.so` and potentially other installed in Miniconda environment.  If that's the case, can you uninstall redundant copies of TensorFlow?

**Comment by summer2rain** [comment]
@alsrgv  There is only one libtensorflow_framework.so.
/home/me/lib/libtensorflow_framework.so -> /home/me/miniconda2/lib/python2.7/site-packages/tensorflow/libtensorflow_framework.so

I want to ask, is the reason for the program error because my glibc is too old?

**Comment by alsrgv** [comment]
@summer2rain, could it be that you upgraded TensorFlow after installing Horovod?

**Comment by xixiaoyao** [comment]
> @summer2rain, could it be that you upgraded TensorFlow after installing Horovod?

Yes, so how to solve it? I have tried to reinstall horovod but it doesn't work...

**Comment by alsrgv** [comment]
@xixiaoyao, can you try reinstalling it with `--no-cache-dir` option?  If it installs very quickly, it uses previous cached build which was built against an older version of TensorFlow.

**Comment by stonephoenix** [comment]
If anyone stilling looking for a solution....
In my case, the reason is missing multiprocessing libs, such as mpich. Download mpich and add the bin path to $PATH and lib path to $LD_LIBRARY_PATH solves the problem.

**Comment by daliel** [comment]
my env:
Ubuntu 18.04
python 3.6.9
cuda 10.2
tensorflow 1.14.1
openmpi 3.1.6 intalled to /usr/local/
horovod 0.24.3

```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-10.2/bin:/usr/local/bin
$ echo $LD_LIBRARY_PATH
/usr/local/lib:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64:/usr/local/opencv/lib
```
```
$ printenv | grep HOROVOD
HOROVOD_WITH_PYTORCH=0
HOROVOD_GPU_OPERATIONS=MPI
HOROVOD_GPU_ALLREDUCE=MPI
HOROVOD_WITHOUT_GLOO=1
HOROVOD_WITHOUT_PYTORCH=1
HOROVOD_GPU_BROADCAST=MPI
HOROVOD_WITH_TENSORFLOW=1
HOROVOD_CUDA_HOME=/usr/local/cuda-10.2/
HOROVOD_GPU_ALLGATHER=MPI
```

horovod install command:
`sudo python3 -m pip install -U --no-cache-dir git+https://github.com/horovod/horovod.git@master`

try run:
`$ mpirun -np 1 -H localhost:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO  -mca pml ob1 -mca btl ^openib  python3 -c "import tensorflow as tf;import horovod.tensorflow as hvd"`
output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/horovod/tensorflow/__init__.py", line 24, in <module>
    check_extension('horovod.tensorflow', 'HOROVOD_WITH_TENSORFLOW', __file__, 'mpi_lib')
  File "/usr/local/lib/python3.6/dist-packages/horovod/common/util.py", line 59, in check_extension
    ext_name, full_path, ext_env_var
ImportError: Extension horovod.tensorflow has not been built: /usr/local/lib/python3.6/dist-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so not found
If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[48585,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```
