### ISSUE TITLE
event_base_loop warning

### ISSUE THREAD

**Issue by Fubukimaru** [horovod/horovod#593]
Hello,

I'm training a network using Horovod and I'm getting this warning constantly:

```
[warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
```
The network trains correctly, but it's a bit annoying. I searched a bit on Internet and it seems that is something related to libev and mpi, any clue? 

I'm currently using Horovod version 0.13.11

Thanks!

**Comment by alsrgv** [comment]
@Fubukimaru, which version of Open MPI are you using?  Can you try upgrading to Open MPI 3.1.2?

**Comment by Fubukimaru** [comment]
Hello alsrgv,

Thanks for your reply. I was using OpenMPI 3.0.0.  OpenMPI 3.1.2 is available in my cluster but I cannot use it, I'll contact the guys from support to be able to use it and then come back to you.

Thanks again!

**Comment by Fubukimaru** [comment]
Hello alsrgv,

Thanks for your reply. I was using OpenMPI 3.0.0.  OpenMPI 3.1.2 is available in my cluster but I cannot use it, I'll contact the guys from support to be able to use it and then come back to you.

Thanks again!

**Comment by Fubukimaru** [comment]
It seems I get the same warning with OpenMPI 3.1.2. Any recommendation?

Thanks!

**Comment by Fubukimaru** [comment]
I haven't had time for posting the issue, but it seems that I'm not alone:
https://github.com/open-mpi/ompi/issues/1081

**Comment by alsrgv** [comment]
@Fubukimaru, ah - in that case you can probably avoid it by setting `HOROVOD_MPI_THREADS_DISABLE=1` during runtime.
