### ISSUE TITLE
Tensorflow not able to import meta_graph after models saved with horovod training

### ISSUE THREAD

**Issue by shoubhik** [horovod/horovod#594]
After running training with horovod, I want to load the model back into memory using `tf.train.import_meta_graph`. I used the following code
```
with tf.Session() as sess:
   ...:     saver = tf.train.import_meta_graph('model.ckpt-70001.meta', clear_devices=True)
```

But I am getting the following error

```
/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.9/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in import_meta_graph(meta_graph_or_file, clear_devices, import_scope, **kwargs)
   1958       clear_devices=clear_devices,
   1959       import_scope=import_scope,
-> 1960       **kwargs)
   1961
   1962   if meta_graph_def.HasField("saver_def"):

/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.9/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.pyc in import_scoped_meta_graph(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate)
    742         name=(import_scope or scope_to_prepend_to_names),
    743         input_map=input_map,
--> 744         producer_op_list=producer_op_list)
    745
    746     # Restores all the other collections.

/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.9/lib/python2.7/site-packages/tensorflow/python/util/deprecation.pyc in new_func(*args, **kwargs)
    430                 'in a future version' if date is None else ('after %s' % date),
    431                 instructions)
--> 432       return func(*args, **kwargs)
    433     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    434                                        _add_deprecated_arg_notice_to_docstring(

/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.9/lib/python2.7/site-packages/tensorflow/python/framework/importer.pyc in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    389   if producer_op_list is not None:
    390     # TODO(skyewm): make a copy of graph_def so we're not mutating the argument?
--> 391     _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
    392
    393   graph = ops.get_default_graph()

/Users/shoubhik/anaconda/anaconda3/envs/tensorflow-1.9/lib/python2.7/site-packages/tensorflow/python/framework/importer.pyc in _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
    156     # Remove any default attr values that aren't in op_def.
    157     if node.op in producer_op_dict:
--> 158       op_def = op_dict[node.op]
    159       producer_op_def = producer_op_dict[node.op]
    160       # We make a copy of node.attr to iterate through since we may modify

KeyError: u'HorovodAllreduce'
```
I am using the esitmator API
Any idea how I can read in the meta file to restore the weights?

**Comment by alsrgv** [comment]
@shoubhik, can you describe your use case in a bit more details?  Are you trying to do this for inference purposes?  If so, can you check if solutions in [Inference doc](https://github.com/uber/horovod/blob/master/docs/inference.md) help you?

**Comment by shoubhik** [comment]
Hi,
My use case is to basically reload the weights of an existing network and retrain it using quantization. The link you pointed to may work for me but can you point me on how to generate a .pb file from checkpoint files?

**Comment by alsrgv** [comment]
@shoubhik, are you planning to retrain using the Estimator?  You should be able to restore from the previous checkpoint.

**Comment by shoubhik** [comment]
Yes, I would be using the estimator API. However, I looked into loading model from checkpoint using the estimator API and the input for loading the model is` MODEL_DIR`. I am assuming that will load the latest checkpoint. However, my use case is to load a particular checkpoint where the loss is minimum. Is there a way where I can just load a particular checkpoint and not the latest one?

**Comment by alsrgv** [comment]
@shoubhik, can you try using `warm_start_from`: https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#__init__ ?

**Comment by AvKhokhlov** [comment]
I've the same issue.  I learned the model from PocketFlow using horavod and got 'HorovodAllreduce' error when I imported meta graph. Is there some workaround to write script which loads only checkpoints and freeze model without this horavod issue if I don't have '.pb' file and the code of the model ?

**Comment by alsrgv** [comment]
@AvKhokhlov, can you try following [this guide](https://github.com/horovod/horovod/blob/master/docs/inference.md) to optimize your model for inference?

**Comment by AvKhokhlov** [comment]
It doesn't look as my case. I don't have '.pb', '.pbtxt' and etc. files. Only checkpoints and I want to load the model from them. Give the result to some our proprietor converter and make some processing with them. There are a variety of the models and some of them are ours and I can load them as estimators pr some kind of it because I have code of the model. But I'd like to have general solution which works even with checkpoints using import_meta_graph or some analog of this function

**Comment by ZhenhuaGe** [comment]
try   import horovod.tensorflow as hvd

**Comment by ZhenhuaGe** [comment]
try 
import horovod.tensorflow as hvd
I've the same issue, and add this line help me solve this problem

**Comment by alsrgv** [comment]
@AvKhokhlov, as @ZhenhuaGe mentioned, is it possible for you to `import horovod.tensorflow` as part of your importer?

**Comment by murphypei** [comment]
> try
> import horovod.tensorflow as hvd
> I've the same issue, and add this line help me solve this problem

this works for me, thanks.
