### ISSUE TITLE
Running horovod with MVAPICH2-GDR has some errors

### ISSUE THREAD

**Issue by wangxf2018** [horovod/horovod#598]
Hi team,
I am testing horovod with MVAPICH2-GDR on single node. My test environment is ubuntu16.04, tensorflow1.8, horovod0.14, gcc4.8.5, cuda9.2, cudnn7.1,MLNX-OFED 4.3, Intel Xeon CPU, nvidia V100. using HOROVOD_GPU_ALLREDUCE=MPI.
but there are some errors.such as OOM and lib error 
[mvapich2-gdr&horovod-error.log](https://github.com/uber/horovod/files/2527793/mvapich-gdr.horovod-error.log)

**Comment by tgaddair** [comment]
Hey @wangxf2018, does this issue occur if you run with a single worker (without mpirun)?  Could you try reducing the batch size from 64 to 32?

**Comment by wangxf2018** [comment]
Hi @tgaddair,horovod can run successfully with  a single worker.and I tried reducing the batch size to 32,but there was the same error.

**Comment by tgaddair** [comment]
That's curious.  Could you try running `nvidia-smi` in another terminal when you're running Horovod and paste the output here?  I'm wondering if there are other processes that may be making use of the GPU memory.

Also, per [this](https://github.com/tensorflow/tensorflow/issues/6698) thread, are you setting `config.gpu_options.allow_growth = True`?

**Comment by wangxf2018** [comment]
Sorry I haven’t got back to you sooner .it's available when I run horovod with openmpi. Is mvapich2-gdr better than openmpi in your horovod testing?
because mvapich2-gdr  requires gnu4.8.5. does it affect horovod in ubuntu16.04?

here is commond:
mpirun -np 2 -genv MV2_CPU_MAPPING=0  -genv MV2_USE_CUDA=1 -genv MV2_USE_GPUDIRECT_GDRCOPY=0  python tf_cnn_benchmarks.py --model resnet101 --batch_size 32 --num_batches 100 --use_fp16=True --variable_update horovod --horovod_device gpu 

the nvidia-smi's output:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                  Off |
| N/A   35C    P0    54W / 300W |  16159MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1B:00.0 Off |                  Off |
| N/A   36C    P0    60W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:3D:00.0 Off |                  Off |
| N/A   33C    P0    54W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:3E:00.0 Off |                  Off |
| N/A   40C    P0    52W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  Off  | 00000000:88:00.0 Off |                  Off |
| N/A   36C    P0    52W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                  Off |
| N/A   35C    P0    53W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  Off  | 00000000:B1:00.0 Off |                  Off |
| N/A   38C    P0    54W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  Off  | 00000000:B2:00.0 Off |                  Off |
| N/A   35C    P0    57W / 300W |     11MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     36377      C   python                                     14902MiB |
|    0     36378      C   python                                      1246MiB |
+-----------------------------------------------------------------------------+

**Comment by alsrgv** [comment]
@wangxf2018, I don't believe we got further than the original MPICH in that MPI implementation branch.  I think the issue here is that both processes think that their local_rank = 0.

Is it possible that when you installed Horovod, it got built against Open MPI?  If so, reinstalling Horovod with `--no-cache-dir` should help.

**Comment by fightbob** [comment]
@wangxf2018 Could you provide some performance data about horovod with MVAPICH2-GDR ? Thanks a lot in advance.

**Comment by fightbob** [comment]
Hi @alsrgv, within horovod,  MVAPICH2-GDR is better performance than OpenMPI and nccl2?  Thanks a lot in advance.

**Comment by alsrgv** [comment]
@fightbob, I do not believe the choice of MPI matters much until you hit a very large scale - hundreds of GPUs.
