### ISSUE TITLE
Horovod with parameter server (rank 0)

### ISSUE THREAD

**Issue by sandralima** [horovod/horovod#601]
Hello Team,

How to do The worker with rank 0 (master) not processes training. I only need that master runs the validation, summary and the checkpoints operations, just like a parameter server, because when I try to scale to more than 3 workers, the master does not have enough RAM memory and the training finish abnormally.
![masterram](https://user-images.githubusercontent.com/6975642/47736621-0d5b4080-dc3d-11e8-8106-b91bd86e7ca4.png)

**Comment by tgaddair** [comment]
Hey @sandralima, what you're trying to do is possible, but will require a bit of work to get setup.  Basically, what you can do is use the [comm](https://github.com/uber/horovod/blob/master/horovod/common/__init__.py#L58) parameter to `hvd.init(comm)` to restrict communication to all workers except worker 0.  Then you can use normal MPI message passing to signal to worker 0 that it's time to do validation.  

However, this can get very complicated very quickly, so I think your better option is to possibly reduce the batch size first and see if that doesn't solve your memory issue.
