### ISSUE TITLE
When and how is gradient aggregation done?

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#617]
1. Is the Gradient aggregation done after each batch computation in all workers?
2. How can we change the way gradients are aggregated? The hvd.DistributedOptimizer just seem to plainly average the gradients, how to perform custom gradient aggregation? Can you give a code snippet.

Thanks

**Comment by alsrgv** [comment]
@UditGupta10, (1) Yes. (2) What kind of custom aggregation are you thinking about?

**Comment by UditGupta10** [comment]
I am working on an application that does sparse updates to the parameters, after each batch all the parameters are aggregated, but for the unchanged ones it is unnecessary. Is there a way i can make gradient aggregation faster given sparse updates?
