### ISSUE TITLE
the one-to-one correspondence between hvd.rank() and the physical machine

### ISSUE THREAD

**Issue by wx1111** [horovod/horovod#623]
i run distributed training on 4 machines with 4 GPUs, and run the command shown below on each server:
 mpirun -np 16 \
    -H server1:4,server2:4,server3:4,server4:4 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python train.py

how do i get the one-to-one correspondence between hvd.rank() and the physical GPU or the physical server.

**Comment by alsrgv** [comment]
@wx1111, you can use `hvd.local_rank()` to get a GPU ID within the server. Does that solve your problem?

**Comment by wx1111** [comment]
> @wx1111, you can use `hvd.local_rank()` to get a GPU ID within the server. Does that solve your problem?

Unfortunately, this is not what i want.  
what i want to know is something like the rank of the GPU whose ID is 3 on the server1 .

**Comment by alsrgv** [comment]
wx1111, you could use `mpi4py` and use `allgather` or hostnames and local ranks of every process.  Then you could map (hostname:gpuid -> rank).  Would that help?
