### ISSUE TITLE
using  'mpirun'  and  tf  to train  the  net      can not   start

### ISSUE THREAD

**Issue by jiinhui** [horovod/horovod#624]

**Comment by jiinhui** [comment]
I  want  to  use    horovod  and    tf  to   train   my  net  on  2  GPU,  but  it   stop   at  the  funtion   'tf.train.MonitoredTrainingSession(config=config,hooks=myhooks)'.  my  command   line  is  "mpirun  --   -np 2  -H localhost:2  python  my_net.py".  If  I  change  the  command  to"mpirun    -np 1  -H localhost:1  python  my_net.py",  and  that  will  be  ok.        Why?

**Comment by alsrgv** [comment]
@jiinhui, what's the error message that you see?

**Comment by jiinhui** [comment]
> @jiinhui, what's the error message that you see?
no  error message, but  It   is   waiting  at  that  funtion MonitoredTrainingSession() ,
the  log    shows:
......
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Done running local_init_op.

**Comment by jiinhui** [comment]
@alsrgv    It will still  wait ,   I  don't  think    it  will   go   on  only if    I  revise   the   code to    " session = tf.Session(config=config)"  .But     it  shows  error   info  in  next   step  if  I revise  it.

**Comment by alsrgv** [comment]
@jiinhui, what's the error?
