### ISSUE TITLE
Config gpu options on cpu cluster

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#630]
According to the examples, this is how we pin a gpu to a process
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())

What needs to be done if we are using a cpu cluster with no gpus?

**Comment by tgaddair** [comment]
Hey @UditGupta10, one option is to do nothing, and let TensorFlow take care of running on all the CPU resources available on the machine.

If you want to specifically ensure that each process only binds to a specific CPU socket, or uses a specific number of cores, this can be done with `mpirun` as explained in [this](https://stackoverflow.com/questions/36488549/how-to-replace-cpus-per-proc-with-map-by-in-openmpi) StackOverflow answer.

The example they give:

```
-n 4 --map-by socket:pe=3 --bind-to core
```

That will start 4 processes, one per CPU socket, using 3 cores per socket.

**Comment by UditGupta10** [comment]
I got your point. The code runs on the cpu machine even after specifying the 3 lines of code mentioned in earlier post. I guess if the machine does not have gpu(s) then these commands will be neglected.

**Comment by UditGupta10** [comment]
I got your point. I am using cray cluster which uses aprun instead of mpirun. 
In my case 1 node has 2 CPU sockets, each socket has 12 cores. I want to run horovod on multiple nodes such that each node uses maximum resources (cores) available. Please suggest the right value to use for flags.
Following flags are available: 
-n:  Number of processing elements PEs required for the application (pes)
-N:  Number of PEs to place per node
-d:  Number of CPU cores required for each PE and its threads
-j:   Number of CPUs to use per compute unit (bulldozer core-module)
-cc: Bind PEs to CPU cores.
