### ISSUE TITLE
Running Horovod on more than 2 nodes with only CPU.

### ISSUE THREAD

**Issue by salemmohammed** [horovod/horovod#637]
I am trying to run horovod on more than one machine. I ran it on one, and two machines. I tried the third machine and I got the following error. 

[ip-hostname3:14313] [[44845,0],2] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file grpcomm_direct.c at line 355
--------------------------------------------------------------------------
An internal error has occurred in ORTE:

[[44845,0],2] FORCE-TERMINATE AT Data unpack would read past end of buffer:-26 - error grpcomm_direct.c(359)

This is something that should be reported to the developers.

I run horovod on machine 1 and 2, 1 and 3, they worked fine but when I run on three machines or second and the third machine, the above error occurs. 

on the first machine (hostname1)
mpirun -np 3 \
    -H hostname1:1,hostname2:1,hostname3:1 \
    -bind-to none -map-by slot \
    -mca pml ob1 -mca btl ^openib \
    python3 offex.py

on the first machine (hostname1)
mpirun -np 2 \
    -H hostname2:1,hostname3:1 \
    -bind-to none -map-by slot \
    -mca pml ob1 -mca btl ^openib \
    python3 offex.py

I am using AWS ec2 instances, Ubuntu 16.04. Open MPI version 4.0.0.
Can anybody point me some suggestion?

**Comment by salemmohammed** [comment]
@alsrgv

**Comment by tgaddair** [comment]
Hey @salemmohammed, it could be an MPI version mismatch.  Per #368, I would suggest checking:

1. Did you install both Open MPI in the same location?
2. Did you specify --enable-mpirun-prefix-by-default option to ./configure?

@regel sounds like your issue is different, related to SSH configuration.  Did the suggestions in that issue you referenced work for your setup?

**Comment by algorithmconquer** [comment]
I  meet a similar problem, but how to do with the problem?
