### ISSUE TITLE
Clarification on How the Data is Distributed by Horovod

### ISSUE THREAD

**Issue by EhsanM4t1qbit** [horovod/horovod#640]
Hi, I was wondering if you could clarify a couple of points for me please, regarding [issue 166](https://github.com/uber/horovod/issues/166) and in general how Horovod distributes the data.

In the[ mnist TF example](https://github.com/uber/horovod/blob/master/examples/tensorflow_mnist.py), each process (and hence each GPU) seems to be working on a separate part of the dataset.
`mnist = learn.datasets.mnist.read_data_sets('MNIST-data-%d' % hvd.rank())`
Is that right? And then the gradient are averaged at the end of each batch during training, right?

In the [Keras example](https://github.com/uber/horovod/blob/master/examples/keras_imagenet_resnet50.py), the data is not explicitly distributed. Who is taking care of that?

** For my application, I have my data saved up as multiple TFRecord files and I want to code in tesnorflow. I am not sure how to distribute the data though. The data is large (40-50 GB). Ideally I'd like to distribute the data batch by batch between all the GPUs, but I don't know how to do that.

Your help would be greatly appreciated.

**Comment by alsrgv** [comment]
@EhsanM4t1qbit, actually, the MNIST example just uses rank to avoid file name conflicts on the disk.

In general, if you use data reader that randomly reads input data, you will be OK, since each worker reads a random portion of the dataset. E.g., you can do it as described here - https://www.tensorflow.org/api_guides/python/reading_data#batching

With TF dataset API you can be a bit more deterministic and add sharding on top of randomization, like so: https://github.com/uber/horovod/issues/223#issuecomment-377831331

**Comment by chandana1332** [comment]
I'd like to understand more on how data is distributed in MxNet. 
I see your point about using a random data reader and then each process will read a possibly different batch. But a couple of questions here:

1. Each process would go through the entire training data as opposed to all the processes collectively going through the training data once. 
2. If I don't have a random reader but a sequential one, how would one go about distributing those batches?

@alsrgv

**Comment by tgaddair** [comment]
Hey @chandana1332 

1. For N processes, each process would typically go through 1/N of the training data each epoch. The processes do not collectively coordinate on reading training data, each process handles that work independently.
2. Even with a sequential reader you would typically [shuffle](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shuffle) the training data prior to the start of each epoch. So long as the shuffling is non-deterministic, different processes will get different batches.

cc @yuxihu for MXNet specifics.

**Comment by apeforest** [comment]
@chandana1332 In MXNet example mxnet_imagenet_resnet50.py, each process would load a part of the training data by passing in GPU rank to the `part_index` parameter in API mx.io.ImageRecordIter().

Please refer to https://github.com/horovod/horovod/blob/master/examples/mxnet_imagenet_resnet50.py#L181

**Comment by chandana1332** [comment]
@tgaddair 
1. How is the vocab created if different processes process chunks of training data independently?
2. Got it!

@apeforest 
I see. 
Two questions:
1. I see that the training data is sharded to hvd.size() parts but validation data is not as seen here: https://github.com/horovod/horovod/blob/master/examples/mxnet_imagenet_resnet50.py#L185
Does this mean all the processors are validating on the same dataset? 

2. How can we achieve the data sharding in ImageRecordIter in Gluon DataLoader? I don't see any options for sharding here: https://mxnet.incubator.apache.org/api/python/gluon/data.html#mxnet.gluon.data.DataLoader
I'm working on a project that only deals with text and we heavily use Gluon and GluonNLP.

**Comment by apeforest** [comment]
> @tgaddair
> 
> 1. How is the vocab created if different processes process chunks of training data independently?
> 2. Got it!
> 
> @apeforest
> I see.
> Two questions:
> 
> 1. I see that the training data is sharded to hvd.size() parts but validation data is not as seen here: https://github.com/horovod/horovod/blob/master/examples/mxnet_imagenet_resnet50.py#L185
>    Does this mean all the processes are validating on the same dataset?
The answer is yes.

> 2. How can we achieve the data sharding in ImageRecordIter through Gluon DataLoader? I don't see any options for sharding here: https://mxnet.incubator.apache.org/api/python/gluon/data.html#mxnet.gluon.data.DataLoader
>    I'm working on a project that only deals with text and we heavily use Gluon and GluonNLP.
I believe in an earlier version we were using gluon.split_and_load() but later changed. I don't recall the exact reason for this revert. @yuxihu may have more clear answer.

**Comment by apeforest** [comment]
@chandana1332 
1. The answer is yes
2. Can you try using https://mxnet.incubator.apache.org/api/python/gluon/gluon.html?highlight=split_and#mxnet.gluon.utils.split_and_load

**Comment by tgaddair** [comment]
Hey @chandana1332 

If you need to preprocess the input data to determine certain constants like the vocab, then read those constants on each worker, you can do so. But during training, you want to ensure that each worker is only processing a subset of the data.

**Comment by chandana1332** [comment]
@tgaddair

Okay. I have a usecase where I'm training with an extremely large dataset. Vocab creation takes up a lot of CPU memory. If I'm training with 4 GPUs that means 4 different processes will be computing this vocabulary using shared CPU memory. I'm surely going to run out of memory. How do you suggest I deal with this usecase?

**Comment by chandana1332** [comment]
@tgaddair ping

**Comment by tgaddair** [comment]
Hey @chandana1332, apologies for the late reply.  I'd suggest using a shared-memory store like [Plasma](https://arrow.apache.org/docs/python/plasma.html#putting-and-getting-python-objects) for this.  

Using Plasma, you can have one process create the object and write it into the store, while the other processes wait for it to become present and then read it.  Plasma supports zero-copy reads, so you can get away with having only one copy of the data in the system's memory, but shared across multiple processes.

**Comment by orwa-te** [comment]
Depending on the concepts above, if I have **2** Horovod processes and each one reads **1/2** of the dataset, then each process will have different batches for its half, but each batch should be sharded into **2 mini batches** here in this example, and then the gradients are averaged on each one.
What I don't understand is **how a process can access and read its minibatch if the batch itself is read by the other process** ?!!!

**Comment by tgaddair** [comment]
Hey @orwa-te, the way to think about it is: every Horovod process is going to read its own subset of the data (in your example, 1/2).  At each step, each process is going to independently process a batch of its subset.  During the backward pass, the gradients of each process are averaged together before being applied.  So the only interaction between the processed comes from the gradient averaging.  All the data reading and batching is done independently.
