### ISSUE TITLE
Segmentation fault. 

### ISSUE THREAD

**Issue by GoldenSpark** [horovod/horovod#647]

**Comment by tgaddair** [comment]
Hey @GoldenSpark, could you try updating to v0.15.2?  There was a race condition prior to #619 that could sometimes cause segfaults like this (see: #585).

**Comment by GoldenSpark** [comment]
@tgaddair 
Thanks for your advice, I will give it a try.

**Comment by GoldenSpark** [comment]
Hey @tgaddair , there is still a segmentation fault  when using horovod-0.15.2.  Could you try to solve this problem? Thanks.

**Comment by tgaddair** [comment]
Do you know if this also happens with the example scripts that come with Horovod, or only with the PocketFlow training script?  

It looks like the segfault is occurring in the underlying TensorFlow library, similar to #554. Can you share some more information about your training script?  What batch size are you using?  Does your training involve sparse tensors?

Also, can you try capturing a timeline?  That may be useful in identifying what Horovod was doing at the time of the segfault.
