### ISSUE TITLE
Aggregating parameters instead of gradients

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#651]
The distributed optimizer does gradient averaging across processes before applying locally. Instead of this, if we do routine single process minimisation and update parameters and then do parameter averaging, will it eventually result in the same global minimisation across processes similar to distributed optimizer.

**Comment by tgaddair** [comment]
Hey @UditGupta10, if I understand your approach correctly, then yes.  There is a proof given [here](https://blog.skymind.ai/distributed-deep-learning-part-1-an-introduction-to-distributed-training-of-neural-networks/) that shows parameter averaging is equivalent to gradient aggregation.

**Comment by michaelstjules** [comment]
> Hey @UditGupta10, if I understand your approach correctly, then yes. There is a proof given [here](https://blog.skymind.ai/distributed-deep-learning-part-1-an-introduction-to-distributed-training-of-neural-networks/) that shows parameter averaging is equivalent to gradient aggregation.

I think this is true for vanilla SGD (or with momentum), but will be false for optimizers like Adam which accumulate and use statistics nonlinearly (e.g. dividing by moments). I'm not sure if the difference would be significant, though.

**Comment by tgaddair** [comment]
Yes, that's a good point.  In such cases, aggregating gradients would give the same results as the serialized version, but parameter averaging would not.
