### ISSUE TITLE
horovod hang with tensorpack

### ISSUE THREAD

**Issue by CYang0515** [horovod/horovod#655]
The server upgrades drivers, Then I run mpiirun ,the GPU is always 100%. But there are no any outputs.

**Comment by CYang0515** [comment]
Thanks for your reply.
I use ''CUDA_VISIBLE_DEVICES=0,1,2,3 mpirun -np 4 --output-filename mylog python train.py'' to train faster rcnn network. The log is sopped in starting epoch1, meanwhile, the GPU occupied is always 100%,but CPU is nearly 0. However, when I use ''python train.py'' to train with 1 GPU card, everything is OK!

**Comment by alsrgv** [comment]
@CYang0515, could you add more flags from [Running Horovod](https://github.com/uber/horovod/blob/master/docs/running.md) doc and share the output?  I'm particularly interested about NCCL debug messages.

**Comment by CYang0515** [comment]
I don't know why it's failure, one week ago, it worked well, but suddenly it become so terrible. I pretend to reinstall the horovod. I follow the documents, but when I use '' HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod'' , there is an error:

gcc -pthread -B /home/amax/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
-std=c++11 -fPIC -O2 -mf16c -mavx -I/home/amax/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.cc -o bui
ld/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /home/amax/anaconda3/compiler_compat -L/home/amax/anaconda3/lib -Wl,-rpath=/home/amax/anaconda3/lib -Wl,--no-as-need
ed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.6/test_compile/test_cpp_flags.so
    gcc -pthread -B /home/amax/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
-I/home/amax/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.6/test_com
pile/test_link_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /home/amax/anaconda3/compiler_compat -L/home/amax/anaconda3/lib -Wl,-rpath=/home/amax/anaconda3/lib -Wl,--no-as-need
ed -Wl,--sysroot=/ -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.6/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.6/te
st_compile/test_link_flags.so
    gcc -pthread -B /home/amax/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
-std=c++11 -fPIC -O2 -mf16c -mavx -I/usr/local/cuda/include -I/home/amax/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compil
e/test_cuda.cc -o build/temp.linux-x86_64-3.6/test_compile/test_cuda.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /home/amax/anaconda3/compiler_compat -L/home/amax/anaconda3/lib -Wl,-rpath=/home/amax/anaconda3/lib -Wl,--no-as-need
ed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -lcudart -o build/temp.lin
ux-x86_64-3.6/test_compile/test_cuda.so
    gcc -pthread -B /home/amax/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
-std=c++11 -fPIC -O2 -mf16c -mavx -I/usr/local/cuda/include -I/home/amax/anaconda3/include/python3.6m -c build/temp.linux-x86_64-3.6/test_compil
e/test_nccl.cc -o build/temp.linux-x86_64-3.6/test_compile/test_nccl.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    build/temp.linux-x86_64-3.6/test_compile/test_nccl.cc:3:2: error: #error Horovod requires NCCL 2.0 or later version, please upgrade.
     #error Horovod requires NCCL 2.0 or later version, please upgrade.
      ^
    error: NCCL 2.0 library or its later version was not found (see error above).
    Please specify correct NCCL location with the HOROVOD_NCCL_HOME environment variable or combination of HOROVOD_NCCL_INCLUDE and HOROVOD_NCCL
_LIB environment variables.

    HOROVOD_NCCL_HOME - path where NCCL include and lib directories can be found
    HOROVOD_NCCL_INCLUDE - path to NCCL include directory
    HOROVOD_NCCL_LIB - path to NCCL lib directory

    ----------------------------------------
Command "/home/amax/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hhhwoghw/horovod/setup.py';f=getattr(tokeni
ze, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-oe88x
ift-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hhhwoghw/horovod/

**Comment by CYang0515** [comment]
mpirun -np 8 -H localhost:4 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python tra
in.py
ssh: Could not resolve hostname localhost:4: Name or service not known
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).

**Comment by CYang0515** [comment]
~/tensorpack_modify/examples/FasterRCNN$ mpirun -np 8 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python train.py
[amax:133017] OPAL ERROR: Not initialized in file pmix3x_client.c at line 113
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[amax:133017] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarant
ee that all other processes were killed!
[amax:133019] OPAL ERROR: Not initialized in file pmix3x_client.c at line 113
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[amax:133019] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarant
ee that all other processes were killed!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[amax:133024] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarant
ee that all other processes were killed!
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[amax:133020] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarant
ee that all other processes were killed!
[amax:133020] OPAL ERROR: Not initialized in file pmix3x_client.c at line 113
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[amax:133021] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarant
ee that all other processes were killed!
[amax:133021] OPAL ERROR: Not initialized in file pmix3x_client.c at line 113
[amax:133024] OPAL ERROR: Not initialized in file pmix3x_client.c at line 113
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[27138,1],0]
  Exit code:    1
--------------------------

**Comment by denfromufa** [comment]
you probably built against one mpi version and then running horovod in another mpi version.
