### ISSUE TITLE
How to improve performance in low bandwidth?

### ISSUE THREAD

**Issue by shaarawy18** [horovod/horovod#659]
Hi, when I run the benchmark with horovod in 10Gbps network, I can't  get the expected result. 

I run resnet-101 model provided by benchmark with real imagenet dataset. 

Single node with 1 RTX2080 GPU produces around 172 images/second. And 2 nodes with 1 RTX2080 GPUs each produce 291 images/second totally, there only 1.6x  better than baseline.   I also  try to train model in 1 node with 2 GPUs, and the result is reasonable that can have 2x improvement than baseline. 

So I think the network bandwidth limit the performance of horovod in muilt-nodes 
environment. When I run the test I also observe the statement of network and  GPU. I find that when using single node with 1 GPU or single node with 2 GPUs train the model, the Memory-Usage  and GPU-Util are nearly 100%  It is not include communication with muilt-nodes in this test environment.
But when  training model in muilt-nodes,   the GPU Memory-Usage will down to around 60%  At the same time，the speed of communication between nodes is around rx/tx 3.80Gbps.  I think the 10Gbps bandwidth is not fully used. 

1. I am confused the reason of above result. Would you have some opinions?
2. I want to know how to improve performance in 10Gbps network?

hardware: 
GPU: GTX 2080
network: 10Gbps(neither InfiniBand  nor RoCE)
switch: 10Gbps

software：
horovod：0.15.0
tensorflow：1.10.0

All tests run in docker environment.

Thanks!

**Comment by tgaddair** [comment]
Hey @shaarawy18, my first suggestion would be to enable fp16 compression.  When initializing your distributed optimizer:

```
opt = hvd.DistributedOptimizer(opt, compression=hvd.Compression.fp16)
```

That will effectively half the amount of data being sent over the network, which should speed things up quite a bit.

If that doesn't help, then there may be something in your environment that's causing issues.  In which case, we can dive deeper if you generate a [timeline](https://github.com/uber/horovod/blob/master/docs/timeline.md) and then share the results here.

**Comment by shaarawy18** [comment]
@tgaddair  Thanks for you reply !

I follow your suggestion and run benchmarks with `hvd.Compression.fp16`. It can effectively  speed model training up.  Now the speedup is nearly 90% of the ideal in 2 nodes with 2GPUs each. 

I have another related questions: 


1.  This is my timeline file when runing the benchmarks.  I can't understand the meaning of the timeline clearly. Which part of this timeline I should pay attention to ?  Could you teach me some methods to analysis timeline ?  Thanks!

2. Can  `Tensor Fusion` method improve the  performance in the distributed training case  by reducing the amount of data in  communication ? How much  the environment variable `HOROVOD_FUSION_THRESHOLD`  should be set ?  


[timeline2x2.json.zip](https://github.com/uber/horovod/files/2648100/timeline2x2.json.zip)

![2018-12-05 5 26 58](https://user-images.githubusercontent.com/17583264/49503697-06b28f80-f8b3-11e8-87b7-8b502a2e91eb.png)





***

```
HOROVOD_TIMELINE=/benchmarks/output/timeline2x2.json mpirun -np 4 -H airl-namenode-0:2,airl-datanode-0:2 
               -mca plm_rsh_args "-p 12345" -x NCCL_SOCKET_IFNAME=p3p1  
               -mca btl_tcp_if_exclude lo,docker_gwbridge,docker0,em1     
               python /benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
               --model resnet101 
               --batch_size 64 
               --variable_update horovod  
               --data_name imagenet 
               --data_dir /input/imagenet/train/
```
### baseline 
```
Step	Img/sec	total_loss
----------------------------------------------------------------
100	images/sec: 171.5 +/- 0.3 (jitter = 2.4)	9.184
----------------------------------------------------------------
total images/sec: 171.43
----------------------------------------------------------------
```
### 2 nodes with 2GPUs each 
```
100	images/sec: 111.0 +/- 0.9 (jitter = 2.8)	9.165
----------------------------------------------------------------
total images/sec: 443.84
----------------------------------------------------------------
```
### 2 nodes with 2GPUs each && hvd.Compression.fp16
```
100	images/sec: 154.4 +/- 1.7 (jitter = 3.9)	8.925
----------------------------------------------------------------
total images/sec: 617.29
----------------------------------------------------------------
```

**Comment by tgaddair** [comment]
In general, you want to pay attention to the areas that are taking the most time (the widest horizontal bars), as those will typically be your bottlenecks.  One thing I'm seeing from your timeline is that Horovod is using `MPI_ALLREDUCE` instead of NCCL.  In general, NCCL will be able to better make use of your network if you can install it in your environment.

We have some docs on understanding the timeline [here](https://github.com/uber/horovod/blob/master/docs/timeline.md) for more detailed info.

Tensor Fusion will not reduce the overall amount of data sent over the network, but it can help in situations where there are many small allreduce requests being made by batching these requests together.  By default, Horovod runs with a 64MB fusion buffer, which is pretty large.  In some environments, we've seen performance improvements by reducing this to 32, 16 or 8MB.  So it may be worth playing around with that.

Worth noting that when you change the fusion buffer size, you'll often want to change the cycle time as well, as the two are linked.  We're currently working on an autotuner that will allow you to find the right values of these settings automatically, that's slated for the next release.  So stay tuned.

**Comment by shaarawy18** [comment]
@tgaddair  Follow your advice, I reinstall Horovod in my environment to support NCCL. And there is timeline that Horovod is using  NCCL. When using NCLL instead of `MPI_ALLREDUCE `, the  speedup is still 90%  of the ideal,  the same as using `MPI_ALLREDUCE `. Do you think it is in a normal state?

 
![2018-12-06 5 06 46](https://user-images.githubusercontent.com/17583264/49574752-0c27dc80-f97c-11e8-8890-b40465acde2c.png)

I understand the areas of  ` WAITING FOR OTHER TONSER  DATA `  in the timeline is the processing of Tensor Fusion. In this case, should I reduce the fusion buffer?

I also record network  traffic when running Horovod, I think the  10Gbps bandwidth is the my
 bottlenecks. If I want to upgrade network devices，do you have any good suggestions？


![download](https://user-images.githubusercontent.com/17583264/49575434-a63c5480-f97d-11e8-8dfc-81979a100a26.png)
