### ISSUE TITLE
How to take full advantage of horovod to train 

### ISSUE THREAD

**Issue by Yang-HangWA** [horovod/horovod#681]
My script is just as  https://github.com/uber/horovod/issues/669#issuecomment-444003140 .I run the script successful  on two machines and each of them has two gpus. However,most of the time the volatile GPU-Util is 0%. The training  data store on one of them with a NFS to share data with others. Besides, I  find  it's even slower than training on one machine with one gpu. I suspect it has to do with networking and NFS. What can I do to speed up the training ?   Any ideas ? Any suggestions? The two machines' test output as follow:
![impove](https://user-images.githubusercontent.com/38546249/49578033-c111c780-f983-11e8-9e63-d11b4590165b.PNG)

**Comment by tgaddair** [comment]
I wonder if your sparse tensors being allgathered are very large.  Do you know about what percentage of the tensor is non-zero?  If it's high, you could try using the `sparse_to_dense` option of the `DistributedOptimizer` to convert them into dense tensors and perform allreduce.  You can then also take advantage of fp16 compression, which would definitely help in a slow network environment.

**Comment by Yang-HangWA** [comment]
Hey,@tgaddair. I followed your advice and I set sparse_to_dense to True which make decrease to 1/3~1/4 of original training time.What a amazing!What's more, can I get a great improvement to decrease the training time if I improve the network to 10Gpbs?
