### ISSUE TITLE
how to implement model horovod_model_parallelism for big model

### ISSUE THREAD

**Issue by yyht** [horovod/horovod#682]
I had a big model  that needs to run on two machines with 8-gpus for one process. 
I had seen https://gist.github.com/alsrgv/cbbb2e25f09c1df983098098511d16c4.  Could you provide some details about multi-machine, multi-gpu for one-process training? 
As far as I known, "with tf.device('/gpu:0')" seems use local gpu-id. If i want to use two machines to distribute my model across two machines such as "with tf.device('/gpu:5')", how should i set gpu-id( I think I need global rank but for each mahcine, global rank doesn't work because it only has 4-gpus)

**Comment by tgaddair** [comment]
Hey @yyht, multi-machine model parallelism is a non-trivial problem.  At the moment, Horovod isn't designed to split a single model across multiple machines, as its primary function is for data parallelism.  At the moment, you'd need to split the training into two processes, with one process on machine-1 using 4 GPUs and another processing on machine-2 using 4 GPUs.
