### ISSUE TITLE
unable to install horovod

### ISSUE THREAD

**Issue by LeanderK** [horovod/horovod#686]
I am using mac osx without a GPU for development.

    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:23:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:24:
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:17:2: error: This file was generated by an older version of protoc which is
    #error This file was generated by an older version of protoc which is
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
    #error incompatible with your Protocol Buffer headers.  Please
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:19:2: error: regenerate this file with a newer version of protoc.
    #error regenerate this file with a newer version of protoc.
     ^
    In file included from horovod/tensorflow/mpi_ops.cc:22:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:23:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:24:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:33:
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/attr_value.pb.h:17:2: error: This file was generated by an older version of protoc which is
    #error This file was generated by an older version of protoc which is
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/attr_value.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
    #error incompatible with your Protocol Buffer headers.  Please
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/attr_value.pb.h:19:2: error: regenerate this file with a newer version of protoc.
    #error regenerate this file with a newer version of protoc.
     ^
    In file included from horovod/tensorflow/mpi_ops.cc:22:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:23:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:24:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:33:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/attr_value.pb.h:36:
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor.pb.h:17:2: error: This file was generated by an older version of protoc which is
    #error This file was generated by an older version of protoc which is
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
    #error incompatible with your Protocol Buffer headers.  Please
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor.pb.h:19:2: error: regenerate this file with a newer version of protoc.
    #error regenerate this file with a newer version of protoc.
     ^
    In file included from horovod/tensorflow/mpi_ops.cc:22:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:23:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:24:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:33:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/attr_value.pb.h:36:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor.pb.h:33:
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/resource_handle.pb.h:17:2: error: This file was generated by an older version of protoc which is
    #error This file was generated by an older version of protoc which is
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/resource_handle.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
    #error incompatible with your Protocol Buffer headers.  Please
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/resource_handle.pb.h:19:2: error: regenerate this file with a newer version of protoc.
    #error regenerate this file with a newer version of protoc.
     ^
    In file included from horovod/tensorflow/mpi_ops.cc:22:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:23:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:24:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:33:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/attr_value.pb.h:36:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor.pb.h:34:
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor_shape.pb.h:17:2: error: This file was generated by an older version of protoc which is
    #error This file was generated by an older version of protoc which is
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor_shape.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
    #error incompatible with your Protocol Buffer headers.  Please
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor_shape.pb.h:19:2: error: regenerate this file with a newer version of protoc.
    #error regenerate this file with a newer version of protoc.
     ^
    In file included from horovod/tensorflow/mpi_ops.cc:22:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:23:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:24:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def.pb.h:33:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/attr_value.pb.h:36:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/tensor.pb.h:35:
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/types.pb.h:17:2: error: This file was generated by an older version of protoc which is
    #error This file was generated by an older version of protoc which is
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/types.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
    #error incompatible with your Protocol Buffer headers.  Please
     ^
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/types.pb.h:19:2: error: regenerate this file with a newer version of protoc.
    #error regenerate this file with a newer version of protoc.
     ^
    In file included from horovod/tensorflow/mpi_ops.cc:22:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:23:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:25:
    In file included from /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/lib/core/status.h:23:
    /Users/LeanderK/miniconda3/envs/bijection-action/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/lib/core/error_codes.pb.h:17:2: error: This file was generated by an older version of protoc which is
    #error This file was generated by an older version of protoc which is
     ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    INFO: Unable to build TensorFlow plugin, will skip it.

running 
`python3 -c 'import tensorflow as tf; print(tf.__version__)'`
returns
`1.12.0`

**Comment by alsrgv** [comment]
@LeanderK, can you try following recommendations here - https://stackoverflow.com/questions/46235376/tensorflow-protobuf-version-mismatch ?

**Comment by wanglouis49** [comment]
@alsrgv I had the same issue and it's resolved by following the link you mentioned. Thanks!

**Comment by yselivonchyk** [comment]
In order to resolve similar issue had to:
1. remove all existing protobuf installs 
```
conda uninstall protobuf
conda uninstall libprotobuf
```
2. manually clean up /usr/include/google/protobuf/ where /usr/bin/ is the installation folder of older protobuf
3. Install latest version of protobuf, not necessarily the exact one used by TF.

**Comment by zdgithub** [comment]
I degrade my tensorflow from `1.13.0` to `1.12.0`

**Comment by tonyreina** [comment]
I'm having the same error with TensorFlow 1.15 and the latest Horovod. 

$ protoc --version
libprotoc 3.11.2

I don't really want to have to hack the protoc just to get Horovod to work. Is there some way the install package can be changed to correct the error?
