### ISSUE TITLE
segmentation fault 1000 process - Transformer Model

### ISSUE THREAD

**Issue by srinivas-varadharajan** [horovod/horovod#687]
Hey @alsrgv ,

I'm running into seg fault for anything above 250 process.
sparse_as_dense works good till 250 process with local batch size of 5000 tokens (transformer model).
Follow up to below issue.
[https://github.com/uber/horovod/issues/554](url)

I've attached the timeline and debug files for 1000 process (250 nodes, 4 process each).
[1000_process_seg_fault.zip](https://github.com/uber/horovod/files/2658686/1000_process_seg_fault.zip)

In the timeline I don't see the all reduce step and I'm unable to see the shape of the tensor. Looks like it's failing as the gradients are collected.

Thanks,
Srini

**Comment by alsrgv** [comment]
Hi Srini, could you get a core dump and get the back trace of all threads?

**Comment by billy19murahmi** [comment]
@alsrgv  Debug file (debug_output_1000.o) in the zipped folder is the back trace of all threads.

**Comment by alsrgv** [comment]
@billy19murahmi, got it. Is it possible that one of the workers has flaky access to the data store?  Does it always fail on the same set of workers?

**Comment by billy19murahmi** [comment]
It doesn't fail on the same set of workers. I've also tried to exclude those workers. I still get the same seg fault with different set of nodes.

**Comment by alsrgv** [comment]
How is your data pipeline built, does it use TFRecords? If you use new sharding API, maybe you're running out of shards?

**Comment by billy19murahmi** [comment]
yes, it uses TFRecords. I'm listing and sharding before other pipeline functions. 
I'm not sure if I'm running out of shards, because I've tried to run 250 process experiments with 100 shards and it worked fine. All current experiments I'm running with 400 shards.

I’ve created gists for transformer_main and dataset pipeline scripts which has horovod changes.

[https://gist.github.com/billy19murahmi/8ce0e0b0fbb10010c34f154f3742195c](url)
[https://gist.github.com/billy19murahmi/60f7810da035d14812f1e2264cedf4a4](url)

**Comment by alsrgv** [comment]
@billy19murahmi,

How many TFRecord files do you have?

```python
  dataset = tf.data.Dataset.list_files(file_pattern, shuffle=shuffle)
  # added for horovod
  if input_flag=="train":
    print(hvd.size(), hvd.rank())
    dataset = dataset.shard(hvd.size(), hvd.rank())
```

What if you disable this sharding functionality - does segfault go away?

**Comment by billy19murahmi** [comment]
@alsrgv  Ran few tests with 1000 processes. When sharding functionality is removed, the model trains without any segfault error. Thanks for the suggestion.

**Comment by sarunyap** [comment]
@billy19murahmi @alsrgv Hi guys, what is the problem with data sharding in this case?
