### ISSUE TITLE
multi-machine training but hangs on

### ISSUE THREAD

**Issue by yyht** [horovod/horovod#690]
I had modified the script with 

-mca btl_tcp_if_exclude docker0,lo,br-1ca618956367,br-224fa76e2bea,br-be5c07c9e794,br-697da8ae7b12,br-6655561aac78,br-3e45e7ddc33c,docker_gwbridge,vboxnet0,virbr0 \
 -x NCCL_SOCKET_IFNAME=enp14s0,eno1 \

![image](https://user-images.githubusercontent.com/14133687/49696932-27008800-fbec-11e8-8b8d-e843f227d707.png)
![image](https://user-images.githubusercontent.com/14133687/49696934-32ec4a00-fbec-11e8-8f89-8363ee41ef13.png)

It seems it works on with 100%-precent gpu useage but it doesn't log training info。。。。

**Comment by alsrgv** [comment]
@yyht, can you connect to your running process using `gdb -p <pid>` and get an output of `thread apply all bt`?

**Comment by yyht** [comment]
![image](https://user-images.githubusercontent.com/14133687/49725869-b74fd300-fca7-11e8-9d84-714e39ef2fa8.png)
"Launch mode Parallel" was succeeded but the training process seemd to be stuck.
![image](https://user-images.githubusercontent.com/14133687/49725988-ecf4bc00-fca7-11e8-82f2-8ca315f6c88e.png)
This was the GPU-usage of second machine which shown 100% gpu usage。。。

While for bsingle-machine with multi-gpus, 
![image](https://user-images.githubusercontent.com/14133687/49734782-68626780-fcc0-11e8-9f2b-9781e663895f.png)
it worked fine.

**Comment by alsrgv** [comment]
@yyhh, got it - can you get the output of `thread apply bt all` within `gdb` though?
