### ISSUE TITLE
multi node training is too slow

### ISSUE THREAD

**Issue by LEESEYUN** [horovod/horovod#693]
I run "tf_cnn_benchmark.py" with horovod  

But "2node 8GPU" is too much slower than  "1node 4GPU"

My network is 1GB/s

**1node 4GPU (1080ti x 4)**

mpirun -np 4 --allow-run-as-root -x NCCL_DEBUG=INFO -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python3 tf_cnn_benchmarks.py --data_format=NCHW --batch_size=64 --model=resnet50 --variable_update=horovod --nodistortions --allow_growth=True --print_training_accuracy=True --data_dir=./test_data/fake_tf_record_data --data_name=imagenet

==============================================================
70	images/sec: 152.2 +/- 0.3 (jitter = 2.3)	2.101	0.750	1.000
80	images/sec: 152.1 +/- 0.2 (jitter = 2.1)	1.968	0.953	1.000
80	images/sec: 152.1 +/- 0.2 (jitter = 2.1)	2.050	0.875	1.000
80	images/sec: 152.1 +/- 0.2 (jitter = 1.9)	2.199	0.609	1.000
80	images/sec: 152.1 +/- 0.2 (jitter = 2.4)	2.274	0.688	1.000
90	images/sec: 152.2 +/- 0.2 (jitter = 2.3)	1.799	0.875	1.000
90	images/sec: 152.2 +/- 0.2 (jitter = 2.2)	1.867	0.703	1.000
90	images/sec: 152.2 +/- 0.2 (jitter = 2.1)	2.220	0.516	1.000
90	images/sec: 152.2 +/- 0.2 (jitter = 2.5)	2.321	0.422	1.000
100	images/sec: 152.1 +/- 0.2 (jitter = 2.2)	1.678	0.828	1.000
----------------------------------------------------------------
total images/sec: 608.38
----------------------------------------------------------------
100	images/sec: 152.1 +/- 0.2 (jitter = 2.3)	1.735	0.797	1.000

==============================================================

**1node 4GPU (titan xp x 4)**

==============================================================

80	images/sec: 221.1 +/- 0.7 (jitter = 3.7)	2.162	0.703	1.000
80	images/sec: 221.1 +/- 0.7 (jitter = 3.6)	2.190	0.688	1.000
80	images/sec: 221.1 +/- 0.7 (jitter = 3.4)	2.141	0.781	1.000
80	images/sec: 221.1 +/- 0.7 (jitter = 3.6)	2.464	0.219	1.000
90	images/sec: 221.1 +/- 0.6 (jitter = 3.8)	2.262	0.281	1.000
90	images/sec: 221.1 +/- 0.6 (jitter = 3.7)	1.813	0.906	1.000
90	images/sec: 221.1 +/- 0.6 (jitter = 3.6)	2.064	0.672	0.844
90	images/sec: 221.2 +/- 0.6 (jitter = 3.8)	2.429	0.359	0.953
100	images/sec: 221.1 +/- 0.6 (jitter = 3.9)	1.520	0.953	1.000
----------------------------------------------------------------
total images/sec: 884.14

==============================================================

**2node 8GPU (1080ti x4 , titian xp x4)**

==============================================================
80	images/sec: 19.8 +/- 0.1 (jitter = 0.3)	1.098	0.844	1.000
90	images/sec: 19.8 +/- 0.1 (jitter = 0.6)	1.038	0.781	1.000
90	images/sec: 19.8 +/- 0.1 (jitter = 0.6)	1.953	0.547	1.000
90	images/sec: 19.8 +/- 0.1 (jitter = 0.6)	0.667	1.000	1.000
90	images/sec: 19.8 +/- 0.1 (jitter = 0.5)	1.167	0.719	1.000
90	images/sec: 19.8 +/- 0.1 (jitter = 0.4)	2.205	0.562	1.000
90	images/sec: 19.8 +/- 0.1 (jitter = 0.4)	0.752	0.844	1.000
90	images/sec: 19.8 +/- 0.1 (jitter = 0.3)	3.302	0.438	1.000
90	images/sec: 19.8 +/- 0.1 (jitter = 0.3)	3.390	0.422	0.875
100	images/sec: 19.9 +/- 0.1 (jitter = 0.5)	0.568	1.000	1.000
----------------------------------------------------------------
total images/sec: 158.80

==============================================================

**NCCL Debug**

==============================================================
seyun:7758:8026 [0] NCCL INFO NET : Using interface eth0:115.145.178.160<0>
seyun:7758:8026 [0] NCCL INFO NET/IB : Using interface eth0 for sideband communication
seyun:7758:8026 [0] NCCL INFO Using internal Network Socket
seyun:7758:8026 [0] NCCL INFO NET : Using interface eth0:115.145.178.160<0>
seyun:7758:8026 [0] NCCL INFO NET/Socket : 1 interfaces found
NCCL version 2.3.7+cuda9.0
seyun:7758:8026 [0] NCCL INFO rank 0 nranks 8
2018-12-10 20:43:58.572094: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
seyun:7761:8032 [3] NCCL INFO NET : Using interface eth0:115.145.178.160<0>
seyun:7761:8032 [3] NCCL INFO NET/IB : Using interface eth0 for sideband communication
seyun:7759:8029 [1] NCCL INFO NET : Using interface eth0:115.145.178.160<0>
seyun:7759:8029 [1] NCCL INFO NET/IB : Using interface eth0 for sideband communication
seyun:7760:8023 [2] NCCL INFO NET : Using interface eth0:115.145.178.160<0>
seyun:7760:8023 [2] NCCL INFO NET/IB : Using interface eth0 for sideband communication
seyun:7761:8032 [3] NCCL INFO Using internal Network Socket
seyun:7761:8032 [3] NCCL INFO rank 3 nranks 8
seyun:7759:8029 [1] NCCL INFO Using internal Network Socket
seyun:7759:8029 [1] NCCL INFO rank 1 nranks 8
seyun:7760:8023 [2] NCCL INFO Using internal Network Socket
seyun:7760:8023 [2] NCCL INFO rank 2 nranks 8
vclab-server-08:13673:13852 [0] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:13673:13852 [0] NCCL INFO NET/IB : Using interface eno2 for sideband communication
vclab-server-08:13673:13852 [0] NCCL INFO Using internal Network Socket
vclab-server-08:13673:13852 [0] NCCL INFO rank 4 nranks 8
vclab-server-08:13674:13855 [1] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:13674:13855 [1] NCCL INFO NET/IB : Using interface eno2 for sideband communication
vclab-server-08:13674:13855 [1] NCCL INFO Using internal Network Socket
vclab-server-08:13674:13855 [1] NCCL INFO rank 5 nranks 8
vclab-server-08:13675:13847 [2] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:13675:13847 [2] NCCL INFO NET/IB : Using interface eno2 for sideband communication
vclab-server-08:13675:13847 [2] NCCL INFO Using internal Network Socket
vclab-server-08:13675:13847 [2] NCCL INFO rank 6 nranks 8
vclab-server-08:13676:13846 [3] NCCL INFO NET : Using interface eno2:115.145.173.234<0>
vclab-server-08:13676:13846 [3] NCCL INFO NET/IB : Using interface eno2 for sideband communication
vclab-server-08:13676:13846 [3] NCCL INFO Using internal Network Socket
vclab-server-08:13676:13846 [3] NCCL INFO rank 7 nranks 8
==============================================================

Horovod Timeline 

==============================================================
https://github.com/LEESEYUN/horovod_debug.git
==============================================================

Same Problem is occur in pytorch !! 

I try hard to solve this problem. 

If you can advice this problem then I'll very appreciate your kindness!! 

Thank you!!

**Comment by LEESEYUN** [comment]
I try to reinstall the horovod with this option. Then I got increase the performance 

152 -> 300.18  But this is still slower than 1node 4gpu (608 or 884)

sudo HOROVOD_HIERARCHICAL_ALLREDUCE=1 HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/usr/local/nccl HOROVOD_WITH_TENSORFLOW=1 pip3 install --no-cache-dir horovod



==========================================================
80	images/sec: 37.5 +/- 0.1 (jitter = 0.6)	0.596	1.000	1.000
80	images/sec: 37.5 +/- 0.1 (jitter = 0.7)	1.051	0.844	1.000
80	images/sec: 37.6 +/- 0.1 (jitter = 0.6)	0.569	1.000	1.000
80	images/sec: 37.6 +/- 0.1 (jitter = 0.6)	0.567	1.000	1.000
80	images/sec: 37.6 +/- 0.1 (jitter = 0.7)	0.588	1.000	1.000
90	images/sec: 37.5 +/- 0.1 (jitter = 0.8)	2.702	0.438	1.000
90	images/sec: 37.5 +/- 0.1 (jitter = 0.7)	1.081	0.906	1.000
90	images/sec: 37.5 +/- 0.1 (jitter = 0.7)	1.943	0.500	1.000
90	images/sec: 37.5 +/- 0.1 (jitter = 0.7)	0.760	1.000	1.000
90	images/sec: 37.5 +/- 0.1 (jitter = 0.6)	0.806	0.891	1.000
90	images/sec: 37.5 +/- 0.1 (jitter = 0.6)	1.530	0.625	1.000
90	images/sec: 37.5 +/- 0.1 (jitter = 0.6)	0.871	0.922	1.000
90	images/sec: 37.5 +/- 0.1 (jitter = 0.7)	0.642	1.000	1.000
100	images/sec: 37.5 +/- 0.1 (jitter = 0.6)	0.590	1.000	1.000
----------------------------------------------------------------
total images/sec: 300.18
----------------------------------------------------------------
100	images/sec: 37.5 +/- 0.1 (jitter = 0.6)	0.675	0.906	1.000
=====================================================

**Comment by tgaddair** [comment]
Hey @LEESEYUN, it's possible that the network is simply the bottleneck here, in which case you might want to try using fp16 compression: 

```
opt = hvd.DistributedOptimizer(opt, compression=hvd.Compression.fp16)
```

Apart from that, it would be useful if you could create a timeline so we can see where Horovod is spending most of its time.

**Comment by LEESEYUN** [comment]
Thank you for reply

I fixed to compression=hvd.Compression.fp16 

But it is not significant increase the performance 

before 
=====================================
80	images/sec: 38.2 +/- 0.1 (jitter = 0.6)	0.991	0.844	1.000
80	images/sec: 38.2 +/- 0.1 (jitter = 0.5)	0.648	1.000	1.000
80	images/sec: 38.2 +/- 0.1 (jitter = 0.5)	0.611	1.000	1.000
80	images/sec: 38.2 +/- 0.0 (jitter = 0.5)	0.675	1.000	1.000
80	images/sec: 38.2 +/- 0.1 (jitter = 0.6)	1.176	0.844	1.000
80	images/sec: 38.2 +/- 0.0 (jitter = 0.4)	0.608	1.000	1.000
80	images/sec: 38.2 +/- 0.0 (jitter = 0.4)	0.581	1.000	1.000
80	images/sec: 38.2 +/- 0.0 (jitter = 0.4)	0.608	1.000	1.000
90	images/sec: 38.2 +/- 0.0 (jitter = 0.4)	1.273	0.719	1.000
90	images/sec: 38.2 +/- 0.1 (jitter = 0.5)	2.916	0.312	1.000
90	images/sec: 38.2 +/- 0.0 (jitter = 0.5)	1.043	0.750	1.000
90	images/sec: 38.2 +/- 0.1 (jitter = 0.5)	3.584	0.250	0.922
90	images/sec: 38.2 +/- 0.0 (jitter = 0.5)	0.803	0.891	1.000
90	images/sec: 38.2 +/- 0.1 (jitter = 0.6)	1.559	0.750	1.000
90	images/sec: 38.2 +/- 0.0 (jitter = 0.4)	2.000	0.609	1.000
90	images/sec: 38.2 +/- 0.0 (jitter = 0.4)	0.764	0.922	1.000
100	images/sec: 38.2 +/- 0.0 (jitter = 0.5)	0.807	0.938	1.000
----------------------------------------------------------------
total images/sec: 305.77
==================================



Fixed hvd.Compression.fp16
======================================
 80	images/sec: 68.0 +/- 0.5 (jitter = 3.3)	0.808	0.938	1.000
80	images/sec: 68.0 +/- 0.4 (jitter = 2.7)	0.650	1.000	1.000
80	images/sec: 68.0 +/- 0.4 (jitter = 2.7)	1.131	0.688	1.000
80	images/sec: 68.0 +/- 0.4 (jitter = 2.4)	0.850	0.875	1.000
80	images/sec: 67.9 +/- 0.5 (jitter = 2.6)	0.725	1.000	1.000
80	images/sec: 68.0 +/- 0.4 (jitter = 2.2)	0.662	1.000	1.000
80	images/sec: 67.9 +/- 0.5 (jitter = 2.1)	0.644	1.000	1.000
80	images/sec: 68.0 +/- 0.5 (jitter = 2.1)	0.650	1.000	1.000
90	images/sec: 68.0 +/- 0.4 (jitter = 2.6)	0.989	0.781	1.000
90	images/sec: 68.0 +/- 0.4 (jitter = 3.4)	1.099	0.906	1.000
90	images/sec: 68.0 +/- 0.4 (jitter = 2.4)	0.755	0.891	1.000
90	images/sec: 68.0 +/- 0.4 (jitter = 2.7)	1.843	0.656	1.000
90	images/sec: 68.0 +/- 0.4 (jitter = 2.2)	1.358	0.609	1.000
90	images/sec: 68.0 +/- 0.4 (jitter = 2.1)	0.766	1.000	1.000
90	images/sec: 68.0 +/- 0.4 (jitter = 2.8)	2.268	0.375	1.000
90	images/sec: 68.0 +/- 0.4 (jitter = 2.1)	0.990	0.766	1.000
100	images/sec: 67.9 +/- 0.4 (jitter = 2.1)	0.640	1.000	1.000
----------------------------------------------------------------
total images/sec: 543.54
======================================

First time I suspect that my network is the main bottleneck.
But I check the transmit and receive performance between my 2 computer with 'iperf3'
It shows that 1Gb. 

When I run the "tf_cnn_benchmark.py", I check the transmit and receive performance between my 2compter with ' bwm-ng'. And it shows that max transmit = 120mb, max receive =120mb. 
That means that there is a lot of rooms for transmit and receive performance... 

Q1. Could you tell me the version of openmpi and nccl?  my openmpi version is 4.0, nccl version is 2.3.7. 

Q2. Could you tell me that how can I solve this problem?

**Comment by alsrgv** [comment]
@LEESEYUN, what's your physical NIC performance?  Distributed deep learning is very spiky workload from the network standpoint - there's no communication during the forward pass, and during the backward pass it's still intermittent - that's one of the reason that average utilization may seem low.

**Comment by HydrogenQAQ** [comment]
@tgaddair Hey, when i use 16 GPUs(two nodes), If i using fp16 compression, images/secs ≈ 4534,  but there has 344 images/secs in 1 GPU, the speedup is too slow. When i do not use hvd.DistributedOptimizer(no sync), there has 5500 images/secs。

machine configuration:
Python: python3.6
pytorch: 1.0.0
horovod: 0.16.0

code: pytorch resnet50 example

mpirun -np 16 --bind-to socket -x LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=ib0,bond0,eth0 -x NCCL_SOCKET_FAMILY=AF_INET -x NCCL_IB_DISABLE=0 -x HOROVOD_MPI_THREADS_DISABLE=1 -tune env_for_user_process -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_include 192.168.0.0/16 /home/work/anaconda3/bin/python test.py --train-dir=./data/imagenet/train --fp16-allreduce=True --batches-per-allreduce=1 --batch-size=256

**Comment by alsrgv** [comment]
@HydrogenQAQ, what kind of NICs do you use for your training?  What kind of performance do you get without fp16 compression?  Can you share the output of NCCL debug messages?
