### ISSUE TITLE
horovod code refactor for new communication library support

### ISSUE THREAD

**Issue by LiweiPeng** [horovod/horovod#696]
Horovod supports several types of communication libraries to do allreduce operations, including NCCL, DDL, MPI etc. We are adding a new, internal libraries beyond the existing ones. The current horovod code design requires us to change many lines in common/operations.cc file. This makes it difficult for us to use new Horovod releases and features.

My request is: can Horovod refactor its code so that it is easier to add a new communication library (at NCCL level)? This can make it easy for us to use new Horovod releases/features.

Thanks.

**Comment by tgaddair** [comment]
Hey @LiweiPeng, coincidentally, this is something we have planned for this sprint after #616 is landed.  So should be done in the next couple of weeks.

**Comment by LiweiPeng** [comment]
this feature was completed since 0.16.2. So close this
