### ISSUE TITLE
horovod works fine with Tensorflow but not with Pytorch

### ISSUE THREAD

**Issue by sedghi** [horovod/horovod#715]
Hi,
I'm having difficulties running `pytorch_mnist.py` example. However, all other examples (tensorflow or keras) works great. 

I run `mpirun -np 2 python pytorch_mnist.py` and I get the following error:

`CUDA driver version is insufficient for CUDA runtime version at horovod/torch/cuda_util.cc:32`

Any comment is appreciated

**Comment by alsrgv** [comment]
@sedghi, sorry for delayed reply.  You need to upgrade NVIDIA driver on the host.
