### ISSUE TITLE
Horovod + PyTorch 1.0.0 failed at CentOS7

### ISSUE THREAD

**Issue by wangzhimingchn** [horovod/horovod#716]
I get a image from NVIDIA: docker.io/nvidia/cuda:9.0-cudnn7-devel-centos7 and install develop tools, NCCL and Open MPI 3.0.0.
The torch 1.0.0 is installed from pip. The horovod version is 0.15.2. Both build by self and from pip is failed.
# pip install numpy tensorboardX tqdm torch torchvision 
# pip list |grep torch
torch                        1.0.0
torchvision                  0.2.1
# git clone https://github.com/uber/horovod.git
# git checkout v0.15.2 -b v0.15.2
# HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_PYTORCH=1 python setup.py install

# python examples/pytorch_synthetic_benchmark.py
[e82f79a143a4:00142] *** Process received signal ***
[e82f79a143a4:00142] Signal: Segmentation fault (11)
[e82f79a143a4:00142] Signal code: Address not mapped (1)
[e82f79a143a4:00142] Failing at address: 0xb
[e82f79a143a4:00142] [ 0] /usr/lib64/libpthread.so.0(+0xf5d0)[0x7f68364485d0]
[e82f79a143a4:00142] [ 1] /usr/lib64/python2.7/site-packages/horovod/torch/mpi_lib_v2.so(+0x55fee)[0x7f67c581cfee]
[e82f79a143a4:00142] [ 2] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6df0)[0x7f6836739cf0]
[e82f79a143a4:00142] [ 3] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed)[0x7f683673c03d]
[e82f79a143a4:00142] [ 4] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x663c)[0x7f683673953c]
[e82f79a143a4:00142] [ 5] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed)[0x7f683673c03d]
[e82f79a143a4:00142] [ 6] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x663c)[0x7f683673953c]
[e82f79a143a4:00142] [ 7] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed)[0x7f683673c03d]
[e82f79a143a4:00142] [ 8] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x663c)[0x7f683673953c]
[e82f79a143a4:00142] [ 9] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x7ed)[0x7f683673c03d]
[e82f79a143a4:00142] [10] /usr/lib64/libpython2.7.so.1.0(PyEval_EvalCode+0x32)[0x7f683673c142]
[e82f79a143a4:00142] [11] /usr/lib64/libpython2.7.so.1.0(+0x10057f)[0x7f683675557f]
[e82f79a143a4:00142] [12] /usr/lib64/libpython2.7.so.1.0(PyRun_FileExFlags+0x7e)[0x7f683675673e]
[e82f79a143a4:00142] [13] /usr/lib64/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xe9)[0x7f68367579c9]
[e82f79a143a4:00142] [14] /usr/lib64/libpython2.7.so.1.0(Py_Main+0xc9f)[0x7f6836768b7f]
[e82f79a143a4:00142] [15] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f68359853d5]
[e82f79a143a4:00142] [16] python[0x40066e]
[e82f79a143a4:00142] *** End of error message ***

It is failed at hvd.broadcast_parameters(), the horovod function is at mpi_lib.
def _broadcast_async(tensor, output, root_rank, name):
    function = _check_function(_broadcast_function_factory, tensor)
    handle = getattr(mpi_lib, function)(
        tensor, output, root_rank, name.encode() if name is not None else _NULL)
    _handle_map[handle] = (tensor, output)
    return handle

Thanks!

**Comment by hujie-frank** [comment]
I meet the same problem.
