### ISSUE TITLE
Horovod profiling 

### ISSUE THREAD

**Issue by salemmohammed** [horovod/horovod#723]
Hi everybody,

I will attach the profiling for my experiment. 
<img width="1680" alt="screen shot 2018-12-27 at 5 52 25 pm" src="https://user-images.githubusercontent.com/6541193/50484235-7f16f700-0a00-11e9-9903-62a515cd4c51.png">

I have three machines with 4 layers fully connected neural network including input and output layer. 
when server 1 communicates with server 2 and when 2 communicates with 3, what exactly they communicate. I guess every worker communicate the layer which is a subset of the nn.

**Comment by salemmohammed** [comment]
@alsrgv Thanks for your reply.
how do you explain Horovod based on the following iteration scenario?

Total iteration time = time of computation + gradient communication after every iteration in synchronous model + combining the result with other receining results in global model + pulling the model back to the client from the server.

**Comment by alsrgv** [comment]
@salemmohammed, there's no 'server' in this model - it's doing ring allreduce. We have a paper published about Horovod - https://arxiv.org/abs/1802.05799, which may share more light.

In general, as gradients are computed, they are scheduled to be averaged in a distributed way. As such, frequently gradient averaging and computation will be interleaved.

Can you clarify what do you want to measure exactly?

**Comment by salemmohammed** [comment]
@alsrgv Thanks for your sharing. I read this paper and it's helpful.

I know there is an overlap between computation and communication time. The Horovod architecture is based on ring communication. Every peer communicates its gradients to its neighbor in one direction. Total communication for one iteration is 2(N-1) where N the number of nodes in the system.  I want to know the latency of communication of one iteration. I guess it's as the following 
latency time =  (model size / bandwidth between peers) * (2*(N-1))

**Comment by alsrgv** [comment]
In your timeline, you can expand each tensor and see moments of time when it was averaged. You will see the timing of various phases, with exact stages described [here](https://github.com/uber/horovod/blob/master/docs/timeline.md).

If you want to get aggregate information, you could programmatically process timeline file using a script to extract what you want.

**Comment by aruhela** [comment]
Did you create a script to process the timeline programmatically?
