### ISSUE TITLE
Barrier causes CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by YeYuanS** [horovod/horovod#728]
I trained my model on a 4 GPUs machine with command as following and it works good
`mpirun -np 4 python my_code.py`

However, when I tried to run part of my code on one GPU and set a BARRIER as following
```
if hvd.rank() ==0:
     #part of code
hvd.allreduce([0])
#part of code
```
It encounters the error that CUDA_ERROR_OUT_OF_MEMORY, seems like memory leaking
![screen shot 2019-01-02 at 5 16 35 pm](https://user-images.githubusercontent.com/41984177/50620070-3359c700-0eb2-11e9-821b-26c97252c4b8.png)

The tensorflow version I'm using is 1.5.0 and keras version is 2.1.3
Does anyone have some idea about this?

**Comment by alsrgv** [comment]
@YeYuanS, can you check which processes are using GPUs using `nvidia-smi` at a time of failure?

**Comment by YeYuanS** [comment]
@alsrgv Seems each process uses one GPU
![screen shot 2019-01-02 at 5 47 05 pm](https://user-images.githubusercontent.com/41984177/50620829-dad8f880-0eb6-11e9-81a7-d1699f205d65.png)

**Comment by alsrgv** [comment]
Did you add [GPU pinning code](https://github.com/uber/horovod/blob/master/examples/keras_imagenet_resnet50.py#L62) ?

**Comment by YeYuanS** [comment]
@alsrgv Yes, I added the following code in the beginning
```
    hvd.init()
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.gpu_options.visible_device_list = str(hvd.local_rank())
```

**Comment by alsrgv** [comment]
What about `K.set_session(tf.Session(config=config))`?

**Comment by alsrgv** [comment]
@YeYuanS, hard to say without looking at the code.  Is this K.set_session happening in the very beginning of the code?  Do you have any other code that creates sessions?

**Comment by YeYuanS** [comment]
@alsrgv Yes, I put K.set_session in the very beginning of the code. Actually, the situation which seems like memory leaking happens when other 1, 2, 3 processes reached the barrier while 0 process hasn't reached the barrier.

**Comment by alsrgv** [comment]
@YeYuanS, does your code or any of its dependencies use `device_lib.list_local_devices()`?  Sometimes it's used for logging, etc - but it actually makes TensorFlow grab all GPU memory it can find.

**Comment by YeYuanS** [comment]
@alsrgv Thanks for your reply! I really appreciate that. I also found that `device_lib.list_local_devices()` and `keras.clear_session()`  make TensorFlow grab all GPU memory, which would cause CUDA_ERROR_OUT_OF_MEMORY. But I solved those problems before I post this Issue. Anyway, thank you for your responsible replies. I will post if I found something new.
