### ISSUE TITLE
how to optimizer my ckpt files?

### ISSUE THREAD

**Issue by lostemples** [horovod/horovod#740]
when i trained my model. i got the ckpt files. as i use these files to test my model, i got the error message:KeyError: 'HorovodAllreduce'. 
can you give me an example to optimize the model.

**Comment by tgaddair** [comment]
Hey @lostemples, one issue that can arise when deserializing graphs with Horovod ops is that Horovod needs to be imported in order for the graph to deserialize properly. Not sure if this is the exact issue in your case, but do you `import horovod.tensorflow` somewhere in your script that's attempting to optimize your model?
