### ISSUE TITLE
Advice for model parallelism

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#746]
I am working on a problem (Knowledge graph embedding) in which the number of parameters may well exceed the memory of a single machine (without gpu). The model isn't complex but the number of parameters are too many (similar to word2vec). Is horovod a good option moving forward ? If not, please suggest some frameworks through which its feasible to do model parallelism. If yes, then please link some resources to get started.
P.S. I have used horovod to do data parallel training for my problem involving less number of parameters.

**Comment by alsrgv** [comment]
@UditGupta10, can you give an estimate of the amount of memory required to fit the embedding?

**Comment by UditGupta10** [comment]
Somewhere in the range of 30-40 GB.

**Comment by alsrgv** [comment]
@UditGupta10, sorry for delayed response.  I imagine you could partition your embedding onto multiple devices, e.g. by hashing entities and spreading them across 4 GPUs.  Would that work for your use case?
