### ISSUE TITLE
Horovod getting stuck with no error

### ISSUE THREAD

**Issue by gganes3** [horovod/horovod#747]
The following steps were done by me. Please let me know whether I should be doing anything different.
1. Installed TensorFlow, Keras and then Horovod succesfully on two different Ubuntu systems wherein each system has one GPU.
2. Made the ssh to both systems passwordless.
3. Tried running the Distributed training on the system(keras-mnist example) , however it is stuck with no error. 
$ mpirun -np 2\
    -H server1:1,server2:1 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python keras_mnist.py

**Comment by mr-ubik** [comment]
Have you configured the MPI cluster properly?
Have you made sure that you are using the proper net interface?

**Comment by gganes3** [comment]
Yes MPI ver. 4.0 on both servers. 
Yes, I am running it using TCP and made sure it is configured properly.

**Comment by gganes3** [comment]
I am using this link to set up MPI cluster configuration.
http://mpitutorial.com/tutorials/running-an-mpi-cluster-within-a-lan/
Is this the right one? Pls help.

**Comment by alsrgv** [comment]
@gganes3, can you check if this helps - https://github.com/uber/horovod/blob/master/docs/running.md#hangs-due-to-non-routed-network-interfaces ?

**Comment by gganes3** [comment]
I checked that. Still no luck. 
At the end, got this error " include/socket.h:196 WARN Connection closed by remote peer".

Just checking whether https://id-vision.net/detail/how-to-install-openmpi-on-linux-QIMAu_o_5V8.html is the right link to install openmpi?

**Comment by makseq** [comment]
Maybe you are not follow rules about ssh - it must not have password and any asks at the ssh login..
