### ISSUE TITLE
Horovod is not picking the right GPU

### ISSUE THREAD

**Issue by harishkool** [horovod/horovod#749]
I have 2 servers (for e.g., server1 and server2) both has 2 GPUs, I am trying to run my experiment from server1 to run it on server2. The thing is server1 has GPU 1 free and server2 has GPU 0 free, so when I am running my experiment from server1 to run on server2 it is always picking the GPU 1 of server2. I have set CUDA_VISIBLE_DEVICES, tried setting the variable in many different ways even though I am not unable to succeed.
Have used the following part in my code
config.gpu_options.visible_device_list = str(hvd.local_rank())

Thanks,
Harish

**Comment by alsrgv** [comment]
@harishkool, is it working correctly if you run the experiment directly from server2?  Can you check with `nvidia-smi` which GPUs are being used by the program (just one, or all of them)?

**Comment by harishkool** [comment]
sorry I have to take it back some of things from above.....I am actually facing error whenever I tried to run on two servers.
PFB details for the error:
Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!

I am getting this error whenever I am trying to run my experiments from server1 on server2.

Regards,
Harish
