### ISSUE TITLE
How does Horovod guarantee the allreduce call order across different ranks are the same for different tensors?

### ISSUE THREAD

**Issue by jianyinglang** [horovod/horovod#763]
For two different ranks, each rank could have different tensor call orders of the Allreduce. For example:
Rank0                                         Rank1
Allreduce(Tensor1)                  Allreduce(Tensor2)
Allreduce(Tensor2)                 Allreduce(Tensor3)
Allreduce(Tensor3)                 Allreduce(Tensor4)
Allreduce(Tensor4)                 Allreduce(Tensor1)
This different execution order will give MPI error because of the mismatch in the tensor shape (count). How does Horovod make sure the Allreduce happens for the same tensor?

Thanks!

**Comment by tgaddair** [comment]
Hey @jianyinglang, Horovod has rank 0 act as a "coordinator" for the allreduce process.  All other ranks report in which tensors they're ready to reduce, and based on that information, the coordinator decides which tensors are going to be reduced in what order.

See [operations.cc](https://github.com/uber/horovod/blob/master/horovod/common/operations.cc#L2117) for more details.

**Comment by jianyinglang** [comment]
Thanks @tgaddair ! I will check it for more details.
