### ISSUE TITLE
horovod hang after a few hours

### ISSUE THREAD

**Issue by ustcyue** [horovod/horovod#777]
Hi, I launched a four worker horovod training job using [k8s mpi-operator](https://github.com/kubeflow/mpi-operator). It runs normal for three hours and then hanged. the last output in log is:
![image](https://user-images.githubusercontent.com/2103334/51652836-f8881200-1fcb-11e9-937b-46d65fe3ae62.png)
Then there is no more output in the log and no checkpoint saving. But GPUs on all worker are still busy with 100% utility rate.
NCCL debug info is 
[debug.log](https://github.com/uber/horovod/files/2790143/debug.log)

There is only one network interface which is `eth0` in the docker and one `lo`

We had run successfully without any issue several times before, but this issue occur randomly. We also observed random speed degradation, like 1 in 100 iter is 20 times slower than normal when this issue happens.

**Comment by alsrgv** [comment]
@ustcyue, this looks like an intermittent network issue and/or node failure.  Did you observe either from your log?  Also, could you try upgrading NCCL to latest?  Technically, it should fail once there is a communication issue instead of locking down.

**Comment by ustcyue** [comment]
@alsrgv I haven't seen any sign of node failure or network issue. I will try upgrade NCCL.

**Comment by t13m** [comment]
Hi @ustcyue , I believe I'm having the same issue with you. Did the new version nccl solve it?
I'm running the "tensorflow:19.03" image provided by nvidia's "nvcr.io" repository on two machines (multiple gpus in each machine) with manually invoked "mpirun" command.
Usually after about 370k optimization steps (may be more or less than that), the training process will hang, no more log message in output, utility of all gpus are 100%, cpu usage is 15%, which is relatively low (40% during training).
I was wondering is there any theory about what happened here, and is there any workaround? Thanks.

versions
tensorflow:19.03
nccl: 2.4.3
horovod: 0.16.0
cuda: 10.1

**Comment by alsrgv** [comment]
@t13m, can you try to upgrade to NCCL 2.4.7?  It fixed a hang that may be affecting you.

**Comment by t13m** [comment]
Thanks @alsrgv , I tried v2.4.7 following your advice last weekend and it didn't solve the problem. The training progress still hangs at about 350k step and no error or logging messages. 
Is there any other way to try? or to get some diagnosis message?

**Comment by alsrgv** [comment]
@t13m, interesting. When it does hang, could you capture stack traces of all threads using gdb? `thread apply all bt`

**Comment by t13m** [comment]
[gdb.txt](https://github.com/horovod/horovod/files/3280297/gdb.txt)
Hi, call stacks are in attachment. It seems like deadlock in nsync?

**Comment by t13m** [comment]
In addition, about cpu usage (in hanging state). There are 10 worker processes on each machine. On one machine, there are 2 processes consume 200% cpu, 7 processes 100% cpu, and 1 process 12% cpu. On another one, there are 2 processes consume 200% cpu, 8 processes 100% cpu. Not sure if this helps.

Call stack of one of 200% processes has been attached in last post
Call stack of one of 100% processes : [gdb-100.txt](https://github.com/horovod/horovod/files/3280809/gdb-100.txt)
Call stack of the 12% process: [gdb-10.txt](https://github.com/horovod/horovod/files/3280808/gdb-10.txt)

**Comment by alsrgv** [comment]
It looks like it's hanging on NCCL kernel call.  Any chance that there could be a slow GPU memory leak that over time causes it to hang?  How does GPU memory utilization look like at the beginning of the training, and at the hang point?

**Comment by Frank1993** [comment]
> It looks like it's hanging on NCCL kernel call. Any chance that there could be a slow GPU memory leak that over time causes it to hang? How does GPU memory utilization look like at the beginning of the training, and at the hang point?

Hi @alsrgv, my job also hang after 216K steps. And cpu, memory and network are normal, and GPU utilization is 100%, but the used GPU memory suddenly decrease to 0%.

![image](https://user-images.githubusercontent.com/10986888/59993150-b26dd200-9681-11e9-9fd0-db50431179a6.png)

**Comment by alsrgv** [comment]
@Frank1993, do you have part of the chart where hang happens in the middle, i.e. half of the chart is before the hang and half of the chart is after the hang?
