### ISSUE TITLE
unable to start horovod

### ISSUE THREAD

**Issue by qiang13568** [horovod/horovod#781]
I am using a Ubuntu machine with 3 GPUs. when I try to run the example  tensorflow-mnist.py, I  have some trouble as following, 

![image](https://user-images.githubusercontent.com/18524705/51732965-e46f0e00-20ba-11e9-8937-87a528d12682.png)
![image](https://user-images.githubusercontent.com/18524705/51732988-f0f36680-20ba-11e9-86d5-3f7da8c32312.png)

all environments have been installed,including NCCL2 ,open MPI etc.  any suggestion ???

**Comment by qiang13568** [comment]
I directly copied and pasted the text with typesetting problems, so I pasted it into word and sent out the screenshot.

**Comment by tsmolcic** [comment]
How did you install Horovod?
Have you tried what the error output says, reinstall Horovod with `HOROVOD_WITH_TENSORFLOW=True`?

**Comment by qiang13568** [comment]
@tsmolcic 
yes, have installed horovod successfully. I am reinstalling Horovod immediately

**Comment by qiang13568** [comment]
@tsmolcic  
after I have finished what the console suggested, run as following , nothing happens,so that must Ctrl+c to kill it

**Comment by qiang13568** [comment]
@tsmolcic 
after I have finished what the console suggested, run as following , nothing happens,so that must Ctrl+c to kill it

mpirun -np 3 \
    -H localhost:3 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python3 tensorflow_mnist.py

**Comment by tsmolcic** [comment]
The second command doesn't run your code on 3 GPU-s, rather only on one.

Can you paste the full command you used to install Horovod?

**Comment by alsrgv** [comment]
In addition, could you try recommendations from https://github.com/uber/horovod/blob/master/docs/running.md ?

**Comment by qiang13568** [comment]
@alsrgv 
refer to "Hangs due to non-routed network interfaces", I change the orders 

![image](https://user-images.githubusercontent.com/18524705/51827551-a70db900-2324-11e9-931e-ad49c2f4a77d.png)

following are the configuration
![image](https://user-images.githubusercontent.com/18524705/51827653-dae8de80-2324-11e9-8301-013acff09ade.png)


both all failed
Could you give me some advice

**Comment by alsrgv** [comment]
@qiang13568, you need to keep routed interfaces.  Can you remove `enp15s0` from your parameters?  Also, can you make sure that you can `ssh localhost` w/o password?

**Comment by qiang13568** [comment]
@alsrgv @tsmolcic 
After various failed attempts, I uninstalled all the packages, reinstalled the programs, changed the versions of some of them, and it works

nccl 2.3.7 -> nccl 2.1.15
openmpi 3.1.1
cuda 9.0
cudnn 7.1.2

thanks for your suggestions and help, best wishes!
