### ISSUE TITLE
How to run model estimator with horovod on more than one docker

### ISSUE THREAD

**Issue by jaroslaw-wieczorek** [horovod/horovod#790]
I have a model based on tensorflow estimator and horovod  which I can run on one docker container. Data sets are placed directly in the dock container.  I have implemented a mechanism to divide the training set based on hvd.rank() and hvd.size() and pandas_input_fn. 
I try to run my model in more than one container. 
Analyzing the examples I'm not sure how to do it.  
Does each host contain code with the model? 
![obraz](https://user-images.githubusercontent.com/19189927/51867485-f4515100-234b-11e9-931f-d52bf20d7ca1.png)

Could I ask for a simple step-by-step example of how to run my model with two local docks, for example? 

I mean that the workers (hvd.rank() == 1, 2, 3, etc.) start working together, between containers. In other words, by running 8 employees of 4 per container numbered from 0 to 7. Improve me if I'm wrong, but is it possible? And does it require the use of nvidia-docker?

In the next stage I planned to run this prepared model in the cluster Kubernetes.

**Comment by biggerkim** [comment]
Hi，Have your problem solved?

**Comment by Mesilenceki** [comment]
the same question.

**Comment by tgaddair** [comment]
Hey everyone, for TensorFlow estimator, you can use the [example](https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist_estimator.py) script as a starting point.  I would also take a look at our example [Dockerfile](https://github.com/horovod/horovod/blob/master/Dockerfile.gpu) (we have pre-built versions on DockerHub you can use as well).  

From there, you can follow the instructions in [Horovod](https://github.com/horovod/horovod/blob/master/docs/docker.rst) on Docker to get started.  Yes, the code needs to be available in each container.

Let me know if you have any more specific questions I can help with.
