### ISSUE TITLE
Number of GPUs used in training

### ISSUE THREAD

**Issue by jw447** [horovod/horovod#792]
I'm trying to run the tensorflow_mnist from [horovod examples](https://github.com/uber/horovod/blob/master/examples/tensorflow_mnist.py). I'm running on centos server with 2 gpus but I think the timeline indicates that only one is being used.

![screen shot 2019-01-29 at 00 43 46](https://user-images.githubusercontent.com/20617304/51886716-f83a9e80-235e-11e9-83ad-7c1d549c9103.png)

However, the logs in [gist](https://gist.github.com/jw447/39b549d69d66219ae128236c044fcdd0) here indicates that two gpu devices were added and parameters got updated twice every step. I'm confused by the issue. Does anyone know how can I set the number of gpu to be used by horovod? Despite the -np value in mpirun?

**Comment by tgaddair** [comment]
Hey @jw447, looks like it's working correctly, though I can't say for sure since I don't have access to the entire timeline.  Have you tried checking `nvidia-smi` to verify GPU utilization?

**Comment by jw447** [comment]
Hi @tgaddair thank you for the suggestion. Sorry I couldn't get back to you earlier. I ran the mnist example again using the same setup and I'm attaching the timeline here so that you could take a look if time permits. Also I observe that both gpus are working with 8% - 20% capacity utilized during the training so I guess the program is fine. Maybe it is because the bug of tensor-flow timeline?

[timeline](https://www.dropbox.com/s/svj8ulxe9oirefh/timeline_01.json?dl=0)

**Comment by tgaddair** [comment]
Hmm, looks like you're using GPUs in the forward pass, but not during allreduce.  What version of Horovod are you using, and how did you install it?  Did you include NCCL?

**Comment by jw447** [comment]
I installed it via `pip install horovod`. I didn't include NCCL. I will try again with NCCL included.

**Comment by tgaddair** [comment]
Sounds good, please see the docs on [GPUs](https://github.com/uber/horovod/blob/master/docs/gpus.md) for more install instructions.
