### ISSUE TITLE
Issue with horovod timeline

### ISSUE THREAD

**Issue by lakshmiumenon** [horovod/horovod#798]
Hi,

$ HOROVOD_TIMELINE=/path/to/timeline.json mpirun -np 4 -x HOROVOD_TIMELINE python train.py

When I gave the above command,it is giving the following error.
unrecognized argument x

How to resolve this issue?

**Comment by tgaddair** [comment]
Hi @lakshmiumenon, could you paste or screenshot the exact input and output you get from running the command?  I am unable to reproduce the issue with the command you've provided (possibly the arguments are out of order).

**Comment by Jeffwan** [comment]
I experienced this issue in kubernetes. sometimes one line command have have issues, need good arrangement. 

I also suggest to use 
`mpirun -np 4 -x HOROVOD_TIMELINE=/path/to/timeline.json python train.py` to have a try
