### ISSUE TITLE
Horovod Dockerfile with python 2.7 EOL?

### ISSUE THREAD

**Issue by bapriddy** [horovod/horovod#808]
@alsrgv @tgaddair  I realize everyone must be busy but are there any plans to update the Dockerfile to python 3.6 or later since python 2.7 has an end of life date for Jan 2020.

 https://pythonclock.org/ 

I guess there is also a definitive split between ubuntu 16 vs 18.  18 supports cuda 10 but might not be useful of some older systems.

**Comment by maxhgerlach** [comment]
Python 2 support has been dropped by now.
