### ISSUE TITLE
Why does the Dockerfile uses 'devel' not the 'base'

### ISSUE THREAD

**Issue by gautamkmr** [horovod/horovod#812]
The Dockerfile is built on top of `nvidia/cuda:9.0-devel-ubuntu16.04` while official Tensorflow has been built on top of `nvidia/cuda:9.0-base-ubuntu16.04`

**Horovod Dockerfile**: https://github.com/uber/horovod/blob/master/Dockerfile#L1
**TensorFlow Dockerfile**: https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/tools/dockerfiles/dockerfiles/nvidia.Dockerfile#L38

**Comment by alsrgv** [comment]
@gautamkmr, to give us the flexibility to compile CUDA code if needed.  We're planning to add MXNet to the image, and it needs to be compiled from source.

That said, if there's a desire for smaller docker images from the community, we could start producing a separate image for each framework, which would make TF and PyTorch images smaller.

**Comment by gautamkmr** [comment]
@alsrgv  Thank you for prompt reply.

In fact I was trying to make it work on top of  base or run time nvidia docker but it was not going well. I will give another shot. IMHO having smaller docker image will always be welcomed by community :) 

At least TensorFlow it would make sense given that we are adding pip binary.

**Comment by gautamkmr** [comment]
Closing this for now, will revisit if I find any issue on building on top of base.
