### ISSUE TITLE
Does horovod (tensorflow) use Openmp to utilize multiple cores in CPU

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#814]
I am running Horovod (with tensorflow) on Cray XC40 and wanted to know how Horovod uses multithreading within a node to use multiple cores. Does it have its own implementation or does it delegate that to tensorflow?
P.S. This has nothing to do with inter node communications.

**Comment by tgaddair** [comment]
Hey @UditGupta10, in the case of multi-CPU training, it's not multithreading but rather multiprocessing.  You run a separate worker process for every "thread" of execution you want to use, and MPI handles the synchronization between processes.

There is still some amount of multithreading that takes place within Horovod even within a single MPI process.  TensorFlow itself uses multiple threads, and within Horovod we use separate threads for enqueuing new tensors and performing batched allreduce.  But this is separate from anything done by MPI.

Does that answer your question?

**Comment by UditGupta10** [comment]
Yes it partially answers the question. What kind of shared memory parallelism (like openmp) does horovod use? Could you link the source code where horovod uses multi threading. How to check the utilisation of cores.

**Comment by tgaddair** [comment]
You can see an example of shared memory using what MPI calls "windows" in the hierarchical allgather implementation [here](https://github.com/uber/horovod/blob/master/horovod/common/operations.cc#L932).  

Remember that Horovod itself does not spawn additional processes, the user spawns multiple processes when they specify `mpirun -np <N>` where N is the total number of worker processes.

Horovod's background thread can be found [here](https://github.com/uber/horovod/blob/master/horovod/common/operations.cc#L1695).  That thread is responsible for negotiating and then performing the allreduce.  

The timeline doesn't give you resource utilization info, it simply tells you how long each step in the process took.  The negotiation step will be primarily over MPI, so more CPU utilization, but may also be network bound.  You can certainly profile Horovod as you could any C++ application if you'd like more fine grained resource metrics.

**Comment by UditGupta10** [comment]
Thanks. I am using a Cray system which has a profiler 'craypat' but it requires an executable binary file and i am not sure how to do it with python. After searching on internet for long i haven't found a solution, please suggest a way to profile a distributed python code.

**Comment by AlexisEspinosaGayosso** [comment]
Dear @tgaddair , could you have a look to the following query:
https://github.com/horovod/horovod/discussions/4022

You seem to be very aware on how tensorflow threads may affect horovod distributed training speed, and then your input would be very valuable! Thanks.
