### ISSUE TITLE
Error message while runnning horovod-spark

### ISSUE THREAD

**Issue by abimur-123** [horovod/horovod#816]
While running the spark example, I get the following error messages for every epoch (image below). This happens even when I set `verbose=0` in the `horovod.spark.run` command
![image](https://user-images.githubusercontent.com/14052278/52371364-49aff100-2a23-11e9-9316-be2de7ec3599.png)

Trying to figure out what this error message means

**Comment by alsrgv** [comment]
@abimur-123, it seems that you're running in docker container.  Can you run your container in `-privileged` mode? These messages are harmless but are annoying.
