### ISSUE TITLE
Horovod hangs using containers on multiple hosts.

### ISSUE THREAD

**Issue by gautamkmr** [horovod/horovod#819]
I am trying to run `multiple machine` example from [here](https://github.com/uber/horovod/blob/master/docs/docker.md).

I have two hosts (A and B) each with 8 GPUs. I've enabled passwordless ssh from host A (master to host B as well as passwordless ssh to itself (ssh localhost). 

**Command on host A**
Host A had three interface 'docker0, ens3 and lo'
`nvidia-docker run -it --network=host -p 12345:12345  -v /home/ubuntu/.ssh/:/root/.ssh uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py3.5`

` mpirun -np 8 -H localhost:4,<host B ip>:4 --allow-run-as-root --display-map --tag-output --timestamp-output -mca btl_tcp_if_exclude lo,docker0    -mca plm_rsh_args "-p 12345" -x NCCL_SOCKET_IFNAME=ens3   python keras_mnist_advanced.py`

**Command on host B**
` nvidia-docker run -it --network=host  -p 12345:12345  -v /home/ubuntu/.ssh/:/root/.ssh uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py3.5  bash -c "/usr/sbin/sshd -p 12345; sleep infinity"`

Once I run the above command it just hangs without any error or output.

**Comment by gautamkmr** [comment]
@alsrgv  Any help on what I might be missing here?

**Comment by alsrgv** [comment]
@gautamkmr, you may have wrong permissions on your `.ssh` folder and its files (they're all supposed to be owned by root for ssh to accept the key), can you check that you can do ssh between docker containers (instead of hosts) and possibly fix permission issues?

**Comment by gautamkmr** [comment]
Thanks that helps to resolve the issue.

**Comment by gautamkmr** [comment]
However it requires to change the permission for ~/.ssh to root:root and sometime it becomes difficult to connect to that instance. 

I was thinking of other way to put these keys in some other folder and change the permission there and mount that folder to container as volume but that did not work.
