### ISSUE TITLE
horovod：mpirun was unable to start the specified application

### ISSUE THREAD

**Issue by qiang13568** [horovod/horovod#821]
hardware env: a server with 3GPUs

I want to test the official samples, but something wrong, commands as following:

```
mpirun -np 3 \
    -H localhost:3 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -x NCCL_SOCKET_IFNAME=^lo,docker0,enp15s0 \
    -mca btl_tcp_if_exclude lo,docker0,enp15s0 \
    -mca pml ob1 -mca btl ^openib \
    -mca plm_rsh_args \
    python3 /home/hwq/tensorflow_mnist.py 
```
Open MPI tried to fork a new process via the "execve" system call but failed.  Open MPI checks many things before attempting to launch a child process, but nothing is perfect. This error may be indicative
of another problem on the target host, or even something as silly as having specified a directory for your application. Your job will now abort.

 Local host:Server712
 Working dir:/home/hwq
 Application name:/home/hwq/tensorflow_mnist.py
 Error:Exec format error
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun was unable to start the specified application as it encountered an
error:

Error code: -125
Error name: The specified application failed to start
Node: Server712
 
when attempting to start process rank 0
--------------------------------------------------------------------------
3 total processes failed to start
[Server712:27557] 2 more processes have sent help message help-orte-odls-default                                                                                                                                                             .txt / execve error
[Server712:27557] Set MCA parameter "orte_base_help_aggregate" to 0 to see all h                                                                                                                                                             elp / error messages
hwq@Server712:~$

when I set parameter "orte_base_help_aggregate" to 0, the console prompts as following:

```
mpirun -np 3 \
    -H localhost:3 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -x NCCL_SOCKET_IFNAME=^lo,docker0,enp15s0 \
    -mca btl_tcp_if_exclude lo,docker0,enp15s0 \
    -mca pml ob1 -mca btl ^openib \
    -mca plm_rsh_args \
    -mca orte_base_help_aggregate=0 \
    python3 /home/hwq/tensorflow_mnist.py
```
mpirun was unable to find the specified executable file, and therefore did not launch the job.  This error was first reported for process rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command line parameter option (remember that mpirun interprets the first unrecognized command line token as the executable).

Node:       Server712
Executable: orte_base_help_aggregate=0
--------------------------------------------------------------------------
3 total processes failed to start
hwq@Server712:~$

some suggestions ?
Firstly, I dont know how find out the non-routed interfaces like lo,docker0
secondly, command "orte_base_help_aggregate" is set incorrectly,but I dont know the right way
thirdly, openMPI is installed successfully, test it in hello_c , showed as following,

hwq@Server712:~$ mpirun -np 3 /home/hwq/openmpi-3.1.1/examples/hello_c
Hello, world, I am 1 of 3, (Open MPI v3.1.1, package: Open MPI hwq@Server712 Distribution, ident: 3.1.1, repo rev: v3.1.1, Jun 29, 2018, 108)
Hello, world, I am 0 of 3, (Open MPI v3.1.1, package: Open MPI hwq@Server712 Distribution, ident: 3.1.1, repo rev: v3.1.1, Jun 29, 2018, 108)
Hello, world, I am 2 of 3, (Open MPI v3.1.1, package: Open MPI hwq@Server712 Distribution, ident: 3.1.1, repo rev: v3.1.1, Jun 29, 2018, 108)

hwq@Server712:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:36:cd:34:b4
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eno1      Link encap:Ethernet  HWaddr 10:7b:44:b0:b5:99
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:20 Memory:fb700000-fb720000

enp15s0   Link encap:Ethernet  HWaddr 10:7b:44:b0:b5:9a
          inet addr:192.168.10.195  Bcast:192.168.10.255  Mask:255.255.255.0
          inet6 addr: fe80::9dea:8361:b758:c0ae/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:370515 errors:0 dropped:0 overruns:0 frame:0
          TX packets:596693 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:213487281 (213.4 MB)  TX bytes:810120290 (810.1 MB)
          Memory:fb300000-fb37ffff

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:146252 errors:0 dropped:0 overruns:0 frame:0
          TX packets:146252 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:384702511 (384.7 MB)  TX bytes:384702511 (384.7 MB)

**Comment by qiang13568** [comment]
[https://github.com/uber/horovod/issues/98#issuecomment-345536375](url) the nccl test runs successfully

**Comment by alsrgv** [comment]
@qiang13568, you need to remove "-mca plm_rsh_args". Currently, that parameter consumes `python3` argument and mpirun is trying to run python file directly.

**Comment by qiang13568** [comment]
@alsrgv 
At first,there is no the parameter, but the program hung up without any prompt, and after refering to many documents, added the parameter, and then the program appeared some error messages
#781

**Comment by alsrgv** [comment]
Got it. Let's keep debugging there - I will close this issue.
