### ISSUE TITLE
mxnet plugin error after success build

### ISSUE THREAD

**Issue by douzsh** [horovod/horovod#823]
With mxnet plugin , I have to build from source.
I build successfully with command
`HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_MXNET=1 python setup.py install`
envs: NCCL 2.4.2 openMPI:3.1.2 CUDA:9.0

I got following error when load horovod with command `import horovod.mxnet as hvd`

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zesheng.dzs/anaconda/lib/python3.6/site-packages/horovod-0.15.2-py3.6-linux-x86_64.egg/horovod/mxnet/__init__.py", line 25, in <module>
    from horovod.mxnet.mpi_ops import allgather
  File "/home/zesheng.dzs/anaconda/lib/python3.6/site-packages/horovod-0.15.2-py3.6-linux-x86_64.egg/horovod/mxnet/mpi_ops.py", line 29, in <module>
    _basics = _HorovodBasics(__file__, 'mpi_lib')
  File "/home/zesheng.dzs/anaconda/lib/python3.6/site-packages/horovod-0.15.2-py3.6-linux-x86_64.egg/horovod/common/__init__.py", line 56, in __init__
    self.MPI_LIB_CTYPES = ctypes.CDLL(full_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/zesheng.dzs/anaconda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/zesheng.dzs/anaconda/lib/python3.6/site-packages/horovod-0.15.2-py3.6-linux-x86_64.egg/horovod/mxnet/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5mxnet12on_enter_apiEPKc`

**Comment by alsrgv** [comment]
cc @apeforest, @yuxihu

**Comment by yuxihu** [comment]
@douzsh which mxnet package are you using? Did you build from source? which commit?

**Comment by douzsh** [comment]
> @douzsh which mxnet package are you using? Did you build from source? which commit?

My mxnet is installed from pip with command
`pip install mxnet-cu90 --pre`

**Comment by yuxihu** [comment]
@douzsh When did you install mxnet? Older mxnet nightly package does not have the symbol exposed. Can you rerun the command in your environment?

In addition, which OS are you running on? If you are running on an OS with GCC 5.X, we recommend to build mxnet from source. Please see [note](https://github.com/horovod/horovod#mxnet).

**Comment by yuxihu** [comment]
@douzsh There might be some issue with our nightly pip package for cu90. We are investigating. In the meanwhile, please build mxnet from source.

**Comment by douzsh** [comment]
@yuxihu Is it possible for me to use a stable version of mxnet? 
Build from source will cost some time.

**Comment by yuxihu** [comment]
@douzsh  The first MXNet release that supports Horovod will be 1.4.0, which will be coming soon. Even with the MXNet 1.4.0 release, you may still need to build mxnet from source due to GCC incompatibility issue if the GCC version is 5.x or above in your OS (e.g. Ubuntu 16.04). 

If the GCC version is 4.x in your OS, you can use the mxnet nightly pip package and the upcoming 1.4.0 release. But there is some issue in the nightly package now. We are trying to fix ASAP. I will let you know once it is ready.

**Comment by douzsh** [comment]
@yuxihu Thanks a lot!
I'll try to build from source later. Hope you can publish upgraded MXNet ASAP ^-^

**Comment by douzsh** [comment]
I can import hvd.mxnet successfully after rebuild mxnet from source. 
close the issue.
