### ISSUE TITLE
Horovod install fails with Tensorflow 1.13

### ISSUE THREAD

**Issue by armandmcqueen** [horovod/horovod#825]
I am unable to install Horovod on top of Tensorflow 1.13 (rc0, rc1 or built from source). This is the failure we see:

`distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1`

More detail:

`This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer headers.  Please update your headers.`

Is this an issue that needs to be resolved within Horovod, or is this an issue with the install env that I can fix on my side? I've tried some of the obvious solutions, like upgrading protoc locally to match TF 1.13's CI setup, but I haven't made any progress.

**Comment by armandmcqueen** [comment]
This was an issue on my side. I needed to upgrade protoc to 3.6.1 for TF 1.13 and I wasn't doing it correctly.

Steps for installing 3.6.1 if anyone else has this issue: https://gist.github.com/ryujaehun/991f5f1e8c1485dea72646877707f497

**Comment by jw447** [comment]
Did yo enabled mxnet and pytorch when building? I got this error "error: TensorFlow, PyTorch, and MXNet plugins were excluded from build. Aborting." When i set HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1
