### ISSUE TITLE
errors when installing Horovod on aarch64

### ISSUE THREAD

**Issue by TonyTangYu** [horovod/horovod#829]
I want to install Horovod on an aarch64 Linux. But when I run the command `PATH=/usr/local/bin:$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH  HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 MSHADOW_USE_CUDA=0 HOROVOD_MPICXX_SHOW="/usr/local/mpi3/bin/mpicxx -show" INCLUDES=['mxnet git directory'/python/mxnet/include] LIBRARY_DIRS=['mxnet git directory'/lib] /home/ubuntu/anaconda3/bin/pip install --upgrade -v --no-cache-dir ['horovod git directory']`, I met the following error.

>  /vol7/home/zqlai/ty/mxnet/python/mxnet/include/mshadow/././././extension/../packet/sse-inl.h:10:23: fatal error: emmintrin.h: No such file or directory
     #include <emmintrin.h>
                           ^
    compilation terminated.
    command 'gcc' failed with exit status 1
    INFO: Unable to build MXNet plugin, will skip it.

I took the steps [here](https://github.com/ctcyang/incubator-mxnet/tree/horovod_feature/example/image-classification/scripts) building Mxnet and Horovod. 
Could anyone help me fix it? Thank you in advance!

**Comment by alsrgv** [comment]
cc @apeforest @yuxihu to take a look

**Comment by yuxihu** [comment]
@TonyTangYu The instructions you were following is out of date. If you GCC version is 4.x, you can follow these steps to install Horovod:
```
pip install <mxnet_pip_package> --pre
git clone --recursive https://github.com/uber/horovod.git
HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITH_MXNET=1 pip install --no-cache-dir <horovod_dir>
```

**Comment by TonyTangYu** [comment]
@yuxihu  What if I installed mxnet through source?

**Comment by yuxihu** [comment]
Here is the [guide ](http://mxnet.incubator.apache.org/versions/master/install/build_from_source.html)to build MXNet from source. Then you can install Horovod as:
```
pip install --no-cache-dir horovod
```

**Comment by TonyTangYu** [comment]
@yuxihu  Thank you for response! I have installed MXNet from source.  Now when I install Horovod, it gives me the following error:

> horovod/mxnet/mpi_ops.cc: In function ‘void horovod::mxnet::InvokeCompleteCallback(horovod::mxnet::Callback, const horovod::common::Status&)’:
    horovod/mxnet/mpi_ops.cc:47:23: error: no match for call to ‘(horovod::mxnet::Callback {aka mxnet::engine::CallbackOnComplete}) (dmlc::Error*)’
         on_complete(&error);
                           ^
    In file included from horovod/mxnet/mpi_ops.h:22:0,
                     from horovod/mxnet/mpi_ops.cc:21:
    /vol7/home/zqlai/ty/mxnet/python/mxnet/include/mxnet/engine.h:73:7: note: candidate is:
     class CallbackOnComplete {
           ^
    /vol7/home/zqlai/ty/mxnet/python/mxnet/include/mxnet/engine.h:77:15: note: void mxnet::engine::CallbackOnComplete::operator()() const
       inline void operator()() const {
                   ^
    /vol7/home/zqlai/ty/mxnet/python/mxnet/include/mxnet/engine.h:77:15: note:   candidate expects 0 arguments, 1 provided
    INFO: Unable to build MXNet plugin, will skip it.

What should I do to fix it? Thank you inadvance!

**Comment by yuxihu** [comment]
@TonyTangYu It looks like you are building MXNet from source with a commit which does not support Horovod yet. Which branch/commit did you use to build MXNet? We recommend you to use the latest master.

**Comment by TristonC** [comment]
Has this problem been solved @TonyTangYu ?
