### ISSUE TITLE
How to run more than 1 process on a single gpu/cpu

### ISSUE THREAD

**Issue by UditGupta10** [horovod/horovod#839]
Hi, I am familiar with running horovod on multigpu systems where each process is run on separate gpu. What changes need to be made to the command line and code such that we can spawn more than 1 process on a single gpu.
P.S. This is for debugging purpose only.

**Comment by tsmolcic** [comment]
I'm not familiar if you can do this with Horovod, but you might find this useful: https://docs.nvidia.com/deploy/mps/index.html

**Comment by alsrgv** [comment]
@UditGupta10, you'd have to specify `allow_growth`, [like so](https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist.py#L140), and make sure multiple processes will end up pointing to the same GPU (e.g. by using `hvd.local_rank() % gpus_per_server`).

**Comment by alsrgv** [comment]
Note though, that NCCL may deadlock if you run multiple NCCL ranks on the same GPU.

**Comment by THULiusj** [comment]
@alsrgv ,Hi, I'm tesing multiple processes with Horovod on single GPU, but failed. Can you explain why NCCL may deadlock if I run multiple NCCL ranks on the same GPU? I remember NCCL can support multiple ranks.
