### ISSUE TITLE
Scaling Efficiency for deep fully connected neural network 

### ISSUE THREAD

**Issue by YeYuanS** [horovod/horovod#849]
I tried to use Horovod to train a four-layer fully connected neural network on a `4-GPU` machine(each machine train on 1/4 training data and evaluate on same evaluation dataset) and the speed performance was only like `20%` better than training on `1-GPU` machine. Is that because fully connected neural network is hard to parallelize or I'm doing something wrong?

**Comment by alsrgv** [comment]
@YeYuanS, how many batches per second does your 4-layer FC model process on GPU?  Most likely communication overhead dominates if this number is large.
