### ISSUE TITLE
how to sync variable if I use  tf.Session?

### ISSUE THREAD

**Issue by scotthuang1989** [horovod/horovod#855]
In the example,  horovod use:

> hvd.BroadcastGlobalVariablesHook(0)

to sync variable at the beginning of training, but only 

> tf.train.MonitoredTrainingSession

 accept hooks as parameter?

Is there native support for **tf.Session?**

**Comment by ppwwyyxx** [comment]
`sess.run()` this op:
https://github.com/horovod/horovod/blob/ca3c1e38798ddfad56d714eaef6ddcfd14fe6bdf/horovod/tensorflow/__init__.py#L95-L102

**Comment by scotthuang1989** [comment]
thanks. It works .
