### ISSUE TITLE
Data column features has not been analyzed yet,

### ISSUE THREAD

**Issue by karlbernard2** [horovod/horovod#856]
I've been successful fitting a HorovodEstimator
However when I call transform, I get:
 
java.lang.Exception: Data column features has not been analyzed yet, cannot run TF on this dataframe

My features column is a Dense Vector generated from a  VectorAssembler in a Pipeline.

If I try
`df = tfs.analyze(df_with_val)`
`tfs.print_schema(df)`

I get 

>  |-- features: vector (nullable = true) <no tensor info>

I'm not sure what to do and I am stuck, any advice?

**Comment by alsrgv** [comment]
@karlbernard2, I assume you're using Databricks platform - in which case it's best to contact their support.
