### ISSUE TITLE
multi-gpu seems to be slower. how to use estimator API to increase train speed

### ISSUE THREAD

**Issue by vangogh0318** [horovod/horovod#859]
Running tensorflow_mnist_estimator.py code, I found that there is no linear acceleration， and I also read the related discussion #71 . (running larger-scale CNN benchmarks which show scaling.)

but I have a question,  if I want to use estimator api, how should I modify the estimator code to increase trainning speed? thank you.
Now I am modifying the bert code （support distributed） , so the model is complicated

**Comment by alsrgv** [comment]
@vangogh0318, larger models should have better scaling. Please share your findings of modifying BERT model.

**Comment by alsrgv** [comment]
cc @abditag2 @tgaddair

**Comment by Mesilenceki** [comment]
> Running tensorflow_mnist_estimator.py code, I found that there is no linear acceleration， and I also read the related discussion #71 . (running larger-scale CNN benchmarks which show scaling.)
> 
> but I have a question, if I want to use estimator api, how should I modify the estimator code to increase trainning speed? thank you.
> Now I am modifying the bert code （support distributed） , so the model is complicated

hi, How do you config estimator with horovod? with kubenetes?
