### ISSUE TITLE
Run Horovod using MPI inside container?

### ISSUE THREAD

**Issue by wedsall** [horovod/horovod#863]
Hello group,
 Is it possible to run Horovod using the mpirun that's inside the Singularity container? This would make the container fully portable.

**Comment by alsrgv** [comment]
@wedsall, running Horovod in Singularity should be similar to running other MPI programs.  We do not have experience (or user guide) with Singularity, but if you make it would it'd be great if you can publish the steps.

**Comment by zrss** [comment]
@wedsall , hi wedsall, u can check this out [mpi-operator](https://github.com/kubeflow/mpi-operator)
