### ISSUE TITLE
Deeplab with Horovod 

### ISSUE THREAD

**Issue by naveenmiriyalu** [horovod/horovod#864]
Hi ,
I am trying to use Deeplab (https://github.com/tensorflow/models/tree/master/research/deeplab) with Horovod.  I am following the example (https://github.com/horovod/horovod/README.md). 

I am at this step of creating a hook and we must then pass it to the tf.train.MonitoredTrainingSession . The steps I have pasted from the tutorial .

But from Deeplab code perspective ,train.py uses slim.train located here /anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py. It uses the Supervisor API to run a session . 

1.How do I pass the hook in this scenario ?
2. Should I convert the code to use tf.train.MonitoredTrainingSession only ? 
3. Is there an alternative way other than hooks to use the current code to enable Horovod?

 sv = supervisor.Supervisor(
      graph=graph,
      is_chief=is_chief,
      logdir=logdir,
      init_op=init_op,
      init_feed_dict=init_feed_dict,
      local_init_op=local_init_op,
      ready_for_local_init_op=ready_for_local_init_op,
      ready_op=ready_op,
      summary_op=summary_op,
      summary_writer=summary_writer,
      global_step=global_step,
      saver=saver,
      save_summaries_secs=save_summaries_secs,
      save_model_secs=save_interval_secs,
      init_fn=init_fn)

Steps to enable a model with Horovod:
--Add hook to broadcast variables from rank 0 to all other processes during initialization.
hooks = [hvd.BroadcastGlobalVariablesHook(0)]

Now ,
-- The MonitoredTrainingSession takes care of session initialization,restoring from a checkpoint, saving to a checkpoint, and closing when done or an error occurs.
with tf.train.MonitoredTrainingSession(checkpoint_dir=checkpoint_dir,
                                       config=config,
                                       hooks=hooks)

**Comment by UditGupta10** [comment]
The word2vec example `https://github.com/horovod/horovod/blob/master/examples/tensorflow_word2vec.py`
does not use hooks, hope this helps.
