### ISSUE TITLE
Question about manual seed in PyTorch

### ISSUE THREAD

**Issue by hubutui** [horovod/horovod#866]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.0.1
3. Horovod version: 0.16.0
4. MPI version: 3.1.2
5. CUDA version: 10.0
6. NCCL version: 1.3.5
7. Python version: 3.6.8
8. OS and version: Ubuntu 16.04

**Your question:**
In the pytorch example, https://github.com/horovod/horovod/blob/master/examples/pytorch_mnist.py#L35, and https://github.com/horovod/horovod/blob/master/examples/pytorch_mnist.py#L40, you set manual seed twice. Is there any particular consideration? According to pytorch doc, https://pytorch.org/docs/stable/notes/randomness.html#pytorch, `torch.manual_seed()` seed the RNG for all devices (both CPU and CUDA). Also, do I need to call this?:
```python
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
np.random.seed(0)
```

**Comment by tgaddair** [comment]
Hey @hubutui, my understanding is that there are subtle differences between `torch.manual_seed()` and `torch.cuda.manual_seed()`.  Namely, that `torch.cuda.manual_seed()` will guarantee determinism for on-GPU generation of random numbers like `torch.cuda.FloatTensor(100).uniform_()` ([source](https://discuss.pytorch.org/t/difference-between-torch-manual-seed-and-torch-cuda-manual-seed/13848)).

After reading up on `torch.backends.cudnn.deterministic`, I would agree with setting that to `True` if you need the guaranteed determinism (at possible expense of performance).
