### ISSUE TITLE
hvd.size() doesn't change when multiple mpi/horovod processes are executed

### ISSUE THREAD

**Issue by AnkBurov** [horovod/horovod#870]
**Environment:**
1. Framework: Keras
2. Framework version: 2.2.4
3. Horovod version: 0.16.0
4. MPI version: mpich 3.2
5. CUDA version: -
6. NCCL version: -
7. Python version: 3.6.2
8. OS and version: Ubuntu 18.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
* https://github.com/horovod/horovod/issues/822

**Your question:**
Hi, when I'm trying to execute multiple MPI processes to use distributed learning model I get replicated Keras models instead of one distributed model across all MPI processes. If I print `hvd.size()` value, it says that its value is 1 on all MPI processes. So executing 
`mpirun -np 2 -bind-to none -map-by slot -genv NCCL_DEBUG INFO -envlist LD_LIBRARY_PATH,PATH python3 horovod_fashion_mnist.py` 
says
`Horovod size is 1`
`Horovod size is 1`
instead of `Horovod size is 2`

I've also tried to execute mpirun on multiple physical servers (like that `-hosts username@server1,127.0.0.1` and got the same results - `hvd.size()` is 1 everywhere hence no distributed model and learning. I've tried to delete virtual env several times to make sure that Horovod is installed with a correct MPI implementation, but it didn't help either. 

Any ideas why Horovod doesn't detect other MPI processes? Thanks!

**Comment by alsrgv** [comment]
@AnkBurov, do you have any Open MPI or any other MPI version installed separately from your normal MPICH?  This seems like conflict between two MPI implementations.
