### ISSUE TITLE
What's the reasonable NEGOTIATE_ALLREDUCE duration?

### ISSUE THREAD

**Issue by Jeffwan** [horovod/horovod#871]
**Environment:**

1. Container Image: uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py2.7
2. Machines:  AWS P3.16xlarge V100-SXM2 16GB in placement group
3. Storage: Lustre (use AWS FSx) and ebs (Provisioned IOSP SSD). The following examples are against Lustre. 

**Checklist:**
1. Did you search issues to find if somebody asked this question before? yes

**Your question:**

I am trying to reproduce Resnet50 benchmark on kubernetes cluster with real data set. The goal is to get 90% scaling efficiency for more than 160 gpus. I got pretty close result between ebs and lustre and I think storage is not the bottleneck (I also tried EFS and it's obvious worse)

8 Gpus     750.3/gpu   6001.19/total    100%
16 Gpus   693.3/gpu    11090.10/total  92.4%
32 Gpus   584.3/gpu    18695.00/total  77.88%  

I tried more gpus but it won't give me good performance, I stopped at 4 machines and diagnose problems. 

1. For 32 Gpus (4 machines), based on timeline, looks like every a few seconds, there're few NEGOTIATE_ALLREDUCE taking long regularly. I think this might be the reason I cannot get linear scalability?  those small bars NEGOTIATE_ALLREDUCE also takes ~150ms, is it too long? 
I also measure GPU Utilization at the same time, it's not full and some of gpu can not hit 95%

![image](https://user-images.githubusercontent.com/4739316/53534227-ca0dc300-3ab2-11e9-8d6f-23d02b78d0b5.png)

2. I am not sure if RING topology matters here. I set MIN_RING = 8 but I can not control rank in every  ring? Seems in every ring, there's four `NET/Socket/0` connections and all rests are via `P2P/IPC`. Anything I can improve here?

```
ip-192-168-71-135:19:1059 [0] NCCL INFO Ring 00 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15  16  17  19  18
ip-192-168-71-135:19:1059 [0] NCCL INFO Ring 01 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15  16  17  19  18
ip-192-168-71-135:19:1059 [0] NCCL INFO Ring 02 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15  16  17  19  18
ip-192-168-71-135:19:1059 [0] NCCL INFO Ring 03 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15  16  17  19  18
ip-192-168-71-135:19:1059 [0] NCCL INFO Ring 04 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15  16  17  19  18
ip-192-168-71-135:19:1059 [0] NCCL INFO Ring 05 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15  16  17  19  18
ip-192-168-71-135:19:1059 [0] NCCL INFO Ring 06 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15  16  17  19  18
ip-192-168-71-135:19:1059 [0] NCCL INFO Ring 07 :    0   1   3   2   6   4   5   7   8   9  11  10  14  12  13  15  16  17  19  18
```
Full logs here.  https://gist.github.com/Jeffwan/ab55b42ee47f67a217217c34b776b611

3.  I meet several warning like this, batch 256 should be fine on V100 GPU but not sure why it complains OOM issue. if this could be a performance issue?

```
2019-02-28 18:05:17.811849: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.34GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
```

### Setting:

```
mpirun
-mca btl_tcp_if_exclude, lo,docker0,
-mca pml,ob1
-mca btl,^openib,
--bind-to none,
-map-by slot,
-x LD_LIBRARY_PATH,
-x PATH,
-x NCCL_DEBUG=INFO,
-x NCCL_MIN_NRINGS=8,
-x HOROVOD_FUSION_THRESHOLD=16777216,
-x HOROVOD_TIMELINE=/timeline/timeline.json

```

### My Job Spec:
```
- python
- scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
- --data_format=NCHW
- --batch_size=256
- --model=resnet50
- --num_batches=200
- --optimizer=sgd
- --variable_update=horovod
- --horovod_device=gpu
- --data_name=imagenet
- --use_fp16
- --nodistortions
- --num_intra_threads=8
- --num_inter_threads=8
- --data_dir=/data/imagenet
- --datasets_use_prefetch=True
- --gpu_thread_mode=gpu_shared
- --gradient_repacking=8
- --datasets_use_caching=true
- --datasets_num_private_threads=8
```

**Comment by ustcyue** [comment]
@Jeffwan What we found is that horovod timeline is recorded at host side, which cannot always show the real problem. You'd better dump the tensorflow timeline and look at the execution timeline on GPU.

**Comment by Jeffwan** [comment]
@ustcyue 

I check GPU utilization, it's not always above 90% level and it comes intermittent drop down then I suspect CPU side may blocker. 

I check CPU utilization rate.  Seems each process uses 450~550% cpu in these cases. The machine I use has 8 gpus and 64 cpus. I tried different parameters like inter_op and intra_op but can not utilize full CPU resource. It's probably the IO limitation? I tried local disk and it's same utilization rate level. 

Do you have any insights?

**Comment by ustcyue** [comment]
@Jeffwan did you try synthetic data? Is scaling efficiency the same? Also did you compare performance of single card and 8 card on the same machine?

**Comment by Jeffwan** [comment]
@ustcyue I've tried synthetic data. Absolute number is little bit higher. Actually scaling efficiency is close to 90% for 8 machines.  I have not checked more machines. 


1 | 875 | 1
-- | -- | --
8 | 6725 | 96%
16 | 12719 | 90.80%
32 | 25096 | 89.62%
64 | 49123 | 87.70%

**Comment by Sergei-Lebedev** [comment]
@Jeffwan It can be a problem with the network. What interconnect you use? I see from logs that NCCL tried to load ibverbs but failed.

**Comment by Jeffwan** [comment]
@Sergei-Lebedev I use 25Gbps network without IB support. It will use default eth0 instead. I think 25Gbps should be good enough for ResNet50 model?

**Comment by alsrgv** [comment]
@Jeffwan, 25GbE is not great for V100 GPUs.  In practice, you get the best performance with 2x100GbE with RDMA, and everything below that is a tradeoff.  AWS has p3dn GPU instances that come with 100GbE connectivity and may improve your scaling.

**Comment by Jeffwan** [comment]
@alsrgv Thanks. I will double check network peak traffic. I will close this issue now, if I have further questions, I will submit another one or reopen this.

**Comment by compete369** [comment]
@Jeffwan So how did you get the best performance? could you share your experience,  thanks very much!

**Comment by compete369** [comment]
@Jeffwan I see from your log, some rank to ran are NET/Socket/0 , and others IPC. how could you get that, I have same env with you. 

when I set map-by= slot, it says The specified mapping policy is not recognized:    Policy: slot.

**Comment by alsrgv** [comment]
@compete369, can you upgrade your OpenMPI?

**Comment by Jeffwan** [comment]
@compete369 As Alex said, please upgrade your OpenMPI. I would suggest to you to use pre-built container image and bring your model.
