### ISSUE TITLE
TypeError: Object of Type  'DirectoryIterator' has no len()?

### ISSUE THREAD

**Issue by jiangzihanict** [horovod/horovod#874]
When I was running keras_imagenet_resnet50.py example, I found the following error. But in the source code,  len() is a function of object Iterator that inherited by DirectoryIterator.  My tensorflow version is 1.2.0 and keras is 2.0.5

traceback (most recent call last):
  File "keras_imagenet_resnet50.py", line 167, in <module>
    steps_per_epoch=len(train_iter) // hvd.size(),
TypeError: object of type 'DirectoryIterator' has no len()

Command Line:  
mpirun --np 2 -H localhost:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python2.7 keras_imagenet_resnet50.py --train-dir /home/jzh/work_space/tiny-imagenet-200/tr    ain --val-dir /home/jzh/work_space/tiny-imagenet-200/val

Dataset: https://tiny-imagenet.herokuapp.com/   which is raw JPEG image dataset in a standard structure.

**Comment by alsrgv** [comment]
@jiangzihanict, is it possible to upgrade to TF 1.12.0 and latest Keras?  Keras 2.0.5 and old TF may not work with examples.

**Comment by jiangzihanict** [comment]
@alsrgv Thanks！I can't upgrade, but there is another way to compute len().
