### ISSUE TITLE
Why in one node with 4 V100 GPU card, every GPU card run four mpi program

### ISSUE THREAD

**Issue by xajxiang** [horovod/horovod#877]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow
2. Framework version: 1.13.1
3. Horovod version: 0.16.0
4. MPI version: openmpi4.0.0
5. CUDA version: 10.0
6. NCCL version: 2.3.4
7. Python version: 3.6.5
8. OS and version: ubuntu 16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Please ask your question here.
1.  1 node with 4 v100 GPU card
2.  mpirun -np 4 --allow-run-as-root -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python tensorflow_mnist.py
3. block at launch mode parallel

unnormal thing below
![image](https://user-images.githubusercontent.com/37759620/53696651-29960680-3e04-11e9-8bfa-853a9fef24e6.png)
4.  why the same pid program run in all 4 cards?
5.  nccl deadlock in this situation

normal thing below (in another node with 4 P100 cards)
![image](https://user-images.githubusercontent.com/37759620/53696662-5b0ed200-3e04-11e9-949f-58010258aa14.png)

**Comment by abditag2** [comment]
Seems related to https://github.com/horovod/horovod/issues/876
@xajxiang did you pin each process to a unique GPU?
```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
```

**Comment by alsrgv** [comment]
Closing this issue as a duplicate.
