### ISSUE TITLE
Segmentation fault: running MXNet with Horovod on Ubuntu Linux 16.04

### ISSUE THREAD

**Issue by apeforest** [horovod/horovod#884]
**Environment:**
1. Framework: MXNet
2. Framework version: 1.4.0
3. Horovod version: 0.16.0
4. MPI version: 3.1.1
5. CUDA version: 9.2
6. NCCL version: 2.2.13
7. Python version: 3.5
8. OS and version: Linux Ubuntu 16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Bug report:**
When running Horovod with MXNet on Linux Ubuntu 16.04, there will be a segmentation fault.

**Comment by apeforest** [comment]
The rootcause of this issue is because the pip release of MXNet is built using GCC 4.8.4 and Horovod pip release is built using GCC 5.x. There is a function call from Horovod to MXNet using `std::function()` which has different function signature between [GCC 4.x](https://github.com/gcc-mirror/gcc/blob/gcc-4_8_4-release/libstdc++-v3/include/std/functional#L2069) and [GCC 5.x](https://github.com/gcc-mirror/gcc/blob/gcc-5_4_0-release/libstdc++-v3/include/std/functional#L1854). 

We are working to resolve this incompatibility. In the meanwhile, please build MXNet from source following this [guide](https://mxnet.incubator.apache.org/versions/master/install/build_from_source.html) to workaround the segmentation fault. Sorry for the inconvenience!

**Comment by yuxihu** [comment]
The fixes have been merged into MXNet and Horovod. Users can now use MXNet nightly build and Horovod master branch to avoid the GCC incompatibility issue.
