### ISSUE TITLE
Scaling efficiency is less than 70%  when we training on single server with 4 GPUs

### ISSUE THREAD

**Issue by Crystalrem** [horovod/horovod#889]
When we train resnet50 with imagenet on a server with a Tesla V100, the traing speed is  3.81 steps/s. But when we training with horovod on on the same server with 4 V100 GPUs, the training speed can only reach 2.62 steps/s. Our observe from the timeline is that horovod is not overlapping with backward propagation and some horovod cycle blocked the training process for more than 100ms. By the way, the batch size per card is 64 in both experiments.

We printed the timeline at the 200 step of each GPU, the json files is attached.
Would you give us some advice to improve the scaling efficiency?

**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: tensorflow-gpu 1.12.0
3. Horovod version: 0.16.0
4. MPI version: 3.1.2
5. CUDA version: 9.0
6. NCCL version: 2.2.13-1+cuda9.0
7. Python version: 3.5.2
8. OS and version: Ubuntu 16.04.4 LTS
[timelines.zip](https://github.com/horovod/horovod/files/2935509/timelines.zip)

9. PCIE: gen3  x16

**Comment by alsrgv** [comment]
@Crystalrem, can you provide Horovod timeline, and the output of `nvidia-smi topo -m`?  PCIE gen3 may be an issue here.

@ustcyue has [recently found](https://github.com/horovod/horovod/issues/582#issuecomment-471860721) that it's better to use nvprof timeline to determine if communication/computation overlap is happening.
