### ISSUE TITLE
Pip3 install error for Horovod 0.16.0 with intel compilers

### ISSUE THREAD

**Issue by casparvl** [horovod/horovod#894]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.13.1
3. Horovod version: 0.16.0
4. MPI version: 2018.3.222
5. CUDA version: 10.0.130
6. NCCL version: 2.3.5
7. Python version: 3.6.6
8. OS and version: RedHatEnterpriseServer 7.5
9. Compilers: icc version 2018.3.222

**Bug report:**
Running 

`pip3 install horovod`

fails on the setup.py install:

```
Running setup.py install for horovod ... error
...

    In file included from horovod/common/timeline.cc(22):
    horovod/common/timeline.h(60): error: namespace "std" has no member "atomic_bool"
        std::atomic_bool healthy_{false};
             ^
    
    compilation aborted for horovod/common/timeline.cc (code 2)
    INFO: Unable to build TensorFlow plugin, will skip it.
```

I have noticed that timeline.h does not have an 
```
#include <atomic>
```
include. I downloaded the Horovod source code, added this include to horovod/common/timeline.h, tarred it again and then installed with

```
pip3 install horovod-0.16.0.tar.gz
```
Installation then completes without errors.

**Suggested solution:**
Add `#include <atomic>` to `horovod/common/timeline.h`.

**Comment by tgaddair** [comment]
Hey @casparvl, thanks for raising this issue.  Let me know if #901 fully addresses the compilation issues you were experiencing.
