### ISSUE TITLE
mxnet+hvd with different random seed won't work with Gluon API

### ISSUE THREAD

**Issue by eric-haibin-lin** [horovod/horovod#895]
**Environment:**
1. Framework: (MXNet)
2. Framework version: 1.4
3. Horovod version: v0.16.0 
4. MPI version: 
5. CUDA version:
6. NCCL version:
7. Python version: 2.7/3.6
8. OS and version: 

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.

If the shape of a parameter has to be inferred after a batch of data is seen, the parameter will not be broadcast. Therefore, the correctness of the program depends on whether all workers are initialized with the same random seed. So the following program will not work:

```
random.seed(hvd.local_rank())
data = ..
model = mx.gluon.nn.Dense(10)
model.initialize()

// no parameters are broadcast, because initialization is deferred.
hvd.broadcast_parameters(model.collect_parameters())

for batch in data:
    // params are initialized after shape is known
    pred = model(batch.data[0])
    ...
...
```

**Comment by yuxihu** [comment]
@eric-haibin-lin append "using Gluon API" in the title to avoid confusion?

**Comment by eric-haibin-lin** [comment]
Added. Thanks
