### ISSUE TITLE
horovod with nccl2 and rdma on mellanox 100Gb device not work

### ISSUE THREAD

**Issue by kinglion811** [horovod/horovod#897]
**Environment:**
1. Framework: tenworflow
2. Framework version:  1.9
3. Horovod version:  0.11.0
5. CUDA version: 9.2
6. NCCL version: ncc2
7. Python version: python3
8. OS and version: ubuntu 16.04

I have some v100 gpu machines (host1 host2 host3 host4), using the mellanox 100Gb NIC, host1 and host2 are on the same switch (switch1), host3 and host4 are on the other switch (switch2), and switch1 and switch2 are connected through switch3. I use rdma and nccl2 to run horovod-tensorflow tasks on host1 and host2. It works fine, but running on host2 and host3 can't work properly. What is causing this problem?
  -x HOROVOD_MPI_THREADS_DISABLE=1 \
               -x NCCL_IB_CUDA_SUPPORT=1 \
               -x NCCL_IB_GID_INDEX=3
I have added these parameters at runtime。

**Comment by alsrgv** [comment]
@kinglion811, could you provide logs when things aren't working and specify the version of NCCL?

**Comment by kinglion811** [comment]
@alsrgv  it's ok,that my error,thanks
