### ISSUE TITLE
                          │tensorflow.python.framework.errors_impl.NotFoundError: /home/pat/.virtualenvs/venv/lib/python3.6/site-packag         training = mp.Process(target=train)                                                        │es/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow14kernel_fac         measuring = mp.Process(target=measure)                                                     │tory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFacto                                                                                                    │ryESt14default_deleteIS8_EE

### ISSUE THREAD

**Issue by pstefanou12** [horovod/horovod#898]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Please ask your question here.

tensorflow.python.framework.errors_impl.NotFoundError: /home/pat/.virtualenvs/venv/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow14kernel_fac                          tory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

I'm not sure what the error is. Can anyone please help me?

**Comment by jiangzihanict** [comment]
Maybe the version of TF is not compatible with Horovod?

**Comment by alsrgv** [comment]
@pstefanou12, sorry for the delayed response.  Can you try reinstalling Horovod using `pip uninstall -y horovod` and `[flags] pip install --no-cache-dir horovod`?
