### ISSUE TITLE
multi code may be slow , how to modify 

### ISSUE THREAD

**Issue by vangogh0318** [horovod/horovod#900]
**Environment:**
1. Framework: TensorFlow
2. Framework version:  tf 1.11
3. Horovod version:  0.15.2
4. MPI version:  mpirun.real (OpenRTE) 3.1.2
5. CUDA version: cuda 9.0
6. NCCL version: master
7. Python version:  3.6.7
8. OS and version: Ubuntu 16.04.5 LTS
9. GPU=V100
10. batch_size=128

**Checklist:**
1. Did you search issues to find if somebody asked this question before?  yes

**Your question:**

The bert code is modified using horovod(my code is run_pretraining_hvd.py ,  according to https://github.com/lambdal/bert.git). However, it was found that linear acceleration was not achieved. BERT model's size is 470M, Network bandwidth  20G.

Single machine 1 card ：
INFO:tensorflow:global_step/sec: 1.71161

Single machine 4 card
INFO:tensorflow:global_step/sec: 1.17172

Multi-machine 8 card
INFO:tensorflow:global_step/sec: 0.655329

(4 card) / (1 card) = 4 * 1.172/(1.711) = 2.74
(8 card) / (1 card) = 8 * 0.655/(1.711) = 3.06
(8 card) / (4 card) = 8 * 0.655/(4*1.172) = 1.11

It can be seen that when there are Multi-machine 8 cards, the acceleration is not good.

my quesiton is how to modify the code to decrease training time？ 

here is bert_config.json,  my log and timeline. thanks

bert_config
{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 3,
  "type_vocab_size": 2,
  "vocab_size": 21128
}

[timeline_gpu8.zip](https://github.com/horovod/horovod/files/2952055/timeline_gpu8.zip)
[20190311.m1.gpu1.b128.layer6.iter1w.nocheckpoint.log](https://github.com/horovod/horovod/files/2952102/20190311.m1.gpu1.b128.layer6.iter1w.nocheckpoint.log)
[20190311.m2.gpu8.b128.layer6.iter1w.nocheckpoint.log](https://github.com/horovod/horovod/files/2952103/20190311.m2.gpu8.b128.layer6.iter1w.nocheckpoint.log)
[20190311.m1.gpu4.b128.layer6.iter1w.nocheckpoint.log](https://github.com/horovod/horovod/files/2952104/20190311.m1.gpu4.b128.layer6.iter1w.nocheckpoint.log)

**Comment by alsrgv** [comment]
Assigned to @abditag2 and @tgaddair, they're looking at BERT model.

**Comment by vangogh0318** [comment]
> Assigned to @abditag2 and @tgaddair, they're looking at BERT model.

here is code: https://github.com/lambdal/bert.git
I modified like that

**Comment by vangogh0318** [comment]
> Assigned to @abditag2 and @tgaddair, they're looking at BERT model.

@abditag2  @tgaddair  help, thanks

**Comment by abditag2** [comment]
@vangogh0318 Can you run the training for more epochs and see if the speed increases? I tried on our cluster and were able to get better number than yours. Let me know how it goes.

**Comment by zira-wang** [comment]
> > Assigned to @abditag2 and @tgaddair, they're looking at BERT model.
> 
> @abditag2 @tgaddair help, thanks

i have same question. Have you solved this problem yet?

**Comment by Shirlly** [comment]
Hi, I have got the same problem as well.  Have you got any solutions?

**Comment by zouweidong91** [comment]
@vangogh0318  Hi, do you fix this issue? I have the same problem when run on multi nodes.

**Comment by tgaddair** [comment]
Hey @zouweidong91, are you also attempting to train a BERT model?  Can you share a timeline file for your script?

**Comment by zouweidong91** [comment]
> Hey @zouweidong91, are you also attempting to train a BERT model? Can you share a timeline file for your script?

Sorry for the late reply.  My training model is pegassu which is for text-summarization. For me ,the bottleneck is bandwidth. The previous bandwidth is very low, only  934 Mbits/sec. The train test
```
Two nodes 16 card
examples/sec: 2.06896 
```

Now the bandwidth  9.40 Gbits/sec. the training speed :
```
Two nodes 16 card
examples/sec: 9.06896
```
Meanwhile when open  AUTOMATIC MIXED PRECISION and XLA:
```
Two nodes 16 card
examples/sec: 17.6534
```

Now everything looks fine. Thank you very much.
