### ISSUE TITLE
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python 

### ISSUE THREAD

**Issue by lakshmiumenon** [horovod/horovod#903]
**Environment:**
1. Framework: Keras
2. Framework version:1.0.5
3. Horovod version:0.16.0
4. Python version:3.6

I was trying to run keras_spark_rossmann.py.
 Installed java jdk1.8.0_201 and set JAVA_HOME. Py4j  updated to the latest version 0.10.8.1.
Attached the error trace.

[keras_spark_error.txt](https://github.com/horovod/horovod/files/2955333/keras_spark_error.txt)

**Comment by alsrgv** [comment]
@lakshmiumenon, could you paste the log with full output?  The most interesting part is likely before `[1,0]<stderr>:2019-03-11 22:50:41.975079: F ./tensorflow/core/common_runtime/bfc_allocator.h:298] Could not find Region for 0x7fcc3c0130f0`.

**Comment by lakshmiumenon** [comment]
@alsrgv 
[keras_spark_error.txt](https://github.com/horovod/horovod/files/2959968/keras_spark_error.txt)


Attached the updated log.

**Comment by alsrgv** [comment]
@lakshmiumenon, thanks for the updated log.  Which version of TensorFlow are you using?

**Comment by lakshmiumenon** [comment]
@alsrgv 
tensorflow 1.12.0

**Comment by alsrgv** [comment]
Sorry for delayed response.  How much RAM do you have on this server?  This message seems a bit odd:
```
2019-03-11 22:50:28 WARN  MemoryManager:115 - Total allocation exceeds 95.00% (949,826,343 bytes) of heap memory
```
