### ISSUE TITLE
Install horovod from source for tensorflow only

### ISSUE THREAD

**Issue by jw447** [horovod/horovod#909]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) TensorFlow
2. Framework version: r1.13
3. Horovod version: master
4. MPI version: Specturm MPI 10.2
5. CUDA version: 9.2
6. NCCL version: 2.2
7. Python version: 3.6
8. OS and version: Centos 7

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Please ask your question here.

I'm trying to build horovod for TensorFlow only with the command:
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/sw/summit/cuda/9.2.148 HOROVOD_WITHOUT_TENSORFLOW=0 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 python setup.py install

hoping to install horovod for TF only. However I'm getting the error as "error: TensorFlow, PyTorch, and MXNet plugins were excluded from build. Aborting.". I thought HOROVOD_WITHOUT_TENSORFLOW=0 means to use TensorFlow. Please correct me if I'm wrong.

**Comment by jw447** [comment]
I'm thinking there might be a bug for setup.py. I'm not sure if I'm the only one getting this error. I'm using the master branch of horovod and the function "build_extensions(self)" under class "custom_build_ext" is not working. 

I'm modifying the corresponding lines to show the error:
```
if not os.environ.get('HOROVOD_WITHOUT_TENSORFLOW'):
    #try:
    print("building for tensorflow")
    build_tf_extension(self, options)
    built_plugins.append(True)
    #print(built_plugins)
    # except:
           #     if not os.environ.get('HOROVOD_WITH_TENSORFLOW'):
           #         print('INFO: Unable to build TensorFlow plugin, will skip it.\n\n'
           #               '%s' % traceback.format_exc(), file=sys.stderr)
           #         built_plugins.append(False)
           #     else:
           #         raise
```
When I set the "HOROVOD_WITHOUT_TENSORFLOW" to be 0, which will make the if statement true, the function does NOT print. Since i hope to build for tensorflow only, I had to comment out the if-else and run the following lines directly.
```
build_tf_extension(self, options)
built_plugins.append(True)
```

Please let me know if I got anything wrong.

**Comment by tgaddair** [comment]
Hey @jw447, when you set the environment variable `HOROVOD_WITHOUT_TENSORFLOW` to `0`, you're actually setting it to the string value "0", which will evaluate to `True` in Python.

Instead, you should set `HOROVOD_WITH_TENSORFLOW=1`.

So your command line could be:

```
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/sw/summit/cuda/9.2.148 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 HOROVOD_WITHOUT_MXNET=1 python setup.py install
```

**Comment by jw447** [comment]
Oh, I see. Thank you so much.

**Comment by jw447** [comment]
@tgaddair Hi I'm trying to use advised command to install horovod. However I've got this error:
```
horovod/common/wire/message_generated.h:22:37: fatal error: flatbuffers/flatbuffers.h: No such file or directory
#include "flatbuffers/flatbuffers.h"
                                     ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```
Could you help me locate the error please?

**Comment by jw447** [comment]
This can be solved by "git clone https://github.com/horovod/horovod.git --recursive".
