### ISSUE TITLE
Scaling efficiency difference between Pytorch and Tensorflow

### ISSUE THREAD

**Issue by canopyPanda** [horovod/horovod#912]
**Environment:**
1. Framework: (TensorFlow, PyTorch)
2. Framework version: TensorFlow 1.11.0, PyTorch 1.0.1.post2
3. Horovod version:0.15.2
4. MPI version: (Open MPI) 4.0.0
5. CUDA version: cuda_9.0.176_384.81_linux.run
6. NCCL version:
7. Python version: 2.7
8. OS and version: unbuntu 16.04

**Your question:**
I run (tensorflow/pytorch)_synthetic_benchmark.py using horovod in a machine with two Titan Xp.
Why the scaling efficiency is so different between them?

Pytorch：（1GPU 217.2img/s）
![image](https://user-images.githubusercontent.com/18417400/54343255-5f938000-4679-11e9-974a-3bd20e58dccd.png)

Tensorflow：（1GPU 210.9img/s）
![image](https://user-images.githubusercontent.com/18417400/54343398-a5504880-4679-11e9-9b71-677a85f5f4fe.png)

If use VGG model， The difference between the two is greater.

**Comment by alsrgv** [comment]
@canopyPanda, that's odd - I get 94% scaling efficiency on pytorch_synthetic_benchmark.py on a system with similar GPUs.  Are you using NCCL?

**Comment by canopyPanda** [comment]
> @canopyPanda, that's odd - I get 94% scaling efficiency on pytorch_synthetic_benchmark.py on a system with similar GPUs. Are you using NCCL?

I didn't use NCCL when doing that test. So the the difference due to the lack of NCCL?
And why the tensorflow's scaling efficiency is better than pytorch?

**Comment by alsrgv** [comment]
@canopyPanda, any reason for not using NCCL?  Without it, we fall back to CPU allreduce and PyTorch fallback code path may be less optimized.
