### ISSUE TITLE
Running test_tensorflow.py on cpu nodes ERRNO=38

### ISSUE THREAD

**Issue by jiangzihanict** [horovod/horovod#923]
I  am running test_tensorflow.py on a CPU node for testing horovod installing, but I get the following error:
...
[anode84:04386] Read -1, expected 4912, errno = 38
[anode84:04384] Read -1, expected 4912, errno = 38
[anode84:04383] Read -1, expected 4914, errno = 38
[anode84:04385] Read -1, expected 4912, errno = 38
[anode84:04384] Read -1, expected 4914, errno = 38
[anode84:04383] Read -1, expected 4912, errno = 38
[anode84:04384] Read -1, expected 9824, errno = 38
[anode84:04386] Read -1, expected 9824, errno = 38
[anode84:04385] Read -1, expected 9828, errno = 38
[anode84:04383] Read -1, expected 9824, errno = 38
...

What does "erron=38" mean? And how can I fix it? I'd appreciate it if someone could help me.
Tensorflow version is 1.12 
Keras version is 2.2.4
OpenMPI version is 3.1.2
Python version is 3.6

My running command 

mpirun --allow-run-as-root -np 4     -H localhost:4     -bind-to none -map-by slot     -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH     -mca pml ob1 -mca btl ^openib     python3 test_tensorflow.py

**Comment by vmarkovtsev** [comment]
@jiangzihanict Why did you close this? I have the same problem.

**Comment by vmarkovtsev** [comment]
https://github.com/horovod/horovod/issues/566#issuecomment-430455575
