### ISSUE TITLE
GPU0 uses more memory?

### ISSUE THREAD

**Issue by hubutui** [horovod/horovod#934]
**Environment:**
1. Framework: PyTorch
2. Framework version: 1.0.1
3. Horovod version: 0.16.1
4. MPI version: 3.1.2
5. CUDA version: 10.0.130
6. NCCL version: 2.4.2
7. Python version: 3.6.8
8. OS and version: Ubuntu 16.04

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
 related to #242 , but not helpful.

**Your question:**
![image](https://user-images.githubusercontent.com/2948593/54606184-0fa42700-4a86-11e9-92c1-dfc8f09b5d19.png)
As the picture shows, gpu0 uses more memory. I could only run with `batch size = 3`, but I used to run with `batch size = 4` using `torch.nn.DataParallel`. I trying to migrate to horovod.

**Comment by tgaddair** [comment]
Hey @hubutui, does this happen when you run the standard benchmarks, like [pytorch_synthetic_benchmark.py](https://github.com/horovod/horovod/blob/master/examples/pytorch_synthetic_benchmark.py)?

**Comment by hubutui** [comment]
Thank you. I double check it. And I found that I have a pretrained model load as backbone but not used in my training model. It used extra memory.
