### ISSUE TITLE
How horovod integrate itself into tf distribute strategy?

### ISSUE THREAD

**Issue by zhouhaiy** [horovod/horovod#935]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
2. Framework version:
3. Horovod version:
4. MPI version:
5. CUDA version:
6. NCCL version:
7. Python version:
8. OS and version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Please ask your question here.

Hi,
I read from tensorflow design spec that horovod team is collobrating with tf team upon the HorovodDistributionStrategy. 
RFC: https://github.com/tensorflow/community/blob/master/rfcs/20181016-replicator.md#use-case-4-users-who-will-create-new-distributionstrategy-implementations

Can anyone share with us more details or more material about how to integrate horovod into d.s.? Because there's a lot of difference between them: e.g. launcher mode

Thanks!

**Comment by alsrgv** [comment]
@zhouhaiy, we're indeed collaborating with TensorFlow team on HorovodDistributionStrategy.  We don't have anything to try out yet, the plan is to have it ready before TF 2.0 comes out.  We'll keep this thread updated as we have more info to share.

**Comment by zhouhaiy** [comment]
@alsrgv Thanks for response. TF 2.0 alpha has already been released. I think TF 2.0 is coming...

**Comment by alsrgv** [comment]
It's not part of the 2.0 alpha release.

**Comment by Rong-Inspur** [comment]
@alsrgv Any update on this? Or any related documents can refer to? Thanks a lot!

**Comment by tgaddair** [comment]
Hey @Rong-Inspur, we're still investigating the best approach to integrate with Distribution Strategy, as it will require some changes to Horovod's internals to make it work.  

The Horovod steering committee will be meeting in January, and this will be one of the projects we look into for our 2020 roadmap, but no timelines or documents as of yet.

Let me know if this is something you're very interested in, as we're still gauging community interest in this feature.  (Note that Horovod does work with TensorFlow 2.0, just not with the Distribution Strategy API at this time).
