### ISSUE TITLE
broadcast optimizer state dict or not in PyTorch?

### ISSUE THREAD

**Issue by hubutui** [horovod/horovod#936]
Hey, I notice there is a minor difference in https://github.com/horovod/horovod/blob/master/examples/pytorch_synthetic_benchmark.py#L64, https://github.com/horovod/horovod/blob/master/examples/pytorch_imagenet_resnet50.py#L155, and https://github.com/horovod/horovod/blob/master/examples/pytorch_mnist.py#L94. Do I need to broadcast optimizer state dict or not?
Also, there's no API reference document?

**Comment by alsrgv** [comment]
@hubutui, good catch!  `hvd.broadcast_optimizer_state()` is useful when restoring from checkpoint, as it can broadcast optimizer state, such as momentums, from first rank to everyone else.  While it's not strictly necessary in either synthetic benchmark or mnist example, it's good to add.

**Comment by alsrgv** [comment]
We have a plan to build a doc website, but didn't get to it yet.  It will have an API reference.
