### ISSUE TITLE
Symbol not found: __ZN10tensorflow12OpDefBuilder3DocESs

### ISSUE THREAD

**Issue by zhenghh04** [horovod/horovod#939]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
TensorFlow

2. Framework version: 1.13.1
3. Horovod version: 0.16.1
4. MPI version: MPICH 3.3
5. CUDA version: Non
6. NCCL version: Non
7. Python version:3.6.5
8. OS and version: macOS Mojave 10.14.3

**Bug report:**
Horovod was built successfully. But try to run it as

$ python -c 'import horovod.tensorflow as hvd'
I got the following error: 

  File "<string>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 38, in <module>
    from horovod.tensorflow.mpi_ops import allgather, broadcast, _allreduce
  File "/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 59, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 46, in _load_library
    library = load_library.load_op_library(filename)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-darwin.so, 6): Symbol not found: __ZN10tensorflow12OpDefBuilder3DocESs
  Referenced from: /anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-darwin.so
  Expected in: flat namespace
 in /anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-darwin.so

=====
I suspect that it might be due to incompatibility between Tensorflow 1.13.1 and Horovod 0.16.1.

**Comment by alsrgv** [comment]
@zhenghh04, can you reinstall Horovod (`pip uninstall -y horovod`, `[flags] pip install --no-cache-dir horovod`) to make sure it's not using outdated binaries?

**Comment by abhimanyuchadha96** [comment]
I see the exact issue again @maxhgerlach

**Comment by abhimanyuchadha96** [comment]
![Screen Shot 2022-06-14 at 1 08 43 PM](https://user-images.githubusercontent.com/37940438/173636324-c8063abf-c8d7-4ff1-81b0-1d419c9708b3.png)

**Comment by maxhgerlach** [comment]
Can't be exactly the same issue as you certainly are not running on an environment equivalent to that described by OP. 🙂 

So please post exactly what you did to build Horovod and how your environment is set up.

**Comment by abhimanyuchadha96** [comment]
Oops, my bad.
Here it is: https://github.com/horovod/horovod/issues/3579
