### ISSUE TITLE
Best practice to run horovod using CPUs

### ISSUE THREAD

**Issue by jw447** [horovod/horovod#945]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet) Tensorflow
2. Framework version: v1.12
3. Horovod version: 0.10
4. MPI version: cray-mpich
5. CUDA version: none
6. NCCL version: none
7. Python version: 3.6
8. OS and version: centos

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Please ask your question here.

I'm trying to use multiple cores from multiple nodes to train horovod benchmark (tf_cnn_benchmarks). I'm wondering what is the best practice to deploy distributed training on multiple cores on a node and potentially on many nodes.

Rightnow, I'm using the following command on a single node

```
srun -n4 python ../tf_cnn_benchmarks.py \
    --model resnet50 --variable_update horovod \
    --horovod_device cpu --data_format=NHWC
```

However my questions are:

1. I'm specifying 4 workers to run the node, but I did not specify the number of CPUs to use by each worker. I also tried to add -c 8 to the command (each worker to use 8 CPUs) but I didn't see any performance gain. How should I leverage multi cores and multi processes which is the main power of the intel KNL node i'm using.

2. Is it the best practice to deploy the model or should I run 4 srun commands in the same time
```
srun -n1 python ... &
srun -n1 python ... &
srun -n1 python ... &
srun -n1 python ... &
wait
```

3. What difference does it make to use "--horovod_device" variable? Should I use this one or "--device cpu"

**Comment by alsrgv** [comment]
@jw447, I'd recommend using [MKL-enabled TensorFlow](https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide?page=1#pip_wheels).  TensorFlow has an internal mechanism to use many cores, so you generally can just launch one process per node.

**Comment by jw447** [comment]
I see. Thank you. I'm using MKL enabled TensorFlow already which I didn't make it clear in my previous post. I guess my question is about the performance of my CPU cluster. Right now I'm launching one process(worker) per node and the throughput is about 30 images/sec on 1 node and 70 images/sec on 2. Is it about right for CPU training?

**Comment by alsrgv** [comment]
@jw447,  unfortunately, I don't have reference points for CPU training performance.  You can also try running 2 processes per node to see if it makes things better or worse.

**Comment by jw447** [comment]
Thank you. Your help is sincerely appreciated!
