### ISSUE TITLE
In the run.py file,  the variable "envs" does not have a attribute "ENV_IGNORE"

### ISSUE THREAD

**Issue by memozhu** [horovod/horovod#950]
![image](https://user-images.githubusercontent.com/24536530/54912344-651b8080-4f2b-11e9-91fa-15d949f73843.png)

![image](https://user-images.githubusercontent.com/24536530/54912371-75cbf680-4f2b-11e9-9f6f-40da57b82c70.png)

![image](https://user-images.githubusercontent.com/24536530/54911665-ed008b00-4f29-11e9-993c-85975d954bba.png)

Maybe there is something wrong with the "env" variable name. How can I solve it?

**Comment by alsrgv** [comment]
@memozhu, looks like there was a name clash.  I've updated #949 with the fix.  Could you re-install and try again?
