### ISSUE TITLE
Fails when running Horovod over CDH 5.15.1 or HDP 3.1.0

### ISSUE THREAD

**Issue by dasight** [horovod/horovod#952]
**Environment:**
1. Framework: PySpark
2. Framework version: 2.3.2
3. Horovod version: 0.16.0 & 0.16.1
4. MPI version:3.1.2
5. CUDA version: N/A
6. NCCL version: N/A
7. Python version: 3.6
8. OS and version: CentOS 7.5

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
Searched, but no found.

2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
Including hang, but can not be solved with doc above.

3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?
Not about docker.

**Bug report:**
Please describe errorneous behavior you're observing and steps to reproduce it.
```
$ pyspark
[PySpark welcome message]

>>> def fn(magic_number):
...   import horovod.torch as hvd
...   hvd.init()
...   print('Hello, rank = %d, local_rank = %d, size = %d, local_size = %d, magic_number = %d' % (hvd.rank(), hvd.local_rank(), hvd.size(), hvd.local_size(), magic_number))
...   return hvd.rank()
...
>>> import horovod.spark
>>> horovod.spark.run(fn, args=(42,))
```
When I tried to run the code above in CDH 5.15.1 with Spark 2.3.2, the error message below is shown. The error message remains the same even after Open MPI is compiled with --enable-orterun-prefix-by-default.
```
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   john-cm
  target node:  john-cdhx-1

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
```
Meanwhile, as the code was ran in HDP 3.1.0, the PySpark job hangs in the stage below.
```
2019-03-25 09:10:11 INFO  DAGScheduler:54 - Submitting 2 missing tasks from ResultStage 0 (PythonRDD[1] at collect at /usr/miniconda3/lib/python3.6/site-packages/horovod/spark/__init__.py:71) (first 15 tasks are for partitions Vector(0, 1))
2019-03-25 09:10:11 INFO  TaskSchedulerImpl:54 - Adding task set 0.0 with 2 tasks
2019-03-25 09:10:11 INFO  TaskSetManager:54 - Starting task 0.0 in stage 0.0 (TID 0, localhost, executor driver, partition 0, PROCESS_LOCAL, 7839 bytes)
2019-03-25 09:10:11 INFO  TaskSetManager:54 - Starting task 1.0 in stage 0.0 (TID 1, localhost, executor driver, partition 1, PROCESS_LOCAL, 7839 bytes)
2019-03-25 09:10:11 INFO  Executor:54 - Running task 0.0 in stage 0.0 (TID 0)
2019-03-25 09:10:11 INFO  Executor:54 - Running task 1.0 in stage 0.0 (TID 1)
[Stage 0:>                                                          (0 + 2) / 2][1,0]<stdout>:Hello, rank = 0, local_rank = 0, size = 2, local_size = 2, magic_number = 42
[1,1]<stdout>:Hello, rank = 1, local_rank = 1, size = 2, local_size = 2, magic_number = 42
[Stage 0:>                                                          (0 + 2) / 2]
```
A related question:
Could you please tell about the Spark version that is recommended to run Horovod over PySpark in the current stage? Thanks.

**Comment by alsrgv** [comment]
@dasight, we had success with 2.3.x and 2.4.0, but prior versions may work as well.

To help debug, could you execute `horovod.spark.run()` with `verbose=2`?

**Comment by dasight** [comment]
Thanks, @alsrgv .Let me retries it with your recommendation.

Best regards,
- Zuling

**Comment by dasight** [comment]
Hi @alsrgv ,

Below is one of the additional output when I set verbose=2 in horovod.spark.run(). It seems that Horovod added a ramdom HEX number to the end of each hostname. Could you please show me how (in which code) Horovod get these hostnames?

Initial Spark task registration is complete.
Spark task-to-task address registration is complete.
+ mpirun --allow-run-as-root --tag-output -np 9 -H john-cdhx-3.gce.cloudera.com-**11aed9aa6c5cdabe73c81686492d16bc**:2,john-cdhx-1.gce.cloudera.com-**11aed9aa6c5cdabe73c81686492d16bc**:4,john-cdhx-2.gce.cloudera.com-**11aed9aa6c5cdabe73c81686492d16bc**:3 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_include eth0 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 -x XDG_SESSION_ID -x SPARK_HOME -x HOSTNAME -x TERM -x SHELL -x HISTSIZE -x HADOOP_HOME -x SSH_CLIENT -x QTDIR -x QTINC -x SSH_TTY -x LC_ALL -x SPARK_CONF_DIR -x QT_GRAPHICSSYSTEM_CHECKED -x SPARK_KAFKA_VERSION -x USER -x LD_LIBRARY_PATH -x LS_COLORS -x PYSPARK_PYTHON -x PYSPARK_DRIVER_PYTHON -x SPARK_PYTHON_PATH -x MAIL -x PATH -x PYTHONHASHSEED -x SELF -x TMP_PYSPARK_DRIVER_PYTHON -x HADOOP_COMMON_HOME -x PWD -x JAVA_HOME -x HADOOP_CONF_DIR -x LANG -x PYTHONSTARTUP -x PYLIB -x PYSPARK_ARCHIVES_PATH -x SPARK_ENV_LOADED -x TMP_PYSPARK_PYTHON -x HISTCONTROL -x M2_HOME -x SHLVL -x HOME -x SPARK_DIST_CLASSPATH -x OLD_PYTHONSTARTUP -x PYTHONPATH -x _SPARK_CMD_USAGE -x LOGNAME -x QTLIB -x lib -x SSH_CONNECTION -x LC_CTYPE -x LESSOPEN -x SPARK_EXTRA_LIB_PATH -x XDG_RUNTIME_DIR -x SPARK_SCALA_VERSION -x PYSPARK_SUBMIT_ARGS -x _HOROVOD_SECRET_KEY -mca plm_rsh_agent "/usr/miniconda3/bin/python -m horovod.spark.driver.mpirun_rsh gASVPgAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTWI2hpRhjARldGgwlF2UjA4xNzIuMzEuMTE0LjE3MpRNYjaGlGF1Lg==" /usr/miniconda3/bin/python -m horovod.spark.task.mpirun_exec_fn gASVPgAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTWI2hpRhjARldGgwlF2UjA4xNzIuMzEuMTE0LjE3MpRNYjaGlGF1Lg==

Best regards,
Zuling

**Comment by dasight** [comment]
Hi @alsrgv ,

Below is one of the additional output when I set verbose=2 in horovod.spark.run() in CDH 5.15.x. It seems that Horovod added a ramdom HEX number to the end of each hostname. Could you please show me how (in which code) Horovod get these hostnames? Maybe I can look into this issue with together you.

Initial Spark task registration is complete.
Spark task-to-task address registration is complete.
mpirun --allow-run-as-root --tag-output -np 9 -H john-cdhx-3.gce.cloudera.com-**11aed9aa6c5cdabe73c81686492d16bc**:2,john-cdhx-1.gce.cloudera.com-**11aed9aa6c5cdabe73c81686492d16bc**:4,john-cdhx-2.gce.cloudera.com-**11aed9aa6c5cdabe73c81686492d16bc**:3 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_include eth0 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 -x XDG_SESSION_ID -x SPARK_HOME -x HOSTNAME -x TERM -x SHELL -x HISTSIZE -x HADOOP_HOME -x SSH_CLIENT -x QTDIR -x QTINC -x SSH_TTY -x LC_ALL -x SPARK_CONF_DIR -x QT_GRAPHICSSYSTEM_CHECKED -x SPARK_KAFKA_VERSION -x USER -x LD_LIBRARY_PATH -x LS_COLORS -x PYSPARK_PYTHON -x PYSPARK_DRIVER_PYTHON -x SPARK_PYTHON_PATH -x MAIL -x PATH -x PYTHONHASHSEED -x SELF -x TMP_PYSPARK_DRIVER_PYTHON -x HADOOP_COMMON_HOME -x PWD -x JAVA_HOME -x HADOOP_CONF_DIR -x LANG -x PYTHONSTARTUP -x PYLIB -x PYSPARK_ARCHIVES_PATH -x SPARK_ENV_LOADED -x TMP_PYSPARK_PYTHON -x HISTCONTROL -x M2_HOME -x SHLVL -x HOME -x SPARK_DIST_CLASSPATH -x OLD_PYTHONSTARTUP -x PYTHONPATH -x _SPARK_CMD_USAGE -x LOGNAME -x QTLIB -x lib -x SSH_CONNECTION -x LC_CTYPE -x LESSOPEN -x SPARK_EXTRA_LIB_PATH -x XDG_RUNTIME_DIR -x SPARK_SCALA_VERSION -x PYSPARK_SUBMIT_ARGS -x _HOROVOD_SECRET_KEY -mca plm_rsh_agent "/usr/miniconda3/bin/python -m horovod.spark.driver.mpirun_rsh gASVPgAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTWI2hpRhjARldGgwlF2UjA4xNzIuMzEuMTE0LjE3MpRNYjaGlGF1Lg==" /usr/miniconda3/bin/python -m horovod.spark.task.mpirun_exec_fn gASVPgAAAAAAAAB9lCiMAmxvlF2UjAkxMjcuMC4wLjGUTWI2hpRhjARldGgwlF2UjA4xNzIuMzEuMTE0LjE3MpRNYjaGlGF1Lg==

Best regards,
Zuling

**Comment by alsrgv** [comment]
@dasight, the hostnames are generated using [this code](https://github.com/horovod/horovod/blob/f3b118629ff2770cb1485209e8fa46daf9eb6c9a/horovod/run/common/util/host_hash.py#L33), but these hostnames are purely virtual for Horovodrun purposes and are not used by the mpirun.

Can you make sure that you have the same version of MPI installed on all nodes, and both Python and MPI are installed in the same location everywhere?

**Comment by dasight** [comment]
@alsrgv Hi, I double checked just now, and can confirm that I have the same version of MPI installed on all nodes, and both Python and MPI are installed in the same location.

One more thing is that the Open MPI is compiled in one node and installed in other 3 nodes. I don't think that'll cause trouble, as I am using exactly the same instance type in GCE.

Is that possible for you to share the major steps of how your test environment are deployed? Including whether you are using an underlying HDFS?

Thanks!

**Comment by Qiuzhuang** [comment]
can you please check LD_LIBRARY_PATH/ldconfig to make sure .so are loaded?
I replicated open mpi build to other nodes as well and it looks good.

**Comment by dasight** [comment]
Hi @Qiuzhuang , I am totally okay to use horovodrun to directly in command line. But I don't find any extra .so path for Open MPI libraries in paths like /etc/ld.so.conf.d. Is there any extra configuration needed for Spark?

**Comment by alsrgv** [comment]
@dasight, we tested Horovod on Spark with Spark distribution that we use internally at Uber, and with a [standalone](https://spark.apache.org/docs/latest/spark-standalone.html) Spark 2.4.0 distribution.  We have not tested enterprise distributions like CDH or HDP.

In order to debug this further and dissect whether the issue is related to Horovod, CDH/HDP, or your environment, is it possible for you to install standalone Spark and try running Horovod over that Spark cluster?

**Comment by Qiuzhuang** [comment]
@dasight I add .so for hadoop when using pyarrow as follows:

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/cloudera/parcels/CDH/lib6

I test this in CDH 5.12/Spark 2.2/CUDA with example keras_spark.rossmann.py.

**Comment by dasight** [comment]
@alsrgv Okay. Let me see if I can find some time to do the test under Spark 2.4.x, standalone mode in community edition, today or tomorrow. If it turns out to be distribution specific, I wish we could co-work to fix this.

@Qiuzhuang Hi, I see a little difference between our environment, Spark 2.2 Vs. 2.3. Let me also try Spark 2.2 if I have extra time these days. Two further questions:
* Could you please tell me whether you are using CDH/SPARK or community edition?
* Could you please explain some reasons why you feel we should add Hadoop native library paths to the LD_LIBRARY_PATH? If you are considering to co-work with pyarrow, I roughly understand its necessity.

Thanks both of you,
- Zuling

**Comment by Qiuzhuang** [comment]
1. I use CHD community edition 5.12 with spark 2.2 from CDH. 
2. pyarrow need hadoop so file libhdfs.so. To be honest, when you just try horovod toy example, you don't need this.

Thanks.

**Comment by dasight** [comment]
@alsrgv Hi, I tried with Spark 2.3.2 community edition in standalone mode just now. However, the error message is almost the same. Is there any error-prone or special steps when you do the configuration?

Another thing I almost forget to mention is about adding the following configurations in spark-env.sh, and then install both horovod and pyspark 2.3.2 in Miniconda/Python. Shall I install the horovod package somewhere else like OS native Python?

export PYSPARK_PYTHON=/usr/miniconda3/bin/python
export PYSPARK_DRIVER_PYTHON=/usr/miniconda3/bin/python
export PYSPARK_PYTHON=/usr/miniconda3/bin/python
export PYSPARK_DRIVER_PYTHON=/usr/miniconda3/bin/python

Thanks.

**Comment by alsrgv** [comment]
@dasight, I just realized you're using Open MPI 3.1.2.  I bet you're hitting the bug #504.  Can you try upgrading the system to 4.0.0+?

**Comment by dasight** [comment]
Thanks @alsrgv . Let me go through #504 and try OpenMPI 4.0.0+ first.

Thanks.

**Comment by dasight** [comment]
Hi @alsrgv , I tried with Open MPI  4.0.1, however, it still fails with the same error message.
Is there any approach to show Open MPI functions call invoked, and the exact parameter passed into the functions?

Thanks.

**Comment by alsrgv** [comment]
@dasight, sorry for the delayed response.   I'm not sure what's causing CDH issue, but since the error message suggests to specify `-mca routed direct`, can you do this in your dockerfile (or on all VMs):
```
echo "routed = direct" >> /usr/local/etc/openmpi-mca-params.conf
```
?

Were you able to resolve the HDP hang issue?  If not, could you check if there are any errors in `dmesg` on any of the servers, and which processes are still running after you get the output?

**Comment by alsrgv** [comment]
@dasight @Qiuzhuang, we've discovered #1201 after an issue in our environment.  I believe once it lands, it may fix your issue.
