### ISSUE TITLE
I want to run my model on horovod, and get out of memory

### ISSUE THREAD

**Issue by solomatov** [horovod/horovod#953]
I want to run horovod on my model. Unfortunately, when I do so, the process dies with out of memory even in case when there's only one process. I tried reducing batch size to low values, it doesn't help. 

I use pytorch.

Could you give me some hints on how to debug it?

**Comment by alsrgv** [comment]
@solomatov, is it running out of CPU RAM of GPU memory?  How does the error message look like?

**Comment by solomatov** [comment]
It's running out of GPU memory. It's a CUDA message.

**Comment by alsrgv** [comment]
Could you check the output of `nvidia-smi` and make sure nothing is using GPU memory?

If you run a single process with Horovodrun, it should not consume much more memory than non-Horovod program, so making batch size smaller should have fixed the issue.

Thanks,
Alex
________________________________

**Comment by solomatov** [comment]
@alsrgv I run the same program and checked there was nothing in there. I will try again, later and write here. For now, I tried DistributedDataParallel from pytorch and it worked fine for me. AFAIU, horovod is better if I have many GPUs over infiniband, right?

**Comment by alsrgv** [comment]
@solomatov, not necessarily - Horovod works fine even with modest # of GPUs and over high-speed Ethernet. It can work better over low-speed Ethernet due to features like compression.

**Comment by echan00** [comment]
Does horovod band together memory from all the GPUs? Or is it mainly just multi-GPU distributed training?

**Comment by alsrgv** [comment]
@echan00, it's for multi-GPU distributed training.
