### ISSUE TITLE
slow on 3 gpus

### ISSUE THREAD

**Issue by Tangjiandd** [horovod/horovod#956]
**Your question:**
My code runs on three gpus is slower than just one gpu.
I spent 15 minutes running code with three gpus, but 3 minutes running code with only one gpu.

**Comment by alsrgv** [comment]
@Tangjiandd, does the whole training take 3 minutes on a single GPU?  Normally, you want to use distributed training if your training on a single GPU takes hours or days.

**Comment by Tangjiandd** [comment]
> @Tangjiandd, does the whole training take 3 minutes on a single GPU?  If that's the case, your model is likely too small and communication overhead far exceeds computational requirements.  Normally, you want to use distributed training if your training on a single GPU takes hours or days.

just 100 iterations spend 3 minutes. In general, this system may be run on 100,000 iterations, which may take about 3 days.

**Comment by alsrgv** [comment]
So it’s ~2 second per iteration? That sounds pretty good for distributed training. You mentioned you’re trying to scale the training to 3 GPUs, are they all in the same server, or spread across machines?

Thanks,
Alex
________________________________

**Comment by alsrgv** [comment]
@Tangjiandd, sounds pretty odd. What's CPU utilization during the run, is it possible that CPU is overstressed by running three processes instead of one?
