### ISSUE TITLE
Could I put multiple network models on single GPU with Horovod?

### ISSUE THREAD

**Issue by LeavesLei** [horovod/horovod#961]
Hi, @alsrgv I have used horovod with 4 GPUs. But the usage for every GPU is only about 30% because of my small network architecture.
-  I follow the examples that pin GPU to be used to process local rank **(one GPU per process)**.  
- Could I pin GPU so that **one GPU with multiple processes** with horovod to make full use of GPU?

**Comment by tsmolcic** [comment]
Similar question recently: #839

**Comment by alsrgv** [comment]
#839 is indeed a helpful way to solve this.  You can also take a look at [NVIDIA MPS](https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf) as it may help to spread the GPU compute resources across processes more evenly.
