### ISSUE TITLE
data files to run the horovod spark examples missing !

### ISSUE THREAD

**Issue by mohanraj1311** [horovod/horovod#962]
I was trying to run the horovod spark example, where can i find all the data files used by the example. The kaggle link doesnt have all the csv files: https://www.kaggle.com/c/rossmann-store-sales/data.

Where can i download all the data files ? Missing ones : weather.csv, store_states, state_names, googletrend.csv

**Comment by alsrgv** [comment]
@mohanraj1311, please see [this doc](https://github.com/horovod/horovod/blob/master/docs/spark.md#end-to-end-example) for instructions.

**Comment by mohanraj1311** [comment]
@alsrgv : i have already read the doc, it asks to get the data from kaggle page : https://www.kaggle.com/c/rossmann-store-sales/data.
The files used in the example are not present even in the kaggle data section. You can check that there only 4 files, rest of the files used by the script - weather.csv, store_states, state_names, googletrend.csv are MISSING

**Comment by alsrgv** [comment]
These files are coming from http://files.fast.ai/part2/lesson14/rossmann.tgz.

**Comment by mohanraj1311** [comment]
Thanks @alsrgv 👍
