### ISSUE TITLE
ModuleNotFoundError: No module named 'horovod.run'

### ISSUE THREAD

**Issue by XuesongYang** [horovod/horovod#970]
**Environment:**
1. Framework: Tensorflow
2. Framework version: 1.12
3. Horovod version: 0.16.1
4. MPI version: 3.1.0
5. CUDA version: 9.2
6. NCCL version:  2.2.13
7. Python version: 3.6.8
8. OS and version: aws ec2

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Please ask your question here.
I received the following errors. But the error is gone if I run `horovodrun --verbose -np 8 -H localhost:8 python tf_mnist_eager.py`

(tensorflow_p36) (6c61e111):~/workspace/test_horovod$ horovodrun --verbose -np 16 -H localhost:8,worker_ip_address:8 python tf_mnist_eager.py
Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Launching horovodrun task function was not successful:
~/anaconda3/envs/tensorflow_p36/bin/python: Error while finding module specification for 'horovod.run.task_fn' (ModuleNotFoundError: No module named 'horovod.run')

**Comment by alsrgv** [comment]
@XuesongYang, do you have Horovod installed on both machines? Is Anaconda environment installed in the same path on both machines?

**Comment by XuesongYang** [comment]
@alsrgv I double checked, and find the solution on that following the instruction: `https://github.com/awsdocs/aws-deep-learning-amis/blob/master/examples/horovod/tensorflow/train_synthetic.sh`

Actually, I need to activate the conda env first before mpirun as shown in the following:

`function runclust(){ while read -u 10 host; do host=${host%% slots*}; if [ ""$3"" == "verbose" ]; then echo "On $host"; fi; ssh -o "StrictHostKeyChecking no" $host ""$2""; done 10<$1; };`

`runclust hosts "echo 'Activating tensorflow_p36'; tmux new-session -s activation_tf -d \"source activate tensorflow_p36 > activation_log.txt;\"" verbose; `
