### ISSUE TITLE
Horovod runs when I ran on single node, but on multiple node it hangs

### ISSUE THREAD

**Issue by Nilesh-Agrawal** [horovod/horovod#975]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet):Pytorch
2. Framework version: 1.0.1.post2
3. Horovod version: 0.16.1
4. MPI version: 4.0.0
5. CUDA version: 10.0
6. NCCL version: 2.4.2
7. Python version: 3.5
8. OS and version: Ubuntu 16.0.4

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)? Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)? No

When I run command **mpirun -np 4 -H localhost:4 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python src-pytorch-dist/main.py** or by replacing **localhost** with hostname **server1**, it runs successfully,

But when I ran it on multiple node, or try to run on some other server server2, from server1 it hangs. Command which I ran from server1:
**mpirun -np 4 -H server2:4 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python src-pytorch-dist/main.py**

**mpirun -np 4 -H server1:2,server2:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python src-pytorch-dist/main.py**

I am able to ssh without password from server1 to server2, and can run command **ssh server2 ls** from server1 and gets appropriate output.

Please find strace log for command,
**mpirun -np 8 -H server1:4,server2:4 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python src-pytorch-dist/main.py**
[strace_log.txt](https://github.com/horovod/horovod/files/3031099/strace_log.txt)
**

**Comment by alsrgv** [comment]
@Nilesh-Agrawal, could you try `horovodrun --verbose -np 4 -H server1:2,server2:2 python src-pytorch-dist/main.py` and see if it helps?

**Comment by Nilesh-Agrawal** [comment]
This is the output I got after running above command.
_Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Notified all the hosts that the registration is complete.
Waiting for hosts to perform host-to-host interface checking._

**Comment by KimMeen** [comment]
Same issue and my console output was:

Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
Notified all the hosts that the registration is complete.
Waiting for hosts to perform host-to-host interface checking.
Launching horovodrun task function was not successful:
Traceback (most recent call last):
  File "/home/tpc1/.conda/envs/machine-learning/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tpc1/.conda/envs/machine-learning/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tpc1/.conda/envs/machine-learning/lib/python3.6/site-packages/horovod/run/task_fn.py", line 68, in <module>
    _task_fn(index, driver_addresses, num_hosts, tmout, key)
  File "/home/tpc1/.conda/envs/machine-learning/lib/python3.6/site-packages/horovod/run/task_fn.py", line 42, in _task_fn
    retries=10)
  File "/home/tpc1/.conda/envs/machine-learning/lib/python3.6/site-packages/horovod/run/task/task_service.py", line 72, in __init__
    retries=retries)
  File "/home/tpc1/.conda/envs/machine-learning/lib/python3.6/site-packages/horovod/run/common/service/task_service.py", line 133, in __init__
    retries=retries)
  File "/home/tpc1/.conda/envs/machine-learning/lib/python3.6/site-packages/horovod/run/common/util/network.py", line 165, in __init__
    % (service_name, addresses))
horovod.run.common.util.network.NoValidAddressesFound: Unable to connect to the horovodrun task service #1 on any of the addresses: {'lo': [('127.0.0.1', 19485)], 'eno1': [('192.168.1.1', 19485)]}

And ideas to figure it out?

**Comment by abditag2** [comment]
@KimMeen can you post the command that you are using to launch the tasks?

**Comment by KimMeen** [comment]
@abditag2 The command was: 

`horovodrun --verbose -np 2 -H localhost:1,tpc2:1 python lstm-ds-training.py`

Then it throws the error above. However, I am able to run this command in these two scenarios:

`horovodrun --verbose -np 1 -H localhost:1 python lstm-ds-training.py`
`horovodrun --verbose -np 1 -H tpc2:1 python lstm-ds-training.py`

So as I can see the failure occurs only when I trying to parallel the model in two machines. Any ideas to solve this problem? Thank you :D

**Comment by abditag2** [comment]
@KimMeen can you check if you can ssh from localhost to tpc2 and from tpc2 to your current localhost?

**Comment by alsrgv** [comment]
@KimMeen, @Nilesh-Agrawal, also, do you guys happen to have any firewall rules present on your systems that could prohibit cross-machine traffic on odd ports?

**Comment by KimMeen** [comment]
@abditag2 Yes I can, and currently I am using mpirun to do the distributed training like this:

`HOROVOD_TIMELINE='/mnt/data/project/Linux Distributed Version/imagenet_example/timeline.json' mpirun --allow-run-as-root --tag-output -np 2 -H localhost:1,tpc2:1 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib  -mca btl_tcp_if_exclude lo -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eno1,enp0s31f6 -x XDG_VTNR -x XDG_SESSION_ID -x XDG_GREETER_DATA_DIR -x CLUTTER_IM_MODULE -x SESSION -x GPG_AGENT_INFO -x TERM -x VTE_VERSION -x XDG_MENU_PREFIX -x SHELL -x CONDA_SHLVL -x QT_LINUX_ACCESSIBILITY_ALWAYS_ON -x CONDA_PROMPT_MODIFIER -x WINDOWID -x OLDPWD -x UPSTART_SESSION -x GNOME_KEYRING_CONTROL -x GTK_MODULES -x USER -x LS_COLORS -x QT_ACCESSIBILITY -x LD_LIBRARY_PATH -x CONDA_EXE -x UNITY_HAS_3D_SUPPORT -x XDG_SESSION_PATH -x XDG_SEAT_PATH -x SSH_AUTH_SOCK -x DEFAULTS_PATH -x XDG_CONFIG_DIRS -x UNITY_DEFAULT_PROFILE -x DESKTOP_SESSION -x PATH -x QT_IM_MODULE -x QT_QPA_PLATFORMTHEME -x CONDA_PREFIX -x XDG_SESSION_TYPE -x PWD -x JOB -x XMODIFIERS -x GNOME_KEYRING_PID -x LANG -x GDM_LANG -x MANDATORY_PATH -x COMPIZ_CONFIG_PROFILE -x IM_CONFIG_PHASE -x GDMSESSION -x SESSIONTYPE -x GTK2_MODULES -x SHLVL -x HOME -x XDG_SEAT -x LANGUAGE -x GNOME_DESKTOP_SESSION_ID -x UPSTART_INSTANCE -x CONDA_PYTHON_EXE -x UPSTART_EVENTS -x XDG_SESSION_DESKTOP -x LOGNAME -x COMPIZ_BIN_PATH -x DBUS_SESSION_BUS_ADDRESS -x XDG_DATA_DIRS -x QT4_IM_MODULE -x CONDA_DEFAULT_ENV -x LESSOPEN -x INSTANCE -x UPSTART_JOB -x XDG_RUNTIME_DIR -x DISPLAY -x XDG_CURRENT_DESKTOP -x GTK_IM_MODULE -x LESSCLOSE -x XAUTHORITY -x _ -x _HOROVOD_SECRET_KEY /mnt/environment/python '/mnt/data/project/Linux Distributed Version/imagenet_example/tensorflow_synthetic_benchmark.py' --model ResNet50 --batch-size 16`

Actually it works fine but when I tried to use `horovodrun` it will throw that error as before. @alsrgv So if there are some firewall rules I shouldn't be able to mpirun as well right?

**Comment by alsrgv** [comment]
@KimMeen, most likely firewall is not an issue then.  Can you share the output of `ifconfig -a` on both nodes?

**Comment by KimMeen** [comment]
@alsrgv, this is the output from tpc1:
```
enp0s31f6 Link encap:Ethernet  HWaddr d8:9e:f3:1d:e8:93  
          inet addr:192.168.1.12  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::4df5:ff34:7808:d59d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:351573129 errors:0 dropped:0 overruns:0 frame:0
          TX packets:350481717 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:367373204280 (367.3 GB)  TX bytes:366046020495 (366.0 GB)
          Interrupt:16 Memory:f7180000-f71a0000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2744827 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2744827 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:12984714086 (12.9 GB)  TX bytes:12984714086 (12.9 GB)
```
And this is the output from tpc2:
```
eno1      Link encap:Ethernet  HWaddr 00:d8:61:0c:cf:7a  
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::efc5:cea7:84a8:5fd6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:344563854 errors:0 dropped:0 overruns:0 frame:0
          TX packets:340479792 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:364836653967 (364.8 GB)  TX bytes:351786385973 (351.7 GB)
          Interrupt:16 Memory:a3300000-a3320000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:536754 errors:0 dropped:0 overruns:0 frame:0
          TX packets:536754 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:649973316 (649.9 MB)  TX bytes:649973316 (649.9 MB)
```

**Comment by alsrgv** [comment]
@KimMeen, we should make the error message better, but the root cause is that `horovodrun` currently requires all servers to have the same interface name.  Is there any reason it's not the case among your two servers?

**Comment by alsrgv** [comment]
@abditag2, we should experiment with adding a warning for interface name mismatches here - https://github.com/horovod/horovod/blob/master/horovod/run/common/util/network.py#L208

**Comment by KimMeen** [comment]
@alsrgv Thank you for taking a look at this problem! May I continue to use my `mpirun` command to do the experiment like I posted above? Since I guess `horovodrun` is a wrapper to simplify the `mpirun` command for users?

**Comment by alsrgv** [comment]
@KimMeen, sure - `mpirun` will be supported forever.

**Comment by Young768** [comment]
Did you guys find a solution for this issue? I met the same issue when distributing Horovod.

**Comment by KimMeen** [comment]
@Young768 Maybe you can try to launch the task via `mpirun` command directly, as I did above.

**Comment by alsrgv** [comment]
This is implemented in 0.16.2

**Comment by 652994331** [comment]
same probelm here,i read the information above, what did you guys mean: "should have same @alsrgv @KimMeen interface for two servers", could you please help me out? same, mpirun ok, but horovodrun not, i think horovodrun might have better training speed and performance than mpirun, am i right?
![image](https://user-images.githubusercontent.com/51428350/65358819-70382c00-dbaf-11e9-9341-ed44e72074f4.png)

**Comment by 652994331** [comment]
![image](https://user-images.githubusercontent.com/51428350/65358880-a4135180-dbaf-11e9-9f36-3f1986c0535e.png)

![image](https://user-images.githubusercontent.com/51428350/65358992-f5bbdc00-dbaf-11e9-8cc1-18c249878d14.png)
these are my results of command ifconfig -a
