### ISSUE TITLE
horovodrun – "There are not enough slots in the system"

### ISSUE THREAD

**Issue by radrow** [horovod/horovod#978]
When I run `horovodrun  -np 2 -H localhost python train.py` I get following error:
```
There are not enough slots available in the system to satisfy the 2 slots 
that were requested by the application:
  python

Either request fewer slots for your application, or make more slots available
for use.
```

With `mpirun` I could workaround it by providing custom hostfile or setting `--oversubscribe` flag. How can I deal with it using `horovodrun`?

**Comment by evgeniivas** [comment]
@radrow , you need set the number of gpu which can be used in localhost

try: horovodrun -np 2 -H localhost:2 python train.py

**Comment by radrow** [comment]
The solution was to append `:2` to `localhost` and update `mpirun`
