### ISSUE TITLE
Question on the description of the configuration of servers for benchmarks

### ISSUE THREAD

**Issue by eugene-vasilev** [horovod/horovod#979]
Hi! 
Is it possible to clarify the configuration of your servers on which benchmarks were held?
In the presentation (https://www.slideshare.net/AlexanderSergeev4/horovod-distributed-tensorflow-made-easy), only the GPU architecture and network bandwidth were specified. I would like to know the exact models of GPU's and processor, amount of RAM per server.

thanks in advance

**Comment by alsrgv** [comment]
@evgeniivas, I'm afraid that I can't share the exact spec of the servers we used.  I can share important ingredients for PCIx based Pascal servers:

1. Dual PCIx root.
2. 2 GPUs per CPU.
3. Reasonably fast CPU.  Take low-to-medium price in the lineup.
4. Populate all RAM channels.
5. Use RDMA if possible.
