### ISSUE TITLE
How to catch exceptions and restart training?

### ISSUE THREAD

**Issue by biswajitsc** [horovod/horovod#981]
**Environment:**
1. Framework: TensorFlow
2. Framework version: 1.12
3. Horovod version: 0.16.1
4. MPI version: 4.0.0
5. CUDA version: 9.0
6. NCCL version: 2.3.7
7. Python version: 3.6
8. OS and version: Ubuntu 18.04.1

**Checklist:**
1. Did you search issues to find if somebody asked this question before? Yes
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)? Yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)? Yes

**Your question:**
Please ask your question here.

I am using tensorflow Estimators and training on 4 GPUs. One of the processes throws a ResourceExhaustedError after few hours of training. Apparently tensorflow is not perfect at managing memory and a simple solution is to restart the code if you encounter such an error. I am precisely trying to do this.

Some issues with this solution:
ResourceExhaustedError on one of the processes results in UnknownError in the other processes. How can I make horovodrun detect that one of the processes has thrown a ResourceExhaustedError and restart the code?

An alternative to the above solution is to leave the other processes running, catch the ResourceExhaustedError in the problematic process and restart only that process. I have tried this, and this does not seem to work. All the processes simply stall.

Is there any way I could resolve this? Thanks.

**Comment by tgaddair** [comment]
Hey @biswajitsc, we're actively working on ways to make Horovod more resilient to failures like this, but in the meantime, what we typically do in practice is wrap the `horovodrun` call in a script that will retry when such failures occur.  For example, you would have a retry loop that retries up to some number of times when the return code is non-zero.  Then in your training script you would read the last checkpoint from disk to resume training.

**Comment by biswajitsc** [comment]
Thank you for the solution (although hacky :) ). This will work for now. Closing this issue.
