### ISSUE TITLE
Distributed only CPUs

### ISSUE THREAD

**Issue by aitgana** [horovod/horovod#987]
Hello, thank you for your work, it helps me enormously.
I just wanted to know if it was possible to use Horovod distributed with a cluster (I'm working on Slurm cluster) but using only the CPUs nodes.
And if so, give me an example. Thank you so much.

**Comment by abditag2** [comment]
If your question is whether horovod can run with only CPU nodes, the answer is yes, you can. if you install `pip install horovod` and install a non-gpu version of tensorflow, horovod will only use CPU.

**Comment by aitgana** [comment]
@abditag2  
I see, thank you!
Would you have an example of a basic code? because I am new with distributed progamation, and even more with Keras

**Comment by abditag2** [comment]
Keep in mind, In general, CPU training is going to be very, very slow compared to GPU training. This isn't anything specific to Horovod, but just due to the cost of running the forward and backwards passes without GPUs.

Any of the examples can run with CPU only. For example, in https://github.com/horovod/horovod/blob/master/examples/tensorflow_mnist.py, remove the following lines. 

    config.gpu_options.allow_growth = True
    config.gpu_options.visible_device_list = str(hvd.local_rank())

If you have GPUs on your machine and do not want to use them set the environment variable `CUDA_VISIBLE_DEVICES=-1`. 

    CUDA_VISIBLE_DEVICES=-1 python examples/tensorflow_mnist.py

**Comment by Young768** [comment]
@abditag2 Hi Fardin. If we distribute Horovod with CPU only, will the MPI be responsible for performing the allreduce operation. Because we do not install NCCL library.

**Comment by abditag2** [comment]
yes.

**Comment by Young768** [comment]
@abditag2 Could you please help me classify which parts of code in the Horovod are responsible for doing these? I am also trying to get familiar with the codebase.

**Comment by abditag2** [comment]
Sure, in the operations.cc https://github.com/horovod/horovod/blob/73d860f2396321761e0f5ef6fe934130afd69094/horovod/common/operations.cc#L45 we use the environment flags to decide which framework will execute the allreduce/allgather/bcast operations. For each framework, there is a file that uses the APIs provided by that framework to perform the operation e.g., `ops/nccl_operations.h` and `ops/ddl_operations.h`. If none of NCCL and DDL are implemented, we use mpi to perform the operations.

**Comment by Young768** [comment]
@abditag2 Thanks Fardin!!!!! One more question. After we submit the job, for example, $ horovodrun -np 16 -H server1:4,server2:4,server3:4,server4:4 python train.py, these four servers will form the communication topology. Each will send the data to the neighboring server during the training. I want to know which parts of code are responsible for setting up the topology. I am quite interested in how they work.

**Comment by abditag2** [comment]
I would recommend reading this paper: https://arxiv.org/abs/1802.05799

**Comment by abditag2** [comment]
Generally, all the workers report to worker 0 when the tensors are ready to be reduced. Once there are enough tensors, worker 0 informs all the workers to start that operation (i.e. allreduce/allgather). The core of the operation is performed by the underlying framework. For example, if you are using MPI, we use ring allreduce between the workers to reduce the tensors.

**Comment by Young768** [comment]
@abditag2 Hi Fardin. Yep, I did read that paper before. I am looking into the detailed code to see how you implement the ring allreduce, for example, forming the communication topology. It seems that all the related codes are under horovod/horovod/common/...?

**Comment by alsrgv** [comment]
@Young768, in Horovod we mostly decide between hierarchical (NCCL + MPI) vs native (NCCL-only, MPI-only) strategies. Those operations can be found [here](https://github.com/horovod/horovod/tree/master/horovod/common/ops).  Under the hood, NCCL and MPI have their own way of building low-level topologies.  That code can be found on their GitHub pages: [NCCL](https://github.com/NVIDIA/nccl), [Open MPI](https://github.com/open-mpi/ompi).
