### ISSUE TITLE
How to run horovod in multiple servers with different ports?

### ISSUE THREAD

**Issue by gdfishhannah** [horovod/horovod#996]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
TensorFlow
2. Framework version:
1.12.0
3. Horovod version:
0.16.1
4. MPI version:
4.0.0
5. CUDA version:
9.0
6. NCCL version:
2.3.7
7. Python version:
3.5
8. OS and version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?

**Your question:**
Please ask your question here.
I am trying to run horovod in multiple containers on multiple servers throught different ports, but I can only find the way to run through one port.

I run this in the first container.
horovodrun -np 16 -H localhost:8,host01:8 python keras_mnist_advanced.py
or
mpirun --allow-run-as-root -np 4 -H host01:2,host02:2 --mca plm_rsh_args "-p 22339" --mca btl_tcp_if_include ens10f1 -x LD_LIBRARY_PATH python keras_mnist_advanced.py

Is there any way to assign different port to host01 and host02?

**Comment by zsk423200** [comment]
i also have the problem, i use yarn to schedule the dockers, and the ports are random, so the port can not be unified.

**Comment by alsrgv** [comment]
@zsk423200, which mechanism do you use to look up port given a hostname or a container name?  One way to do this would be to override `--mca plm_rsh_agent "/path/to/resolver.sh"` where `resolver.sh` would be a script that resolves hostname & port of a given container and calls ssh appropriately.

Additionally, you may want to look at [Horovod in Spark](https://github.com/horovod/horovod/blob/master/docs/spark.md) if you're able to run Spark cluster in your Yarn environment, as it solves these kind of issues automatically.

**Comment by gdfishhannah** [comment]
> @zsk423200, which mechanism do you use to look up port given a hostname or a container name? One way to do this would be to override `--mca plm_rsh_agent "/path/to/resolver.sh"` where `resolver.sh` would be a script that resolves hostname & port of a given container and calls ssh appropriately.
> 
> Additionally, you may want to look at [Horovod in Spark](https://github.com/horovod/horovod/blob/master/docs/spark.md) if you're able to run Spark cluster in your Yarn environment, as it solves these kind of issues automatically.

Hi @alsrgv, could you please give some example of the resolver.sh?

**Comment by alsrgv** [comment]
@gdfishhannah, apologies for the delay.  Here's an example:
```bash
#!/bin/bash

hostname=$1
shift
args=$*

# TODO: lookup port by hostname
port=12345
ssh -p "${port}" "${hostname}" "${args}"
```

**Comment by kyunggeun-lee** [comment]
> @zsk423200, which mechanism do you use to look up port given a hostname or a container name? One way to do this would be to override `--mca plm_rsh_agent "/path/to/resolver.sh"` where `resolver.sh` would be a script that resolves hostname & port of a given container and calls ssh appropriately.
> 
> Additionally, you may want to look at [Horovod in Spark](https://github.com/horovod/horovod/blob/master/docs/spark.md) if you're able to run Spark cluster in your Yarn environment, as it solves these kind of issues automatically.

Well, I tried this but didn't work. But `--mca plm_rsh_agent "sh /path/to/resolver.sh"` worked for me.

**Comment by Qiuzhuang** [comment]
> @gdfishhannah, apologies for the delay. Here's an example:
> 
> ```shell
> #!/bin/bash
> 
> hostname=$1
> shift
> args=$*
> 
> # TODO: lookup port by hostname
> port=12345
> ssh -p "${port}" "${hostname}" "${args}"
> ```

Hi Alex, 

So if I have three containers with ssh ports like host1:12345, host2:12346, host3:12347, then in this resolve.sh, we should have something like:

ssh -p 12345 host1
ssh -p 12346 host2
ssh -p 12347 host3

and execute command like this in the primary container,e.g. host1:12345?

horovodrun -np 16 -H host1:3,host2:3,host3:3 python keras_mnist_advanced.py --mca plm_rsh_agent "sh /path/to/resolver.sh"

Thanks,
Qiuzhuang

**Comment by Qiuzhuang** [comment]
All right, see this ticket #2377 which suggests using .ssh to fix this. See link:

https://linuxize.com/post/using-the-ssh-config-file/
